<?php

use Utopia\View;
use Appwrite\Database\Validator\Authorization;

$collection = $this->getParam('collection', null);
$db = $this->getParam('db', null);
$rules = $collection->getAttribute('rules', []);
$namespace = 'project-document';
$collections = [];
?>

<?php foreach($rules as $rule):
    $key = (isset($rule['key'])) ? $rule['key'] : '';
    $label = (isset($rule['label'])) ? $rule['label'] : '';
    $type = (isset($rule['type'])) ? $rule['type'] : '';
    $list = (isset($rule['list'])) ? $rule['list'] : false;
    $array = (isset($rule['array'])) ? $rule['array'] : false;
?>

    <?php if($type !== 'document' && $array): ?>

        <form class="margin-bottom-no"
            data-service="container.path"
            data-event="collection-child-<?php echo $this->escape($namespace.'.'.$key); ?>"
            data-scope="window.ls"
            data-success="reset">

            <input type="hidden" name="path" value="<?php echo $this->escape($namespace.'.'.$key); ?>" />
            <input type="hidden" name="type" value="append" />
            <input type="hidden" name="value" value="" />
        </form>

    <?php endif; ?>
    
    <?php if($type !== 'document'): ?>
        <?php continue; ?>
    <?php endif; ?>

    <?php foreach($list as $item):
        if($item === $collection->getId()) {
            continue; // Do not allow rec recrusion
        }

        Authorization::disable(); //TODO Try and avoid calling the DB from the template
        $childCollection = $db->getDocument($item, false);
        Authorization::reset();

        if(!$childCollection->getId()) {
            continue;
        }

        $collections[$childCollection->getId()] = $childCollection->getAttribute('name');
    ?>
        <form class="margin-bottom-no"
            data-service="container.path"
            data-event="collection-child-<?php echo $this->escape($namespace.'.'.$key); ?>-<?php echo $this->escape($childCollection->getId()); ?>"
            data-scope="window.ls"
            data-success="reset">

            <input type="hidden" name="path" value="<?php echo $this->escape($namespace.'.'.$key); ?>" />
            <input type="hidden" name="type" value="append" />
            
            <fieldset name="value" data-cast-to="object">                            
                <input name="$id" type="hidden" value="" />
                <input name="$collection" type="hidden" value="<?php echo $this->escape($childCollection->getId()); ?>" />
            </fieldset>
        </form>

        <script type="text/html" id="collection-<?php echo ($array) ? 'array-' : ''; ?><?php echo $this->escape($childCollection->getId()); ?>">
            <?php 

            $comp = new View(__DIR__.'/form.phtml');
                                        
            $comp
                ->setParam('collection', $childCollection)
                ->setParam('namespace', ($array) ? 'node' : $namespace.'.'.$key)
                ->setParam('key', $key)
                ->setParam('array', $array)
                ->setParam('parent', 0)
            ;

            echo $comp->render();
            ?>
        </script>
    <?php endforeach; ?>
<?php endforeach; ?>

<?php foreach($rules as $rule):
    $key = (isset($rule['key'])) ? $rule['key'] : '';
    $label = (isset($rule['label'])) ? $rule['label'] : '';
    $type = (isset($rule['type'])) ? $rule['type'] : '';
    $list = (isset($rule['list'])) ? $rule['list'] : false;
    $array = (isset($rule['array'])) ? $rule['array'] : false;

    if(!$array) {
        continue;
    }
?>
    <ul data-ls-loop="<?php echo $this->escape($namespace.'.'.$key); ?>" data-ls-as="xxx">
        <li>
            <form
                data-service="container.path"
                data-event="splice-<?php echo $this->escape($namespace.'.'.$key); ?>-{{$index}}"
                data-scope="window.ls"
                data-success="reset">

                <input type="hidden" name="path" value="<?php echo $this->escape($namespace.'.'.$key); ?>" />
                <input type="hidden" name="type" value="splice" />
                <input type="hidden" name="value" data-ls-bind="{{$index}}" />
            </form>
        </li>
    </ul>
<?php endforeach; ?>
<div
    data-service="database.getCollection"
    data-param-collection-id="{{router.params.collection}}"
    data-scope="sdk"
    data-event="load,database.updateCollection"
    data-name="project-collection">

    <div
        data-service="database.getDocument"
        data-param-collection-id="{{router.params.collection}}"
        data-param-document-id="{{router.params.id}}"
        data-scope="sdk"
        data-event="load,database.updateDocument"
        data-name="project-document"
        data-success="default">

        <div class="cover">
            <h1 class="zone xl margin-bottom-large">
                <a data-ls-attrs="href=/console/database/collection?id={{router.params.collection}}&project={{router.params.project}}" class="back text-size-small"><i class="icon-left-open"></i> <span data-ls-bind="{{project-collection.name}}">Collection</span></a>

                <br />

                <span data-ls-if="({{project-document.$id}})" data-ls-bind="Update Document">&nbsp;&nbsp;</span>
                <span data-ls-if="(!{{project-document.$id}})" data-ls-bind="New Document">&nbsp;&nbsp;</span>
            </h1>
        </div>

        <div data-ui-modal class="modal width-large box close" data-button-hide="on" data-open-event="open-json">
            <button type="button" class="close pull-end" data-ui-modal-close=""><i class="icon-cancel"></i></button>    
            
            <h2>JSON View</h2>

            <div class="margin-bottom">
                <input type="hidden" data-ls-bind="{{project-document}}" data-forms-code />
            </div>

            <button data-ui-modal-close="" type="button" class="reverse">Cancel</button>
        </div>

        <div class="zone xl margin-bottom-no">
            <ul class="phases clear" data-ui-phases data-selected="{{router.params.tab}}">
                <li data-state="/console/database/document?id={{router.params.id}}&collection={{router.params.collection}}&project={{router.params.project}}">
                    <h2>Update</h2>

                    <div class="row responsive margin-top-negative">
                        <div class="col span-8 margin-bottom">
                            <form
                                data-analytics-event="submit"
                                data-analytics-category="console"
                                data-analytics-label="Update Database Document"
                                data-service="{{|documentAction}}"
                                data-name="project-document"
                                data-scope="sdk"
                                data-event="submit"
                                data-success="alert,trigger{{|documentSuccess}}"
                                data-success-param-alert-text="Updated document successfully"
                                data-success-param-trigger-events="database.updateDocument"
                                data-success-param-redirect-url="/console/database/document?id={{serviceData.$id}}&collection={{router.params.collection}}&project={{router.params.project}}"
                                data-failure="alert"
                                data-failure-param-alert-text="Failed to update document"
                                data-failure-param-alert-classname="error">

                                <label>&nbsp;</label>

                                <div class="box">
                                    <?php if(empty($rules)): ?>
                                        <div class="margin-bottom-xl margin-top-xl margin-end margin-start text-align-center">
                                            <h4 class="text-fade text-size-small">No attribute rules added yet.<br /><br /><a data-ls-attrs="href=/console/database/collection/settings?id={{router.params.collection}}&project={{router.params.project}}">Update Collection</a></h4>
                                        </div>
                                    <?php else: ?>
                                        <?php

                                        $comp = new View(__DIR__.'/form.phtml');
                            
                                        $comp
                                            ->setParam('collection', $collection)
                                            ->setParam('collections', $collections)
                                            ->setParam('namespace', $namespace)
                                            ->setParam('key', 'data')
                                            ->setParam('parent', 1)
                                        ;

                                        echo $comp->render();
                                        ?>

                                        <div class="toggle margin-bottom" data-ls-ui-open>
                                            <i class="icon-plus pull-end margin-top-tiny"></i>
                                            <i class="icon-minus pull-end margin-top-tiny"></i>
                                            
                                            <h3 class="margin-bottom-large">Permissions</h3>
                                            
                                            <label for="collection-read">Read Access <span class="text-size-small">(<a data-ls-attrs="href={{env.HOME}}/docs/permissions" target="_blank">Learn more</a>)</span></label>
                                            <input type="hidden" id="collection-read" name="read" data-forms-tags data-cast-to="json" data-ls-bind="{{project-document.$permissions.read}}" placeholder="User ID, Team ID or Role" />
                                                            
                                            <label for="collection-write">Write Access <span class="text-size-small">(<a data-ls-attrs="href={{env.HOME}}/docs/permissions" target="_blank">Learn more</a>)</label>
                                            <input type="hidden" id="collection-write" name="write" data-forms-tags data-cast-to="json" data-ls-bind="{{project-collection.$permissions.write}}" placeholder="User ID, Team ID or Role" />
                                        </div>

                                        <button data-ls-if="({{project-document.$id}})">Update</button>
                                        <button data-ls-if="(!{{project-document.$id}})">Create</button>
                                    <?php endif; ?>
                                </div>

                            </form>
                        </div>
                        <div class="col span-4 sticky-top">

                            <div data-ls-if="({{project-document.$id}})">
                                <label>Document ID</label>
                                <div class="input-copy margin-bottom">
                                    <input type="text" autocomplete="off" placeholder="" data-ls-bind="{{project-document.$id}}" disabled data-forms-copy class="margin-bottom-no" />
                                </div>
                            </div>

                            <label>Collection ID</label>
                            <div class="input-copy margin-bottom">
                                <input type="text" autocomplete="off" placeholder="" data-ls-bind="{{project-collection.$id}}" disabled data-forms-copy class="margin-bottom-no" />
                            </div>

                            <ul class="margin-bottom-large text-fade text-size-small">
                                <li class="margin-bottom-small"><i class="icon-angle-circled-right margin-start-tiny margin-end-tiny"></i> <button data-ls-ui-trigger="open-json" class="link text-size-small">View as JSON</button></li>
                            </ul>

                            <div data-ls-if="({{project-document.$id}})">
                                <form name="database.deleteDocument" class="margin-bottom"
                                    data-analytics-event="submit"
                                    data-analytics-category="console"
                                    data-analytics-label="Delete Collection Document"
                                    data-service="database.deleteDocument"
                                    data-event="submit"
                                    data-param-collection-id="{{router.params.collection}}"
                                    data-param-document-id="{{project-document.$id}}"
                                    data-confirm="Are you sure you want to delete this document?"
                                    data-success="alert,trigger,redirect"
                                    data-success-param-alert-text="Document deleted successfully"
                                    data-success-param-trigger-events="database.deleteDocument"
                                    data-success-param-redirect-url="/console/database/collection?id={{router.params.collection}}&project={{router.params.project}}"
                                    data-failure="alert"
                                    data-failure-param-alert-text="Failed to delete collection"
                                    data-failure-param-alert-classname="error">

                                    <button type="submit" class="danger fill">Delete Document</button>
                                </form>
                            </div>
                        </div>
                    </div>
                </li>
                <li data-ls-if="{{project-document.$id}}" data-state="/console/database/document/activity?id={{router.params.id}}&collection={{router.params.collection}}&project={{router.params.project}}">
                    <h2>Activity</h2>
                </li>
            </ul>
        </div>
    </div>
</div>

<div data-ui-modal class="modal sticky-footer width-large box close" data-button-hide="on" data-open-event="open-file-serach" data-close-event="none">
    <button type="button" class="close pull-end" data-ui-modal-close=""><i class="icon-cancel"></i></button>    
    
    <h2>File Search</h2>
    
    <form class="search margin-bottom-large"
        data-service="storage.listFiles"
        data-event="submit"
        data-param-search="{{router.params.search}}"
        data-param-limit="<?php echo APP_PAGING_LIMIT; ?>"
        data-param-offset=""
        data-param-order-type="DESC"
        data-scope="sdk"
        data-name="project-files"
        data-success="state"
        data-success-param-state-keys="search,offset">
        <input name="search" id="searchFiles" type="search" autocomplete="off" placeholder="Search" class="margin-bottom-no" data-ls-bind="{{router.params.search}}">
    </form>

    <div
        data-service="storage.listFiles"
        data-event="load,storage.createFile,storage.updateFile,storage.deleteFile"
        data-param-search="{{router.params.search}}"
        data-param-limit="<?php echo APP_PAGING_LIMIT; ?>"
        data-param-offset="{{router.params.offset}}"
        data-param-order-type="DESC"
        data-scope="sdk"
        data-name="project-files">

        <div data-ls-if="0 == {{project-files.sum}}" class="margin-bottom">
            <h3 class="margin-bottom-small text-bold">No Files Found</h3>

            <p class="margin-bottom-no">Try a different search term.</p>
        </div>

        <div data-ls-if="0 != {{project-files.sum}}">
            <div>
                <table class="vertical">
                    <thead>
                        <tr>
                            <th width="40"></th>
                            <th width="40"></th>
                            <th>Filename</th>
                            <th width="100">Type</th>
                            <th width="100">Size</th>
                            <th width="80">Created</th>
                            <!-- <th width="30"></th> -->
                        </tr>
                    </thead>
                    <tbody data-ls-loop="project-files.files" data-ls-as="file">
                        <tr>
                            <td class="hide">
                                <input type="radio" name="selected" data-ls-attrs="value={{file.$id}}" data-ls-bind="{{search.selected}}" />
                            </td>
                            <td class="hide">
                                <img src="" data-ls-attrs="src=//{{env.DOMAIN}}/v1/storage/files/{{file.$id}}/preview?width=65&height=65&project={{router.params.project}}&mode=admin" class="pull-start avatar" width="30" height="30" loading="lazy" />
                            </td>
                            <td data-title="Name: " class="text-one-liner">
                                <span data-ls-bind="{{file.name}}" data-ls-attrs="title={{file.name}}" class="text-fade text-size-small"></span>
                            </td>
                            <td data-title="Type: ">
                                <span data-ls-bind="{{file.mimeType}}" class="text-fade text-size-small"></span>
                            </td>
                            <td data-title="Size: ">
                                <span class="text-fade text-size-small" data-ls-bind="{{file.sizeOriginal|humanFileSize}}"></span>
                            </td>
                            <td data-title="Created: ">
                                <span class="text-fade text-size-small" data-ls-bind="{{file.dateCreated|date-text}}"></span>
                            </td>
                            <!-- <td class="hide">
                                <a target="_blank" data-ls-attrs="href="><i class="icon-link-ext"></i></a>
                            </td> -->
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>

    <footer>
        <div class="clear text-align-center paging pull-end">
            <form
                data-service="storage.listFiles"
                data-event="submit"
                data-param-search="{{router.params.search}}"
                data-param-limit="<?php echo APP_PAGING_LIMIT; ?>"
                data-param-order-type="DESC"
                data-scope="sdk"
                data-name="project-files"
                data-success="state"
                data-success-param-state-keys="search,offset">
                <button name="offset" data-paging-back data-offset="{{router.params.offset}}" data-sum="{{project-files.sum}}" class="margin-end round small" aria-label="Back"><i class="icon-left-open"></i></button>
            </form>

            <span data-ls-bind="{{router.params.offset|pageCurrent}} / {{project-files.sum|pageTotal}}"></span>

            <form
                data-service="storage.listFiles"
                data-event="submit"
                data-param-search="{{router.params.search}}"
                data-param-limit="<?php echo APP_PAGING_LIMIT; ?>"
                data-param-order-type="DESC"
                data-scope="sdk"
                data-name="project-files"
                data-success="state"
                data-success-param-state-keys="search,offset">
                <button name="offset" data-paging-next data-offset="{{router.params.offset}}" data-sum="{{project-files.sum}}" class="margin-start round small" aria-label="Next"><i class="icon-right-open"></i></button>
            </form>
        </div>

        <form data-service="container.path"
            data-param-path="search.selected"
            data-param-type="assign"
            data-param-value="{{file.$id}}"
            data-success="trigger"
            data-success-param-trigger-events="modal-close"
            data-event="click"
            data-scope="window.ls">

            <input type="hidden" name="path" data-ls-bind="{{search.path}}" />
            <input type="hidden" name="type" value="assign" />
            <input type="hidden" name="value" data-ls-bind="{{search.selected}}" />

            <button data-ls-if="({{search.selected}})" type="button" class=""> &nbsp; Select &nbsp; </button> &nbsp; 
            <button data-ls-if="(!{{search.selected}})" type="button" class="" disabled> &nbsp; Select &nbsp; </button> &nbsp; 
        </form>
        <button data-ui-modal-close="" type="button" class="reverse">Cancel</button>
    </footer>
</div>