import coverDimensions from './cover-dimensions.json'

export type CoverImageDimensions = {
  width: number
  height: number
}

/**
 * Looks up the real pixel dimensions of a blog or changelog cover image so
 * og:image:width / og:image:height reflect the actual file instead of a
 * hardcoded 1200x630. The manifest is generated by
 * `bun run generate:cover-manifest`.
 *
 * Accepts a public path (`/images/blog/<slug>/cover.avif`) or an absolute URL.
 */
export function getCoverImageDimensions(
  coverPathOrUrl: string,
): CoverImageDimensions | undefined {
  let path = coverPathOrUrl
  if (/^https?:\/\//.test(path)) {
    try {
      path = new URL(path).pathname
    } catch {
      return undefined
    }
  }

  const value = (coverDimensions as Record<string, string>)[path]
  if (!value) return undefined

  const [width, height] = value.split('x').map(Number)
  if (!Number.isFinite(width) || !Number.isFinite(height)) return undefined
  return { width, height }
}
