<?php
$graph = $this->getParam('graph', false);
$usageStatsEnabled = $this->getParam('usageStatsEnabled',true);


$locale = $this->getParam("locale");
/** @var Utopia\Locale\Locale $locale */
?>

<div class="cover margin-bottom-small">
    <div class="zone xxl margin-bottom-xl margin-top-small">
        <h1 class="margin-bottom-small"
            data-service="projects.get"
            data-event="load,project.update,projects.createPlatform,projects.updatePlatform,projects.deletePlatform"
            data-name="console-project"
            data-param-project-id="{{router.params.project}}"
            data-scope="console">
            <span class="title" data-ls-bind="{{console-project.name}}">&nbsp;</span>&nbsp;&nbsp;
        </h1>

        <ul class="desktops-only margin-top-negative-small margin-bottom clear">
            <li class="pull-start margin-end margin-bottom-small"><a data-ls-attrs="href=/console/settings?project={{router.params.project}}" class="link-animation-enabled"><i class="icon-cog"></i> &nbsp;<?php echo $locale->getText('console.comps.header.menu-item-settings'); ?></a> &nbsp;&nbsp;</li>
            <li class="pull-start margin-end margin-bottom-small"><a data-ls-attrs="href=/console/keys?project={{router.params.project}}" class="link-animation-enabled"><i class="icon-key-inv"></i> &nbsp;<?php echo $locale->getText('console.comps.header.menu-item-keys'); ?></a> &nbsp;&nbsp;</li>
            <li class="pull-start margin-end margin-bottom-small"><a data-ls-attrs="href=/console/webhooks?project={{router.params.project}}" class="link-animation-enabled"><i class="icon-link"></i> &nbsp;<?php echo $locale->getText('console.comps.header.menu-item-webhooks'); ?></a> &nbsp;&nbsp;</li>
            <li class="pull-start margin-end margin-bottom-small"><a data-ls-attrs="href=/console/tasks?project={{router.params.project}}" class="link-animation-enabled"><i class="icon-clock"></i> &nbsp;<?php echo $locale->getText('console.comps.header.menu-item-tasks'); ?></a> &nbsp;&nbsp;</li>
        </ul>

        <div class="margin-bottom phones-only">&nbsp;</div>
    </div>
</div>

<div class="zone xxl margin-top-negative-xxxl">
    <div class="clear margin-bottom-small margin-top-negative">
        <?php if (!$graph && $usageStatsEnabled): ?>
            <div class="pull-end">

                <form class="margin-start-small inline" data-ls-if="{{usage.range}} !== '24h'"
                    data-analytics
                    data-analytics-event="click"
                    data-analytics-category="console"
                    data-analytics-label="Usage 24h"
                    data-service="projects.getUsage"
                    data-event="submit"
                    data-name="usage"
                    data-param-project-id="{{router.params.project}}"
                    data-param-range="24h"
                    data-scope="console">
                    <button class="tick"><?php echo $locale->getText('shared.graph.hours24'); ?></button>
                </form>

                <button class="tick margin-start-small" data-ls-if="{{usage.range}} === '24h'" disabled><?php echo $locale->getText('shared.graph.hours24'); ?></button>

                <form class="margin-start-small inline" data-ls-if="{{usage.range}} !== '30d'"
                    data-analytics
                    data-analytics-event="click"
                    data-analytics-category="console"
                    data-analytics-label="Usage 30d"
                    data-service="projects.getUsage"
                    data-event="submit"
                    data-name="usage"
                    data-param-project-id="{{router.params.project}}"
                    data-scope="console">
                    <button class="tick"><?php echo $locale->getText('shared.graph.days30'); ?></button>
                </form>

                <button class="tick margin-start-small" data-ls-if="{{usage.range}} === '30d'" disabled><?php echo $locale->getText('shared.graph.days30'); ?></button>

                <form class="margin-start-small inline" data-ls-if="{{usage.range}} !== '90d'"
                    data-analytics
                    data-analytics-event="click"
                    data-analytics-category="console"
                    data-analytics-label="Usage 90d"
                    data-service="projects.getUsage"
                    data-event="submit"
                    data-name="usage"
                    data-param-project-id="{{router.params.project}}"
                    data-param-range="90d"
                    data-scope="console">
                    <button class="tick"><?php echo $locale->getText('shared.graph.days90'); ?></button>
                </form>

                <button class="tick margin-start-small" data-ls-if="{{usage.range}} === '90d'" disabled><?php echo $locale->getText('shared.graph.days90'); ?></button>
            </div>
        <?php endif; ?>
    </div>
        <div
        data-service="projects.getUsage"
        data-event="load"
        data-scope="console"
        data-name="usage"
        data-param-project-id="{{router.params.project}}"
        data-param-range="30d">
            <?php if (!$graph && $usageStatsEnabled): ?>
            <div class="box dashboard">
                <div class="row responsive">
                    <div class="col span-9">
                        <div class="chart pull-end">
                            <input type="hidden" data-ls-bind="{{usage}}" data-forms-chart="Requests=usage.requests.data" />
                        </div>

                        <div class="chart-metric">
                            <div class="value margin-bottom-small"><span class="sum" data-ls-bind="{{usage.requests.total|statsTotal}}">N/A</span></div>
                            <div class="unit margin-start-no margin-bottom-small"><?php echo $locale->getText('console.home.index.stats-requests'); ?></div>
                        </div>
                    </div>
                    <div class="col span-3">
                        <div class="value margin-bottom-small">
                            <span class="sum" data-ls-bind="{{realtime.current|accessProject}}" data-default="0">0</span>
                        </div>
                        <div class="unit margin-start-no margin-bottom-small"><?php echo $locale->getText('console.home.index.stats-connections'); ?></div>
                        <div class="chart-bar margin-top-small margin-bottom-small" data-ls-attrs="data-history={{realtime.history|accessProject}}" data-forms-chart-bars="{{realtime.history|accessProject}}"></div>
                        <div class="text-fade-dark text-size-small"><?php echo $locale->getText('console.home.index.stats-connections-description'); ?></div>
                    </div>
                </div>
            </div>
            <?php endif; ?>
            <div class="box dashboard">
                <div class="row responsive">
                    <div class="col span-3">
                        <div class="value"><span class="sum" data-ls-bind="{{usage.documents.total|statsTotal}}" data-default="0">0</span></div>
                        <div class="margin-top-small"><b class="text-size-small unit"><?php echo $locale->getText('console.home.index.stats-documents'); ?></b></div>
                    </div>
                    <div class="col span-3">
                        <div class="value">
                            <span class="sum" data-ls-bind="{{usage.storage.total|humanFileSize}}" data-default="0">0</span>
                            <span data-ls-bind="{{usage.storage.total|humanFileUnit}}" class="text-size-small unit"></span>
                        </div>
                        <div class="margin-top-small"><b class="text-size-small unit"><?php echo $locale->getText('console.home.index.stats-storage'); ?></b></div>
                    </div>
                    <div class="col span-3">
                        <div class="value"><span class="sum" data-ls-bind="{{usage.users.total}}" data-default="0">0</span></div>
                        <div class="margin-top-small"><b class="text-size-small unit"><?php echo $locale->getText('console.home.index.stats-users'); ?></b></div>
                    </div>
                    <div class="col span-3">
                        <div class="value"><span class="sum" data-ls-bind="{{usage.functions.total|statsTotal}}" data-default="0">0</span></div>
                        <div class="margin-top-small"><b class="text-size-small unit"><?php echo $locale->getText('console.home.index.stats-executions'); ?></b></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="zone xl margin-top-xl clear" data-ls-if="({{console-project}})">
    <h2 class="margin-bottom"><?php echo $locale->getText('console.home.index.platforms-title'); ?></h2>

    <div class="box margin-bottom" data-ls-if="0 < {{console-project.platforms.length}} && undefined !== {{console-project.platforms}}">
        <ul data-ls-loop="console-project.platforms" data-ls-as="platform" class="list">
            <li class="clear">
                <div class="pull-end desktops-only">
                    <button data-ls-ui-trigger="platform-delete-{{platform.$id}}" class="reverse danger margin-end-small"><?php echo $locale->getText('shared.button-delete'); ?></button>
                    <button data-ls-ui-trigger="platform-update-{{platform.$id}}"><?php echo $locale->getText('shared.button-update'); ?></button>
                </div>


                <div data-ui-modal data-button-hide="on" data-open-event="platform-update-{{platform.$id}}">
                    <button type="button" class="close pull-end" data-ui-modal-close=""><i class="icon-cancel"></i></button>

                    <h1><?php echo $locale->getText('console.home.index.platforms-update-title'); ?></h1>

                    <div data-ls-template="template-{{platform.type}}-update" data-type="script"></div>
                </div>

                <form class="pull-end margin-end"
                    data-analytics
                    data-analytics-activity
                    data-analytics-event="submit"
                    data-analytics-category="console"
                    data-analytics-label="Delete Project Platform"
                    data-service="projects.deletePlatform"
                    data-scope="console"
                    data-event="platform-delete-{{platform.$id}}"
                    data-confirm="<?php echo $locale->getText('console.home.index.platforms-delete-confirm'); ?>"
                    data-success="alert,trigger"
                    data-success-param-alert-text="<?php echo $locale->getText('console.home.index.platforms-delete-success'); ?>"
                    data-success-param-trigger-events="projects.deletePlatform"
                    data-failure="alert"
                    data-failure-param-alert-text="<?php echo $locale->getText('console.home.index.platforms-delete-error'); ?>"
                    data-failure-param-alert-classname="error">
                    <input type="hidden" name="projectId" data-ls-bind="{{router.params.project}}" />
                    <input type="hidden" name="platformId" data-ls-bind="{{platform.$id}}" />
                </form>

                <div>
                    <div class="pull-start margin-end avatar-container">
                        <img src="" data-ls-attrs="src=/images/clients/{{platform.type}}.png?v=<?php echo APP_CACHE_BUSTER; ?>" alt="<?php echo $locale->getText('console.home.index.platforms-alt-platform'); ?>" class="avatar" loading="lazy" width="60" height="60" />
                        
                        <div data-ls-if="{{platform.type}} === 'flutter-ios'" class="corner">
                            <img src="" data-ls-attrs="src=/images/clients/flutter.png?v=<?php echo APP_CACHE_BUSTER; ?>" alt="<?php echo $locale->getText('console.home.index.platforms-alt-ios'); ?>" class="avatar xs" loading="lazy" width="30" height="30" />
                        </div>
                        
                        <div data-ls-if="{{platform.type}} === 'flutter-android'" class="corner">
                            <img src="" data-ls-attrs="src=/images/clients/flutter.png?v=<?php echo APP_CACHE_BUSTER; ?>" alt="<?php echo $locale->getText('console.home.index.platforms-alt-android'); ?>" class="avatar xs" loading="lazy" width="30" height="30" />
                        </div>

                        <div data-ls-if="{{platform.type}} === 'flutter-linux'" class="corner">
                            <img src="" data-ls-attrs="src=/images/clients/flutter.png?v=<?php echo APP_CACHE_BUSTER; ?>" alt="<?php echo $locale->getText('console.home.index.platforms-alt-linux'); ?>" class="avatar xs" loading="lazy" width="30" height="30" />
                        </div>

                        <div data-ls-if="{{platform.type}} === 'flutter-macos'" class="corner">
                            <img src="" data-ls-attrs="src=/images/clients/flutter.png?v=<?php echo APP_CACHE_BUSTER; ?>" alt="<?php echo $locale->getText('console.home.index.platforms-alt-macos'); ?>" class="avatar xs" loading="lazy" width="30" height="30" />
                        </div>

                        <div data-ls-if="{{platform.type}} === 'flutter-windows'" class="corner">
                            <img src="" data-ls-attrs="src=/images/clients/flutter.png?v=<?php echo APP_CACHE_BUSTER; ?>" alt="<?php echo $locale->getText('console.home.index.platforms-alt-windows'); ?>" class="avatar xs" loading="lazy" width="30" height="30" />
                        </div>
                    </div>
                    <span class="text-one-liner" data-ls-bind="{{platform.name}}"></span>
                </div>

                <p class="margin-bottom-no"><small data-ls-bind="{{platform.hostname}}{{platform.key}}"></small></p>

                <div class="phones-only-inline tablets-only-inline margin-top-small">
                    <button class="link" data-ls-ui-trigger="platform-update-{{platform.$id}}"><?php echo $locale->getText('shared.button-update'); ?></button>
                    <button class="link danger" data-ls-ui-trigger="platform-delete-{{platform.$id}}"><?php echo $locale->getText('shared.button-delete'); ?></button>
                </div>
            </li>
        </ul>
    </div>

    <div data-ls-if="(!{{console-project.platforms.length}})" class="box dashboard margin-bottom">
        <div class="margin-bottom-small margin-top-small margin-end margin-start">
            <h3 class="margin-bottom-small text-bold"><?php echo $locale->getText('console.home.index.platforms-no-platform-title'); ?></h3>

            <p class="margin-bottom-no"><?php echo $locale->getText('console.home.index.platforms-no-platform-description'); ?></p>
        </div>
    </div>

    <div class="pull-end desktops-only tablets-only">
        <a data-analytics
            data-analytics-event="click"
            data-analytics-category="console"
            data-analytics-label="API Keys Link"
            data-ls-attrs="href=/console/keys?project={{router.params.project}}"><?php echo $locale->getText('console.home.index.platforms-no-manage-api-keys'); ?></a>
    </div>

    <div class="drop-list pull-start" data-ls-ui-open="" data-button-aria="<?php echo $locale->getText('console.home.index.platforms-label-add'); ?>" data-button-text="<?php echo $locale->getText('console.home.index.platforms-button-add'); ?>" data-button-class="button" data-blur="1">
        <ul>
            <li>
                <div class="link web-new"><img src="/images/clients/web.png?v=<?php echo APP_CACHE_BUSTER; ?>" alt="<?php echo $locale->getText('console.home.index.platforms-web-alt'); ?>" class="avatar xxs margin-end-small" loading="lazy" /> <?php echo $locale->getText('console.home.index.platforms-web-name'); ?></div>
            </li>
            <li>
                <div class="link flutter-new"><img src="/images/clients/flutter.png?v=<?php echo APP_CACHE_BUSTER; ?>" alt="<?php echo $locale->getText('console.home.index.platforms-flutter-alt'); ?>" class="avatar xxs margin-end-small" loading="lazy" /> <?php echo $locale->getText('console.home.index.platforms-flutter-name'); ?> &nbsp;<span class="text-size-tiny">(<?php echo $locale->getText('shared.beta'); ?>)</span></div>
            </li>
            <li>
                <div class="link android-new"><img src="/images/clients/android.png?v=<?php echo APP_CACHE_BUSTER; ?>" alt="<?php echo $locale->getText('console.home.index.platforms-android-alt'); ?>" class="avatar xxs margin-end-small" loading="lazy" /> <?php echo $locale->getText('console.home.index.platforms-android-name'); ?></div>
            </li>
            <li class="disabled">
                <div class="link ios-new"><img src="/images/clients/ios.png?v=<?php echo APP_CACHE_BUSTER; ?>" alt="<?php echo $locale->getText('console.home.index.platforms-ios-alt'); ?>" class="avatar xxs margin-end-small" loading="lazy" /> <?php echo $locale->getText('console.home.index.platforms-ios-name'); ?> <span class="text-fade text-size-small">(<?php echo $locale->getText('shared.soon'); ?>)</span></div>
            </li>
            <li class="disabled">
                <div class="link unity-new"><img src="/images/clients/unity.png?v=<?php echo APP_CACHE_BUSTER; ?>" alt="<?php echo $locale->getText('console.home.index.platforms-unity-alt'); ?>" class="avatar xxs margin-end-small" loading="lazy" /> <?php echo $locale->getText('console.home.index.platforms-unity-name'); ?>  <span class="text-fade text-size-small">(<?php echo $locale->getText('shared.soon'); ?>)</span></div>
            </li>
        </ul>
    </div>
</div>

<div data-ui-modal class="modal box close" data-button-alias=".web-new">
    <button type="button" class="close pull-end" data-ui-modal-close=""><i class="icon-cancel"></i></button>

    <h1><?php echo $locale->getText('console.home.index.platforms-web-title'); ?></h1>

    <form
        data-analytics
        data-analytics-activity
        data-analytics-event="submit"
        data-analytics-category="console"
        data-analytics-label="Create Project Platform (Web)"
        data-service="projects.createPlatform"
        data-scope="console"
        data-event="submit"
        data-success="alert,trigger,reset"
        data-success-param-alert-text="<?php echo $locale->getText('console.home.index.platforms-web-create-success'); ?>"
        data-success-param-trigger-events="projects.createPlatform"
        data-failure="alert"
        data-failure-param-alert-text="<?php echo $locale->getText('console.home.index.platforms-web-create-error'); ?>"
        data-failure-param-alert-classname="error">

        <input type="hidden" name="projectId" data-ls-bind="{{router.params.project}}" />
        <input type="hidden" name="type" data-ls-bind="web" />

        <label for="name"><?php echo $locale->getText('shared.label-name'); ?> <span class="tooltip large" data-tooltip="<?php echo $locale->getText('console.home.index.platforms-tooltip-name'); ?>"><i class="icon-question"></i></span></label>
        <input type="text" class="full-width" name="name" required autocomplete="off" placeholder="<?php echo $locale->getText('console.home.index.platforms-placeholder-web-name'); ?>" maxlength="128" />

        <label for="hostname"><?php echo $locale->getText('console.home.index.platforms-label-hostname'); ?> <span class="tooltip large" data-tooltip="<?php echo $locale->getText('console.home.index.platforms-tooltip-hostname'); ?>"><i class="icon-question"></i></span></label>
        <input name="hostname" type="text" class="margin-bottom" autocomplete="off" placeholder="<?php echo $locale->getText('console.home.index.platforms-placeholder-web-hostname'); ?>" required>
        
        <div class="info margin-top margin-bottom">
            <div class="text-bold margin-bottom-small"><?php echo $locale->getText('console.home.index.platforms-web-create-next-steps-title'); ?></div>

            <p><?php echo $locale->getText('console.home.index.platforms-web-create-next-steps-description-chunk1'); ?> <a data-ls-attrs="href={{env.HOME}}/docs/getting-started-for-web" target="_blank" rel="noopener"><?php echo $locale->getText('console.home.index.platforms-web-create-next-steps-description-chunk2'); ?></a> <?php echo $locale->getText('console.home.index.platforms-web-create-next-steps-description-chunk3'); ?>.</p>

            <div class="margin-bottom-no ide" data-lang="bash" data-lang-label="bash">
                <pre class="line-numbers"><code class="prism language-bash" data-prism>npm install appwrite</code></pre>
            </div>
        </div>

        <button type="submit"><?php echo $locale->getText('console.home.index.platforms-create-button-submit'); ?></button> &nbsp; <button data-ui-modal-close="" type="button" class="reverse"><?php echo $locale->getText('console.home.index.platforms-web-create-error'); ?></button>
    </form>
</div>

<script type="text/html" id="template-web-update">
    <form
        data-analytics
        data-analytics-activity
        data-analytics-event="submit"
        data-analytics-category="console"
        data-analytics-label="Update Project Platform (Web)"
        data-service="projects.updatePlatform"
        data-scope="console"
        data-event="submit"
        data-success="alert,trigger"
        data-success-param-alert-text="<?php echo $locale->getText('console.home.index.platforms-update-success'); ?>"
        data-success-param-trigger-events="projects.updatePlatform"
        data-failure="alert"
        data-failure-param-alert-text="<?php echo $locale->getText('console.home.index.platforms-update-error'); ?>"
        data-failure-param-alert-classname="error">

        <input type="hidden" name="projectId" data-ls-bind="{{router.params.project}}" />
        <input type="hidden" name="platformId" data-ls-bind="{{platform.$id}}" />

        <label data-ls-attrs="for=name-{{platform.$id}}"><?php echo $locale->getText('shared.label-name'); ?> <span class="tooltip large" data-tooltip="<?php echo $locale->getText('console.home.index.platforms-tooltip-name'); ?>"><i class="icon-question"></i></span></label>
        <input type="text" class="full-width" data-ls-attrs="id=name-{{platform.$id}}" name="name" required autocomplete="off" data-ls-bind="{{platform.name}}" placeholder="<?php echo $locale->getText('console.home.index.platforms-placeholder-web-name'); ?>" maxlength="128" />

        <label for="hostname"><?php echo $locale->getText('console.home.index.platforms-label-hostname'); ?> <span class="tooltip large" data-tooltip="<?php echo $locale->getText('console.home.index.platforms-tooltip-hostname'); ?>"><i class="icon-question"></i></span></label>
        <input name="hostname" type="text" class="margin-bottom" autocomplete="off" placeholder="<?php echo $locale->getText('console.home.index.platforms-placeholder-web-hostname'); ?>" data-ls-bind="{{platform.hostname}}" required />
        
        <hr />

        <button type="submit"><?php echo $locale->getText('shared.button-update'); ?></button> &nbsp; <button data-ls-ui-trigger="modal-close" type="button" class="reverse"><?php echo $locale->getText('shared.cancel'); ?></button>
    </form>
</script>

<div data-ui-modal class="modal box close" data-button-alias=".android-new">
    <button type="button" class="close pull-end" data-ui-modal-close=""><i class="icon-cancel"></i></button>

    <h1><?php echo $locale->getText('console.home.index.platforms-android-title'); ?></h1>

    <form
        data-analytics
        data-analytics-activity
        data-analytics-event="submit"
        data-analytics-category="console"
        data-analytics-label="Create Project Platform (Android)"
        data-service="projects.createPlatform"
        data-scope="console"
        data-event="submit"
        data-success="alert,trigger,reset"
        data-success-param-alert-text="<?php echo $locale->getText('console.home.index.platforms-create-success'); ?>"
        data-success-param-trigger-events="projects.createPlatform"
        data-failure="alert"
        data-failure-param-alert-text="<?php echo $locale->getText('console.home.index.platforms-create-error'); ?>"
        data-failure-param-alert-classname="error">

        <input type="hidden" name="projectId" data-ls-bind="{{router.params.project}}" />
        <input type="hidden" name="type" data-ls-bind="android" />

        <label for="name"><?php echo $locale->getText('shared.label-name'); ?> <span class="tooltip large" data-tooltip="<?php echo $locale->getText('console.home.index.platforms-tooltip-name'); ?>"><i class="icon-question"></i></span></label>
        <input type="text" class="full-width" name="name" required autocomplete="off" placeholder="<?php echo $locale->getText('console.home.index.platforms-placeholder-android-name'); ?>" maxlength="128" />

        <label for="key"><?php echo $locale->getText('console.home.index.platforms-label-package-name'); ?> <span class="tooltip large" data-tooltip="<?php echo $locale->getText('console.home.index.platforms-tooltip-package-name'); ?>"><i class="icon-question"></i></span></label>
        <input type="text" class="full-width" name="key" required autocomplete="off" placeholder="<?php echo $locale->getText('console.home.index.platforms-placeholder-android-hostname'); ?>" />

        <hr />

        <button type="submit"><?php echo $locale->getText('console.home.index.platforms-create-button-submit'); ?></button> &nbsp; <button data-ui-modal-close="" type="button" class="reverse"><?php echo $locale->getText('shared.cancel'); ?></button>
    </form>
</div>

<div data-ui-modal class="modal box close width-large" data-button-alias=".flutter-new">
    <button type="button" class="close pull-end" data-ui-modal-close=""><i class="icon-cancel"></i></button>

    <h1 class="margin-bottom-xl"><?php echo $locale->getText('console.home.index.platforms-flutter-title'); ?></h1>

    <ul class="phases clear margin-top-negative-small padding" data-ui-phases>
        <li>
            <h2 style="display: none">&nbsp;&nbsp;<?php echo $locale->getText('console.home.index.platforms-flutter-ios-title'); ?>&nbsp;&nbsp;</h2>

            <form
                data-analytics
                data-analytics-activity
                data-analytics-event="submit"
                data-analytics-category="console"
                data-analytics-label="Create Project Platform (Flutter / iOS)"
                data-service="projects.createPlatform"
                data-scope="console"
                data-event="submit"
                data-success="alert,trigger,reset"
                data-success-param-alert-text="<?php echo $locale->getText('console.home.index.platforms-create-success'); ?>"
                data-success-param-trigger-events="projects.createPlatform"
                data-failure="alert"
                data-failure-param-alert-text="<?php echo $locale->getText('console.home.index.platforms-create-error'); ?>"
                data-failure-param-alert-classname="error">

                <input type="hidden" name="projectId" data-ls-bind="{{router.params.project}}" />
                <input type="hidden" name="type" data-ls-bind="flutter-ios" />

                <label for="name"><?php echo $locale->getText('shared.label-name'); ?> <span class="tooltip large" data-tooltip="<?php echo $locale->getText('console.home.index.platforms-tooltip-name'); ?>"><i class="icon-question"></i></span></label>
                <input type="text" class="full-width" name="name" required autocomplete="off" placeholder="<?php echo $locale->getText('console.home.index.platforms-placeholder-ios-name'); ?>" maxlength="128" />

                <label for="key"><?php echo $locale->getText('console.home.index.platforms-label-bundle-id'); ?> <span class="tooltip large" data-tooltip="<?php echo $locale->getText('console.home.index.platforms-tooltip-bundle-id'); ?>"><i class="icon-question"></i></span></label>
                <input type="text" class="full-width" name="key" required autocomplete="off" placeholder="<?php echo $locale->getText('console.home.index.platforms-placeholder-ios-hostname'); ?>" />

                <hr />

                <button type="submit"><?php echo $locale->getText('console.home.index.platforms-create-button-submit'); ?></button> &nbsp; <button data-ui-modal-close="" type="button" class="reverse"><?php echo $locale->getText('shared.cancel'); ?></button>
            </form>

        </li>
        <li>
            <h2 style="display: none">&nbsp;&nbsp;<?php echo $locale->getText('console.home.index.platforms-flutter-android-title'); ?>&nbsp;&nbsp;</h2>

            <form
                data-analytics
                data-analytics-activity
                data-analytics-event="submit"
                data-analytics-category="console"
                data-analytics-label="Create Project Platform (Flutter / Android)"
                data-service="projects.createPlatform"
                data-scope="console"
                data-event="submit"
                data-success="alert,trigger,reset"
                data-success-param-alert-text="<?php echo $locale->getText('console.home.index.platforms-create-success'); ?>"
                data-success-param-trigger-events="projects.createPlatform"
                data-failure="alert"
                data-failure-param-alert-text="<?php echo $locale->getText('console.home.index.platforms-create-error'); ?>"
                data-failure-param-alert-classname="error">

                <input type="hidden" name="projectId" data-ls-bind="{{router.params.project}}" />
                <input type="hidden" name="type" data-ls-bind="flutter-android" />

                <label for="name"><?php echo $locale->getText('shared.label-name'); ?> <span class="tooltip large" data-tooltip="<?php echo $locale->getText('console.home.index.platforms-tooltip-name'); ?>"><i class="icon-question"></i></span></label>
                <input type="text" class="full-width" name="name" required autocomplete="off" placeholder="<?php echo $locale->getText('console.home.index.platforms-placeholder-android-name'); ?>" maxlength="128" />

                <label for="key"><?php echo $locale->getText('console.home.index.platforms-label-package-name'); ?> <span class="tooltip large" data-tooltip="<?php echo $locale->getText('console.home.index.platforms-tooltip-package-name'); ?>"><i class="icon-question"></i></span></label>
                <input type="text" class="full-width" name="key" required autocomplete="off" placeholder="<?php echo $locale->getText('console.home.index.platforms-placeholder-android-hostname'); ?>" />

                <hr />

                <button type="submit"><?php echo $locale->getText('console.home.index.platforms-create-button-submit'); ?></button> &nbsp; <button data-ui-modal-close="" type="button" class="reverse"><?php echo $locale->getText('shared.cancel'); ?></button>
            </form>
        </li>
        <li>
            <h2 style="display: none">&nbsp;&nbsp;<?php echo $locale->getText('console.home.index.platforms-flutter-linux-title'); ?>&nbsp;&nbsp;</h2>

            <form
                data-analytics
                data-analytics-activity
                data-analytics-event="submit"
                data-analytics-category="console"
                data-analytics-label="Create Project Platform (Flutter / Linux)"
                data-service="projects.createPlatform"
                data-scope="console"
                data-event="submit"
                data-success="alert,trigger,reset"
                data-success-param-alert-text="<?php echo $locale->getText('console.home.index.platforms-create-success'); ?>"
                data-success-param-trigger-events="projects.createPlatform"
                data-failure="alert"
                data-failure-param-alert-text="<?php echo $locale->getText('console.home.index.platforms-create-error'); ?>"
                data-failure-param-alert-classname="error">

                <input type="hidden" name="projectId" data-ls-bind="{{router.params.project}}" />
                <input type="hidden" name="type" data-ls-bind="flutter-linux" />

                <label for="name"><?php echo $locale->getText('shared.label-name'); ?> <span class="tooltip large" data-tooltip="<?php echo $locale->getText('console.home.index.platforms-tooltip-name'); ?>"><i class="icon-question"></i></span></label>
                <input type="text" class="full-width" name="name" required autocomplete="off" placeholder="<?php echo $locale->getText('console.home.index.platforms-placeholder-linux-name'); ?>" maxlength="128" />

                <label for="key"><?php echo $locale->getText('console.home.index.platforms-label-package-name'); ?> <span class="tooltip large" data-tooltip="<?php echo $locale->getText('console.home.index.platforms-tooltip-package-name2'); ?>"><i class="icon-question"></i></span></label>
                <input type="text" class="full-width" name="key" required autocomplete="off" placeholder="<?php echo $locale->getText('console.home.index.platforms-placeholder-linux-hostname'); ?>" />

                <hr />

                <button type="submit"><?php echo $locale->getText('console.home.index.platforms-create-button-submit'); ?></button> &nbsp; <button data-ui-modal-close="" type="button" class="reverse"><?php echo $locale->getText('shared.cancel'); ?></button>
            </form>
        </li>
        <li>
            <h2 style="display: none">&nbsp;&nbsp;<?php echo $locale->getText('console.home.index.platforms-flutter-macos-title'); ?>&nbsp;&nbsp;</h2>

            <form
                data-analytics
                data-analytics-activity
                data-analytics-event="submit"
                data-analytics-category="console"
                data-analytics-label="Create Project Platform (Flutter / Mac OS)"
                data-service="projects.createPlatform"
                data-scope="console"
                data-event="submit"
                data-success="alert,trigger,reset"
                data-success-param-alert-text="<?php echo $locale->getText('console.home.index.platforms-create-success'); ?>"
                data-success-param-trigger-events="projects.createPlatform"
                data-failure="alert"
                data-failure-param-alert-text="<?php echo $locale->getText('console.home.index.platforms-create-error'); ?>"
                data-failure-param-alert-classname="error">

                <input type="hidden" name="projectId" data-ls-bind="{{router.params.project}}" />
                <input type="hidden" name="type" data-ls-bind="flutter-macos" />

                <label for="name"><?php echo $locale->getText('shared.label-name'); ?> <span class="tooltip large" data-tooltip="<?php echo $locale->getText('console.home.index.platforms-tooltip-name'); ?>"><i class="icon-question"></i></span></label>
                <input type="text" class="full-width" name="name" required autocomplete="off" placeholder="<?php echo $locale->getText('console.home.index.platforms-placeholder-macos-name'); ?>" maxlength="128" />

                <label for="key"><?php echo $locale->getText('console.home.index.platforms-label-bundle-id'); ?> <span class="tooltip large" data-tooltip="<?php echo $locale->getText('console.home.index.platforms-tooltip-bundle-id'); ?>"><i class="icon-question"></i></span></label>
                <input type="text" class="full-width" name="key" required autocomplete="off" placeholder="<?php echo $locale->getText('console.home.index.platforms-placeholder-macos-hostname'); ?>" />

                <hr />

                <button type="submit"><?php echo $locale->getText('console.home.index.platforms-create-button-submit'); ?></button> &nbsp; <button data-ui-modal-close="" type="button" class="reverse"><?php echo $locale->getText('shared.cancel'); ?></button>
            </form>
        </li>
        <li>
            <h2 style="display: none">&nbsp;&nbsp;<?php echo $locale->getText('console.home.index.platforms-flutter-windows-title'); ?>&nbsp;&nbsp;</h2>

            <form
                data-analytics
                data-analytics-activity
                data-analytics-event="submit"
                data-analytics-category="console"
                data-analytics-label="Create Project Platform (Flutter / Windows)"
                data-service="projects.createPlatform"
                data-scope="console"
                data-event="submit"
                data-success="alert,trigger,reset"
                data-success-param-alert-text="<?php echo $locale->getText('console.home.index.platforms-create-success'); ?>"
                data-success-param-trigger-events="projects.createPlatform"
                data-failure="alert"
                data-failure-param-alert-text="<?php echo $locale->getText('console.home.index.platforms-create-error'); ?>"
                data-failure-param-alert-classname="error">

                <input type="hidden" name="projectId" data-ls-bind="{{router.params.project}}" />
                <input type="hidden" name="type" data-ls-bind="flutter-windows" />

                <label for="name"><?php echo $locale->getText('shared.label-name'); ?> <span class="tooltip large" data-tooltip="<?php echo $locale->getText('console.home.index.platforms-tooltip-name'); ?>"><i class="icon-question"></i></span></label>
                <input type="text" class="full-width" name="name" required autocomplete="off" placeholder="<?php echo $locale->getText('console.home.index.platforms-placeholder-windows-name'); ?>" maxlength="128" />

                <label for="key"><?php echo $locale->getText('console.home.index.platforms-label-package-name'); ?> <span class="tooltip large" data-tooltip="<?php echo $locale->getText('console.home.index.platforms-tooltip-package-name2'); ?>"><i class="icon-question"></i></span></label>
                <input type="text" class="full-width" name="key" required autocomplete="off" placeholder="<?php echo $locale->getText('console.home.index.platforms-placeholder-windows-hostname'); ?>" />

                <hr />

                <button type="submit"><?php echo $locale->getText('console.home.index.platforms-create-button-submit'); ?></button> &nbsp; <button data-ui-modal-close="" type="button" class="reverse"><?php echo $locale->getText('shared.cancel'); ?></button>
            </form>
        </li>
    </ul>
</div>

<script type="text/html" id="template-ios-update">
    <form
        data-analytics
        data-analytics-activity
        data-analytics-event="submit"
        data-analytics-category="console"
        data-analytics-label="Update Project Platform (Flutter / iOS)"
        data-service="projects.updatePlatform"
        data-scope="console"
        data-event="submit"
        data-success="alert,trigger"
        data-success-param-alert-text="<?php echo $locale->getText('console.home.index.platforms-update-success'); ?>"
        data-success-param-trigger-events="projects.updatePlatform"
        data-failure="alert"
        data-failure-param-alert-text="<?php echo $locale->getText('console.home.index.platforms-update-error'); ?>"
        data-failure-param-alert-classname="error">

        <input type="hidden" name="projectId" data-ls-bind="{{router.params.project}}" />
        <input type="hidden" name="platformId" data-ls-bind="{{platform.$id}}" />

        <label data-ls-attrs="for=name-{{platform.$id}}"><?php echo $locale->getText('shared.label-name'); ?> <span class="tooltip large" data-tooltip="<?php echo $locale->getText('console.home.index.platforms-tooltip-name'); ?>"><i class="icon-question"></i></span></label>
        <input type="text" class="full-width" data-ls-attrs="id=name-{{platform.$id}}" name="name" required autocomplete="off" data-ls-bind="{{platform.name}}" placeholder="<?php echo $locale->getText('console.home.index.platforms-placeholder-ios-name'); ?>" maxlength="128" />

        <label data-ls-attrs="for=key-{{platform.$id}}"><?php echo $locale->getText('console.home.index.platforms-label-bundle-id'); ?> <span class="tooltip large" data-tooltip="<?php echo $locale->getText('console.home.index.platforms-tooltip-bundle-id'); ?>"><i class="icon-question"></i></span></label>
        <input name="key" type="text" class="margin-bottom" autocomplete="off" placeholder="<?php echo $locale->getText('console.home.index.platforms-placeholder-ios-hostname'); ?>" data-ls-bind="{{platform.key}}" required />
        
        <hr />

        <button type="submit"><?php echo $locale->getText('shared.button-update'); ?></button> &nbsp; <button data-ls-ui-trigger="modal-close" type="button" class="reverse"><?php echo $locale->getText('shared.cancel'); ?></button>
    </form>
</script>

<script type="text/html" id="template-android-update">
    <form
        data-analytics
        data-analytics-event="submit"
        data-analytics-category="console"
        data-analytics-label="Update Project Platform (Flutter / Android)"
        data-service="projects.updatePlatform"
        data-scope="console"
        data-event="submit"
        data-success="alert,trigger"
        data-success-param-alert-text="<?php echo $locale->getText('console.home.index.platforms-update-success'); ?>"
        data-success-param-trigger-events="projects.updatePlatform"
        data-failure="alert"
        data-failure-param-alert-text="<?php echo $locale->getText('console.home.index.platforms-update-error'); ?>"
        data-failure-param-alert-classname="error">

        <input type="hidden" name="projectId" data-ls-bind="{{router.params.project}}" />
        <input type="hidden" name="platformId" data-ls-bind="{{platform.$id}}" />

        <label data-ls-attrs="for=name-{{platform.$id}}"><?php echo $locale->getText('shared.label-name'); ?> <span class="tooltip large" data-tooltip="<?php echo $locale->getText('console.home.index.platforms-tooltip-name'); ?>"><i class="icon-question"></i></span></label>
        <input type="text" class="full-width" data-ls-attrs="id=name-{{platform.$id}}" name="name" required autocomplete="off" data-ls-bind="{{platform.name}}" placeholder="<?php echo $locale->getText('console.home.index.platforms-placeholder-android-name'); ?>" maxlength="128" />

        <label data-ls-attrs="for=key-{{platform.$id}}"><?php echo $locale->getText('console.home.index.platforms-label-package-name'); ?> <span class="tooltip large" data-tooltip="<?php echo $locale->getText('console.home.index.platforms-tooltip-package-name'); ?>"><i class="icon-question"></i></span></label>
        <input name="key" type="text" class="margin-bottom" autocomplete="off" placeholder="<?php echo $locale->getText('console.home.index.platforms-placeholder-android-hostname'); ?>" data-ls-bind="{{platform.key}}" required />
        
        <hr />

        <button type="submit"><?php echo $locale->getText('shared.button-update'); ?></button> &nbsp; <button data-ls-ui-trigger="modal-close" type="button" class="reverse"><?php echo $locale->getText('shared.cancel'); ?></button>
    </form>
</script>

<script type="text/html" id="template-flutter-ios-update">
    <div data-ls-template="template-ios-update" data-type="script"></div>
</script>

<script type="text/html" id="template-flutter-android-update">
    <div data-ls-template="template-android-update" data-type="script"></div>
</script>

<script type="text/html" id="template-flutter-macos-update">
    <div data-ls-template="template-macos-update" data-type="script"></div>
</script>