<div class="logo text-align-center">
    <a href="/">
        <img src="/images/appwrite.svg" alt="Appwrite Light Logo" class="force-light" />
        <img src="/images/appwrite-footer.svg" alt="Appwrite Dark Logo" class="force-dark" />
    </a>

    <button data-general-theme class="theme-button trans text-fade">
        <i class="icon-sun-inv force-dark"></i>
        <i class="icon-moon-inv force-light"></i>
    </button>
</div>