<?php
$locale = $this->getParam("locale");
/** @var Utopia\Locale\Locale $locale */
?>

<div class="logo text-align-center margin-bottom-xl">
    <a href="/">
        <img src="/images/appwrite.svg" alt="<?php echo $locale->getText("shared.header.alt-logo-light"); ?>" class="force-light" loading="lazy" />
        <img src="/images/appwrite-footer-dark.svg" alt="<?php echo $locale->getText("shared.header.alt-logo-dark"); ?>" class="force-dark" loading="lazy" />
    </a>
</div>
