import type { RowCellValue } from '@/lib/database-row-inline-edits'
import {
  isDateTimeInlineFieldType,
  isNumericInlineFieldType,
  rowCellValuesEqual,
} from '@/lib/database-row-inline-edits'
import {
  isMysqlDatetimeType,
  parseMysqlColumnTypeFromRow,
  type MysqlColumnTypeId,
} from '@/lib/mysql-column-types'
import {
  isMysqlPrimaryKeyColumn,
  type MysqlTableColumnRow,
} from '@/lib/mysql-sql'
import type { MysqlRowIdentity } from '@/lib/mysql-row-sql'

export type MysqlColumnEditMeta = {
  typeId: MysqlColumnTypeId
  dataType: string
  udtName: string
  nullable: boolean
  isPrimaryKey: boolean
  hasDefault: boolean
  length?: number
  numericPrecision?: number
  numericScale?: number
  enumValues?: string[]
}

export type PendingMysqlRowCellEdit = {
  databaseId: string
  tableId: string
  rowKey: string
  columnKey: string
  originalValue: RowCellValue
  value: RowCellValue
  identity: MysqlRowIdentity
}

const NON_INLINE_EDITABLE_TYPES = new Set<MysqlColumnTypeId>([
  'json',
  'jsonb',
  'bytea',
  'interval',
  'bit',
  'bit varying',
])

export function getMysqlColumnEditMeta(
  column: MysqlTableColumnRow,
): MysqlColumnEditMeta {
  const typeState = parseMysqlColumnTypeFromRow(column)
  return {
    typeId: typeState.typeId,
    dataType: column.data_type,
    udtName: column.udt_name,
    nullable: column.is_nullable === 'YES',
    isPrimaryKey: isMysqlPrimaryKeyColumn(column),
    hasDefault: column.column_default != null && column.column_default !== '',
    length: typeState.length,
    numericPrecision: typeState.numericPrecision,
    numericScale: typeState.numericScale,
    enumValues:
      typeState.typeId === 'enum' ? typeState.enumValues : undefined,
  }
}

export function getMysqlInlineFieldType(
  meta: MysqlColumnEditMeta,
  value?: RowCellValue,
): string {
  if (meta.typeId === 'boolean') return 'boolean'
  if (meta.typeId === 'enum') return 'enum'
  if (isMysqlDatetimeType(meta.typeId)) return 'datetime'
  if (
    meta.typeId === 'smallint' ||
    meta.typeId === 'integer' ||
    meta.typeId === 'bigint' ||
    meta.typeId === 'smallserial' ||
    meta.typeId === 'serial' ||
    meta.typeId === 'bigserial'
  ) {
    return 'integer'
  }
  if (
    meta.typeId === 'real' ||
    meta.typeId === 'double precision' ||
    meta.typeId === 'numeric'
  ) {
    return 'double'
  }
  if (meta.typeId === 'uuid') return 'string'
  if (meta.typeId === 'json' || meta.typeId === 'jsonb') return 'json'
  if (meta.typeId === 'bytea') return 'bytea'
  if (Array.isArray(value)) return 'array'
  return 'string'
}

export function isMysqlGeneratedColumn(column: MysqlTableColumnRow): boolean {
  if (column.serial_sequence?.trim()) return true
  if (column.is_identity === 'YES') return true

  const defaultValue = column.column_default?.toLowerCase() ?? ''
  if (
    defaultValue.includes('nextval(') ||
    defaultValue.includes('generated always') ||
    defaultValue.includes('generated by default')
  ) {
    return true
  }

  const typeId = parseMysqlColumnTypeFromRow(column).typeId
  return (
    typeId === 'serial' ||
    typeId === 'bigserial' ||
    typeId === 'smallserial'
  )
}

function columnHasExplicitDefault(column: MysqlTableColumnRow): boolean {
  return column.column_default != null && column.column_default !== ''
}

/**
 * True only when Mysql will assign a unique value on INSERT if the column
 * is omitted: serial/identity sequences, nextval(), or UUID generators.
 * Plain defaults (constants, now(), etc.) are not auto-generation.
 */
export function mysqlColumnAutoGeneratesOnInsert(
  column: MysqlTableColumnRow,
): boolean {
  if (column.serial_sequence?.trim()) return true

  const identity = String(column.is_identity ?? '').toUpperCase()
  if (identity === 'YES' || identity === 'TRUE' || identity === 'T') {
    return true
  }

  const generation = String(column.identity_generation ?? '').toUpperCase()
  if (generation === 'ALWAYS' || generation === 'BY DEFAULT') {
    return true
  }

  const defaultValue = column.column_default?.toLowerCase() ?? ''
  if (!defaultValue) return false

  return (
    defaultValue.includes('nextval(') ||
    defaultValue.includes('gen_random_uuid(') ||
    defaultValue.includes('uuid_generate_')
  )
}

/**
 * True when an empty create field should be omitted from INSERT so Mysql
 * applies its default. Primary keys only qualify when they truly auto-generate;
 * otherwise the user must supply a unique value.
 */
export function mysqlColumnCanOmitOnCreate(
  column: MysqlTableColumnRow,
): boolean {
  if (mysqlColumnAutoGeneratesOnInsert(column)) return true
  if (
    columnHasExplicitDefault(column) &&
    !isMysqlPrimaryKeyColumn(column)
  ) {
    return true
  }
  return false
}

/**
 * Columns Mysql rejects user-supplied values for (GENERATED ALWAYS identity
 * or stored generated columns). Primary keys and serial/identity BY DEFAULT
 * columns are writable on both create and update.
 */
export function isMysqlColumnSystemGenerated(
  column: MysqlTableColumnRow,
): boolean {
  const generation = String(column.identity_generation ?? '').toUpperCase()
  if (generation === 'ALWAYS') return true

  const defaultValue = column.column_default?.toLowerCase() ?? ''
  return defaultValue.includes('generated always')
}

/** Columns omitted from the create form because Mysql rejects user values. */
export function shouldOmitMysqlColumnOnRowCreate(
  column: MysqlTableColumnRow,
): boolean {
  return isMysqlColumnSystemGenerated(column)
}

/**
 * Primary keys without auto-generation are always required on create.
 * Other NOT NULL columns are optional when they have a database default.
 */
export function isMysqlColumnRequiredOnCreate(
  column: MysqlTableColumnRow,
): boolean {
  if (mysqlColumnAutoGeneratesOnInsert(column)) return false
  if (column.is_nullable === 'YES') return false
  if (isMysqlPrimaryKeyColumn(column)) return true
  if (columnHasExplicitDefault(column)) return false
  return true
}

export function filterMysqlRowCreateValues(
  values: Record<string, RowCellValue>,
  columns: MysqlTableColumnRow[],
): Record<string, RowCellValue> {
  const omitColumns = new Set(
    columns
      .filter((column) => shouldOmitMysqlColumnOnRowCreate(column))
      .map((column) => column.column_name),
  )
  const filtered: Record<string, RowCellValue> = {}
  for (const [columnName, value] of Object.entries(values)) {
    if (omitColumns.has(columnName) || value === undefined) continue
    filtered[columnName] = value
  }
  return filtered
}

export function isMysqlColumnInlineEditable(
  column: MysqlTableColumnRow,
): boolean {
  if (isMysqlColumnSystemGenerated(column)) return false
  const meta = getMysqlColumnEditMeta(column)
  if (NON_INLINE_EDITABLE_TYPES.has(meta.typeId)) return false
  return true
}

export function isMysqlColumnRequired(column: MysqlTableColumnRow): boolean {
  return column.is_nullable !== 'YES'
}

export function valueToMysqlEditString(
  value: RowCellValue,
  _meta: MysqlColumnEditMeta,
): string {
  if (value === null || value === undefined) return ''
  if (typeof value === 'boolean') return value ? 'true' : 'false'
  if (typeof value === 'object') return JSON.stringify(value, null, 2)
  return String(value)
}

type ParseResult =
  | { ok: true; value: RowCellValue }
  | { ok: false; error: string }

function parseBooleanInput(raw: string): ParseResult {
  const normalized = raw.trim().toLowerCase()
  if (!normalized) return { ok: true, value: null }
  if (['true', 't', '1', 'yes'].includes(normalized)) {
    return { ok: true, value: true }
  }
  if (['false', 'f', '0', 'no'].includes(normalized)) {
    return { ok: true, value: false }
  }
  return { ok: false, error: 'Enter true or false.' }
}

function parseNumericInput(
  raw: string,
  meta: MysqlColumnEditMeta,
  integerOnly: boolean,
): ParseResult {
  const trimmed = raw.trim()
  if (!trimmed) return { ok: true, value: null }
  const parsed = integerOnly ? Number.parseInt(trimmed, 10) : Number(trimmed)
  if (!Number.isFinite(parsed)) {
    return { ok: false, error: 'Enter a valid number.' }
  }
  if (meta.numericPrecision != null && integerOnly) {
    const max = 10 ** meta.numericPrecision - 1
    if (Math.abs(parsed) > max) {
      return { ok: false, error: `Value exceeds allowed range.` }
    }
  }
  return { ok: true, value: parsed }
}

function parseJsonInput(raw: string): ParseResult {
  const trimmed = raw.trim()
  if (!trimmed) return { ok: true, value: null }
  try {
    return { ok: true, value: JSON.parse(trimmed) }
  } catch {
    return { ok: false, error: 'Enter valid JSON.' }
  }
}

export function parseAndValidateMysqlCellInput(
  raw: string,
  column: MysqlTableColumnRow,
): ParseResult {
  const meta = getMysqlColumnEditMeta(column)
  const trimmed = raw.trim()
  const required = isMysqlColumnRequired(column)

  if (!trimmed) {
    if (required) return { ok: false, error: 'This field is required.' }
    return { ok: true, value: null }
  }

  const fieldType = getMysqlInlineFieldType(meta)

  if (fieldType === 'boolean') return parseBooleanInput(raw)
  if (fieldType === 'enum') {
    if (meta.enumValues?.length && !meta.enumValues.includes(trimmed)) {
      return { ok: false, error: 'Value is not allowed for this enum.' }
    }
    return { ok: true, value: trimmed }
  }
  if (fieldType === 'json') return parseJsonInput(raw)
  if (isDateTimeInlineFieldType(fieldType)) {
    const date = new Date(trimmed)
    if (Number.isNaN(date.getTime())) {
      return { ok: false, error: 'Enter a valid date and time.' }
    }
    return { ok: true, value: trimmed }
  }
  if (isNumericInlineFieldType(fieldType)) {
    return parseNumericInput(
      raw,
      meta,
      fieldType === 'integer' || fieldType === 'bigint',
    )
  }

  if (meta.length != null && trimmed.length > meta.length) {
    return {
      ok: false,
      error: `Maximum length is ${meta.length} characters.`,
    }
  }

  return { ok: true, value: trimmed }
}

export function makeMysqlPendingEditKey(
  tableId: string,
  rowKey: string,
  columnKey: string,
): string {
  return `${tableId}:${rowKey}:${columnKey}`
}

export { rowCellValuesEqual }

export function groupMysqlEditsByRow(
  edits: PendingMysqlRowCellEdit[],
): Map<
  string,
  {
    identity: PendingMysqlRowCellEdit['identity']
    changes: Record<string, RowCellValue>
  }
> {
  const grouped = new Map<
    string,
    {
      identity: PendingMysqlRowCellEdit['identity']
      changes: Record<string, RowCellValue>
    }
  >()

  for (const edit of edits) {
    const existing = grouped.get(edit.rowKey)
    if (existing) {
      existing.changes[edit.columnKey] = edit.value
      continue
    }
    grouped.set(edit.rowKey, {
      identity: edit.identity,
      changes: { [edit.columnKey]: edit.value },
    })
  }

  return grouped
}
