import type { RowCellValue } from '@/lib/database-row-inline-edits'
import {
  isDateTimeInlineFieldType,
  isNumericInlineFieldType,
  rowCellValuesEqual,
} from '@/lib/database-row-inline-edits'
import {
  isPostgresDatetimeType,
  parsePostgresColumnTypeFromRow,
  type PostgresColumnTypeId,
} from '@/lib/postgres-column-types'
import type { PostgresTableColumnRow } from '@/lib/postgres-sql'
import type { PostgresRowIdentity } from '@/lib/postgres-row-sql'

export type PostgresColumnEditMeta = {
  typeId: PostgresColumnTypeId
  dataType: string
  udtName: string
  nullable: boolean
  isPrimaryKey: boolean
  hasDefault: boolean
  length?: number
  numericPrecision?: number
  numericScale?: number
}

export type PendingPostgresRowCellEdit = {
  databaseId: string
  tableId: string
  rowKey: string
  columnKey: string
  originalValue: RowCellValue
  value: RowCellValue
  identity: PostgresRowIdentity
}

const NON_INLINE_EDITABLE_TYPES = new Set<PostgresColumnTypeId>([
  'json',
  'jsonb',
  'bytea',
  'interval',
  'bit',
  'bit varying',
])

export function getPostgresColumnEditMeta(
  column: PostgresTableColumnRow,
): PostgresColumnEditMeta {
  const typeState = parsePostgresColumnTypeFromRow(column)
  return {
    typeId: typeState.typeId,
    dataType: column.data_type,
    udtName: column.udt_name,
    nullable: column.is_nullable === 'YES',
    isPrimaryKey:
      column.is_primary_key === true || column.is_primary_key === 'true',
    hasDefault: column.column_default != null && column.column_default !== '',
    length: typeState.length,
    numericPrecision: typeState.numericPrecision,
    numericScale: typeState.numericScale,
  }
}

export function getPostgresInlineFieldType(
  meta: PostgresColumnEditMeta,
  value?: RowCellValue,
): string {
  if (meta.typeId === 'boolean') return 'boolean'
  if (isPostgresDatetimeType(meta.typeId)) return 'datetime'
  if (
    meta.typeId === 'smallint' ||
    meta.typeId === 'integer' ||
    meta.typeId === 'bigint' ||
    meta.typeId === 'smallserial' ||
    meta.typeId === 'serial' ||
    meta.typeId === 'bigserial'
  ) {
    return 'integer'
  }
  if (
    meta.typeId === 'real' ||
    meta.typeId === 'double precision' ||
    meta.typeId === 'numeric'
  ) {
    return 'double'
  }
  if (meta.typeId === 'uuid') return 'string'
  if (meta.typeId === 'json' || meta.typeId === 'jsonb') return 'json'
  if (meta.typeId === 'bytea') return 'bytea'
  if (Array.isArray(value)) return 'array'
  return 'string'
}

export function isPostgresGeneratedColumn(column: PostgresTableColumnRow): boolean {
  const defaultValue = column.column_default?.toLowerCase() ?? ''
  return (
    defaultValue.includes('nextval(') ||
    defaultValue.includes('generated always') ||
    defaultValue.includes('generated by default')
  )
}

export function isPostgresColumnInlineEditable(
  column: PostgresTableColumnRow,
): boolean {
  const meta = getPostgresColumnEditMeta(column)
  if (meta.isPrimaryKey && meta.hasDefault) return false
  if (isPostgresGeneratedColumn(column)) return false
  if (NON_INLINE_EDITABLE_TYPES.has(meta.typeId)) return false
  return true
}

export function isPostgresColumnRequired(column: PostgresTableColumnRow): boolean {
  return column.is_nullable !== 'YES'
}

export function valueToPostgresEditString(
  value: RowCellValue,
  _meta: PostgresColumnEditMeta,
): string {
  if (value === null || value === undefined) return ''
  if (typeof value === 'boolean') return value ? 'true' : 'false'
  if (typeof value === 'object') return JSON.stringify(value, null, 2)
  return String(value)
}

type ParseResult =
  | { ok: true; value: RowCellValue }
  | { ok: false; error: string }

function parseBooleanInput(raw: string): ParseResult {
  const normalized = raw.trim().toLowerCase()
  if (!normalized) return { ok: true, value: null }
  if (['true', 't', '1', 'yes'].includes(normalized)) {
    return { ok: true, value: true }
  }
  if (['false', 'f', '0', 'no'].includes(normalized)) {
    return { ok: true, value: false }
  }
  return { ok: false, error: 'Enter true or false.' }
}

function parseNumericInput(
  raw: string,
  meta: PostgresColumnEditMeta,
  integerOnly: boolean,
): ParseResult {
  const trimmed = raw.trim()
  if (!trimmed) return { ok: true, value: null }
  const parsed = integerOnly ? Number.parseInt(trimmed, 10) : Number(trimmed)
  if (!Number.isFinite(parsed)) {
    return { ok: false, error: 'Enter a valid number.' }
  }
  if (meta.numericPrecision != null && integerOnly) {
    const max = 10 ** meta.numericPrecision - 1
    if (Math.abs(parsed) > max) {
      return { ok: false, error: `Value exceeds allowed range.` }
    }
  }
  return { ok: true, value: parsed }
}

function parseJsonInput(raw: string): ParseResult {
  const trimmed = raw.trim()
  if (!trimmed) return { ok: true, value: null }
  try {
    return { ok: true, value: JSON.parse(trimmed) }
  } catch {
    return { ok: false, error: 'Enter valid JSON.' }
  }
}

export function parseAndValidatePostgresCellInput(
  raw: string,
  column: PostgresTableColumnRow,
): ParseResult {
  const meta = getPostgresColumnEditMeta(column)
  const trimmed = raw.trim()
  const required = isPostgresColumnRequired(column)

  if (!trimmed) {
    if (required) return { ok: false, error: 'This field is required.' }
    return { ok: true, value: null }
  }

  const fieldType = getPostgresInlineFieldType(meta)

  if (fieldType === 'boolean') return parseBooleanInput(raw)
  if (fieldType === 'json') return parseJsonInput(raw)
  if (isDateTimeInlineFieldType(fieldType)) {
    const date = new Date(trimmed)
    if (Number.isNaN(date.getTime())) {
      return { ok: false, error: 'Enter a valid date and time.' }
    }
    return { ok: true, value: trimmed }
  }
  if (isNumericInlineFieldType(fieldType)) {
    return parseNumericInput(
      raw,
      meta,
      fieldType === 'integer' || fieldType === 'bigint',
    )
  }

  if (meta.length != null && trimmed.length > meta.length) {
    return {
      ok: false,
      error: `Maximum length is ${meta.length} characters.`,
    }
  }

  return { ok: true, value: trimmed }
}

export function makePostgresPendingEditKey(
  tableId: string,
  rowKey: string,
  columnKey: string,
): string {
  return `${tableId}:${rowKey}:${columnKey}`
}

export { rowCellValuesEqual }

export function groupPostgresEditsByRow(
  edits: PendingPostgresRowCellEdit[],
): Map<
  string,
  {
    identity: PendingPostgresRowCellEdit['identity']
    changes: Record<string, RowCellValue>
  }
> {
  const grouped = new Map<
    string,
    {
      identity: PendingPostgresRowCellEdit['identity']
      changes: Record<string, RowCellValue>
    }
  >()

  for (const edit of edits) {
    const existing = grouped.get(edit.rowKey)
    if (existing) {
      existing.changes[edit.columnKey] = edit.value
      continue
    }
    grouped.set(edit.rowKey, {
      identity: edit.identity,
      changes: { [edit.columnKey]: edit.value },
    })
  }

  return grouped
}
