<?php

use Utopia\Locale\Locale;

?>

<div class="cover">
    <h1 class="zone xl margin-bottom-large margin-top">
        <?php echo Locale::getText('console.settings.title'); ?>
    </h1>
</div>

<div class="zone xl" data-service="projects.getProject" data-scope="console" data-name="console-project" data-event="load" data-param-project-id="{{router.params.project}}" data-success="render,trigger" data-error="render" data-success-rerender="" data-error-rerender="" data-success-triggers="project.load">

    <div class="zone xl">
        <ul class="phases clear" data-ui-phases data-selected="{{router.params.tab}}">
            <li data-state="/console/settings?project={{router.params.project}}">
                <h2><?php echo Locale::getText('console.settings.section.overview.title'); ?></h2>

                <form data-service="projects.updateProject" data-scope="console" data-event="submit" data-param-project-id="{{router.params.project}}" data-success="alert,trigger" data-success-alert="Saved project successfully" data-success-triggers="project.update" data-error="alert" data-error-alert="Failed to update project">

                    <input name="$uid" type="hidden" data-ls-bind="{{console-project.$uid}}" />

                    <div class="row">
                        <div class="col span-9">
                            <div class="box">
                                <label for="name">Name</label>
                                <input name="name" id="name" type="text" autocomplete="off" data-ls-bind="{{console-project.name}}" data-forms-text-direction required>

                                <label for="name">Project ID</label>
                                <div class="input-copy">
                                    <input data-forms-copy type="text" disabled data-ls-bind="{{router.params.project}}" />
                                </div>

                                <label for="description">Description &nbsp;<small>(optional)</small></label>
                                <textarea name="description" id="description" autocomplete="off" placeholder="Help us make the world a better place" data-ls-bind="{{console-project.description}}" data-forms-text-direction data-forms-text-count></textarea>

                                <label for="url">Website &nbsp;<small>(optional)</small></label>
                                <input name="url" id="url" type="url" class="full-width" autocomplete="off" placeholder="https://acme-corp.com" data-ls-bind="{{console-project.url}}">

                                <hr />

                                <h3>Clients</h3>

                                <input name="clients" type="hidden" data-cast-to="array-empty">

                                <div data-ls-loop="console-project.clients" data-ls-as="client" style="overflow: hidden">
                                    <div class="margin-bottom-small">
                                        <div data-forms-remove class="row thin">
                                            <div class="col span-9">
                                                <input name="clients" type="url" class="full-width" autocomplete="off" placeholder="https://acme-corp.com" data-ls-bind="{{client}}" data-cast-to="array">
                                            </div>
                                            <div class="col span-3">
                                                <button type="button" data-remove class="reverse danger pull-end"><i class="icon-cancel"></i></button>
                                            </div>
                                        </div>
                                    </div>
                                </div>

                                <div data-forms-clone="" data-first="0">
                                    <div class="margin-bottom-small">
                                        <div data-forms-remove class="row thin">
                                            <div class="col span-9">
                                                <input name="clients" type="url" class="full-width" autocomplete="off" placeholder="https://acme-corp.com" data-cast-to="array">
                                            </div>
                                            <div class="col span-3">
                                                <button type="button" data-remove class="reverse danger pull-end"><i class="icon-cancel"></i></button>
                                            </div>
                                        </div>
                                    </div>
                                </div>

                                <hr />

                                <button class="" type="submit">Save</button>
                            </div>
                        </div>

                        <div class="col span-3 box-aside">
                            <label for="name">Logo</label>
                            <div class="text-center clear">
                                <input type="hidden" name="logo" data-ls-bind="{{console-project.logo}}" data-read="<?php echo $this->escape(json_encode(['*'])); ?>" data-write="<?php echo $this->escape(json_encode(['team:{{console-project.teamId}}'])); ?>" data-accept="image/*" data-forms-upload="" data-scope="console" data-default="">
                            </div>
                        </div>
                    </div>
                </form>
            </li>
            <li data-state="/console/settings/privacy?project={{router.params.project}}">

                <form data-service="projects.updateProject" data-scope="console" data-event="submit" data-param-project-id="{{router.params.project}}" data-success="alert,trigger" data-success-alert="Saved project successfully" data-success-triggers="project.update" data-error="alert" data-error-alert="Failed to update project">
                    <h2>Privacy & Legal</h2>

                    <div class="box margin-bottom">
                        <input name="$uid" type="hidden" data-ls-bind="{{console-project.$uid}}" />

                        <div class="row thin">
                            <div class="col span-6">
                                <label for="legalName">Legal Name</label>
                                <input name="legalName" id="legalName" type="text" autocomplete="off" data-ls-bind="{{console-project.legalName}}" data-forms-text-direction>

                                <label for="legalCountry">Country</label>
                                <select id="legalCountry" name="legalCountry" data-ls-options="{{geo-countries}}" data-ls-bind="{{console-project.legalCountry}}"></select>

                                <label for="legalCity">City</label>
                                <input name="legalCity" id="legalCity" type="text" autocomplete="off" data-ls-bind="{{console-project.legalCity}}" data-forms-text-direction>
                            </div>

                            <div class="col span-6">
                                <label for="legalTaxId">Tax ID</label>
                                <input name="legalTaxId" id="legalTaxId" type="text" autocomplete="off" data-ls-bind="{{console-project.legalTaxId}}" data-forms-text-direction>

                                <label for="legalState">State</label>
                                <input name="legalState" id="legalState" type="text" autocomplete="off" data-ls-bind="{{console-project.legalState}}" data-forms-text-direction>

                                <label for="legalAddress">Address</label>
                                <input name="legalAddress" id="legalAddress" type="text" autocomplete="off" data-ls-bind="{{console-project.legalAddress}}" data-forms-text-direction>
                            </div>
                        </div>

                        <hr />

                        <button class="" type="submit">Save</button>
                    </div>
                </form>
            </li>
            <li data-state="/console/settings/members?project={{router.params.project}}">
                <h2><?php echo Locale::getText('console.settings.section.members.title'); ?></h2>

                <div class="zone xl" data-service="teams.getTeamMembers" data-scope="console" data-event="load,auth.invite,auth.leave" data-name="members" data-param-team-id="{{console-project.teamId}}" data-success="render,trigger" data-success-triggers="members.load" data-error="render" data-error-rerender="">

                    <div class="box margin-bottom">
                        <ul data-ls-loop="members" data-ls-as="member" class="list">
                            <li class="clear">
                                <form class="pull-end" data-service="auth.leave" data-scope="console" data-event="submit" data-success="alert,trigger" data-success-alert="<?php echo Locale::getText('console.settings.section.members.leave.success'); ?>" data-success-triggers="auth.leave,project.update" data-error="alert" data-error-alert="<?php echo Locale::getText('console.settings.section.members.leave.failure'); ?>">

                                    <input name="inviteId" id="inviteId" type="hidden" data-ls-bind="{{member.inviteId}}">

                                    <button class="danger"><?php echo Locale::getText('console.settings.section.members.labels.leave'); ?></button>
                                </form>

                                <div data-ls-if="false === {{member.confirm}}" class="pull-end margin-end" style="display: none;">
                                    <form data-service="auth.inviteResend" data-scope="console" data-event="submit" data-success="alert,trigger" data-success-alert="<?php echo Locale::getText('console.settings.section.members.invite.success'); ?>" data-success-triggers="auth.invite" data-error="alert" data-error-alert="<?php echo Locale::getText('console.settings.section.members.invite.failure'); ?>">
                                        <input name="inviteId" id="inviteId" type="hidden" data-ls-bind="{{member.inviteId}}">
                                        <input name="redirect" type="hidden" data-ls-bind="https://{{env.DOMAIN}}/auth/join?project={{router.params.project}}" />

                                        <button class="reverse"><?php echo Locale::getText('console.settings.section.members.labels.resend'); ?></button>
                                    </form>
                                </div>

                                <img src="" data-ls-attrs="src={{member|gravatar}}" alt="User Avatar" class="avatar pull-start margin-end" />

                                <div class="margin-bottom-small">
                                    <span data-ls-bind="{{member.name}}"></span> &nbsp;&nbsp;<span class="tag" data-ls-bind="{{member.roles.0|id2role}}"></span> &nbsp;&nbsp;<span data-ls-if="false === {{member.confirm}}" class="tag red" style="display: none;"><?php echo Locale::getText('console.settings.section.members.labels.pending'); ?></span>
                                </div>
                                <span class="note" data-ls-bind="{{member.email}}"></span>
                            </li>
                        </ul>
                    </div>

                    <div data-ui-modal class="modal close width-small" data-button-text="<?php echo Locale::getText('console.settings.section.members.labels.invite'); ?>" data-button-class="">
                        <button type="button" class="close pull-end" data-ui-modal-close><i class="icon-cancel"></i></button>

                        <h1><?php echo Locale::getText('console.settings.section.members.labels.invite'); ?></h1>

                        <form name="auth.invite" data-service="auth.invite" data-scope="console" data-event="submit" data-success="alert,trigger,reset" data-success-alert="<?php echo Locale::getText('console.settings.section.members.invite.success'); ?>" data-success-triggers="auth.invite,modal-close" data-error="alert" data-error-alert="<?php echo Locale::getText('console.settings.section.members.invite.failure'); ?>">

                            <input name="team" id="team" type="hidden" data-ls-bind="{{console-project.teamId}}">
                            <input name="redirect" type="hidden" data-ls-bind="https://{{env.DOMAIN}}/auth/join?project={{router.params.project}}" />

                            <label for="name"><?php echo Locale::getText('console.settings.section.members.labels.name'); ?> <small>(<?php echo Locale::getText('general.optional'); ?>)</small></label>
                            <input name="name" id="name" type="text" autocomplete="name">

                            <label for="email"><?php echo Locale::getText('console.settings.section.members.labels.email'); ?></label>
                            <input name="email" id="email" type="email" autocomplete="email" required>

                            <label for="roles"><?php echo Locale::getText('console.settings.section.members.labels.role'); ?></label>
                            <select id="roles" name="roles" required data-ls-options="{{env.ROLES}}" data-cast-to="array"></select>

                            <div class="clear">
                                <button><?php echo Locale::getText('console.settings.section.members.labels.send'); ?></button>
                                &nbsp; <button data-ui-modal-close="" type="button" class="reverse"><?php echo Locale::getText('console.settings.section.members.labels.cancel'); ?></button>
                            </div>
                        </form>
                    </div>
                </div>
            </li>
        </ul>
    </div>
</div>