<?php

$customDomains = $this->getParam('customDomains', false);

?>
<div class="cover">
    <h1 class="zone xl margin-bottom-xl margin-top">
        Settings
    </h1>
</div>

<div class="zone xl"
    data-service="projects.get"
    data-scope="console"
    data-name="console-project"
    data-event="load"
    data-param-project-id="{{router.params.project}}"
    data-success="trigger"
    data-success-param-trigger-events="projects.get">

    <div class="zone xl">
        <ul class="phases clear" data-ui-phases data-selected="{{router.params.tab}}">
            <li data-state="/console/settings?project={{router.params.project}}">
                <h2>Overview</h2>

                <form
                    data-analytics-event="submit"
                    data-analytics-category="console"
                    data-analytics-label="Update Project"
                    data-service="projects.update"
                    data-scope="console"
                    data-event="submit"
                    data-param-project-id="{{router.params.project}}"
                    data-success="alert,trigger"
                    data-success-param-alert-text="Saved project successfully"
                    data-success-param-trigger-events="projects.update"
                    data-failure="alert"
                    data-failure-param-alert-text="Failed to update project"
                    data-failure-param-alert-classname="error">

                    <input name="$id" type="hidden" data-ls-bind="{{console-project.$id}}" />

                    <div class="row">
                        <div class="col span-9">
                            <div class="box">
                                <label for="name">Name</label>
                                <input name="name" id="name" type="text" autocomplete="off" data-ls-bind="{{console-project.name}}" data-forms-text-direction required>

                                <label for="name">Project ID</label>
                                <div class="input-copy">
                                    <input data-forms-copy type="text" disabled data-ls-bind="{{console-project.$id}}" />
                                </div>

                                <label for="name">API Endpoint</label>
                                <div class="input-copy">
                                    <input data-forms-copy type="text" disabled data-ls-bind="{{env.PROTOCOL}}://{{env.DOMAIN}}/v1" />
                                </div>
                                <div class="margin-top-negative-small margin-bottom text-size-small">
                                    <a data-ls-attrs="href=/console/settings/domains?project={{router.params.project}}">Add a custom domain <i class="icon-angle-circled-right"></i></a>
                                </div>
<!-- 
                                <label for="description">Description &nbsp;<small>(optional)</small></label>
                                <textarea name="description" id="description" autocomplete="off" placeholder="Help us make the world a better place" data-ls-bind="{{console-project.description}}" data-forms-text-direction data-forms-text-count></textarea>

                                <label for="url">Website &nbsp;<small>(optional)</small></label>
                                <input name="url" id="url" type="url" class="full-width" autocomplete="off" placeholder="https://acme-corp.com" data-ls-bind="{{console-project.url}}"> -->

                                <hr />

                                <button class="" type="submit">Save</button>
                            </div>
                        </div>

                        <div class="col span-3 box-aside">
                            <label for="name">Logo</label>
                            <div class="text-align-center clear">
                                <input type="hidden" name="logo" data-ls-bind="{{console-project.logo}}" data-read="<?php echo $this->escape(json_encode(['*'])); ?>" data-write="<?php echo $this->escape(json_encode(['team:{{console-project.teamId}}'])); ?>" data-accept="image/*" data-forms-upload="" data-scope="console" data-default="">
                            </div>
                        </div>
                    </div>
                </form>
            </li>
            <!-- <li data-state="/console/settings/privacy?project={{router.params.project}}">

                <form
                    data-service="projects.update"
                    data-scope="console"
                    data-event="submit"
                    data-param-project-id="{{router.params.project}}"
                    data-success="alert,trigger"
                    data-success-param-alert-text="Saved project successfully"
                    data-success-param-trigger-events="projects.update"
                    data-failure="alert"
                    data-failure-param-alert-text="Failed to update project"
                    data-failure-param-alert-classname="error">

                    <h2>Privacy & Legal</h2>

                    <div class="box margin-bottom">
                        <input name="$id" type="hidden" data-ls-bind="{{console-project.$id}}" />

                        <div class="row thin">
                            <div class="col span-6">
                                <label for="legalName">Legal Name</label>
                                <input name="legalName" id="legalName" type="text" autocomplete="off" data-ls-bind="{{console-project.legalName}}" data-forms-text-direction>

                                <label for="legalCountry">Country</label>
                                <select id="legalCountry" name="legalCountry" data-ls-bind="{{console-project.legalCountry}}" data-ls-loop="locale-countries" data-ls-as="option">
                                    <option data-ls-attrs="value={{$index}}" data-ls-bind="{{option}}"></option>
                                </select>

                                <label for="legalCity">City</label>
                                <input name="legalCity" id="legalCity" type="text" autocomplete="off" data-ls-bind="{{console-project.legalCity}}" data-forms-text-direction>
                            </div>

                            <div class="col span-6">
                                <label for="legalTaxId">Tax ID</label>
                                <input name="legalTaxId" id="legalTaxId" type="text" autocomplete="off" data-ls-bind="{{console-project.legalTaxId}}" data-forms-text-direction>

                                <label for="legalState">State</label>
                                <input name="legalState" id="legalState" type="text" autocomplete="off" data-ls-bind="{{console-project.legalState}}" data-forms-text-direction>

                                <label for="legalAddress">Address</label>
                                <input name="legalAddress" id="legalAddress" type="text" autocomplete="off" data-ls-bind="{{console-project.legalAddress}}" data-forms-text-direction>
                            </div>
                        </div>

                        <hr />

                        <button class="" type="submit">Save</button>
                    </div>
                </form>
            </li> -->
            <li data-state="/console/settings/domains?project={{router.params.project}}">
                
                <?php if(!$customDomains): ?>
                    <h2 style="display: none;">Custom Domains</h2>

                    <div class="box line margin-bottom">
                        <h3>Enable Custom Domains</h3>
                        
                        <p>To enable <?php echo APP_NAME; ?>'s custom domain feature, you have to start your server instance with a public accessable domain name.</p>
                        
                        <p>Start your <?php echo APP_NAME; ?> server container with the <b>_APP_DOMAINS_TARGET</b> enviornment variable set with a public accessable domain name that resolves to your <?php echo APP_NAME; ?> server setup.</p>
                        <p class="margin-bottom-no">The <?php echo APP_NAME; ?> server will use your target domain to validate new custom domains and will automatically generate SSL certificates for your new domains using letsencrypt certbot.</p>
                    </div>
                <?php endif; ?>

                <?php if($customDomains): ?>
                    <h2>Custom Domains</h2>

                    <div class="zone xl"
                        data-service="teams.getMemberships"
                        data-scope="console"
                        data-event="load,teams.createMembership,teams.deleteMembership"
                        data-name="members"
                        data-param-team-id="{{console-project.teamId}}"
                        data-success="trigger"
                        data-success-param-trigger-events="teams.getMemberships">

                        <div class="box margin-bottom">
                            <table class="vertical">
                                <thead>
                                    <tr>
                                        <th width="140"></th>
                                        <th width="220">Domain Name</th>
                                        <th width="160">TLS</th>
                                        <th></th>
                                        <th width="60"></th>
                                    </tr>
                                </thead>
                                <tbody data-ls-loop="members" data-ls-as="team">
                                    <tr>
                                        <td data-title="Status">
                                            <span class="tag blue"><i class="icon-ok-circled"></i>Verified&nbsp;</span> &nbsp;
                                        </td>
                                        <td data-title="Domain: ">
                                        <span xdata-ls-bind="{{member.name}}" class="text-size-small text-bold">appwrite.example.com</span>
                                        </td>
                                        <td data-title="TLS: ">
                                            <!-- <span class="tag yellow"><i class="icon-ok-circled"></i> Pending&nbsp;</span> &nbsp; -->
                                            <span class="tag green"><i class="icon-ok-circled"></i> Enabled&nbsp;</span> &nbsp;
                                        </td>
                                        <td data-title="">
                                            <a href="" class="text-size-small">DNS Settings</a>
                                        </td>
                                        <td data-title="">
                                            <form class="pull-end"
                                                data-analytics-event="submit"
                                                data-analytics-category="console"
                                                data-analytics-label="Delete Project Task"
                                                data-service="projects.deleteTask"
                                                data-scope="console"
                                                data-event="submit"
                                                data-confirm="Are you sure you want to delete this task?"
                                                data-success="alert,trigger"
                                                data-success-param-alert-text="Deleted task successfully"
                                                data-success-param-trigger-events="projects.deleteTask,modal-close"
                                                data-failure="alert"
                                                data-failure-param-alert-text="Failed to delete task"
                                                data-failure-param-alert-classname="error">

                                                <input type="hidden" name="projectId" data-ls-bind="{{router.params.project}}" />
                                                <input type="hidden" name="taskId" data-ls-bind="{{task.$id}}" />

                                                <button class="danger round reverse small"><i class="icon-trash"></i></button>
                                            </form>
                                        </td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>

                        <div class="clear">
                            <div data-ui-modal class="modal box close" data-button-text="Add Domain">
                                <button type="button" class="close pull-end" data-ui-modal-close=""><i class="icon-cancel"></i></button>

                                <h1>Add Domain</h1>

                                <form
                                    data-analytics-event="submit"
                                    data-analytics-category="console"
                                    data-analytics-label="Create Project Task"
                                    data-service="projects.createTask"
                                    data-scope="console"
                                    data-event="submit"
                                    data-success="alert,trigger,reset"
                                    data-success-param-alert-text="Created task successfully"
                                    data-success-param-trigger-events="projects.createTask,modal-close"
                                    data-failure="alert"
                                    data-failure-param-alert-text="Failed to create task"
                                    data-failure-param-alert-classname="error">

                                    <input type="hidden" name="projectId" data-ls-bind="{{router.params.project}}" />

                                    <label for="name">Domain Name</label>
                                    <input type="text" class="full-width" id="domain" name="domain" placeholder="appwrite.example.com" required autocomplete="off" />

                                    <div class="info margin-top margin-bottom">
                                        <div class="text-bold margin-bottom-small">Setup & Verify your Domain</div>
                                        <p>Add the following DNS records to your DNS provider settings to setup and verify your new custom domain.</p>
                                        
                                        <ol>
                                            <li>
                                                <p>Add a CNAME record to point your subdomain to <?php echo APP_NAME; ?> with the following value:</p>
                                                
                                                <div class="ide margin-bottom-small">
                                                    <pre class="line-numbers"><code class="prism language-javascript" data-prism>custom.appwrite.io</code></pre>
                                                </div>

                                                <p>For example:</p>

                                                <div class="ide margin-bottom-small">
                                                    <pre class="line-numbers"><code class="prism language-javascript" data-prism>appwrite.myapp.com   CNAME   custom.appwrite.io</code></pre>
                                                </div>
                                            </li>

                                            <li>Add a CNAME record to point your subdomain to <?php echo APP_NAME; ?> API
                                
                                            </li>
                                        </ol>
                                    </div>
                                    

                                    <button type="submit">Create</button> &nbsp; <button data-ui-modal-close="" type="button" class="reverse">Cancel</button>
                                </form>
                            </div>
                        </div>
                    </div>
                <?php endif; ?>
            </li>
            <li data-state="/console/settings/members?project={{router.params.project}}">
                <h2>Members</h2>

                <div class="zone xl"
                    data-service="teams.getMemberships"
                    data-scope="console"
                    data-event="load,teams.createMembership,teams.deleteMembership"
                    data-name="members"
                    data-param-team-id="{{console-project.teamId}}"
                    data-success="trigger"
                    data-success-param-trigger-events="teams.getMemberships">

                    <div class="box margin-bottom">
                        <ul data-ls-loop="members" data-ls-as="member" class="list">
                            <li class="clear">
                                <form class="pull-end"
                                    data-analytics-event="submit"
                                    data-analytics-category="console"
                                    data-analytics-label="Delete Team Membership"
                                    data-service="teams.deleteMembership"
                                    data-scope="console"
                                    data-event="submit"
                                    data-success="alert,trigger"
                                    data-success-param-alert-text="Member Removed Successfully"
                                    data-success-param-trigger-events="teams.deleteMembership"
                                    data-failure="alert"
                                    data-failure-param-alert-text="Failed to Remove Member"
                                    data-failure-param-alert-classname="error">

                                    <input name="teamId" id="teamId" type="hidden" data-ls-bind="{{console-project.teamId}}">
                                    <input name="inviteId" id="inviteId" type="hidden" data-ls-bind="{{member.$id}}">

                                    <button class="danger">Leave</button>
                                </form>
                                
                                <div data-ls-if="false === {{member.confirm}}" class="pull-end margin-end" style="display: none;">
                                    <form class="pull-end"
                                        data-analytics-event="submit"
                                        data-analytics-category="console"
                                        data-analytics-label="Create Team Membership (resend)"
                                        data-service="teams.deleteMembership"
                                        data-scope="console"
                                        data-event="submit"
                                        data-success="trigger"
                                        data-success-param-trigger-events="teams.deleteMembership.resend"
                                        data-failure="alert"
                                        data-failure-param-alert-text="Failed to Resend Invitation"
                                        data-failure-param-alert-classname="error">

                                        <input name="teamId" id="teamId" type="hidden" data-ls-bind="{{console-project.teamId}}">
                                        <input name="inviteId" id="inviteId" type="hidden" data-ls-bind="{{member.$id}}">

                                        <button class="reverse">Resend</button>
                                    </form>

                                    <form class="pull-end"
                                        data-service="teams.createMembership"
                                        data-scope="console"
                                        data-event="teams.deleteMembership.resend"
                                        data-success="alert,trigger"
                                        data-success-param-alert-text="Invitation Sent Successfully"
                                        data-success-param-trigger-events="teams.createMembership.resent"
                                        data-failure="alert"
                                        data-failure-param-alert-text="Failed to Send inivitation"
                                        data-failure-param-alert-classname="error">

                                        <input name="teamId" type="hidden" data-ls-bind="{{member.teamId}}">
                                        <input name="url" type="hidden" data-ls-bind="{{env.PROTOCOL}}://{{env.DOMAIN}}/auth/join?project={{router.params.project}}" />
                                        <input name="email" type="hidden" data-ls-bind="{{member.email}}">
                                        <input name="name" type="hidden" data-ls-bind="{{member.name}}">
                                        <input name="roles" type="hidden" data-ls-bind="{{member.roles}}" data-cast-to="json">
                                    </form>
                                </div>

                                <img src="" data-ls-attrs="src={{member|gravatar}}" data-size="200" alt="User Avatar" class="avatar pull-start margin-end" loading="lazy" width="60" height="60" />

                                <div class="margin-bottom-tiny">
                                    <span data-ls-bind="{{member.name}}"></span> &nbsp;&nbsp;<span class="tag" data-ls-bind="{{member.roles.0}}"></span> &nbsp;&nbsp;<span data-ls-if="false === {{member.confirm}}" class="tag red" style="display: none;">Pending Approval</span>
                                </div>
                                <span class="text-size-small text-fade" data-ls-bind="{{member.email}}"></small>
                            </li>
                        </ul>
                    </div>

                    <div data-ui-modal class="modal close width-medium" data-button-text="Invite Member" data-button-class="">
                        <button type="button" class="close pull-end" data-ui-modal-close><i class="icon-cancel"></i></button>

                        <h1>Invite Member</h1>

                        <form name="teams.createTeamMembership"
                            data-analytics-event="submit"
                            data-analytics-category="console"
                            data-analytics-label="Create Team Membership"
                            data-service="teams.createMembership"
                            data-scope="console"
                            data-event="submit"
                            data-loading="Sending invitation, please wait..."
                            data-success="alert,trigger,reset"
                            data-success-param-alert-text="Invitation Sent Successfully"
                            data-success-param-trigger-events="teams.createMembership,modal-close"
                            data-failure="alert"
                            data-failure-param-alert-text="Failed to Send Invite"
                            data-failure-param-alert-classname="error">

                            <input name="teamId" id="team-teamId" type="hidden" data-ls-bind="{{console-project.teamId}}">
                            <input name="url" type="hidden" data-ls-bind="{{env.PROTOCOL}}://{{env.DOMAIN}}/auth/join?project={{router.params.project}}" />
                            
                            <label for="email">Email</label>
                            <input name="email" id="email" type="email" autocomplete="email" required>
                            
                            <label for="team-name">Name <small>(optional)</small></label>
                            <input name="name" id="team-name" type="text" autocomplete="name">

                            <label for="roles" style="display: none">Role</label>
                            <select id="roles" name="roles" required data-ls-loop="env.ROLES" data-ls-as="role" data-cast-to="array" style="display: none">
                                <option data-ls-attrs="value={{role.type}}" data-ls-bind="{{role.label}}"></option>
                            </select>

                            <div class="clear">
                                <button>Send Invite</button>
                                &nbsp; <button data-ui-modal-close="" type="button" class="reverse">Cancel</button>
                            </div>
                        </form>
                    </div>
                </div>
            </li>
        </ul>
    </div>
</div>