/**
 * Legacy URL redirects ported from the old website (appwrite/website
 * src/redirects.json) so inbound links and search engine results keep working.
 *
 * Kept in sync with the old list with these adaptations:
 * - Redirect chains are flattened (e.g. `/docs/tooling/mcp/claude` points
 *   straight at the final target instead of another redirecting path).
 * - Targets that do not exist in this app are remapped to the closest
 *   equivalent (`/contact-us` -> `/enterprise`, `/customer-stories` ->
 *   `/blog/category/customer-stories`, legacy generic databases docs ->
 *   their TablesDB equivalents, `/products/sites/offer-300` ->
 *   `/products/sites`).
 * - Query-string source variants (e.g. `?sdk=web-default`) are dropped;
 *   matching is by pathname and the incoming query string is preserved on
 *   redirect.
 *
 * Matching is exact on the pathname (trailing slashes stripped). Targets may
 * include a `#hash`.
 */
const LEGACY_REDIRECTS: Record<string, string> = {
  '/docs/getting-started-for-web': '/docs/quick-starts',
  '/contact': '/enterprise',
  '/docs/server/database': '/docs/references/cloud/server-nodejs/databases',
  '/docs/getting-started-for-flutter': '/docs/quick-starts/flutter',
  '/docs/getting-started-for-apple': '/docs/quick-starts/apple',
  '/docs/getting-started-for-android': '/docs/quick-starts/android',
  '/docs/getting-started-for-server': '/docs/quick-starts',
  '/docs/self-hosting': '/docs/advanced/self-hosting',
  '/docs/client/databases': '/docs/references/cloud/client-web/databases',
  '/docs/client/account': '/docs/references/cloud/client-web/account',
  '/docs/client/storage': '/docs/references/cloud/client-web/storage',
  '/docs/functions': '/docs/products/functions',
  '/docs/realtime': '/docs/apis/realtime',
  '/docs/command-line': '/docs/tooling/command-line/installation',
  '/docs/command-line-commands': '/docs/tooling/command-line/commands',
  '/docs/command-line-ci': '/docs/tooling/command-line/non-interactive',
  '/docs/rest': '/docs/apis/rest',
  '/docs/graphql': '/docs/apis/graphql',
  '/docs/server/users': '/docs/references/cloud/server-nodejs/users',
  '/docs/client/teams': '/docs/references/cloud/client-web/teams',
  '/docs/client/functions': '/docs/references/cloud/client-web/functions',
  '/docs/client/locale': '/docs/references/cloud/client-web/locale',
  '/docs/client/avatars': '/docs/references/cloud/client-web/avatars',
  '/docs/databases': '/docs/products/databases',
  '/docs/databases-queries': '/docs/products/databases/tablesdb/queries',
  '/docs/databases-pagination': '/docs/products/databases/tablesdb/pagination',
  '/docs/databases-relationships': '/docs/products/databases/tablesdb/relationships',
  '/docs/storage': '/docs/products/storage',
  '/docs/authentication': '/docs/products/auth',
  '/docs/authentication-email-pass': '/docs/products/auth/email-password',
  '/docs/authentication-sms': '/docs/products/auth/phone-sms',
  '/docs/authentication-magic': '/docs/products/auth/magic-url',
  '/docs/authentication-oauth': '/docs/products/auth/oauth2',
  '/docs/authentication-anonymous': '/docs/products/auth/anonymous',
  '/docs/authentication-management': '/docs/products/auth/users',
  '/docs/authentication-security': '/docs/products/auth/security',
  '/docs/products/functions/development': '/docs/products/functions/develop',
  '/docs/products/functions/deployment': '/docs/products/functions/deploy-from-git',
  '/docs/products/functions/execution': '/docs/products/functions/execute',
  '/docs/functions-develop': '/docs/products/functions/develop',
  '/docs/functions-deploy': '/docs/products/functions/deploy-from-git',
  '/docs/functions-execute': '/docs/products/functions/execute',
  '/docs/functions-runtimes': '/docs/products/functions/runtimes',
  '/docs/functions-examples': '/docs/products/functions',
  '/docs/migrations': '/docs/advanced/migrations',
  '/docs/migrations-firebase': '/docs/advanced/migrations/firebase',
  '/docs/migrations-supabase': '/docs/advanced/migrations/supabase',
  '/docs/migrations-nhost': '/docs/advanced/migrations/nhost',
  '/docs/migrations-cloud-to-self-hosted': '/docs/advanced/migrations/self-hosted',
  '/docs/migrations-self-hosted-to-cloud': '/docs/advanced/migrations/cloud',
  '/docs/keys': '/docs/partners/project/api-keys',
  '/docs/permissions': '/docs/advanced/security/permissions',
  '/docs/events': '/docs/apis/events',
  '/docs/queries': '/docs/products/databases/tablesdb/queries',
  '/docs/pagination': '/docs/products/databases/tablesdb/pagination',
  '/docs/webhooks': '/docs/apis/webhooks',
  '/docs/custom-domains': '/docs/products/network/custom-domains',
  '/docs/email-and-sms-templates': '/docs/products/auth/message-templates',
  '/docs/response-codes': '/docs/apis/response-codes',
  '/docs/rate-limits': '/docs/advanced/security/rate-limits',
  '/docs/configuration': '/docs/advanced/self-hosting',
  '/docs/environment-variables': '/docs/advanced/self-hosting/configuration/environment-variables',
  '/docs/email-delivery': '/docs/advanced/self-hosting/configuration/email',
  '/docs/sms-delivery': '/docs/advanced/self-hosting/configuration/sms',
  '/docs/certificates': '/docs/advanced/self-hosting/configuration/tls-certificates',
  '/docs/debugging': '/docs/advanced/self-hosting/production/debugging',
  '/docs/upgrade': '/docs/advanced/self-hosting/production/updates',
  '/docs/production': '/docs/advanced/self-hosting/production',
  '/docs/server/databases': '/docs/references/cloud/server-nodejs/databases',
  '/docs/models/document': '/docs/references/cloud/models/document',
  '/docs/models/documentList': '/docs/references/cloud/models/documentList',
  '/docs/server/account': '/docs/references/cloud/server-nodejs/account',
  '/docs/models/user': '/docs/references/cloud/models/user',
  '/docs/models/session': '/docs/references/cloud/models/session',
  '/docs/models/identityList': '/docs/references/cloud/models/identityList',
  '/docs/models/token': '/docs/references/cloud/models/token',
  '/docs/models/jwt': '/docs/references/cloud/models/jwt',
  '/docs/models/preferences': '/docs/references/cloud/models/preferences',
  '/docs/models/sessionList': '/docs/references/cloud/models/sessionList',
  '/docs/models/logList': '/docs/references/cloud/models/logList',
  '/docs/server/storage': '/docs/references/cloud/server-nodejs/storage',
  '/docs/models/file': '/docs/references/cloud/models/file',
  '/docs/models/fileList': '/docs/references/cloud/models/fileList',
  '/docs/models/attributeList': '/docs/references/cloud/models/attributeList',
  '/docs/models/indexList': '/docs/references/cloud/models/indexList',
  '/docs/server/functions': '/docs/references/cloud/server-nodejs/functions',
  '/docs/models/userList': '/docs/references/cloud/models/userList',
  '/docs/models/membershipList': '/docs/references/cloud/models/membershipList',
  '/docs/server/teams': '/docs/references/cloud/server-nodejs/teams',
  '/docs/models/team': '/docs/references/cloud/models/team',
  '/docs/models/teamList': '/docs/references/cloud/models/teamList',
  '/docs/models/membership': '/docs/references/cloud/models/membership',
  '/docs/models/execution': '/docs/references/cloud/models/execution',
  '/docs/models/executionList': '/docs/references/cloud/models/executionList',
  '/docs/server/locale': '/docs/references/cloud/server-nodejs/locale',
  '/docs/models/locale': '/docs/references/cloud/models/locale',
  '/docs/models/localeCodeList': '/docs/references/cloud/models/localeCodeList',
  '/docs/models/countryList': '/docs/references/cloud/models/countryList',
  '/docs/models/phoneList': '/docs/references/cloud/models/phoneList',
  '/docs/models/continentList': '/docs/references/cloud/models/continentList',
  '/docs/models/currencyList': '/docs/references/cloud/models/currencyList',
  '/docs/models/languageList': '/docs/references/cloud/models/languageList',
  '/docs/server/avatars': '/docs/references/cloud/server-nodejs/avatars',
  '/docs/models/bucket': '/docs/references/cloud/models/bucket',
  '/docs/models/database': '/docs/references/cloud/models/database',
  '/docs/models/collection': '/docs/references/cloud/models/collection',
  '/docs/models/index': '/docs/references/cloud/models/index',
  '/docs/models/function': '/docs/references/cloud/models/function',
  '/docs/models/deployment': '/docs/references/cloud/models/deployment',
  '/docs/models/databaseList': '/docs/references/cloud/models/databaseList',
  '/docs/models/collectionList': '/docs/references/cloud/models/collectionList',
  '/docs/models/attributeString': '/docs/references/cloud/models/attributeString',
  '/docs/models/attributeEmail': '/docs/references/cloud/models/attributeEmail',
  '/docs/models/attributeEnum': '/docs/references/cloud/models/attributeEnum',
  '/docs/models/attributeIp': '/docs/references/cloud/models/attributeIp',
  '/docs/models/attributeUrl': '/docs/references/cloud/models/attributeUrl',
  '/docs/models/attributeInteger': '/docs/references/cloud/models/attributeInteger',
  '/docs/models/attributeFloat': '/docs/references/cloud/models/attributeFloat',
  '/docs/models/attributeBoolean': '/docs/references/cloud/models/attributeBoolean',
  '/docs/models/attributeDatetime': '/docs/references/cloud/models/attributeDatetime',
  '/docs/models/attributeRelationship': '/docs/references/cloud/models/attributeRelationship',
  '/docs/models/algoArgon2': '/docs/references/cloud/models/algoArgon2',
  '/docs/models/algoScrypt': '/docs/references/cloud/models/algoScrypt',
  '/docs/models/algoScryptModified': '/docs/references/cloud/models/algoScryptModified',
  '/docs/models/algoBcrypt': '/docs/references/cloud/models/algoBcrypt',
  '/docs/models/algoPhpass': '/docs/references/cloud/models/algoPhpass',
  '/docs/models/algoSha': '/docs/references/cloud/models/algoSha',
  '/docs/models/algoMd5': '/docs/references/cloud/models/algoMd5',
  '/docs/models/identity': '/docs/references/cloud/models/identity',
  '/docs/models/log': '/docs/references/cloud/models/log',
  '/docs/models/bucketList': '/docs/references/cloud/models/bucketList',
  '/docs/models/functionList': '/docs/references/cloud/models/functionList',
  '/docs/models/runtimeList': '/docs/references/cloud/models/runtimeList',
  '/docs/models/deploymentList': '/docs/references/cloud/models/deploymentList',
  '/docs/models/variable': '/docs/references/cloud/models/variable',
  '/docs/models/variableList': '/docs/references/cloud/models/variableList',
  '/docs/models/headers': '/docs/references/cloud/models/headers',
  '/docs/models/localeCode': '/docs/references/cloud/models/localeCode',
  '/docs/models/country': '/docs/references/cloud/models/country',
  '/docs/models/phone': '/docs/references/cloud/models/phone',
  '/docs/models/continent': '/docs/references/cloud/models/continent',
  '/docs/models/currency': '/docs/references/cloud/models/currency',
  '/docs/models/language': '/docs/references/cloud/models/language',
  '/docs/models/runtime': '/docs/references/cloud/models/runtime',
  '/docs/installation': '/docs/advanced/self-hosting',
  '/keyboard': '/docs/tooling/appwriter',
  '/policy/terms': '/terms',
  '/policy/privacy': '/privacy',
  '/case-studies': '/blog/category/customer-stories',
  '/blog/category/case-studies': '/blog/category/customer-stories',
  '/blog/post/case-study-smartbee': '/blog/post/customer-stories-smartbee',
  '/blog/post/case-study-kcollect': '/blog/post/customer-stories-kcollect',
  '/blog/post/case-study-majik-kids': '/blog/post/customer-stories-majik-kids',
  '/blog/post/case-study-myshoefitter': '/blog/post/customer-stories-myshoefitter',
  '/blog/post/case-study-open-mind': '/blog/post/customer-stories-open-mind',
  '/blog/post/case-study-langx': '/blog/post/customer-stories-langx',
  '/blog/post/case-study-undo': '/blog/post/customer-stories-undo',
  '/blog/post/top-5-tips-to-build-an-AI-agent-startup': '/blog/post/ai-agent-startup-tips',
  '/blog/post/5-MCP-startup-ideas-to-build-in-2025': '/blog/post/mcp-startup-ideas',
  '/blog/post/10-open-source-alternatives-to-popular-software-for-startups': '/blog/post/open-source-startup-tools',
  '/blog/post/the-shift-from-SaaS-to-Vertical-AI-what-startup-founders-need-to-know': '/blog/post/saas-to-vertical-ai',
  '/blog/post/how-can-you-rapidly-build-an-mvp-for-your-startup': '/blog/post/startup-mvp-guide',
  '/docs/tooling/command-line/collections': '/docs/tooling/command-line/tables',
  '/docs/tooling/terraform/databases': '/docs/tooling/terraform/resources/databases',
  '/docs/tooling/mcp/mcp-for-docs': '/docs/tooling/ai/mcp-servers/docs',
  '/docs/tooling/mcp/claude': '/docs/tooling/ai/vibe-coding/claude-desktop',
  '/docs/advanced/self-hosting/debug': '/docs/advanced/self-hosting/production/debugging',
  '/docs/advanced/self-hosting/update': '/docs/advanced/self-hosting/production/updates',
  '/docs/advanced/self-hosting/functions': '/docs/advanced/self-hosting/configuration/functions',
  '/docs/advanced/self-hosting/tls-certificates': '/docs/advanced/self-hosting/configuration/tls-certificates',
  '/docs/advanced/self-hosting/storage': '/docs/advanced/self-hosting/configuration/storage',
  '/docs/advanced/self-hosting/sites': '/docs/advanced/self-hosting/configuration/sites',
  '/docs/advanced/self-hosting/sms': '/docs/advanced/self-hosting/configuration/sms',
  '/docs/advanced/self-hosting/email': '/docs/advanced/self-hosting/configuration/email',
  '/docs/advanced/self-hosting/coolify': '/docs/advanced/self-hosting/platforms/coolify',
  '/docs/advanced/self-hosting/environment-variables': '/docs/advanced/self-hosting/configuration/environment-variables',
  '/products/sites/offer-300-s': '/products/sites',
  '/docs/products/auth/preferences-storage': '/docs/products/auth/preferences',
  '/docs/tooling/mcp': '/docs/tooling/ai/mcp-servers',
  '/docs/tooling/mcp/cursor': '/docs/tooling/ai/agents/cursor',
  '/docs/tooling/mcp/vscode': '/docs/tooling/ai/agents/vscode',
  '/docs/tooling/mcp/windsurf': '/docs/tooling/ai/agents/windsurf',
  '/docs/tooling/mcp/opencode': '/docs/tooling/ai/agents/opencode',
  '/docs/tooling/mcp/antigravity': '/docs/tooling/ai/agents/antigravity',
  '/docs/tooling/mcp/claude-code': '/docs/tooling/ai/agents/claude-code',
  '/docs/tooling/mcp/claude-desktop': '/docs/tooling/ai/vibe-coding/claude-desktop',
  '/docs/tooling/mcp/api': '/docs/tooling/ai/mcp-servers/api',
  '/docs/tooling/mcp/docs': '/docs/tooling/ai/mcp-servers/docs',
  '/docs/tooling/skills': '/docs/tooling/ai/skills',
  '/docs/tooling/arena': '/docs/tooling/ai/arena',
  '/docs/tooling/assistant': '/docs/tooling/ai/assistant',
  '/docs/tooling/mcp/zenflow': '/docs/tooling/ai/vibe-coding/zenflow',
  '/docs/tooling/ai/ai-dev-tools': '/docs/tooling/ai',
  '/docs/tooling/ai/ai-dev-tools/claude-code': '/docs/tooling/ai/agents/claude-code',
  '/docs/tooling/ai/ai-dev-tools/codex': '/docs/tooling/ai/agents/codex',
  '/docs/tooling/ai/ai-dev-tools/cursor': '/docs/tooling/ai/agents/cursor',
  '/docs/tooling/ai/ai-dev-tools/vscode': '/docs/tooling/ai/agents/vscode',
  '/docs/tooling/ai/ai-dev-tools/opencode': '/docs/tooling/ai/agents/opencode',
  '/docs/tooling/ai/ai-dev-tools/antigravity': '/docs/tooling/ai/agents/antigravity',
  '/docs/tooling/ai/ai-dev-tools/windsurf': '/docs/tooling/ai/agents/windsurf',
  '/docs/tooling/ai/ai-dev-tools/claude-desktop': '/docs/tooling/ai/vibe-coding/claude-desktop',
  '/docs/tooling/ai/ai-dev-tools/lovable': '/docs/tooling/ai/vibe-coding/lovable',
  '/docs/tooling/ai/ai-dev-tools/emergent': '/docs/tooling/ai/vibe-coding/emergent',
  '/docs/tooling/ai/ai-dev-tools/bolt': '/docs/tooling/ai/vibe-coding/bolt',
  '/docs/tooling/ai/ai-dev-tools/zenflow': '/docs/tooling/ai/vibe-coding/zenflow',
  '/install/compose': '/docs/advanced/self-hosting/installation#manual-installation',
  '/install/env': '/docs/advanced/self-hosting/installation#manual-installation',
  '/the-appwrite-network': '/docs/products/network',
  '/blog/post/backend-as-a-service-baas': '/blog/post/backend-as-a-service',
  '/blog/post/baas-backend-as-a-service-explained-when-should-you-use-it': '/blog/post/backend-as-a-service',
  '/blog/post/choosing-the-right-baas-in-2025': '/blog/post/backend-as-a-service',
  '/blog/post/choosing-the-right-backend': '/blog/post/backend-as-a-service',
  '/heroes': '/',
  '/docs/advanced/platform': '/docs',
  '/docs/advanced/platform/billing': '/docs/advanced/billing/payments',
  '/docs/advanced/platform/free': '/docs/advanced/billing/free',
  '/docs/advanced/platform/pro': '/docs/advanced/billing/pro',
  '/docs/advanced/platform/scale': '/docs/advanced/billing/pro',
  '/docs/advanced/platform/enterprise': '/docs/advanced/billing/enterprise',
  '/docs/advanced/platform/oss': '/docs/advanced/billing/oss',
  '/docs/advanced/platform/compute': '/docs/advanced/billing/compute',
  '/docs/advanced/platform/phone-otp': '/docs/advanced/billing/phone-otp',
  '/docs/advanced/platform/image-transformations': '/docs/advanced/billing/image-transformations',
  '/docs/advanced/platform/database-reads-and-writes': '/docs/advanced/billing/database-reads-and-writes',
  '/docs/advanced/platform/support-sla': '/docs/advanced/billing/support-sla',
  '/docs/advanced/platform/uptime-sla': '/docs/advanced/billing/uptime-sla',
  '/docs/advanced/platform/fair-use-policy': '/docs/advanced/billing/fair-use-policy',
  '/docs/advanced/platform/abuse': '/docs/advanced/billing/abuse',
  '/docs/advanced/platform/refund-policy': '/docs/advanced/billing/refund-policy',
  '/docs/advanced/platform/events': '/docs/apis/events',
  '/docs/advanced/platform/webhooks': '/docs/apis/webhooks',
  '/docs/advanced/platform/response-codes': '/docs/apis/response-codes',
  '/docs/advanced/platform/error-handling': '/docs/apis/response-codes#error-handling',
  '/docs/advanced/platform/release-policy': '/docs/apis/release-policy',
  '/docs/advanced/release-policy': '/docs/apis/release-policy',
  '/docs/advanced/platform/permissions': '/docs/advanced/security/permissions',
  '/docs/advanced/platform/rate-limits': '/docs/advanced/security/rate-limits',
  '/docs/advanced/platform/api-keys': '/docs/partners/project/api-keys',
  '/docs/advanced/security/api-keys': '/docs/partners/project/api-keys',
  '/docs/advanced/platform/dev-keys': '/docs/advanced/security/dev-keys',
  '/docs/advanced/platform/roles': '/docs/advanced/security/roles',
  '/docs/advanced/platform/message-templates': '/docs/products/auth/message-templates',
  '/docs/advanced/platform/custom-domains': '/docs/products/network/custom-domains',
  '/docs/advanced/platform/shortcuts': '/docs/tooling/command-center/shortcuts',
  '/docs/advanced/platform/environment-variables': '/docs/partners/project/environment-variables',
  '/docs/advanced/security/environment-variables': '/docs/partners/project/environment-variables',
  '/docs/advanced/integration': '/docs/apis/rest',
}

/**
 * Returns the redirect target (pathname, optionally with `#hash`) for a legacy
 * URL pathname, or null when the path has no legacy redirect. Matching strips
 * trailing slashes; query strings are the caller's responsibility to preserve.
 */
export function getLegacyRedirectTarget(pathname: string): string | null {
  const normalized = pathname.replace(/\/+$/, '') || '/'
  return LEGACY_REDIRECTS[normalized] ?? null
}
