import { Cpu, GitBranch, Hammer, Play, Settings } from 'lucide-react'
import type { ResourceSettingsNavItem } from '../../shared/ProjectResourceSettingsShell'

export const FUNCTION_SETTINGS_NAV: ResourceSettingsNavItem[] = [
  {
    id: 'general',
    label: 'General',
    pathSuffix: '',
    icon: Settings,
    keywords: [
      'general',
      'name',
      'identity',
      'enabled',
      'status',
      'disabled',
      'details',
      'id',
      'copy',
      'created',
      'updated',
      'identifiers',
      'delete',
      'remove',
      'trash',
      'destroy',
      'danger',
    ],
  },
  {
    id: 'git',
    label: 'Version control (Git)',
    pathSuffix: 'git',
    icon: GitBranch,
    keywords: [
      'git',
      'github',
      'repository',
      'branch',
      'vcs',
      'silent',
      'silent mode',
      'comments',
      'commits',
      'pull request',
      'integration',
      'connect',
      'disconnect',
      'root directory',
      'production',
      'deployment',
    ],
  },
  {
    id: 'build',
    label: 'Build',
    pathSuffix: 'build',
    icon: Hammer,
    keywords: [
      'build',
      'commands',
      'install',
      'package',
      'specification',
      'framework',
      'adapter',
      'output',
      'docker',
      'compile',
      'script',
      'profile',
      'vcpu',
      'memory',
      'worker',
      'deployment',
      'retention',
      'cleanup',
      'inactive',
      'forever',
      'triggers',
      'branch filter',
      'path filter',
      'glob',
      'pattern',
    ],
  },
  {
    id: 'runtime',
    label: 'Runtime',
    pathSuffix: 'runtime',
    icon: Cpu,
    keywords: [
      'runtime',
      'image',
      'entrypoint',
      'timeout',
      'logging',
      'specification',
      'vcpu',
      'memory',
      'execute',
      'invoke',
      'variables',
      'environment',
    ],
  },
  {
    id: 'executions',
    label: 'Executions',
    pathSuffix: 'executions',
    icon: Play,
    keywords: [
      'executions',
      'execution',
      'schedule',
      'cron',
      'events',
      'webhook',
      'trigger',
      'invoke',
      'async',
    ],
  },
]
