<?php

use Utopia\Database\Attribute;
use Utopia\Database\Database;
use Utopia\Database\Index;
use Utopia\Query\Schema\ColumnType;
use Utopia\Query\Schema\IndexType;

return [
    'cache' => [
        '$collection' => '_metadata',
        '$id' => 'cache',
        'name' => 'Cache',
        'attributes' => [
            new Attribute(
                key: 'resource',
                type: ColumnType::String,
                size: Database::LENGTH_KEY,
            ),
            new Attribute(
                key: 'resourceType',
                type: ColumnType::String,
                size: Database::LENGTH_KEY,
            ),
            new Attribute(
                key: 'mimeType',
                type: ColumnType::String,
                size: Database::LENGTH_KEY,
            ),
            new Attribute(
                key: 'accessedAt',
                type: ColumnType::Datetime,
                signed: false,
                filters: ['datetime'],
            ),
            new Attribute(
                key: 'signature',
                type: ColumnType::String,
                size: Database::LENGTH_KEY,
            ),
        ],
        'indexes' => [
            new Index(
                key: '_key_accessedAt',
                type: IndexType::Key,
                attributes: ['accessedAt'],
            ),
            new Index(
                key: '_key_resource',
                type: IndexType::Key,
                attributes: ['resource'],
            ),
        ],
    ],
    'users' => [
        '$collection' => '_metadata',
        '$id' => 'users',
        'name' => 'Users',
        'attributes' => [
            new Attribute(
                key: 'name',
                type: ColumnType::String,
                size: 256,
            ),
            new Attribute(
                key: 'email',
                type: ColumnType::String,
                size: 320,
            ),
            new Attribute(
                key: 'phone',
                type: ColumnType::String,
                size: 16,
            ),
            new Attribute(
                key: 'status',
                type: ColumnType::Boolean,
            ),
            new Attribute(
                key: 'labels',
                type: ColumnType::String,
                size: 128,
                array: true,
            ),
            new Attribute(
                key: 'passwordHistory',
                type: ColumnType::String,
                size: 16384,
                array: true,
            ),
            new Attribute(
                key: 'password',
                type: ColumnType::String,
                size: 16384,
                filters: ['encrypt'],
            ),
            new Attribute(
                key: 'hash',
                type: ColumnType::String,
                size: 256,
                default: 'argon2',
            ),
            new Attribute(
                key: 'hashOptions',
                type: ColumnType::String,
                size: 65535,
                default: ['type' => 'argon2', 'memory_cost' => 65536, 'time_cost' => 4, 'threads' => 3],
                filters: ['json'],
            ),
            new Attribute(
                key: 'passwordUpdate',
                type: ColumnType::Datetime,
                signed: false,
                filters: ['datetime'],
            ),
            new Attribute(
                key: 'prefs',
                type: ColumnType::String,
                size: 65535,
                default: (object) array(
                ),
                filters: ['json'],
            ),
            new Attribute(
                key: 'registration',
                type: ColumnType::Datetime,
                signed: false,
                filters: ['datetime'],
            ),
            new Attribute(
                key: 'emailVerification',
                type: ColumnType::Boolean,
            ),
            new Attribute(
                key: 'phoneVerification',
                type: ColumnType::Boolean,
            ),
            new Attribute(
                key: 'reset',
                type: ColumnType::Boolean,
            ),
            new Attribute(
                key: 'mfa',
                type: ColumnType::Boolean,
            ),
            new Attribute(
                key: 'mfaRecoveryCodes',
                type: ColumnType::String,
                size: 256,
                default: [],
                array: true,
                filters: ['encrypt'],
            ),
            new Attribute(
                key: 'authenticators',
                type: ColumnType::String,
                size: 16384,
                filters: ['subQueryAuthenticators'],
            ),
            new Attribute(
                key: 'sessions',
                type: ColumnType::String,
                size: 16384,
                filters: ['subQuerySessions'],
            ),
            new Attribute(
                key: 'tokens',
                type: ColumnType::String,
                size: 16384,
                filters: ['subQueryTokens'],
            ),
            new Attribute(
                key: 'challenges',
                type: ColumnType::String,
                size: 16384,
                filters: ['subQueryChallenges'],
            ),
            new Attribute(
                key: 'memberships',
                type: ColumnType::String,
                size: 16384,
                filters: ['subQueryMemberships'],
            ),
            new Attribute(
                key: 'targets',
                type: ColumnType::String,
                size: 16384,
                filters: ['subQueryTargets'],
            ),
            new Attribute(
                key: 'search',
                type: ColumnType::String,
                size: 16384,
                filters: ['userSearch'],
            ),
            new Attribute(
                key: 'accessedAt',
                type: ColumnType::Datetime,
                signed: false,
                filters: ['datetime'],
            ),
            new Attribute(
                key: 'emailCanonical',
                type: ColumnType::String,
                size: 320,
            ),
            new Attribute(
                key: 'emailIsFree',
                type: ColumnType::Boolean,
            ),
            new Attribute(
                key: 'emailIsDisposable',
                type: ColumnType::Boolean,
            ),
            new Attribute(
                key: 'emailIsCorporate',
                type: ColumnType::Boolean,
            ),
            new Attribute(
                key: 'emailIsCanonical',
                type: ColumnType::Boolean,
            ),
            new Attribute(
                key: 'impersonator',
                type: ColumnType::Boolean,
                default: false,
            ),
        ],
        'indexes' => [
            new Index(
                key: '_key_name',
                type: IndexType::Key,
                attributes: ['name'],
                lengths: [256],
                orders: ['ASC'],
            ),
            new Index(
                key: '_key_email',
                type: IndexType::Unique,
                attributes: ['email'],
                lengths: [256],
                orders: ['ASC'],
            ),
            new Index(
                key: '_key_phone',
                type: IndexType::Unique,
                attributes: ['phone'],
                lengths: [16],
                orders: ['ASC'],
            ),
            new Index(
                key: '_key_status',
                type: IndexType::Key,
                attributes: ['status'],
                orders: ['ASC'],
            ),
            new Index(
                key: '_key_passwordUpdate',
                type: IndexType::Key,
                attributes: ['passwordUpdate'],
                orders: ['ASC'],
            ),
            new Index(
                key: '_key_registration',
                type: IndexType::Key,
                attributes: ['registration'],
                orders: ['ASC'],
            ),
            new Index(
                key: '_key_emailVerification',
                type: IndexType::Key,
                attributes: ['emailVerification'],
                orders: ['ASC'],
            ),
            new Index(
                key: '_key_phoneVerification',
                type: IndexType::Key,
                attributes: ['phoneVerification'],
                orders: ['ASC'],
            ),
            new Index(
                key: '_key_search',
                type: IndexType::Fulltext,
                attributes: ['search'],
            ),
            new Index(
                key: '_key_accessedAt',
                type: IndexType::Key,
                attributes: ['accessedAt'],
            ),
            new Index(
                key: 'impersonator',
                type: IndexType::Key,
                attributes: ['impersonator'],
            ),
        ],
    ],
    'tokens' => [
        '$collection' => '_metadata',
        '$id' => 'tokens',
        'name' => 'Tokens',
        'attributes' => [
            new Attribute(
                key: 'userInternalId',
                type: ColumnType::String,
                size: Database::LENGTH_KEY,
                required: true,
            ),
            new Attribute(
                key: 'userId',
                type: ColumnType::String,
                size: Database::LENGTH_KEY,
            ),
            new Attribute(
                key: 'type',
                type: ColumnType::Integer,
                required: true,
            ),
            new Attribute(
                key: 'secret',
                type: ColumnType::String,
                size: 512,
                filters: ['encrypt'],
            ),
            new Attribute(
                key: 'expire',
                type: ColumnType::Datetime,
                signed: false,
                filters: ['datetime'],
            ),
            new Attribute(
                key: 'userAgent',
                type: ColumnType::String,
                size: 16384,
            ),
            new Attribute(
                key: 'ip',
                type: ColumnType::String,
                size: 45,
            ),
        ],
        'indexes' => [
            new Index(
                key: '_key_user',
                type: IndexType::Key,
                attributes: ['userInternalId'],
                lengths: [255],
                orders: ['ASC'],
            ),
        ],
    ],
    'authenticators' => [
        '$collection' => '_metadata',
        '$id' => 'authenticators',
        'name' => 'Authenticators',
        'attributes' => [
            new Attribute(
                key: 'userInternalId',
                type: ColumnType::String,
                size: Database::LENGTH_KEY,
            ),
            new Attribute(
                key: 'userId',
                type: ColumnType::String,
                size: Database::LENGTH_KEY,
            ),
            new Attribute(
                key: 'type',
                type: ColumnType::String,
                size: Database::LENGTH_KEY,
            ),
            new Attribute(
                key: 'verified',
                type: ColumnType::Boolean,
                default: false,
            ),
            new Attribute(
                key: 'data',
                type: ColumnType::String,
                size: 65535,
                default: [],
                filters: ['json', 'encrypt'],
            ),
        ],
        'indexes' => [
            new Index(
                key: '_key_userInternalId',
                type: IndexType::Key,
                attributes: ['userInternalId'],
                lengths: [255],
                orders: ['ASC'],
            ),
        ],
    ],
    'challenges' => [
        '$collection' => '_metadata',
        '$id' => 'challenges',
        'name' => 'Challenges',
        'attributes' => [
            new Attribute(
                key: 'userInternalId',
                type: ColumnType::String,
                size: Database::LENGTH_KEY,
            ),
            new Attribute(
                key: 'userId',
                type: ColumnType::String,
                size: Database::LENGTH_KEY,
            ),
            new Attribute(
                key: 'type',
                type: ColumnType::String,
                size: Database::LENGTH_KEY,
            ),
            new Attribute(
                key: 'token',
                type: ColumnType::String,
                size: 512,
                filters: ['encrypt'],
            ),
            new Attribute(
                key: 'code',
                type: ColumnType::String,
                size: 512,
                filters: ['encrypt'],
            ),
            new Attribute(
                key: 'expire',
                type: ColumnType::Datetime,
                signed: false,
                filters: ['datetime'],
            ),
        ],
        'indexes' => [
            new Index(
                key: '_key_user',
                type: IndexType::Key,
                attributes: ['userInternalId'],
                lengths: [255],
                orders: ['ASC'],
            ),
        ],
    ],
    'sessions' => [
        '$collection' => '_metadata',
        '$id' => 'sessions',
        'name' => 'Sessions',
        'attributes' => [
            new Attribute(
                key: 'userInternalId',
                type: ColumnType::String,
                size: Database::LENGTH_KEY,
                required: true,
            ),
            new Attribute(
                key: 'userId',
                type: ColumnType::String,
                size: Database::LENGTH_KEY,
            ),
            new Attribute(
                key: 'provider',
                type: ColumnType::String,
                size: 128,
            ),
            new Attribute(
                key: 'providerUid',
                type: ColumnType::String,
                size: 2048,
            ),
            new Attribute(
                key: 'providerAccessToken',
                type: ColumnType::String,
                size: 16384,
                filters: ['encrypt'],
            ),
            new Attribute(
                key: 'providerAccessTokenExpiry',
                type: ColumnType::Datetime,
                signed: false,
                filters: ['datetime'],
            ),
            new Attribute(
                key: 'providerRefreshToken',
                type: ColumnType::String,
                size: 16384,
                filters: ['encrypt'],
            ),
            new Attribute(
                key: 'secret',
                type: ColumnType::String,
                size: 512,
                filters: ['encrypt'],
            ),
            new Attribute(
                key: 'userAgent',
                type: ColumnType::String,
                size: 16384,
            ),
            new Attribute(
                key: 'ip',
                type: ColumnType::String,
                size: 45,
            ),
            new Attribute(
                key: 'countryCode',
                type: ColumnType::String,
                size: 2,
            ),
            new Attribute(
                key: 'osCode',
                type: ColumnType::String,
                size: 256,
            ),
            new Attribute(
                key: 'osName',
                type: ColumnType::String,
                size: 256,
            ),
            new Attribute(
                key: 'osVersion',
                type: ColumnType::String,
                size: 256,
            ),
            new Attribute(
                key: 'clientType',
                type: ColumnType::String,
                size: 256,
            ),
            new Attribute(
                key: 'clientCode',
                type: ColumnType::String,
                size: 256,
            ),
            new Attribute(
                key: 'clientName',
                type: ColumnType::String,
                size: 256,
            ),
            new Attribute(
                key: 'clientVersion',
                type: ColumnType::String,
                size: 256,
            ),
            new Attribute(
                key: 'clientEngine',
                type: ColumnType::String,
                size: 256,
            ),
            new Attribute(
                key: 'clientEngineVersion',
                type: ColumnType::String,
                size: 256,
            ),
            new Attribute(
                key: 'deviceName',
                type: ColumnType::String,
                size: 256,
            ),
            new Attribute(
                key: 'deviceBrand',
                type: ColumnType::String,
                size: 256,
            ),
            new Attribute(
                key: 'deviceModel',
                type: ColumnType::String,
                size: 256,
            ),
            new Attribute(
                key: 'factors',
                type: ColumnType::String,
                size: 256,
                default: [],
                array: true,
            ),
            new Attribute(
                key: 'expire',
                type: ColumnType::Datetime,
                required: true,
                signed: false,
                filters: ['datetime'],
            ),
            new Attribute(
                key: 'mfaUpdatedAt',
                type: ColumnType::Datetime,
                signed: false,
                filters: ['datetime'],
            ),
        ],
        'indexes' => [
            new Index(
                key: '_key_provider_providerUid',
                type: IndexType::Key,
                attributes: ['provider', 'providerUid'],
                lengths: [128, 128],
                orders: ['ASC', 'ASC'],
            ),
            new Index(
                key: '_key_user',
                type: IndexType::Key,
                attributes: ['userInternalId'],
                lengths: [255],
                orders: ['ASC'],
            ),
        ],
    ],
    'identities' => [
        '$collection' => '_metadata',
        '$id' => 'identities',
        'name' => 'Identities',
        'attributes' => [
            new Attribute(
                key: 'userInternalId',
                type: ColumnType::String,
                size: Database::LENGTH_KEY,
            ),
            new Attribute(
                key: 'userId',
                type: ColumnType::String,
                size: Database::LENGTH_KEY,
            ),
            new Attribute(
                key: 'provider',
                type: ColumnType::String,
                size: 128,
            ),
            new Attribute(
                key: 'providerUid',
                type: ColumnType::String,
                size: 2048,
            ),
            new Attribute(
                key: 'providerEmail',
                type: ColumnType::String,
                size: 320,
            ),
            new Attribute(
                key: 'providerAccessToken',
                type: ColumnType::String,
                size: 16384,
                filters: ['encrypt'],
            ),
            new Attribute(
                key: 'providerAccessTokenExpiry',
                type: ColumnType::Datetime,
                signed: false,
                filters: ['datetime'],
            ),
            new Attribute(
                key: 'providerRefreshToken',
                type: ColumnType::String,
                size: 16384,
                filters: ['encrypt'],
            ),
            new Attribute(
                key: 'secrets',
                type: ColumnType::String,
                size: 16384,
                default: [],
                filters: ['json', 'encrypt'],
            ),
            new Attribute(
                key: 'scopes',
                type: ColumnType::String,
                size: Database::LENGTH_KEY,
                array: true,
            ),
            new Attribute(
                key: 'expire',
                type: ColumnType::Datetime,
                signed: false,
                filters: ['datetime'],
            ),
        ],
        'indexes' => [
            new Index(
                key: '_key_userInternalId_provider_providerUid',
                type: IndexType::Unique,
                attributes: ['userInternalId', 'provider', 'providerUid'],
                lengths: [11, 128, 128],
                orders: ['ASC', 'ASC'],
            ),
            new Index(
                key: '_key_provider_providerUid',
                type: IndexType::Unique,
                attributes: ['provider', 'providerUid'],
                lengths: [128, 128],
                orders: ['ASC', 'ASC'],
            ),
            new Index(
                key: '_key_userId',
                type: IndexType::Key,
                attributes: ['userId'],
                lengths: [255],
                orders: ['ASC'],
            ),
            new Index(
                key: '_key_userInternalId',
                type: IndexType::Key,
                attributes: ['userInternalId'],
                lengths: [255],
                orders: ['ASC'],
            ),
            new Index(
                key: '_key_provider',
                type: IndexType::Key,
                attributes: ['provider'],
                lengths: [128],
                orders: ['ASC'],
            ),
            new Index(
                key: '_key_providerUid',
                type: IndexType::Key,
                attributes: ['providerUid'],
                lengths: [255],
                orders: ['ASC'],
            ),
            new Index(
                key: '_key_providerEmail',
                type: IndexType::Key,
                attributes: ['providerEmail'],
                lengths: [255],
                orders: ['ASC'],
            ),
            new Index(
                key: '_key_providerAccessTokenExpiry',
                type: IndexType::Key,
                attributes: ['providerAccessTokenExpiry'],
                orders: ['ASC'],
            ),
        ],
    ],
    'teams' => [
        '$collection' => '_metadata',
        '$id' => 'teams',
        'name' => 'Teams',
        'attributes' => [
            new Attribute(
                key: 'name',
                type: ColumnType::String,
                size: 128,
            ),
            new Attribute(
                key: 'total',
                type: ColumnType::Integer,
            ),
            new Attribute(
                key: 'search',
                type: ColumnType::String,
                size: 16384,
            ),
            new Attribute(
                key: 'prefs',
                type: ColumnType::String,
                size: 65535,
                default: (object) array(
                ),
                filters: ['json'],
            ),
            new Attribute(
                key: 'labels',
                type: ColumnType::String,
                size: 128,
                array: true,
            ),
        ],
        'indexes' => [
            new Index(
                key: '_key_search',
                type: IndexType::Fulltext,
                attributes: ['search'],
            ),
            new Index(
                key: '_key_name',
                type: IndexType::Key,
                attributes: ['name'],
                lengths: [128],
                orders: ['ASC'],
            ),
            new Index(
                key: '_key_total',
                type: IndexType::Key,
                attributes: ['total'],
                orders: ['ASC'],
            ),
        ],
    ],
    'memberships' => [
        '$collection' => '_metadata',
        '$id' => 'memberships',
        'name' => 'Memberships',
        'attributes' => [
            new Attribute(
                key: 'userInternalId',
                type: ColumnType::String,
                size: Database::LENGTH_KEY,
                required: true,
            ),
            new Attribute(
                key: 'userId',
                type: ColumnType::String,
                size: Database::LENGTH_KEY,
            ),
            new Attribute(
                key: 'teamInternalId',
                type: ColumnType::String,
                size: Database::LENGTH_KEY,
                required: true,
            ),
            new Attribute(
                key: 'teamId',
                type: ColumnType::String,
                size: Database::LENGTH_KEY,
            ),
            new Attribute(
                key: 'roles',
                type: ColumnType::String,
                size: 128,
                array: true,
            ),
            new Attribute(
                key: 'invited',
                type: ColumnType::Datetime,
                signed: false,
                filters: ['datetime'],
            ),
            new Attribute(
                key: 'joined',
                type: ColumnType::Datetime,
                signed: false,
                filters: ['datetime'],
            ),
            new Attribute(
                key: 'confirm',
                type: ColumnType::Boolean,
            ),
            new Attribute(
                key: 'secret',
                type: ColumnType::String,
                size: 256,
                filters: ['encrypt'],
            ),
            new Attribute(
                key: 'search',
                type: ColumnType::String,
                size: 16384,
            ),
        ],
        'indexes' => [
            new Index(
                key: '_key_unique',
                type: IndexType::Unique,
                attributes: ['teamInternalId', 'userInternalId'],
                lengths: [255, 255],
                orders: ['ASC', 'ASC'],
            ),
            new Index(
                key: '_key_user',
                type: IndexType::Key,
                attributes: ['userInternalId'],
                lengths: [255],
                orders: ['ASC'],
            ),
            new Index(
                key: '_key_team',
                type: IndexType::Key,
                attributes: ['teamInternalId'],
                lengths: [255],
                orders: ['ASC'],
            ),
            new Index(
                key: '_key_search',
                type: IndexType::Fulltext,
                attributes: ['search'],
            ),
            new Index(
                key: '_key_userId',
                type: IndexType::Key,
                attributes: ['userId'],
                lengths: [255],
                orders: ['ASC'],
            ),
            new Index(
                key: '_key_teamId',
                type: IndexType::Key,
                attributes: ['teamId'],
                lengths: [255],
                orders: ['ASC'],
            ),
            new Index(
                key: '_key_invited',
                type: IndexType::Key,
                attributes: ['invited'],
                orders: ['ASC'],
            ),
            new Index(
                key: '_key_joined',
                type: IndexType::Key,
                attributes: ['joined'],
                orders: ['ASC'],
            ),
            new Index(
                key: '_key_confirm',
                type: IndexType::Key,
                attributes: ['confirm'],
                orders: ['ASC'],
            ),
        ],
    ],
    'buckets' => [
        '$collection' => '_metadata',
        '$id' => 'buckets',
        'name' => 'Buckets',
        'attributes' => [
            new Attribute(
                key: 'enabled',
                type: ColumnType::Boolean,
                required: true,
            ),
            new Attribute(
                key: 'name',
                type: ColumnType::String,
                size: 128,
                required: true,
            ),
            new Attribute(
                key: 'fileSecurity',
                type: ColumnType::Boolean,
                size: 1,
            ),
            new Attribute(
                key: 'maximumFileSize',
                type: ColumnType::Integer,
                size: 8,
                required: true,
                signed: false,
            ),
            new Attribute(
                key: 'allowedFileExtensions',
                type: ColumnType::String,
                size: 64,
                required: true,
                array: true,
            ),
            new Attribute(
                key: 'compression',
                type: ColumnType::String,
                size: 10,
                required: true,
            ),
            new Attribute(
                key: 'encryption',
                type: ColumnType::Boolean,
                required: true,
            ),
            new Attribute(
                key: 'antivirus',
                type: ColumnType::Boolean,
                required: true,
            ),
            new Attribute(
                key: 'transformations',
                type: ColumnType::Boolean,
                default: true,
            ),
            new Attribute(
                key: 'search',
                type: ColumnType::String,
                size: 16384,
            ),
        ],
        'indexes' => [
            new Index(
                key: '_key_search',
                type: IndexType::Fulltext,
                attributes: ['search'],
            ),
            new Index(
                key: '_key_enabled',
                type: IndexType::Key,
                attributes: ['enabled'],
                orders: ['ASC'],
            ),
            new Index(
                key: '_key_name',
                type: IndexType::Key,
                attributes: ['name'],
                orders: ['ASC'],
            ),
            new Index(
                key: '_key_fileSecurity',
                type: IndexType::Key,
                attributes: ['fileSecurity'],
                orders: ['ASC'],
            ),
            new Index(
                key: '_key_maximumFileSize',
                type: IndexType::Key,
                attributes: ['maximumFileSize'],
                orders: ['ASC'],
            ),
            new Index(
                key: '_key_encryption',
                type: IndexType::Key,
                attributes: ['encryption'],
                orders: ['ASC'],
            ),
            new Index(
                key: '_key_antivirus',
                type: IndexType::Key,
                attributes: ['antivirus'],
                orders: ['ASC'],
            ),
        ],
    ],
    'stats' => [
        '$collection' => '_metadata',
        '$id' => 'stats',
        'name' => 'Stats',
        'attributes' => [
            new Attribute(
                key: 'metric',
                type: ColumnType::String,
                size: Database::LENGTH_KEY,
                required: true,
            ),
            new Attribute(
                key: 'region',
                type: ColumnType::String,
                size: Database::LENGTH_KEY,
                required: true,
            ),
            new Attribute(
                key: 'value',
                type: ColumnType::Integer,
                size: 8,
                required: true,
            ),
            new Attribute(
                key: 'time',
                type: ColumnType::Datetime,
                signed: false,
                filters: ['datetime'],
            ),
            new Attribute(
                key: 'period',
                type: ColumnType::String,
                size: 4,
                required: true,
            ),
        ],
        'indexes' => [
            new Index(
                key: '_key_time',
                type: IndexType::Key,
                attributes: ['time'],
                orders: ['DESC'],
            ),
            new Index(
                key: '_key_period_time',
                type: IndexType::Key,
                attributes: ['period', 'time'],
                orders: ['ASC'],
            ),
            new Index(
                key: '_key_metric_period_time',
                type: IndexType::Unique,
                attributes: ['metric', 'period', 'time'],
                orders: ['DESC'],
            ),
        ],
    ],
    'providers' => [
        '$collection' => '_metadata',
        '$id' => 'providers',
        'name' => 'Providers',
        'attributes' => [
            new Attribute(
                key: 'name',
                type: ColumnType::String,
                size: 128,
                required: true,
            ),
            new Attribute(
                key: 'provider',
                type: ColumnType::String,
                size: Database::LENGTH_KEY,
                required: true,
            ),
            new Attribute(
                key: 'type',
                type: ColumnType::String,
                size: 128,
                required: true,
            ),
            new Attribute(
                key: 'enabled',
                type: ColumnType::Boolean,
                required: true,
                default: true,
            ),
            new Attribute(
                key: 'credentials',
                type: ColumnType::String,
                size: 16384,
                required: true,
                filters: ['json', 'encrypt'],
            ),
            new Attribute(
                key: 'options',
                type: ColumnType::String,
                size: 16384,
                default: [],
                filters: ['json'],
            ),
            new Attribute(
                key: 'search',
                type: ColumnType::String,
                size: 65535,
                default: '',
                filters: ['providerSearch'],
            ),
        ],
        'indexes' => [
            new Index(
                key: '_key_provider',
                type: IndexType::Key,
                attributes: ['provider'],
                orders: ['ASC'],
            ),
            new Index(
                key: '_key_type',
                type: IndexType::Key,
                attributes: ['type'],
                orders: ['ASC'],
            ),
            new Index(
                key: '_key_enabled_type',
                type: IndexType::Key,
                attributes: ['enabled', 'type'],
                orders: ['ASC'],
            ),
            new Index(
                key: '_key_search',
                type: IndexType::Fulltext,
                attributes: ['search'],
            ),
        ],
    ],
    'messages' => [
        '$collection' => '_metadata',
        '$id' => 'messages',
        'name' => 'Messages',
        'attributes' => [
            new Attribute(
                key: 'providerType',
                type: ColumnType::String,
                size: Database::LENGTH_KEY,
                required: true,
            ),
            new Attribute(
                key: 'status',
                type: ColumnType::String,
                size: Database::LENGTH_KEY,
                required: true,
                default: 'processing',
            ),
            new Attribute(
                key: 'data',
                type: ColumnType::String,
                size: 65535,
                required: true,
                filters: ['json'],
            ),
            new Attribute(
                key: 'topics',
                type: ColumnType::String,
                size: 21845,
                default: [],
                array: true,
            ),
            new Attribute(
                key: 'users',
                type: ColumnType::String,
                size: 21845,
                default: [],
                array: true,
            ),
            new Attribute(
                key: 'targets',
                type: ColumnType::String,
                size: 21845,
                default: [],
                array: true,
            ),
            new Attribute(
                key: 'scheduledAt',
                type: ColumnType::Datetime,
                signed: false,
                filters: ['datetime'],
            ),
            new Attribute(
                key: 'scheduleInternalId',
                type: ColumnType::String,
                size: Database::LENGTH_KEY,
            ),
            new Attribute(
                key: 'scheduleId',
                type: ColumnType::String,
                size: Database::LENGTH_KEY,
            ),
            new Attribute(
                key: 'deliveredAt',
                type: ColumnType::Datetime,
                signed: false,
                filters: ['datetime'],
            ),
            new Attribute(
                key: 'deliveryErrors',
                type: ColumnType::String,
                size: 65535,
                array: true,
            ),
            new Attribute(
                key: 'deliveredTotal',
                type: ColumnType::Integer,
                default: 0,
            ),
            new Attribute(
                key: 'search',
                type: ColumnType::String,
                size: 16384,
                default: '',
                filters: ['messageSearch'],
            ),
        ],
        'indexes' => [
            new Index(
                key: '_key_search',
                type: IndexType::Fulltext,
                attributes: ['search'],
            ),
        ],
    ],
    'topics' => [
        '$collection' => '_metadata',
        '$id' => 'topics',
        'name' => 'Topics',
        'attributes' => [
            new Attribute(
                key: 'name',
                type: ColumnType::String,
                size: 128,
                required: true,
            ),
            new Attribute(
                key: 'subscribe',
                type: ColumnType::String,
                size: 128,
                array: true,
            ),
            new Attribute(
                key: 'emailTotal',
                type: ColumnType::Integer,
                default: 0,
            ),
            new Attribute(
                key: 'smsTotal',
                type: ColumnType::Integer,
                default: 0,
            ),
            new Attribute(
                key: 'pushTotal',
                type: ColumnType::Integer,
                default: 0,
            ),
            new Attribute(
                key: 'targets',
                type: ColumnType::String,
                size: 16384,
                filters: ['subQueryTopicTargets'],
            ),
            new Attribute(
                key: 'search',
                type: ColumnType::String,
                size: 16384,
                default: '',
                filters: ['topicSearch'],
            ),
        ],
        'indexes' => [
            new Index(
                key: '_key_search',
                type: IndexType::Fulltext,
                attributes: ['search'],
                orders: ['ASC'],
            ),
        ],
    ],
    'subscribers' => [
        '$collection' => '_metadata',
        '$id' => 'subscribers',
        'name' => 'Subscribers',
        'attributes' => [
            new Attribute(
                key: 'targetId',
                type: ColumnType::String,
                size: Database::LENGTH_KEY,
                required: true,
            ),
            new Attribute(
                key: 'targetInternalId',
                type: ColumnType::String,
                size: Database::LENGTH_KEY,
                required: true,
            ),
            new Attribute(
                key: 'userId',
                type: ColumnType::String,
                size: Database::LENGTH_KEY,
                required: true,
            ),
            new Attribute(
                key: 'userInternalId',
                type: ColumnType::String,
                size: Database::LENGTH_KEY,
                required: true,
            ),
            new Attribute(
                key: 'topicId',
                type: ColumnType::String,
                size: Database::LENGTH_KEY,
                required: true,
            ),
            new Attribute(
                key: 'topicInternalId',
                type: ColumnType::String,
                size: Database::LENGTH_KEY,
                required: true,
            ),
            new Attribute(
                key: 'providerType',
                type: ColumnType::String,
                size: 128,
                required: true,
            ),
            new Attribute(
                key: 'search',
                type: ColumnType::String,
                size: 16384,
            ),
        ],
        'indexes' => [
            new Index(
                key: '_key_targetId',
                type: IndexType::Key,
                attributes: ['targetId'],
            ),
            new Index(
                key: '_key_targetInternalId',
                type: IndexType::Key,
                attributes: ['targetInternalId'],
            ),
            new Index(
                key: '_key_userId',
                type: IndexType::Key,
                attributes: ['userId'],
            ),
            new Index(
                key: '_key_userInternalId',
                type: IndexType::Key,
                attributes: ['userInternalId'],
            ),
            new Index(
                key: '_key_topicId',
                type: IndexType::Key,
                attributes: ['topicId'],
            ),
            new Index(
                key: '_key_topicInternalId',
                type: IndexType::Key,
                attributes: ['topicInternalId'],
            ),
            new Index(
                key: '_unique_target_topic',
                type: IndexType::Unique,
                attributes: ['targetInternalId', 'topicInternalId'],
            ),
            new Index(
                key: '_fulltext_search',
                type: IndexType::Fulltext,
                attributes: ['search'],
            ),
        ],
    ],
    'targets' => [
        '$collection' => '_metadata',
        '$id' => 'targets',
        'name' => 'Targets',
        'attributes' => [
            new Attribute(
                key: 'userId',
                type: ColumnType::String,
                size: Database::LENGTH_KEY,
                required: true,
            ),
            new Attribute(
                key: 'userInternalId',
                type: ColumnType::String,
                size: Database::LENGTH_KEY,
                required: true,
            ),
            new Attribute(
                key: 'sessionId',
                type: ColumnType::String,
                size: Database::LENGTH_KEY,
            ),
            new Attribute(
                key: 'sessionInternalId',
                type: ColumnType::String,
                size: Database::LENGTH_KEY,
            ),
            new Attribute(
                key: 'providerType',
                type: ColumnType::String,
                size: Database::LENGTH_KEY,
                required: true,
            ),
            new Attribute(
                key: 'providerId',
                type: ColumnType::String,
                size: Database::LENGTH_KEY,
            ),
            new Attribute(
                key: 'providerInternalId',
                type: ColumnType::String,
                size: Database::LENGTH_KEY,
            ),
            new Attribute(
                key: 'identifier',
                type: ColumnType::String,
                size: Database::LENGTH_KEY,
                required: true,
            ),
            new Attribute(
                key: 'name',
                type: ColumnType::String,
                size: Database::LENGTH_KEY,
            ),
            new Attribute(
                key: 'expired',
                type: ColumnType::Boolean,
                default: false,
            ),
        ],
        'indexes' => [
            new Index(
                key: '_key_userId',
                type: IndexType::Key,
                attributes: ['userId'],
                orders: ['ASC'],
            ),
            new Index(
                key: '_key_userInternalId',
                type: IndexType::Key,
                attributes: ['userInternalId'],
                orders: ['ASC'],
            ),
            new Index(
                key: '_key_providerId',
                type: IndexType::Key,
                attributes: ['providerId'],
            ),
            new Index(
                key: '_key_providerInternalId',
                type: IndexType::Key,
                attributes: ['providerInternalId'],
            ),
            new Index(
                key: '_key_identifier',
                type: IndexType::Unique,
                attributes: ['identifier'],
            ),
            new Index(
                key: '_key_expired',
                type: IndexType::Key,
                attributes: ['expired'],
            ),
            new Index(
                key: '_key_session_internal_id',
                type: IndexType::Key,
                attributes: ['sessionInternalId'],
            ),
        ],
    ],
    'files' => [
        '$collection' => 'buckets',
        '$id' => 'files',
        '$name' => 'Files',
        'attributes' => [
            new Attribute(
                key: 'bucketId',
                type: ColumnType::String,
                size: Database::LENGTH_KEY,
            ),
            new Attribute(
                key: 'bucketInternalId',
                type: ColumnType::String,
                size: Database::LENGTH_KEY,
                required: true,
            ),
            new Attribute(
                key: 'name',
                type: ColumnType::String,
                size: 2048,
            ),
            new Attribute(
                key: 'path',
                type: ColumnType::String,
                size: 2048,
            ),
            new Attribute(
                key: 'signature',
                type: ColumnType::String,
                size: 2048,
            ),
            new Attribute(
                key: 'mimeType',
                type: ColumnType::String,
                size: Database::LENGTH_KEY,
            ),
            new Attribute(
                key: 'metadata',
                type: ColumnType::String,
                size: 75000,
                filters: ['json'],
            ),
            new Attribute(
                key: 'sizeOriginal',
                type: ColumnType::Integer,
                size: 8,
                signed: false,
            ),
            new Attribute(
                key: 'sizeActual',
                type: ColumnType::Integer,
                size: 8,
                signed: false,
            ),
            new Attribute(
                key: 'algorithm',
                type: ColumnType::String,
                size: Database::LENGTH_KEY,
            ),
            new Attribute(
                key: 'comment',
                type: ColumnType::String,
                size: 2048,
            ),
            new Attribute(
                key: 'openSSLVersion',
                type: ColumnType::String,
                size: 64,
            ),
            new Attribute(
                key: 'openSSLCipher',
                type: ColumnType::String,
                size: 64,
            ),
            new Attribute(
                key: 'openSSLTag',
                type: ColumnType::String,
                size: 2048,
            ),
            new Attribute(
                key: 'openSSLIV',
                type: ColumnType::String,
                size: 2048,
            ),
            new Attribute(
                key: 'chunksTotal',
                type: ColumnType::Integer,
                signed: false,
            ),
            new Attribute(
                key: 'chunksUploaded',
                type: ColumnType::Integer,
                signed: false,
            ),
            new Attribute(
                key: 'transformedAt',
                type: ColumnType::Datetime,
                signed: false,
                filters: ['datetime'],
            ),
            new Attribute(
                key: 'search',
                type: ColumnType::String,
                size: 16384,
            ),
        ],
        'indexes' => [
            new Index(
                key: '_key_search',
                type: IndexType::Fulltext,
                attributes: ['search'],
            ),
            new Index(
                key: '_key_bucket',
                type: IndexType::Key,
                attributes: ['bucketId'],
                lengths: [255],
                orders: ['ASC'],
            ),
            new Index(
                key: '_key_name',
                type: IndexType::Key,
                attributes: ['name'],
                lengths: [256],
                orders: ['ASC'],
            ),
            new Index(
                key: '_key_signature',
                type: IndexType::Key,
                attributes: ['signature'],
                lengths: [256],
                orders: ['ASC'],
            ),
            new Index(
                key: '_key_mimeType',
                type: IndexType::Key,
                attributes: ['mimeType'],
                orders: ['ASC'],
            ),
            new Index(
                key: '_key_sizeOriginal',
                type: IndexType::Key,
                attributes: ['sizeOriginal'],
                orders: ['ASC'],
            ),
            new Index(
                key: '_key_chunksTotal',
                type: IndexType::Key,
                attributes: ['chunksTotal'],
                orders: ['ASC'],
            ),
            new Index(
                key: '_key_chunksUploaded',
                type: IndexType::Key,
                attributes: ['chunksUploaded'],
                orders: ['ASC'],
            ),
            new Index(
                key: '_key_transformedAt',
                type: IndexType::Key,
                attributes: ['transformedAt'],
            ),
        ],
    ],
];
