<?php

use Utopia\Database\Attribute;
use Utopia\Database\Database;
use Utopia\Database\Index;
use Utopia\Query\Schema\ColumnType;
use Utopia\Query\Schema\IndexType;

return [
    'projects' => [
        '$collection' => '_metadata',
        '$id' => 'projects',
        'name' => 'Projects',
        'attributes' => [
            new Attribute(
                key: 'teamInternalId',
                type: ColumnType::String,
                size: Database::LENGTH_KEY,
                required: true,
            ),
            new Attribute(
                key: 'teamId',
                type: ColumnType::String,
                size: Database::LENGTH_KEY,
            ),
            new Attribute(
                key: 'name',
                type: ColumnType::String,
                size: 128,
            ),
            new Attribute(
                key: 'region',
                type: ColumnType::String,
                size: 128,
            ),
            new Attribute(
                key: 'description',
                type: ColumnType::String,
                size: 256,
            ),
            new Attribute(
                key: 'database',
                type: ColumnType::String,
                size: 256,
                required: true,
            ),
            new Attribute(
                key: 'logo',
                type: ColumnType::String,
                size: Database::LENGTH_KEY,
            ),
            new Attribute(
                key: 'url',
                type: ColumnType::String,
                size: 16384,
            ),
            new Attribute(
                key: 'version',
                type: ColumnType::String,
                size: 16,
            ),
            new Attribute(
                key: 'legalName',
                type: ColumnType::String,
                size: 256,
            ),
            new Attribute(
                key: 'legalCountry',
                type: ColumnType::String,
                size: 256,
            ),
            new Attribute(
                key: 'legalState',
                type: ColumnType::String,
                size: 256,
            ),
            new Attribute(
                key: 'legalCity',
                type: ColumnType::String,
                size: 256,
            ),
            new Attribute(
                key: 'legalAddress',
                type: ColumnType::String,
                size: 256,
            ),
            new Attribute(
                key: 'legalTaxId',
                type: ColumnType::String,
                size: 256,
            ),
            new Attribute(
                key: 'accessedAt',
                type: ColumnType::Datetime,
                signed: false,
                filters: ['datetime'],
            ),
            new Attribute(
                key: 'services',
                type: ColumnType::String,
                size: 16384,
                default: [],
                filters: ['json'],
            ),
            new Attribute(
                key: 'apis',
                type: ColumnType::String,
                size: 16384,
                default: [],
                filters: ['json'],
            ),
            new Attribute(
                key: 'smtp',
                type: ColumnType::String,
                size: 16384,
                default: [],
                filters: ['json', 'encrypt'],
            ),
            new Attribute(
                key: 'templates',
                type: ColumnType::String,
                size: 1000000,
                default: [],
                filters: ['json'],
            ),
            new Attribute(
                key: 'auths',
                type: ColumnType::String,
                size: 16384,
                default: [],
                filters: ['json'],
            ),
            new Attribute(
                key: 'oAuthProviders',
                type: ColumnType::String,
                size: 16384,
                default: [],
                filters: ['json', 'encrypt'],
            ),
            new Attribute(
                key: 'platforms',
                type: ColumnType::String,
                size: 16384,
                filters: ['subQueryPlatforms'],
            ),
            new Attribute(
                key: 'webhooks',
                type: ColumnType::String,
                size: 16384,
                filters: ['subQueryWebhooks'],
            ),
            new Attribute(
                key: 'keys',
                type: ColumnType::String,
                size: 16384,
                filters: ['subQueryKeys'],
            ),
            new Attribute(
                key: 'devKeys',
                type: ColumnType::String,
                size: 16384,
                filters: ['subQueryDevKeys'],
            ),
            new Attribute(
                key: 'search',
                type: ColumnType::String,
                size: 16384,
            ),
            new Attribute(
                key: 'pingCount',
                type: ColumnType::Integer,
                default: 0,
                signed: false,
            ),
            new Attribute(
                key: 'pingedAt',
                type: ColumnType::Datetime,
                signed: false,
                filters: ['datetime'],
            ),
            new Attribute(
                key: 'labels',
                type: ColumnType::String,
                size: 128,
                default: [],
                array: true,
            ),
            new Attribute(
                key: 'status',
                type: ColumnType::String,
                size: 100,
                signed: false,
            ),
        ],
        'indexes' => [
            new Index(
                key: '_key_search',
                type: IndexType::Fulltext,
                attributes: ['search'],
            ),
            new Index(
                key: '_key_name',
                type: IndexType::Key,
                attributes: ['name'],
                lengths: [128],
                orders: ['ASC'],
            ),
            new Index(
                key: '_key_team',
                type: IndexType::Key,
                attributes: ['teamId'],
                lengths: [255],
                orders: ['ASC'],
            ),
            new Index(
                key: '_key_pingCount',
                type: IndexType::Key,
                attributes: ['pingCount'],
            ),
            new Index(
                key: '_key_pingedAt',
                type: IndexType::Key,
                attributes: ['pingedAt'],
            ),
            new Index(
                key: '_key_database',
                type: IndexType::Key,
                attributes: ['database'],
            ),
            new Index(
                key: '_key_region_accessed_at',
                type: IndexType::Key,
                attributes: ['region', 'accessedAt'],
            ),
        ],
    ],
    'schedules' => [
        '$collection' => '_metadata',
        '$id' => 'schedules',
        'name' => 'schedules',
        'attributes' => [
            new Attribute(
                key: 'resourceType',
                type: ColumnType::String,
                size: 100,
            ),
            new Attribute(
                key: 'resourceInternalId',
                type: ColumnType::String,
                size: Database::LENGTH_KEY,
            ),
            new Attribute(
                key: 'resourceId',
                type: ColumnType::String,
                size: Database::LENGTH_KEY,
            ),
            new Attribute(
                key: 'resourceUpdatedAt',
                type: ColumnType::Datetime,
                signed: false,
                filters: ['datetime'],
            ),
            new Attribute(
                key: 'projectId',
                type: ColumnType::String,
                size: Database::LENGTH_KEY,
            ),
            new Attribute(
                key: 'schedule',
                type: ColumnType::String,
                size: 100,
            ),
            new Attribute(
                key: 'data',
                type: ColumnType::String,
                size: 65535,
                default: (object) array(
                ),
                filters: ['json', 'encrypt'],
            ),
            new Attribute(
                key: 'active',
                type: ColumnType::Boolean,
            ),
            new Attribute(
                key: 'region',
                type: ColumnType::String,
                size: 10,
                required: true,
            ),
        ],
        'indexes' => [
            new Index(
                key: '_key_region_resourceType_resourceUpdatedAt',
                type: IndexType::Key,
                attributes: ['region', 'resourceType', 'resourceUpdatedAt'],
            ),
            new Index(
                key: '_key_region_resourceType_projectId_resourceId',
                type: IndexType::Key,
                attributes: ['region', 'resourceType', 'projectId', 'resourceId'],
            ),
            new Index(
                key: '_key_project_id_region',
                type: IndexType::Key,
                attributes: ['projectId', 'region'],
            ),
            new Index(
                key: '_key_region_rt_active',
                type: IndexType::Key,
                attributes: ['region', 'resourceType', 'active'],
            ),
        ],
    ],
    'platforms' => [
        '$collection' => '_metadata',
        '$id' => 'platforms',
        'name' => 'platforms',
        'attributes' => [
            new Attribute(
                key: 'projectInternalId',
                type: ColumnType::String,
                size: Database::LENGTH_KEY,
                required: true,
            ),
            new Attribute(
                key: 'projectId',
                type: ColumnType::String,
                size: Database::LENGTH_KEY,
            ),
            new Attribute(
                key: 'type',
                type: ColumnType::String,
                size: Database::LENGTH_KEY,
            ),
            new Attribute(
                key: 'name',
                type: ColumnType::String,
                size: 256,
                required: true,
            ),
            new Attribute(
                key: 'key',
                type: ColumnType::String,
                size: Database::LENGTH_KEY,
            ),
            new Attribute(
                key: 'store',
                type: ColumnType::String,
                size: 256,
            ),
            new Attribute(
                key: 'hostname',
                type: ColumnType::String,
                size: 256,
            ),
        ],
        'indexes' => [
            new Index(
                key: '_key_project',
                type: IndexType::Key,
                attributes: ['projectInternalId'],
                lengths: [255],
                orders: ['ASC'],
            ),
        ],
    ],
    'keys' => [
        '$collection' => '_metadata',
        '$id' => 'keys',
        'name' => 'keys',
        'attributes' => [
            new Attribute(
                key: 'resourceType',
                type: ColumnType::String,
                size: Database::LENGTH_KEY,
            ),
            new Attribute(
                key: 'resourceId',
                type: ColumnType::String,
                size: Database::LENGTH_KEY,
            ),
            new Attribute(
                key: 'resourceInternalId',
                type: ColumnType::String,
                size: Database::LENGTH_KEY,
            ),
            new Attribute(
                key: 'name',
                type: ColumnType::String,
                size: Database::LENGTH_KEY,
                required: true,
            ),
            new Attribute(
                key: 'scopes',
                type: ColumnType::String,
                size: Database::LENGTH_KEY,
                required: true,
                array: true,
            ),
            new Attribute(
                key: 'secret',
                type: ColumnType::String,
                size: 512,
                required: true,
                filters: ['encrypt'],
            ),
            new Attribute(
                key: 'expire',
                type: ColumnType::Datetime,
                signed: false,
                filters: ['datetime'],
            ),
            new Attribute(
                key: 'accessedAt',
                type: ColumnType::Datetime,
                signed: false,
                filters: ['datetime'],
            ),
            new Attribute(
                key: 'sdks',
                type: ColumnType::String,
                size: Database::LENGTH_KEY,
                required: true,
                array: true,
            ),
        ],
        'indexes' => [
            new Index(
                key: '_key_resource',
                type: IndexType::Key,
                attributes: ['resourceType', 'resourceInternalId'],
            ),
            new Index(
                key: '_key_accessedAt',
                type: IndexType::Key,
                attributes: ['accessedAt'],
            ),
        ],
    ],
    'devKeys' => [
        '$collection' => '_metadata',
        '$id' => 'devKeys',
        'name' => 'Dev keys',
        'attributes' => [
            new Attribute(
                key: 'projectInternalId',
                type: ColumnType::String,
                size: Database::LENGTH_KEY,
                required: true,
            ),
            new Attribute(
                key: 'projectId',
                type: ColumnType::String,
                size: Database::LENGTH_KEY,
                required: true,
                default: 0,
            ),
            new Attribute(
                key: 'name',
                type: ColumnType::String,
                size: Database::LENGTH_KEY,
                required: true,
            ),
            new Attribute(
                key: 'secret',
                type: ColumnType::String,
                size: 512,
                required: true,
                filters: ['encrypt'],
            ),
            new Attribute(
                key: 'expire',
                type: ColumnType::Datetime,
                signed: false,
                filters: ['datetime'],
            ),
            new Attribute(
                key: 'accessedAt',
                type: ColumnType::Datetime,
                signed: false,
                filters: ['datetime'],
            ),
            new Attribute(
                key: 'sdks',
                type: ColumnType::String,
                size: Database::LENGTH_KEY,
                required: true,
                array: true,
            ),
        ],
        'indexes' => [
            new Index(
                key: '_key_project',
                type: IndexType::Key,
                attributes: ['projectInternalId'],
                lengths: [255],
                orders: ['ASC'],
            ),
            new Index(
                key: '_key_accessedAt',
                type: IndexType::Key,
                attributes: ['accessedAt'],
            ),
        ],
    ],
    'webhooks' => [
        '$collection' => '_metadata',
        '$id' => 'webhooks',
        'name' => 'webhooks',
        'attributes' => [
            new Attribute(
                key: 'projectInternalId',
                type: ColumnType::String,
                size: Database::LENGTH_KEY,
                required: true,
            ),
            new Attribute(
                key: 'projectId',
                type: ColumnType::String,
                size: Database::LENGTH_KEY,
            ),
            new Attribute(
                key: 'name',
                type: ColumnType::String,
                size: Database::LENGTH_KEY,
                required: true,
            ),
            new Attribute(
                key: 'url',
                type: ColumnType::String,
                size: Database::LENGTH_KEY,
                required: true,
            ),
            new Attribute(
                key: 'httpUser',
                type: ColumnType::String,
                size: Database::LENGTH_KEY,
            ),
            new Attribute(
                key: 'httpPass',
                type: ColumnType::String,
                size: Database::LENGTH_KEY,
                filters: ['encrypt'],
            ),
            new Attribute(
                key: 'security',
                type: ColumnType::Boolean,
                required: true,
            ),
            new Attribute(
                key: 'events',
                type: ColumnType::String,
                size: Database::LENGTH_KEY,
                required: true,
                array: true,
            ),
            new Attribute(
                key: 'signatureKey',
                type: ColumnType::String,
                size: 2048,
            ),
            new Attribute(
                key: 'enabled',
                type: ColumnType::Boolean,
                default: true,
            ),
            new Attribute(
                key: 'logs',
                type: ColumnType::String,
                size: 1000000,
                default: '',
            ),
            new Attribute(
                key: 'attempts',
                type: ColumnType::Integer,
                default: 0,
            ),
        ],
        'indexes' => [
            new Index(
                key: '_key_project',
                type: IndexType::Key,
                attributes: ['projectInternalId'],
                lengths: [255],
                orders: ['ASC'],
            ),
        ],
    ],
    'certificates' => [
        '$collection' => '_metadata',
        '$id' => 'certificates',
        'name' => 'Certificates',
        'attributes' => [
            new Attribute(
                key: 'domain',
                type: ColumnType::String,
                size: Database::LENGTH_KEY,
            ),
            new Attribute(
                key: 'issueDate',
                type: ColumnType::Datetime,
                signed: false,
                filters: ['datetime'],
            ),
            new Attribute(
                key: 'renewDate',
                type: ColumnType::Datetime,
                signed: false,
                filters: ['datetime'],
            ),
            new Attribute(
                key: 'attempts',
                type: ColumnType::Integer,
            ),
            new Attribute(
                key: 'logs',
                type: ColumnType::String,
                size: 1000000,
            ),
            new Attribute(
                key: 'updated',
                type: ColumnType::Datetime,
                signed: false,
                filters: ['datetime'],
            ),
        ],
        'indexes' => [
            new Index(
                key: '_key_domain',
                type: IndexType::Key,
                attributes: ['domain'],
                lengths: [255],
                orders: ['ASC'],
            ),
        ],
    ],
    'realtime' => [
        '$collection' => '_metadata',
        '$id' => 'realtime',
        'name' => 'Realtime Connections',
        'attributes' => [
            new Attribute(
                key: 'container',
                type: ColumnType::String,
                size: Database::LENGTH_KEY,
                required: true,
            ),
            new Attribute(
                key: 'timestamp',
                type: ColumnType::Datetime,
                signed: false,
                filters: ['datetime'],
            ),
            new Attribute(
                key: 'value',
                type: ColumnType::String,
                size: 16384,
                required: true,
            ),
        ],
        'indexes' => [
            new Index(
                key: '_key_timestamp',
                type: IndexType::Key,
                attributes: ['timestamp'],
                orders: ['DESC'],
            ),
        ],
    ],
    'rules' => [
        '$collection' => '_metadata',
        '$id' => 'rules',
        'name' => 'Rules',
        'attributes' => [
            new Attribute(
                key: 'projectId',
                type: ColumnType::String,
                size: Database::LENGTH_KEY,
                required: true,
            ),
            new Attribute(
                key: 'projectInternalId',
                type: ColumnType::String,
                size: Database::LENGTH_KEY,
                required: true,
            ),
            new Attribute(
                key: 'domain',
                type: ColumnType::String,
                size: Database::LENGTH_KEY,
                required: true,
            ),
            new Attribute(
                key: 'type',
                type: ColumnType::String,
                size: 32,
            ),
            new Attribute(
                key: 'trigger',
                type: ColumnType::String,
                size: 32,
                default: '',
            ),
            new Attribute(
                key: 'redirectUrl',
                type: ColumnType::String,
                size: 2048,
                default: '',
            ),
            new Attribute(
                key: 'redirectStatusCode',
                type: ColumnType::Integer,
            ),
            new Attribute(
                key: 'deploymentResourceType',
                type: ColumnType::String,
                size: 32,
                default: '',
            ),
            new Attribute(
                key: 'deploymentId',
                type: ColumnType::String,
                size: Database::LENGTH_KEY,
                default: '',
            ),
            new Attribute(
                key: 'deploymentInternalId',
                type: ColumnType::String,
                size: Database::LENGTH_KEY,
                default: '',
            ),
            new Attribute(
                key: 'deploymentResourceId',
                type: ColumnType::String,
                size: Database::LENGTH_KEY,
                default: '',
            ),
            new Attribute(
                key: 'deploymentResourceInternalId',
                type: ColumnType::String,
                size: Database::LENGTH_KEY,
                default: '',
            ),
            new Attribute(
                key: 'deploymentVcsProviderBranch',
                type: ColumnType::String,
                size: Database::LENGTH_KEY,
                default: '',
            ),
            new Attribute(
                key: 'status',
                type: ColumnType::String,
                size: Database::LENGTH_KEY,
            ),
            new Attribute(
                key: 'certificateId',
                type: ColumnType::String,
                size: Database::LENGTH_KEY,
            ),
            new Attribute(
                key: 'search',
                type: ColumnType::String,
                size: 16384,
            ),
            new Attribute(
                key: 'owner',
                type: ColumnType::String,
                size: 16,
                default: '',
            ),
            new Attribute(
                key: 'region',
                type: ColumnType::String,
                size: 16,
                required: true,
            ),
            new Attribute(
                key: 'logs',
                type: ColumnType::String,
                size: 1000000,
                default: '',
            ),
        ],
        'indexes' => [
            new Index(
                key: '_key_search',
                type: IndexType::Fulltext,
                attributes: ['search'],
            ),
            new Index(
                key: '_key_domain',
                type: IndexType::Unique,
                attributes: ['domain'],
                lengths: [255],
                orders: ['ASC'],
            ),
            new Index(
                key: '_key_projectInternalId',
                type: IndexType::Key,
                attributes: ['projectInternalId'],
                lengths: [255],
                orders: ['ASC'],
            ),
            new Index(
                key: '_key_projectId',
                type: IndexType::Key,
                attributes: ['projectId'],
                lengths: [255],
                orders: ['ASC'],
            ),
            new Index(
                key: '_key_type',
                type: IndexType::Key,
                attributes: ['type'],
                orders: ['ASC'],
            ),
            new Index(
                key: '_key_trigger',
                type: IndexType::Key,
                attributes: ['trigger'],
                orders: ['ASC'],
            ),
            new Index(
                key: '_key_deploymentResourceType',
                type: IndexType::Key,
                attributes: ['deploymentResourceType'],
                orders: ['ASC'],
            ),
            new Index(
                key: '_key_deploymentResourceId',
                type: IndexType::Key,
                attributes: ['deploymentResourceId'],
                lengths: [255],
                orders: ['ASC'],
            ),
            new Index(
                key: '_key_deploymentResourceInternalId',
                type: IndexType::Key,
                attributes: ['deploymentResourceInternalId'],
                lengths: [255],
                orders: ['ASC'],
            ),
            new Index(
                key: '_key_deploymentId',
                type: IndexType::Key,
                attributes: ['deploymentId'],
                lengths: [255],
                orders: ['ASC'],
            ),
            new Index(
                key: '_key_deploymentInternalId',
                type: IndexType::Key,
                attributes: ['deploymentInternalId'],
                lengths: [255],
                orders: ['ASC'],
            ),
            new Index(
                key: '_key_deploymentVcsProviderBranch',
                type: IndexType::Key,
                attributes: ['deploymentVcsProviderBranch'],
                lengths: [255],
                orders: ['ASC'],
            ),
            new Index(
                key: '_key_owner',
                type: IndexType::Key,
                attributes: ['owner'],
                orders: ['ASC'],
            ),
            new Index(
                key: '_key_piid_diid_drt',
                type: IndexType::Key,
                attributes: ['projectInternalId', 'deploymentInternalId', 'deploymentResourceType'],
            ),
            new Index(
                key: '_key_region_status_createdAt',
                type: IndexType::Key,
                attributes: ['region', 'status', '$createdAt'],
            ),
        ],
    ],
    'installations' => [
        '$collection' => '_metadata',
        '$id' => 'installations',
        'name' => 'installations',
        'attributes' => [
            new Attribute(
                key: 'projectId',
                type: ColumnType::String,
                size: Database::LENGTH_KEY,
                required: true,
            ),
            new Attribute(
                key: 'projectInternalId',
                type: ColumnType::String,
                size: Database::LENGTH_KEY,
                required: true,
            ),
            new Attribute(
                key: 'providerInstallationId',
                type: ColumnType::String,
                size: Database::LENGTH_KEY,
                required: true,
            ),
            new Attribute(
                key: 'organization',
                type: ColumnType::String,
                size: Database::LENGTH_KEY,
                required: true,
            ),
            new Attribute(
                key: 'provider',
                type: ColumnType::String,
                size: Database::LENGTH_KEY,
                required: true,
            ),
            new Attribute(
                key: 'personal',
                type: ColumnType::Boolean,
                default: false,
            ),
            new Attribute(
                key: 'personalAccessToken',
                type: ColumnType::String,
                size: 256,
                filters: ['encrypt'],
            ),
            new Attribute(
                key: 'personalAccessTokenExpiry',
                type: ColumnType::Datetime,
                signed: false,
                filters: ['datetime'],
            ),
            new Attribute(
                key: 'personalRefreshToken',
                type: ColumnType::String,
                size: 256,
                filters: ['encrypt'],
            ),
        ],
        'indexes' => [
            new Index(
                key: '_key_projectInternalId',
                type: IndexType::Key,
                attributes: ['projectInternalId'],
                lengths: [255],
                orders: ['ASC'],
            ),
            new Index(
                key: '_key_projectId',
                type: IndexType::Key,
                attributes: ['projectId'],
                lengths: [255],
                orders: ['ASC'],
            ),
            new Index(
                key: '_key_providerInstallationId',
                type: IndexType::Key,
                attributes: ['providerInstallationId'],
                lengths: [255],
                orders: ['ASC'],
            ),
        ],
    ],
    'repositories' => [
        '$collection' => '_metadata',
        '$id' => 'repositories',
        'name' => 'repositories',
        'attributes' => [
            new Attribute(
                key: 'installationId',
                type: ColumnType::String,
                size: Database::LENGTH_KEY,
                required: true,
            ),
            new Attribute(
                key: 'installationInternalId',
                type: ColumnType::String,
                size: Database::LENGTH_KEY,
            ),
            new Attribute(
                key: 'projectId',
                type: ColumnType::String,
                size: Database::LENGTH_KEY,
                required: true,
            ),
            new Attribute(
                key: 'projectInternalId',
                type: ColumnType::String,
                size: Database::LENGTH_KEY,
                required: true,
            ),
            new Attribute(
                key: 'providerRepositoryId',
                type: ColumnType::String,
                size: Database::LENGTH_KEY,
                required: true,
            ),
            new Attribute(
                key: 'resourceId',
                type: ColumnType::String,
                size: Database::LENGTH_KEY,
                required: true,
            ),
            new Attribute(
                key: 'resourceInternalId',
                type: ColumnType::String,
                size: Database::LENGTH_KEY,
            ),
            new Attribute(
                key: 'resourceType',
                type: ColumnType::String,
                size: Database::LENGTH_KEY,
                required: true,
            ),
            new Attribute(
                key: 'providerPullRequestIds',
                type: ColumnType::String,
                size: 128,
                array: true,
            ),
        ],
        'indexes' => [
            new Index(
                key: '_key_installationId',
                type: IndexType::Key,
                attributes: ['installationId'],
                lengths: [255],
                orders: ['ASC'],
            ),
            new Index(
                key: '_key_installationInternalId',
                type: IndexType::Key,
                attributes: ['installationInternalId'],
                lengths: [255],
                orders: ['ASC'],
            ),
            new Index(
                key: '_key_projectInternalId',
                type: IndexType::Key,
                attributes: ['projectInternalId'],
                lengths: [255],
                orders: ['ASC'],
            ),
            new Index(
                key: '_key_projectId',
                type: IndexType::Key,
                attributes: ['projectId'],
                lengths: [255],
                orders: ['ASC'],
            ),
            new Index(
                key: '_key_providerRepositoryId',
                type: IndexType::Key,
                attributes: ['providerRepositoryId'],
                lengths: [255],
                orders: ['ASC'],
            ),
            new Index(
                key: '_key_resourceId',
                type: IndexType::Key,
                attributes: ['resourceId'],
                lengths: [255],
                orders: ['ASC'],
            ),
            new Index(
                key: '_key_resourceInternalId',
                type: IndexType::Key,
                attributes: ['resourceInternalId'],
                lengths: [255],
                orders: ['ASC'],
            ),
            new Index(
                key: '_key_resourceType',
                type: IndexType::Key,
                attributes: ['resourceType'],
                lengths: [255],
                orders: ['ASC'],
            ),
            new Index(
                key: '_key_piid_riid_rt',
                type: IndexType::Key,
                attributes: ['projectInternalId', 'resourceInternalId', 'resourceType'],
            ),
        ],
    ],
    'vcsComments' => [
        '$collection' => '_metadata',
        '$id' => 'vcsComments',
        'name' => 'vcsComments',
        'attributes' => [
            new Attribute(
                key: 'installationId',
                type: ColumnType::String,
                size: Database::LENGTH_KEY,
                required: true,
            ),
            new Attribute(
                key: 'installationInternalId',
                type: ColumnType::String,
                size: Database::LENGTH_KEY,
            ),
            new Attribute(
                key: 'projectId',
                type: ColumnType::String,
                size: Database::LENGTH_KEY,
                required: true,
            ),
            new Attribute(
                key: 'projectInternalId',
                type: ColumnType::String,
                size: Database::LENGTH_KEY,
                required: true,
            ),
            new Attribute(
                key: 'providerRepositoryId',
                type: ColumnType::String,
                size: Database::LENGTH_KEY,
                required: true,
            ),
            new Attribute(
                key: 'providerCommentId',
                type: ColumnType::String,
                size: Database::LENGTH_KEY,
                required: true,
            ),
            new Attribute(
                key: 'providerPullRequestId',
                type: ColumnType::String,
                size: Database::LENGTH_KEY,
                required: true,
            ),
            new Attribute(
                key: 'providerBranch',
                type: ColumnType::String,
                size: Database::LENGTH_KEY,
                required: true,
            ),
        ],
        'indexes' => [
            new Index(
                key: '_key_installationId',
                type: IndexType::Key,
                attributes: ['installationId'],
                lengths: [255],
                orders: ['ASC'],
            ),
            new Index(
                key: '_key_installationInternalId',
                type: IndexType::Key,
                attributes: ['installationInternalId'],
                lengths: [255],
                orders: ['ASC'],
            ),
            new Index(
                key: '_key_projectInternalId',
                type: IndexType::Key,
                attributes: ['projectInternalId'],
                lengths: [255],
                orders: ['ASC'],
            ),
            new Index(
                key: '_key_projectId',
                type: IndexType::Key,
                attributes: ['projectId'],
                lengths: [255],
                orders: ['ASC'],
            ),
            new Index(
                key: '_key_providerRepositoryId',
                type: IndexType::Key,
                attributes: ['providerRepositoryId'],
                lengths: [255],
                orders: ['ASC'],
            ),
            new Index(
                key: '_key_providerPullRequestId',
                type: IndexType::Key,
                attributes: ['providerPullRequestId'],
                lengths: [255],
                orders: ['ASC'],
            ),
            new Index(
                key: '_key_providerBranch',
                type: IndexType::Key,
                attributes: ['providerBranch'],
                lengths: [255],
                orders: ['ASC'],
            ),
            new Index(
                key: '_key_piid_prid_rt',
                type: IndexType::Key,
                attributes: ['projectInternalId', 'providerRepositoryId'],
            ),
        ],
    ],
    'vcsCommentLocks' => [
        '$collection' => '_metadata',
        '$id' => 'vcsCommentLocks',
        'name' => 'vcsCommentLocks',
        'attributes' => [
        ],
        'indexes' => [
        ],
    ],
    'teams' => [
        'attributes' => [
            new Attribute(
                key: 'keys',
                type: ColumnType::String,
                size: 16384,
                filters: ['subQueryOrganizationKeys'],
            ),
        ],
    ],
    'users' => [
        'attributes' => [
            new Attribute(
                key: 'keys',
                type: ColumnType::String,
                size: 16384,
                filters: ['subQueryAccountKeys'],
            ),
        ],
    ],
];
