<?php

use Utopia\Database\Attribute;
use Utopia\Database\Database;
use Utopia\Database\Helpers\ID;
use Utopia\Database\Index;
use Utopia\Query\Schema\ColumnType;
use Utopia\Query\Schema\IndexType;

return [
    'databases' => [
        '$collection' => ID::custom(Database::METADATA),
        '$id' => ID::custom('databases'),
        'name' => 'Databases',
        'attributes' => [
            new Attribute(
                key: 'name',
                type: ColumnType::String,
                size: 256,
                required: true,
            ),
            new Attribute(
                key: 'enabled',
                type: ColumnType::Boolean,
                default: true,
            ),
            new Attribute(
                key: 'search',
                type: ColumnType::String,
                size: 16384,
            ),
            new Attribute(
                key: 'originalId',
                type: ColumnType::String,
                size: Database::LENGTH_KEY,
            ),
            new Attribute(
                key: 'type',
                type: ColumnType::String,
                size: 128,
                default: 'tablesdb',
            ),
            new Attribute(
                key: 'database',
                type: ColumnType::String,
                size: 2000,
            ),
            new Attribute(
                key: 'status',
                type: ColumnType::String,
                size: 16,
            ),
        ],
        'indexes' => [
            new Index(
                key: '_fulltext_search',
                type: IndexType::Fulltext,
                attributes: ['search'],
            ),
            new Index(
                key: '_key_name',
                type: IndexType::Key,
                attributes: ['name'],
                lengths: [256],
                orders: ['ASC'],
            ),
        ],
    ],

    'attributes' => [
        '$collection' => ID::custom(Database::METADATA),
        '$id' => ID::custom('attributes'),
        'name' => 'Attributes',
        'attributes' => [
            new Attribute(
                key: 'databaseInternalId',
                type: ColumnType::String,
                size: Database::LENGTH_KEY,
                required: true,
            ),
            new Attribute(
                key: 'databaseId',
                type: ColumnType::String,
                size: Database::LENGTH_KEY,
                required: true,
                signed: false,
            ),
            new Attribute(
                key: 'collectionInternalId',
                type: ColumnType::String,
                size: Database::LENGTH_KEY,
                required: true,
            ),
            new Attribute(
                key: 'collectionId',
                type: ColumnType::String,
                size: Database::LENGTH_KEY,
                required: true,
            ),
            new Attribute(
                key: 'key',
                type: ColumnType::String,
                size: Database::LENGTH_KEY,
            ),
            new Attribute(
                key: 'type',
                type: ColumnType::String,
                size: 256,
            ),
            new Attribute(
                key: 'status',
                type: ColumnType::String,
                size: 16,
            ),
            new Attribute(
                key: 'error',
                type: ColumnType::String,
                size: 2048,
            ),
            new Attribute(
                key: 'size',
                type: ColumnType::Integer,
            ),
            new Attribute(
                key: 'required',
                type: ColumnType::Boolean,
            ),
            new Attribute(
                key: 'default',
                type: ColumnType::String,
                size: 16384,
                filters: ['casting'],
            ),
            new Attribute(
                key: 'signed',
                type: ColumnType::Boolean,
            ),
            new Attribute(
                key: 'array',
                type: ColumnType::Boolean,
            ),
            new Attribute(
                key: 'format',
                type: ColumnType::String,
                size: 64,
            ),
            new Attribute(
                key: 'formatOptions',
                type: ColumnType::String,
                size: 16384,
                default: new stdClass(),
                filters: ['json', 'range', 'enum'],
            ),
            new Attribute(
                key: 'filters',
                type: ColumnType::String,
                size: 64,
                array: true,
            ),
            new Attribute(
                key: 'options',
                type: ColumnType::String,
                size: 16384,
                signed: false,
                filters: ['json'],
            ),
        ],
        'indexes' => [
            new Index(
                key: '_key_db_collection',
                type: IndexType::Key,
                attributes: ['databaseInternalId', 'collectionInternalId'],
                lengths: [Database::LENGTH_KEY, Database::LENGTH_KEY],
                orders: ['ASC', 'ASC'],
            ),
        ],
    ],

    'indexes' => [
        '$collection' => ID::custom(Database::METADATA),
        '$id' => ID::custom('indexes'),
        'name' => 'Indexes',
        'attributes' => [
            new Attribute(
                key: 'databaseInternalId',
                type: ColumnType::String,
                size: Database::LENGTH_KEY,
                required: true,
            ),
            new Attribute(
                key: 'databaseId',
                type: ColumnType::String,
                size: Database::LENGTH_KEY,
                required: true,
                signed: false,
            ),
            new Attribute(
                key: 'collectionInternalId',
                type: ColumnType::String,
                size: Database::LENGTH_KEY,
                required: true,
            ),
            new Attribute(
                key: 'collectionId',
                type: ColumnType::String,
                size: Database::LENGTH_KEY,
                required: true,
            ),
            new Attribute(
                key: 'key',
                type: ColumnType::String,
                size: Database::LENGTH_KEY,
            ),
            new Attribute(
                key: 'type',
                type: ColumnType::String,
                size: 16,
            ),
            new Attribute(
                key: 'status',
                type: ColumnType::String,
                size: 16,
            ),
            new Attribute(
                key: 'error',
                type: ColumnType::String,
                size: 2048,
            ),
            new Attribute(
                key: 'attributes',
                type: ColumnType::String,
                size: Database::LENGTH_KEY,
                array: true,
            ),
            new Attribute(
                key: 'lengths',
                type: ColumnType::Integer,
                array: true,
            ),
            new Attribute(
                key: 'orders',
                type: ColumnType::String,
                size: 4,
                array: true,
            ),
        ],
        'indexes' => [
            new Index(
                key: '_key_db_collection',
                type: IndexType::Key,
                attributes: ['databaseInternalId', 'collectionInternalId'],
                lengths: [Database::LENGTH_KEY, Database::LENGTH_KEY],
                orders: ['ASC', 'ASC'],
            ),
        ],
    ],

    'functions' => [
        '$collection' => ID::custom(Database::METADATA),
        '$id' => ID::custom('functions'),
        'name' => 'Functions',
        'attributes' => [
            new Attribute(
                key: 'execute',
                type: ColumnType::String,
                size: 128,
                array: true,
            ),
            new Attribute(
                key: 'name',
                type: ColumnType::String,
                size: 2048,
            ),
            new Attribute(
                key: 'enabled',
                type: ColumnType::Boolean,
                required: true,
            ),
            new Attribute(
                key: 'live',
                type: ColumnType::Boolean,
                required: true,
            ),
            new Attribute(
                key: 'installationId',
                type: ColumnType::String,
                size: Database::LENGTH_KEY,
            ),
            new Attribute(
                key: 'installationInternalId',
                type: ColumnType::String,
                size: Database::LENGTH_KEY,
            ),
            new Attribute(
                key: 'providerRepositoryId',
                type: ColumnType::String,
                size: Database::LENGTH_KEY,
            ),
            new Attribute(
                key: 'repositoryId',
                type: ColumnType::String,
                size: Database::LENGTH_KEY,
            ),
            new Attribute(
                key: 'repositoryInternalId',
                type: ColumnType::String,
                size: Database::LENGTH_KEY,
            ),
            new Attribute(
                key: 'providerBranch',
                type: ColumnType::String,
                size: Database::LENGTH_KEY,
            ),
            new Attribute(
                key: 'providerRootDirectory',
                type: ColumnType::String,
                size: Database::LENGTH_KEY,
            ),
            new Attribute(
                key: 'providerSilentMode',
                type: ColumnType::Boolean,
                default: false,
            ),
            new Attribute(
                key: 'logging',
                type: ColumnType::Boolean,
                required: true,
            ),
            new Attribute(
                key: 'runtime',
                type: ColumnType::String,
                size: 2048,
            ),
            new Attribute(
                key: 'deploymentRetention',
                type: ColumnType::Integer,
                default: 0,
            ),
            new Attribute(
                key: 'deploymentInternalId',
                type: ColumnType::String,
                size: Database::LENGTH_KEY,
            ),
            new Attribute(
                key: 'deploymentId',
                type: ColumnType::String,
                size: Database::LENGTH_KEY,
            ),
            new Attribute(
                key: 'deploymentCreatedAt',
                type: ColumnType::Datetime,
                signed: false,
                filters: ['datetime'],
            ),
            new Attribute(
                key: 'latestDeploymentId',
                type: ColumnType::String,
                size: Database::LENGTH_KEY,
            ),
            new Attribute(
                key: 'latestDeploymentInternalId',
                type: ColumnType::String,
                size: Database::LENGTH_KEY,
            ),
            new Attribute(
                key: 'latestDeploymentCreatedAt',
                type: ColumnType::Datetime,
                signed: false,
                filters: ['datetime'],
            ),
            new Attribute(
                key: 'latestDeploymentStatus',
                type: ColumnType::String,
                size: 16,
                default: '',
            ),
            new Attribute(
                key: 'vars',
                type: ColumnType::String,
                size: 16384,
                filters: ['subQueryVariables'],
            ),
            new Attribute(
                key: 'varsProject',
                type: ColumnType::String,
                size: 16384,
                filters: ['subQueryProjectVariables'],
            ),
            new Attribute(
                key: 'events',
                type: ColumnType::String,
                size: 256,
                array: true,
            ),
            new Attribute(
                key: 'scheduleInternalId',
                type: ColumnType::String,
                size: Database::LENGTH_KEY,
            ),
            new Attribute(
                key: 'scheduleId',
                type: ColumnType::String,
                size: Database::LENGTH_KEY,
            ),
            new Attribute(
                key: 'schedule',
                type: ColumnType::String,
                size: 128,
            ),
            new Attribute(
                key: 'timeout',
                type: ColumnType::Integer,
            ),
            new Attribute(
                key: 'search',
                type: ColumnType::String,
                size: 16384,
            ),
            new Attribute(
                key: 'version',
                type: ColumnType::String,
                size: 8,
                default: 'v5',
            ),
            new Attribute(
                key: 'entrypoint',
                type: ColumnType::String,
                size: 16384,
            ),
            new Attribute(
                key: 'commands',
                type: ColumnType::String,
                size: 16384,
            ),
            // At the moment, always empty (no runtime supports it yet)
            new Attribute(
                key: 'startCommand',
                type: ColumnType::String,
                size: 20000,
            ),
            new Attribute(
                key: 'specification',
                type: ColumnType::String,
                size: 128,
                default: APP_COMPUTE_SPECIFICATION_DEFAULT,
                signed: false,
            ),
            new Attribute(
                key: 'buildSpecification',
                type: ColumnType::String,
                size: 128,
                default: APP_COMPUTE_SPECIFICATION_DEFAULT,
                signed: false,
            ),
            new Attribute(
                key: 'runtimeSpecification',
                type: ColumnType::String,
                size: 128,
                default: APP_COMPUTE_SPECIFICATION_DEFAULT,
                signed: false,
            ),
            new Attribute(
                key: 'scopes',
                type: ColumnType::String,
                size: Database::LENGTH_KEY,
                default: [],
                array: true,
            ),
            new Attribute(
                key: 'providerBranches',
                type: ColumnType::String,
                size: 128,
                default: [],
                array: true,
            ),
            new Attribute(
                key: 'providerPaths',
                type: ColumnType::String,
                size: 128,
                default: [],
                array: true,
            ),
        ],
        'indexes' => [
            new Index(
                key: '_key_search',
                type: IndexType::Fulltext,
                attributes: ['search'],
            ),
            new Index(
                key: '_key_name',
                type: IndexType::Key,
                attributes: ['name'],
                lengths: [256],
                orders: ['ASC'],
            ),
            new Index(
                key: '_key_enabled',
                type: IndexType::Key,
                attributes: ['enabled'],
                orders: ['ASC'],
            ),
            new Index(
                key: '_key_installationId',
                type: IndexType::Key,
                attributes: ['installationId'],
                lengths: [Database::LENGTH_KEY],
                orders: ['ASC'],
            ),
            new Index(
                key: '_key_installationInternalId',
                type: IndexType::Key,
                attributes: ['installationInternalId'],
                lengths: [Database::LENGTH_KEY],
                orders: ['ASC'],
            ),
            new Index(
                key: '_key_providerRepositoryId',
                type: IndexType::Key,
                attributes: ['providerRepositoryId'],
                lengths: [Database::LENGTH_KEY],
                orders: ['ASC'],
            ),
            new Index(
                key: '_key_repositoryId',
                type: IndexType::Key,
                attributes: ['repositoryId'],
                lengths: [Database::LENGTH_KEY],
                orders: ['ASC'],
            ),
            new Index(
                key: '_key_repositoryInternalId',
                type: IndexType::Key,
                attributes: ['repositoryInternalId'],
                lengths: [Database::LENGTH_KEY],
                orders: ['ASC'],
            ),
            new Index(
                key: '_key_runtime',
                type: IndexType::Key,
                attributes: ['runtime'],
                lengths: [64],
                orders: ['ASC'],
            ),
            new Index(
                key: '_key_deploymentId',
                type: IndexType::Key,
                attributes: ['deploymentId'],
                orders: ['ASC'],
            ),
        ],
    ],

    'sites' => [
        '$collection' => ID::custom(Database::METADATA),
        '$id' => ID::custom('sites'),
        'name' => 'Sites',
        'attributes' => [
            new Attribute(
                key: 'name',
                type: ColumnType::String,
                size: 2048,
            ),
            new Attribute(
                key: 'enabled',
                type: ColumnType::Boolean,
                required: true,
            ),
            new Attribute(
                key: 'live',
                type: ColumnType::Boolean,
                required: true,
            ),
            new Attribute(
                key: 'installationId',
                type: ColumnType::String,
                size: Database::LENGTH_KEY,
            ),
            new Attribute(
                key: 'installationInternalId',
                type: ColumnType::String,
                size: Database::LENGTH_KEY,
            ),
            new Attribute(
                key: 'providerRepositoryId',
                type: ColumnType::String,
                size: Database::LENGTH_KEY,
            ),
            new Attribute(
                key: 'repositoryId',
                type: ColumnType::String,
                size: Database::LENGTH_KEY,
            ),
            new Attribute(
                key: 'repositoryInternalId',
                type: ColumnType::String,
                size: Database::LENGTH_KEY,
            ),
            new Attribute(
                key: 'providerBranch',
                type: ColumnType::String,
                size: Database::LENGTH_KEY,
            ),
            new Attribute(
                key: 'providerRootDirectory',
                type: ColumnType::String,
                size: Database::LENGTH_KEY,
            ),
            new Attribute(
                key: 'providerSilentMode',
                type: ColumnType::Boolean,
                default: false,
            ),
            new Attribute(
                key: 'logging',
                type: ColumnType::Boolean,
                required: true,
            ),
            new Attribute(
                key: 'framework',
                type: ColumnType::String,
                size: 2048,
            ),
            new Attribute(
                key: 'outputDirectory',
                type: ColumnType::String,
                size: 16384,
            ),
            new Attribute(
                key: 'buildCommand',
                type: ColumnType::String,
                size: 16384,
            ),
            new Attribute(
                key: 'installCommand',
                type: ColumnType::String,
                size: 16384,
            ),
            new Attribute(
                key: 'startCommand',
                type: ColumnType::String,
                size: 20000,
            ),
            new Attribute(
                key: 'fallbackFile',
                type: ColumnType::String,
                size: 16384,
            ),
            new Attribute(
                key: 'deploymentRetention',
                type: ColumnType::Integer,
                default: 0,
            ),
            new Attribute(
                key: 'deploymentInternalId',
                type: ColumnType::String,
                size: Database::LENGTH_KEY,
            ),
            new Attribute(
                key: 'deploymentId',
                type: ColumnType::String,
                size: Database::LENGTH_KEY,
            ),
            new Attribute(
                key: 'deploymentCreatedAt',
                type: ColumnType::Datetime,
                signed: false,
                filters: ['datetime'],
            ),
            // File ID from 'screenshots' Console bucket
            new Attribute(
                key: 'deploymentScreenshotLight',
                type: ColumnType::String,
                size: 32,
                signed: false,
            ),
            // File ID from 'screenshots' Console bucket
            new Attribute(
                key: 'deploymentScreenshotDark',
                type: ColumnType::String,
                size: 32,
                signed: false,
            ),
            new Attribute(
                key: 'latestDeploymentId',
                type: ColumnType::String,
                size: Database::LENGTH_KEY,
            ),
            new Attribute(
                key: 'latestDeploymentInternalId',
                type: ColumnType::String,
                size: Database::LENGTH_KEY,
            ),
            new Attribute(
                key: 'latestDeploymentCreatedAt',
                type: ColumnType::Datetime,
                signed: false,
                filters: ['datetime'],
            ),
            new Attribute(
                key: 'latestDeploymentStatus',
                type: ColumnType::String,
                size: 16,
                default: '',
            ),
            new Attribute(
                key: 'vars',
                type: ColumnType::String,
                size: 16384,
                filters: ['subQueryVariables'],
            ),
            new Attribute(
                key: 'varsProject',
                type: ColumnType::String,
                size: 16384,
                filters: ['subQueryProjectVariables'],
            ),
            new Attribute(
                key: 'timeout',
                type: ColumnType::Integer,
            ),
            new Attribute(
                key: 'search',
                type: ColumnType::String,
                size: 16384,
            ),
            new Attribute(
                key: 'specification',
                type: ColumnType::String,
                size: 128,
                default: APP_COMPUTE_SPECIFICATION_DEFAULT,
                signed: false,
            ),
            new Attribute(
                key: 'buildSpecification',
                type: ColumnType::String,
                size: 128,
                default: APP_SITES_BUILD_SPECIFICATION_DEFAULT,
                signed: false,
            ),
            new Attribute(
                key: 'runtimeSpecification',
                type: ColumnType::String,
                size: 128,
                default: APP_COMPUTE_SPECIFICATION_DEFAULT,
                signed: false,
            ),
            new Attribute(
                key: 'buildRuntime',
                type: ColumnType::String,
                size: 2048,
                required: true,
                default: '',
            ),
            // ssr or static; named this way as it's a term in SSR frameworks
            new Attribute(
                key: 'adapter',
                type: ColumnType::String,
                size: 16,
                default: '',
            ),
            new Attribute(
                key: 'scopes',
                type: ColumnType::String,
                size: Database::LENGTH_KEY,
                default: [],
                array: true,
            ),
            new Attribute(
                key: 'providerBranches',
                type: ColumnType::String,
                size: 128,
                default: [],
                array: true,
            ),
            new Attribute(
                key: 'providerPaths',
                type: ColumnType::String,
                size: 128,
                default: [],
                array: true,
            ),
        ],
        'indexes' => [
            new Index(
                key: '_key_search',
                type: IndexType::Fulltext,
                attributes: ['search'],
            ),
            new Index(
                key: '_key_name',
                type: IndexType::Key,
                attributes: ['name'],
                lengths: [256],
                orders: ['ASC'],
            ),
            new Index(
                key: '_key_enabled',
                type: IndexType::Key,
                attributes: ['enabled'],
                orders: ['ASC'],
            ),
            new Index(
                key: '_key_installationId',
                type: IndexType::Key,
                attributes: ['installationId'],
                lengths: [Database::LENGTH_KEY],
                orders: ['ASC'],
            ),
            new Index(
                key: '_key_installationInternalId',
                type: IndexType::Key,
                attributes: ['installationInternalId'],
                lengths: [Database::LENGTH_KEY],
                orders: ['ASC'],
            ),
            new Index(
                key: '_key_providerRepositoryId',
                type: IndexType::Key,
                attributes: ['providerRepositoryId'],
                lengths: [Database::LENGTH_KEY],
                orders: ['ASC'],
            ),
            new Index(
                key: '_key_repositoryId',
                type: IndexType::Key,
                attributes: ['repositoryId'],
                lengths: [Database::LENGTH_KEY],
                orders: ['ASC'],
            ),
            new Index(
                key: '_key_repositoryInternalId',
                type: IndexType::Key,
                attributes: ['repositoryInternalId'],
                lengths: [Database::LENGTH_KEY],
                orders: ['ASC'],
            ),
            new Index(
                key: '_key_framework',
                type: IndexType::Key,
                attributes: ['framework'],
                lengths: [64],
                orders: ['ASC'],
            ),
            new Index(
                key: '_key_deploymentId',
                type: IndexType::Key,
                attributes: ['deploymentId'],
                orders: ['ASC'],
            ),
        ],
    ],

    'deployments' => [
        '$collection' => ID::custom(Database::METADATA),
        '$id' => ID::custom('deployments'),
        'name' => 'Deployments',
        'attributes' => [
            new Attribute(
                key: 'resourceInternalId',
                type: ColumnType::String,
                size: Database::LENGTH_KEY,
            ),
            new Attribute(
                key: 'resourceId',
                type: ColumnType::String,
                size: Database::LENGTH_KEY,
            ),
            new Attribute(
                key: 'resourceType',
                type: ColumnType::String,
                size: Database::LENGTH_KEY,
            ),
            new Attribute(
                key: 'entrypoint',
                type: ColumnType::String,
                size: 2048,
            ),
            new Attribute(
                key: 'buildCommands',
                type: ColumnType::String,
                size: 16384,
            ),
            new Attribute(
                key: 'startCommand',
                type: ColumnType::String,
                size: 20000,
            ),
            new Attribute(
                key: 'buildOutput',
                type: ColumnType::String,
                size: 16384,
            ),
            new Attribute(
                key: 'sourcePath',
                type: ColumnType::String,
                size: 16384,
            ),
            new Attribute(
                key: 'type',
                type: ColumnType::String,
                size: 2048,
                required: true,
            ),
            new Attribute(
                key: 'installationId',
                type: ColumnType::String,
                size: Database::LENGTH_KEY,
            ),
            new Attribute(
                key: 'installationInternalId',
                type: ColumnType::String,
                size: Database::LENGTH_KEY,
            ),
            new Attribute(
                key: 'providerRepositoryId',
                type: ColumnType::String,
                size: Database::LENGTH_KEY,
            ),
            new Attribute(
                key: 'repositoryId',
                type: ColumnType::String,
                size: Database::LENGTH_KEY,
            ),
            new Attribute(
                key: 'repositoryInternalId',
                type: ColumnType::String,
                size: Database::LENGTH_KEY,
            ),
            new Attribute(
                key: 'providerRepositoryName',
                type: ColumnType::String,
                size: Database::LENGTH_KEY,
            ),
            new Attribute(
                key: 'providerRepositoryOwner',
                type: ColumnType::String,
                size: Database::LENGTH_KEY,
            ),
            new Attribute(
                key: 'providerRepositoryUrl',
                type: ColumnType::String,
                size: Database::LENGTH_KEY,
            ),
            new Attribute(
                key: 'providerCommitHash',
                type: ColumnType::String,
                size: Database::LENGTH_KEY,
            ),
            new Attribute(
                key: 'providerCommitAuthorUrl',
                type: ColumnType::String,
                size: Database::LENGTH_KEY,
            ),
            new Attribute(
                key: 'providerCommitAuthor',
                type: ColumnType::String,
                size: Database::LENGTH_KEY,
            ),
            new Attribute(
                key: 'providerCommitMessage',
                type: ColumnType::String,
                size: Database::LENGTH_KEY,
            ),
            new Attribute(
                key: 'providerCommitUrl',
                type: ColumnType::String,
                size: Database::LENGTH_KEY,
            ),
            new Attribute(
                key: 'providerBranch',
                type: ColumnType::String,
                size: Database::LENGTH_KEY,
            ),
            new Attribute(
                key: 'providerBranchUrl',
                type: ColumnType::String,
                size: Database::LENGTH_KEY,
            ),
            new Attribute(
                key: 'providerRootDirectory',
                type: ColumnType::String,
                size: Database::LENGTH_KEY,
            ),
            new Attribute(
                key: 'providerCommentId',
                type: ColumnType::String,
                size: 2048,
            ),
            new Attribute(
                key: 'sourceSize',
                type: ColumnType::Integer,
                size: 8,
                signed: false,
            ),
            // https://tools.ietf.org/html/rfc4288#section-4.2
            new Attribute(
                key: 'sourceMetadata',
                type: ColumnType::String,
                size: 16384,
                filters: ['json'],
            ),
            new Attribute(
                key: 'sourceChunksTotal',
                type: ColumnType::Integer,
                signed: false,
            ),
            new Attribute(
                key: 'sourceChunksUploaded',
                type: ColumnType::Integer,
                signed: false,
            ),
            new Attribute(
                key: 'activate',
                type: ColumnType::Boolean,
                default: false,
            ),
            // File ID from 'screenshots' Console bucket
            new Attribute(
                key: 'screenshotLight',
                type: ColumnType::String,
                size: 32,
                signed: false,
            ),
            // File ID from 'screenshots' Console bucket
            new Attribute(
                key: 'screenshotDark',
                type: ColumnType::String,
                size: 32,
                signed: false,
            ),
            new Attribute(
                key: 'buildStartedAt',
                type: ColumnType::Datetime,
                signed: false,
                filters: ['datetime'],
            ),
            new Attribute(
                key: 'buildEndedAt',
                type: ColumnType::Datetime,
                signed: false,
                filters: ['datetime'],
            ),
            new Attribute(
                key: 'buildDuration',
                type: ColumnType::Integer,
                signed: false,
            ),
            new Attribute(
                key: 'buildSize',
                type: ColumnType::Integer,
                size: 8,
                signed: false,
            ),
            new Attribute(
                key: 'totalSize',
                type: ColumnType::Integer,
                size: 8,
                signed: false,
            ),
            new Attribute(
                key: 'status',
                type: ColumnType::String,
                size: 16,
                default: 'waiting',
            ),
            new Attribute(
                key: 'buildPath',
                type: ColumnType::String,
                size: 16384,
                default: '',
            ),
            new Attribute(
                key: 'buildLogs',
                type: ColumnType::String,
                size: APP_LOG_LENGTH_LIMIT,
                default: '',
            ),
            // ssr or static; named this way as it's a term in SSR frameworks
            new Attribute(
                key: 'adapter',
                type: ColumnType::String,
                size: 16,
                default: '',
            ),
            new Attribute(
                key: 'fallbackFile',
                type: ColumnType::String,
                size: 16384,
            ),
        ],
        'indexes' => [
            new Index(
                key: '_key_resource',
                type: IndexType::Key,
                attributes: ['resourceId'],
                orders: ['ASC'],
            ),
            new Index(
                key: '_key_resource_type',
                type: IndexType::Key,
                attributes: ['resourceType'],
                orders: ['ASC'],
            ),
            new Index(
                key: '_key_sourceSize',
                type: IndexType::Key,
                attributes: ['sourceSize'],
                orders: ['ASC'],
            ),
            new Index(
                key: '_key_buildSize',
                type: IndexType::Key,
                attributes: ['buildSize'],
                orders: ['ASC'],
            ),
            new Index(
                key: '_key_totalSize',
                type: IndexType::Key,
                attributes: ['totalSize'],
                orders: ['ASC'],
            ),
            new Index(
                key: '_key_buildDuration',
                type: IndexType::Key,
                attributes: ['buildDuration'],
                orders: ['ASC'],
            ),
            new Index(
                key: '_key_activate',
                type: IndexType::Key,
                attributes: ['activate'],
                orders: ['ASC'],
            ),
            new Index(
                key: '_key_type',
                type: IndexType::Key,
                attributes: ['type'],
                lengths: [32],
                orders: ['ASC'],
            ),
            new Index(
                key: '_key_status',
                type: IndexType::Key,
                attributes: ['status'],
                lengths: [16],
                orders: ['ASC'],
            ),
            new Index(
                key: '_key_resourceId_resourceType',
                type: IndexType::Key,
                attributes: ['resourceId', 'resourceType'],
            ),
            new Index(
                key: '_key_resource_internal_id',
                type: IndexType::Key,
                attributes: ['resourceInternalId'],
            ),
        ],
    ],

    'executions' => [
        '$collection' => ID::custom(Database::METADATA),
        '$id' => ID::custom('executions'),
        'name' => 'Executions',
        'attributes' => [
            [
                '$id' => ID::custom('resourceInternalId'),
                'type' => Database::VAR_STRING,
                'format' => '',
                'size' => Database::LENGTH_KEY,
                'signed' => true,
                'required' => false,
                'default' => null,
                'array' => false,
                'filters' => [],
            ],
            [
                '$id' => ID::custom('resourceId'),
                'type' => Database::VAR_STRING,
                'format' => '',
                'size' => Database::LENGTH_KEY,
                'signed' => true,
                'required' => false,
                'default' => null,
                'array' => false,
                'filters' => [],
            ],
            [
                '$id' => ID::custom('resourceType'),
                'type' => Database::VAR_STRING,
                'format' => '',
                'size' => Database::LENGTH_KEY,
                'signed' => true,
                'required' => false,
                'default' => null,
                'array' => false,
                'filters' => [],
            ],
            [
                '$id' => ID::custom('deploymentInternalId'),
                'type' => Database::VAR_STRING,
                'format' => '',
                'size' => Database::LENGTH_KEY,
                'signed' => true,
                'required' => false,
                'default' => null,
                'array' => false,
                'filters' => [],
            ],
            [
                '$id' => ID::custom('deploymentId'),
                'type' => Database::VAR_STRING,
                'format' => '',
                'size' => Database::LENGTH_KEY,
                'signed' => true,
                'required' => false,
                'default' => null,
                'array' => false,
                'filters' => [],
            ],
            [
                'array' => false,
                '$id' => ID::custom('trigger'),
                'type' => Database::VAR_STRING,
                'format' => '',
                'size' => 128,
                'signed' => true,
                'required' => false,
                'default' => null,
                'filters' => [],
            ],
            [
                '$id' => ID::custom('status'),
                'type' => Database::VAR_STRING,
                'format' => '',
                'size' => 128,
                'signed' => true,
                'required' => false,
                'default' => null,
                'array' => false,
                'filters' => [],
            ],
            [
                '$id' => ID::custom('duration'),
                'type' => Database::VAR_FLOAT,
                'format' => '',
                'size' => 0,
                'signed' => true,
                'required' => false,
                'default' => null,
                'array' => false,
                'filters' => [],
            ],
            [
                '$id' => ID::custom('errors'),
                'type' => Database::VAR_STRING,
                'format' => '',
                'size' => APP_FUNCTION_ERROR_LENGTH_LIMIT,
                'signed' => true,
                'required' => false,
                'default' => null,
                'array' => false,
                'filters' => [],
            ],
            [
                '$id' => ID::custom('logs'),
                'type' => Database::VAR_STRING,
                'format' => '',
                'size' => APP_FUNCTION_LOG_LENGTH_LIMIT,
                'signed' => true,
                'required' => false,
                'default' => null,
                'array' => false,
                'filters' => [],
            ],
            [
                'array' => false,
                '$id' => ID::custom('requestMethod'),
                'type' => Database::VAR_STRING,
                'format' => '',
                'size' => 128,
                'signed' => true,
                'required' => false,
                'default' => null,
                'filters' => [],
            ],
            [
                'array' => false,
                '$id' => ID::custom('requestPath'),
                'type' => Database::VAR_STRING,
                'format' => '',
                'size' => 2048,
                'signed' => true,
                'required' => false,
                'default' => null,
                'filters' => [],
            ],
            [
                '$id' => ID::custom('requestHeaders'),
                'type' => Database::VAR_STRING,
                'format' => '',
                'size' => 16384,
                'signed' => true,
                'required' => false,
                'default' => null,
                'array' => false,
                'filters' => ['json'],
            ],
            [
                '$id' => ID::custom('responseStatusCode'),
                'type' => Database::VAR_INTEGER,
                'format' => '',
                'size' => 0,
                'signed' => true,
                'required' => false,
                'default' => null,
                'array' => false,
                'filters' => [],
            ],
            [
                '$id' => ID::custom('responseHeaders'),
                'type' => Database::VAR_STRING,
                'format' => '',
                'size' => 16384,
                'signed' => true,
                'required' => false,
                'default' => null,
                'array' => false,
                'filters' => ['json'],
            ],
            [
                '$id' => ID::custom('scheduledAt'),
                'type' => Database::VAR_DATETIME,
                'format' => '',
                'size' => 0,
                'signed' => false,
                'required' => false,
                'default' => null,
                'array' => false,
                'filters' => ['datetime'],
            ],
            [
                '$id' => ID::custom('scheduleInternalId'),
                'type' => Database::VAR_STRING,
                'format' => '',
                'size' => Database::LENGTH_KEY,
                'signed' => true,
                'required' => false,
                'default' => null,
                'array' => false,
                'filters' => [],
            ],
            [
                '$id' => ID::custom('scheduleId'),
                'type' => Database::VAR_STRING,
                'format' => '',
                'size' => Database::LENGTH_KEY,
                'signed' => true,
                'required' => false,
                'default' => null,
                'array' => false,
                'filters' => [],
            ],
        ],
        'indexes' => [
            [
                '$id' => ID::custom('_key_resource'),
                'type' => Database::INDEX_KEY,
                'attributes' => ['resourceInternalId', 'resourceType', 'resourceId'],
                'lengths' => [Database::LENGTH_KEY],
                'orders' => [Database::ORDER_ASC],
            ],
            [
                '$id' => ID::custom('_key_trigger'),
                'type' => Database::INDEX_KEY,
                'attributes' => ['trigger'],
                'lengths' => [32],
                'orders' => [Database::ORDER_ASC],
            ],
            [
                '$id' => ID::custom('_key_status'),
                'type' => Database::INDEX_KEY,
                'attributes' => ['status'],
                'lengths' => [32],
                'orders' => [Database::ORDER_ASC],
            ],
            [
                '$id' => ID::custom('_key_requestMethod'),
                'type' => Database::INDEX_KEY,
                'attributes' => ['requestMethod'],
                'lengths' => [128],
                'orders' => [Database::ORDER_ASC],
            ],
            [
                '$id' => ID::custom('_key_requestPath'),
                'type' => Database::INDEX_KEY,
                'attributes' => ['requestPath'],
                'lengths' => [Database::LENGTH_KEY],
                'orders' => [Database::ORDER_ASC],
            ],
            [
                '$id' => ID::custom('_key_deployment'),
                'type' => Database::INDEX_KEY,
                'attributes' => ['deploymentId'],
                'lengths' => [Database::LENGTH_KEY],
                'orders' => [Database::ORDER_ASC],
            ],
            [
                '$id' => ID::custom('_key_responseStatusCode'),
                'type' => Database::INDEX_KEY,
                'attributes' => ['responseStatusCode'],
                'lengths' => [],
                'orders' => [Database::ORDER_ASC],
            ],
            [
                '$id' => ID::custom('_key_duration'),
                'type' => Database::INDEX_KEY,
                'attributes' => ['duration'],
                'lengths' => [],
                'orders' => [Database::ORDER_ASC],
            ],
            [
                '$id' => ID::custom('_key_resourceType'),
                'type' => Database::INDEX_KEY,
                'attributes' => ['resourceType'],
                'lengths' => [],
                'orders' => [Database::ORDER_ASC],
            ],
        ],
    ],

    'variables' => [
        '$collection' => Database::METADATA,
        '$id' => 'variables',
        'name' => 'variables',
        'attributes' => [
            new Attribute(
                key: 'resourceType',
                type: ColumnType::String,
                size: 100,
                required: true,
            ),
            new Attribute(
                key: 'resourceInternalId',
                type: ColumnType::String,
                size: Database::LENGTH_KEY,
            ),
            new Attribute(
                key: 'resourceId',
                type: ColumnType::String,
                size: Database::LENGTH_KEY,
            ),
            new Attribute(
                key: 'key',
                type: ColumnType::String,
                size: Database::LENGTH_KEY,
            ),
            new Attribute(
                key: 'value',
                type: ColumnType::String,
                size: 8192,
                required: true,
                filters: ['encrypt'],
            ),
            new Attribute(
                key: 'secret',
                type: ColumnType::Boolean,
                default: false,
            ),
            new Attribute(
                key: 'search',
                type: ColumnType::String,
                size: 16384,
            ),
        ],
        'indexes' => [
            new Index(
                key: '_key_resourceInternalId',
                type: IndexType::Key,
                attributes: ['resourceInternalId'],
                lengths: [Database::LENGTH_KEY],
            ),
            new Index(
                key: '_key_resourceType',
                type: IndexType::Key,
                attributes: ['resourceType'],
                orders: ['ASC'],
            ),
            new Index(
                key: '_key_resourceId_resourceType',
                type: IndexType::Key,
                attributes: ['resourceId', 'resourceType'],
                lengths: [Database::LENGTH_KEY, 100],
                orders: ['ASC', 'ASC'],
            ),
            new Index(
                key: '_key_uniqueKey',
                type: IndexType::Unique,
                attributes: ['resourceId', 'key', 'resourceType'],
                lengths: [Database::LENGTH_KEY, Database::LENGTH_KEY, 100],
                orders: ['ASC', 'ASC', 'ASC'],
            ),
            new Index(
                key: '_key_key',
                type: IndexType::Key,
                attributes: ['key'],
                lengths: [Database::LENGTH_KEY],
                orders: ['ASC'],
            ),
            new Index(
                key: '_fulltext_search',
                type: IndexType::Fulltext,
                attributes: ['search'],
            ),
            new Index(
                key: '_key_resource_internal_id_resource_type',
                type: IndexType::Key,
                attributes: ['resourceInternalId', 'resourceType'],
            ),
        ],
    ],

    'migrations' => [
        '$collection' => ID::custom(Database::METADATA),
        '$id' => ID::custom('migrations'),
        'name' => 'Migrations',
        'attributes' => [
            new Attribute(
                key: 'status',
                type: ColumnType::String,
                size: Database::LENGTH_KEY,
                required: true,
            ),
            new Attribute(
                key: 'stage',
                type: ColumnType::String,
                size: Database::LENGTH_KEY,
                required: true,
            ),
            // reduce size
            new Attribute(
                key: 'source',
                type: ColumnType::String,
                size: 8192,
                required: true,
            ),
            // make true after patch script
            new Attribute(
                key: 'destination',
                type: ColumnType::String,
                size: Database::LENGTH_KEY,
            ),
            new Attribute(
                key: 'credentials',
                type: ColumnType::String,
                size: 65536,
                default: [],
                filters: ['json', 'encrypt'],
            ),
            new Attribute(
                key: 'options',
                type: ColumnType::String,
                size: 65536,
                default: [],
                filters: ['json'],
            ),
            new Attribute(
                key: 'resources',
                type: ColumnType::String,
                size: Database::LENGTH_KEY,
                required: true,
                default: [],
                array: true,
            ),
            new Attribute(
                key: 'statusCounters',
                type: ColumnType::String,
                size: 3000,
                required: true,
                filters: ['json'],
            ),
            new Attribute(
                key: 'resourceData',
                type: ColumnType::String,
                size: 131070,
                required: true,
                filters: ['json'],
            ),
            new Attribute(
                key: 'errors',
                type: ColumnType::String,
                size: 1_000_000,
                required: true,
                array: true,
            ),
            new Attribute(
                key: 'search',
                type: ColumnType::String,
                size: 16384,
            ),
            new Attribute(
                key: 'resourceId',
                type: ColumnType::String,
                size: Database::LENGTH_KEY,
            ),
            new Attribute(
                key: 'resourceInternalId',
                type: ColumnType::String,
                size: Database::LENGTH_KEY,
            ),
            new Attribute(
                key: 'resourceType',
                type: ColumnType::String,
                size: Database::LENGTH_KEY,
            ),
            new Attribute(
                key: 'parentResourceId',
                type: ColumnType::String,
                size: Database::LENGTH_KEY,
            ),
            new Attribute(
                key: 'parentResourceInternalId',
                type: ColumnType::String,
                size: Database::LENGTH_KEY,
            ),
            new Attribute(
                key: 'parentResourceType',
                type: ColumnType::String,
                size: Database::LENGTH_KEY,
            ),
            new Attribute(
                key: 'destinationResourceId',
                type: ColumnType::String,
                size: Database::LENGTH_KEY,
            ),
            new Attribute(
                key: 'destinationResourceInternalId',
                type: ColumnType::String,
                size: Database::LENGTH_KEY,
            ),
            new Attribute(
                key: 'destinationResourceType',
                type: ColumnType::String,
                size: Database::LENGTH_KEY,
            ),
        ],
        'indexes' => [
            new Index(
                key: '_key_status',
                type: IndexType::Key,
                attributes: ['status'],
                lengths: [Database::LENGTH_KEY],
                orders: ['ASC'],
            ),
            new Index(
                key: '_key_stage',
                type: IndexType::Key,
                attributes: ['stage'],
                lengths: [Database::LENGTH_KEY],
                orders: ['ASC'],
            ),
            new Index(
                key: '_key_source',
                type: IndexType::Key,
                attributes: ['source'],
                lengths: [Database::LENGTH_KEY],
                orders: ['ASC'],
            ),
            new Index(
                key: '_key_resource_id',
                type: IndexType::Key,
                attributes: ['resourceId'],
                lengths: [Database::LENGTH_KEY],
                orders: ['DESC'],
            ),
            new Index(
                key: '_key_resourceType',
                type: IndexType::Key,
                attributes: ['resourceType'],
                lengths: [Database::LENGTH_KEY],
                orders: ['ASC'],
            ),
            new Index(
                key: '_key_resourceInternalId',
                type: IndexType::Key,
                attributes: ['resourceInternalId'],
                lengths: [Database::LENGTH_KEY],
                orders: ['ASC'],
            ),
            new Index(
                key: '_key_parentResourceId',
                type: IndexType::Key,
                attributes: ['parentResourceId'],
                lengths: [Database::LENGTH_KEY],
                orders: ['ASC'],
            ),
            new Index(
                key: '_key_parentResourceType',
                type: IndexType::Key,
                attributes: ['parentResourceType'],
                lengths: [Database::LENGTH_KEY],
                orders: ['ASC'],
            ),
            new Index(
                key: '_key_parentResourceInternalId',
                type: IndexType::Key,
                attributes: ['parentResourceInternalId'],
                lengths: [Database::LENGTH_KEY],
                orders: ['ASC'],
            ),
            new Index(
                key: '_key_destinationResourceId',
                type: IndexType::Key,
                attributes: ['destinationResourceId'],
                lengths: [Database::LENGTH_KEY],
                orders: ['ASC'],
            ),
            new Index(
                key: '_key_destinationResourceInternalId',
                type: IndexType::Key,
                attributes: ['destinationResourceInternalId'],
                lengths: [Database::LENGTH_KEY],
                orders: ['ASC'],
            ),
            new Index(
                key: '_key_destinationResourceType',
                type: IndexType::Key,
                attributes: ['destinationResourceType'],
                lengths: [Database::LENGTH_KEY],
                orders: ['ASC'],
            ),
            new Index(
                key: '_fulltext_search',
                type: IndexType::Fulltext,
                attributes: ['search'],
            ),
        ],
    ],

    'resourceTokens' => [
        '$collection' => ID::custom(Database::METADATA),
        '$id' => ID::custom('resourceTokens'),
        'name' => 'Resource Tokens',
        'attributes' => [
            new Attribute(
                key: 'resourceId',
                type: ColumnType::String,
                size: Database::LENGTH_KEY,
                required: true,
            ),
            new Attribute(
                key: 'resourceInternalId',
                type: ColumnType::String,
                size: Database::LENGTH_KEY,
                required: true,
            ),
            new Attribute(
                key: 'resourceType',
                type: ColumnType::String,
                size: 100,
                required: true,
            ),
            new Attribute(
                key: 'secret',
                type: ColumnType::String,
                size: 512,
                required: true,
                filters: ['encrypt'],
            ),
            new Attribute(
                key: 'expire',
                type: ColumnType::Datetime,
                size: 255,
                filters: ['datetime'],
            ),
            new Attribute(
                key: 'accessedAt',
                type: ColumnType::Datetime,
                signed: false,
                filters: ['datetime'],
            ),
        ],
        'indexes' => [
            new Index(
                key: '_key_expiry_date',
                type: IndexType::Key,
                attributes: ['expire'],
                orders: ['ASC'],
            ),
            new Index(
                key: '_key_accessedAt',
                type: IndexType::Key,
                attributes: ['accessedAt'],
            ),
            new Index(
                key: '_key_resourceInternalId_resourceType',
                type: IndexType::Key,
                attributes: ['resourceInternalId', 'resourceType'],
            ),
        ],
    ],

    'transactions' => [
        '$collection' => ID::custom(Database::METADATA),
        '$id' => ID::custom('transactions'),
        'name' => 'Transactions',
        'attributes' => [
            // pending | committing | committed | failed
            new Attribute(
                key: 'status',
                type: ColumnType::String,
                size: 16,
                default: 'pending',
            ),
            new Attribute(
                key: 'operations',
                type: ColumnType::Integer,
                required: true,
                default: 0,
                signed: false,
            ),
            new Attribute(
                key: 'expiresAt',
                type: ColumnType::Datetime,
                required: true,
                filters: ['datetime'],
            ),
        ],
        'indexes' => [
            new Index(
                key: '_key_expiresAt',
                type: IndexType::Key,
                attributes: ['expiresAt'],
                orders: ['DESC'],
            ),
        ],
    ],

    'transactionLogs' => [
        '$collection' => ID::custom(Database::METADATA),
        '$id' => ID::custom('transactionLogs'),
        'name' => 'Transaction Logs',
        'attributes' => [
            new Attribute(
                key: 'transactionInternalId',
                type: ColumnType::String,
                size: Database::LENGTH_KEY,
                required: true,
            ),
            new Attribute(
                key: 'databaseInternalId',
                type: ColumnType::String,
                size: Database::LENGTH_KEY,
                required: true,
            ),
            new Attribute(
                key: 'collectionInternalId',
                type: ColumnType::String,
                size: Database::LENGTH_KEY,
                required: true,
            ),
            new Attribute(
                key: 'documentId',
                type: ColumnType::String,
                size: Database::LENGTH_KEY,
            ),
            // create | update | upsert | increment | decrement | delete | bulkCreate | bulkUpdate | bulkUpsert | bulkDelete
            new Attribute(
                key: 'action',
                type: ColumnType::String,
                size: 32,
                required: true,
            ),
            // Allow large payloads for bulk operations
            new Attribute(
                key: 'data',
                type: ColumnType::String,
                size: 5_000_000,
                required: true,
                signed: false,
                filters: ['json'],
            ),
        ],
        'indexes' => [
            new Index(
                key: '_key_transaction',
                type: IndexType::Key,
                attributes: ['transactionInternalId'],
            ),
        ],
    ],
];
