/**
 * Hand-written Agent client: the agent API has not merged into cloud `main`, so
 * the generated SDK carries no `Agent` service. Delete this folder for the
 * generated one once it ships. `teamId` is optional here — the route defaults it
 * to '' and the console lets the server resolve the team from the org context.
 */

import { AppwriteException, type Client } from '@appwrite.io/console'

import type {
  AgentAutomation,
  AgentAutomationList,
  AgentConversation,
  AgentConversationList,
  AgentMcpConnection,
  AgentMcpConnectionList,
  AgentMemory,
  AgentMemoryList,
  AgentMessage,
  AgentMessageList,
  AgentModel,
  AgentModelList,
} from './models'

export class Agent {
  client: Client

  constructor(client: Client) {
    this.client = client
  }

  /**
   * List agent automations for a team.
   *
   * @param {string} params.teamId - Team unique ID. Omit to let the server
   *   resolve the team from the console organization context.
   * @param {string[]} params.queries - Queries generated by SDK Query class.
   * @throws {AppwriteException}
   * @returns {Promise<AgentAutomationList>}
   */
  listAutomations(params: {
    teamId?: string
    queries?: string[]
  }): Promise<AgentAutomationList> {
    const teamId = params.teamId
    const queries = params.queries
    const apiPath = '/agent/automations'
    const payload: Record<string, unknown> = {}
    if (typeof teamId !== 'undefined') {
      payload['teamId'] = teamId
    }
    if (typeof queries !== 'undefined') {
      payload['queries'] = queries
    }
    const uri = new URL(this.client.config.endpoint + apiPath)
    const apiHeaders: Record<string, string> = {
      'X-Appwrite-Project': this.client.config.project,
      accept: 'application/json',
    }
    return this.client.call('get', uri, apiHeaders, payload)
  }

  /**
   * Create an agent automation for a team that runs on a cron schedule and creates a conversation each run.
   *
   * @param {string} params.teamId - Team unique ID. Omit to let the server
   *   resolve the team from the console organization context.
   * @param {string} params.automationId - Automation ID. Must match ^[a-z][a-z0-9_-]{1,63}$ when not using unique().
   * @param {string} params.name - Display name.
   * @param {string} params.prompt - First user message sent on every run.
   * @param {string} params.schedule - Cron expression controlling when this automation runs.
   * @param {string} params.titlePrefix - Prefix used for conversation titles created by this automation.
   * @param {string} params.modelId - Optional custom LLM model ID (agentModels) to use for runs.
   * @param {number} params.modelTemp - Model temperature.
   * @param {string} params.contextTeamId - Optional team ID context.
   * @param {string} params.contextProjectId - Optional project ID context.
   * @param {string} params.contextOrganizationId - Optional organization ID context.
   * @param {string} params.contextPagePath - Optional console page path context.
   * @param {string} params.contextPageTitle - Optional console page title context.
   * @param {string} params.contextPageUrl - Optional console page URL context.
   * @param {string[]} params.attachments - Optional list of agent attachment file IDs sent with each run.
   * @param {boolean} params.enabled - Whether this automation is scheduled to run.
   * @throws {AppwriteException}
   * @returns {Promise<AgentAutomation>}
   */
  createAutomation(params: {
    teamId?: string
    automationId: string
    name: string
    prompt: string
    schedule: string
    titlePrefix?: string
    modelId?: string
    modelTemp?: number
    contextTeamId?: string
    contextProjectId?: string
    contextOrganizationId?: string
    contextPagePath?: string
    contextPageTitle?: string
    contextPageUrl?: string
    attachments?: string[]
    enabled?: boolean
  }): Promise<AgentAutomation> {
    const teamId = params.teamId
    const automationId = params.automationId
    const name = params.name
    const prompt = params.prompt
    const schedule = params.schedule
    const titlePrefix = params.titlePrefix
    const modelId = params.modelId
    const modelTemp = params.modelTemp
    const contextTeamId = params.contextTeamId
    const contextProjectId = params.contextProjectId
    const contextOrganizationId = params.contextOrganizationId
    const contextPagePath = params.contextPagePath
    const contextPageTitle = params.contextPageTitle
    const contextPageUrl = params.contextPageUrl
    const attachments = params.attachments
    const enabled = params.enabled
    if (typeof automationId === 'undefined') {
      throw new AppwriteException('Missing required parameter: "automationId"')
    }
    if (typeof name === 'undefined') {
      throw new AppwriteException('Missing required parameter: "name"')
    }
    if (typeof prompt === 'undefined') {
      throw new AppwriteException('Missing required parameter: "prompt"')
    }
    if (typeof schedule === 'undefined') {
      throw new AppwriteException('Missing required parameter: "schedule"')
    }
    const apiPath = '/agent/automations'
    const payload: Record<string, unknown> = {}
    if (typeof teamId !== 'undefined') {
      payload['teamId'] = teamId
    }
    if (typeof automationId !== 'undefined') {
      payload['automationId'] = automationId
    }
    if (typeof name !== 'undefined') {
      payload['name'] = name
    }
    if (typeof titlePrefix !== 'undefined') {
      payload['titlePrefix'] = titlePrefix
    }
    if (typeof prompt !== 'undefined') {
      payload['prompt'] = prompt
    }
    if (typeof modelId !== 'undefined') {
      payload['modelId'] = modelId
    }
    if (typeof modelTemp !== 'undefined') {
      payload['modelTemp'] = modelTemp
    }
    if (typeof contextTeamId !== 'undefined') {
      payload['contextTeamId'] = contextTeamId
    }
    if (typeof contextProjectId !== 'undefined') {
      payload['contextProjectId'] = contextProjectId
    }
    if (typeof contextOrganizationId !== 'undefined') {
      payload['contextOrganizationId'] = contextOrganizationId
    }
    if (typeof contextPagePath !== 'undefined') {
      payload['contextPagePath'] = contextPagePath
    }
    if (typeof contextPageTitle !== 'undefined') {
      payload['contextPageTitle'] = contextPageTitle
    }
    if (typeof contextPageUrl !== 'undefined') {
      payload['contextPageUrl'] = contextPageUrl
    }
    if (typeof attachments !== 'undefined') {
      payload['attachments'] = attachments
    }
    if (typeof schedule !== 'undefined') {
      payload['schedule'] = schedule
    }
    if (typeof enabled !== 'undefined') {
      payload['enabled'] = enabled
    }
    const uri = new URL(this.client.config.endpoint + apiPath)
    const apiHeaders: Record<string, string> = {
      'X-Appwrite-Project': this.client.config.project,
      'content-type': 'application/json',
      accept: 'application/json',
    }
    return this.client.call('post', uri, apiHeaders, payload)
  }

  /**
   * Get an agent automation by ID.
   *
   * @param {string} params.automationId - Automation unique ID.
   * @throws {AppwriteException}
   * @returns {Promise<AgentAutomation>}
   */
  getAutomation(params: { automationId: string }): Promise<AgentAutomation> {
    const automationId = params.automationId
    if (typeof automationId === 'undefined') {
      throw new AppwriteException('Missing required parameter: "automationId"')
    }
    const apiPath = '/agent/automations/{automationId}'.replace(
      '{automationId}',
      encodeURIComponent(String(automationId)),
    )
    const payload: Record<string, unknown> = {}
    const uri = new URL(this.client.config.endpoint + apiPath)
    const apiHeaders: Record<string, string> = {
      'X-Appwrite-Project': this.client.config.project,
      accept: 'application/json',
    }
    return this.client.call('get', uri, apiHeaders, payload)
  }

  /**
   * Update an agent automation. Pass an empty string for modelId to clear the override and use the Appwrite default.
   *
   * @param {string} params.automationId - Automation unique ID.
   * @param {string} params.name - Display name.
   * @param {string} params.titlePrefix - Prefix used for conversation titles created by this automation.
   * @param {string} params.prompt - First user message sent on every run.
   * @param {string} params.modelId - Custom LLM model ID. Pass an empty string to clear the override.
   * @param {number} params.modelTemp - Model temperature.
   * @param {string} params.contextTeamId - Optional team ID context.
   * @param {string} params.contextProjectId - Optional project ID context.
   * @param {string} params.contextOrganizationId - Optional organization ID context.
   * @param {string} params.contextPagePath - Optional console page path context.
   * @param {string} params.contextPageTitle - Optional console page title context.
   * @param {string} params.contextPageUrl - Optional console page URL context.
   * @param {string[]} params.attachments - Optional list of agent attachment file IDs sent with each run.
   * @param {string} params.schedule - Cron expression controlling when this automation runs.
   * @param {boolean} params.enabled - Whether this automation is scheduled to run.
   * @throws {AppwriteException}
   * @returns {Promise<AgentAutomation>}
   */
  updateAutomation(params: {
    automationId: string
    name?: string
    titlePrefix?: string
    prompt?: string
    modelId?: string
    modelTemp?: number
    contextTeamId?: string
    contextProjectId?: string
    contextOrganizationId?: string
    contextPagePath?: string
    contextPageTitle?: string
    contextPageUrl?: string
    attachments?: string[]
    schedule?: string
    enabled?: boolean
  }): Promise<AgentAutomation> {
    const automationId = params.automationId
    const name = params.name
    const titlePrefix = params.titlePrefix
    const prompt = params.prompt
    const modelId = params.modelId
    const modelTemp = params.modelTemp
    const contextTeamId = params.contextTeamId
    const contextProjectId = params.contextProjectId
    const contextOrganizationId = params.contextOrganizationId
    const contextPagePath = params.contextPagePath
    const contextPageTitle = params.contextPageTitle
    const contextPageUrl = params.contextPageUrl
    const attachments = params.attachments
    const schedule = params.schedule
    const enabled = params.enabled
    if (typeof automationId === 'undefined') {
      throw new AppwriteException('Missing required parameter: "automationId"')
    }
    const apiPath = '/agent/automations/{automationId}'.replace(
      '{automationId}',
      encodeURIComponent(String(automationId)),
    )
    const payload: Record<string, unknown> = {}
    if (typeof name !== 'undefined') {
      payload['name'] = name
    }
    if (typeof titlePrefix !== 'undefined') {
      payload['titlePrefix'] = titlePrefix
    }
    if (typeof prompt !== 'undefined') {
      payload['prompt'] = prompt
    }
    if (typeof modelId !== 'undefined') {
      payload['modelId'] = modelId
    }
    if (typeof modelTemp !== 'undefined') {
      payload['modelTemp'] = modelTemp
    }
    if (typeof contextTeamId !== 'undefined') {
      payload['contextTeamId'] = contextTeamId
    }
    if (typeof contextProjectId !== 'undefined') {
      payload['contextProjectId'] = contextProjectId
    }
    if (typeof contextOrganizationId !== 'undefined') {
      payload['contextOrganizationId'] = contextOrganizationId
    }
    if (typeof contextPagePath !== 'undefined') {
      payload['contextPagePath'] = contextPagePath
    }
    if (typeof contextPageTitle !== 'undefined') {
      payload['contextPageTitle'] = contextPageTitle
    }
    if (typeof contextPageUrl !== 'undefined') {
      payload['contextPageUrl'] = contextPageUrl
    }
    if (typeof attachments !== 'undefined') {
      payload['attachments'] = attachments
    }
    if (typeof schedule !== 'undefined') {
      payload['schedule'] = schedule
    }
    if (typeof enabled !== 'undefined') {
      payload['enabled'] = enabled
    }
    const uri = new URL(this.client.config.endpoint + apiPath)
    const apiHeaders: Record<string, string> = {
      'X-Appwrite-Project': this.client.config.project,
      'content-type': 'application/json',
      accept: 'application/json',
    }
    return this.client.call('patch', uri, apiHeaders, payload)
  }

  /**
   * Delete an agent automation.
   *
   * @param {string} params.automationId - Automation unique ID.
   * @throws {AppwriteException}
   * @returns {Promise<{}>}
   */
  deleteAutomation(params: { automationId: string }): Promise<unknown> {
    const automationId = params.automationId
    if (typeof automationId === 'undefined') {
      throw new AppwriteException('Missing required parameter: "automationId"')
    }
    const apiPath = '/agent/automations/{automationId}'.replace(
      '{automationId}',
      encodeURIComponent(String(automationId)),
    )
    const payload: Record<string, unknown> = {}
    const uri = new URL(this.client.config.endpoint + apiPath)
    const apiHeaders: Record<string, string> = {
      'X-Appwrite-Project': this.client.config.project,
      'content-type': 'application/json',
      accept: 'application/json',
    }
    return this.client.call('delete', uri, apiHeaders, payload)
  }

  /**
   * List agent conversations for a team.
   *
   * @param {string} params.teamId - Team unique ID. Omit to let the server
   *   resolve the team from the console organization context.
   * @param {string[]} params.queries - Queries generated by SDK Query class.
   * @param {string} params.search - Search term to filter your list results. Max length: 256 chars.
   * @throws {AppwriteException}
   * @returns {Promise<AgentConversationList>}
   */
  listConversations(params: {
    teamId?: string
    queries?: string[]
    search?: string
  }): Promise<AgentConversationList> {
    const teamId = params.teamId
    const queries = params.queries
    const search = params.search
    const apiPath = '/agent/conversations'
    const payload: Record<string, unknown> = {}
    if (typeof teamId !== 'undefined') {
      payload['teamId'] = teamId
    }
    if (typeof queries !== 'undefined') {
      payload['queries'] = queries
    }
    if (typeof search !== 'undefined') {
      payload['search'] = search
    }
    const uri = new URL(this.client.config.endpoint + apiPath)
    const apiHeaders: Record<string, string> = {
      'X-Appwrite-Project': this.client.config.project,
      accept: 'application/json',
    }
    return this.client.call('get', uri, apiHeaders, payload)
  }

  /**
   * Create a new agent conversation for a team.
   *
   * @param {string} params.teamId - Team unique ID. Omit to let the server
   *   resolve the team from the console organization context.
   * @param {string} params.title - Conversation title.
   * @param {string} params.modelName - Model identifier.
   * @param {number} params.modelTemp - Model temperature.
   * @param {string} params.modelId - Optional custom LLM model ID (agentModels) to use for this conversation.
   * @throws {AppwriteException}
   * @returns {Promise<AgentConversation>}
   */
  createConversation(params: {
    teamId?: string
    title?: string
    modelName?: string
    modelTemp?: number
    modelId?: string
  }): Promise<AgentConversation> {
    const teamId = params.teamId
    const title = params.title
    const modelName = params.modelName
    const modelTemp = params.modelTemp
    const modelId = params.modelId
    const apiPath = '/agent/conversations'
    const payload: Record<string, unknown> = {}
    if (typeof teamId !== 'undefined') {
      payload['teamId'] = teamId
    }
    if (typeof title !== 'undefined') {
      payload['title'] = title
    }
    if (typeof modelName !== 'undefined') {
      payload['modelName'] = modelName
    }
    if (typeof modelTemp !== 'undefined') {
      payload['modelTemp'] = modelTemp
    }
    if (typeof modelId !== 'undefined') {
      payload['modelId'] = modelId
    }
    const uri = new URL(this.client.config.endpoint + apiPath)
    const apiHeaders: Record<string, string> = {
      'X-Appwrite-Project': this.client.config.project,
      'content-type': 'application/json',
      accept: 'application/json',
    }
    return this.client.call('post', uri, apiHeaders, payload)
  }

  /**
   * Get a single agent conversation.
   *
   * @param {string} params.conversationId - Conversation unique ID.
   * @throws {AppwriteException}
   * @returns {Promise<AgentConversation>}
   */
  getConversation(params: {
    conversationId: string
  }): Promise<AgentConversation> {
    const conversationId = params.conversationId
    if (typeof conversationId === 'undefined') {
      throw new AppwriteException(
        'Missing required parameter: "conversationId"',
      )
    }
    const apiPath = '/agent/conversations/{conversationId}'.replace(
      '{conversationId}',
      encodeURIComponent(String(conversationId)),
    )
    const payload: Record<string, unknown> = {}
    const uri = new URL(this.client.config.endpoint + apiPath)
    const apiHeaders: Record<string, string> = {
      'X-Appwrite-Project': this.client.config.project,
      accept: 'application/json',
    }
    return this.client.call('get', uri, apiHeaders, payload)
  }

  /**
   * Patch conversation fields and control state.
   *
   * @param {string} params.conversationId - Conversation unique ID.
   * @param {string} params.title - Conversation title.
   * @param {string} params.status - Conversation status. Only archived can be set by clients; other statuses are managed by the worker.
   * @param {string} params.controlType - Control mutation type.
   * @param {string} params.retryFromMessageId - Message ID for retry control.
   * @param {string} params.modelName - Model identifier.
   * @param {number} params.modelTemp - Model temperature.
   * @param {string} params.modelId - Custom LLM model ID. Pass an empty string to clear the override and use the Appwrite default.
   * @param {string} params.lockReason - Lock reason.
   * @throws {AppwriteException}
   * @returns {Promise<AgentConversation>}
   */
  updateConversation(params: {
    conversationId: string
    title?: string
    status?: string
    controlType?: string
    retryFromMessageId?: string
    modelName?: string
    modelTemp?: number
    modelId?: string
    lockReason?: string
  }): Promise<AgentConversation> {
    const conversationId = params.conversationId
    const title = params.title
    const status = params.status
    const controlType = params.controlType
    const retryFromMessageId = params.retryFromMessageId
    const modelName = params.modelName
    const modelTemp = params.modelTemp
    const modelId = params.modelId
    const lockReason = params.lockReason
    if (typeof conversationId === 'undefined') {
      throw new AppwriteException(
        'Missing required parameter: "conversationId"',
      )
    }
    const apiPath = '/agent/conversations/{conversationId}'.replace(
      '{conversationId}',
      encodeURIComponent(String(conversationId)),
    )
    const payload: Record<string, unknown> = {}
    if (typeof title !== 'undefined') {
      payload['title'] = title
    }
    if (typeof status !== 'undefined') {
      payload['status'] = status
    }
    if (typeof controlType !== 'undefined') {
      payload['controlType'] = controlType
    }
    if (typeof retryFromMessageId !== 'undefined') {
      payload['retryFromMessageId'] = retryFromMessageId
    }
    if (typeof modelName !== 'undefined') {
      payload['modelName'] = modelName
    }
    if (typeof modelTemp !== 'undefined') {
      payload['modelTemp'] = modelTemp
    }
    if (typeof modelId !== 'undefined') {
      payload['modelId'] = modelId
    }
    if (typeof lockReason !== 'undefined') {
      payload['lockReason'] = lockReason
    }
    const uri = new URL(this.client.config.endpoint + apiPath)
    const apiHeaders: Record<string, string> = {
      'X-Appwrite-Project': this.client.config.project,
      'content-type': 'application/json',
      accept: 'application/json',
    }
    return this.client.call('patch', uri, apiHeaders, payload)
  }

  /**
   * Delete an agent conversation.
   *
   * @param {string} params.conversationId - Conversation unique ID.
   * @throws {AppwriteException}
   * @returns {Promise<{}>}
   */
  deleteConversation(params: { conversationId: string }): Promise<unknown> {
    const conversationId = params.conversationId
    if (typeof conversationId === 'undefined') {
      throw new AppwriteException(
        'Missing required parameter: "conversationId"',
      )
    }
    const apiPath = '/agent/conversations/{conversationId}'.replace(
      '{conversationId}',
      encodeURIComponent(String(conversationId)),
    )
    const payload: Record<string, unknown> = {}
    const uri = new URL(this.client.config.endpoint + apiPath)
    const apiHeaders: Record<string, string> = {
      'X-Appwrite-Project': this.client.config.project,
      'content-type': 'application/json',
      accept: 'application/json',
    }
    return this.client.call('delete', uri, apiHeaders, payload)
  }

  /**
   * List all messages under a conversation.
   *
   * @param {string} params.conversationId - Conversation unique ID.
   * @param {string[]} params.queries - Queries generated by SDK Query class.
   * @throws {AppwriteException}
   * @returns {Promise<AgentMessageList>}
   */
  listMessages(params: {
    conversationId: string
    queries?: string[]
  }): Promise<AgentMessageList> {
    const conversationId = params.conversationId
    const queries = params.queries
    if (typeof conversationId === 'undefined') {
      throw new AppwriteException(
        'Missing required parameter: "conversationId"',
      )
    }
    const apiPath = '/agent/conversations/{conversationId}/messages'.replace(
      '{conversationId}',
      encodeURIComponent(String(conversationId)),
    )
    const payload: Record<string, unknown> = {}
    if (typeof queries !== 'undefined') {
      payload['queries'] = queries
    }
    const uri = new URL(this.client.config.endpoint + apiPath)
    const apiHeaders: Record<string, string> = {
      'X-Appwrite-Project': this.client.config.project,
      accept: 'application/json',
    }
    return this.client.call('get', uri, apiHeaders, payload)
  }

  /**
   * Create a new user message under a conversation.
   *
   * @param {string} params.conversationId - Conversation unique ID.
   * @param {string} params.contentType - Message content type.
   * @param {string} params.contentText - Message content text. Optional when attachments are provided.
   * @param {string} params.contextTeamId - Optional current team ID from console context.
   * @param {string} params.contextProjectId - Optional current project ID from console context.
   * @param {string} params.contextOrganizationId - Optional current organization ID from console context.
   * @param {string} params.contextPagePath - Optional current console page path.
   * @param {string} params.contextPageTitle - Optional current console page title.
   * @param {string} params.contextPageUrl - Optional current console page URL.
   * @param {string[]} params.attachments - Optional list of agent attachment file IDs from the attachements bucket.
   * @param {boolean} params.continueRun - When true, mark conversation as running.
   * @throws {AppwriteException}
   * @returns {Promise<AgentMessage>}
   */
  createMessage(params: {
    conversationId: string
    contentType?: string
    contentText?: string
    contextTeamId?: string
    contextProjectId?: string
    contextOrganizationId?: string
    contextPagePath?: string
    contextPageTitle?: string
    contextPageUrl?: string
    attachments?: string[]
    continueRun?: boolean
  }): Promise<AgentMessage> {
    const conversationId = params.conversationId
    const contentType = params.contentType
    const contentText = params.contentText
    const contextTeamId = params.contextTeamId
    const contextProjectId = params.contextProjectId
    const contextOrganizationId = params.contextOrganizationId
    const contextPagePath = params.contextPagePath
    const contextPageTitle = params.contextPageTitle
    const contextPageUrl = params.contextPageUrl
    const attachments = params.attachments
    const continueRun = params.continueRun
    if (typeof conversationId === 'undefined') {
      throw new AppwriteException(
        'Missing required parameter: "conversationId"',
      )
    }
    const apiPath = '/agent/conversations/{conversationId}/messages'.replace(
      '{conversationId}',
      encodeURIComponent(String(conversationId)),
    )
    const payload: Record<string, unknown> = {}
    if (typeof contentType !== 'undefined') {
      payload['contentType'] = contentType
    }
    if (typeof contentText !== 'undefined') {
      payload['contentText'] = contentText
    }
    if (typeof contextTeamId !== 'undefined') {
      payload['contextTeamId'] = contextTeamId
    }
    if (typeof contextProjectId !== 'undefined') {
      payload['contextProjectId'] = contextProjectId
    }
    if (typeof contextOrganizationId !== 'undefined') {
      payload['contextOrganizationId'] = contextOrganizationId
    }
    if (typeof contextPagePath !== 'undefined') {
      payload['contextPagePath'] = contextPagePath
    }
    if (typeof contextPageTitle !== 'undefined') {
      payload['contextPageTitle'] = contextPageTitle
    }
    if (typeof contextPageUrl !== 'undefined') {
      payload['contextPageUrl'] = contextPageUrl
    }
    if (typeof attachments !== 'undefined') {
      payload['attachments'] = attachments
    }
    if (typeof continueRun !== 'undefined') {
      payload['continueRun'] = continueRun
    }
    const uri = new URL(this.client.config.endpoint + apiPath)
    const apiHeaders: Record<string, string> = {
      'X-Appwrite-Project': this.client.config.project,
      'content-type': 'application/json',
      accept: 'application/json',
    }
    return this.client.call('post', uri, apiHeaders, payload)
  }

  /**
   * Get a single message under a conversation.
   *
   * @param {string} params.conversationId - Conversation unique ID.
   * @param {string} params.messageId - Message unique ID.
   * @throws {AppwriteException}
   * @returns {Promise<AgentMessage>}
   */
  getMessage(params: {
    conversationId: string
    messageId: string
  }): Promise<AgentMessage> {
    const conversationId = params.conversationId
    const messageId = params.messageId
    if (typeof conversationId === 'undefined') {
      throw new AppwriteException(
        'Missing required parameter: "conversationId"',
      )
    }
    if (typeof messageId === 'undefined') {
      throw new AppwriteException('Missing required parameter: "messageId"')
    }
    const apiPath = '/agent/conversations/{conversationId}/messages/{messageId}'
      .replace('{conversationId}', encodeURIComponent(String(conversationId)))
      .replace('{messageId}', encodeURIComponent(String(messageId)))
    const payload: Record<string, unknown> = {}
    const uri = new URL(this.client.config.endpoint + apiPath)
    const apiHeaders: Record<string, string> = {
      'X-Appwrite-Project': this.client.config.project,
      accept: 'application/json',
    }
    return this.client.call('get', uri, apiHeaders, payload)
  }

  /**
   * Patch a single message under a conversation.
   *
   * @param {string} params.conversationId - Conversation unique ID.
   * @param {string} params.messageId - Message unique ID.
   * @param {string} params.status - Message status.
   * @param {string} params.contentText - Message content text.
   * @param {string} params.contextTeamId - Optional current team ID from console context.
   * @param {string} params.contextProjectId - Optional current project ID from console context.
   * @param {string} params.contextOrganizationId - Optional current organization ID from console context.
   * @param {string} params.contextPagePath - Optional current console page path.
   * @param {string} params.contextPageTitle - Optional current console page title.
   * @param {string} params.contextPageUrl - Optional current console page URL.
   * @param {string[]} params.attachments - Optional replacement list of attachment file IDs.
   * @param {boolean} params.continueRun - When true, queue a new agent run for the edited message.
   * @param {string} params.score - Feedback score for an agent message. `1` for thumbs up, `-1` for thumbs down, `0` to clear.
   * @throws {AppwriteException}
   * @returns {Promise<AgentMessage>}
   */
  updateMessage(params: {
    conversationId: string
    messageId: string
    status?: string
    contentText?: string
    contextTeamId?: string
    contextProjectId?: string
    contextOrganizationId?: string
    contextPagePath?: string
    contextPageTitle?: string
    contextPageUrl?: string
    attachments?: string[]
    continueRun?: boolean
    score?: string
  }): Promise<AgentMessage> {
    const conversationId = params.conversationId
    const messageId = params.messageId
    const status = params.status
    const contentText = params.contentText
    const contextTeamId = params.contextTeamId
    const contextProjectId = params.contextProjectId
    const contextOrganizationId = params.contextOrganizationId
    const contextPagePath = params.contextPagePath
    const contextPageTitle = params.contextPageTitle
    const contextPageUrl = params.contextPageUrl
    const attachments = params.attachments
    const continueRun = params.continueRun
    const score = params.score
    if (typeof conversationId === 'undefined') {
      throw new AppwriteException(
        'Missing required parameter: "conversationId"',
      )
    }
    if (typeof messageId === 'undefined') {
      throw new AppwriteException('Missing required parameter: "messageId"')
    }
    const apiPath = '/agent/conversations/{conversationId}/messages/{messageId}'
      .replace('{conversationId}', encodeURIComponent(String(conversationId)))
      .replace('{messageId}', encodeURIComponent(String(messageId)))
    const payload: Record<string, unknown> = {}
    if (typeof status !== 'undefined') {
      payload['status'] = status
    }
    if (typeof contentText !== 'undefined') {
      payload['contentText'] = contentText
    }
    if (typeof contextTeamId !== 'undefined') {
      payload['contextTeamId'] = contextTeamId
    }
    if (typeof contextProjectId !== 'undefined') {
      payload['contextProjectId'] = contextProjectId
    }
    if (typeof contextOrganizationId !== 'undefined') {
      payload['contextOrganizationId'] = contextOrganizationId
    }
    if (typeof contextPagePath !== 'undefined') {
      payload['contextPagePath'] = contextPagePath
    }
    if (typeof contextPageTitle !== 'undefined') {
      payload['contextPageTitle'] = contextPageTitle
    }
    if (typeof contextPageUrl !== 'undefined') {
      payload['contextPageUrl'] = contextPageUrl
    }
    if (typeof attachments !== 'undefined') {
      payload['attachments'] = attachments
    }
    if (typeof continueRun !== 'undefined') {
      payload['continueRun'] = continueRun
    }
    if (typeof score !== 'undefined') {
      payload['score'] = score
    }
    const uri = new URL(this.client.config.endpoint + apiPath)
    const apiHeaders: Record<string, string> = {
      'X-Appwrite-Project': this.client.config.project,
      'content-type': 'application/json',
      accept: 'application/json',
    }
    return this.client.call('patch', uri, apiHeaders, payload)
  }

  /**
   * List MCP server connections for a team.
   *
   * @param {string} params.teamId - Team unique ID. Omit to let the server
   *   resolve the team from the console organization context.
   * @param {string[]} params.queries - Queries generated by SDK Query class.
   * @throws {AppwriteException}
   * @returns {Promise<AgentMcpConnectionList>}
   */
  listMcpConnections(params: {
    teamId?: string
    queries?: string[]
  }): Promise<AgentMcpConnectionList> {
    const teamId = params.teamId
    const queries = params.queries
    const apiPath = '/agent/mcps'
    const payload: Record<string, unknown> = {}
    if (typeof teamId !== 'undefined') {
      payload['teamId'] = teamId
    }
    if (typeof queries !== 'undefined') {
      payload['queries'] = queries
    }
    const uri = new URL(this.client.config.endpoint + apiPath)
    const apiHeaders: Record<string, string> = {
      'X-Appwrite-Project': this.client.config.project,
      accept: 'application/json',
    }
    return this.client.call('get', uri, apiHeaders, payload)
  }

  /**
   * Create an MCP server connection for a team. OAuth is handled by the client; pass resulting tokens here.
   *
   * @param {string} params.teamId - Team unique ID. Omit to let the server
   *   resolve the team from the console organization context.
   * @param {string} params.mcpId - MCP connection ID. Must match ^[a-z][a-z0-9_-]{1,63}$ when not using unique().
   * @param {string} params.name - Display name.
   * @param {string} params.url - MCP server URL (https; http loopback allowed only in development).
   * @param {string} params.description - Optional description.
   * @param {boolean} params.enabled - Whether to include this connection on agent turns.
   * @param {string} params.tokens - OAuth token payload as a JSON object string (must include access_token).
   * @param {string} params.clientInfo - OAuth client info as a JSON object string.
   * @param {string} params.status - Optional status label.
   * @throws {AppwriteException}
   * @returns {Promise<AgentMcpConnection>}
   */
  createMcpConnection(params: {
    teamId?: string
    mcpId: string
    name: string
    url: string
    description?: string
    enabled?: boolean
    tokens?: string
    clientInfo?: string
    status?: string
  }): Promise<AgentMcpConnection> {
    const teamId = params.teamId
    const mcpId = params.mcpId
    const name = params.name
    const url = params.url
    const description = params.description
    const enabled = params.enabled
    const tokens = params.tokens
    const clientInfo = params.clientInfo
    const status = params.status
    if (typeof mcpId === 'undefined') {
      throw new AppwriteException('Missing required parameter: "mcpId"')
    }
    if (typeof name === 'undefined') {
      throw new AppwriteException('Missing required parameter: "name"')
    }
    if (typeof url === 'undefined') {
      throw new AppwriteException('Missing required parameter: "url"')
    }
    const apiPath = '/agent/mcps'
    const payload: Record<string, unknown> = {}
    if (typeof teamId !== 'undefined') {
      payload['teamId'] = teamId
    }
    if (typeof mcpId !== 'undefined') {
      payload['mcpId'] = mcpId
    }
    if (typeof name !== 'undefined') {
      payload['name'] = name
    }
    if (typeof url !== 'undefined') {
      payload['url'] = url
    }
    if (typeof description !== 'undefined') {
      payload['description'] = description
    }
    if (typeof enabled !== 'undefined') {
      payload['enabled'] = enabled
    }
    if (typeof tokens !== 'undefined') {
      payload['tokens'] = tokens
    }
    if (typeof clientInfo !== 'undefined') {
      payload['clientInfo'] = clientInfo
    }
    if (typeof status !== 'undefined') {
      payload['status'] = status
    }
    const uri = new URL(this.client.config.endpoint + apiPath)
    const apiHeaders: Record<string, string> = {
      'X-Appwrite-Project': this.client.config.project,
      'content-type': 'application/json',
      accept: 'application/json',
    }
    return this.client.call('post', uri, apiHeaders, payload)
  }

  /**
   * Get an MCP server connection by ID.
   *
   * @param {string} params.mcpId - MCP connection unique ID.
   * @throws {AppwriteException}
   * @returns {Promise<AgentMcpConnection>}
   */
  getMcpConnection(params: { mcpId: string }): Promise<AgentMcpConnection> {
    const mcpId = params.mcpId
    if (typeof mcpId === 'undefined') {
      throw new AppwriteException('Missing required parameter: "mcpId"')
    }
    const apiPath = '/agent/mcps/{mcpId}'.replace(
      '{mcpId}',
      encodeURIComponent(String(mcpId)),
    )
    const payload: Record<string, unknown> = {}
    const uri = new URL(this.client.config.endpoint + apiPath)
    const apiHeaders: Record<string, string> = {
      'X-Appwrite-Project': this.client.config.project,
      accept: 'application/json',
    }
    return this.client.call('get', uri, apiHeaders, payload)
  }

  /**
   * Update an MCP server connection. Omit tokens/clientInfo to leave stored secrets unchanged; pass empty JSON object strings to clear them.
   *
   * @param {string} params.mcpId - MCP connection unique ID.
   * @param {string} params.name - Display name.
   * @param {string} params.url - MCP server URL (https; http loopback allowed only in development).
   * @param {string} params.description - Optional description.
   * @param {boolean} params.enabled - Whether to include this connection on agent turns.
   * @param {string} params.tokens - OAuth token payload as a JSON object string. Omit to keep existing tokens.
   * @param {string} params.clientInfo - OAuth client info as a JSON object string. Omit to keep existing client info.
   * @param {string} params.status - Optional status label.
   * @throws {AppwriteException}
   * @returns {Promise<AgentMcpConnection>}
   */
  updateMcpConnection(params: {
    mcpId: string
    name?: string
    url?: string
    description?: string
    enabled?: boolean
    tokens?: string
    clientInfo?: string
    status?: string
  }): Promise<AgentMcpConnection> {
    const mcpId = params.mcpId
    const name = params.name
    const url = params.url
    const description = params.description
    const enabled = params.enabled
    const tokens = params.tokens
    const clientInfo = params.clientInfo
    const status = params.status
    if (typeof mcpId === 'undefined') {
      throw new AppwriteException('Missing required parameter: "mcpId"')
    }
    const apiPath = '/agent/mcps/{mcpId}'.replace(
      '{mcpId}',
      encodeURIComponent(String(mcpId)),
    )
    const payload: Record<string, unknown> = {}
    if (typeof name !== 'undefined') {
      payload['name'] = name
    }
    if (typeof url !== 'undefined') {
      payload['url'] = url
    }
    if (typeof description !== 'undefined') {
      payload['description'] = description
    }
    if (typeof enabled !== 'undefined') {
      payload['enabled'] = enabled
    }
    if (typeof tokens !== 'undefined') {
      payload['tokens'] = tokens
    }
    if (typeof clientInfo !== 'undefined') {
      payload['clientInfo'] = clientInfo
    }
    if (typeof status !== 'undefined') {
      payload['status'] = status
    }
    const uri = new URL(this.client.config.endpoint + apiPath)
    const apiHeaders: Record<string, string> = {
      'X-Appwrite-Project': this.client.config.project,
      'content-type': 'application/json',
      accept: 'application/json',
    }
    return this.client.call('patch', uri, apiHeaders, payload)
  }

  /**
   * Delete an MCP server connection.
   *
   * @param {string} params.mcpId - MCP connection unique ID.
   * @throws {AppwriteException}
   * @returns {Promise<{}>}
   */
  deleteMcpConnection(params: { mcpId: string }): Promise<unknown> {
    const mcpId = params.mcpId
    if (typeof mcpId === 'undefined') {
      throw new AppwriteException('Missing required parameter: "mcpId"')
    }
    const apiPath = '/agent/mcps/{mcpId}'.replace(
      '{mcpId}',
      encodeURIComponent(String(mcpId)),
    )
    const payload: Record<string, unknown> = {}
    const uri = new URL(this.client.config.endpoint + apiPath)
    const apiHeaders: Record<string, string> = {
      'X-Appwrite-Project': this.client.config.project,
      'content-type': 'application/json',
      accept: 'application/json',
    }
    return this.client.call('delete', uri, apiHeaders, payload)
  }

  /**
   * List agent memories for a team.
   *
   * @param {string} params.teamId - Team unique ID. Omit to let the server
   *   resolve the team from the console organization context.
   * @param {string[]} params.queries - Queries generated by SDK Query class.
   * @throws {AppwriteException}
   * @returns {Promise<AgentMemoryList>}
   */
  listMemories(params: {
    teamId?: string
    queries?: string[]
  }): Promise<AgentMemoryList> {
    const teamId = params.teamId
    const queries = params.queries
    const apiPath = '/agent/memories'
    const payload: Record<string, unknown> = {}
    if (typeof teamId !== 'undefined') {
      payload['teamId'] = teamId
    }
    if (typeof queries !== 'undefined') {
      payload['queries'] = queries
    }
    const uri = new URL(this.client.config.endpoint + apiPath)
    const apiHeaders: Record<string, string> = {
      'X-Appwrite-Project': this.client.config.project,
      accept: 'application/json',
    }
    return this.client.call('get', uri, apiHeaders, payload)
  }

  /**
   * Create an agent memory for a team. If a memory with the same scope, owner, and key already exists, it is updated in place.
   *
   * @param {string} params.teamId - Team unique ID. Omit to let the server
   *   resolve the team from the console organization context.
   * @param {string} params.memoryId - Memory ID. Choose a custom ID or pass unique().
   * @param {string} params.scope - Ownership scope.
   * @param {string} params.key - Stable memory key within the scope (e.g. style.concise).
   * @param {string} params.content - Memory content.
   * @param {string} params.category - Memory category.
   * @param {number} params.priority - Injection priority. Higher values are kept first under the token budget.
   * @param {string} params.status - Memory status.
   * @param {string} params.source - Who wrote the memory.
   * @param {string} params.expiresAt - Optional expiry time. Omit or null for permanent.
   * @throws {AppwriteException}
   * @returns {Promise<AgentMemory>}
   */
  createMemory(params: {
    teamId?: string
    memoryId: string
    scope: string
    key: string
    content: string
    category?: string
    priority?: number
    status?: string
    source?: string
    expiresAt?: string
  }): Promise<AgentMemory> {
    const teamId = params.teamId
    const memoryId = params.memoryId
    const scope = params.scope
    const key = params.key
    const content = params.content
    const category = params.category
    const priority = params.priority
    const status = params.status
    const source = params.source
    const expiresAt = params.expiresAt
    if (typeof memoryId === 'undefined') {
      throw new AppwriteException('Missing required parameter: "memoryId"')
    }
    if (typeof scope === 'undefined') {
      throw new AppwriteException('Missing required parameter: "scope"')
    }
    if (typeof key === 'undefined') {
      throw new AppwriteException('Missing required parameter: "key"')
    }
    if (typeof content === 'undefined') {
      throw new AppwriteException('Missing required parameter: "content"')
    }
    const apiPath = '/agent/memories'
    const payload: Record<string, unknown> = {}
    if (typeof teamId !== 'undefined') {
      payload['teamId'] = teamId
    }
    if (typeof memoryId !== 'undefined') {
      payload['memoryId'] = memoryId
    }
    if (typeof scope !== 'undefined') {
      payload['scope'] = scope
    }
    if (typeof key !== 'undefined') {
      payload['key'] = key
    }
    if (typeof content !== 'undefined') {
      payload['content'] = content
    }
    if (typeof category !== 'undefined') {
      payload['category'] = category
    }
    if (typeof priority !== 'undefined') {
      payload['priority'] = priority
    }
    if (typeof status !== 'undefined') {
      payload['status'] = status
    }
    if (typeof source !== 'undefined') {
      payload['source'] = source
    }
    if (typeof expiresAt !== 'undefined') {
      payload['expiresAt'] = expiresAt
    }
    const uri = new URL(this.client.config.endpoint + apiPath)
    const apiHeaders: Record<string, string> = {
      'X-Appwrite-Project': this.client.config.project,
      'content-type': 'application/json',
      accept: 'application/json',
    }
    return this.client.call('post', uri, apiHeaders, payload)
  }

  /**
   * Get an agent memory by ID.
   *
   * @param {string} params.memoryId - Memory unique ID.
   * @throws {AppwriteException}
   * @returns {Promise<AgentMemory>}
   */
  getMemory(params: { memoryId: string }): Promise<AgentMemory> {
    const memoryId = params.memoryId
    if (typeof memoryId === 'undefined') {
      throw new AppwriteException('Missing required parameter: "memoryId"')
    }
    const apiPath = '/agent/memories/{memoryId}'.replace(
      '{memoryId}',
      encodeURIComponent(String(memoryId)),
    )
    const payload: Record<string, unknown> = {}
    const uri = new URL(this.client.config.endpoint + apiPath)
    const apiHeaders: Record<string, string> = {
      'X-Appwrite-Project': this.client.config.project,
      accept: 'application/json',
    }
    return this.client.call('get', uri, apiHeaders, payload)
  }

  /**
   * Update an agent memory. Scope, owner, and key are immutable; create a new memory to change them.
   *
   * @param {string} params.memoryId - Memory unique ID.
   * @param {string} params.content - Memory content.
   * @param {string} params.category - Memory category.
   * @param {number} params.priority - Injection priority. Higher values are kept first under the token budget.
   * @param {string} params.status - Memory status.
   * @param {string} params.source - Who wrote the memory.
   * @param {string} params.expiresAt - Optional expiry time as ISO 8601. Pass an empty string to clear.
   * @throws {AppwriteException}
   * @returns {Promise<AgentMemory>}
   */
  updateMemory(params: {
    memoryId: string
    content?: string
    category?: string
    priority?: number
    status?: string
    source?: string
    expiresAt?: string
  }): Promise<AgentMemory> {
    const memoryId = params.memoryId
    const content = params.content
    const category = params.category
    const priority = params.priority
    const status = params.status
    const source = params.source
    const expiresAt = params.expiresAt
    if (typeof memoryId === 'undefined') {
      throw new AppwriteException('Missing required parameter: "memoryId"')
    }
    const apiPath = '/agent/memories/{memoryId}'.replace(
      '{memoryId}',
      encodeURIComponent(String(memoryId)),
    )
    const payload: Record<string, unknown> = {}
    if (typeof content !== 'undefined') {
      payload['content'] = content
    }
    if (typeof category !== 'undefined') {
      payload['category'] = category
    }
    if (typeof priority !== 'undefined') {
      payload['priority'] = priority
    }
    if (typeof status !== 'undefined') {
      payload['status'] = status
    }
    if (typeof source !== 'undefined') {
      payload['source'] = source
    }
    if (typeof expiresAt !== 'undefined') {
      payload['expiresAt'] = expiresAt
    }
    const uri = new URL(this.client.config.endpoint + apiPath)
    const apiHeaders: Record<string, string> = {
      'X-Appwrite-Project': this.client.config.project,
      'content-type': 'application/json',
      accept: 'application/json',
    }
    return this.client.call('patch', uri, apiHeaders, payload)
  }

  /**
   * Delete an agent memory.
   *
   * @param {string} params.memoryId - Memory unique ID.
   * @throws {AppwriteException}
   * @returns {Promise<{}>}
   */
  deleteMemory(params: { memoryId: string }): Promise<unknown> {
    const memoryId = params.memoryId
    if (typeof memoryId === 'undefined') {
      throw new AppwriteException('Missing required parameter: "memoryId"')
    }
    const apiPath = '/agent/memories/{memoryId}'.replace(
      '{memoryId}',
      encodeURIComponent(String(memoryId)),
    )
    const payload: Record<string, unknown> = {}
    const uri = new URL(this.client.config.endpoint + apiPath)
    const apiHeaders: Record<string, string> = {
      'X-Appwrite-Project': this.client.config.project,
      'content-type': 'application/json',
      accept: 'application/json',
    }
    return this.client.call('delete', uri, apiHeaders, payload)
  }

  /**
   * List agent models for a team.
   *
   * @param {string} params.teamId - Team unique ID. Omit to let the server
   *   resolve the team from the console organization context.
   * @param {string[]} params.queries - Queries generated by SDK Query class.
   * @throws {AppwriteException}
   * @returns {Promise<AgentModelList>}
   */
  listModels(params: {
    teamId?: string
    queries?: string[]
  }): Promise<AgentModelList> {
    const teamId = params.teamId
    const queries = params.queries
    const apiPath = '/agent/models'
    const payload: Record<string, unknown> = {}
    if (typeof teamId !== 'undefined') {
      payload['teamId'] = teamId
    }
    if (typeof queries !== 'undefined') {
      payload['queries'] = queries
    }
    const uri = new URL(this.client.config.endpoint + apiPath)
    const apiHeaders: Record<string, string> = {
      'X-Appwrite-Project': this.client.config.project,
      accept: 'application/json',
    }
    return this.client.call('get', uri, apiHeaders, payload)
  }

  /**
   * Create a custom LLM model credential for a team.
   *
   * @param {string} params.teamId - Team unique ID. Omit to let the server
   *   resolve the team from the console organization context.
   * @param {string} params.modelId - Model ID. Must match ^[a-z][a-z0-9_-]{1,63}$ when not using unique().
   * @param {string} params.name - Display name.
   * @param {string} params.provider - LLM provider identifier (e.g. openai).
   * @param {string} params.model - Provider model identifier (e.g. gpt-4o).
   * @param {string} params.apiKey - Provider API key.
   * @param {string} params.baseUrl - Optional custom base URL for the provider API.
   * @param {boolean} params.enabled - Whether this model can be selected on conversations.
   * @param {string} params.status - Optional status label.
   * @throws {AppwriteException}
   * @returns {Promise<AgentModel>}
   */
  createModel(params: {
    teamId?: string
    modelId: string
    name: string
    provider: string
    model: string
    apiKey: string
    baseUrl?: string
    enabled?: boolean
    status?: string
  }): Promise<AgentModel> {
    const teamId = params.teamId
    const modelId = params.modelId
    const name = params.name
    const provider = params.provider
    const model = params.model
    const apiKey = params.apiKey
    const baseUrl = params.baseUrl
    const enabled = params.enabled
    const status = params.status
    if (typeof modelId === 'undefined') {
      throw new AppwriteException('Missing required parameter: "modelId"')
    }
    if (typeof name === 'undefined') {
      throw new AppwriteException('Missing required parameter: "name"')
    }
    if (typeof provider === 'undefined') {
      throw new AppwriteException('Missing required parameter: "provider"')
    }
    if (typeof model === 'undefined') {
      throw new AppwriteException('Missing required parameter: "model"')
    }
    if (typeof apiKey === 'undefined') {
      throw new AppwriteException('Missing required parameter: "apiKey"')
    }
    const apiPath = '/agent/models'
    const payload: Record<string, unknown> = {}
    if (typeof teamId !== 'undefined') {
      payload['teamId'] = teamId
    }
    if (typeof modelId !== 'undefined') {
      payload['modelId'] = modelId
    }
    if (typeof name !== 'undefined') {
      payload['name'] = name
    }
    if (typeof provider !== 'undefined') {
      payload['provider'] = provider
    }
    if (typeof model !== 'undefined') {
      payload['model'] = model
    }
    if (typeof apiKey !== 'undefined') {
      payload['apiKey'] = apiKey
    }
    if (typeof baseUrl !== 'undefined') {
      payload['baseUrl'] = baseUrl
    }
    if (typeof enabled !== 'undefined') {
      payload['enabled'] = enabled
    }
    if (typeof status !== 'undefined') {
      payload['status'] = status
    }
    const uri = new URL(this.client.config.endpoint + apiPath)
    const apiHeaders: Record<string, string> = {
      'X-Appwrite-Project': this.client.config.project,
      'content-type': 'application/json',
      accept: 'application/json',
    }
    return this.client.call('post', uri, apiHeaders, payload)
  }

  /**
   * Get an agent model by ID.
   *
   * @param {string} params.modelId - Model unique ID.
   * @throws {AppwriteException}
   * @returns {Promise<AgentModel>}
   */
  getModel(params: { modelId: string }): Promise<AgentModel> {
    const modelId = params.modelId
    if (typeof modelId === 'undefined') {
      throw new AppwriteException('Missing required parameter: "modelId"')
    }
    const apiPath = '/agent/models/{modelId}'.replace(
      '{modelId}',
      encodeURIComponent(String(modelId)),
    )
    const payload: Record<string, unknown> = {}
    const uri = new URL(this.client.config.endpoint + apiPath)
    const apiHeaders: Record<string, string> = {
      'X-Appwrite-Project': this.client.config.project,
      accept: 'application/json',
    }
    return this.client.call('get', uri, apiHeaders, payload)
  }

  /**
   * Update an agent model. Omit apiKey to leave the stored key unchanged; the key cannot be cleared, only replaced.
   *
   * @param {string} params.modelId - Model unique ID.
   * @param {string} params.name - Display name.
   * @param {string} params.provider - LLM provider identifier (e.g. openai).
   * @param {string} params.model - Provider model identifier (e.g. gpt-4o).
   * @param {string} params.apiKey - Provider API key. Omit to keep the existing key.
   * @param {string} params.baseUrl - Optional custom base URL for the provider API.
   * @param {boolean} params.enabled - Whether this model can be selected on conversations.
   * @param {string} params.status - Optional status label.
   * @throws {AppwriteException}
   * @returns {Promise<AgentModel>}
   */
  updateModel(params: {
    modelId: string
    name?: string
    provider?: string
    model?: string
    apiKey?: string
    baseUrl?: string
    enabled?: boolean
    status?: string
  }): Promise<AgentModel> {
    const modelId = params.modelId
    const name = params.name
    const provider = params.provider
    const model = params.model
    const apiKey = params.apiKey
    const baseUrl = params.baseUrl
    const enabled = params.enabled
    const status = params.status
    if (typeof modelId === 'undefined') {
      throw new AppwriteException('Missing required parameter: "modelId"')
    }
    const apiPath = '/agent/models/{modelId}'.replace(
      '{modelId}',
      encodeURIComponent(String(modelId)),
    )
    const payload: Record<string, unknown> = {}
    if (typeof name !== 'undefined') {
      payload['name'] = name
    }
    if (typeof provider !== 'undefined') {
      payload['provider'] = provider
    }
    if (typeof model !== 'undefined') {
      payload['model'] = model
    }
    if (typeof apiKey !== 'undefined') {
      payload['apiKey'] = apiKey
    }
    if (typeof baseUrl !== 'undefined') {
      payload['baseUrl'] = baseUrl
    }
    if (typeof enabled !== 'undefined') {
      payload['enabled'] = enabled
    }
    if (typeof status !== 'undefined') {
      payload['status'] = status
    }
    const uri = new URL(this.client.config.endpoint + apiPath)
    const apiHeaders: Record<string, string> = {
      'X-Appwrite-Project': this.client.config.project,
      'content-type': 'application/json',
      accept: 'application/json',
    }
    return this.client.call('patch', uri, apiHeaders, payload)
  }

  /**
   * Delete an agent model.
   *
   * @param {string} params.modelId - Model unique ID.
   * @throws {AppwriteException}
   * @returns {Promise<{}>}
   */
  deleteModel(params: { modelId: string }): Promise<unknown> {
    const modelId = params.modelId
    if (typeof modelId === 'undefined') {
      throw new AppwriteException('Missing required parameter: "modelId"')
    }
    const apiPath = '/agent/models/{modelId}'.replace(
      '{modelId}',
      encodeURIComponent(String(modelId)),
    )
    const payload: Record<string, unknown> = {}
    const uri = new URL(this.client.config.endpoint + apiPath)
    const apiHeaders: Record<string, string> = {
      'X-Appwrite-Project': this.client.config.project,
      'content-type': 'application/json',
      accept: 'application/json',
    }
    return this.client.call('delete', uri, apiHeaders, payload)
  }
}
