<?php
$home = $this->getParam('home', '');
$fileLimit = $this->getParam('fileLimit', 0);
$fileLimitHuman = $this->getParam('fileLimitHuman', 0);

$locale = $this->getParam("locale");
/** @var Utopia\Locale\Locale $locale */
?>
<div class="cover">
    <h1 class="zone xl margin-bottom-large">
        <a data-ls-attrs="href=/console/home?project={{router.params.project}}" class="back text-size-small link-return-animation--start"><i class="icon-left-open"></i> <?php echo $locale->getText('console.shared-button-back-to-home'); ?></a>
        <br />

        <span><?php echo $locale->getText('console.storage.index.title'); ?></span>
    </h1>
</div>

<div class="zone xl">
    <ul class="phases clear" data-ui-phases data-selected="{{router.params.tab}}">
        <li data-state="/console/database?project={{router.params.project}}">
            <h2 class="margin-bottom"><?php echo $locale->getText('console.storage.index.files-title'); ?></h2>

            <form class="box padding-small margin-bottom search"
                data-service="storage.listFiles"
                data-event="submit"
                data-param-search="{{router.params.search}}"
                data-param-limit="<?php echo APP_PAGING_LIMIT; ?>"
                data-param-offset=""
                data-param-order-type="DESC"
                data-scope="sdk"
                data-name="project-files"
                data-success="state"
                data-success-param-state-keys="search,offset">
                <div class="row thin responsive">
                    <div class="col span-10">
                        <input name="search" id="searchFiles" type="search" autocomplete="off" placeholder="<?php echo $locale->getText('console.storage.index.files-search-placeholder'); ?>" class="margin-bottom-no" data-ls-bind="{{router.params.search}}">
                    </div>
                    <div class="col span-2 desktops-only">
                        <button class="fill" title="Search" aria-label="<?php echo $locale->getText('console.storage.index.files-search-label'); ?>"><i class="icon-search"></i></button>
                    </div>
                </div>
            </form>

            <div
                data-service="storage.listFiles"
                data-event="load,storage.createFile,storage.updateFile,storage.deleteFile"
                data-param-search="{{router.params.search}}"
                data-param-limit="<?php echo APP_PAGING_LIMIT; ?>"
                data-param-offset="{{router.params.offset}}"
                data-param-order-type="DESC"
                data-scope="sdk"
                data-name="project-files">

                <div data-ls-if="0 == {{project-files.sum}}" class="box margin-bottom">
                    <h3 class="margin-bottom-small text-bold"><?php echo $locale->getText('console.storage.index.no-files-title'); ?></h3>

                    <p class="margin-bottom-no"><?php echo $locale->getText('console.storage.index.no-files-description'); ?></p>
                </div>

                <div data-ls-if="0 != {{project-files.sum}}">
                    <div class="margin-bottom-small margin-end-small text-align-end text-size-small"><span data-ls-bind="{{project-files.sum}}"></span> <?php echo $locale->getText('console.storage.index.files-sum'); ?></div>

                    <div class="box margin-bottom">
                        <table class="vertical">
                            <thead>
                                <tr>
                                    <th width="40"></th>
                                    <th><?php echo $locale->getText('console.storage.index.table-column-filename'); ?></th>
                                    <th width="140"><?php echo $locale->getText('console.storage.index.table-column-type'); ?></th>
                                    <th width="100"><?php echo $locale->getText('console.storage.index.table-column-size'); ?></th>
                                    <th width="120"><?php echo $locale->getText('console.storage.index.table-column-created-at'); ?></th>
                                </tr>
                            </thead>
                            <tbody data-ls-loop="project-files.files" data-ls-as="file">
                                <tr>
                                    <td class="hide">
                                        <img src="" data-ls-attrs="src={{env.ENDPOINT}}/v1/storage/files/{{file.$id}}/preview?width=65&height=65&project={{router.params.project}}&mode=admin" class="pull-start avatar" width="30" height="30" loading="lazy" />
                                    </td>
                                    <td data-title="<?php echo $locale->getText('console.storage.index.table-column-filename'); ?>: " class="text-one-liner" data-ls-attrs="title={{file.name}}" >
                                        <div data-ui-modal class="box modal sticky-footer width-large close" data-button-text="{{file.name}}" data-button-class="link" data-button-element="span">
                                            <button type="button" class="close pull-end" data-ui-modal-close=""><i class="icon-cancel"></i></button>

                                            <h1><?php echo $locale->getText('console.storage.index.update-title'); ?></h1>

                                            <hr />

                                            <div class="row responsive modalize">
                                                <div class="col span-8">
                                                    <form class="strip"
                                                        data-analytics
                                                        data-analytics-activity
                                                        data-analytics-event="submit"
                                                        data-analytics-category="console"
                                                        data-analytics-label="Update Storage File"
                                                        data-service="storage.updateFile"
                                                        data-event="file-update-{{file.$id}}"
                                                        data-scope="sdk"
                                                        data-success="alert,trigger"
                                                        data-success-param-alert-text="<?php echo $locale->getText('console.storage.index.update-submit-success'); ?>"
                                                        data-success-param-trigger-events="storage.updateFile"
                                                        data-failure="alert"
                                                        data-failure-param-alert-text="<?php echo $locale->getText('console.storage.index.update-submit-error'); ?>"
                                                        data-failure-param-alert-classname="error">

                                                        <label for="files-fileId"><?php echo $locale->getText('console.storage.index.update-field-id'); ?></label>
                                                        <div class="input-copy">
                                                            <input data-forms-copy type="text" data-ls-attrs="id=file-id-{{file.$id}}" name="fileId" disabled data-ls-bind="{{file.$id}}" />
                                                        </div>
                                                        <input type="hidden" data-ls-attrs="id=file-folderId-{{file.$id}}" name="folderId" data-cast-to="integer" value="1">

                                                        <label for="file-read"><?php echo $locale->getText('shared.read-access'); ?> (<a data-ls-attrs="href={{env.HOME}}/docs/permissions" target="_blank" rel="noopener"><?php echo $locale->getText('shared.learn-more'); ?></a>)</label>
                                                        <input type="hidden" data-ls-attrs="id=file-read-{{file.$id}}" name="read" data-forms-tags data-cast-to="json" data-ls-bind="{{file.$permissions.read}}" placeholder="<?php echo $locale->getText('shared.access-placeholder'); ?>" />
                                                        <div class="text-fade text-size-xs margin-top-negative-small margin-bottom"><?php echo $locale->getText('shared.permission-info'); ?></div>
                                                        
                                                        <label for="file-write"><?php echo $locale->getText('shared.write-access'); ?> (<a data-ls-attrs="href={{env.HOME}}/docs/permissions" target="_blank" rel="noopener"><?php echo $locale->getText('shared.learn-more'); ?></a>)</label>
                                                        <input type="hidden" data-ls-attrs="id=file-write-{{file.$id}}" name="write" data-forms-tags data-cast-to="json" data-ls-bind="{{file.$permissions.write}}" placeholder="<?php echo $locale->getText('shared.access-placeholder'); ?>" />
                                                        <div class="text-fade text-size-xs margin-top-negative-small margin-bottom"><?php echo $locale->getText('shared.permission-info'); ?></div>
                                                    </form>

                                                    <form class="strip"
                                                        data-analytics
                                                        data-analytics-activity
                                                        data-analytics-event="submit"
                                                        data-analytics-category="console"
                                                        data-analytics-label="Delete File"
                                                        data-service="storage.deleteFile"
                                                        data-scope="sdk"
                                                        data-event="file-delete-{{file.$id}}"
                                                        data-confirm="<?php echo $locale->getText('console.storage.index.delete-submit-confirm'); ?>"
                                                        data-success="alert,trigger"
                                                        data-success-param-alert-text="<?php echo $locale->getText('console.storage.index.delete-submit-success'); ?>"
                                                        data-success-param-trigger-events="storage.deleteFile"
                                                        data-failure="alert"
                                                        data-failure-param-alert-text="<?php echo $locale->getText('console.storage.index.delete-submit-error'); ?>"
                                                        data-failure-param-alert-classname="error">

                                                        <input type="hidden" name="fileId" data-ls-bind="{{file.$id}}" />
                                                    </form>
                                                </div>
                                                <div class="col span-4 text-size-small">
                                                    <div class="margin-bottom-small"><?php echo $locale->getText('console.storage.index.update-preview'); ?></div>
                                                    
                                                    <div class="margin-bottom-small">
                                                        <img src="" class="file-preview" data-ls-attrs="src={{env.ENDPOINT}}/v1/storage/files/{{file.$id}}/preview?width=350&height=250&project={{router.params.project}}&mode=admin" loading="lazy" width="225" height="160" />
                                                    </div>

                                                    <div class="margin-bottom-tiny">
                                                        <a href="" data-ls-attrs="href={{env.ENDPOINT}}/v1/storage/files/{{file.$id}}/view?project={{router.params.project}}&mode=admin" target="_blank" rel="noopener"><i class="icon-angle-circled-right margin-start-negative-tiny margin-end-tiny"></i> <?php echo $locale->getText('console.storage.index.update-preview-new-window'); ?> <i class="icon-link-ext"></i></a>
                                                    </div>

                                                    <div class="margin-bottom-small">
                                                        <a href="" data-ls-attrs="href={{env.ENDPOINT}}/v1/storage/files/{{file.$id}}/download?project={{router.params.project}}&mode=admin" target="_blank" rel="noopener"><i class="icon-angle-circled-right margin-start-negative-tiny margin-end-tiny"></i> <?php echo $locale->getText('console.storage.index.update-preview-download'); ?> <i class="icon-link-ext"></i></a>
                                                    </div>

                                                    <div class="margin-bottom-tiny">
                                                        <i class="icon-angle-circled-right margin-start-negative-tiny margin-end-tiny"></i> <?php echo $locale->getText('console.storage.index.table-column-type'); ?>: <span data-ls-bind="{{file.mimeType}}"></span>
                                                    </div>
                                                    <div class="margin-bottom-tiny">
                                                        <i class="icon-angle-circled-right margin-start-negative-tiny margin-end-tiny"></i> <?php echo $locale->getText('console.storage.index.table-column-size'); ?>: <span data-ls-bind="{{file.sizeOriginal|humanFileSize}}"></span>
                                                        <span data-ls-bind="{{file.sizeOriginal|humanFileUnit}}"></span>
                                                    </div>
                                                    <div class="margin-bottom">
                                                        <i class="icon-angle-circled-right margin-start-negative-tiny margin-end-tiny"></i> <?php echo $locale->getText('console.storage.index.table-column-created-at'); ?>: <span data-ls-bind="{{file.dateCreated|dateText}}"></span>
                                                    </div>
                                                </div>
                                            </div>

                                            <footer>
                                                <button class="link pull-end text-danger" data-ls-ui-trigger="file-delete-{{file.$id}},modal-close"><?php echo $locale->getText('console.storage.index.delete-button-submit'); ?></button>
                                                <button type="button" data-ls-ui-trigger="file-update-{{file.$id}},modal-close"><?php echo $locale->getText('console.storage.index.update-button-submit'); ?></button> &nbsp; <button data-ui-modal-close="" type="button" class="reverse desktops-only-inline tablets-only-inline"><?php echo $locale->getText('console.storage.index.update-button-cancel'); ?></button>
                                            </footer>
                                        </div>
                                    </td>
                                    <td data-title="<?php echo $locale->getText('console.storage.index.table-column-type'); ?>: ">
                                        <span class="text-fade text-size-small" data-ls-bind="{{file.mimeType}}"></span>
                                    </td>
                                    <td data-title="<?php echo $locale->getText('console.storage.index.table-column-size'); ?>: ">
                                        <span class="text-fade text-size-small" data-ls-bind="{{file.sizeOriginal|humanFileSize}}"></span>
                                        <span class="text-fade text-size-small" data-ls-bind="{{file.sizeOriginal|humanFileUnit}}"></span>
                                    </td>
                                    <td data-title="<?php echo $locale->getText('console.storage.index.table-column-created-at'); ?>: ">
                                        <span class="text-fade text-size-small" data-ls-bind="{{file.dateCreated|dateText}}"></span>
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>

                <div class="pull-end text-align-center paging">
                    <form
                        data-service="storage.listFiles"
                        data-event="submit"
                        data-param-search="{{router.params.search}}"
                        data-param-limit="<?php echo APP_PAGING_LIMIT; ?>"
                        data-param-order-type="DESC"
                        data-scope="sdk"
                        data-name="project-files"
                        data-success="state"
                        data-success-param-state-keys="search,offset">
                        <button name="offset" data-paging-back data-offset="{{router.params.offset}}" data-sum="{{project-files.sum}}" class="margin-end round small" aria-label="<?php echo $locale->getText('shared.pagination-back'); ?>"><i class="icon-left-open"></i></button>
                    </form>

                    <span data-ls-bind="{{router.params.offset|pageCurrent}} / {{project-files.sum|pageTotal}}"></span>

                    <form
                        data-service="storage.listFiles"
                        data-event="submit"
                        data-param-search="{{router.params.search}}"
                        data-param-limit="<?php echo APP_PAGING_LIMIT; ?>"
                        data-param-order-type="DESC"
                        data-scope="sdk"
                        data-name="project-files"
                        data-success="state"
                        data-success-param-state-keys="search,offset">
                        <button name="offset" data-paging-next data-offset="{{router.params.offset}}" data-sum="{{project-files.sum}}" class="margin-start round small" aria-label="<?php echo $locale->getText('shared.pagination-next'); ?>"><i class="icon-right-open"></i></button>
                    </form>
                </div>

                <div data-ui-modal class="box modal sticky-footer close" data-button-text="<?php echo $locale->getText('console.storage.index.create-button-modal'); ?>">
                    <button type="button" class="close pull-end" data-ui-modal-close=""><i class="icon-cancel"></i></button>

                    <h1><?php echo $locale->getText('console.storage.index.create-title'); ?></h1>

                    <form
                        data-analytics
                        data-analytics-activity
                        data-analytics-event="submit"
                        data-analytics-category="console"
                        data-analytics-label="Create Storage File"
                        data-service="storage.createFile"
                        data-event="submit"
                        data-scope="sdk"
                        data-loading="<?php echo $locale->getText('console.storage.index.create-submit-loading'); ?>"
                        data-success="alert,trigger,reset"
                        data-success-param-alert-text="<?php echo $locale->getText('console.storage.index.create-submit-success'); ?>"
                        data-success-param-trigger-events="storage.createFile"
                        data-failure="alert"
                        data-failure-param-alert-text="<?php echo $locale->getText('console.storage.index.create-submit-error'); ?>"
                        data-failure-param-alert-classname="error">
                        <input type="hidden" name="folderId" id="files-folderId" data-cast-to="integer" value="1">

                        <label for="file-read">File</label>
                        <input type="file" name="file" id="file-file" size="1" required>

                        <div class="text-fade text-size-xs margin-top-negative-small margin-bottom">(Max file size allowed: <?php echo $fileLimitHuman; ?>)</div>

                        <label for="file-read"><?php echo $locale->getText('shared.read-access'); ?> (<a data-ls-attrs="href={{env.HOME}}/docs/permissions" target="_blank" rel="noopener"><?php echo $locale->getText('shared.learn-more'); ?></a>)</label>
                        <input type="hidden" id="file-read" name="read" data-forms-tags data-cast-to="json" value="<?php echo htmlentities(json_encode(['*'])); ?>" placeholder="<?php echo $locale->getText('shared.access-placeholder'); ?>" />
                        <div class="text-fade text-size-xs margin-top-negative-small margin-bottom"><?php echo $locale->getText('shared.permission-info'); ?></div>
                        
                        <label for="file-write"><?php echo $locale->getText('shared.write-access'); ?> (<a data-ls-attrs="href={{env.HOME}}/docs/permissions" target="_blank" rel="noopener"><?php echo $locale->getText('shared.learn-more'); ?></a>)</label>
                        <input type="hidden" id="file-write" name="write" data-forms-tags data-cast-to="json" value="" placeholder="<?php echo $locale->getText('shared.access-placeholder'); ?>" />
                        <div class="text-fade text-size-xs margin-top-negative-small margin-bottom"><?php echo $locale->getText('shared.permission-info'); ?></div>

                        <footer>
                            <button type="submit"><?php echo $locale->getText('console.storage.index.create-button-submit'); ?></button> &nbsp; <button data-ui-modal-close="" type="button" class="reverse"><?php echo $locale->getText('console.storage.index.create-button-cancel'); ?></button>
                        </footer>
                    </form>
                </div>
            </div>
        </li>
    </ul>
</div>
