/** Shown before the user searches; full library is available via search. */
export const COVER_LUCIDE_POPULAR_ICONS = [
  'activity',
  'app-window',
  'archive',
  'arrow-right',
  'bell',
  'blocks',
  'book-open',
  'box',
  'calendar',
  'chart-bar',
  'check',
  'cloud',
  'code',
  'cog',
  'database',
  'file',
  'folder',
  'globe',
  'heart',
  'image',
  'key',
  'layers',
  'link',
  'lock',
  'mail',
  'message-square',
  'package',
  'palette',
  'rocket',
  'search',
  'server',
  'settings',
  'shield',
  'sparkles',
  'star',
  'terminal',
  'upload',
  'user',
  'users',
  'zap',
] as const

export const COVER_LUCIDE_ICON_PREFIX = 'lucide:'
