tasks:
  - name: Run Appwrite Docker Stack
    init: |
      docker compose pull
      docker compose build
      docker pull composer
    command: |
      docker run --rm --interactive --tty \
      --volume $PWD:/app \
      composer update \
      --ignore-platform-reqs \
      --optimize-autoloader \
      --no-plugins \
      --no-scripts \
      --prefer-dist

ports:
  - port: 8080
    onOpen: open-preview
    visibility: public

vscode:
  extensions:
    - ms-azuretools.vscode-docker
    - zobo.php-intellisense

github:
  # https://www.gitpod.io/docs/prebuilds#github-specific-configuration
  prebuilds:
    # enable for pull requests coming from forks (defaults to false)
    pullRequestsFromForks: true
    # add a check to pull requests (defaults to true)
    addCheck: false
