services:
    traefik:
        ports:
            - 9500:8080
    appwrite:
        ports:
            - 9501:80
    appwrite-realtime:
        ports:
            - 9505:80
    mariadb:
        ports:
            - 3306:3306
    redis:
        ports:
            - 6379:6379
    # Dev Tools Start ------------------------------------------------------------------------------------------
    #
    # The Appwrite Team uses the following tools to help debug, monitor and diagnose the Appwrite stack
    #
    # Here is a description of the different tools and why are we using them:
    #
    # MailCatcher - An SMTP server. Catches all system emails and displays them in a nice UI.
    # RequestCatcher - An HTTP server. Catches all system https calls and displays them using a simple HTTP API. Used to debug & tests webhooks and HTTP tasks
    # Redis Insight - A nice UI for exploring Redis data
    # Adminer - A nice UI for exploring MariaDB data
    # GraphQl Explorer - A nice UI for exploring GraphQL API
    maildev: # used mainly for dev tests
        image: appwrite/mailcatcher:1.0.0
        container_name: appwrite-mailcatcher
        ports:
            - "9503:1080"
        networks:
            - appwrite

    request-catcher: # used mainly for dev tests
        image: appwrite/requestcatcher:1.0.0
        container_name: appwrite-requestcatcher
        ports:
            - "9504:5000"
        networks:
            - appwrite

    adminer:
        image: adminer
        container_name: appwrite-adminer
        restart: always
        ports:
            - 9506:8080
        networks:
            - appwrite

    redis-insight:
        image: redis/redisinsight:latest
        restart: unless-stopped
        networks:
            - appwrite
        environment:
            - REDIS_HOSTS=redis
        ports:
            - "8081:5540"

    graphql-explorer:
        container_name: appwrite-graphql-explorer
        image: appwrite/altair:0.3.0
        restart: unless-stopped
        networks:
            - appwrite
        ports:
            - "9509:3000"
        environment:
            - SERVER_URL=http://localhost/v1/graphql
