name: "Tests"

on: [pull_request]
jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup PHP 8.3
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3'
        extensions: yaml

    - name: Validate composer.json and composer.lock
      run: composer validate --strict
    
    - name: Compose install
      run: composer install --ignore-platform-reqs

    - name: Run tests
      run: |
        composer test