[package]
name = "utopia-auth"
description = "Password hashes, proofs and session stores compatible with utopia-php/auth."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
aes.workspace = true
argon2.workspace = true
base64.workspace = true
bcrypt.workspace = true
ctr.workspace = true
getrandom.workspace = true
hex.workspace = true
md-5.workspace = true
scrypt.workspace = true
serde_json.workspace = true
sha1.workspace = true
sha2.workspace = true
sha3.workspace = true
