<?php
$provider = $this->getParam('provider', 'oidc');
?>
<label for="oauth2<?php echo $this->escape(ucfirst($provider)); ?>Appid">App ID</label>
<input name="appId" id="oauth2<?php echo $this->escape(ucfirst($provider)); ?>Appid" type="text" autocomplete="off" data-ls-bind="{{console-project.provider<?php echo $this->escape(ucfirst($provider)); ?>Appid}}">

<label for="oauth2<?php echo $this->escape(ucfirst($provider)); ?>AppSecret">App Secret</label>
<input name="appSecret" data-forms-show-secret id="oauth2<?php echo $this->escape(ucfirst($provider)); ?>AppSecret" type="password" autocomplete="off" data-ls-bind="{{console-project.provider<?php echo $this->escape(ucfirst($provider)); ?>Secret}}">

<label for="oauth2<?php echo $this->escape(ucfirst($provider)); ?>Discovery">OpenID Connect Discovery<span class="tooltip" data-tooltip="Well-known URL of the OpenID server"><i class="icon-info-circled"></i></span></label>
<input name="appSecret" id="oauth2<?php echo $this->escape(ucfirst($provider)); ?>Discovery" type="text" autocomplete="off" placeholder="https://your-server.com/.well-known/openid-configuration">

  <?php /*Hidden input for the final secret. Gets filled with a JSON via JS. */ ?>
<input name="secret" data-forms-oauth-custom="<?php echo $this->escape(ucfirst($provider)); ?>" id="oauth2<?php echo $this->escape(ucfirst($provider)); ?>Secret" type="hidden" autocomplete="off" data-ls-bind="{{console-project.provider<?php echo $this->escape(ucfirst($provider)); ?>Secret}}" />