<?php

$logs = $this->getParam('logs', null);
$permissions = $this->getParam('permissions', null);

?>
<div
    data-service="databases.getCollection"
    data-param-database-id="{{router.params.databaseId}}"
    data-param-collection-id="{{router.params.id}}"
    data-scope="sdk"
    data-event="load,databases.updateCollection,databases.createAttribute,databases.deleteAttribute,databases.createIndex,databases.deleteIndex"
    data-name="project-collection">

    <div
        data-service="databases.get"
        data-param-database-id="{{router.params.databaseId}}"
        data-scope="sdk"
        data-event="load,databases.update"
        data-name="project-database">
        <div class="cover">
            <h1 class="zone xl margin-bottom-large">
                <a data-ls-attrs="href=/console/databases/database?id={{router.params.databaseId}}&project={{router.params.project}}" class="back text-size-small link-return-animation--start"><i class="icon-left-open"></i> <span data-ls-bind="{{project-database.name}}">&nbsp;&nbsp;</span></a>

                <br />

                <span data-ls-bind="{{project-collection.name}}">&nbsp;&nbsp;</span>
            </h1>
        </div>
    </div>

    <div data-ui-modal class="modal width-large box close" data-button-hide="on" data-open-event="open-json">
        <button type="button" class="close pull-end" data-ui-modal-close=""><i class="icon-cancel"></i></button>

        <h2>JSON View</h2>

        <div class="margin-bottom">
            <input type="hidden" data-ls-bind="{{project-collection}}" data-forms-code />
        </div>

        <button data-ui-modal-close="" type="button" class="reverse">Cancel</button>
    </div>

    <div class="zone xl">
        <ul class="phases clear" data-ui-phases data-selected="{{router.params.tab}}">
            <li data-state="/console/databases/collection?id={{router.params.id}}&databaseId={{router.params.databaseId}}&project={{router.params.project}}">

                <h2>Documents</h2>

                <div
                    data-service="databases.listDocuments"
                    data-event="load,databases.createDocument,databases.updateDocument,databases.deleteDocument"
                    data-param-collection-id="{{router.params.id}}"
                    data-param-database-id="{{router.params.databaseId}}"
                    data-param-queries="limit(<?php echo APP_PAGING_LIMIT; ?>),offset({{router.params.offset|orZero}}),orderDesc('')"
                    data-param-queries-cast-to="array"
                    data-param-queries-cast-from="csv"
                    data-scope="sdk"
                    data-name="project-documents"
                    x-data="{ project: new URLSearchParams(location.search).get('project') }">

                    <div data-ls-if="0 == {{project-documents.total}}" class="box margin-bottom">
                        <h3 class="margin-bottom-small text-bold">No Documents Found</h3>

                        <p class="margin-bottom-no">Add your first document to get started</p>
                    </div>

                    <div data-ls-if="({{project-documents.total}})" class="margin-top-negative">
                        <div class="margin-bottom-small text-align-end text-size-small text-fade"><span data-ls-bind="{{project-documents.total}}"></span><span data-ls-if="{{project-documents.total}} == <?php echo APP_LIMIT_COUNT; ?>">+</span> documents found</div>
                        <div class="box margin-bottom y-scroll text-size-small">
                            <!-- Alpine.js Start -->
                            <table
                                data-ls-attrs="x-init=attributes = {{project-collection.attributes}}"
                                x-data="{attributes: []}"
                                class="vertical borders">
                                <thead>
                                    <tr>
                                        <td style="width: 170px">$id <i class="pull-end text-size-xs icon-key"></i></td>
                                        <template x-for="attr in attributes">
                                            <td x-show="attr.status === 'available'" style="width: 170px">
                                                <i :class="'icon-' + (attr.format ? attr.format : attr.type)" class="pull-end text-size-xs"></i>
                                                <span x-text="attr.key" class="text-bold"></span>
                                                <span x-show="attr.array" class="text-size-small">[]</span>
                                            </td>
                                        </template>
                                    </tr>
                                </thead>
                                <tbody data-ls-attrs="x-init=documents = {{project-documents.documents}}; databaseId='{{router.params.databaseId}}'" x-data="{documents: []}">
                                    <template x-for="doc in documents">
                                        <tr>
                                            <td data-title="$id: ">
                                                <a :href="`/console/databases/document?id=${doc.$id}&collection=${doc.$collection}&databaseId=${databaseId}&project=${project}`" x-text="doc.$id"></a>
                                            </td>
                                            <template x-for="attr in attributes">
                                                <td x-show="attr.status === 'available'" :data-title="attr.key + ':'">
                                                    <a :href="`/console/databases/document?id=${doc.$id}&collection=${doc.$collection}&databaseId=${databaseId}&project=${project}`">
                                                        <span x-text="doc[attr.key] ?? 'n/a'"></span>
                                                    </a>
                                                </td>
                                            </template>
                                        </tr>
                                    </template>
                                </tbody>
                            </table>
                            <!-- Alpine.js End -->
                        </div>
                    </div>

                    <div class="pull-end text-align-center paging">
                        <form
                            data-service="databases.listDocuments"
                            data-event="submit"
                            data-param-database-id="{{router.params.databaseId}}"
                            data-param-collection-id="{{router.params.id}}"
                            data-scope="sdk"
                            data-name="project-documents"
                            data-success="state"
                            data-success-param-state-keys="search,offset">
                            <input type="hidden" name="offset">
                            <button name="queries" data-cast-to="array" data-cast-from="csv" data-paging-back data-paging-desc data-offset="{{router.params.offset}}" data-total="{{project-documents.total}}" class="margin-end round small" aria-label="Back"><i class="icon-left-open"></i></button>
                        </form>

                        <span data-ls-bind="{{router.params.offset|pageCurrent}} / {{project-documents.total|pageTotal}}"></span>

                        <form
                            data-service="databases.listDocuments"
                            data-event="submit"
                            data-param-database-id="{{router.params.databaseId}}"
                            data-param-collection-id="{{router.params.id}}"
                            data-scope="sdk"
                            data-name="project-documents"
                            data-success="state"
                            data-success-param-state-keys="search,offset">
                            <input type="hidden" name="offset">
                            <button name="queries" data-cast-to="array" data-cast-from="csv" data-paging-next data-paging-desc data-offset="{{router.params.offset}}" data-total="{{project-documents.total}}" class="margin-start round small" aria-label="Next"><i class="icon-right-open"></i></button>
                        </form>
                    </div>

                    <a data-ls-if="0 < {{project-collection.attributes.length}}" data-ls-attrs="href=/console/databases/document/new?collection={{router.params.id}}&databaseId={{router.params.databaseId}}&project={{router.params.project}}" class="button">
                        Add Document
                    </a>
                    <a data-ls-if="!{{project-collection.attributes.length}}" data-ls-attrs="href=/console/databases/collection/attributes?id={{router.params.id}}&databaseId={{router.params.databaseId}}&project={{router.params.project}}" class="button">
                        Create Attribute
                    </a>
                </div>
            </li>
            <li data-state="/console/databases/collection/attributes?id={{router.params.id}}&databaseId={{router.params.databaseId}}&project={{router.params.project}}">
                <h2>Attributes</h2>

                <div class="clear box margin-bottom">
                    <div data-ls-if="0 == {{project-collection.attributes.length}}">
                        <h3 class="margin-bottom-small text-bold">No Attributes Found</h3>

                        <p class="margin-bottom-no">Add your first attribute to get started</p>
                    </div>

                    <table class="vertical" data-ls-if="0 < {{project-collection.attributes.length}}">
                        <thead>
                            <tr>
                                <th width="30"></th>
                                <th width="100"></th>
                                <th width="130">Attribute ID</th>
                                <th width="100">Type</th>
                                <th></th>
                                <th width="32"></th>
                            </tr>
                        </thead>
                        <tbody data-ls-loop="project-collection.attributes" data-ls-as="attribute">
                            <tr>
                                <td>
                                    <i data-ls-if="!{{attribute.format}}" data-ls-attrs="class=icon-{{attribute.type}}"></i>
                                    <i data-ls-if="{{attribute.format}}" data-ls-attrs="class=icon-{{attribute.format}}"></i>
                                </td>

                                <td data-title="Status">
                                    <span data-ls-if="{{attribute.status}} == 'available'" class="text-size-small text-success">available&nbsp;</span>
                                    <span data-ls-if="{{attribute.status}} == 'processing'" class="text-size-small text-info">processing&nbsp;</span>
                                    <span data-ls-if="{{attribute.status}} == 'failed'" class="text-size-small text-danger">failed&nbsp;</span>
                                    <span data-ls-if="{{attribute.status}} == 'deleting'" class="text-size-small text-danger">deleting&nbsp;</span>
                                    <span data-ls-if="{{attribute.status}} == 'stuck'" class="text-size-small text-danger">stuck&nbsp;</span>
                                </td>

                                <td data-title="Attribute ID: ">
                                    <span class="text-size-small" data-ls-bind="{{attribute.key}}"></span>
                                </td>

                                <td data-title="Type:">
                                    <span class="text-size-small" data-ls-if="!{{attribute.array}}" data-ls-bind="{{attribute.type}}"></span>
                                    <span class="text-size-small" data-ls-if="{{attribute.array}}" data-ls-bind="{{attribute.type}}[]"></span>
                                    <span class="text-size-small" data-ls-if="{{attribute.format}}" data-ls-bind="({{attribute.format}})"></span>
                                </td>

                                <td data-title="">
                                    <span class="text-size-small text-danger" data-ls-if="{{attribute.required}}">required</span>
                                </td>

                                <td data-title="">
                                    <div data-ui-modal class="box modal sticky-footer width-large close" data-button-class="icon-dot-3 link" data-button-element="i">
                                        <button type="button" class="close pull-end" data-ui-modal-close=""><i class="icon-cancel"></i></button>

                                        <h1>
                                            <i data-ls-if="!{{attribute.format}}" data-ls-attrs="class=icon-{{attribute.type}}"></i>
                                            <i data-ls-if="{{attribute.format}}" data-ls-attrs="class=icon-{{attribute.format}}"></i>
                                            <span data-ls-bind="{{attribute.key}}"></span>
                                        </h1>

                                        <hr />

                                        <div class="row responsive modalize">
                                            <form>
                                                <div class="col span-12">
                                                    <label>Key</label>
                                                    <div class="input-copy">
                                                        <input type="text" data-ls-bind="{{attribute.key}}" data-forms-copy disabled />
                                                    </div>

                                                    <label>Type</label>
                                                    <input type="text" data-ls-bind="{{attribute.type}}" disabled />
                                                    <div data-ls-if="{{attribute.format}}">
                                                        <label>Format</label>
                                                        <input type="text" data-ls-bind="{{attribute.format}}" class="full-width" disabled />
                                                    </div>

                                                    <div class="row responsive thin">
                                                        <div class="col span-6 margin-bottom-small">
                                                            <label>Required</label>
                                                            <input type="text" data-ls-bind="{{attribute.required}}" disabled />
                                                        </div>
                                                        <div class="col span-6 margin-bottom-small">
                                                            <label>Array</label>
                                                            <input type="text" data-ls-bind="{{attribute.array}}" disabled />
                                                        </div>
                                                    </div>

                                                    <div data-ls-if="{{attribute.default}}">
                                                        <label>Default Value</label>
                                                        <input type="text" data-ls-bind="{{attribute.default}}" class="full-width" disabled />
                                                    </div>
                                                    <div data-ls-if="{{attribute.size}}">
                                                        <label for="size">Length</label>
                                                        <input type="text" data-ls-bind="{{attribute.size}}" class="full-width" disabled />
                                                    </div>

                                                    <div data-ls-if="{{attribute.format}} == 'enum'">
                                                        <label>Elements</label>
                                                        <span data-ls-loop="attribute.elements" data-ls-as="element">
                                                            <input type="text" data-ls-bind="{{element}}" class="full-width" disabled />
                                                        </span>
                                                    </div>

                                                    <div data-ls-if="{{attribute.min}} && {{attribute.max}}" class="row responsive thin">
                                                        <div class="col span-6 margin-bottom-small">
                                                            <label>Min</label>
                                                            <input type="text" name="min" data-ls-bind="{{attribute.min}}" class="full-width" disabled />
                                                        </div>
                                                        <div class="col span-6 margin-bottom-small">
                                                            <label>Max</label>
                                                            <input type="text" name="max" data-ls-bind="{{attribute.max}}" class="full-width" disabled />
                                                        </div>
                                                    </div>


                                                </div>
                                            </form>
                                        </div>

                                        <footer>
                                            <button data-ui-modal-close="" type="button" class="reverse">Cancel</button>
                                            <form
                                                data-ls-if="{{attribute.status}} !== 'deleting'"
                                                class="pull-end"
                                                data-analytics
                                                data-analytics-activity
                                                data-analytics-event="submit"
                                                data-analytics-category="console"
                                                data-analytics-label="Delete Collection Attribute"
                                                data-service="databases.deleteAttribute"
                                                data-scope="sdk"
                                                data-event="submit"
                                                data-confirm="Are you sure you want to delete this attribute?"
                                                data-param-database-id="{{router.params.databaseId}}"
                                                data-success="alert,trigger"
                                                data-success-param-alert-text="Deleted attribute successfully"
                                                data-success-param-trigger-events="databases.deleteAttribute"
                                                data-failure="alert"
                                                data-failure-param-alert-text="Failed to delete attribute"
                                                data-failure-param-alert-classname="error">

                                                <input type="hidden" name="projectId" data-ls-bind="{{router.params.project}}" />
                                                <input type="hidden" name="collectionId" data-ls-bind="{{project-collection.$id}}" />
                                                <input type="hidden" name="key" data-ls-bind="{{attribute.key}}" />

                                                <button class="danger">Delete</button>
                                            </form>
                                        </footer>
                                    </div>
                                </td>
                            </tr>
                        </tbody>
                    </table>
                </div>

                <div class="drop-list pull-start" data-ls-ui-open="" data-button-aria="Choose Attribute" data-button-text="Add Attribute" data-button-class="button" data-blur="1">
                    <ul>
                        <li>
                            <div class="link new-attribute-string"><i class="avatar icon-string"></i> New String Attribute</div>
                        </li>
                        <li>
                            <div class="link new-attribute-integer"><i class="avatar icon-integer"></i> New Integer Attribute</div>
                        </li>
                        <li>
                            <div class="link new-attribute-float"><i class="avatar icon-float"></i> New Float Attribute</div>
                        </li>
                        <li>
                            <div class="link new-attribute-boolean"><i class="avatar icon-boolean"></i> New Boolean Attribute</div>
                        </li>
                        <li>
                            <div class="link new-attribute-datetime"><i class="avatar icon-string"></i> New DateTime Attribute</div>
                        </li>
                        <li>
                            <div class="link new-attribute-url"><i class="avatar icon-link"></i> New URL Attribute</div>
                        </li>
                        <li>
                            <div class="link new-attribute-email"><i class="avatar icon-mail"></i> New Email Attribute</div>
                        </li>
                        <li>
                            <div class="link new-attribute-ip"><i class="avatar icon-ip"></i> New IP Attribute</div>
                        </li>
                        <li>
                            <div class="link new-attribute-enum"><i class="avatar icon-enum"></i> New Enum Attribute</div>
                        </li>
                    </ul>
                </div>
            </li>
            <li data-state="/console/databases/collection/indexes?id={{router.params.id}}&databaseId={{router.params.databaseId}}&project={{router.params.project}}">
                <h2>Indexes</h2>

                <div class="clear box margin-bottom">
                    <div data-ls-if="0 == {{project-collection.indexes.length}}">
                        <h3 class="margin-bottom-small text-bold">No Indexes Found</h3>

                        <p class="margin-bottom-no">Add your first index to get started</p>
                    </div>

                    <table class="vertical multi-line" data-ls-if="0 < {{project-collection.indexes.length}}">
                        <thead>
                            <tr>
                                <th width="30"></th>
                                <th width="80"></th>
                                <th width="130">Index Key</th>
                                <th width="100">Type</th>
                                <th width="180">Attributes</th>
                                <th></th>
                                <th width="80"></th>
                            </tr>
                        </thead>
                        <tbody data-ls-loop="project-collection.indexes" data-ls-as="index">
                            <tr>
                                <td>
                                    <i class="icon-key"></i>
                                </td>

                                <td data-title="Status">
                                    <span data-ls-if="{{index.status}} == 'available'" class="text-size-small text-success">available&nbsp;</span>
                                    <span data-ls-if="{{index.status}} == 'processing'" class="text-size-small text-info">processing&nbsp;</span>
                                    <span data-ls-if="{{index.status}} == 'failed'" class="text-size-small text-danger">failed&nbsp;</span>
                                    <span data-ls-if="{{index.status}} == 'deleting'" class="text-size-small text-danger">deleting&nbsp;</span>
                                    <span data-ls-if="{{index.status}} == 'stuck'" class="text-size-small text-danger">stuck&nbsp;</span>
                                </td>

                                <td data-title="Index Key: ">
                                    <span class="text-size-small" data-ls-bind="{{index.key}}"></span><span class="text-size-small" data-ls-if="{{index.size}}" data-ls-bind="({{index.size}})"></span>
                                </td>

                                <td data-title="Type:">
                                    <span class="text-size-small" data-ls-bind="{{index.type}}"></span>
                                    <span class="text-size-small" data-ls-if="{{index.array}}">[]</span>
                                </td>

                                <td data-title="Attributes:">
                                    <span class="text-size-small" data-ls-bind="{{index|indexAttributes}}"></span>
                                </td>

                                <td data-title="">
                                    <span class="text-size-small text-danger" data-ls-if="{{index.required}}">required</span>
                                </td>

                                <td data-title="">
                                    <form
                                        data-ls-if="{{index.status}} !== 'deleting'"
                                        class="pull-end"
                                        data-analytics
                                        data-analytics-activity
                                        data-analytics-event="submit"
                                        data-analytics-category="console"
                                        data-analytics-label="Delete Collection Index"
                                        data-service="databases.deleteIndex"
                                        data-scope="sdk"
                                        data-event="submit"
                                        data-confirm="Are you sure you want to delete this index?"
                                        data-param-database-id="{{router.params.databaseId}}"
                                        data-success="alert,trigger"
                                        data-success-param-alert-text="Deleted index successfully"
                                        data-success-param-trigger-events="databases.deleteIndex"
                                        data-failure="alert"
                                        data-failure-param-alert-text="Failed to delete index"
                                        data-failure-param-alert-classname="error">

                                        <input type="hidden" name="projectId" data-ls-bind="{{router.params.project}}" />
                                        <input type="hidden" name="collectionId" data-ls-bind="{{project-collection.$id}}" />
                                        <input type="hidden" name="key" data-ls-bind="{{index.key}}" />

                                        <button class="danger small">Delete</button>
                                    </form>
                                </td>
                            </tr>
                        </tbody>
                    </table>
                </div>

                <button class="new-index">Add Index</button>
            </li>
            <li data-state="/console/databases/collection/activity?id={{router.params.id}}&databaseId={{router.params.databaseId}}&project={{router.params.project}}">
                <h2>Activity</h2>

                <?php echo $logs->render(); ?>
            </li>
            <li data-state="/console/databases/collection/usage?id={{router.params.id}}&databaseId={{router.params.databaseId}}&project={{router.params.project}}">
                <form
                    class="pull-end margin-start-small margin-top-small" data-ls-if="{{usage.range}} !== '90d'"
                    data-service="databases.getCollectionUsage"
                    data-event="submit"
                    data-name="usage"
                    data-param-collection-id="{{router.params.id}}"
                    data-param-database-id="{{router.params.databaseId}}"
                    data-param-range="90d">
                    <button class="tick">90d</button>
                </form>

                <button class="tick pull-end margin-start-small margin-top-small" data-ls-if="{{usage.range}} === '90d'" disabled>90d</button>

                <form
                    class="pull-end margin-start-small margin-top-small" data-ls-if="{{usage.range}} !== '30d'"
                    data-service="databases.getCollectionUsage"
                    data-event="submit"
                    data-name="usage"
                    data-param-database-id="{{router.params.databaseId}}"
                    data-param-collection-id="{{router.params.id}}">
                    <button class="tick">30d</button>
                </form>

                <button class="tick pull-end margin-start-small margin-top-small" data-ls-if="{{usage.range}} === '30d'" disabled>30d</button>

                <form
                    class="pull-end margin-start-small margin-top-small" data-ls-if="{{usage.range}} !== '24h'"
                    data-service="databases.getCollectionUsage"
                    data-event="submit"
                    data-name="usage"
                    data-param-database-id="{{router.params.databaseId}}"
                    data-param-collection-id="{{router.params.id}}"
                    data-param-range="24h">
                    <button class="tick">24h</button>
                </form>

                <button class="tick pull-end margin-start-small margin-top-small" data-ls-if="{{usage.range}} === '24h'" disabled>24h</button>

                <h2>Usage</h2>

                <div data-service="databases.getCollectionUsage" data-event="load" data-name="usage" data-param-collection-id="{{router.params.id}}" data-param-database-id="{{router.params.databaseId}}">
                    <h3 class="margin-bottom-tiny">Documents</h3>
                    <p class="text-fade">Count of documents over time</p>
                    <div class="box margin-bottom-small">
                        <div class="margin-start-negative-small margin-end-negative-small margin-top-negative-small margin-bottom-negative-small">
                            <div class="chart background-image-no border-no margin-bottom-no">
                                <input type="hidden" data-ls-bind="{{usage}}" data-forms-chart="Documents=documentsCount" data-show-y-axis="true" data-height="140" />
                            </div>
                        </div>
                    </div>

                    <ul class="chart-notes margin-bottom-large">
                        <li>Documents <span data-ls-bind="({{usage.documentsCount|statsGetLast|statsTotal}})"></span></li>
                    </ul>

                    <h3 class="margin-bottom-tiny">Operations</h3>
                    <p class="text-fade">Count of documents create, read, update and delete operations over time</p>
                    <div class="box margin-bottom-small">
                        <div class="margin-start-negative-small margin-end-negative-small margin-top-negative-small margin-bottom-negative-small">
                            <div class="chart background-image-no border-no margin-bottom-no">
                                <input
                                    type="hidden"
                                    data-ls-bind="{{usage}}"
                                    data-forms-chart="Created=documentsCreate,Read=documentsRead,Updated=documentsUpdate,Deleted=documentsDelete"
                                    data-show-y-axis="true"
                                    data-colors="create,read,update,delete"
                                    data-height="140" />
                            </div>
                        </div>
                    </div>

                    <ul class="chart-notes margin-bottom-large crud">
                        <li>Created</li>
                        <li>Read</li>
                        <li>Updated</li>
                        <li>Deleted</li>
                    </ul>
                </div>
            </li>
            <li data-state="/console/databases/collection/settings?id={{router.params.id}}&databaseId={{router.params.databaseId}}&project={{router.params.project}}">
                <h2>Settings</h2>

                <div class="row responsive">
                    <div class="col span-8 margin-bottom">
                        <form id="<?php echo $permissions->getParam('form') ?>"></form>

                        <form
                            data-analytics
                            data-analytics-activity
                            data-analytics-event="submit"
                            data-analytics-category="console"
                            data-analytics-label="Update Database Collection"
                            data-service="databases.updateCollection"
                            data-scope="sdk"
                            data-event="submit"
                            data-param-collection-id="{{router.params.id}}"
                            data-param-database-id="{{router.params.databaseId}}"
                            data-success="alert,trigger"
                            data-success-param-alert-text="Updated collection successfully"
                            data-success-param-trigger-events="databases.updateCollection"
                            data-failure="alert"
                            data-failure-param-alert-text="Failed to update collection"
                            data-failure-param-alert-classname="error">

                            <div class="box">
                                <label for="collection-name">Name</label>
                                <input name="name" id="collection-name" type="text" autocomplete="off" data-ls-bind="{{project-collection.name}}" data-forms-text-direction required placeholder="Collection Name" maxlength="128" />

                                <div class="margin-bottom">
                                    <input name="enabled" type="hidden" data-forms-switch data-cast-to="boolean" data-ls-bind="{{project-collection.enabled}}" /> &nbsp; Enabled <span class="tooltip" data-tooltip="Mark whether collection is enabled"><i class="icon-info-circled"></i></span>
                                </div>

                                <hr class="margin-top-small" />

                                <label class="margin-bottom-small">Permissions</label>

                                <p class="text-fade text-size-small">Configure the permissions for this collection.</p>

                                <hr class="margin-top-small" />

                                <?php echo $permissions->render(); ?>

                                <hr class="margin-top-no" />

                                <label class="margin-bottom-small">Document Security</label>

                                <div class="row">
                                    <div class="col span-1"><input name="documentSecurity" value="false" type="checkbox" class="margin-top-no" data-ls-bind="{{project-collection.documentSecurity}}" /></div>
                                    <div class="col span-11">
                                        <b>Enabled</b>
                                        <p class="text-fade margin-top-tiny">With Document Security enabled, users will be able to access documents for which they have been granted <b>either</b> Document or Collection permissions.</p>
                                    </div>
                                </div>

                                <hr class="margin-top-no" />

                                <button x-data @click="$dispatch('addrow<?php echo \strtolower($permissions->getParam('form')) ?>')">Update</button>
                        </form>
                    </div>
                </div>
                <div class="col span-4 sticky-top">
                    <label>Collection ID</label>
                    <div class="input-copy margin-bottom">
                        <input id="id" type="text" autocomplete="off" placeholder="" data-ls-bind="{{project-collection.$id}}" disabled data-forms-copy class="margin-bottom-no" />
                    </div>

                    <label>Database ID</label>
                    <div class="input-copy margin-bottom">
                        <input type="text" autocomplete="off" placeholder="" data-ls-bind="{{router.params.databaseId}}" disabled data-forms-copy class="margin-bottom-no" />
                    </div>

                    <ul class="margin-bottom-large text-fade text-size-small">
                        <li class="margin-bottom-small"><i class="icon-angle-circled-right margin-start-tiny margin-end-tiny"></i>
                            <button data-ls-ui-trigger="open-json"
                                class="link text-size-small"
                                data-analytics
                                data-analytics-event="click"
                                data-analytics-category="console"
                                data-analytics-label="View as JSON (Collection)">
                                View as JSON
                            </button>
                        </li>
                        <li class="margin-bottom-small"><i class="icon-angle-circled-right margin-start-tiny margin-end-tiny"></i> Last Updated: <span data-ls-bind="{{project-collection.$updatedAt|date}}"></span></li>
                        <li class="margin-bottom-small"><i class="icon-angle-circled-right margin-start-tiny margin-end-tiny"></i> Created: <span data-ls-bind="{{project-collection.$createdAt|date}}"></span></li>
                    </ul>

                        <form
                            name="databases.deleteCollection" class="margin-bottom"
                            data-analytics
                            data-analytics-activity
                            data-analytics-event="submit"
                            data-analytics-category="console"
                            data-analytics-label="Delete Database Collection"
                            data-service="databases.deleteCollection"
                            data-event="submit"
                            data-param-collection-id="{{router.params.id}}"
                            data-param-database-id="{{router.params.databaseId}}"
                            data-confirm="Are you sure you want to delete this collection?"
                            data-success="alert,trigger,redirect"
                            data-success-param-alert-text="Collection deleted successfully"
                            data-success-param-trigger-events="databases.deleteCollection"
                            data-success-param-redirect-url="/console/databases?project={{router.params.project}}"
                            data-failure="alert"
                            data-failure-param-alert-text="Failed to delete collection"
                            data-failure-param-alert-classname="error">

                        <button type="submit" class="danger fill">Delete Collection</button>
                    </form>
                </div>
            </div>
        </li>
    </ul>
</div>

<div data-ui-modal class="modal box close sticky-footer" data-button-alias=".new-attribute-string">
    <button type="button" class="close pull-end" data-ui-modal-close=""><i class="icon-cancel"></i></button>

    <h1>Add String Attribute</h1>

    <form
        id="add-string-attribute"
        data-analytics
        data-analytics-activity
        data-analytics-event="submit"
        data-analytics-category="console"
        data-analytics-label="Create Collection Attribute (string)"
        data-service="databases.createStringAttribute"
        data-scope="sdk"
        data-event="submit"
        data-success="alert,trigger,reset"
        data-success-param-alert-text="Created new attribute successfully"
        data-success-param-trigger-events="databases.createAttribute"
        data-failure="alert"
        data-failure-param-alert-text="Failed to create attribute"
        data-failure-param-alert-classname="error"
        @reset="array = required = false"
        x-data="{ array: false, required: false, size: null }">

        <input type="hidden" name="projectId" data-ls-bind="{{router.params.project}}" />
        <input type="hidden" name="collectionId" data-ls-bind="{{router.params.id}}" />
        <input type="hidden" name="databaseId" data-ls-bind="{{router.params.databaseId}}" />

        <label for="string-key">Attribute ID</label>
        <input id="string-key" type="text" class="full-width" name="key" required autocomplete="off" maxlength="36" pattern="^[a-zA-Z0-9][a-zA-Z0-9._-]{0,35}$" />
        <div class="text-fade text-size-xs margin-top-negative-small margin-bottom">Allowed Characters A-Z, a-z, 0-9, and non-leading underscore, hyphen and dot</div>

        <label for="string-length">Size</label>
        <input id="string-length" name="size" type="number" class="margin-bottom" autocomplete="off" required value="255" data-cast-to="integer" x-model="size" />

        <div class="margin-bottom">
            <input x-model="required" name="required" class="button switch" type="checkbox" /> &nbsp; Required <span class="tooltip" data-tooltip="Mark whether this is a required attribute"><i class="icon-info-circled"></i></span>
        </div>

        <div class="margin-bottom">
            <input x-model="array" name="array" class="button switch" type="checkbox" /> &nbsp; Array <span class="tooltip" data-tooltip="Mark whether this attribute should act as an array"><i class="icon-info-circled"></i></span>
        </div>

        <label for="xdefault">Default Value</label>
        <template x-if="!(array || required)">
            <input name="xdefault" type="text" class="margin-bottom-large" autocomplete="off" :maxlength="size">
        </template>
        <template x-if="(array || required)">
            <input name="xdefault" type="text" class="margin-bottom-large" autocomplete="off" disabled value="">
        </template>

        <footer>
            <button type="submit">Create</button> &nbsp; <button data-ui-modal-close="" type="button" class="reverse">Cancel</button>
        </footer>
    </form>
</div>

<div data-ui-modal class="modal box close sticky-footer" data-button-alias=".new-attribute-datetime">
    <button type="button" class="close pull-end" data-ui-modal-close=""><i class="icon-cancel"></i></button>

    <h1>Add DateTime Attribute</h1>

    <form
        id="add-datetime-attribute"
        data-analytics
        data-analytics-activity
        data-analytics-event="submit"
        data-analytics-category="console"
        data-analytics-label="Create Collection Attribute (datetime)"
        data-service="databases.createDatetimeAttribute"
        data-scope="sdk"
        data-event="submit"
        data-success="alert,trigger,reset"
        data-success-param-alert-text="Created new attribute successfully"
        data-success-param-trigger-events="databases.createAttribute"
        data-failure="alert"
        data-failure-param-alert-text="Failed to create attribute"
        data-failure-param-alert-classname="error"
        @reset="array = required = false"
        x-data="{ array: false, required: false, size: null }">

        <input type="hidden" name="projectId" data-ls-bind="{{router.params.project}}" />
        <input type="hidden" name="collectionId" data-ls-bind="{{router.params.id}}" />
        <input type="hidden" name="databaseId" data-ls-bind="{{router.params.databaseId}}" />

        <label for="string-key">Attribute ID</label>
        <input id="string-key" type="text" class="full-width" name="key" required autocomplete="off" maxlength="36" pattern="^[a-zA-Z0-9][a-zA-Z0-9._-]{0,35}$" />
        <div class="text-fade text-size-xs margin-top-negative-small margin-bottom">Allowed Characters A-Z, a-z, 0-9, and non-leading underscore, hyphen and dot</div>

        <div class="margin-bottom">
            <input x-model="required" name="required" class="button switch" type="checkbox" /> &nbsp; Required <span class="tooltip" data-tooltip="Mark whether this is a required attribute"><i class="icon-info-circled"></i></span>
        </div>

        <div class="margin-bottom">
            <input x-model="array" name="array" class="button switch" type="checkbox" /> &nbsp; Array <span class="tooltip" data-tooltip="Mark whether this attribute should act as an array"><i class="icon-info-circled"></i></span>
        </div>

        <label for="xdefault">Default Value</label>
        <template x-if="!(array || required)">
            <input name="xdefault" type="datetime-local" class="margin-bottom-large">
        </template>
        <template x-if="(array || required)">
            <input name="xdefault" type="datetime-local" class="margin-bottom-large" disabled value="">
        </template>

        <footer>
            <button type="submit">Create</button> &nbsp; <button data-ui-modal-close="" type="button" class="reverse">Cancel</button>
        </footer>
    </form>
</div>

<div data-ui-modal class="modal box close sticky-footer" data-button-alias=".new-attribute-integer">
    <button type="button" class="close pull-end" data-ui-modal-close=""><i class="icon-cancel"></i></button>

    <h1>Add Integer Attribute</h1>

    <form
        id="add-integer-attribute"
        data-analytics
        data-analytics-activity
        data-analytics-event="submit"
        data-analytics-category="console"
        data-analytics-label="Create Collection Attribute (integer)"
        data-service="databases.createIntegerAttribute"
        data-scope="sdk"
        data-event="submit"
        data-success="alert,trigger,reset"
        data-success-param-alert-text="Created new attribute successfully"
        data-success-param-trigger-events="databases.createAttribute"
        data-failure="alert"
        data-failure-param-alert-text="Failed to create attribute"
        data-failure-param-alert-classname="error"
        @reset="array = required = false"
        x-data="{ array: false, required: false, min: null, max: null }">

        <input type="hidden" name="projectId" data-ls-bind="{{router.params.project}}" />
        <input type="hidden" name="databaseId" data-ls-bind="{{router.params.databaseId}}" />
        <input type="hidden" name="collectionId" data-ls-bind="{{router.params.id}}" />

        <label for="integer-key">Attribute ID</label>
        <input id="integer-key" type="text" class="full-width" name="key" required autocomplete="off" maxlength="36" pattern="^[a-zA-Z0-9][a-zA-Z0-9._-]{0,35}$" />
        <div class="text-fade text-size-xs margin-top-negative-small margin-bottom">Allowed Characters A-Z, a-z, 0-9, and non-leading underscore, hyphen and dot</div>

        <div class="margin-bottom">
            <input x-model="required" name="required" class="button switch" type="checkbox" /> &nbsp; Required <span class="tooltip" data-tooltip="Mark whether this is a required attribute"><i class="icon-info-circled"></i></span>
        </div>

        <div class="margin-bottom">
            <input x-model="array" name="array" class="button switch" type="checkbox" /> &nbsp; Array <span class="tooltip" data-tooltip="Mark whether this attribute should act as an array"><i class="icon-info-circled"></i></span>
        </div>

        <div class="row responsive thin">
            <div class="col span-6 margin-bottom-small">
                <label for="integer-min">Min</label>
                <input id="integer-min" type="number" step="1" class="full-width" name="min" autocomplete="off" data-cast-to="integer" x-model="min" />
            </div>
            <div class="col span-6 margin-bottom-small">
                <label for="integer-max">Max</label>
                <input id="integer-max" type="number" step="1" class="full-width" name="max" autocomplete="off" data-cast-to="integer" x-model="max" />
            </div>
        </div>

        <label for="integer-default">Default Value</label>

        <template x-if="!(array || required)">
            <input name="xdefault" type="number" class="margin-bottom-large" autocomplete="off" data-cast-to="integer" :min="min" :max="max">
        </template>
        <template x-if="(array || required)">
            <input name="xdefault" type="number" class="margin-bottom-large" autocomplete="off" data-cast-to="integer" disabled>
        </template>

        <footer>
            <button type="submit">Create</button> &nbsp; <button data-ui-modal-close="" type="button" class="reverse">Cancel</button>
        </footer>
    </form>
</div>

<div data-ui-modal class="modal box close sticky-footer" data-button-alias=".new-attribute-float">
    <button type="button" class="close pull-end" data-ui-modal-close=""><i class="icon-cancel"></i></button>

    <h1>Add Float Attribute</h1>

    <form
        id="add-float-attribute"
        data-analytics
        data-analytics-activity
        data-analytics-event="submit"
        data-analytics-category="console"
        data-analytics-label="Create Collection Attribute (float)"
        data-service="databases.createFloatAttribute"
        data-scope="sdk"
        data-event="submit"
        data-success="alert,trigger,reset"
        data-success-param-alert-text="Created new attribute successfully"
        data-success-param-trigger-events="databases.createAttribute"
        data-failure="alert"
        data-failure-param-alert-text="Failed to create attribute"
        data-failure-param-alert-classname="error"
        @reset="array = required = false"
        x-data="{ array: false, required: false, min: null, max: null }">

        <input type="hidden" name="projectId" data-ls-bind="{{router.params.project}}" />
        <input type="hidden" name="databaseId" data-ls-bind="{{router.params.databaseId}}" />
        <input type="hidden" name="collectionId" data-ls-bind="{{router.params.id}}" />

        <label for="float-key">Attribute ID</label>
        <input id="float-key" type="text" class="full-width" name="key" required autocomplete="off" maxlength="36" pattern="^[a-zA-Z0-9][a-zA-Z0-9._-]{0,35}$" />
        <div class="text-fade text-size-xs margin-top-negative-small margin-bottom">Allowed Characters A-Z, a-z, 0-9, and non-leading underscore, hyphen and dot</div>

        <div class="margin-bottom">
            <input x-model="required" name="required" class="button switch" type="checkbox" /> &nbsp; Required <span class="tooltip" data-tooltip="Mark whether this is a required attribute"><i class="icon-info-circled"></i></span>
        </div>

        <div class="margin-bottom">
            <input x-model="array" name="array" class="button switch" type="checkbox" /> &nbsp; Array <span class="tooltip" data-tooltip="Mark whether this attribute should act as an array"><i class="icon-info-circled"></i></span>
        </div>

        <div class="row responsive thin">
            <div class="col span-6 margin-bottom-small">
                <label for="float-min">Min</label>
                <input id="float-min" type="number" class="full-width" name="min" step="any" autocomplete="off" data-cast-to="float" x-model="min" />
            </div>
            <div class="col span-6 margin-bottom-small">
                <label for="float-max">Max</label>
                <input id="float-max" type="number" class="full-width" name="max" step="any" autocomplete="off" data-cast-to="float" x-model="max" />
            </div>
        </div>

        <label for="float-default">Default Value</label>

        <template x-if="!(array || required)">
            <input name="xdefault" type="number" step="any" class="margin-bottom-large" autocomplete="off" data-cast-to="float" :min="min" :max="max">
        </template>
        <template x-if="(array || required)">
            <input name="xdefault" type="number" step="any" class="margin-bottom-large" autocomplete="off" data-cast-to="float" disabled>
        </template>

        <footer>
            <button type="submit">Create</button> &nbsp; <button data-ui-modal-close="" type="button" class="reverse">Cancel</button>
        </footer>
    </form>
</div>

<div data-ui-modal class="modal box close sticky-footer" data-button-alias=".new-attribute-email">
    <button type="button" class="close pull-end" data-ui-modal-close=""><i class="icon-cancel"></i></button>

    <h1>Add Email Attribute</h1>

    <form
        id="add-email-attribute"
        data-analytics
        data-analytics-activity
        data-analytics-event="submit"
        data-analytics-category="console"
        data-analytics-label="Create Collection Attribute (email)"
        data-service="databases.createEmailAttribute"
        data-scope="sdk"
        data-event="submit"
        data-success="alert,trigger,reset"
        data-success-param-alert-text="Created new attribute successfully"
        data-success-param-trigger-events="databases.createAttribute"
        data-failure="alert"
        data-failure-param-alert-text="Failed to create attribute"
        data-failure-param-alert-classname="error"
        @reset="array = required = false"
        x-data="{ array: false, required: false }">

        <input type="hidden" name="projectId" data-ls-bind="{{router.params.project}}" />
        <input type="hidden" name="databaseId" data-ls-bind="{{router.params.databaseId}}" />
        <input type="hidden" name="collectionId" data-ls-bind="{{router.params.id}}" />

        <label for="email-key">Attribute ID</label>
        <input id="email-key" type="text" class="full-width" name="key" required autocomplete="off" maxlength="128" maxlength="36" pattern="^[a-zA-Z0-9][a-zA-Z0-9._-]{0,35}$" />
        <div class="text-fade text-size-xs margin-top-negative-small margin-bottom">Allowed Characters A-Z, a-z, 0-9, and non-leading underscore, hyphen and dot</div>

        <div class="margin-bottom">
            <input x-model="required" name="required" class="button switch" type="checkbox" /> &nbsp; Required <span class="tooltip" data-tooltip="Mark whether this is a required attribute"><i class="icon-info-circled"></i></span>
        </div>

        <div class="margin-bottom">
            <input x-model="array" name="array" class="button switch" type="checkbox" /> &nbsp; Array <span class="tooltip" data-tooltip="Mark whether this attribute should act as an array"><i class="icon-info-circled"></i></span>
        </div>

        <label for="string-default">Default Value</label>
        <template x-if="!(array || required)">
            <input name="xdefault" type="email" class="margin-bottom-large" autocomplete="off">
        </template>
        <template x-if="(array || required)">
            <input name="xdefault" type="email" class="margin-bottom-large" autocomplete="off" disabled value="">
        </template>

        <footer>
            <button type="submit">Create</button> &nbsp; <button data-ui-modal-close="" type="button" class="reverse">Cancel</button>
        </footer>
    </form>
</div>

<div data-ui-modal class="modal box close sticky-footer" data-button-alias=".new-attribute-boolean">
    <button type="button" class="close pull-end" data-ui-modal-close=""><i class="icon-cancel"></i></button>

    <h1>Add Boolean Attribute</h1>

    <form
        id="add-boolean-attribute"
        data-analytics
        data-analytics-activity
        data-analytics-event="submit"
        data-analytics-category="console"
        data-analytics-label="Create Collection Attribute (boolean)"
        data-service="databases.createBooleanAttribute"
        data-scope="sdk"
        data-event="submit"
        data-success="alert,trigger,reset"
        data-success-param-alert-text="Created new attribute successfully"
        data-success-param-trigger-events="databases.createAttribute"
        data-failure="alert"
        data-failure-param-alert-text="Failed to create attribute"
        data-failure-param-alert-classname="error"
        @reset="array = required = false"
        x-data="{ array: false, required: false }">

        <input type="hidden" name="projectId" data-ls-bind="{{router.params.project}}" />
        <input type="hidden" name="databaseId" data-ls-bind="{{router.params.databaseId}}" />
        <input type="hidden" name="collectionId" data-ls-bind="{{router.params.id}}" />

        <label for="boolean-key">Attribute ID</label>
        <input id="boolean-key" type="text" class="full-width" name="key" required autocomplete="off" maxlength="36" pattern="^[a-zA-Z0-9][a-zA-Z0-9._-]{0,35}$" />
        <div class="text-fade text-size-xs margin-top-negative-small margin-bottom">Allowed Characters A-Z, a-z, 0-9, and non-leading underscore, hyphen and dot</div>

        <div class="margin-bottom">
            <input x-model="required" name="required" class="button switch" type="checkbox" /> &nbsp; Required <span class="tooltip" data-tooltip="Mark whether this is a required attribute"><i class="icon-info-circled"></i></span>
        </div>

        <div class="margin-bottom">
            <input x-model="array" name="array" class="button switch" type="checkbox" /> &nbsp; Array <span class="tooltip" data-tooltip="Mark whether this attribute should act as an array"><i class="icon-info-circled"></i></span>
        </div>


        <div class="margin-bottom-large">
            <template x-if="!(array || required)">
                <input name="xdefault" class="button switch" type="checkbox" />
            </template>
            <template x-if="(array || required)">
                <input name="" class="button switch" type="checkbox" disabled />
            </template>
            &nbsp; Default Value <span class="tooltip" data-tooltip="Whether this attribute is set to true or false on creation"><i class="icon-info-circled"></i></span>
        </div>

        <footer>
            <button type="submit">Create</button> &nbsp; <button data-ui-modal-close="" type="button" class="reverse">Cancel</button>
        </footer>
    </form>
</div>


<div data-ui-modal class="modal box close sticky-footer" data-button-alias=".new-attribute-ip">
    <button type="button" class="close pull-end" data-ui-modal-close=""><i class="icon-cancel"></i></button>

    <h1>Add IP Attribute</h1>

    <form
        id="add-ip-attribute"
        data-analytics
        data-analytics-activity
        data-analytics-event="submit"
        data-analytics-category="console"
        data-analytics-label="Create Collection Attribute (IP)"
        data-service="databases.createIpAttribute"
        data-scope="sdk"
        data-event="submit"
        data-success="alert,trigger,reset"
        data-success-param-alert-text="Created new attribute successfully"
        data-success-param-trigger-events="databases.createAttribute"
        data-failure="alert"
        data-failure-param-alert-text="Failed to create attribute"
        data-failure-param-alert-classname="error"
        @reset="array = required = false"
        x-data="{ array: false, required: false }">

        <input type="hidden" name="projectId" data-ls-bind="{{router.params.project}}" />
        <input type="hidden" name="databaseId" data-ls-bind="{{router.params.databaseId}}" />
        <input type="hidden" name="collectionId" data-ls-bind="{{router.params.id}}" />

        <label for="ip-key">Attribute ID</label>
        <input id="ip-key" type="text" class="full-width" name="key" required autocomplete="off" maxlength="36" pattern="^[a-zA-Z0-9][a-zA-Z0-9._-]{0,35}$" />
        <div class="text-fade text-size-xs margin-top-negative-small margin-bottom">Allowed Characters A-Z, a-z, 0-9, and non-leading underscore, hyphen and dot</div>

        <div class="margin-bottom">
            <input x-model="required" name="required" class="button switch" type="checkbox" /> &nbsp; Required <span class="tooltip" data-tooltip="Mark whether this is a required attribute"><i class="icon-info-circled"></i></span>
        </div>

        <div class="margin-bottom">
            <input x-model="array" name="array" class="button switch" type="checkbox" /> &nbsp; Array <span class="tooltip" data-tooltip="Mark whether this attribute should act as an array"><i class="icon-info-circled"></i></span>
        </div>

        <label for="string-default">Default Value</label>
        <template x-if="!(array || required)">
            <input name="xdefault" type="text" class="margin-bottom-large" autocomplete="off">
        </template>
        <template x-if="(array || required)">
            <input name="xdefault" type="text" class="margin-bottom-large" autocomplete="off" disabled value="">
        </template>

        <footer>
            <button type="submit">Create</button> &nbsp; <button data-ui-modal-close="" type="button" class="reverse">Cancel</button>
        </footer>
    </form>
</div>

<div data-ui-modal class="modal box close sticky-footer" data-button-alias=".new-attribute-url">
    <button type="button" class="close pull-end" data-ui-modal-close=""><i class="icon-cancel"></i></button>

    <h1>Add URL Attribute</h1>

    <form
        id="add-url-attribute"
        data-analytics
        data-analytics-activity
        data-analytics-event="submit"
        data-analytics-category="console"
        data-analytics-label="Create Collection Attribute (url)"
        data-service="databases.createUrlAttribute"
        data-scope="sdk"
        data-event="submit"
        data-success="alert,trigger,reset"
        data-success-param-alert-text="Created new attribute successfully"
        data-success-param-trigger-events="databases.createAttribute"
        data-failure="alert"
        data-failure-param-alert-text="Failed to create attribute"
        data-failure-param-alert-classname="error"
        @reset="array = required = false"
        x-data="{ array: false, required: false }">

        <input type="hidden" name="projectId" data-ls-bind="{{router.params.project}}" />
        <input type="hidden" name="databaseId" data-ls-bind="{{router.params.databaseId}}" />
        <input type="hidden" name="collectionId" data-ls-bind="{{router.params.id}}" />

        <label for="url-key">Attribute ID</label>
        <input id="url-key" type="text" class="full-width" name="key" required autocomplete="off" maxlength="36" pattern="^[a-zA-Z0-9][a-zA-Z0-9._-]{0,35}$" />
        <div class="text-fade text-size-xs margin-top-negative-small margin-bottom">Allowed Characters A-Z, a-z, 0-9, and non-leading underscore, hyphen and dot</div>

        <div class="margin-bottom">
            <input x-model="required" name="required" class="button switch" type="checkbox" /> &nbsp; Required <span class="tooltip" data-tooltip="Mark whether this is a required attribute"><i class="icon-info-circled"></i></span>
        </div>

        <div class="margin-bottom">
            <input x-model="array" name="array" class="button switch" type="checkbox" /> &nbsp; Array <span class="tooltip" data-tooltip="Mark whether this attribute should act as an array"><i class="icon-info-circled"></i></span>
        </div>

        <label for="string-default">Default Value</label>
        <template x-if="!(array || required)">
            <input name="xdefault" type="url" class="margin-bottom-large" autocomplete="off">
        </template>
        <template x-if="(array || required)">
            <input name="xdefault" type="url" class="margin-bottom-large" autocomplete="off" disabled value="">
        </template>

        <footer>
            <button type="submit">Create</button> &nbsp; <button data-ui-modal-close="" type="button" class="reverse">Cancel</button>
        </footer>
    </form>
</div>

<div data-ui-modal class="modal box close sticky-footer" data-button-alias=".new-attribute-enum">
    <button type="button" class="close pull-end" data-ui-modal-close=""><i class="icon-cancel"></i></button>

    <h1>Add Enum Attribute</h1>

    <form
        id="add-enum-attribute"
        data-analytics
        data-analytics-activity
        data-analytics-event="submit"
        data-analytics-category="console"
        data-analytics-label="Create Collection Attribute (enum)"
        data-service="databases.createEnumAttribute"
        data-scope="sdk"
        data-event="submit"
        data-success="alert,trigger,reset"
        data-success-param-alert-text="Created new attribute successfully"
        data-success-param-trigger-events="databases.createAttribute"
        data-failure="alert"
        data-failure-param-alert-text="Failed to create attribute"
        data-failure-param-alert-classname="error"
        @reset="array = required = false"
        x-data="{ array: false, required: false }">

        <input type="hidden" name="projectId" data-ls-bind="{{router.params.project}}" />
        <input type="hidden" name="databaseId" data-ls-bind="{{router.params.databaseId}}" />
        <input type="hidden" name="collectionId" data-ls-bind="{{router.params.id}}" />

        <label for="enum-key">Attribute ID</label>
        <input id="enum-key" type="text" class="full-width" name="key" required autocomplete="off" maxlength="36" pattern="^[a-zA-Z0-9][a-zA-Z0-9._-]{0,35}$" />
        <div class="text-fade text-size-xs margin-top-negative-small margin-bottom">Allowed Characters A-Z, a-z, 0-9, and non-leading underscore, hyphen and dot</div>

        <label>Elements</label>

        <div id="elements-section"></div>

        <div class="margin-bottom">
            <div data-forms-clone="" data-label="Add Element" data-target="elements-section" data-first="1">
                <div class="row responsive thin margin-bottom-tiny">
                    <div class="col span-11 margin-bottom-small">
                        <input data-cast-to="array" type="text" class="full-width" name="elements" required autocomplete="off" maxlength="128" />
                    </div>
                    <div class="col span-1 margin-bottom-small">
                        <button type="button" data-remove class="dark danger small round pull-end" style="margin-top: 10px;"><i class="icon-cancel"></i></button>
                    </div>
                </div>
            </div>
        </div>

        <div class="margin-bottom">
            <input x-model="required" name="required" class="button switch" type="checkbox" /> &nbsp; Required <span class="tooltip" data-tooltip="Mark whether this is a required attribute"><i class="icon-info-circled"></i></span>
        </div>

        <div class="margin-bottom">
            <input x-model="array" name="array" class="button switch" type="checkbox" /> &nbsp; Array <span class="tooltip" data-tooltip="Mark whether this attribute should act as an array"><i class="icon-info-circled"></i></span>
        </div>

        <label for="enunm-default">Default Value</label>
        <template x-if="!(array || required)">
            <input name="xdefault" type="text" class="margin-bottom-large" autocomplete="off">
        </template>
        <template x-if="(array || required)">
            <input name="xdefault" type="text" class="margin-bottom-large" autocomplete="off" disabled value="">
        </template>

        <footer>
            <button type="submit">Create</button> &nbsp; <button data-ui-modal-close="" type="button" class="reverse">Cancel</button>
        </footer>
    </form>
</div>

<div data-ui-modal class="modal box close sticky-footer" data-button-alias=".new-index">
    <button type="button" class="close pull-end" data-ui-modal-close=""><i class="icon-cancel"></i></button>

    <h1>Add Index</h1>

    <div data-ls-if="0 == {{project-collection.attributes.length}}">
        <div class="info margin-top margin-bottom">
            <h2>No Attributes Found</h2>

            <p>Please add your first attribute before adding your first index.</p>
        </div>

        <button data-ui-modal-close="" type="button" class="reverse">Cancel</button>
    </div>

    <form
        data-ls-if="0 < {{project-collection.attributes.length}}"
        data-analytics
        data-analytics-activity
        data-analytics-event="submit"
        data-analytics-category="console"
        data-analytics-label="Create Collection Index"
        data-service="databases.createIndex"
        data-scope="sdk"
        data-event="submit"
        data-success="alert,trigger,reset"
        data-success-param-alert-text="Created new index successfully"
        data-success-param-trigger-events="databases.createIndex"
        data-failure="alert"
        data-failure-param-alert-text="Failed to create index"
        data-failure-param-alert-classname="error">

        <input type="hidden" name="projectId" data-ls-bind="{{router.params.project}}" />
        <input type="hidden" name="databaseId" data-ls-bind="{{router.params.databaseId}}" />
        <input type="hidden" name="collectionId" data-ls-bind="{{router.params.id}}" />

        <label for="index-key">Index Key</label>
        <input id="index-key" type="text" class="full-width" name="key" required autocomplete="off" maxlength="36" pattern="^[a-zA-Z0-9][a-zA-Z0-9._-]{0,35}$" />
        <div class="text-fade text-size-xs margin-top-negative-small margin-bottom">Allowed Characters A-Z, a-z, 0-9, and non-leading underscore, hyphen and dot</div>

        <label for="index-type">Type</label>
        <select id="index-type" name="type">
            <option value="key">Key</option>
            <option value="unique">Unique</option>
            <option value="fulltext">Fulltext</option>
        </select>

        <label>Attributes</label>

        <div id="attributes-section"></div>

        <div class="margin-bottom">
            <div data-forms-clone="" data-label="Add Attribute" data-target="attributes-section" data-first="1">
                <div class="row responsive thin margin-bottom-tiny">
                    <div class="col span-7 margin-bottom-small">
                        <select data-duplications data-ls-attrs="name=attributes" data-cast-to="array" class="margin-bottom-no">
                            <optgroup label="Internal">
                                <option value="$id">$id</option>
                                <option value="$createdAt">$createdAt</option>
                                <option value="$updatedAt">$updatedAt</option>
                            </optgroup>
                            <optgroup label="Attributes" data-ls-loop="project-collection.attributes" data-ls-as="option">
                                <option data-ls-attrs="value={{option.key}}" data-ls-bind="{{option.key}}"></option>
                            </optgroup>
                        </select>
                    </div>
                    <div class="col span-4 margin-bottom-small">
                        <select name="orders" data-cast-to="array" class="margin-bottom-no">
                            <option value="ASC">ASC</option>
                            <option value="DESC">DESC</option>
                        </select>
                    </div>
                    <div class="col span-1 margin-bottom-small">
                        <button type="button" data-remove class="dark danger small round pull-end" style="margin-top: 10px;"><i class="icon-cancel"></i></button>
                    </div>
                </div>
            </div>
        </div>

        <footer>
            <button type="submit">Create</button> &nbsp; <button data-ui-modal-close="" type="button" class="reverse">Cancel</button>
        </footer>
    </form>
</div>

<div class="margin-top" data-service="databases.listCollections" data-param-database-id="{{router.params.databaseId}}" data-event="load,databases.createCollection,databases.updateCollection,databases.deleteCollection" data-scope="sdk" data-param-limit="100" data-name="project-collections">
</div>

<script type="text/html" id="template-attribute-title-first">
    <i data-ls-attrs="class=pull-end icon-key text-size-xs"></i>
    <span class="text-bold">$id</span>
</script>
<script type="text/html" id="template-attribute-body-first">
    <span class="text-fade" data-ls-bind="{{node.$id}}" data-general-copy data-class="icon-docs note copy text-fade pull-end"></span>
</script>
