import { Cpu, GitBranch, Hammer, Settings } from 'lucide-react'
import type { ResourceSettingsNavItem } from '../../shared/ProjectResourceSettingsShell'

export const SITE_SETTINGS_NAV: ResourceSettingsNavItem[] = [
  {
    id: 'general',
    label: 'General',
    pathSuffix: '',
    icon: Settings,
    keywords: [
      'general',
      'name',
      'identity',
      'details',
      'id',
      'copy',
      'created',
      'updated',
      'identifiers',
      'enabled',
      'disabled',
      'status',
      'toggle',
      'delete',
      'remove',
      'trash',
      'destroy',
      'danger',
    ],
  },
  {
    id: 'git',
    label: 'Version control (Git)',
    pathSuffix: 'git',
    icon: GitBranch,
    keywords: [
      'git',
      'github',
      'repository',
      'branch',
      'vcs',
      'silent',
      'silent mode',
      'comments',
      'commits',
      'pull request',
      'integration',
      'connect',
      'disconnect',
      'root directory',
      'production',
      'deployment',
    ],
  },
  {
    id: 'build',
    label: 'Build',
    pathSuffix: 'build',
    icon: Hammer,
    keywords: [
      'build',
      'framework',
      'adapter',
      'commands',
      'output',
      'specification',
      'profile',
      'vcpu',
      'memory',
      'worker',
      'compile',
      'static',
      'ssg',
      'deployment',
      'retention',
      'cleanup',
      'inactive',
      'forever',
      'triggers',
      'branch filter',
      'path filter',
      'glob',
      'pattern',
    ],
  },
  {
    id: 'runtime',
    label: 'Runtime',
    pathSuffix: 'runtime',
    icon: Cpu,
    keywords: [
      'runtime',
      'ssr',
      'specification',
      'timeout',
      'logging',
      'server',
      'render',
      'start',
      'image',
    ],
  },
]
