<?php
$key = $this->getParam('key', '');
$required = $this->getParam('required', '');
$comp = $this->getParam('comp', '');
$namespace = $this->getParam('namespace', '');

$comp->setParam('namespace', 'node.');
?>

<input type="hidden" name="<?php echo $this->escape($key); ?>"<?php if($required): ?> required<?php endif; ?> data-cast-to="array-empty">

<ul data-forms-add="New" data-ls-loop="<?php echo $this->escape($namespace); ?>" data-ls-as="node" class="sortable">
    <li data-forms-remove data-forms-move-up  data-forms-move-down>
        <div class="row thin responsive margin-bottom-small force-reverse">
            <div class="col span-1">
                <div class="drop-list bottom end" data-ls-ui-open="" data-button-text="" data-button-icon="icon-cog" data-button-selector="[data-toggler]" data-button-class="round dark small margin-bottom-small margin-top-tiny pull-end" data-blur="1" tabindex="1">
                    <ul>
                        <li data-move-up>
                            <button type="button" class="link"><i class="icon-up-dir"></i> Move Up</button>
                        </li>
                        <li data-move-down>
                            <button type="button" class="link"><i class="icon-down-dir"></i> Move Down</button>
                        </li>
                        <li data-remove>
                            <button type="button" class="link"><i class="icon-cancel"></i> Remove</button>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="col span-11">
                <?php echo $comp->render(); ?>
            </div>
        </div>

        <hr class="margin-top-no" />
    </li>
</ul>