<?php
$key = $this->getParam('key', '');
$required = $this->getParam('required', '');
$namespace = $this->getParam('namespace', '');
$collections = $this->getParam('collections', []);
$array = $this->getParam('array', false);
$list = $this->getParam('list', []);
$list = (is_array($list)) ? $list : [];
?>

<input
    type="text"
    name="<?php echo $this->escape($key); ?>"
    data-ls-bind="{{<?php echo $this->escape($namespace); ?>}}"
    class="margin-bottom-no">

<?php foreach($collections as $collection): ?>

    <button class="reverse margin-end-small" type="button"
        data-forms-document="open-document-serach-<?php echo $this->escape($collection->getId()); ?>"
        data-search="<?php echo $this->escape($namespace); ?>"><i class="icon-search"></i> <?php echo $this->escape($collection->getAttribute('name')); ?></button>
<?php endforeach; ?>