<?php
$key = $this->getParam('key', '');
$required = $this->getParam('required', '');
$namespace = $this->getParam('namespace', '');
?>
<input
    type="hidden"
    name="<?php echo $this->escape($key); ?>"
    data-ls-bind="{{<?php echo $this->escape($namespace); ?>}}"
    data-read="<?php echo $this->escape(json_encode([])); ?>"
    data-write="<?php echo $this->escape(json_encode([])); ?>"
    data-accept=""
    data-forms-upload=""
    data-label-button="Upload"
    data-search="<?php echo $this->escape($namespace); ?>"
    data-scope="sdk"
    data-default=""
    data-project="{{router.params.project}}"
    <?php if($required): ?> required<?php endif; ?>
    class="margin-bottom-no">