export const jaAccountGlobalBatch: Record<string, string> = {
  '123 Main St': '大手町 1-1-1',
  'Edge Functions': 'エッジ Functions',
  'Add a new billing address to your account.': 'アカウントに新しい請求先住所を追加します。',
  'Are you sure you want to delete this billing address? This action cannot be undone.':
    'この請求先住所を削除してもよろしいですか? この操作は元に戻せません。',
  "Are you sure you want to delete this identity?": 'この ID を削除してもよろしいですか?',
  'Are you sure you want to delete this payment method? This action cannot be undone.':
    'この支払い方法を削除してもよろしいですか? この操作は元に戻せません。',
  'Are you sure you want to delete your account? This action cannot be undone.':
    'アカウントを削除してもよろしいですか? この操作は元に戻せません。',
  'Are you sure you want to logout from all devices? You will need to sign in again to access your account from any device.':
    'すべてのデバイスからログアウトしてもよろしいですか? どのデバイスからアカウントにアクセスするにも、再度サインインする必要があります。',
  'Are you sure you want to logout from this device? You will be redirected to the sign-in page and will need to sign in again to access your account.':
    'このデバイスからログアウトしてもよろしいですか? サインインページにリダイレクトされ、アカウントにアクセスするには再度サインインする必要があります。',
  'Are you sure you want to logout from this device? You will need to sign in again to access your account from this device.':
    'このデバイスからログアウトしてもよろしいですか? このデバイスからアカウントにアクセスするには、再度サインインする必要があります。',
  'Are you sure you want to regenerate all recovery codes? All previously generated recovery codes will become invalid.':
    'すべてのリカバリーコードを再生成してもよろしいですか? 以前に生成されたリカバリーコードはすべて無効になります。',
  'Billing address has been added to your organization':
    '請求先住所が組織に追加されました',
  'Change your account password. Includes link to password recovery if forgotten.':
    'アカウントのパスワードを変更します。パスワードを忘れた場合のリカバリーリンクも含まれます。',
  'Deleting it will remove it from those organizations.':
    '削除すると、それらの組織からも削除されます。',
  "Enhance your account's security by requiring a second sign-in method":
    '2 つ目のサインイン方法を必須にして、アカウントのセキュリティを強化できます',
  'Enter the 6-digit one-time code generated by the app.':
    'アプリで生成された 6 桁のワンタイムコードを入力してください。',
  'Install an authenticator app on your mobile device, open it and scan the provided QR code or enter it manually.':
    'モバイルデバイスに認証アプリをインストールし、アプリを開いて表示された QR コードをスキャンするか、コードを手動で入力してください。',
  'Manage your billing addresses for invoices and payments.':
    '請求書と支払いのための請求先住所を管理します。',
  'Manage your payment methods and billing information.':
    '支払い方法と請求情報を管理します。',
  'Manually enter the following code into the authenticator app':
    '以下のコードを認証アプリに手動で入力してください',
  "Once you sign in via GitHub, you'll see it here.":
    'GitHub でサインインすると、ここに表示されます。',
  'Password must be at least 8 characters': 'パスワードは 8 文字以上で入力してください',
  "Save these recovery codes now. They won't be shown again.":
    '今すぐこれらのリカバリーコードを保存してください。二度と表示されません。',
  'This removes authenticator app codes from your account.':
    'この操作により、アカウントから認証アプリのコードが削除されます。',
  'Update the expiration date for this payment method.':
    'この支払い方法の有効期限を更新します。',
  'Update your account email address. Requires password verification when changing email.':
    'アカウントのメールアドレスを更新します。メールアドレスの変更にはパスワードによる確認が必要です。',
  'Use an authentication app to generate two-factor authentication codes.':
    '認証アプリを使って二要素認証コードを生成します。',
  "Use in case you can't receive two-factor authentication codes.":
    '二要素認証コードを受け取れない場合に使用してください。',
  'Use these codes to access your account if you lose your authenticator.':
    '認証アプリを紛失した場合は、これらのコードを使ってアカウントにアクセスできます。',
  'Use this ID when integrating with the Appwrite API or SDKs. Support may also ask for this ID when assisting with issues.':
    'Appwrite の API や SDK と連携する際は、この ID を使用してください。サポートが問題対応の際にこの ID を尋ねる場合もあります。',
  "You don't have any active sessions at the moment.":
    '現在アクティブなセッションはありません。',
  'Your account will be permanently deleted and access will be lost to any of your teams and data. This action is irreversible.':
    'アカウントは完全に削除され、すべてのチームとデータへのアクセスを失います。この操作は取り消せません。',
  'A 6-digit verification code was sent to your email. Enter it below.':
    '6 桁の確認コードをメールに送信しました。以下に入力してください。',
  'A 6-digit verification code was sent to your phone. Enter it below.':
    '6 桁の確認コードを電話に送信しました。以下に入力してください。',
  'After authorizing, return to your device.': '承認後、デバイスに戻ってください。',
  'Enter a 6-digit one-time code from your authenticator app.':
    '認証アプリに表示された 6 桁のワンタイムコードを入力してください。',
  'Enter one of the recovery codes you received when enabling MFA.':
    'MFA を有効化した際に受け取ったリカバリーコードのいずれかを入力してください。',
  'Enter your details to create a new account': '新しいアカウントを作成するには情報を入力してください',
  "Enter your email address and we'll send you a link to reset your password.":
    'メールアドレスを入力すると、パスワードをリセットするためのリンクをお送りします。',
  'No verification methods are available for this account. Contact support if you need help signing in.':
    'このアカウントで利用できる確認方法がありません。サインインでお困りの場合はサポートにお問い合わせください。',
  'Please wait while we confirm your email address.':
    'メールアドレスを確認していますので、しばらくお待ちください。',
  'Verified but could not open the console':
    '確認は完了しましたが、コンソールを開けませんでした',
  'wants to access your Appwrite account.': 'があなたの Appwrite アカウントへのアクセスを求めています。',
  "We'll send a recovery link to this email address.":
    'このメールアドレスにリカバリーリンクを送信します。',
  "We've sent a password recovery link to your email address.":
    'パスワードのリカバリーリンクをメールアドレスに送信しました。',
  "We've sent a verification link to your email address. Click the link to verify your account and access the console.":
    '確認リンクをメールアドレスに送信しました。リンクをクリックしてアカウントを確認し、コンソールにアクセスしてください。',
  'Your password has been successfully reset. You can now sign in with your new password.':
    'パスワードが正常にリセットされました。新しいパスワードでサインインできます。',
  'This account cannot use the Appwrite Console - access is blocked or restricted, which may include a Terms of Service violation. For questions about this restriction or to request a review of your account, contact support@appwrite.io.':
    'このアカウントは Appwrite Console を利用できません。利用規約違反などにより、アクセスがブロックまたは制限されている可能性があります。この制限についてのご質問や、アカウントの再審査をご希望の場合は、support@appwrite.io までお問い合わせください。',
  'Manage your organizations, projects, and all their resources on your behalf.':
    'あなたに代わって、組織、プロジェクト、およびそれらのすべてのリソースを管理します。',
  'Confirm who you are using your Appwrite account.':
    'Appwrite アカウントを使ってご本人であることを確認します。',
  'Read the email address associated with your account.':
    'アカウントに関連付けられたメールアドレスを読み取ります。',
  'You have file uploads in progress. Are you sure you want to leave?':
    'ファイルのアップロードが進行中です。このページを離れてもよろしいですか?',
  'Could not load this documentation page.': 'このドキュメントページを読み込めませんでした。',
  'You can re-enable them anytime from your browser settings.':
    'ブラウザの設定からいつでも再度有効にできます。',
  'Allow browser notifications to hear about build completion even when this tab is in the background.':
    'ブラウザの通知を許可すると、このタブがバックグラウンドにあってもビルドの完了を知ることができます。',
  'Deploy serverless functions at the edge for ultra-low latency':
    'エッジでサーバーレス関数をデプロイし、超低遅延を実現',
  "We've expanded to 12 new regions worldwide": '世界中に新たに 12 のリージョンを追加しました',
  'Check out our latest updates and improvements to enhance your development experience.':
    '開発体験を向上させる最新のアップデートと改善をご確認ください。',
  'Attachments upload in background. Sending waits until they are ready.':
    '添付ファイルはバックグラウンドでアップロードされます。準備が整うまで送信は待機します。',
  'I can inspect your project, explain issues, suggest next steps, and run approved actions.':
    'プロジェクトを確認し、問題を説明し、次のステップを提案し、承認されたアクションを実行できます。',
  'No accessible project found to create a conversation.':
    '会話を作成できるアクセス可能なプロジェクトが見つかりません。',
  'No accessible project found to start a new conversation.':
    '新しい会話を開始できるアクセス可能なプロジェクトが見つかりません。',
  'Press Enter to send, Shift+Enter for new line':
    '送信するには Enter、改行するには Shift+Enter を押してください',
  'Some attachments failed to upload. Remove them and try again.':
    '一部の添付ファイルのアップロードに失敗しました。削除してもう一度お試しください。',
  'Add one Appwrite Query condition for this entry.':
    'このエントリに Appwrite Query の条件を 1 つ追加します。',
  'Build a permission string for this entry. Changes apply when you click Done.':
    'このエントリの権限文字列を構築します。変更は完了をクリックすると適用されます。',
  'This endpoint is deprecated and may be removed in a future version.':
    'このエンドポイントは非推奨であり、将来のバージョンで削除される可能性があります。',
  'Draft scopes already match this endpoint.':
    '下書きのスコープは、すでにこのエンドポイントと一致しています。',
  'Ephemeral API key generated (expires in 1 hour)':
    '一時的な API キーを生成しました (1 時間で期限切れ)',
  'Expires in 1 hour. Regenerate after editing scopes below.':
    '1 時間で期限切れになります。下のスコープを編集した後に再生成してください。',
  'Invalid JSON. Fix the payload before switching to form view.':
    'JSON が無効です。フォーム表示に切り替える前にペイロードを修正してください。',
  'No session or JWT is sent on the request.': 'リクエストにセッションや JWT は送信されません。',
  'A JWT is created for this user when you send the request.':
    'リクエストを送信すると、このユーザー用の JWT が作成されます。',
  'Paste a project API key (optional)': 'プロジェクトの API キーを貼り付け (任意)',
  'Provide an API key or generate an ephemeral key.':
    'API キーを入力するか、一時的なキーを生成してください。',
  'Reset draft scopes to the scopes required by this endpoint.':
    '下書きのスコープを、このエンドポイントに必要なスコープにリセットします。',
  'Reused across methods. Stored locally in this browser.':
    'すべてのメソッドで再利用されます。このブラウザにローカル保存されます。',
  'Search by name, email, phone, or ID…': '名前、メール、電話番号、ID で検索…',
  'Select a method to inspect and send a request.':
    '確認してリクエストを送信するメソッドを選択してください。',
  'Select a user to act as, or choose Guest.':
    '操作するユーザーを選択するか、Guest を選んでください。',
  'Select at least one scope for the ephemeral key.':
    '一時的なキーには、少なくとも 1 つのスコープを選択してください。',
  'Send a request to see the response here.':
    'リクエストを送信すると、ここにレスポンスが表示されます。',
  "You've successfully joined. Redirecting you now...":
    '参加が完了しました。移動しています...',
  'This invitation link is missing required parameters. Please use the link from your invitation email.':
    'この招待リンクには必要なパラメーターが含まれていません。招待メールに記載されたリンクをご利用ください。',
  "You've been invited to join an organization. Accept the invitation to get started.":
    '組織への参加に招待されています。招待を承認して始めましょう。',
  'By accepting this invitation, you agree to our':
    'この招待を承認すると、次に同意したことになります:',
  'By clicking continue, you agree to our': '続行をクリックすると、次に同意したことになります:',
  'Signed in but could not open the console':
    'サインインは完了しましたが、コンソールを開けませんでした',
  'Account created but verification email could not be sent':
    'アカウントは作成されましたが、確認メールを送信できませんでした',
  'Verification link is invalid or has expired.':
    '確認リンクが無効か、有効期限が切れています。',
  'This password reset link is invalid or has expired. Please request a new one.':
    'このパスワードリセットリンクは無効か、有効期限が切れています。新しいリンクをリクエストしてください。',
  'This authorization request is invalid or has expired.':
    'この承認リクエストは無効か、有効期限が切れています。',
  'Missing authorization request. Open this page from an application sign-in.':
    '承認リクエストが見つかりません。アプリケーションのサインインからこのページを開いてください。',
  'That code is invalid or has expired. Check your device and try again.':
    'そのコードは無効か、有効期限が切れています。デバイスを確認してもう一度お試しください。',
  'Make sure this matches the code shown on your device, then continue.':
    'デバイスに表示されているコードと一致することを確認してから、続行してください。',
  'Enter the code shown on your device to continue.':
    '続行するには、デバイスに表示されているコードを入力してください。',
  'You can return to your device, it will continue automatically.':
    'デバイスに戻っていただければ、自動的に続行されます。',
  'No access was granted. You can close this page.':
    'アクセスは許可されませんでした。このページを閉じても構いません。',
  'Some Appwrite Cloud services are temporarily unavailable.':
    '一部の Appwrite Cloud サービスが一時的に利用できません。',
  'We\u2019re experiencing issues with some services.':
    '一部のサービスで問題が発生しています。',
  'You may have trouble accessing some services. We\u2019re working to restore full access.':
    '一部のサービスにアクセスしにくい状況が発生する可能性があります。全面復旧に向けて対応中です。',
  'A subset of Appwrite Cloud services is degraded.':
    '一部の Appwrite Cloud サービスでパフォーマンスが低下しています。',
  'Failed to resume project. Please try again.':
    'プロジェクトの再開に失敗しました。もう一度お試しください。',
  'This project has been paused due to inactivity. Your data is safe and will remain intact.':
    'このプロジェクトは非アクティブのため一時停止されています。データは安全に保持されています。',
  'Upgrade your plan to avoid pausing, or restore the project to continue using it now.':
    '一時停止を避けるにはプランをアップグレードするか、プロジェクトを復元して今すぐ利用を続けられます。',
}
