<?php

return [
    // Codes based on: https://github.com/matomo-org/device-detector/blob/master/Parser/Client/Browser.php
    'aa' => ['name' => 'Avant Browser', 'path' => __DIR__ . '/browsers/avant.png'],
    'an' => ['name' => 'Android WebView Beta', 'path' => __DIR__ . '/browsers/android-webview-beta.png'],
    'ch' => ['name' => 'Google Chrome', 'path' => __DIR__ . '/browsers/chrome.png'],
    'ci' => ['name' => 'Google Chrome (iOS)', 'path' => __DIR__ . '/browsers/chrome.png'],
    'cm' => ['name' => 'Google Chrome (Mobile)', 'path' => __DIR__ . '/browsers/chrome.png'],
    'cr' => ['name' => 'Chromium', 'path' => __DIR__ . '/browsers/chromium.png'],
    'ff' => ['name' => 'Mozilla Firefox', 'path' => __DIR__ . '/browsers/firefox.png'],
    'sf' => ['name' => 'Safari', 'path' => __DIR__ . '/browsers/safari.png'],
    'mf' => ['name' => 'Mobile Safari', 'path' => __DIR__ . '/browsers/safari.png'],
    'ps' => ['name' => 'Microsoft Edge', 'path' => __DIR__ . '/browsers/edge.png'],
    'oi' => ['name' => 'Microsoft Edge (iOS)', 'path' => __DIR__ . '/browsers/edge.png'],
    'om' => ['name' => 'Opera Mini', 'path' => __DIR__ . '/browsers/opera-mini.png'],
    'op' => ['name' => 'Opera', 'path' => __DIR__ . '/browsers/opera.png'],
    'on' => ['name' => 'Opera (Next)', 'path' => __DIR__ . '/browsers/opera.png'],


    /*
    '36' => '360 Phone Browser',
    '3B' => '360 Browser',
    'AA' => 'Avant Browser',
    'AB' => 'ABrowse',
    'AF' => 'ANT Fresco',
    'AG' => 'ANTGalio',
    'AL' => 'Aloha Browser',
    'AM' => 'Amaya',
    'AO' => 'Amigo',
    'AN' => 'Android Browser',
    'AR' => 'Arora',
    'AV' => 'Amiga Voyager',
    'AW' => 'Amiga Aweb',
    'AT' => 'Atomic Web Browser',
    'AS' => 'Avast Secure Browser',
    'BB' => 'BlackBerry Browser',
    'BD' => 'Baidu Browser',
    'BS' => 'Baidu Spark',
    'BE' => 'Beonex',
    'BJ' => 'Bunjalloo',
    'BL' => 'B-Line',
    'BR' => 'Brave',
    'BK' => 'BriskBard',
    'BX' => 'BrowseX',
    'CA' => 'Camino',
    'CC' => 'Coc Coc',
    'CD' => 'Comodo Dragon',
    'C1' => 'Coast',
    'CX' => 'Charon',
    'CF' => 'Chrome Frame',
    'CH' => 'Chrome',
    'CI' => 'Chrome Mobile iOS',
    'CK' => 'Conkeror',
    'CM' => 'Chrome Mobile',
    'CN' => 'CoolNovo',
    'CO' => 'CometBird',
    'CP' => 'ChromePlus',
    'CR' => 'Chromium',
    'CY' => 'Cyberfox',
    'CS' => 'Cheshire',
    'CU' => 'Cunaguaro',
    'DB' => 'dbrowser',
    'DE' => 'Deepnet Explorer',
    'DF' => 'Dolphin',
    'DO' => 'Dorado',
    'DL' => 'Dooble',
    'DI' => 'Dillo',
    'EI' => 'Epic',
    'EL' => 'Elinks',
    'EB' => 'Element Browser',
    'EP' => 'GNOME Web',
    'ES' => 'Espial TV Browser',
    'FB' => 'Firebird',
    'FD' => 'Fluid',
    'FE' => 'Fennec',
    'FF' => 'Firefox',
    'FK' => 'Firefox Focus',
    'FL' => 'Flock',
    'FM' => 'Firefox Mobile',
    'FW' => 'Fireweb',
    'FN' => 'Fireweb Navigator',
    'GA' => 'Galeon',
    'GE' => 'Google Earth',
    'HJ' => 'HotJava',
    'IA' => 'Iceape',
    'IB' => 'IBrowse',
    'IC' => 'iCab',
    'I2' => 'iCab Mobile',
    'I1' => 'Iridium',
    'ID' => 'IceDragon',
    'IV' => 'Isivioo',
    'IW' => 'Iceweasel',
    'IE' => 'Internet Explorer',
    'IM' => 'IE Mobile',
    'IR' => 'Iron',
    'JS' => 'Jasmine',
    'JI' => 'Jig Browser',
    'KI' => 'Kindle Browser',
    'KM' => 'K-meleon',
    'KO' => 'Konqueror',
    'KP' => 'Kapiko',
    'KY' => 'Kylo',
    'KZ' => 'Kazehakase',
    'LB' => 'Liebao',
    'LG' => 'LG Browser',
    'LI' => 'Links',
    'LU' => 'LuaKit',
    'LS' => 'Lunascape',
    'LX' => 'Lynx',
    'MB' => 'MicroB',
    'MC' => 'NCSA Mosaic',
    'ME' => 'Mercury',
    'MF' => 'Mobile Safari',
    'MI' => 'Midori',
    'MU' => 'MIUI Browser',
    'MS' => 'Mobile Silk',
    'MX' => 'Maxthon',
    'NB' => 'Nokia Browser',
    'NO' => 'Nokia OSS Browser',
    'NV' => 'Nokia Ovi Browser',
    'NE' => 'NetSurf',
    'NF' => 'NetFront',
    'NL' => 'NetFront Life',
    'NP' => 'NetPositive',
    'NS' => 'Netscape',
    'NT' => 'NTENT Browser',
    'OB' => 'Obigo',
    'OD' => 'Odyssey Web Browser',
    'OF' => 'Off By One',
    'OE' => 'ONE Browser',
    'OI' => 'Opera Mini',
    'OM' => 'Opera Mobile',
    'OP' => 'Opera',
    'ON' => 'Opera Next',
    'OR' => 'Oregano',
    'OV' => 'Openwave Mobile Browser',
    'OW' => 'OmniWeb',
    'OT' => 'Otter Browser',
    'PL' => 'Palm Blazer',
    'PM' => 'Pale Moon',
    'PP' => 'Oppo Browser',
    'PR' => 'Palm Pre',
    'PU' => 'Puffin',
    'PW' => 'Palm WebPro',
    'PA' => 'Palmscape',
    'PX' => 'Phoenix',
    'PO' => 'Polaris',
    'PT' => 'Polarity',
    'PS' => 'Microsoft Edge',
    'QQ' => 'QQ Browser',
    'QT' => 'Qutebrowser',
    'QZ' => 'QupZilla',
    'RK' => 'Rekonq',
    'RM' => 'RockMelt',
    'SB' => 'Samsung Browser',
    'SA' => 'Sailfish Browser',
    'SC' => 'SEMC-Browser',
    'SE' => 'Sogou Explorer',
    'SF' => 'Safari',
    'SH' => 'Shiira',
    'SK' => 'Skyfire',
    'SS' => 'Seraphic Sraf',
    'SL' => 'Sleipnir',
    'SM' => 'SeaMonkey',
    'SN' => 'Snowshoe',
    'SR' => 'Sunrise',
    'SP' => 'SuperBird',
    'ST' => 'Streamy',
    'SX' => 'Swiftfox',
    'TZ' => 'Tizen Browser',
    'TS' => 'TweakStyle',
    'UC' => 'UC Browser',
    'VI' => 'Vivaldi',
    'VB' => 'Vision Mobile Browser',
    'WE' => 'WebPositive',
    'WF' => 'Waterfox',
    'WO' => 'wOSBrowser',
    'WT' => 'WeTab Browser',
    'YA' => 'Yandex Browser',
    'XI' => 'Xiino'
    */
];
