<?php

return [
    'af' => ['name' => 'Afghanistan', 'path' => __DIR__ . '/flags/af.png'],
    'ao' => ['name' => 'Angola', 'path' => __DIR__ . '/flags/ao.png'],
    'al' => ['name' => 'Albania', 'path' => __DIR__ . '/flags/al.png'],
    'ad' => ['name' => 'Andorra', 'path' => __DIR__ . '/flags/ad.png'],
    'ae' => ['name' => 'United Arab Emirates', 'path' => __DIR__ . '/flags/ae.png'],
    'ar' => ['name' => 'Argentina', 'path' => __DIR__ . '/flags/ar.png'],
    'am' => ['name' => 'Armenia', 'path' => __DIR__ . '/flags/am.png'],
    'ag' => ['name' => 'Antigua and Barbuda', 'path' => __DIR__ . '/flags/ag.png'],
    'au' => ['name' => 'Australia', 'path' => __DIR__ . '/flags/au.png'],
    'at' => ['name' => 'Austria', 'path' => __DIR__ . '/flags/at.png'],
    'az' => ['name' => 'Azerbaijan', 'path' => __DIR__ . '/flags/az.png'],
    'bi' => ['name' => 'Burundi', 'path' => __DIR__ . '/flags/bi.png'],
    'be' => ['name' => 'Belgium', 'path' => __DIR__ . '/flags/be.png'],
    'bj' => ['name' => 'Benin', 'path' => __DIR__ . '/flags/bj.png'],
    'bf' => ['name' => 'Burkina Faso', 'path' => __DIR__ . '/flags/bf.png'],
    'bd' => ['name' => 'Bangladesh', 'path' => __DIR__ . '/flags/bd.png'],
    'bg' => ['name' => 'Bulgaria', 'path' => __DIR__ . '/flags/bg.png'],
    'bh' => ['name' => 'Bahrain', 'path' => __DIR__ . '/flags/bh.png'],
    'bs' => ['name' => 'Bahamas', 'path' => __DIR__ . '/flags/bs.png'],
    'ba' => ['name' => 'Bosnia and Herzegovina', 'path' => __DIR__ . '/flags/ba.png'],
    'by' => ['name' => 'Belarus', 'path' => __DIR__ . '/flags/by.png'],
    'bz' => ['name' => 'Belize', 'path' => __DIR__ . '/flags/bz.png'],
    'bo' => ['name' => 'Bolivia', 'path' => __DIR__ . '/flags/bo.png'],
    'br' => ['name' => 'Brazil', 'path' => __DIR__ . '/flags/br.png'],
    'bb' => ['name' => 'Barbados', 'path' => __DIR__ . '/flags/bb.png'],
    'bn' => ['name' => 'Brunei Darussalam', 'path' => __DIR__ . '/flags/bn.png'],
    'bt' => ['name' => 'Bhutan', 'path' => __DIR__ . '/flags/bt.png'],
    'bw' => ['name' => 'Botswana', 'path' => __DIR__ . '/flags/bw.png'],
    'cf' => ['name' => 'Central African Republic', 'path' => __DIR__ . '/flags/cf.png'],
    'ca' => ['name' => 'Canada', 'path' => __DIR__ . '/flags/ca.png'],
    'ch' => ['name' => 'Switzerland', 'path' => __DIR__ . '/flags/ch.png'],
    'cl' => ['name' => 'Chile', 'path' => __DIR__ . '/flags/cl.png'],
    'cn' => ['name' => 'China', 'path' => __DIR__ . '/flags/cn.png'],
    'ci' => ['name' => 'Côte d\'Ivoire', 'path' => __DIR__ . '/flags/ci.png'],
    'cm' => ['name' => 'Cameroon', 'path' => __DIR__ . '/flags/cm.png'],
    'cd' => ['name' => 'Democratic Republic of the Congo', 'path' => __DIR__ . '/flags/cd.png'],
    'cg' => ['name' => 'Republic of the Congo', 'path' => __DIR__ . '/flags/cg.png'],
    'co' => ['name' => 'Colombia', 'path' => __DIR__ . '/flags/co.png'],
    'km' => ['name' => 'Comoros', 'path' => __DIR__ . '/flags/km.png'],
    'cv' => ['name' => 'Cape Verde', 'path' => __DIR__ . '/flags/cv.png'],
    'cr' => ['name' => 'Costa Rica', 'path' => __DIR__ . '/flags/cr.png'],
    'cu' => ['name' => 'Cuba', 'path' => __DIR__ . '/flags/cu.png'],
    'cy' => ['name' => 'Cyprus', 'path' => __DIR__ . '/flags/cy.png'],
    'cz' => ['name' => 'Czech Republic', 'path' => __DIR__ . '/flags/cz.png'],
    'de' => ['name' => 'Germany', 'path' => __DIR__ . '/flags/de.png'],
    'dj' => ['name' => 'Djibouti', 'path' => __DIR__ . '/flags/dj.png'],
    'dm' => ['name' => 'Dominica', 'path' => __DIR__ . '/flags/dm.png'],
    'dk' => ['name' => 'Denmark', 'path' => __DIR__ . '/flags/dk.png'],
    'do' => ['name' => 'Dominican Republic', 'path' => __DIR__ . '/flags/do.png'],
    'dz' => ['name' => 'Algeria', 'path' => __DIR__ . '/flags/dz.png'],
    'ec' => ['name' => 'Ecuador', 'path' => __DIR__ . '/flags/ec.png'],
    'eg' => ['name' => 'Egypt', 'path' => __DIR__ . '/flags/eg.png'],
    'er' => ['name' => 'Eritrea', 'path' => __DIR__ . '/flags/er.png'],
    'es' => ['name' => 'Spain', 'path' => __DIR__ . '/flags/es.png'],
    'ee' => ['name' => 'Estonia', 'path' => __DIR__ . '/flags/ee.png'],
    'et' => ['name' => 'Ethiopia', 'path' => __DIR__ . '/flags/et.png'],
    'fi' => ['name' => 'Finland', 'path' => __DIR__ . '/flags/fi.png'],
    'fj' => ['name' => 'Fiji', 'path' => __DIR__ . '/flags/fj.png'],
    'fr' => ['name' => 'France', 'path' => __DIR__ . '/flags/fr.png'],
    'fm' => ['name' => 'Micronesia (Federated States of)', 'path' => __DIR__ . '/flags/fm.png'],
    'ga' => ['name' => 'Gabon', 'path' => __DIR__ . '/flags/ga.png'],
    'gb' => ['name' => 'United Kingdom', 'path' => __DIR__ . '/flags/gb.png'],
    'ge' => ['name' => 'Georgia', 'path' => __DIR__ . '/flags/ge.png'],
    'gh' => ['name' => 'Ghana', 'path' => __DIR__ . '/flags/gh.png'],
    'gn' => ['name' => 'Guinea', 'path' => __DIR__ . '/flags/gn.png'],
    'gm' => ['name' => 'Gambia', 'path' => __DIR__ . '/flags/gm.png'],
    'gw' => ['name' => 'Guinea-Bissau', 'path' => __DIR__ . '/flags/gw.png'],
    'gq' => ['name' => 'Equatorial Guinea', 'path' => __DIR__ . '/flags/gq.png'],
    'gr' => ['name' => 'Greece', 'path' => __DIR__ . '/flags/gr.png'],
    'gd' => ['name' => 'Grenada', 'path' => __DIR__ . '/flags/gd.png'],
    'gt' => ['name' => 'Guatemala', 'path' => __DIR__ . '/flags/gt.png'],
    'gy' => ['name' => 'Guyana', 'path' => __DIR__ . '/flags/gy.png'],
    'hn' => ['name' => 'Honduras', 'path' => __DIR__ . '/flags/hn.png'],
    'hr' => ['name' => 'Croatia', 'path' => __DIR__ . '/flags/hr.png'],
    'ht' => ['name' => 'Haiti', 'path' => __DIR__ . '/flags/ht.png'],
    'hu' => ['name' => 'Hungary', 'path' => __DIR__ . '/flags/hu.png'],
    'id' => ['name' => 'Indonesia', 'path' => __DIR__ . '/flags/id.png'],
    'in' => ['name' => 'India', 'path' => __DIR__ . '/flags/in.png'],
    'ie' => ['name' => 'Ireland', 'path' => __DIR__ . '/flags/ie.png'],
    'ir' => ['name' => 'Iran (Islamic Republic of)', 'path' => __DIR__ . '/flags/ir.png'],
    'iq' => ['name' => 'Iraq', 'path' => __DIR__ . '/flags/iq.png'],
    'is' => ['name' => 'Iceland', 'path' => __DIR__ . '/flags/is.png'],
    'il' => ['name' => 'Israel', 'path' => __DIR__ . '/flags/il.png'],
    'it' => ['name' => 'Italy', 'path' => __DIR__ . '/flags/it.png'],
    'jm' => ['name' => 'Jamaica', 'path' => __DIR__ . '/flags/jm.png'],
    'jo' => ['name' => 'Jordan', 'path' => __DIR__ . '/flags/jo.png'],
    'jp' => ['name' => 'Japan', 'path' => __DIR__ . '/flags/jp.png'],
    'kz' => ['name' => 'Kazakhstan', 'path' => __DIR__ . '/flags/kz.png'],
    'ke' => ['name' => 'Kenya', 'path' => __DIR__ . '/flags/ke.png'],
    'kg' => ['name' => 'Kyrgyzstan', 'path' => __DIR__ . '/flags/kg.png'],
    'kh' => ['name' => 'Cambodia', 'path' => __DIR__ . '/flags/kh.png'],
    'ki' => ['name' => 'Kiribati', 'path' => __DIR__ . '/flags/ki.png'],
    'kn' => ['name' => 'Saint Kitts and Nevis', 'path' => __DIR__ . '/flags/kn.png'],
    'kr' => ['name' => 'South Korea', 'path' => __DIR__ . '/flags/kr.png'],
    'kw' => ['name' => 'Kuwait', 'path' => __DIR__ . '/flags/kw.png'],
    'la' => ['name' => 'Lao People\'s Democratic Republic', 'path' => __DIR__ . '/flags/la.png'],
    'lb' => ['name' => 'Lebanon', 'path' => __DIR__ . '/flags/lb.png'],
    'lr' => ['name' => 'Liberia', 'path' => __DIR__ . '/flags/lr.png'],
    'ly' => ['name' => 'Libya', 'path' => __DIR__ . '/flags/ly.png'],
    'lc' => ['name' => 'Saint Lucia', 'path' => __DIR__ . '/flags/lc.png'],
    'li' => ['name' => 'Liechtenstein', 'path' => __DIR__ . '/flags/li.png'],
    'lk' => ['name' => 'Sri Lanka', 'path' => __DIR__ . '/flags/lk.png'],
    'ls' => ['name' => 'Lesotho', 'path' => __DIR__ . '/flags/ls.png'],
    'lt' => ['name' => 'Lithuania', 'path' => __DIR__ . '/flags/lt.png'],
    'lu' => ['name' => 'Luxembourg', 'path' => __DIR__ . '/flags/lu.png'],
    'lv' => ['name' => 'Latvia', 'path' => __DIR__ . '/flags/lv.png'],
    'ma' => ['name' => 'Morocco', 'path' => __DIR__ . '/flags/ma.png'],
    'mc' => ['name' => 'Monaco', 'path' => __DIR__ . '/flags/mc.png'],
    'md' => ['name' => 'Moldova', 'path' => __DIR__ . '/flags/md.png'],
    'mg' => ['name' => 'Madagascar', 'path' => __DIR__ . '/flags/mg.png'],
    'mv' => ['name' => 'Maldives', 'path' => __DIR__ . '/flags/mv.png'],
    'mx' => ['name' => 'Mexico', 'path' => __DIR__ . '/flags/mx.png'],
    'mh' => ['name' => 'Marshall Islands', 'path' => __DIR__ . '/flags/mh.png'],
    'mk' => ['name' => 'North Macedonia', 'path' => __DIR__ . '/flags/mk.png'],
    'ml' => ['name' => 'Mali', 'path' => __DIR__ . '/flags/ml.png'],
    'mt' => ['name' => 'Malta', 'path' => __DIR__ . '/flags/mt.png'],
    'mm' => ['name' => 'Myanmar', 'path' => __DIR__ . '/flags/mm.png'],
    'me' => ['name' => 'Montenegro', 'path' => __DIR__ . '/flags/me.png'],
    'mn' => ['name' => 'Mongolia', 'path' => __DIR__ . '/flags/mn.png'],
    'mz' => ['name' => 'Mozambique', 'path' => __DIR__ . '/flags/mz.png'],
    'mr' => ['name' => 'Mauritania', 'path' => __DIR__ . '/flags/mr.png'],
    'mu' => ['name' => 'Mauritius', 'path' => __DIR__ . '/flags/mu.png'],
    'mw' => ['name' => 'Malawi', 'path' => __DIR__ . '/flags/mw.png'],
    'my' => ['name' => 'Malaysia', 'path' => __DIR__ . '/flags/my.png'],
    'na' => ['name' => 'Namibia', 'path' => __DIR__ . '/flags/na.png'],
    'ne' => ['name' => 'Niger', 'path' => __DIR__ . '/flags/ne.png'],
    'ng' => ['name' => 'Nigeria', 'path' => __DIR__ . '/flags/ng.png'],
    'ni' => ['name' => 'Nicaragua', 'path' => __DIR__ . '/flags/ni.png'],
    'nl' => ['name' => 'Netherlands', 'path' => __DIR__ . '/flags/nl.png'],
    'no' => ['name' => 'Norway', 'path' => __DIR__ . '/flags/no.png'],
    'np' => ['name' => 'Nepal', 'path' => __DIR__ . '/flags/np.png'],
    'nr' => ['name' => 'Nauru', 'path' => __DIR__ . '/flags/nr.png'],
    'nz' => ['name' => 'New Zealand', 'path' => __DIR__ . '/flags/nz.png'],
    'om' => ['name' => 'Oman', 'path' => __DIR__ . '/flags/om.png'],
    'pk' => ['name' => 'Pakistan', 'path' => __DIR__ . '/flags/pk.png'],
    'pa' => ['name' => 'Panama', 'path' => __DIR__ . '/flags/pa.png'],
    'pe' => ['name' => 'Peru', 'path' => __DIR__ . '/flags/pe.png'],
    'ph' => ['name' => 'Philippines', 'path' => __DIR__ . '/flags/ph.png'],
    'pw' => ['name' => 'Palau', 'path' => __DIR__ . '/flags/pw.png'],
    'pg' => ['name' => 'Papua New Guinea', 'path' => __DIR__ . '/flags/pg.png'],
    'pl' => ['name' => 'Poland', 'path' => __DIR__ . '/flags/pl.png'],
    'kp' => ['name' => 'North Korea', 'path' => __DIR__ . '/flags/kp.png'],
    'pt' => ['name' => 'Portugal', 'path' => __DIR__ . '/flags/pt.png'],
    'py' => ['name' => 'Paraguay', 'path' => __DIR__ . '/flags/py.png'],
    'qa' => ['name' => 'Qatar', 'path' => __DIR__ . '/flags/qa.png'],
    'ro' => ['name' => 'Romania', 'path' => __DIR__ . '/flags/ro.png'],
    'ru' => ['name' => 'Russia', 'path' => __DIR__ . '/flags/ru.png'],
    'rw' => ['name' => 'Rwanda', 'path' => __DIR__ . '/flags/rw.png'],
    'sa' => ['name' => 'Saudi Arabia', 'path' => __DIR__ . '/flags/sa.png'],
    'sd' => ['name' => 'Sudan', 'path' => __DIR__ . '/flags/sd.png'],
    'sn' => ['name' => 'Senegal', 'path' => __DIR__ . '/flags/sn.png'],
    'sg' => ['name' => 'Singapore', 'path' => __DIR__ . '/flags/sg.png'],
    'sb' => ['name' => 'Solomon Islands', 'path' => __DIR__ . '/flags/sb.png'],
    'sl' => ['name' => 'Sierra Leone', 'path' => __DIR__ . '/flags/sl.png'],
    'sv' => ['name' => 'El Salvador', 'path' => __DIR__ . '/flags/sv.png'],
    'sm' => ['name' => 'San Marino', 'path' => __DIR__ . '/flags/sm.png'],
    'so' => ['name' => 'Somalia', 'path' => __DIR__ . '/flags/so.png'],
    'rs' => ['name' => 'Serbia', 'path' => __DIR__ . '/flags/rs.png'],
    'ss' => ['name' => 'South Sudan', 'path' => __DIR__ . '/flags/ss.png'],
    'st' => ['name' => 'Sao Tome and Principe', 'path' => __DIR__ . '/flags/st.png'],
    'sr' => ['name' => 'Suriname', 'path' => __DIR__ . '/flags/sr.png'],
    'sk' => ['name' => 'Slovakia', 'path' => __DIR__ . '/flags/sk.png'],
    'si' => ['name' => 'Slovenia', 'path' => __DIR__ . '/flags/si.png'],
    'se' => ['name' => 'Sweden', 'path' => __DIR__ . '/flags/se.png'],
    'sz' => ['name' => 'Eswatini', 'path' => __DIR__ . '/flags/sz.png'],
    'sc' => ['name' => 'Seychelles', 'path' => __DIR__ . '/flags/sc.png'],
    'sy' => ['name' => 'Syria', 'path' => __DIR__ . '/flags/sy.png'],
    'td' => ['name' => 'Chad', 'path' => __DIR__ . '/flags/td.png'],
    'tg' => ['name' => 'Togo', 'path' => __DIR__ . '/flags/tg.png'],
    'th' => ['name' => 'Thailand', 'path' => __DIR__ . '/flags/th.png'],
    'tj' => ['name' => 'Tajikistan', 'path' => __DIR__ . '/flags/tj.png'],
    'tm' => ['name' => 'Turkmenistan', 'path' => __DIR__ . '/flags/tm.png'],
    'tl' => ['name' => 'Timor-Leste', 'path' => __DIR__ . '/flags/tl.png'],
    'to' => ['name' => 'Tonga', 'path' => __DIR__ . '/flags/to.png'],
    'tt' => ['name' => 'Trinidad and Tobago', 'path' => __DIR__ . '/flags/tt.png'],
    'tn' => ['name' => 'Tunisia', 'path' => __DIR__ . '/flags/tn.png'],
    'tr' => ['name' => 'Turkey', 'path' => __DIR__ . '/flags/tr.png'],
    'tv' => ['name' => 'Tuvalu', 'path' => __DIR__ . '/flags/tv.png'],
    'tz' => ['name' => 'Tanzania', 'path' => __DIR__ . '/flags/tz.png'],
    'ug' => ['name' => 'Uganda', 'path' => __DIR__ . '/flags/ug.png'],
    'ua' => ['name' => 'Ukraine', 'path' => __DIR__ . '/flags/ua.png'],
    'uy' => ['name' => 'Uruguay', 'path' => __DIR__ . '/flags/uy.png'],
    'us' => ['name' => 'United States', 'path' => __DIR__ . '/flags/us.png'],
    'uz' => ['name' => 'Uzbekistan', 'path' => __DIR__ . '/flags/uz.png'],
    'va' => ['name' => 'Vatican City', 'path' => __DIR__ . '/flags/va.png'],
    'vc' => ['name' => 'Saint Vincent and the Grenadines', 'path' => __DIR__ . '/flags/vc.png'],
    've' => ['name' => 'Venezuela', 'path' => __DIR__ . '/flags/ve.png'],
    'vn' => ['name' => 'Vietnam', 'path' => __DIR__ . '/flags/vn.png'],
    'vu' => ['name' => 'Vanuatu', 'path' => __DIR__ . '/flags/vu.png'],
    'ws' => ['name' => 'Samoa', 'path' => __DIR__ . '/flags/ws.png'],
    'ye' => ['name' => 'Yemen', 'path' => __DIR__ . '/flags/ye.png'],
    'za' => ['name' => 'South Africa', 'path' => __DIR__ . '/flags/za.png'],
    'zm' => ['name' => 'Zambia', 'path' => __DIR__ . '/flags/zm.png'],
    'zw' => ['name' => 'Zimbabwe', 'path' => __DIR__ . '/flags/zw.png'],
];
