<?php
return [
  'email' => [
    'mailchimp' => [
      'name' => 'Mailchimp',
      'developers' => 'https://mailchimp.com/developer/marketing/api/',
      'icon' => 'icon-mailchimp',
      'enabled' => false,
      'sandbox' => false,
      'form' => false,
      'beta' => false,
      'mock' => false,
    ],
    'mailgun' => [
      'name' => 'Mailgun',
      'developers' => 'https://documentation.mailgun.com/',
      'icon' => 'icon-mailgun',
      'enabled' => true,
      'sandbox' => false,
      'form' => false,
      'beta' => false,
      'mock' => false,
    ],
    'mailjet' => [
      'name' => 'Mailjet',
      'developers' => 'https://dev.mailjet.com/',
      'icon' => 'icon-mailjet',
      'enabled' => false,
      'sandbox' => false,
      'form' => false,
      'beta' => false,
      'mock' => false,
    ],
    'postmark' => [
      'name' => 'Postmark',
      'developers' => 'https://postmarkapp.com/developer',
      'icon' => 'icon-postmark',
      'enabled' => false,
      'sandbox' => false,
      'form' => false,
      'beta' => false,
      'mock' => false,
    ],
    'sendgrid' => [
      'name' => 'Sendgrid',
      'developers' => 'https://docs.sendgrid.com/api-reference/how-to-use-the-sendgrid-v3-api/',
      'icon' => 'icon-sendgrid',
      'enabled' => true,
      'sandbox' => false,
      'form' => false,
      'beta' => false,
      'mock' => false,
    ],
    'sendinblue' => [
      'name' => 'SendinBlue',
      'developers' => 'https://developers.sendinblue.com/',
      'icon' => 'icon-sendinblue',
      'enabled' => false,
      'sandbox' => false,
      'form' => false,
      'beta' => false,
      'mock' => false,
    ],
    'mailslurp' => [
      'name' => 'MailSlurp',
      'developers' => 'https://www.mailslurp.com/docs/',
      'icon' => 'icon-mailslurp',
      'enabled' => false,
      'sandbox' => false,
      'form' => false,
      'beta' => false,
      'mock' => false,
    ],
    'elasticemail' => [
      'name' => 'ElasticEmail',
      'developers' => 'https://api.elasticemail.com/public/help',
      'icon' => 'icon-elasticemail',
      'enabled' => false,
      'sandbox' => false,
      'form' => false,
      'beta' => false,
      'mock' => false,
    ],
    'ses' => [
      'name' => 'SES',
      'developers' => 'https://docs.aws.amazon.com/ses/latest/APIReference/',
      'icon' => 'icon-ses',
      'enabled' => false,
      'sandbox' => false,
      'form' => false,
      'beta' => false,
      'mock' => false,
    ],
  ],
  'sms' => [
    'africastalking' => [
      'name' => 'Africa\'s Talking',
      'developers' => 'https://developers.africastalking.com/',
      'icon' => 'icon-africastalking',
      'enabled' => false,
      'sandbox' => false,
      'form' => false,
      'beta' => false,
      'mock' => false,
    ],
    'clickatell' => [
      'name' => 'Clickatell',
      'developers' => 'https://www.clickatell.com/developers/api-docs/',
      'icon' => 'icon-clickatell',
      'enabled' => false,
      'sandbox' => false,
      'form' => false,
      'beta' => false,
      'mock' => false,
    ],
    'infobip' => [
      'name' => 'Infobip',
      'developers' => 'https://www.infobip.com/docs/',
      'icon' => 'icon-infobip',
      'enabled' => false,
      'sandbox' => false,
      'form' => false,
      'beta' => false,
      'mock' => false,
    ],
    'msg91' => [
      'name' => 'Msg91',
      'developers' => 'https://docs.msg91.com/reference/overview',
      'icon' => 'icon-msg91',
      'enabled' => true,
      'sandbox' => false,
      'form' => false,
      'beta' => false,
      'mock' => false,
    ],
    'plivo' => [
      'name' => 'Plivo',
      'developers' => 'https://developers.plivo.com/',
      'icon' => 'icon-plivo',
      'enabled' => false,
      'sandbox' => false,
      'form' => false,
      'beta' => false,
      'mock' => false,
    ],
    'sinch' => [
      'name' => 'Sinch',
      'developers' => 'https://developers.sinch.com/',
      'icon' => 'icon-sinch',
      'enabled' => false,
      'sandbox' => false,
      'form' => false,
      'beta' => false,
      'mock' => false,
    ],
    'sms77' => [
      'name' => 'Sms77',
      'developers' => 'https://sms77.io/docs/gateway/',
      'icon' => 'icon-sms77',
      'enabled' => false,
      'sandbox' => false,
      'form' => false,
      'beta' => false,
      'mock' => false,
    ],
    'telesign' => [
      'name' => 'Telesign',
      'developers' => 'https://developer.telesign.com/enterprise/docs',
      'icon' => 'icon-telesign',
      'enabled' => true,
      'sandbox' => false,
      'form' => false,
      'beta' => false,
      'mock' => false,
    ],
    'textmagic' => [
      'name' => 'TextMagic',
      'developers' => 'https://www.textmagic.com/docs/api/',
      'icon' => 'icon-twilio',
      'enabled' => true,
      'sandbox' => false,
      'form' => false,
      'beta' => false,
      'mock' => false,
    ],
    'twilio' => [
      'name' => 'Twilio',
      'developers' => 'https://www.twilio.com/docs/sms',
      'icon' => 'icon-twilio',
      'enabled' => true,
      'sandbox' => false,
      'form' => false,
      'beta' => false,
      'mock' => false,
    ],
    'twilio-notify' => [
      'name' => 'Twilio Notify',
      'developers' => 'https://www.twilio.com/docs/notify',
      'icon' => 'icon-twilio',
      'enabled' => true,
      'sandbox' => false,
      'form' => false,
      'beta' => false,
      'mock' => false,
    ],
    'vonage' => [
      'name' => 'Vonage',
      'developers' => 'https://developer.nexmo.com/',
      'icon' => 'icon-vonage',
      'enabled' => true,
      'sandbox' => false,
      'form' => false,
      'beta' => false,
      'mock' => false,
    ],
  ],
  'push' => [
    'apns' => [
      'name' => 'APNS',
      'developers' => 'https://developer.apple.com/documentation/usernotifications',
      'icon' => 'icon-apns',
      'enabled' => false,
      'sandbox' => false,
      'form' => false,
      'beta' => false,
      'mock' => false,
    ],
    'fcm' => [
      'name' => 'FCM',
      'developers' => 'https://firebase.google.com/docs/cloud-messaging',
      'icon' => 'icon-fcm',
      'enabled' => true,
      'sandbox' => false,
      'form' => false,
      'beta' => false,
      'mock' => false,
    ],
    'one_signal' => [
      'name' => 'OneSignal',
      'developers' => 'https://documentation.onesignal.com/docs',
      'icon' => 'icon-onesignal',
      'enabled' => false,
      'sandbox' => false,
      'form' => false,
      'beta' => false,
      'mock' => false,
    ],
    'pushbullet' => [
      'name' => 'PushBullet',
      'developers' => 'https://docs.pushbullet.com/',
      'icon' => 'icon-pushbullet',
      'enabled' => false,
      'sandbox' => false,
      'form' => false,
      'beta' => false,
      'mock' => false,
    ],
    'pusher' => [
      'name' => 'Pusher',
      'developers' => 'https://pusher.com/docs',
      'icon' => 'icon-pusher',
      'enabled' => false,
      'sandbox' => false,
      'form' => false,
      'beta' => false,
      'mock' => false,
    ],
    'pushwoosh' => [
      'name' => 'Pushwoosh',
      'developers' => 'https://www.pushwoosh.com/docs/',
      'icon' => 'icon-pushwoosh',
      'enabled' => false,
      'sandbox' => false,
      'form' => false,
      'beta' => false,
      'mock' => false,
    ],
    'urban_airship' => [
      'name' => 'Urban Airship',
      'developers' => 'https://docs.airship.com/api/',
      'icon' => 'icon-urbanairship',
      'enabled' => false,
      'sandbox' => false,
      'form' => false,
      'beta' => false,
      'mock' => false,
    ],
    'web_push' => [
      'name' => 'WebPush',
      'developers' => 'https://developer.mozilla.org/en-US/docs/Web/API/Push_API',
      'icon' => 'icon-webpush',
      'enabled' => false,
      'sandbox' => false,
      'form' => false,
      'beta' => false,
      'mock' => false,
    ],
  ]
];
