<?php

return [ // List of publicly visible scopes
    'users.read',
    'users.write',
    'teams.read',
    'teams.write',
    'collections.read',
    'collections.write',
    'documents.read',
    'documents.write',
    'files.read',
    'files.write',
    'functions.read',
    'functions.write',
    'health.read',
    // 'platforms.read',
    // 'platforms.write',
    // 'keys.read',
    // 'keys.write',
    // 'tasks.read',
    // 'tasks.write',
    // 'webhooks.read',
    // 'webhooks.write',
    'locale.read',
    'avatars.read',
    'health.read',
];;