<?php

return [
    [
        'label' => 'JS',
        'versions' => ['v1.0.0'],
        'logo' => 'js.svg',
        'link' => 'https://github.com/appwrite/sdk-for-js',
    ],
    [
        'label' => 'Node.js',
        'versions' => ['v1.0.0'],
        'logo' => 'nodejs.svg',
        'link' => 'https://github.com/appwrite/sdk-for-node',
    ],
    [
        'label' => 'Ruby',
        'versions' => ['v1.0.0'],
        'logo' => 'ruby.svg',
        'link' => 'https://github.com/appwrite/sdk-for-ruby',
    ],
    [
        'label' => 'Python',
        'versions' => ['v1.0.0'],
        'logo' => 'python.svg',
        'link' => 'https://github.com/appwrite/sdk-for-python',
    ],
    [
        'label' => 'PHP',
        'versions' => ['v1.0.0'],
        'logo' => 'php.svg',
        'link' => 'https://github.com/appwrite/sdk-for-php',
    ],
    [
        'label' => 'Go',
        'versions' => [],
        'logo' => 'go.svg',
        'link' => 'https://...',
        'tag' => 'Soon',
    ],
    [
        'label' => 'Scala',
        'versions' => [],
        'logo' => 'scala.svg',
        'link' => 'https://...',
        'tag' => 'Soon',
    ],
    [
        'label' => 'Swift',
        'versions' => [],
        'logo' => 'swift.svg',
        'link' => 'https://...',
        'tag' => 'Soon',
    ],
    [
        'label' => 'C',
        'versions' => [],
        'logo' => 'c.svg',
        'link' => 'https://...',
        'tag' => 'Soon',
    ],
    [
        'label' => 'C#',
        'versions' => [],
        'logo' => 'dotnet.svg',
        'link' => 'https://...',
        'tag' => 'Soon',
    ],
    [
        'label' => 'Erlang',
        'versions' => [],
        'logo' => 'erlang.svg',
        'link' => 'https://...',
        'tag' => 'Soon',
    ],
    [
        'label' => 'Kotlin',
        'versions' => [],
        'logo' => 'kotlin.svg',
        'link' => 'https://...',
        'tag' => 'Soon',
    ],
    [
        'label' => 'Java',
        'versions' => [],
        'logo' => 'java.svg',
        'link' => 'https://...',
        'tag' => 'Soon',
    ],
];
