<?php

return [
    '/' => [
        'name' => 'Homepage',
        'controller' => 'web/home.php',
        'sdk' => false,
        'tests' => false,
    ],
    'console/' => [
        'name' => 'Console',
        'controller' => 'web/console.php',
        'sdk' => false,
        'tests' => false,
    ],
    'v1/account' => [
        'name' => 'Account',
        'description' => '/docs/services/account.md',
        'controller' => 'api/account.php',
        'sdk' => true,
        'tests' => false,
    ],
    'v1/avatars' => [
        'name' => 'Avatars',
        'description' => '/docs/services/avatars.md',
        'controller' => 'api/avatars.php',
        'sdk' => true,
        'tests' => false,
    ],
    'v1/database' => [
        'name' => 'Database',
        'description' => '/docs/services/database.md',
        'controller' => 'api/database.php',
        'sdk' => true,
        'tests' => false,
    ],
    'v1/locale' => [
        'name' => 'Locale',
        'description' => '/docs/services/locale.md',
        'controller' => 'api/locale.php',
        'sdk' => true,
        'tests' => false,
    ],
    'v1/health' => [
        'name' => 'Health',
        'description' => '/docs/services/health.md',
        'controller' => 'api/health.php',
        'sdk' => true,
        'tests' => false,
    ],
    'v1/projects' => [
        'name' => 'Projects',
        'controller' => 'api/projects.php',
        'sdk' => true,
        'tests' => false,
    ],
    'v1/storage' => [
        'name' => 'Storage',
        'description' => '/docs/services/storage.md',
        'controller' => 'api/storage.php',
        'sdk' => true,
        'tests' => false,
    ],
    'v1/teams' => [
        'name' => 'Teams',
        'description' => '/docs/services/teams.md',
        'controller' => 'api/teams.php',
        'sdk' => true,
        'tests' => false,
    ],
    'v1/users' => [
        'name' => 'Users',
        'description' => '/docs/services/users.md',
        'controller' => 'api/users.php',
        'sdk' => true,
        'tests' => false,
    ],
    'v1/functions' => [
        'name' => 'Users',
        'description' => '/docs/services/functions.md',
        'controller' => 'api/functions.php',
        'sdk' => true,
        'tests' => false,
    ],
    'v1/mock' => [
        'name' => 'Mock',
        'description' => '',
        'controller' => 'mock.php',
        'sdk' => false,
        'tests' => true,
    ],
    'v1/graphql' => [
        'name' => 'GraphQL',
        'description' => 'GraphQL Endpoint',
        'controller' => 'api/graphql.php',
        'sdk' => false,
        'tests' => false,
    ],
];
