<!--
! BE AWRARE ! This block has not been localized.

<section class="zone xl">
    <form
      data-service="auth.confirm"
      data-scope="console"
      data-event="load"
      data-param-token="{{router.params.token}}"
      data-param-user-id="{{router.params.userId}}"
      data-success="redirect,alert,trigger"
      data-success-param-redirect-url="/console"
      data-success-alert="Confirmation Completed Successfully"
      data-success-triggers="account.update"
      data-failure="alert"
      data-failure-param-alert-text="Confirmation Failed"
      data-failure-param-alert-classname="error">

        <h2 class="margin-bottom-small">Account Confirmation in Progress</h2>
        <p>Please wait a few seconds while your account is verified.</p>
    </form>
</section> -->
