<?php

$locale = $this->getParam("locale");
/** @var Utopia\Locale\Locale $locale */

?>

<div class="zone large padding margin-top" id="message" style="display: none">
    <h1 class="margin-bottom"><?php echo $locale->getText('home.auth.magicurl.title'); ?></h1>
    <p><?php echo $locale->getText('home.auth.magicurl.description-chunk1'); ?>
        <a href="https://<?php echo APP_DOMAIN; ?>/docs/client/account?sdk=web#createMagicURLSession"><?php echo $locale->getText('home.auth.magicurl.description-chunk2'); ?></a>
        <?php echo $locale->getText('home.auth.magicurl.description-chunk3'); ?></p>
</div>

<script>
    setTimeout(function () {
        document.getElementById('message').style.display = 'block';
    }, 25);

    const urlSearchParams = new URLSearchParams(window.location.search);
    const {
        userId,
        secret,
        project
    } = Object.fromEntries(urlSearchParams.entries());

    const formData = new FormData();
    formData.append('userId', userId);
    formData.append('secret', secret);

    const res = fetch(window.location.origin + '/v1/account/sessions/magic-url', {
        method: 'PUT',
        body: formData,
        headers: {
            ["x-appwrite-project"]: project
        }
    }).then(response => response.json())
    .then(data => {
        if(data.$id) {
            window.location = 'appwrite-callback-' + project + '://'+window.location.search;
        }
    })

</script>
<hr />