<?php
$locale = $this->getParam("locale");
/** @var Utopia\Locale\Locale $locale */
?>

<div class="zone large padding margin-top" id="message" style="display: none">
    <h1 class="margin-bottom"><?php echo $locale->getText('home.auth.oauth2.title'); ?></h1>
    <p><?php echo $locale->getText('home.auth.oauth2.description-chunk1'); ?>
        <a href="https://<?php echo APP_DOMAIN; ?>/docs/client/account?sdk=web#createOAuth2Session"><?php echo $locale->getText('home.auth.oauth2.description-chunk2'); ?></a>
        <?php echo $locale->getText('home.auth.oauth2.description-chunk3'); ?></p>
</div>

<script>
    setTimeout(function () {
        document.getElementById('message').style.display = 'block';
    }, 25);

    const query = new URLSearchParams(window.location.search);
    const project = query.get('project');

    window.location = 'appwrite-callback-'+project+'://'+window.location.search;
</script>
<hr />