<div class="zone large padding margin-top" id="message" style="display: none">
    <h1 class="margin-bottom">Missing Redirect URL</h1>
    <p>Your OAuth login flow is missing a redirect URL. Please check the <a href="https://<?php echo APP_DOMAIN; ?>/docs/account?platform=web&language=javascript#createOAuth2Session">OAuth docs</a> and send request for new session with a valid callback URL.</p>
</div>

<script>
    setTimeout(function () {
        document.getElementById('message').style.display = 'block';
    }, 25);

    window.location = 'appwrite-callback://'+window.location.search;
</script>
<hr />