<div class="zone medium">
    <h1 class="zone xl margin-bottom-large margin-top">
        Password Recovery
    </h1>

    <small class="pull-end">* All fields are required</small>

    <form name="recovery"
          data-service="auth.recovery"
          data-scope="console"
          data-event="submit"
          data-success="alert"
          data-success-alert="We have sent you a mail with a password reset link"
          data-failure="alert"
          data-failure-param-alert-text="Password recovery failed"
          data-failure-param-alert-classname="error">

        <label>Email</label>
        <input name="email" type="email" class="full-width" autocomplete="email" placeholder="me@example.com" required>

        <input name="confirmation" type="hidden" data-ls-bind="{{env.PROTOCOL}}://{{env.DOMAIN}}/auth/recovery/reset" />

        <button type="submit" class="btn btn-primary"><i class="fa fa-sign-in"></i> Recover</button>
    </form>
</div>

<div class="zone medium">
    <a href="/auth/signin">Back to sign in</a>
</div>
