<?php
use Utopia\Locale\Locale;
?>
<div class="zone medium">
    <h1 class="zone xl margin-bottom-large margin-top">
        <?php echo $this->escape(Locale::getText('home.auth.signin.title')); ?>
    </h1>

    <div class="text-danger margin-bottom-large" style="display: none;" data-ls-if="{{router.params.failure}} >= 1"><?php echo $this->escape(Locale::getText('home.auth.signin.failure')); ?></div>

    <p><?php echo $this->escape(Locale::getText('home.auth.signin.regular.title')); ?></p>

    <form name="login"
        data-service="auth.login"
        data-scope="console"
        data-event="submit"
        data-success="trigger,redirect"
        data-success-param-trigger-events="login"
        data-success-param-redirect-url="/console"
        data-failure="alert"
        data-failure-param-alert-text="<?php echo $this->escape(Locale::getText('home.auth.signin.failure')); ?>"
        data-failure-param-alert-classname="error">

        <input name="success" type="hidden" data-ls-bind="{{env.PROTOCOL}}://{{env.DOMAIN}}/console">
        <input name="failure" type="hidden" data-ls-bind="{{env.PROTOCOL}}://{{env.DOMAIN}}/auth/signin?failure=1">

        <input name="email" type="email" class="full-width" autocomplete="email" placeholder="<?php echo $this->escape(Locale::getText('home.auth.signin.labels.email')); ?>" required>

        <input name="password" type="password" class="full-width" autocomplete="off" placeholder="<?php echo $this->escape(Locale::getText('home.auth.signin.labels.password')); ?>" required pattern=".{6,}" title="<?php echo $this->escape(Locale::getText('home.auth.signin.labels.password.validation')); ?>">

        <button><?php echo $this->escape(Locale::getText('home.auth.signin.labels.action1')); ?></button>
    </form>
    
    <br />
    <br />

    <div class="text-line-high-large">
        <a href="/auth/recovery"><?php echo $this->escape(Locale::getText('home.auth.signin.labels.action2')); ?></a> <?php echo $this->escape(Locale::getText('home.auth.signin.labels.or')); ?> <b><a href="/auth/signup"><?php echo $this->escape(Locale::getText('home.auth.signin.labels.action3')); ?></a></b>
    </div>
</div>