<?php
$root = ($this->getParam('root') !== 'disabled');

$locale = $this->getParam("locale");
/** @var Utopia\Locale\Locale $locale */

?>
<div class="zone medium"
    data-service="account.get"
    data-name="account"
    data-scope="console"
    data-event="load"
    data-success="redirect"
    data-success-param-redirect-url="/console"
    data-success-param-trigger-events="account.get">

    <div data-ls-if="{{account}} === undefined">
        <h1 class="zone xl margin-bottom-large margin-top">
            <?php echo $locale->getText("home.auth.signin.title"); ?>
        </h1>


        <div class="text-danger margin-bottom-large" data-ls-if="{{router.params.failure}} >= 1"><?php echo $locale->getText("home.auth.signin.submit-error"); ?></div>

        <p><?php echo $locale->getText("home.auth.signin.description"); ?></p>

        <form name="account.createSession"
            data-analytics
            data-analytics-activity
            data-analytics-event="submit"
            data-analytics-category="home"
            data-analytics-label="Create Account Session"
            data-service="account.createSession"
            data-scope="console"
            data-event="submit"
            data-success="trigger,hide,redirect"
            data-success-param-trigger-events="account.createSession"
            data-success-param-redirect-url="/console"
            data-failure="alert"
            data-failure-param-alert-text="Login failed. Please check your credentials."
            data-failure-param-alert-classname="error">

            <input name="email" type="email" class="full-width" autocomplete="email" placeholder="<?php echo $locale->getText("home.auth.signin.input-email-placeholder"); ?>" required>

            <input name="password" type="password" class="full-width" autocomplete="off" placeholder="<?php echo $locale->getText("home.auth.signin.input-password-placeholder"); ?>" required pattern=".{6,}" title="<?php echo $locale->getText("home.auth.signin.input-password-error"); ?>">

            <button><?php echo $locale->getText("home.auth.signin.submit-button"); ?></button>
        </form>
        
        <br />
        <br />

        <div class="text-line-high-large text-align-center">
            <a href="/auth/recovery"><?php echo $locale->getText("home.auth.signin.forgot-password-chunk1"); ?></a><?php if(!$root): ?> <?php echo $locale->getText("home.auth.signin.forgot-password-chunk2"); ?> <b><a href="/auth/signup"><?php echo $locale->getText("home.auth.signin.forgot-password-chunk3"); ?></a></b><?php endif; ?>
        </div>
    </div>
    
</div>