import {
  Cloud,
  Database,
  Megaphone,
  Server,
  Shield,
} from 'lucide-react'
import type { LaunchEventDay, LaunchEventScheduleItem } from './types'

export const INIT_JULY_2026_DAYS: LaunchEventDay[] = [
  {
    day: 1,
    dateLabel: 'JULY 6',
    weekdayLabel: 'MONDAY, JULY 6',
    title: 'Announcing Appwrite 2.0',
    description: 'The next chapter of Appwrite is here.',
    longDescription:
      'Meet Appwrite 2.0 — a refreshed platform experience, stronger foundations, and the start of everything we are shipping during Init week.',
    icon: Megaphone,
    visual: {
      imageSrcLight: '/images/init/appwrite-2-visual-light.jpg',
      imageSrcDark: '/images/init/appwrite-2-visual-dark.jpg',
      imageAlt: 'Appwrite 2.0 announcement visual with 3D 2.0 typography',
      aspectWidth: 1024,
      aspectHeight: 682,
    },
    isLive: true,
    sessionCount: 2,
    resources: [
      {
        id: 'day1-blog',
        typeLabel: 'Blog',
        title: 'Introducing Appwrite 2.0',
        href: 'https://appwrite.io/blog',
        actionLabel: 'Read article',
      },
      {
        id: 'day1-docs',
        typeLabel: 'Docs',
        title: 'Appwrite 2.0 overview',
        href: 'https://appwrite.io/docs',
        actionLabel: 'Visit docs',
      },
    ],
  },
  {
    day: 2,
    dateLabel: 'JULY 7',
    weekdayLabel: 'TUESDAY, JULY 7',
    title: 'DocumentsDB & VectorsDB',
    description: 'Documents and vectors in one database platform.',
    longDescription:
      'DocumentsDB and VectorsDB bring document and vector workloads together — build app data, search, and RAG on a unified database stack.',
    icon: Database,
    visual: {
      imageSrcLight: '/images/init/databases-visual-light.jpg',
      imageSrcDark: '/images/init/databases-visual-dark.jpg',
      imageAlt: 'DocumentsDB and VectorsDB visual showing document and vector data flow',
      aspectWidth: 1024,
      aspectHeight: 682,
    },
    sessionCount: 1,
    resources: [
      {
        id: 'day2-blog',
        typeLabel: 'Blog',
        title: 'DocumentsDB & VectorsDB',
        href: 'https://appwrite.io/blog',
        actionLabel: 'Read article',
      },
      {
        id: 'day2-docs',
        typeLabel: 'Docs',
        title: 'Databases documentation',
        href: 'https://appwrite.io/docs/products/databases',
        actionLabel: 'Visit docs',
      },
    ],
  },
  {
    day: 3,
    dateLabel: 'JULY 8',
    weekdayLabel: 'WEDNESDAY, JULY 8',
    title: 'Dedicated DBs',
    description: 'Dedicated database compute at a fixed price.',
    longDescription:
      'Get dedicated compute for your databases with predictable pricing — pay a fixed rate for CPU and memory, not just serverless bursts.',
    icon: Server,
    visual: {
      imageSrcLight: '/images/init/dedicated-dbs-visual-light.jpg',
      imageSrcDark: '/images/init/dedicated-dbs-visual-dark.jpg',
      imageAlt: 'Dedicated database servers visual with server racks',
      aspectWidth: 1024,
      aspectHeight: 682,
    },
    sessionCount: 2,
    resources: [
      {
        id: 'day3-blog',
        typeLabel: 'Blog',
        title: 'Dedicated database servers',
        href: 'https://appwrite.io/blog',
        actionLabel: 'Read article',
      },
      {
        id: 'day3-docs',
        typeLabel: 'Docs',
        title: 'Database compute',
        href: 'https://appwrite.io/docs/products/databases',
        actionLabel: 'Visit docs',
      },
    ],
  },
  {
    day: 4,
    dateLabel: 'JULY 9',
    weekdayLabel: 'THURSDAY, JULY 9',
    title: 'S3 support for Storage',
    description: 'Connect Appwrite Storage to your S3 buckets.',
    longDescription:
      'Appwrite Storage now supports S3 — use your own buckets, keep familiar workflows, and integrate object storage without rebuilding file pipelines.',
    icon: Cloud,
    visual: {
      imageSrcLight: '/images/init/s3-visual-light.jpg',
      imageSrcDark: '/images/init/s3-visual-dark.jpg',
      imageAlt: 'S3 support for Appwrite Storage visual with 3D S3 typography',
      aspectWidth: 1024,
      aspectHeight: 682,
    },
    sessionCount: 1,
    resources: [
      {
        id: 'day4-blog',
        typeLabel: 'Blog',
        title: 'S3 support for Appwrite Storage',
        href: 'https://appwrite.io/blog',
        actionLabel: 'Read article',
      },
      {
        id: 'day4-docs',
        typeLabel: 'Docs',
        title: 'Storage & S3',
        href: 'https://appwrite.io/docs/products/storage',
        actionLabel: 'Visit docs',
      },
    ],
  },
  {
    day: 5,
    dateLabel: 'JULY 10',
    weekdayLabel: 'FRIDAY, JULY 10',
    title: 'Appwrite Firewall',
    description: 'Network protection for your Appwrite projects.',
    longDescription:
      'Appwrite Firewall helps control what reaches your project — filter traffic, reduce abuse, and tighten what can access your APIs and services.',
    icon: Shield,
    visual: {
      imageSrcLight: '/images/init/firewall-visual-light.jpg',
      imageSrcDark: '/images/init/firewall-visual-dark.jpg',
      imageAlt: 'Appwrite Firewall visual showing filtered network traffic',
      aspectWidth: 1024,
      aspectHeight: 682,
    },
    sessionCount: 2,
    resources: [
      {
        id: 'day5-blog',
        typeLabel: 'Blog',
        title: 'Introducing Appwrite Firewall',
        href: 'https://appwrite.io/blog',
        actionLabel: 'Read article',
      },
      {
        id: 'day5-docs',
        typeLabel: 'Docs',
        title: 'Firewall documentation',
        href: 'https://appwrite.io/docs',
        actionLabel: 'Visit docs',
      },
    ],
  },
]

export const INIT_JULY_2026_SCHEDULE: LaunchEventScheduleItem[] = [
  {
    id: 'sched-keynote',
    day: 1,
    platform: 'youtube',
    title: 'Appwrite 2.0 launch stream',
    timeLabel: 'Live now',
    isLive: true,
  },
  {
    id: 'sched-discord-kickoff',
    day: 1,
    platform: 'discord',
    title: 'Appwrite 2.0 lounge',
    timeLabel: '11:00 AM',
    href: 'https://appwrite.io/discord',
  },
  {
    id: 'sched-reddit-ama',
    day: 1,
    platform: 'reddit',
    title: 'Appwrite 2.0 AMA',
    timeLabel: '2:00 PM',
    href: 'https://reddit.com/r/appwrite',
  },
  {
    id: 'sched-yt-databases',
    day: 2,
    platform: 'youtube',
    title: 'DocumentsDB & VectorsDB deep dive',
    timeLabel: '10:00 AM',
  },
  {
    id: 'sched-discord-databases',
    day: 2,
    platform: 'discord',
    title: 'Databases office hours',
    timeLabel: '3:00 PM',
    href: 'https://appwrite.io/discord',
  },
  {
    id: 'sched-yt-servers',
    day: 3,
    platform: 'youtube',
    title: 'Dedicated DBs deep dive',
    timeLabel: '10:00 AM',
  },
  {
    id: 'sched-discord-servers',
    day: 3,
    platform: 'discord',
    title: 'Database compute Q&A',
    timeLabel: '4:00 PM',
    href: 'https://appwrite.io/discord',
  },
  {
    id: 'sched-reddit-servers',
    day: 3,
    platform: 'reddit',
    title: 'Dedicated servers feedback',
    timeLabel: '6:00 PM',
    href: 'https://reddit.com/r/appwrite',
  },
  {
    id: 'sched-yt-s3',
    day: 4,
    platform: 'youtube',
    title: 'S3 for Appwrite Storage',
    timeLabel: '10:00 AM',
  },
  {
    id: 'sched-discord-s3',
    day: 4,
    platform: 'discord',
    title: 'Storage community hangout',
    timeLabel: '2:00 PM',
    href: 'https://appwrite.io/discord',
  },
  {
    id: 'sched-yt-firewall',
    day: 5,
    platform: 'youtube',
    title: 'Appwrite Firewall launch stream',
    timeLabel: '10:00 AM',
  },
  {
    id: 'sched-discord-closing',
    day: 5,
    platform: 'discord',
    title: 'Init closing party',
    timeLabel: '5:00 PM',
    href: 'https://appwrite.io/discord',
  },
  {
    id: 'sched-reddit-recap',
    day: 5,
    platform: 'reddit',
    title: 'Init week recap discussion',
    timeLabel: '7:00 PM',
    href: 'https://reddit.com/r/appwrite',
  },
]
