export const INIT_TICKET_SECTION_ID = 'ticket'
export const INIT_GLOBE_SECTION_ID = 'globe'
export const INIT_GET_INVOLVED_SECTION_ID = 'get-involved'
export const INIT_PRIZES_SECTION_ID = 'prizes'
export const INIT_RELEASE_AVAILABILITY_SECTION_ID = 'release-availability'
