import type { LaunchEventPrizes } from './types'

export const INIT_JULY_2026_PRIZES: LaunchEventPrizes = {
  sectionTitle: 'Prizes and giveaways',
  sectionDescription:
    'Daily swag on days 1–4. Share your ticket on social to enter the day 5 grand prize.',
  dailyHeading: 'Daily swag giveaways',
  dailyPrizeLabel: 'Appwrite Init swag',
  grandPrizeHeading: 'Grand prize',
  dailyGiveaways: [
    {
      day: 1,
      dateLabel: 'AUGUST 31',
      scheduleItemId: 'sched-reddit-ama',
      sessionTitle: 'Appwrite 2.0 AMA',
      platform: 'reddit',
      timeLabel: '2:00 PM',
      href: 'https://reddit.com/r/appwrite',
      prizeDescription: 'Appwrite hoodie and cap',
      visual: {
        imageAlt: 'Day 1 giveaway including an Appwrite hoodie and cap',
        imageSrcLight: '/images/init/prize-day-1-swag-light.jpg',
        imageSrcDark: '/images/init/prize-day-1-swag.jpg',
      },
    },
    {
      day: 2,
      dateLabel: 'SEPTEMBER 1',
      scheduleItemId: 'sched-reddit-databases-ama',
      sessionTitle: 'PostgreSQL AMA',
      platform: 'reddit',
      timeLabel: '3:00 PM',
      href: 'https://reddit.com/r/appwrite',
      prizeDescription: 'Light Appwriter keyboard',
      visual: {
        imageAlt: 'Day 2 giveaway including a light Appwriter keyboard',
        imageSrcLight: '/images/init/prize-day-2-swag-light.jpg',
        imageSrcDark: '/images/init/prize-day-2-swag.jpg',
      },
    },
    {
      day: 3,
      dateLabel: 'SEPTEMBER 2',
      scheduleItemId: 'sched-reddit-servers-ama',
      sessionTitle: 'VectorsDB, DocumentsDB & MySQL AMA',
      platform: 'reddit',
      timeLabel: '6:00 PM',
      href: 'https://reddit.com/r/appwrite',
      prizeDescription: 'Dark Appwriter keyboard',
      visual: {
        imageAlt: 'Day 3 giveaway including a dark Appwriter keyboard',
        imageSrcLight: '/images/init/prize-day-3-swag-light.jpg',
        imageSrcDark: '/images/init/prize-day-3-swag.jpg',
      },
    },
    {
      day: 4,
      dateLabel: 'SEPTEMBER 3',
      scheduleItemId: 'sched-reddit-s3-ama',
      sessionTitle: 'S3 for Storage AMA',
      platform: 'reddit',
      timeLabel: '2:00 PM',
      href: 'https://reddit.com/r/appwrite',
      prizeDescription: 'RUNTIME bottle and Appwrite tee',
      visual: {
        imageAlt: 'Day 4 giveaway including a RUNTIME water bottle and Appwrite tee',
        imageSrcLight: '/images/init/prize-day-4-swag-light.jpg',
        imageSrcDark: '/images/init/prize-day-4-swag.jpg',
      },
    },
  ],
  grandPrize: {
    day: 5,
    dateLabel: 'SEPTEMBER 4',
    scheduleItemId: 'sched-discord-closing',
    sessionTitle: 'Init closing party',
    platform: 'discord',
    timeLabel: '5:00 PM',
    href: '/discord',
    title: 'Claude Max 20x · 12 months free',
    description: 'Expanded Claude Code access for one winner.',
    eligibility: 'Share Init on social during the week to enter.',
    visual: {
      imageAlt: 'Claude Max 20x plan with a free 12-month subscription grand prize card',
      imageSrcLight: '/images/init/prize-grand-claude-max-light.jpg',
      imageSrcDark: '/images/init/prize-grand-claude-max.jpg',
    },
  },
}
