/**
 * Country names and extra city aliases for timezone search.
 * Keys are IANA zone ids. Values are English search terms (country, cities, abbreviations).
 */
export const TIMEZONE_SEARCH_ALIASES: Record<string, string[]> = {
  UTC: ['UTC', 'GMT', 'Zulu', 'Coordinated Universal Time'],
  'Africa/Cairo': ['Egypt', 'Cairo'],
  'Africa/Casablanca': ['Morocco', 'Casablanca'],
  'Africa/Johannesburg': ['South Africa', 'Johannesburg', 'Cape Town', 'Pretoria'],
  'Africa/Lagos': ['Nigeria', 'Lagos', 'Abuja'],
  'Africa/Nairobi': ['Kenya', 'Nairobi'],
  'America/Bogota': ['Colombia', 'Bogota'],
  'America/Buenos_Aires': ['Argentina', 'Buenos Aires'],
  'America/Caracas': ['Venezuela', 'Caracas'],
  'America/Chicago': [
    'United States',
    'USA',
    'US',
    'Chicago',
    'Austin',
    'Dallas',
    'Houston',
    'Minneapolis',
    'Central Time',
    'CT',
    'CST',
    'CDT',
  ],
  'America/Denver': [
    'United States',
    'USA',
    'US',
    'Denver',
    'Boulder',
    'Salt Lake City',
    'Mountain Time',
    'MT',
    'MST',
    'MDT',
  ],
  'America/Detroit': ['United States', 'USA', 'US', 'Detroit'],
  'America/Edmonton': ['Canada', 'Edmonton', 'Calgary'],
  'America/Halifax': ['Canada', 'Halifax'],
  'America/Indiana/Indianapolis': ['United States', 'USA', 'US', 'Indianapolis'],
  'America/Indianapolis': ['United States', 'USA', 'US', 'Indianapolis'],
  'America/Los_Angeles': [
    'United States',
    'USA',
    'US',
    'Los Angeles',
    'LA',
    'San Francisco',
    'SF',
    'Bay Area',
    'Silicon Valley',
    'Palo Alto',
    'Seattle',
    'Portland',
    'San Diego',
    'California',
    'Washington',
    'Oregon',
    'Pacific Time',
    'PT',
    'PST',
    'PDT',
  ],
  'America/Mexico_City': ['Mexico', 'Mexico City', 'CDMX'],
  'America/New_York': [
    'United States',
    'USA',
    'US',
    'New York',
    'NYC',
    'Boston',
    'Miami',
    'Atlanta',
    'Washington DC',
    'Philadelphia',
    'Eastern Time',
    'ET',
    'EST',
    'EDT',
  ],
  'America/Phoenix': ['United States', 'USA', 'US', 'Phoenix', 'Arizona'],
  'America/Santiago': ['Chile', 'Santiago'],
  'America/Sao_Paulo': ['Brazil', 'Sao Paulo', 'São Paulo', 'Rio de Janeiro'],
  'America/Toronto': ['Canada', 'Toronto', 'Ottawa', 'Montreal'],
  'America/Vancouver': ['Canada', 'Vancouver'],
  'Asia/Bangkok': ['Thailand', 'Bangkok'],
  'Asia/Calcutta': [
    'India',
    'Kolkata',
    'Calcutta',
    'Bengaluru',
    'Bangalore',
    'Mumbai',
    'Delhi',
    'Hyderabad',
    'Pune',
    'Chennai',
    'IST',
  ],
  'Asia/Kolkata': [
    'India',
    'Kolkata',
    'Calcutta',
    'Bengaluru',
    'Bangalore',
    'Mumbai',
    'Delhi',
    'Hyderabad',
    'Pune',
    'Chennai',
    'IST',
  ],
  'Asia/Dhaka': ['Bangladesh', 'Dhaka'],
  'Asia/Dubai': ['United Arab Emirates', 'UAE', 'Dubai', 'Abu Dhabi'],
  'Asia/Hong_Kong': ['Hong Kong', 'HK'],
  'Asia/Jakarta': ['Indonesia', 'Jakarta'],
  'Asia/Jerusalem': ['Israel', 'Jerusalem', 'Tel Aviv', 'TLV'],
  'Asia/Karachi': ['Pakistan', 'Karachi'],
  'Asia/Kuala_Lumpur': ['Malaysia', 'Kuala Lumpur', 'KL'],
  'Asia/Manila': ['Philippines', 'Manila'],
  'Asia/Qatar': ['Qatar', 'Doha'],
  'Asia/Riyadh': ['Saudi Arabia', 'Riyadh'],
  'Asia/Seoul': ['South Korea', 'Korea', 'Seoul'],
  'Asia/Shanghai': ['China', 'Shanghai', 'Beijing', 'Shenzhen'],
  'Asia/Singapore': ['Singapore', 'SG'],
  'Asia/Taipei': ['Taiwan', 'Taipei'],
  'Asia/Tokyo': ['Japan', 'Tokyo', 'Osaka', 'Kyoto', 'JST'],
  'Australia/Melbourne': ['Australia', 'Melbourne'],
  'Australia/Perth': ['Australia', 'Perth'],
  'Australia/Sydney': ['Australia', 'Sydney', 'Canberra'],
  'Europe/Amsterdam': ['Netherlands', 'Holland', 'Amsterdam'],
  'Europe/Athens': ['Greece', 'Athens'],
  'Europe/Belgrade': ['Serbia', 'Belgrade'],
  'Europe/Berlin': ['Germany', 'Berlin', 'Munich', 'Hamburg', 'Frankfurt'],
  'Europe/Brussels': ['Belgium', 'Brussels'],
  'Europe/Bucharest': ['Romania', 'Bucharest'],
  'Europe/Budapest': ['Hungary', 'Budapest'],
  'Europe/Copenhagen': ['Denmark', 'Copenhagen'],
  'Europe/Dublin': ['Ireland', 'Dublin'],
  'Europe/Helsinki': ['Finland', 'Helsinki'],
  'Europe/Istanbul': ['Turkey', 'Istanbul'],
  'Europe/Kiev': ['Ukraine', 'Kyiv', 'Kiev'],
  'Europe/Lisbon': ['Portugal', 'Lisbon'],
  'Europe/London': [
    'United Kingdom',
    'UK',
    'Great Britain',
    'England',
    'London',
    'Manchester',
    'Edinburgh',
    'GMT',
    'BST',
  ],
  'Europe/Madrid': ['Spain', 'Madrid', 'Barcelona'],
  'Europe/Moscow': ['Russia', 'Moscow'],
  'Europe/Oslo': ['Norway', 'Oslo'],
  'Europe/Paris': ['France', 'Paris'],
  'Europe/Prague': ['Czechia', 'Czech Republic', 'Prague'],
  'Europe/Rome': ['Italy', 'Rome', 'Milan'],
  'Europe/Stockholm': ['Sweden', 'Stockholm'],
  'Europe/Vienna': ['Austria', 'Vienna'],
  'Europe/Warsaw': ['Poland', 'Warsaw'],
  'Europe/Zurich': ['Switzerland', 'Zurich', 'Geneva'],
  'Pacific/Auckland': ['New Zealand', 'Auckland', 'Wellington'],
  'Pacific/Honolulu': ['United States', 'USA', 'US', 'Hawaii', 'Honolulu', 'HST'],
}

/**
 * Tech-hub timezones shown first. Order is the display order in the Popular group.
 * IDs must exist in the runtime IANA list (UTC is added even if missing).
 */
export const POPULAR_TECH_TIMEZONE_IDS: string[] = [
  'UTC',
  'America/Los_Angeles',
  'America/New_York',
  'America/Chicago',
  'America/Denver',
  'America/Toronto',
  'America/Sao_Paulo',
  'Europe/London',
  'Europe/Dublin',
  'Europe/Amsterdam',
  'Europe/Berlin',
  'Europe/Paris',
  'Europe/Zurich',
  'Europe/Stockholm',
  'Europe/Madrid',
  'Europe/Warsaw',
  'Asia/Jerusalem',
  'Asia/Dubai',
  'Asia/Kolkata',
  'Asia/Calcutta',
  'Asia/Singapore',
  'Asia/Shanghai',
  'Asia/Tokyo',
  'Asia/Seoul',
  'Asia/Hong_Kong',
  'Australia/Sydney',
  'Australia/Melbourne',
  'Pacific/Auckland',
]
