import { CONTACT_ENTERPRISE_URL } from './constants'
import { DATABASE_COMPUTE_CREDITS_NOTE } from '@/lib/database-create-pricing'
import type { PricingPlan } from './types'

export const pricingPlans: readonly PricingPlan[] = [
  {
    id: 'free',
    name: 'Free',
    price: '$0',
    description: 'A great fit for passion projects and small applications.',
    features: [
      '5GB bandwidth',
      '2GB storage',
      '750K executions',
      '75K monthly active users',
      'Community support',
      '1 Database, 1 Bucket, 2 Functions per project',
      '15-minute builds',
    ],
    footnote:
      'Free projects are paused after 1 week of inactivity. Limit of 2 projects.',
    cta: 'Start project',
    ctaVariant: 'outline',
    href: '/sign-up',
    internal: true,
  },
  {
    id: 'pro',
    name: 'Pro',
    price: '$25',
    pricePrefix: 'From',
    priceSuffix: '/month',
    description:
      'For production applications that need powerful functionality and resources to scale.',
    callout: DATABASE_COMPUTE_CREDITS_NOTE,
    featuresIntro: 'Dedicated resources per project:',
    features: [
      '2TB bandwidth',
      '150GB storage',
      '3.5M executions',
      '200K monthly active users',
      'Organization roles',
      'Email support',
      'Daily backups stored for 7 days',
      'Add-ons',
      'Unlimited Databases, Buckets, and Functions',
      '45-minute builds',
    ],
    cta: 'Start project',
    ctaVariant: 'brandCta',
    href: '/sign-up',
    internal: true,
    popular: true,
  },
  {
    id: 'enterprise',
    name: 'Enterprise',
    price: 'Custom',
    description:
      'For enterprises that need more power, premium support, and advanced security features.',
    featuresIntro: 'Everything in Pro, plus:',
    features: [
      'Uptime SLAs',
      'Success manager and 24/7 support on Slack',
      'Volume discounts',
      'Log drains',
      '90-day log retention',
      'Advanced observability',
      'Bring your own Cloud',
      'SOC-2, HIPAA, and BAA',
      'Custom organization roles',
      'Single Sign-On (SSO)',
      'Activity logs',
      'Custom backup policies',
    ],
    cta: 'Contact us',
    ctaVariant: 'outline',
    href: CONTACT_ENTERPRISE_URL,
    internal: true,
  },
]
