<?php
$code = $this->getParam('code', 500);
$errorID = $this->getParam('errorID', 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx');
$message = $this->getParam('message', '');
$projectName = $this->getParam('projectName', '');
$projectURL = $this->getParam('projectURL', '');
?>

<section class="zone large margin-top-xl">
    <h1 class="margin-bottom">Error <?= $code ?></h1>

    <p><?= $message ?></p>

    <small>Error ID: <?= $errorID ?></small>

    <?php if (!empty($projectURL)): ?>
        <hr class="margin-top margin-bottom" />

        <p><a href="<?= $this->escape($projectURL) ?>" rel="noopener">Back to <?= $projectName ?></a></p>
    <?php endif ?>
</section>
