name: Other
description: Use this for any other issues. Please do NOT create blank issues
title: "[OTHER]"
body:
  - type: markdown
    attributes:
      value: "# Other issue"
  - type: textarea
    id: issuedescription
    attributes:
      label: What would you like to share?
      description: Provide a clear and concise explanation of your issue.
    validations:
      required: true
  - type: textarea
    id: extrainfo
    attributes:
      label: Additional information
      description: Is there anything else we should know about this issue?
    validations:
      required: false
  - type: markdown
    attributes:
      value: |
        You can also join our Discord community [here](https://appwrite.io/discord)
        Feel free to check out other cool repositories of the appwrite [here](https://github.com/appwrite)
