<?php
$home = $this->getParam('home', '');
?>
<footer class="clear margin-top-xl">
    <ul class="copyright pull-start">
        <li>
            <a href="https://github.com/appwrite" target="_blank"><i class="icon-github-circled"></i> Github Repository</a>
        </li>
        <li>
            <a href="https://github.com/appwrite/appwrite/issues/new?body=%0A%0A%0A---%0AAppwrite Version:%20<?php echo VERSION; ?>" target="_blank">Open an Issue</a>
        </li>
        <li>
            <a href="<?php echo $home; ?>/docs" target="_blank">Documentation</a>
        </li>
        <li>
            v:<?php echo VERSION; ?>
        </li>
    </ul>
</footer>