<?php
$home = $this->getParam('home', '');
$version = $this->getParam('version', '') . '.' . APP_CACHE_BUSTER;
?>
<footer class="clear margin-top-large">
    <ul class="copyright pull-start">
        <li>
            <a class="link-animation-enabled"
                data-analytics
                data-analytics-event="click"
                data-analytics-category="console/footer"
                data-analytics-label="GitHub Link"
                href="https://github.com/appwrite/appwrite" target="_blank" rel="noopener"><i class="icon-github"></i> GitHub</a>
        </li>
        <li>
            <a class="link-animation-enabled"
                data-analytics
                data-analytics-event="click"
                data-analytics-category="console/footer"
                data-analytics-label="Discord Link"
                href="https://appwrite.io/discord" target="_blank" rel="noopener"><i class="icon-discord"></i> Discord</a>
        </li>
        <li>
            <a class="link-animation-enabled"
                data-analytics
                data-analytics-event="click"
                data-analytics-category="console/footer"
                data-analytics-label="New GitHub Issue"
                href="https://github.com/appwrite/appwrite/issues/new?assignees=&labels=bug&template=bug.yaml&title=[<?php echo $version; ?>]%20%F0%9F%90%9B+Bug+Report%3A+" target="_blank" rel="noopener">Open an Issue</a>
        </li>
        <li>
            <a class="link-animation-enabled"
                data-analytics
                data-analytics-event="click"
                data-analytics-category="console/footer"
                data-analytics-label="Docs Link"
                href="<?php echo $home; ?>/docs" target="_blank" rel="noopener">Docs</a>
        </li>
        <li>
            v:<?php echo $version; ?>
        </li>
    </ul>
</footer>
