<?php
use Utopia\Locale\Locale;
?>
<footer class="clear margin-top-xl">
    <ul class="copyright pull-start">
        <li>
            <a href="https://github.com/appwrite" target="_blank">Github Project</a>
        </li>
        <li>
            <a href="https://github.com/appwrite/appwrite/issues/new?body=%0A%0A%0A---%0AAppwrite Version:%20<?php echo VERSION; ?>" target="_blank">Open an Issue</a>
        </li>
        <li>
            <a href="https://appwrite.io/docs" target="_blank">Documentation</a>
        </li>
        <li>
            <?php echo VERSION; ?>
        </li>
    </ul>
</footer>