<?php
$locale = $this->getParam("locale");
/** @var Utopia\Locale\Locale $locale */
?>

<header class="clear" data-version>
    <a href="/console" class="logo pull-start">
        <img src="/images/appwrite.svg" alt="<?php echo $locale->getText("shared.header.alt-logo-light"); ?>" class="force-light" loading="lazy" />
        <img src="/images/appwrite-footer-dark.svg" alt="<?php echo $locale->getText("shared.header.alt-logo-dark"); ?>" class="force-dark" loading="lazy" />
    </a>

    <div class="change-project pull-start desktops-only">
        <div class="list project-only margin-end-small">
            <label class="margin-bottom-no">
                <select class="margin-bottom-no"
                    data-xanalytics-event="change"
                    data-xanalytics-category="console/header"
                    data-xanalytics-label="Project Switch"
                    data-switch
                    data-ls-bind="{{router.params.project}}"
                    data-unsync="1"
                    data-ls-loop="projects.projects" data-ls-as="option" aria-label="<?php echo $locale->getText("console.comps.header.label-project-switch"); ?>">
                    <option data-ls-attrs="value={{option.$id}}" data-ls-bind="{{option.name}}"></option>
                </select>
            </label>
        </div>

        <button style="overflow: visible;" class="project-only setup-new tooltip round down pull-end" aria-label="<?php echo $locale->getText("console.comps.header.label-quick-start"); ?>" data-tooltip="<?php echo $locale->getText("console.comps.header.label-project-new"); ?>"><i class="icon-plus"></i></button>
    </div>

    <div class="account-box pull-end"
        data-service="account.get"
        data-name="account"
        data-scope="console"
        data-event="load"
        data-success="trigger"
        data-success-param-trigger-events="account.get"
        data-failure="trigger"
        data-failure-param-trigger-events="account.deleteSession">

        <div class="console-back">
            <a href="/console" class="link-return-animation--end"><?php echo $locale->getText("console.comps.header.button.back-to-console"); ?> &nbsp;<i class="icon-right-open"></i></a>
        </div>

        <div class="account link pull-end clear">
            <img src="" data-ls-attrs="src={{account|avatar}}" alt="<?php echo $locale->getText("console.comps.header.alt-avatar-user"); ?>" class="avatar margin-start pull-end" />
            <span class="name pull-end desktops-only" data-ls-bind="{{account.name}}"></span>
        </div>

        <div class="console-index drop-list bottom end" data-ls-ui-open="" data-button-text="<?php echo $locale->getText("console.comps.header.label-account-options"); ?>" data-button-aria="" data-button-icon="" data-button-selector="[data-toggler]" data-button-class="account-button" data-blur="1">
            <ul class="margin-top-large arrow-end">
                <li>
                    <a href="/console/account"><i class="icon-user"></i> &nbsp; <?php echo $locale->getText("console.comps.header.options-your-account"); ?></a>
                </li>
                <li>
                    <span class="link"><i class="icon-sun-inv force-dark pull-start"></i><i class="icon-moon-inv force-light pull-start"></i> &nbsp; <?php echo $locale->getText("console.comps.header.options-change-theme"); ?>
                        <div class="pull-end switch-theme">
                            <button data-general-theme
                                data-analytics
                                data-analytics-event="click"
                                data-analytics-category="console/header"
                                data-analytics-label="Switch Theme">
                                <i class="icon-sun-inv force-light"></i>
                                <i class="icon-moon-inv force-dark"></i>
                            </button>
                        </div>    
                    </span>
                </li>
            </ul>
        </div>

    </div>

    <nav class="project-only" data-ls-ui-open="" data-button-class="round icon-btn phones-only tablets-only" data-button-aria="<?php echo $locale->getText("console.comps.header.label-menu"); ?>" data-button-icon="icon-dot-3">
        <a class="logo" href="/console"
            data-analytics
            data-analytics-event="click"
            data-analytics-category="console/navigation"
            data-analytics-label="Logo Link">
            <img src="/images/appwrite-nav.svg" loading="lazy" alt="<?php echo $locale->getText("shared.header.alt-logo"); ?>" class="nav" />

            <img src="/images/appwrite.svg" loading="lazy" alt="<?php echo $locale->getText("shared.header.alt-logo-light"); ?>" class="top force-light" loading="lazy" />
            <img src="/images/appwrite-footer-dark.svg" loading="lazy" alt="<?php echo $locale->getText("shared.header.alt-logo-dark"); ?>" class="top force-dark" loading="lazy" />
        </a>

        <div data-ui-highlight class="container">

            <ul class="links">
                <li>
                    <a data-ls-attrs="href=/console/home?project={{router.params.project}}"
                        data-analytics
                        data-analytics-event="click"
                        data-analytics-category="console/navigation"
                        data-analytics-label="Home Link">
                        <i class="icon-home"></i>
                        <?php echo $locale->getText("console.comps.header.menu-item-home"); ?>
                    </a>
                </li>
            </ul>

            <b class="subtitle"><?php echo $locale->getText("console.comps.header.menu-group-develop"); ?></b>

            <ul class="links">
                <li>
                    <a data-ls-attrs="href=/console/database?project={{router.params.project}}"
                        data-analytics
                        data-analytics-event="click"
                        data-analytics-category="console/navigation"
                        data-analytics-label="Database Link">
                        <i class="icon-database"></i>
                        <?php echo $locale->getText("console.comps.header.menu-item-database"); ?>
                    </a>
                </li>
                <li>
                    <a data-ls-attrs="href=/console/storage?project={{router.params.project}}"
                        data-analytics
                        data-analytics-event="click"
                        data-analytics-category="console/navigation"
                        data-analytics-label="Storage Link">
                        <i class="icon-folder"></i>
                        <?php echo $locale->getText("console.comps.header.menu-item-storage"); ?>
                    </a>
                </li>
                <li>
                    <a data-ls-attrs="href=/console/users?project={{router.params.project}}"
                        data-analytics
                        data-analytics-event="click"
                        data-analytics-category="console/navigation"
                        data-analytics-label="Users Link">
                        <i class="icon-users"></i>
                        <?php echo $locale->getText("console.comps.header.menu-item-users"); ?>
                    </a>
                </li>
                <li>
                    <a data-ls-attrs="href=/console/functions?project={{router.params.project}}"
                        data-analytics
                        data-analytics-event="click"
                        data-analytics-category="console/navigation"
                        data-analytics-label="Functions Link"
                        class="link-animation-disabled">
                        <i class="icon-lightning"></i>
                        <?php echo $locale->getText("console.comps.header.menu-item-functions"); ?>
                    </a>
                </li>
            </ul>

            <b class="subtitle"><?php echo $locale->getText("console.comps.header.menu-group-manage"); ?></b>

            <ul class="links">
                <li>
                    <a data-ls-attrs="href=/console/tasks?project={{router.params.project}}"
                        data-analytics
                        data-analytics-event="click"
                        data-analytics-category="console/navigation"
                        data-analytics-label="Tasks Link">
                        <i class="icon-clock"></i>
                        <?php echo $locale->getText("console.comps.header.menu-item-tasks"); ?>
                    </a>
                </li>
                <li>
                    <a data-ls-attrs="href=/console/webhooks?project={{router.params.project}}"
                        data-analytics
                        data-analytics-event="click"
                        data-analytics-category="console/navigation"
                        data-analytics-label="Webhooks Links">
                        <i class="icon-link"></i>
                        <?php echo $locale->getText("console.comps.header.menu-item-webhooks"); ?>
                    </a>
                </li>
                <li>
                    <a data-ls-attrs="href=/console/keys?project={{router.params.project}}"
                        data-analytics
                        data-analytics-event="click"
                        data-analytics-category="console/navigation"
                        data-analytics-label="API Keys Link">
                        <i class="icon-key-inv"></i>
                        <?php echo $locale->getText("console.comps.header.menu-item-api-keys"); ?>
                    </a>
                </li>
            </ul>
        </div>

        <ul class="links bottom">
            <li>
                <a data-ls-attrs="href=/console/settings?project={{router.params.project}}"
                    data-analytics
                    data-analytics-event="click"
                    data-analytics-category="console/navigation"
                    data-analytics-label="Settings Link">
                    <i class="icon-cog"></i> <?php echo $locale->getText("console.comps.header.menu-item-settings"); ?></a>
            </li>
        </ul>
    </nav>
</header>

<div class=""
    data-service="projects.list"
    data-event="load,projects.update"
    data-name="projects"
    data-scope="console"></div>

<div class="load-screen" data-ls-ui-loader>
    <div class="animation"><div></div><div></div><div></div><div></div></div>
    <img src="/images/appwrite.svg" alt="<?php echo $locale->getText("shared.header.alt-logo-light"); ?>" class="force-light" loading="lazy" />
    <img src="/images/appwrite-footer-dark.svg" alt="<?php echo $locale->getText("shared.header.alt-logo-dark"); ?>" class="force-dark" loading="lazy" />
</div>

<div data-ui-modal class="modal box close sticky-footer" data-button-alias=".setup-new" data-button-icon="icon-plus" data-button-class="project-only" data-open-event="create-project">
    <h1><?php echo $locale->getText("console.comps.header.modal-new-project-title"); ?></h1>

    <form
        data-setup
        data-analytics
        data-analytics-activity
        data-analytics-event="submit"
        data-analytics-category="console"
        data-analytics-label="Create Project">
        <p><?php echo $locale->getText("console.comps.header.modal-new-project-description"); ?></p>

        <label><?php echo $locale->getText("console.comps.header.modal-new-project-input-label-name"); ?></label>
        <input type="text" class="full-width margin-bottom-xl" name="name" required autocomplete="off" maxlength="128" />

        <footer>
            <button type="submit"><?php echo $locale->getText("console.comps.header.modal-new-project-button-submit"); ?></button> &nbsp; <button data-ui-modal-close="" type="button" class="reverse"><?php echo $locale->getText("console.comps.header.modal-new-project-button-cancel"); ?></button>
        </footer>
    </form>
</div>
