<?php
$scopes = $this->getParam('scopes', []);
?>
<div class="cover margin-bottom-large">
    <h1 class="zone xl margin-bottom-large">
        <a data-ls-attrs="href=/console/home?project={{router.params.project}}" class="back text-size-small link-return-animation--start"><i class="icon-left-open"></i> Home</a>
        <br />

        <span>API Keys</span>
    </h1>
</div>
<div class="zone xl"
    data-service="projects.listKeys"
    data-scope="console"
    data-event="load,projects.createKey,projects.updateKey,projects.deleteKey"
    data-name="console-keys"
    data-param-project-id="{{router.params.project}}"
    data-success="trigger"
    data-success-param-trigger-events="projects.listKeys">

    <div data-ls-if="0 == {{console-keys.sum}} || undefined == {{console-keys.sum}}" class="box margin-top margin-bottom">
        <h3 class="margin-bottom-small text-bold">No API Keys Found</h3>

        <p class="margin-bottom-no">You haven't created any API keys for your project yet.</p>
    </div>

    <div class="box margin-bottom" data-ls-if="0 != {{console-keys.sum}}">
        <ul data-ls-loop="console-keys.keys" data-ls-as="key" class="list">
            <li class="clear">
                <div data-ui-modal class="modal box close" data-button-alias="none" data-open-event="key-update-{{key.$id}}">
                    <button type="button" class="close pull-end" data-ui-modal-close=""><i class="icon-cancel"></i></button>

                    <h1>Update API Key</h1>

                    <form
                        data-analytics
                        data-analytics-activity
                        data-analytics-event="submit"
                        data-analytics-category="console"
                        data-analytics-label="Update Project Key"
                        data-service="projects.updateKey"
                        data-scope="console"
                        data-event="submit"
                        data-success="alert,trigger"
                        data-success-param-alert-text="Updated API key successfully"
                        data-success-param-trigger-events="projects.updateKey"
                        data-failure="alert"
                        data-failure-param-alert-text="Failed to update API key"
                        data-failure-param-alert-classname="error">

                        <input type="hidden" name="projectId" data-ls-bind="{{router.params.project}}" />
                        <input type="hidden" name="keyId" data-ls-bind="{{key.$id}}" />

                        <label data-ls-attrs="for=name-{{key.$id}}">Name <span class="tooltip large" data-tooltip="Choose any name that will help you distinguish between your different API keys."><i class="icon-question"></i></span></label>
                        <input type="text" class="full-width" data-ls-attrs="id=name-{{key.$id}}" name="name" required autocomplete="off" data-ls-bind="{{key.name}}" maxlength="128" />

                        <section data-forms-select-all>
                            <label data-ls-attrs="for=scopes-{{key.$id}}">Scopes (<a data-ls-attrs="href={{env.HOME}}/docs/keys" target="_blank" rel="noopener">Learn more</a>)</label>
                            <div class="row responsive thin">
                                <?php foreach ($scopes as $i => $scope) : ?>
                                    <div class="col span-6 text-one-liner margin-bottom text-height-large text-size-small" title="<?php echo $scope; ?>">
                                        <input data-ls-attrs="id=scope-<?php echo $scope; ?>" type="checkbox" name="scopes" data-ls-bind="{{key.scopes}}" value="<?php echo $scope; ?>" />
                                        &nbsp;
                                        <label class="inline" for="scope-<?php echo $scope; ?>"><?php echo $scope; ?></label>
                                    </div>
                                    <?php if (($i + 1) % 2 === 0) : ?>
                                    </div>
                                    <div class="row responsive thin">
                                    <?php endif; ?>
    
                                <?php endforeach; ?>
                            </div>
                        </section>

                        <hr class="margin-top-no" />

                        <button type="submit">Save</button> &nbsp; <button data-ui-modal-close="" type="button" class="reverse">Cancel</button>
                    </form>
                </div>

                <form class="pull-end margin-end"
                    data-analytics
                    data-analytics-activity
                    data-analytics-event="submit"
                    data-analytics-category="console"
                    data-analytics-label="Delete Project Key"
                    data-service="projects.deleteKey"
                    data-scope="console"
                    data-event="key-delete-{{key.$id}}"
                    data-confirm="Are you sure you want to delete this API key?"
                    data-success="alert,trigger"
                    data-success-param-alert-text="Deleted API key successfully"
                    data-success-param-trigger-events="projects.deleteKey"
                    data-failure="alert"
                    data-failure-param-alert-text="Failed to delete API key"
                    data-failure-param-alert-classname="error">

                    <input type="hidden" name="projectId" data-ls-bind="{{router.params.project}}" />
                    <input type="hidden" name="keyId" data-ls-bind="{{key.$id}}" />
                </form>

                <button class="pull-end desktops-only margin-start-small" data-ls-ui-trigger="key-update-{{key.$id}}">Update</button>
                <button class="pull-end reverse desktops-only margin-small" data-ls-ui-trigger="key-delete-{{key.$id}}">Delete</button>

                <div class="margin-bottom-tiny"><span data-ls-bind="{{key.name}}"></span> <small>(<span data-ls-bind="{{key.scopes.length}}"></span> scopes granted)</small></div>

                <div class="clear">
                    <div data-ui-modal class="modal box close" data-button-text="Show Secret" data-button-class="link pull-start margin-end-small margin-top-tiny">
                        <button type="button" class="close pull-end" data-ui-modal-close=""><i class="icon-cancel"></i></button>

                        <h1>API Key Secret</h1>

                        <form>
                            <div class="input-copy">
                                <textarea disabled style="height: 130px; line-height: 26px" data-forms-copy data-ls-bind="{{key.secret}}"></textarea>
                            </div>
                            
                            <hr />

                            <div>
                                <button data-ui-modal-close="" type="button" class="reverse">Cancel</button>
                            </div>
                        </form>
                    </div>

                    <button class="link pull-start tablets-only phones-only margin-end-small margin-top-tiny" data-ls-ui-trigger="key-update-{{key.$id}}">Update</button>
                    <button class="link pull-start tablets-only phones-only margin-end-small margin-top-tiny text-danger" data-ls-ui-trigger="key-delete-{{key.$id}}">Delete</button>
                </div>
            </li>
        </ul>
    </div>

    <div class="clear">
        <div data-ui-modal class="modal box close" data-button-text="Add API Key">
            <button type="button" class="close pull-end" data-ui-modal-close=""><i class="icon-cancel"></i></button>

            <h1>Add API Keys</h1>

            <form
                data-analytics
                data-analytics-activity
                data-analytics-event="submit"
                data-analytics-category="console"
                data-analytics-label="Create Project Key"
                data-service="projects.createKey"
                data-scope="console"
                data-event="submit"
                data-success="alert,trigger,reset"
                data-success-param-alert-text="Created API key successfully"
                data-success-param-trigger-events="projects.createKey"
                data-failure="alert"
                data-failure-param-alert-text="Failed to create API key"
                data-failure-param-alert-classname="error">

                <input type="hidden" name="projectId" data-ls-bind="{{router.params.project}}" />

                <label for="name">Name <span class="tooltip large" data-tooltip="Choose any name that will help you distinguish between your different API keys."><i class="icon-question"></i></span></label>
                <input type="text" class="full-width" id="name" name="name" required autocomplete="off" maxlength="128" />

                <label for="keyId">Key ID <span class="tooltip large" data-tooltip="Choose any name that will help you distinguish between your different API keys."><i class="icon-question"></i></span></label>
                <input
                    type="hidden"
                    data-custom-id
                    id-type="auto"
                    required
                    maxlength="36"
                    name="keyId" />

                <section data-forms-select-all>
                    <label for="scopes">Scopes (<a data-ls-attrs="href={{env.HOME}}/docs/keys" target="_blank" rel="noopener">Learn more</a>)</label>
                    <div class="row responsive thin">
                        <?php foreach ($scopes as $i => $scope) : ?>
                            <div class="col span-6 text-one-liner margin-bottom text-height-large text-size-small" title="<?php echo $scope; ?>">
                                <input type="checkbox" name="scopes" id="<?php echo $scope; ?>" value="<?php echo $scope; ?>" /> 
                                &nbsp; 
                                <label class="inline" for="<?php echo $scope; ?>"><?php echo $scope; ?></label>
                            </div>
                            <?php if (($i + 1) % 2 === 0) : ?>
                            </div>
                            <div class="row responsive thin">
                            <?php endif; ?>

                        <?php endforeach; ?>
                    </div>
                </section>

                <hr class="margin-top-no" />

                <button type="submit">Create</button> &nbsp; <button data-ui-modal-close="" type="button" class="reverse">Cancel</button>
            </form>
        </div>
    </div>
</div>
