<?php
$scopes = $this->getParam('scopes', []);

$locale = $this->getParam("locale");
/** @var Utopia\Locale\Locale $locale */

?>
<div class="cover margin-bottom-large">
    <h1 class="zone xl margin-bottom-large">
        <a data-ls-attrs="href=/console/home?project={{router.params.project}}" class="back text-size-small link-return-animation--start"><i class="icon-left-open"></i> <?php echo $locale->getText('console.shared-button-back-to-home'); ?></a>
        <br />

        <span><?php echo $locale->getText('console.keys.index.title'); ?></span>
    </h1>
</div>
<div class="zone xl"
    data-service="projects.listKeys"
    data-scope="console"
    data-event="load,projects.createKey,projects.updateKey,projects.deleteKey"
    data-name="console-keys"
    data-param-project-id="{{router.params.project}}"
    data-success="trigger"
    data-success-param-trigger-events="projects.listKeys">

    <div data-ls-if="0 == {{console-keys.sum}} || undefined == {{console-keys.sum}}" class="box margin-top margin-bottom">
        <h3 class="margin-bottom-small text-bold"><?php echo $locale->getText('console.keys.index.no-keys-title'); ?></h3>

        <p class="margin-bottom-no"><?php echo $locale->getText('console.keys.index.no-keys-description'); ?></p>
    </div>

    <div class="box margin-bottom" data-ls-if="0 != {{console-keys.sum}}">
        <ul data-ls-loop="console-keys.keys" data-ls-as="key" class="list">
            <li class="clear">
                <div data-ui-modal class="modal box close" data-button-alias="none" data-open-event="key-update-{{key.$id}}">
                    <button type="button" class="close pull-end" data-ui-modal-close=""><i class="icon-cancel"></i></button>

                    <h1><?php echo $locale->getText('console.keys.index.update-title'); ?></h1>

                    <form
                        data-analytics
                        data-analytics-activity
                        data-analytics-event="submit"
                        data-analytics-category="console"
                        data-analytics-label="Update Project Key"
                        data-service="projects.updateKey"
                        data-scope="console"
                        data-event="submit"
                        data-success="alert,trigger"
                        data-success-param-alert-text="<?php echo $locale->getText('console.keys.index.update-submit-error'); ?>"
                        data-success-param-trigger-events="projects.updateKey"
                        data-failure="alert"
                        data-failure-param-alert-text="<?php echo $locale->getText('console.keys.index.update-submit-success'); ?>"
                        data-failure-param-alert-classname="error">

                        <input type="hidden" name="projectId" data-ls-bind="{{router.params.project}}" />
                        <input type="hidden" name="keyId" data-ls-bind="{{key.$id}}" />

                        <label data-ls-attrs="for=name-{{key.$id}}"><?php echo $locale->getText('console.keys.index.update-label-name'); ?> <span class="tooltip large" data-tooltip="<?php echo $locale->getText('console.keys.index.update-tooltip-name'); ?>"><i class="icon-question"></i></span></label>
                        <input type="text" class="full-width" data-ls-attrs="id=name-{{key.$id}}" name="name" required autocomplete="off" data-ls-bind="{{key.name}}" maxlength="128" />

                        <section data-forms-select-all data-forms-select-all-text="<?php echo $locale->getText('shared.select-all'); ?>" data-forms-unselect-all-text="<?php echo $locale->getText('shared.unselect-all'); ?>">
                            <label data-ls-attrs="for=scopes-{{key.$id}}"><?php echo $locale->getText('console.keys.index.shared-label-scopes'); ?> (<a data-ls-attrs="href={{env.HOME}}/docs/keys" target="_blank" rel="noopener"><?php echo $locale->getText('shared.learn-more'); ?></a>)</label>
                            <div class="row responsive thin">
                                <?php foreach ($scopes as $i => $scope) : ?>
                                    <div class="col span-6 text-one-liner margin-bottom text-height-large text-size-small" title="<?php echo $scope; ?>">
                                        <input data-ls-attrs="id=scope-<?php echo $scope; ?>" type="checkbox" name="scopes" data-ls-bind="{{key.scopes}}" value="<?php echo $scope; ?>" />
                                        &nbsp;
                                        <label class="inline" for="scope-<?php echo $scope; ?>"><?php echo $scope; ?></label>
                                    </div>
                                    <?php if (($i + 1) % 2 === 0) : ?>
                                    </div>
                                    <div class="row responsive thin">
                                    <?php endif; ?>
    
                                <?php endforeach; ?>
                            </div>
                        </section>

                        <hr class="margin-top-no" />

                        <button type="submit"><?php echo $locale->getText('console.keys.index.update-button-submit'); ?></button> &nbsp; <button data-ui-modal-close="" type="button" class="reverse"><?php echo $locale->getText('console.keys.index.update-button-cancel'); ?></button>
                    </form>
                </div>

                <form class="pull-end margin-end"
                    data-analytics
                    data-analytics-activity
                    data-analytics-event="submit"
                    data-analytics-category="console"
                    data-analytics-label="Delete Project Key"
                    data-service="projects.deleteKey"
                    data-scope="console"
                    data-event="key-delete-{{key.$id}}"
                    data-confirm="<?php echo $locale->getText('console.keys.index.delete-submit-confirm'); ?>"
                    data-success="alert,trigger"
                    data-success-param-alert-text="<?php echo $locale->getText('console.keys.index.delete-submit-success'); ?>"
                    data-success-param-trigger-events="projects.deleteKey"
                    data-failure="alert"
                    data-failure-param-alert-text="<?php echo $locale->getText('console.keys.index.delete-submit-error'); ?>"
                    data-failure-param-alert-classname="error">

                    <input type="hidden" name="projectId" data-ls-bind="{{router.params.project}}" />
                    <input type="hidden" name="keyId" data-ls-bind="{{key.$id}}" />
                </form>

                <button class="pull-end desktops-only margin-start-small" data-ls-ui-trigger="key-update-{{key.$id}}"><?php echo $locale->getText('console.keys.index.update-button-modal'); ?></button>
                <button class="pull-end reverse desktops-only margin-small" data-ls-ui-trigger="key-delete-{{key.$id}}"><?php echo $locale->getText('console.keys.index.delete-button-modal'); ?></button>

                <div class="margin-bottom-tiny"><span data-ls-bind="{{key.name}}"></span> <small>(<span data-ls-bind="{{key.scopes.length}}"></span> <?php echo $locale->getText('console.keys.index.scopes-info'); ?>)</small></div>

                <div class="clear">
                    <div data-ui-modal class="modal box close" data-button-text="<?php echo $locale->getText('console.keys.index.button-show-secret'); ?>" data-button-class="link pull-start margin-end-small margin-top-tiny">
                        <button type="button" class="close pull-end" data-ui-modal-close=""><i class="icon-cancel"></i></button>

                        <h1><?php echo $locale->getText('console.keys.index.secret-title'); ?></h1>

                        <form>
                            <div class="input-copy">
                                <textarea disabled style="height: 130px; line-height: 26px" data-forms-copy data-ls-bind="{{key.secret}}"></textarea>
                            </div>
                            
                            <hr />

                            <div>
                                <button data-ui-modal-close="" type="button" class="reverse"><?php echo $locale->getText('console.keys.index.secret-button-cancel'); ?></button>
                            </div>
                        </form>
                    </div>

                    <button class="link pull-start tablets-only phones-only margin-end-small margin-top-tiny" data-ls-ui-trigger="key-update-{{key.$id}}">Update</button>
                    <button class="link pull-start tablets-only phones-only margin-end-small margin-top-tiny text-danger" data-ls-ui-trigger="key-delete-{{key.$id}}">Delete</button>
                </div>
            </li>
        </ul>
    </div>

    <div class="clear">
        <div data-ui-modal class="modal box close" data-button-text="<?php echo $locale->getText('console.keys.index.add-key-modal-title'); ?>">
            <button type="button" class="close pull-end" data-ui-modal-close=""><i class="icon-cancel"></i></button>

            <h1><?php echo $locale->getText('console.keys.index.add-key-button'); ?></h1>

            <form
                data-analytics
                data-analytics-activity
                data-analytics-event="submit"
                data-analytics-category="console"
                data-analytics-label="Create Project Key"
                data-service="projects.createKey"
                data-scope="console"
                data-event="submit"
                data-success="alert,trigger,reset"
                data-success-param-alert-text="<?php echo $locale->getText('console.keys.index.add-key-submit-success'); ?>"
                data-success-param-trigger-events="projects.createKey"
                data-failure="alert"
                data-failure-param-alert-text="<?php echo $locale->getText('console.keys.index.add-key-submit-error'); ?>"
                data-failure-param-alert-classname="error">

                <input type="hidden" name="projectId" data-ls-bind="{{router.params.project}}" />

                <label for="name"><?php echo $locale->getText('console.keys.index.add-key-label-name'); ?> <span class="tooltip large" data-tooltip="<?php echo $locale->getText('console.keys.index.add-key-label-name-tooltip'); ?>"><i class="icon-question"></i></span></label>
                <input type="text" class="full-width" id="name" name="name" required autocomplete="off" maxlength="128" />

                <section data-forms-select-all data-forms-select-all-text="<?php echo $locale->getText('shared.select-all'); ?>" data-forms-unselect-all-text="<?php echo $locale->getText('shared.unselect-all'); ?>">
                    <label for="scopes"><?php echo $locale->getText('console.keys.index.shared-label-scopes'); ?> (<a data-ls-attrs="href={{env.HOME}}/docs/keys" target="_blank" rel="noopener"><?php echo $locale->getText('shared.learn-more'); ?></a>)</label>
                    <div class="row responsive thin">
                        <?php foreach ($scopes as $i => $scope) : ?>
                            <div class="col span-6 text-one-liner margin-bottom text-height-large text-size-small" title="<?php echo $scope; ?>">
                                <input type="checkbox" name="scopes" id="<?php echo $scope; ?>" value="<?php echo $scope; ?>" /> 
                                &nbsp; 
                                <label class="inline" for="<?php echo $scope; ?>"><?php echo $scope; ?></label>
                            </div>
                            <?php if (($i + 1) % 2 === 0) : ?>
                            </div>
                            <div class="row responsive thin">
                            <?php endif; ?>

                        <?php endforeach; ?>
                    </div>
                </section>

                <hr class="margin-top-no" />

                <button type="submit"><?php echo $locale->getText('console.keys.index.add-key-button-submit'); ?></button> &nbsp; <button data-ui-modal-close="" type="button" class="reverse"><?php echo $locale->getText('console.keys.index.add-key-button-cancel'); ?></button>
            </form>
        </div>
    </div>
</div>
