<div
    data-service="teams.get"
    data-name="team"
    data-event="load,teams.update"
    data-param-team-id="{{router.params.id}}"
    data-success="trigger"
    data-success-param-trigger-events="teams.get">

    <div class="cover">
        <h1 class="zone xl margin-bottom-large">
            <a data-ls-attrs="href=/console/users/teams?project={{router.params.project}}" class="back text-size-small"><i class="icon-left-open"></i> Teams</a>
            <br />

            <span data-ls-bind="{{team.name}}">&nbsp;</span>
            <span data-ls-if="{{team.name}} === ''">Unknown</span>
        </h1>
    </div>

    <div data-ui-modal class="modal width-large box close" data-button-hide="on" data-open-event="open-json">
        <button type="button" class="close pull-end" data-ui-modal-close=""><i class="icon-cancel"></i></button>    
        
        <h2>JSON View</h2>

        <div class="margin-bottom">
            <input type="hidden" data-ls-bind="{{team}}" data-forms-code />
        </div>

        <button data-ui-modal-close="" type="button" class="reverse">Cancel</button>
    </div>

    <div class="zone xl">
        <ul class="phases clear" data-ui-phases data-selected="{{router.params.tab}}">
            <li data-state="/console/users/teams/team?id={{router.params.id}}&project={{router.params.project}}">
                <h2>General</h2>
                
                <div class="row responsive margin-top-negative">
                    <div class="col span-8">
                        <label>&nbsp;</label>

                        <div class="box margin-bottom-large">
                            <form
                                data-analytics-event="submit"
                                data-analytics-category="console"
                                data-analytics-label="Update Team"
                                data-service="teams.update"
                                data-scope="sdk"
                                data-event="submit"
                                data-success="alert,trigger"
                                data-success-param-alert-text="Updated team successfully"
                                data-success-param-trigger-events="teams.update"
                                data-failure="alert"
                                data-failure-param-alert-text="Failed to update team"
                                data-failure-param-alert-classname="error">

                                <input data-ls-attrs="id=team-id-{{team.$id}}" name="teamId" type="hidden" disabled data-ls-bind="{{team.$id}}" />

                                <label for="name">Name</label>
                                <input data-ls-attrs="id=team-name-{{team.$id}}" name="name" type="text" autocomplete="off" data-ls-bind="{{team.name}}">

                                <hr />

                                <button>Update</button>
                            </form>
                        </div>

                        <h3 class="margin-bottom">Members</h3>

                        <div
                            data-service="teams.getMemberships"
                            data-event="load,teams.create,teams.update,teams.delete"
                            data-param-team-id="{{router.params.id}}"
                            data-param-limit="<?php echo APP_PAGING_LIMIT; ?>"
                            data-param-offset="{{router.params.offset}}"
                            data-param-order-type="DESC"
                            data-scope="sdk"
                            data-name="project-teams">

                            <div data-ls-if="0 == {{project-teams.sum}}" class="box margin-bottom">
                                <h3 class="margin-bottom-small text-bold">No Memberships Found</h3>

                                <p class="margin-bottom-no">Create your first team member to get started</p>
                            </div>

                            <div data-ls-if="0 != {{project-teams.sum}}">
                                <div class="margin-bottom-small margin-end-small text-align-end text-size-small"><span data-ls-bind="{{project-teams.sum}}"></span> results found</div>

                                <div class="box margin-bottom margin-top-negative">
                                    <table class="vertical">
                                        <thead>
                                            <tr>
                                                <th width="40"></th>
                                                <th>Name</th>
                                                <th width="150">Members</th>
                                                <th width="150">Created</th>
                                            </tr>
                                        </thead>
                                        <tbody data-ls-loop="project-teams.teams" data-ls-as="team">
                                            <tr>
                                                <td class="hide">
                                                    <img src="" data-ls-attrs="src={{team.name|gravatar}}" data-size="45" alt="Collection Avatar" class="avatar margin-end pull-start" loading="lazy" width="30" height="30" />
                                                </td>
                                                <td data-title="Name: ">
                                                    <a data-ls-attrs="href=/console/users/teams/team?id={{team.$id}}&project={{router.params.project}}" data-ls-bind="{{team.name}}"></a>
                                                </td>
                                                <td data-title="Members: "><span data-ls-bind="{{team.sum}} members"></span></td>
                                                <td data-title="Date Created: "><small data-ls-bind="{{team.dateCreated|date-text}}"></small></td>
                                            </tr>
                                        </tbody>
                                    </table>
                                </div>
                            </div>

                            <div class="clear text-align-center paging">
                                <form
                                    data-service="teams.list"
                                    data-event="submit"
                                    data-param-search="{{router.params.search}}"
                                    data-param-limit="<?php echo APP_PAGING_LIMIT; ?>"
                                    data-param-order-type="DESC"
                                    data-scope="sdk"
                                    data-name="project-teams"
                                    data-success="state"
                                    data-success-param-state-keys="search,offset">
                                    <button name="offset" data-paging-back data-offset="{{router.params.offset}}" data-sum="{{project-teams.sum}}" class="margin-end round small" aria-label="Back"><i class="icon-left-open"></i></button>
                                </form>

                                <span data-ls-bind="{{router.params.offset|pageCurrent}} / {{project-teams.sum|pageTotal}}"></span>

                                <form
                                    data-service="teams.list"
                                    data-event="submit"
                                    data-param-search="{{router.params.search}}"
                                    data-param-limit="<?php echo APP_PAGING_LIMIT; ?>"
                                    data-param-order-type="DESC"
                                    data-scope="sdk"
                                    data-name="project-teams"
                                    data-success="state"
                                    data-success-param-state-keys="search,offset">
                                    <button name="offset" data-paging-next data-offset="{{router.params.offset}}" data-sum="{{project-teams.sum}}" class="margin-start round small" aria-label="Next"><i class="icon-right-open"></i></button>
                                </form>
                            </div>
                        </div>
                    </div>
                    <div class="col span-4 sticky-top">
                        <label>Team ID</label>
                        <div class="input-copy margin-bottom">
                            <input id="uid" type="text" autocomplete="off" placeholder="" data-ls-bind="{{team.$id}}" disabled data-forms-copy>
                        </div>

                        <ul class="margin-bottom-large text-fade text-size-small">
                            <li class="margin-bottom-small"><i class="icon-angle-circled-right margin-start-tiny margin-end-tiny"></i> <button data-ls-ui-trigger="open-json" class="link text-size-small">View as JSON</button></li>
                            <li class="margin-bottom-small"><i class="icon-angle-circled-right margin-start-tiny margin-end-tiny"></i> Created: <span data-ls-bind="{{team.dateCreated|date-text}}"></span></li>
                        </ul>

                        <form name="teams.delete" class="margin-bottom"
                            data-analytics-event="submit"
                            data-analytics-category="console"
                            data-analytics-label="Delete Team"
                            data-service="teams.delete"
                            data-event="submit"
                            data-confirm="Are you sure you want to delete this team?"
                            data-param-team-id="{{router.params.id}}"
                            data-success="alert,trigger,redirect"
                            data-success-param-alert-text="Team deleted successfully"
                            data-success-param-trigger-events="users.update"
                            data-success-param-redirect-url="/console/users/teams?project={{router.params.project}}"
                            data-failure="alert"
                            data-failure-param-alert-text="Failed to delete team"
                            data-failure-param-alert-classname="error">

                            <button type="submit" class="danger fill">Delete Team</button>
                        </form>
                    </div>
                </div>
            </li>
            
        </ul>
    </div>
</div>