<?php
$locale = $this->getParam("locale");
/** @var Utopia\Locale\Locale $locale */
?>

<div class="zone medium">
    <h1 class="zone xl margin-bottom margin-top">
        <?php echo $locale->getText('home.auth.recovery.reset.title'); ?>
    </h1>

    <small class="pull-end text-size-small"><?php echo $locale->getText('shared.fields-required-info'); ?></small>

    <br />
    <br />

    <form name="recovery-reset"
        data-analytics
        data-analytics-activity
        data-analytics-event="submit"
        data-analytics-category="home"
        data-analytics-label="Update Account Recovery"
        data-service="account.updateRecovery"
        data-scope="console"
        data-event="submit"
        data-success="alert,redirect"
        data-success-param-alert="<?php echo $locale->getText('home.auth.recovery.reset.submit-success'); ?>"
        data-success-param-url="/auth/signin"
        data-failure="alert"
        data-failure-param-alert-text="<?php echo $locale->getText('home.auth.recovery.reset.submit-error'); ?>"
        data-failure-param-alert-classname="error">

        <input type="hidden" name="userId" data-ls-bind="{{router.params.userId}}">
        <input type="hidden" name="secret" data-ls-bind="{{router.params.secret}}">

        <label><?php echo $locale->getText('shared.label-password'); ?></label>
        <input name="password" type="password" autocomplete="off" placeholder="" required data-forms-password-meter pattern=".{6,}" title="<?php echo $locale->getText('shared.input-password-error'); ?>">

        <label><?php echo $locale->getText('home.auth.recovery.reset-label-password-confirm'); ?></label>
        <input name="passwordAgain" type="password" autocomplete="off" placeholder="" required data-forms-password-meter pattern=".{6,}" title="<?php echo $locale->getText('shared.input-password-error'); ?>">

        <button type="submit" class="btn btn-primary"><i class="fa fa-sign-in"></i><?php echo $locale->getText('home.auth.recovery.reset.button-submit'); ?></button>
    </form>
</div>
