<?php
use Utopia\Locale\Locale;
?>
<div class="zone medium">
    <h1 class="zone xl margin-bottom margin-top">
        <?php echo $this->escape(Locale::getText('home.auth.reset.title')); ?>
    </h1>

    <small class="pull-end">* <?php echo $this->escape(Locale::getText('home.auth.reset.required')); ?></small>

    <br />
    <br />

    <form name="recovery-reset"
          data-appwrite="auth.recoveryReset"
          data-scope="console"
          data-event="submit"
          data-success="alert,redirect"
          data-success-alert="<?php echo $this->escape(Locale::getText('home.auth.reset.success')); ?>"
          data-success-redirect-url="/auth/signin"
          data-error="alert"
          data-error-alert="<?php echo $this->escape(Locale::getText('home.auth.reset.failure')); ?>">

        <input type="hidden" name="userId" data-ls-echo="{{router.params.userId}}">
        <input type="hidden" name="token" data-ls-echo="{{router.params.token}}">

        <label><?php echo $this->escape(Locale::getText('home.auth.reset.labels.passwordA')); ?></label>
        <input name="passwordA" type="password" autocomplete="off" placeholder="" required data-forms-password-meter pattern=".{6,}" title="<?php echo $this->escape(Locale::getText('home.auth.reset.labels.password.validation')); ?>">

        <label><?php echo $this->escape(Locale::getText('home.auth.reset.labels.passwordB')); ?></label>
        <input name="passwordB" type="password" autocomplete="off" placeholder="" required data-forms-password-meter pattern=".{6,}" title="<?php echo $this->escape(Locale::getText('home.auth.reset.labels.password.validation')); ?>">

        <button type="submit" class="btn btn-primary"><i class="fa fa-sign-in"></i> <?php echo $this->escape(Locale::getText('home.auth.reset.action')); ?></button>
    </form>
</div>