<?php
$locale = $this->getParam("locale");
/** @var Utopia\Locale\Locale $locale */
?>

<div class="cover">
    <h1 class="zone xl margin-bottom-large">
        <a data-ls-attrs="href=/console" class="back text-size-small link-return-animation--start"><i class="icon-left-open"></i> <?php echo $locale->getText('console.shared-button-back-to-home'); ?></a>
        <br />

        <span><?php echo $locale->getText('console.account.index.title'); ?></span>
    </h1>
</div>

<div class="zone xl">
    <ul class="phases clear" data-ui-phases data-selected="{{router.params.tab}}">
        <li data-state="/console/account">
            <h2 class="margin-bottom"><?php echo $locale->getText('console.account.index.overview'); ?></h2>
            
            <div
                data-service="account.get"
                data-scope="console"
                data-name="account"
                data-event="load"
                data-failure="trigger"
                data-failure-param-trigger-events="account.deleteSession">

                <div class="row responsive force-reverse">
                    <div class="col span-3 text-align-center margin-bottom">
                        <img src="" data-ls-attrs="src={{account|avatar}}" data-size="200" height="150" alt="<?php echo $locale->getText('shared.alt-avatar'); ?>" class="avatar huge huge margin-bottom-small" />
                    </div>

                    <div class="col span-9">
                        <div class="box margin-bottom-xl">
                            <div>
                                <form name="account.update"
                                    data-analytics
                                    data-analytics-activity
                                    data-analytics-event="submit"
                                    data-analytics-category="console"
                                    data-analytics-label="Update Account Name"
                                    data-service="account.updateName"
                                    data-scope="console"
                                    data-event="submit"
                                    data-success="trigger,alert"
                                    data-success-param-alert-text="<?php echo $locale->getText('console.account.index.overview-update-name-submit-success'); ?>"
                                    data-success-param-trigger-events="account.update"
                                    data-failure="alert"
                                    data-failure-param-alert-text="<?php echo $locale->getText('console.account.index.overview-update-name-submit-error'); ?>"
                                    data-failure-param-alert-classname="error">

                                    <label for="name"><?php echo $locale->getText('shared.label-name'); ?></label>

                                    <div class="row responsive">
                                        <div class="col span-8 margin-bottom-small">
                                            <input name="name" id="name" type="text" autocomplete="off" data-ls-bind="{{account.name}}" required class="margin-bottom-no" maxlength="128">
                                        </div>
                                        <div class="col span-4">
                                            <button type="submit" class="fill margin-bottom-no"><?php echo $locale->getText('console.account.index.overview-update-name-button-submit'); ?></button>
                                        </div>
                                    </div>
                                </form>
                            </div>

                            <hr />

                            <form name="update-email"
                                data-analytics
                                data-analytics-activity
                                data-analytics-event="submit"
                                data-analytics-category="console"
                                data-analytics-label="Update Account Email"
                                data-service="account.updateEmail"
                                data-scope="console"
                                data-event="submit"
                                data-success="trigger,alert"
                                data-success-param-alert-text="<?php echo $locale->getText('console.account.index.overview-update-email-submit-success'); ?>"
                                data-success-param-trigger-events="account-update,modal-close" 
                                data-failure="alert"
                                data-failure-param-alert-text="<?php echo $locale->getText('console.account.index.overview-update-email-submit-error'); ?>"
                                data-failure-param-alert-classname="error">

                                <label><?php echo $locale->getText('shared.label-email'); ?></label>
                                <div class="row responsive">
                                    <div class="col span-8 margin-bottom-small">
                                        <input name="email" type="email" class="margin-bottom-no" autocomplete="off" placeholder="<?php echo $locale->getText('console.account.index.overview-update-email-placeholder-email'); ?>" data-ls-bind="{{account.email}}" required>
                                    </div>
                                    <div class="col span-4">
                                        <div data-ui-modal class="modal box close width-small height-small" data-button-text="<?php echo $locale->getText('console.account.index.overview-update-email-title'); ?>" data-button-class="fill">
                                            <h3><?php echo $locale->getText('console.account.index.overview-update-email-subtitle'); ?></h3>
                                            
                                            <hr />

                                            <label><?php echo $locale->getText('shared.label-password'); ?></label>
                                            <input name="password" type="password" class="full-width" autocomplete="off" placeholder="" required>
                                            
                                            <hr />

                                            <button type="submit" class="margin-bottom-no"><?php echo $locale->getText('shared.button-update'); ?></button> &nbsp; <button data-ui-modal-close="" type="button" class="reverse"><?php echo $locale->getText('shared.cancel'); ?></button>
                                        </div>
                                    </div>
                                </div>
                            </form>

                            <hr />

                            <div data-ui-modal class="modal box close width-small" data-button-text="<?php echo $locale->getText('console.account.index.overview-update-password-button-submit'); ?>" data-button-class="">
                                <h1><?php echo $locale->getText('console.account.index.overview-update-password-title'); ?></h1>

                                <form name="update-password"
                                    data-analytics
                                    data-analytics-activity
                                    data-analytics-event="submit"
                                    data-analytics-category="console"
                                    data-analytics-label="Update Account Password"
                                    data-service="account.updatePassword"
                                    data-scope="console"
                                    data-event="submit"
                                    data-success="trigger,alert,reset"
                                    data-success-param-trigger-events="account-update"
                                    data-success-param-alert-text="<?php echo $locale->getText('console.account.index.overview-update-password-submit-success'); ?>"
                                    data-failure="alert"
                                    data-failure-param-alert-text="<?php echo $locale->getText('console.account.index.overview-update-password-submit-error'); ?>"
                                    data-failure-param-alert-classname="error">

                                    <label><?php echo $locale->getText('console.account.index.overview-update-password-label-current-password'); ?></label>
                                    <input name="oldPassword" type="password" class="full-width" autocomplete="off" placeholder="" required>

                                    <label><?php echo $locale->getText('console.account.index.overview-update-password-label-new-password'); ?></label>
                                    <input name="password" type="password" class="full-width" autocomplete="off" placeholder="" required data-forms-password-meter>

                                    <hr />

                                    <footer>
                                        <button type="submit"><?php echo $locale->getText('console.account.index.overview-update-password-button-submit'); ?></button> &nbsp; <button data-ui-modal-close="" type="button" class="reverse"><?php echo $locale->getText('shared.cancel'); ?></button>
                                    </footer>
                                </form>
                            </div>

                            <hr />

                            <form class="margin-top"
                                data-analytics
                                data-analytics-activity
                                data-analytics-event="submit"
                                data-analytics-category="console"
                                data-analytics-label="Delete Account Current Session"
                                data-service="account.deleteSession"
                                data-scope="console"
                                data-event="submit"
                                data-success="trigger"
                                data-success-param-trigger-events="account.deleteSession"
                                data-failure="alert"
                                data-failure-param-alert-text="<?php echo $locale->getText('console.account.index.overview-form-logout-submit-error'); ?>"
                                data-failure-param-alert-classname="error">

                                <input type="hidden" name="sessionId" value="current">

                                <button class="fill danger icon fill"><i class="icon-login"></i> <?php echo $locale->getText('console.account.index.overview-form-logout-button-submit'); ?></button>
                            </form>
                        </div>

                    </div>
                </div>

                <div class="row responsive">
                    <div class="col span-9">

                        <h3 class="text-danger"><?php echo $locale->getText('console.account.index.overview-dangerzone-title'); ?></h3>

                        <div class="box danger">
                            <p><?php echo $locale->getText('console.account.index.overview-dangerzone-description-chunk1'); ?></p>

                            <p><?php echo $locale->getText('console.account.index.overview-dangerzone-description-chunk2'); ?></p>

                            <p><?php echo $locale->getText('console.account.index.overview-dangerzone-description-chunk3'); ?></p>

                            <form class="inline"
                                data-analytics
                                data-analytics-activity
                                data-analytics-event="submit"
                                data-analytics-category="console"
                                data-analytics-label="Delete Account"
                                data-service="account.delete"
                                data-scope="console"
                                data-event="submit"
                                data-confirm="<?php echo $locale->getText('console.account.index.overview-dangerzone-confirm'); ?>"
                                data-success="trigger"
                                data-success-param-trigger-events="account.delete"
                                data-failure="alert"
                                data-failure-param-alert-text="<?php echo $locale->getText('console.account.index.overview-dangerzone-error'); ?>"
                                data-failure-param-alert-classname="error">
                                <button class="danger reverse"><?php echo $locale->getText('console.account.index.overview-dangerzone-button-submit'); ?></button>
                            </form>
                        </div>
                    </div>
                    <div class="col span-3"></div>
                </div>
            </div>
        </li>
        <li data-state="/console/account/sessions">
            <h2><?php echo $locale->getText('console.account.index.sessions'); ?></h2>

            <div class="box margin-bottom"
                data-service="account.getSessions"
                data-scope="console"
                data-name="sessions"
                data-event="load,account.deleteRemoteSession">

                <ul data-ls-loop="sessions.sessions" data-ls-as="session" class="list">
                    <li class="clear">
                        <span data-ls-if="true != {{session.current}}">
                            <!-- From remote session (-logout event) -->
                            <form class="pull-end"
                                data-analytics
                                data-analytics-activity
                                data-analytics-event="submit"
                                data-analytics-category="console"
                                data-analytics-label="Delete Account Session"
                                data-service="account.deleteSession"
                                data-scope="console"
                                data-event="submit"
                                data-loading="<?php echo $locale->getText('shared.loading'); ?>"
                                data-success="trigger"
                                data-success-param-trigger-events="account.deleteRemoteSession"
                                data-failure="alert"
                                data-failure-param-alert-text="<?php echo $locale->getText('console.account.index.sessions-current-logout-submit-error'); ?>"
                                data-failure-param-alert-classname="error">

                                <input type="hidden" name="sessionId" data-ls-bind="{{session.$id}}">
                                <button class="danger"><?php echo $locale->getText('console.account.index.sessions-current-logout-button-submit'); ?></button>
                            </form>
                        </span>

                        <span data-ls-if="true == {{session.current}}">
                            <!-- From current session (+logout event) -->
                            <form class="pull-end"
                                data-analytics
                                data-analytics-activity
                                data-analytics-event="submit"
                                data-analytics-category="console"
                                data-analytics-label="Delete Account Current Session"
                                data-service="account.deleteSession"
                                data-scope="console"
                                data-event="submit"
                                data-loading="<?php echo $locale->getText('shared.loading'); ?>"
                                data-success="trigger,redirect"
                                data-success-param-trigger-events="account.deleteSession"
                                data-success-param-redirect-url="/"
                                data-failure="alert"
                                  data-failure-param-alert-text="<?php echo $locale->getText('console.account.index.sessions-current-logout-submit-error'); ?>"
                                data-failure-param-alert-classname="error">
                                <input type="hidden" name="sessionId" data-ls-bind="{{session.$id}}">
                                <button class="danger"><?php echo $locale->getText('console.account.index.sessions-current-logout-button-submit'); ?></button>
                            </form>
                        </span>

                        <div class="pull-start margin-end avatar-container">
                            <img onerror="this.onerror=null;this.src='/images/unknown.svg'" data-ls-attrs="src={{env.API}}/avatars/browsers/{{session.clientCode|lowercase}}?width=60&height=60&project={{env.PROJECT}},title={{session.clientName}},alt={{session.clientName}}" class="avatar" loading="lazy" width="60" height="60" />
                                
                            <div data-ls-if="{{session.provider}} !== 'email'" class="corner">
                                <img data-ls-attrs="src=/images/users/{{session.provider}}.png?buster=<?php echo APP_CACHE_BUSTER; ?>,title={{session.provider}},alt={{session.provider}}"  class="avatar xs" loading="lazy" width="30" height="30" />
                            </div>
                        </div>

                        <span data-ls-if="(!{{log.clientName}})"><?php echo $locale->getText('shared.unknown'); ?></span>
                        <span data-ls-if="({{log.clientName}})" data-ls-bind="{{session.clientName}}"></span> <span data-ls-bind="{{session.clientVersion}}"></span> <?php echo $locale->getText('shared.client-platform-joiner'); ?> <span data-ls-bind="{{session.deviceModel}}"></span> <span data-ls-bind="{{session.osName}}"></span> <span data-ls-bind="{{session.osVersion}}"></span>
                        &nbsp;
                        <span data-ls-if="true == {{session.current}}">
                            <span class="tag green"><?php echo $locale->getText('console.account.index.sessions-info-current'); ?></span>
                        </span>

                        <div class="margin-top-small">
                            <img onerror="this.onerror=null;this.src='/images/unknown.svg'" data-ls-if="{{session.countryCode}} !== '--'" data-ls-attrs="src={{env.API}}/avatars/flags/{{session.countryCode}}?width=80&height=80&project={{env.PROJECT}}" class="avatar xxs margin-end-small inline" />
                            <small data-ls-bind="{{session.ip}}"></small> / <small data-ls-bind="{{session.countryName}}"></small>
                        </div>
                    </li>
                </ul>
            </div>

            <form class="inline margin-bottom-large"
                data-analytics
                data-analytics-activity
                data-analytics-event="submit"
                data-analytics-category="console"
                data-analytics-label="Delete Account Sessions"
                data-service="account.deleteSessions"
                data-scope="console"
                data-event="submit"
                data-success="trigger,redirect"
                data-success-param-trigger-events="account.deleteSession"
                data-success-param-redirect-url="/"
                data-failure="alert"
                data-failure-param-alert-text="<?php echo $locale->getText('console.account.index.sessions-logout-submit-error'); ?>"
                data-failure-param-alert-classname="error">
                <input type="hidden" name="id" value="0">
                <button class="danger"><?php echo $locale->getText('console.account.index.sessions-logout-button-submit'); ?></button>
            </form>
        </li>
        <li data-state="/console/account/activity">
            <h2><?php echo $locale->getText('console.account.index.activity'); ?></h2>

            <div
                data-service="account.getLogs"
                data-scope="console"
                data-name="securityLogs"
                data-event="load">

                <div class="box">
                    <table class="vertical small">
                        <thead>
                            <tr>
                                <th width="140"><?php echo $locale->getText('console.account.index.activity-table-date'); ?></th>
                                <th width="175"><?php echo $locale->getText('console.account.index.activity-table-event'); ?></th>
                                <th><?php echo $locale->getText('console.account.index.activity-table-client'); ?></th>
                                <th width="90"><?php echo $locale->getText('console.account.index.activity-table-location'); ?></th>
                                <th width="90"><?php echo $locale->getText('console.account.index.activity-table-ip'); ?></th>
                            </tr>
                        </thead>
                        <tbody data-ls-loop="securityLogs.logs" data-ls-as="log">
                            <tr>
                                <td data-title="<?php echo $locale->getText('console.account.index.activity-table-date'); ?>: "><span data-ls-bind="{{log.time|dateTime}}"></span></td>
                                <td data-title="<?php echo $locale->getText('console.account.index.activity-table-event'); ?>: "><span data-ls-bind="{{log.event}}"></span></td>
                                <td data-title="<?php echo $locale->getText('console.account.index.activity-table-client'); ?>: ">
                                    <img onerror="this.onerror=null;this.src='/images/unknown.svg'" data-ls-attrs="src={{env.API}}/avatars/browsers/{{log.clientCode|lowercase}}?width=80&height=80&project={{env.PROJECT}},title={{log.clientName}},alt={{log.clientName}}" class="avatar xxs inline margin-end-small" />
                                    <span data-ls-if="(!{{log.clientName}})"><?php echo $locale->getText('shared.unknown'); ?></span>
                                    <span data-ls-if="({{log.clientName}})" data-ls-bind="{{log.clientName}} {{log.clientVersion}} <?php echo $locale->getText('shared.client-platform-joiner'); ?> {{log.model}} {{log.osName}} {{log.osVersion}}"></span>
                                </td>
                                <td data-title="<?php echo $locale->getText('console.account.index.activity-table-location'); ?>: ">
                                    <img onerror="this.onerror=null;this.src='/images/unknown.svg'" data-ls-attrs="src={{env.API}}/avatars/flags/{{log.countryCode}}?width=80&height=80&project={{env.PROJECT}}" class="avatar xxs inline margin-end-small" />
                                    <span data-ls-bind="{{log.geo.countryName}}"></span>
                                </td>
                                <td data-title="<?php echo $locale->getText('console.account.index.activity-table-ip'); ?>: "><span data-ls-bind="{{log.ip}}"></span></td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </li>
    </ul>
</div>
