[package]
name = "utopia-locale"
description = "Translations: languages, default and fallback locales, and placeholders."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
indexmap.workspace = true
php-std.workspace = true
thiserror.workspace = true
tokio = { workspace = true, features = ["fs"] }

[dev-dependencies]
tokio = { workspace = true, features = ["fs", "rt", "macros"] }

[package.metadata.utopia]
php-sync = "81b7c2fea5755cd9dd7f465dd2721aaaa773d59e"
