[package]
name = "utopia-locale"
description = "Translations lookup compatible with utopia-php/locale."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
serde_json.workspace = true
tracing.workspace = true
