/** Static Appwrite CLI topic and subcommand lists for tab completion. */

export const APPWRITE_CLI_TOPICS = [
  'account',
  'avatars',
  'client',
  'databases',
  'functions',
  'graphql',
  'init',
  'locale',
  'login',
  'logout',
  'messaging',
  'projects',
  'proxy',
  'sites',
  'storage',
  'tables-db',
  'teams',
  'tokens',
  'users',
  'vcs',
  'webhooks',
  'whoami',
] as const

export const APPWRITE_CLI_SUBCOMMANDS: Record<string, readonly string[]> = {
  account: ['get', 'update', 'create-recovery', 'update-recovery'],
  avatars: ['get-browser', 'get-credit-card', 'get-favicon', 'get-flag', 'get-image'],
  client: ['set-endpoint', 'set-key', 'set-project', 'set-self-signed'],
  databases: [
    'list',
    'create',
    'get',
    'update',
    'delete',
    'list-collections',
    'create-collection',
    'get-collection',
    'update-collection',
    'delete-collection',
    'list-documents',
    'create-document',
    'get-document',
    'update-document',
    'delete-document',
    'list-attributes',
    'create-attribute',
    'list-indexes',
    'create-index',
  ],
  functions: [
    'list',
    'create',
    'get',
    'update',
    'delete',
    'list-deployments',
    'create-deployment',
    'get-deployment',
    'update-deployment',
    'delete-deployment',
    'list-executions',
    'create-execution',
    'list-variables',
    'create-variable',
    'update-variable',
    'delete-variable',
  ],
  graphql: ['query'],
  locale: ['list-codes', 'list-countries', 'list-continents', 'list-currencies'],
  messaging: [
    'list-topics',
    'create-topic',
    'get-topic',
    'update-topic',
    'delete-topic',
    'list-subscribers',
    'create-subscriber',
    'list-messages',
    'create-email',
    'create-push',
    'create-sms',
    'list-providers',
    'create-provider',
  ],
  projects: ['list', 'get', 'update', 'delete'],
  proxy: ['list-rules', 'create-rule', 'get-rule', 'update-rule', 'delete-rule'],
  sites: [
    'list',
    'create',
    'get',
    'update',
    'delete',
    'list-deployments',
    'create-deployment',
    'list-variables',
    'create-variable',
  ],
  storage: [
    'list-buckets',
    'create-bucket',
    'get-bucket',
    'update-bucket',
    'delete-bucket',
    'list-files',
    'create-file',
    'get-file',
    'update-file',
    'delete-file',
  ],
  'tables-db': [
    'list',
    'create',
    'get',
    'update',
    'delete',
    'list-tables',
    'create-table',
    'get-table',
    'update-table',
    'delete-table',
    'list-rows',
    'create-row',
    'get-row',
    'update-row',
    'delete-row',
    'list-columns',
    'create-column',
    'list-indexes',
    'create-index',
  ],
  teams: [
    'list',
    'create',
    'get',
    'update',
    'delete',
    'list-memberships',
    'create-membership',
    'get-membership',
    'update-membership',
    'delete-membership',
  ],
  tokens: ['create'],
  users: [
    'list',
    'create',
    'get',
    'update',
    'delete',
    'count',
    'create-target',
    'delete-target',
    'list-targets',
    'list-sessions',
    'delete-session',
    'list-identities',
    'list-logs',
    'list-memberships',
  ],
  vcs: ['list-repositories', 'create-repository'],
  webhooks: ['list', 'create', 'get', 'update', 'delete'],
  whoami: [],
}
