services:
    appwrite-console:
        container_name: appwrite-console
        image: appwrite/console:5.3.0-sites-rc.36
        restart: unless-stopped
        networks:
            - appwrite
        labels:
            - "traefik.enable=true"
            - "traefik.constraint-label-stack=appwrite"
            - "traefik.docker.network=appwrite"
            - "traefik.http.services.appwrite_console.loadbalancer.server.port=80"
            #ws
            - traefik.http.routers.appwrite_console_http.entrypoints=appwrite_web
            - traefik.http.routers.appwrite_console_http.rule=PathPrefix(`/console`)
            - traefik.http.routers.appwrite_console_http.service=appwrite_console
            # wss
            - traefik.http.routers.appwrite_console_https.entrypoints=appwrite_websecure
            - traefik.http.routers.appwrite_console_https.rule=PathPrefix(`/console`)
            - traefik.http.routers.appwrite_console_https.service=appwrite_console
            - traefik.http.routers.appwrite_console_https.tls=true
