services:
    mariadb:
        image: mariadb:10.11 # fix issues when upgrading using: mysql_upgrade -u root -p
        container_name: appwrite-mariadb
        networks:
            - appwrite
        volumes:
            - appwrite-mariadb:/var/lib/mysql:rw
        environment:
            - MYSQL_ROOT_PASSWORD=${_APP_DB_ROOT_PASS}
            - MYSQL_DATABASE=${_APP_DB_SCHEMA}
            - MYSQL_USER=${_APP_DB_USER}
            - MYSQL_PASSWORD=${_APP_DB_PASS}
            - MARIADB_AUTO_UPGRADE=1
        command: "mysqld --innodb-flush-method=fsync"
