services:
    appwrite-worker-functions:
        entrypoint: worker-functions
        container_name: appwrite-worker-functions
        image: appwrite-dev
        networks:
            - appwrite
        volumes:
            - ../app:/usr/src/code/app
            - ../src:/usr/src/code/src
        depends_on:
            - redis
            - mariadb
            - openruntimes-executor
        environment:
            - _APP_ENV
            - _APP_WORKER_PER_CORE
            - _APP_OPENSSL_KEY_V1
            - _APP_DOMAIN
            - _APP_OPTIONS_FORCE_HTTPS
            - _APP_REDIS_HOST
            - _APP_REDIS_PORT
            - _APP_REDIS_USER
            - _APP_REDIS_PASS
            - _APP_DB_HOST
            - _APP_DB_PORT
            - _APP_DB_SCHEMA
            - _APP_DB_USER
            - _APP_DB_PASS
            - _APP_COMPUTE_TIMEOUT
            - _APP_COMPUTE_BUILD_TIMEOUT
            - _APP_COMPUTE_CPUS
            - _APP_COMPUTE_MEMORY
            - _APP_EXECUTOR_SECRET
            - _APP_EXECUTOR_HOST
            - _APP_USAGE_STATS
            - _APP_DOCKER_HUB_USERNAME
            - _APP_DOCKER_HUB_PASSWORD
            - _APP_LOGGING_CONFIG
            - _APP_LOGGING_PROVIDER
            - _APP_DATABASE_SHARED_TABLES
