services:
    appwrite-task-maintenance:
        entrypoint: maintenance
        container_name: appwrite-task-maintenance
        image: appwrite-dev
        networks:
            - appwrite
        volumes:
            - ../app:/usr/src/code/app
            - ../src:/usr/src/code/src
        depends_on:
            - redis
        environment:
            - _APP_ENV
            - _APP_WORKER_PER_CORE
            - _APP_DOMAIN
            - _APP_DOMAIN_TARGET
            - _APP_DOMAIN_FUNCTIONS
            - _APP_OPENSSL_KEY_V1
            - _APP_REDIS_HOST
            - _APP_REDIS_PORT
            - _APP_REDIS_USER
            - _APP_REDIS_PASS
            - _APP_DB_HOST
            - _APP_DB_PORT
            - _APP_DB_SCHEMA
            - _APP_DB_USER
            - _APP_DB_PASS
            - _APP_MAINTENANCE_INTERVAL
            - _APP_MAINTENANCE_RETENTION_EXECUTION
            - _APP_MAINTENANCE_RETENTION_CACHE
            - _APP_MAINTENANCE_RETENTION_ABUSE
            - _APP_MAINTENANCE_RETENTION_AUDIT
            - _APP_MAINTENANCE_RETENTION_USAGE_HOURLY
            - _APP_MAINTENANCE_RETENTION_SCHEDULES
            - _APP_MAINTENANCE_DELAY
            - _APP_DATABASE_SHARED_TABLES
