services:
    appwrite-worker-migrations:
        entrypoint: worker-migrations
        container_name: appwrite-worker-migrations
        restart: unless-stopped
        image: appwrite-dev
        networks:
            - appwrite
        volumes:
            - ../app:/usr/src/code/app
            - ../src:/usr/src/code/src
        depends_on:
            - mariadb
        environment:
            - _APP_ENV
            - _APP_WORKER_PER_CORE
            - _APP_OPENSSL_KEY_V1
            - _APP_DOMAIN
            - _APP_DOMAIN_TARGET
            - _APP_EMAIL_SECURITY
            - _APP_REDIS_HOST
            - _APP_REDIS_PORT
            - _APP_REDIS_USER
            - _APP_REDIS_PASS
            - _APP_DB_HOST
            - _APP_DB_PORT
            - _APP_DB_SCHEMA
            - _APP_DB_USER
            - _APP_DB_PASS
            - _APP_LOGGING_CONFIG
            - _APP_MIGRATIONS_FIREBASE_CLIENT_ID
            - _APP_MIGRATIONS_FIREBASE_CLIENT_SECRET
            - _APP_DATABASE_SHARED_TABLES
