services:
    appwrite-worker-deletes:
        entrypoint: worker-deletes
        container_name: appwrite-worker-deletes
        image: appwrite-dev
        networks:
            - appwrite
        depends_on:
            - redis
            - mariadb
        volumes:
            - appwrite-uploads:/storage/uploads:rw
            - appwrite-cache:/storage/cache:rw
            - appwrite-functions:/storage/functions:rw
            - appwrite-sites:/storage/sites:rw
            - appwrite-builds:/storage/builds:rw
            - appwrite-certificates:/storage/certificates:rw
            - ../app:/usr/src/code/app
            - ../src:/usr/src/code/src
        environment:
            - _APP_ENV
            - _APP_WORKER_PER_CORE
            - _APP_OPENSSL_KEY_V1
            - _APP_REDIS_HOST
            - _APP_REDIS_PORT
            - _APP_REDIS_USER
            - _APP_REDIS_PASS
            - _APP_DB_HOST
            - _APP_DB_PORT
            - _APP_DB_SCHEMA
            - _APP_DB_USER
            - _APP_DB_PASS
            - _APP_STORAGE_DEVICE
            - _APP_STORAGE_S3_ACCESS_KEY
            - _APP_STORAGE_S3_SECRET
            - _APP_STORAGE_S3_REGION
            - _APP_STORAGE_S3_BUCKET
            - _APP_STORAGE_S3_ENDPOINT
            - _APP_STORAGE_DO_SPACES_ACCESS_KEY
            - _APP_STORAGE_DO_SPACES_SECRET
            - _APP_STORAGE_DO_SPACES_REGION
            - _APP_STORAGE_DO_SPACES_BUCKET
            - _APP_STORAGE_BACKBLAZE_ACCESS_KEY
            - _APP_STORAGE_BACKBLAZE_SECRET
            - _APP_STORAGE_BACKBLAZE_REGION
            - _APP_STORAGE_BACKBLAZE_BUCKET
            - _APP_STORAGE_LINODE_ACCESS_KEY
            - _APP_STORAGE_LINODE_SECRET
            - _APP_STORAGE_LINODE_REGION
            - _APP_STORAGE_LINODE_BUCKET
            - _APP_STORAGE_WASABI_ACCESS_KEY
            - _APP_STORAGE_WASABI_SECRET
            - _APP_STORAGE_WASABI_REGION
            - _APP_STORAGE_WASABI_BUCKET
            - _APP_LOGGING_CONFIG
            - _APP_EXECUTOR_SECRET
            - _APP_EXECUTOR_HOST
            - _APP_DATABASE_SHARED_TABLES
            - _APP_DATABASE_SHARED_TABLES_V1
            - _APP_EMAIL_CERTIFICATES
