services:
    appwrite-worker-builds:
        entrypoint: worker-builds
        container_name: appwrite-worker-builds
        image: appwrite-dev
        networks:
            - appwrite
        volumes:
            - appwrite-functions:/storage/functions:rw
            - appwrite-sites:/storage/sites:rw
            - appwrite-builds:/storage/builds:rw
            - appwrite-uploads:/storage/uploads:rw
            - ../app:/usr/src/code/app
            - ../src:/usr/src/code/src
        depends_on:
            - redis
            - mariadb
        environment:
            - _APP_ENV
            - _APP_WORKER_PER_CORE
            - _APP_OPENSSL_KEY_V1
            - _APP_EXECUTOR_SECRET
            - _APP_EXECUTOR_HOST
            - _APP_REDIS_HOST
            - _APP_REDIS_PORT
            - _APP_REDIS_USER
            - _APP_REDIS_PASS
            - _APP_DB_HOST
            - _APP_DB_PORT
            - _APP_DB_SCHEMA
            - _APP_DB_USER
            - _APP_DB_PASS
            - _APP_LOGGING_CONFIG
            - _APP_VCS_GITHUB_APP_NAME
            - _APP_VCS_GITHUB_PRIVATE_KEY
            - _APP_VCS_GITHUB_APP_ID
            - _APP_COMPUTE_TIMEOUT
            - _APP_COMPUTE_BUILD_TIMEOUT
            - _APP_COMPUTE_CPUS
            - _APP_COMPUTE_MEMORY
            - _APP_COMPUTE_SIZE_LIMIT
            - _APP_OPTIONS_FORCE_HTTPS
            - _APP_OPTIONS_COMPUTE_FORCE_HTTPS
            - _APP_DOMAIN
            - _APP_STORAGE_DEVICE
            - _APP_STORAGE_S3_ACCESS_KEY
            - _APP_STORAGE_S3_SECRET
            - _APP_STORAGE_S3_REGION
            - _APP_STORAGE_S3_BUCKET
            - _APP_STORAGE_S3_ENDPOINT
            - _APP_STORAGE_DO_SPACES_ACCESS_KEY
            - _APP_STORAGE_DO_SPACES_SECRET
            - _APP_STORAGE_DO_SPACES_REGION
            - _APP_STORAGE_DO_SPACES_BUCKET
            - _APP_STORAGE_BACKBLAZE_ACCESS_KEY
            - _APP_STORAGE_BACKBLAZE_SECRET
            - _APP_STORAGE_BACKBLAZE_REGION
            - _APP_STORAGE_BACKBLAZE_BUCKET
            - _APP_STORAGE_LINODE_ACCESS_KEY
            - _APP_STORAGE_LINODE_SECRET
            - _APP_STORAGE_LINODE_REGION
            - _APP_STORAGE_LINODE_BUCKET
            - _APP_STORAGE_WASABI_ACCESS_KEY
            - _APP_STORAGE_WASABI_SECRET
            - _APP_STORAGE_WASABI_REGION
            - _APP_STORAGE_WASABI_BUCKET
            - _APP_DATABASE_SHARED_TABLES
            - _APP_DOMAIN_SITES
