services:
    appwrite-worker-stats-resources:
        entrypoint: worker-stats-resources
        container_name: appwrite-worker-stats-resources
        image: appwrite-dev
        networks:
            - appwrite
        volumes:
            - ../app:/usr/src/code/app
            - ../src:/usr/src/code/src
        depends_on:
            - redis
            - mariadb
        environment:
            - _APP_ENV
            - _APP_WORKER_PER_CORE
            - _APP_OPENSSL_KEY_V1
            - _APP_DB_HOST
            - _APP_DB_PORT
            - _APP_DB_SCHEMA
            - _APP_DB_USER
            - _APP_DB_PASS
            - _APP_REDIS_HOST
            - _APP_REDIS_PORT
            - _APP_REDIS_USER
            - _APP_REDIS_PASS
            - _APP_USAGE_STATS
            - _APP_LOGGING_CONFIG
            - _APP_USAGE_AGGREGATION_INTERVAL
            - _APP_DATABASE_SHARED_TABLES
