services:
    appwrite-worker-messaging:
        entrypoint: worker-messaging
        container_name: appwrite-worker-messaging
        restart: unless-stopped
        image: appwrite-dev
        networks:
            - appwrite
        volumes:
            - appwrite-uploads:/storage/uploads:rw
            - ../app:/usr/src/code/app
            - ../src:/usr/src/code/src
        depends_on:
            - redis
        environment:
            - _APP_ENV
            - _APP_WORKER_PER_CORE
            - _APP_OPENSSL_KEY_V1
            - _APP_REDIS_HOST
            - _APP_REDIS_PORT
            - _APP_REDIS_USER
            - _APP_REDIS_PASS
            - _APP_DB_HOST
            - _APP_DB_PORT
            - _APP_DB_SCHEMA
            - _APP_DB_USER
            - _APP_DB_PASS
            - _APP_LOGGING_CONFIG
            - _APP_SMS_FROM
            - _APP_SMS_PROVIDER
            - _APP_SMS_PROJECTS_DENY_LIST
            - _APP_STORAGE_DEVICE
            - _APP_STORAGE_S3_ACCESS_KEY
            - _APP_STORAGE_S3_SECRET
            - _APP_STORAGE_S3_REGION
            - _APP_STORAGE_S3_BUCKET
            - _APP_STORAGE_S3_ENDPOINT
            - _APP_STORAGE_DO_SPACES_ACCESS_KEY
            - _APP_STORAGE_DO_SPACES_SECRET
            - _APP_STORAGE_DO_SPACES_REGION
            - _APP_STORAGE_DO_SPACES_BUCKET
            - _APP_STORAGE_BACKBLAZE_ACCESS_KEY
            - _APP_STORAGE_BACKBLAZE_SECRET
            - _APP_STORAGE_BACKBLAZE_REGION
            - _APP_STORAGE_BACKBLAZE_BUCKET
            - _APP_STORAGE_LINODE_ACCESS_KEY
            - _APP_STORAGE_LINODE_SECRET
            - _APP_STORAGE_LINODE_REGION
            - _APP_STORAGE_LINODE_BUCKET
            - _APP_STORAGE_WASABI_ACCESS_KEY
            - _APP_STORAGE_WASABI_SECRET
            - _APP_STORAGE_WASABI_REGION
            - _APP_STORAGE_WASABI_BUCKET
            - _APP_DATABASE_SHARED_TABLES
