services:
    appwrite-worker-webhooks:
        entrypoint: worker-webhooks
        container_name: appwrite-worker-webhooks
        image: appwrite-dev
        networks:
            - appwrite
        volumes:
            - ../app:/usr/src/code/app
            - ../src:/usr/src/code/src
        depends_on:
            - redis
            - mariadb
            - request-catcher
        environment:
            - _APP_ENV
            - _APP_WORKER_PER_CORE
            - _APP_OPENSSL_KEY_V1
            - _APP_EMAIL_SECURITY
            - _APP_DB_HOST
            - _APP_DB_PORT
            - _APP_DB_SCHEMA
            - _APP_DB_USER
            - _APP_DB_PASS
            - _APP_REDIS_HOST
            - _APP_REDIS_PORT
            - _APP_REDIS_USER
            - _APP_REDIS_PASS
            - _APP_LOGGING_CONFIG
            - _APP_WEBHOOK_MAX_FAILED_ATTEMPTS
            - _APP_DATABASE_SHARED_TABLES
