services:
    appwrite-worker-mails:
        entrypoint: worker-mails
        container_name: appwrite-worker-mails
        image: appwrite-dev
        networks:
            - appwrite
        volumes:
            - ../app:/usr/src/code/app
            - ../src:/usr/src/code/src
        depends_on:
            - redis
            - maildev
            # - smtp
        environment:
            - _APP_ENV
            - _APP_WORKER_PER_CORE
            - _APP_OPENSSL_KEY_V1
            - _APP_SYSTEM_EMAIL_NAME
            - _APP_SYSTEM_EMAIL_ADDRESS
            - _APP_REDIS_HOST
            - _APP_REDIS_PORT
            - _APP_REDIS_USER
            - _APP_REDIS_PASS
            - _APP_SMTP_HOST
            - _APP_SMTP_PORT
            - _APP_SMTP_SECURE
            - _APP_SMTP_USERNAME
            - _APP_SMTP_PASSWORD
            - _APP_LOGGING_CONFIG
            - _APP_DOMAIN
            - _APP_OPTIONS_FORCE_HTTPS
            - _APP_DATABASE_SHARED_TABLES
