[package]
name = "utopia-cache"
description = "A Redis-backed cache with leases and purges."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
crc32fast.workspace = true
redis.workspace = true
tracing.workspace = true
