Hi <strong><?php echo $this->getParam('user') ?></strong>,
<br /><br />
Your webhook <strong><?php echo $this->getParam('webhook') ?></strong> on project <strong><?php echo $this->getParam('project') ?></strong> has been paused after <?php echo $this->getParam('attempts') ?> consecutive failures. <br /><br />
<p>Webhook URL: <strong><?php echo $this->getParam('url') ?></strong></p>
<p>Error: <strong><?php echo $this->getParam('error') ?></strong></p> <br />To restore the functionality of your webhook, please take the following steps:<br /><br />
1. Debug the webhook to identify and resolve the issue:
<ul>
    <li>Examine the logs of both Appwrite Console and your webhook server to identify the issue</li>
    <li>Investigate potential network issues and use webhook testing tools to verify expected behaviour</li>
    <li>Ensure the webhook URL is reachable and configured to accept incoming POST requests</li>
    <li>Confirm that the webhook doesn't return error status codes such as 400 or 500</li>
</ul>
2. Re-enable the webhook from the project settings page

<table border="0" cellspacing="0" cellpadding="0" style="padding-top: 10px; padding-bottom: 10px; display: inline-block; margin-top: 32px">
    <tr>
        <td align="center" style="border-radius: 8px; background-color: #FD366E;">
            <a rel="noopener" target="_blank" href="<?php echo $this->getParam('redirect') ?>" style="font-size: 14px; font-family: Inter; color: #ffffff; text-decoration: none; border-radius: 8px; padding: 9px 14px; border: 1px solid #FD366E; display: inline-block;">View webhook settings</a>
        </td>
    </tr>
</table>