/**
 * ISO 639-2 languages accepted by the Videos subtitle API.
 * Mirrors `code2` in appwrite/appwrite `app/config/locale/languages.php`.
 */
export type VideoSubtitleLanguage = {
  code: string
  name: string
  nativeName: string
}

export const VIDEO_SUBTITLE_LANGUAGES: VideoSubtitleLanguage[] = [
  { code: 'abk', name: 'Abkhazian', nativeName: 'Аҧсуа' },
  { code: 'aar', name: 'Afar', nativeName: 'Afar' },
  { code: 'afr', name: 'Afrikaans', nativeName: 'Afrikaans' },
  { code: 'aka', name: 'Akan', nativeName: 'Akana' },
  { code: 'sqi', name: 'Albanian', nativeName: 'Shqip' },
  { code: 'amh', name: 'Amharic', nativeName: 'አማርኛ' },
  { code: 'ara', name: 'Arabic', nativeName: 'العربية' },
  { code: 'arg', name: 'Aragonese', nativeName: 'Aragonés' },
  { code: 'hye', name: 'Armenian', nativeName: 'Հայերեն' },
  { code: 'asm', name: 'Assamese', nativeName: 'অসমীয়া' },
  { code: 'ava', name: 'Avar', nativeName: 'Авар' },
  { code: 'aym', name: 'Aymara', nativeName: 'Aymar' },
  { code: 'aze', name: 'Azerbaijani', nativeName: 'Azərbaycanca / آذربايجان' },
  { code: 'bam', name: 'Bambara', nativeName: 'Bamanankan' },
  { code: 'bak', name: 'Bashkir', nativeName: 'Башҡорт' },
  { code: 'eus', name: 'Basque', nativeName: 'Euskara' },
  { code: 'bel', name: 'Belarusian', nativeName: 'Беларуская' },
  { code: 'ben', name: 'Bengali', nativeName: 'বাংলা' },
  { code: 'bih', name: 'Bihari', nativeName: 'भोजपुरी' },
  { code: 'bis', name: 'Bislama', nativeName: 'Bislama' },
  { code: 'bos', name: 'Bosnian', nativeName: 'Bosanski' },
  { code: 'bre', name: 'Breton', nativeName: 'Brezhoneg' },
  { code: 'bul', name: 'Bulgarian', nativeName: 'Български' },
  { code: 'mya', name: 'Burmese', nativeName: 'မြန်မာစာ' },
  { code: 'cat', name: 'Catalan', nativeName: 'Català' },
  { code: 'cha', name: 'Chamorro', nativeName: 'Chamoru' },
  { code: 'che', name: 'Chechen', nativeName: 'Нохчийн' },
  { code: 'nya', name: 'Chichewa', nativeName: 'Chi-Chewa' },
  { code: 'zho', name: 'Chinese (Simplified)', nativeName: '中文' },
  { code: 'chv', name: 'Chuvash', nativeName: 'Чăваш' },
  { code: 'cor', name: 'Cornish', nativeName: 'Kernewek' },
  { code: 'cos', name: 'Corsican', nativeName: 'Corsu' },
  { code: 'cre', name: 'Cree', nativeName: 'Nehiyaw' },
  { code: 'hrv', name: 'Croatian', nativeName: 'Hrvatski' },
  { code: 'ces', name: 'Czech', nativeName: 'Česky' },
  { code: 'dan', name: 'Danish', nativeName: 'Dansk' },
  { code: 'div', name: 'Divehi', nativeName: 'ދިވެހިބަސް' },
  { code: 'nld', name: 'Dutch', nativeName: 'Nederlands' },
  { code: 'dzo', name: 'Dzongkha', nativeName: 'ཇོང་ཁ' },
  { code: 'eng', name: 'English', nativeName: 'English' },
  { code: 'epo', name: 'Esperanto', nativeName: 'Esperanto' },
  { code: 'est', name: 'Estonian', nativeName: 'Eesti' },
  { code: 'ewe', name: 'Ewe', nativeName: 'Ɛʋɛ' },
  { code: 'fao', name: 'Faroese', nativeName: 'Føroyskt' },
  { code: 'fij', name: 'Fijian', nativeName: 'Na Vosa Vakaviti' },
  { code: 'fin', name: 'Finnish', nativeName: 'Suomi' },
  { code: 'fra', name: 'French', nativeName: 'Français' },
  { code: 'glg', name: 'Galician', nativeName: 'Galego' },
  { code: 'lug', name: 'Ganda', nativeName: 'Luganda' },
  { code: 'kat', name: 'Georgian', nativeName: 'ქართული' },
  { code: 'deu', name: 'German', nativeName: 'Deutsch' },
  { code: 'ell', name: 'Greek', nativeName: 'Ελληνικά' },
  { code: 'kal', name: 'Greenlandic', nativeName: 'Kalaallisut' },
  { code: 'grn', name: 'Guarani', nativeName: "Avañe'ẽ" },
  { code: 'guj', name: 'Gujarati', nativeName: 'ગુજરાતી' },
  { code: 'hat', name: 'Haitian', nativeName: 'Krèyol ayisyen' },
  { code: 'hau', name: 'Hausa', nativeName: 'هَوُسَ' },
  { code: 'heb', name: 'Hebrew', nativeName: 'עברית' },
  { code: 'her', name: 'Herero', nativeName: 'Otsiherero' },
  { code: 'hin', name: 'Hindi', nativeName: 'हिन्दी / हिंदी ' },
  { code: 'hmo', name: 'Hiri Motu', nativeName: 'Hiri Motu' },
  { code: 'hun', name: 'Hungarian', nativeName: 'Magyar' },
  { code: 'isl', name: 'Icelandic', nativeName: 'Íslenska' },
  { code: 'ido', name: 'Ido', nativeName: 'Ido' },
  { code: 'ibo', name: 'Igbo', nativeName: 'Igbo' },
  { code: 'ind', name: 'Indonesian', nativeName: 'Bahasa Indonesia' },
  { code: 'ina', name: 'Interlingua', nativeName: 'Interlingua' },
  { code: 'ile', name: 'Interlingue', nativeName: 'Interlingue' },
  { code: 'iku', name: 'Inuktitut', nativeName: 'ᐃᓄᒃᑎᑐᑦ' },
  { code: 'ipk', name: 'Inupiak', nativeName: 'Iñupiak' },
  { code: 'gle', name: 'Irish', nativeName: 'Gaeilge' },
  { code: 'ita', name: 'Italian', nativeName: 'Italiano' },
  { code: 'jpn', name: 'Japanese', nativeName: '日本語' },
  { code: 'jav', name: 'Javanese', nativeName: 'Basa Jawa' },
  { code: 'kan', name: 'Kannada', nativeName: 'ಕನ್ನಡ' },
  { code: 'kau', name: 'Kanuri', nativeName: 'Kanuri' },
  { code: 'kas', name: 'Kashmiri', nativeName: 'कश्मीरी / كشميري' },
  { code: 'kaz', name: 'Kazakh', nativeName: 'Қазақша' },
  { code: 'khm', name: 'Khmer', nativeName: 'ភាសាខ្មែរ' },
  { code: 'kik', name: 'Kikuyu', nativeName: 'Gĩkũyũ' },
  { code: 'kir', name: 'Kirghiz', nativeName: 'Kırgızca / Кыргызча' },
  { code: 'run', name: 'Kirundi', nativeName: 'Kirundi' },
  { code: 'kom', name: 'Komi', nativeName: 'Коми' },
  { code: 'kon', name: 'Kongo', nativeName: 'KiKongo' },
  { code: 'kor', name: 'Korean', nativeName: '한국어' },
  { code: 'kua', name: 'Kuanyama', nativeName: 'Kuanyama' },
  { code: 'kur', name: 'Kurdish', nativeName: 'Kurdî / كوردی' },
  { code: 'lao', name: 'Laotian', nativeName: 'ລາວ / Pha xa lao' },
  { code: 'lat', name: 'Latin', nativeName: 'Latina' },
  { code: 'lav', name: 'Latvian', nativeName: 'Latviešu' },
  { code: 'lim', name: 'Limburgian', nativeName: 'Limburgs' },
  { code: 'lin', name: 'Lingala', nativeName: 'Lingála' },
  { code: 'lit', name: 'Lithuanian', nativeName: 'Lietuvių' },
  { code: 'lub', name: 'Luba-Katanga', nativeName: 'Tshiluba' },
  { code: 'ltz', name: 'Luxembourgish', nativeName: 'Lëtzebuergesch' },
  { code: 'mkd', name: 'Macedonian', nativeName: 'Македонски' },
  { code: 'mlg', name: 'Malagasy', nativeName: 'Malagasy' },
  { code: 'msa', name: 'Malay', nativeName: 'Bahasa Melayu' },
  { code: 'mal', name: 'Malayalam', nativeName: 'മലയാളം' },
  { code: 'mlt', name: 'Maltese', nativeName: 'bil-Malti' },
  { code: 'glv', name: 'Manx', nativeName: 'Gaelg' },
  { code: 'mri', name: 'Maori', nativeName: 'Māori' },
  { code: 'mar', name: 'Marathi', nativeName: 'मराठी' },
  { code: 'mah', name: 'Marshallese', nativeName: 'Kajin Majel / Ebon' },
  { code: 'mol', name: 'Moldovan', nativeName: 'Moldovenească' },
  { code: 'mon', name: 'Mongolian', nativeName: 'Монгол' },
  { code: 'nau', name: 'Nauruan', nativeName: 'Dorerin Naoero' },
  { code: 'nav', name: 'Navajo', nativeName: 'Diné bizaad' },
  { code: 'ndo', name: 'Ndonga', nativeName: 'Oshiwambo' },
  { code: 'nep', name: 'Nepali', nativeName: 'नेपाली' },
  { code: 'nde', name: 'North Ndebele', nativeName: 'Sindebele' },
  { code: 'sme', name: 'Northern Sami', nativeName: 'Sámegiella' },
  { code: 'nob', name: 'Norwegian Bokmål', nativeName: 'Norsk bokmål' },
  { code: 'nno', name: 'Norwegian Nynorsk', nativeName: 'Norsk nynorsk' },
  { code: 'oci', name: 'Occitan', nativeName: 'Occitan' },
  { code: 'oji', name: 'Ojibwa', nativeName: 'ᐊᓂᔑᓈᐯᒧᐎᓐ / Anishinaabemowin' },
  {
    code: 'chu',
    name: 'Old Church Slavonic / Old Bulgarian',
    nativeName: 'словѣньскъ / slověnĭskŭ',
  },
  { code: 'ori', name: 'Oriya', nativeName: 'ଓଡ଼ିଆ' },
  { code: 'orm', name: 'Oromo', nativeName: 'Oromoo' },
  { code: 'oss', name: 'Ossetian / Ossetic', nativeName: 'Иронау' },
  { code: 'pli', name: 'Pali', nativeName: 'Pāli / पाऴि' },
  {
    code: 'pan',
    name: 'Panjabi / Punjabi',
    nativeName: 'ਪੰਜਾਬੀ / पंजाबी / پنجابي',
  },
  { code: 'pus', name: 'Pashto', nativeName: 'پښتو' },
  { code: 'fas', name: 'Persian', nativeName: 'فارسی' },
  { code: 'ful', name: 'Peul', nativeName: 'Fulfulde' },
  { code: 'pol', name: 'Polish', nativeName: 'Polski' },
  { code: 'por', name: 'Portuguese', nativeName: 'Português' },
  { code: 'que', name: 'Quechua', nativeName: 'Runa Simi' },
  { code: 'roh', name: 'Raeto Romance', nativeName: 'Rumantsch' },
  { code: 'ron', name: 'Romanian', nativeName: 'Română' },
  { code: 'rus', name: 'Russian', nativeName: 'Русский' },
  { code: 'kin', name: 'Rwandi', nativeName: 'Kinyarwandi' },
  { code: 'smo', name: 'Samoan', nativeName: 'Gagana Samoa' },
  { code: 'sag', name: 'Sango', nativeName: 'Sängö' },
  { code: 'san', name: 'Sanskrit', nativeName: 'संस्कृतम्' },
  { code: 'srd', name: 'Sardinian', nativeName: 'Sardu' },
  { code: 'gla', name: 'Scottish Gaelic', nativeName: 'Gàidhlig' },
  { code: 'srp', name: 'Serbian', nativeName: 'Српски' },
  {
    code: 'hbs',
    name: 'Serbo-Croatian',
    nativeName: 'Srpskohrvatski / Српскохрватски',
  },
  { code: 'sna', name: 'Shona', nativeName: 'chiShona' },
  { code: 'iii', name: 'Sichuan Yi', nativeName: 'ꆇꉙ / 四川彝语' },
  { code: 'snd', name: 'Sindhi', nativeName: 'सिन्धी / सिंधी ' },
  { code: 'sin', name: 'Sinhalese', nativeName: 'සිංහල' },
  { code: 'slk', name: 'Slovak', nativeName: 'Slovenčina' },
  { code: 'slv', name: 'Slovenian', nativeName: 'Slovenščina' },
  { code: 'som', name: 'Somalia', nativeName: 'Soomaaliga' },
  { code: 'nbl', name: 'South Ndebele', nativeName: 'isiNdebele' },
  { code: 'sot', name: 'Southern Sotho', nativeName: 'Sesotho' },
  { code: 'spa', name: 'Spanish', nativeName: 'Español' },
  { code: 'sun', name: 'Sundanese', nativeName: 'Basa Sunda' },
  { code: 'swa', name: 'Swahili', nativeName: 'Kiswahili' },
  { code: 'ssw', name: 'Swati', nativeName: 'SiSwati' },
  { code: 'swe', name: 'Swedish', nativeName: 'Svenska' },
  { code: 'tgl', name: 'Tagalog / Filipino', nativeName: 'Tagalog' },
  { code: 'tah', name: 'Tahitian', nativeName: 'Reo Mā`ohi' },
  { code: 'tgk', name: 'Tajik', nativeName: 'Тоҷикӣ' },
  { code: 'tam', name: 'Tamil', nativeName: 'தமிழ்' },
  { code: 'tat', name: 'Tatar', nativeName: 'Tatarça' },
  { code: 'tel', name: 'Telugu', nativeName: 'తెలుగు' },
  { code: 'tha', name: 'Thai', nativeName: 'ไทย / Phasa Thai' },
  { code: 'bod', name: 'Tibetan', nativeName: 'བོད་ཡིག / Bod skad' },
  { code: 'tir', name: 'Tigrinya', nativeName: 'ትግርኛ' },
  { code: 'ton', name: 'Tonga', nativeName: 'Lea Faka-Tonga' },
  { code: 'tso', name: 'Tsonga', nativeName: 'Xitsonga' },
  { code: 'tsn', name: 'Tswana', nativeName: 'Setswana' },
  { code: 'tur', name: 'Turkish', nativeName: 'Türkçe' },
  { code: 'tuk', name: 'Turkmen', nativeName: 'Туркмен / تركمن' },
  { code: 'twi', name: 'Twi', nativeName: 'Twi' },
  { code: 'ukr', name: 'Ukrainian', nativeName: 'Українська' },
  { code: 'urd', name: 'Urdu', nativeName: 'اردو' },
  { code: 'uig', name: 'Uyghur', nativeName: 'Uyƣurqə / ئۇيغۇرچە' },
  { code: 'uzb', name: 'Uzbek', nativeName: 'Ўзбек' },
  { code: 'ven', name: 'Venda', nativeName: 'Tshivenḓa' },
  { code: 'vie', name: 'Vietnamese', nativeName: 'Tiếng Việt' },
  { code: 'vol', name: 'Volapük', nativeName: 'Volapük' },
  { code: 'wln', name: 'Walloon', nativeName: 'Walon' },
  { code: 'cym', name: 'Welsh', nativeName: 'Cymraeg' },
  { code: 'fry', name: 'West Frisian', nativeName: 'Frysk' },
  { code: 'wol', name: 'Wolof', nativeName: 'Wollof' },
  { code: 'xho', name: 'Xhosa', nativeName: 'isiXhosa' },
  { code: 'yid', name: 'Yiddish', nativeName: 'ייִדיש' },
  { code: 'yor', name: 'Yoruba', nativeName: 'Yorùbá' },
  { code: 'zha', name: 'Zhuang', nativeName: 'Cuengh / Tôô / 壮语' },
  { code: 'zul', name: 'Zulu', nativeName: 'isiZulu' },
]

export function getVideoSubtitleLanguage(
  code: string | null | undefined,
): VideoSubtitleLanguage | undefined {
  return VIDEO_SUBTITLE_LANGUAGES.find((language) => language.code === code)
}
