/**
 * Generates blog post metadata manifest from markdoc sources.
 * Invoked by generate:blog-manifest (scripts/generate-blog-manifest.ts).
 */
import { readdir, readFile, writeFile, mkdir } from 'node:fs/promises'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import {
  getFrontmatterAuthor,
  getFrontmatterDate,
  getFrontmatterString,
  parseBlogFrontmatter,
} from '../../src/lib/blog/frontmatter.ts'
import type { BlogPostMeta } from '../../src/lib/blog/types.ts'

const __dirname = dirname(fileURLToPath(import.meta.url))
const VIBES_ROOT = join(__dirname, '../..')
const BLOG_DIR = join(VIBES_ROOT, 'src', 'content', 'blog', 'posts')
const BLOG_LOCAL_DIR = join(VIBES_ROOT, 'src', 'content', 'blog-local', 'posts')
const OUTPUT_DIR = join(VIBES_ROOT, 'src', 'lib', 'blog', 'generated')

function parseBoolean(value: unknown): boolean | undefined {
  if (typeof value === 'boolean') return value
  if (value === 'true') return true
  if (value === 'false') return false
  return undefined
}

function slugFromFilename(filename: string): string {
  return filename.replace(/\.markdoc$/, '')
}

function buildBlogPostMeta(slug: string, raw: string): BlogPostMeta {
  const { frontmatter } = parseBlogFrontmatter(raw)
  const date =
    getFrontmatterDate(frontmatter, 'date') ||
    getFrontmatterDate(frontmatter, 'lastUpdated')
  const lastUpdated =
    getFrontmatterDate(frontmatter, 'lastUpdated') || date
  const cover = getFrontmatterString(frontmatter, 'cover')
  const timeToReadRaw = frontmatter.timeToRead
  const timeToRead =
    typeof timeToReadRaw === 'number'
      ? timeToReadRaw
      : Number.parseInt(getFrontmatterString(frontmatter, 'timeToRead') ?? '0', 10) || 0

  return {
    slug,
    href: `/blog/post/${slug}`,
    title: getFrontmatterString(frontmatter, 'title') ?? slug,
    description: getFrontmatterString(frontmatter, 'description') ?? '',
    date,
    lastUpdated,
    timeToRead,
    author: getFrontmatterAuthor(frontmatter),
    category: getFrontmatterString(frontmatter, 'category') ?? '',
    featured: parseBoolean(frontmatter.featured),
    unlisted: parseBoolean(frontmatter.unlisted),
    draft: parseBoolean(frontmatter.draft),
    metaTitle: getFrontmatterString(frontmatter, 'metaTitle'),
    cover,
    hasCover: Boolean(cover),
  }
}

async function listMarkdocSlugs(dir: string): Promise<Map<string, string>> {
  const bySlug = new Map<string, string>()
  try {
    const entries = await readdir(dir)
    for (const entry of entries) {
      if (!entry.endsWith('.markdoc')) continue
      const slug = slugFromFilename(entry)
      bySlug.set(slug, join(dir, entry))
    }
  } catch {
    // Directory may not exist in sparse checkouts.
  }
  return bySlug
}

async function main() {
  const filesBySlug = await listMarkdocSlugs(BLOG_DIR)
  const localBySlug = await listMarkdocSlugs(BLOG_LOCAL_DIR)
  for (const [slug, filePath] of localBySlug) {
    filesBySlug.set(slug, filePath)
  }

  const posts: BlogPostMeta[] = []
  for (const [slug, filePath] of filesBySlug) {
    const raw = await readFile(filePath, 'utf-8')
    posts.push(buildBlogPostMeta(slug, raw))
  }

  // Newest first; slug tie-break keeps same-day order stable (and puts
  // announcing-appwrite-2 ahead of the other Init day-1 featured posts).
  posts.sort((a, b) => {
    const byDate = new Date(b.date).getTime() - new Date(a.date).getTime()
    if (byDate !== 0) return byDate
    return a.slug.localeCompare(b.slug)
  })

  await mkdir(OUTPUT_DIR, { recursive: true })

  const manifestContent = `// Auto-generated by generate:blog-manifest - do not edit manually.
import type { BlogPostMeta } from '../types'

export const BLOG_POSTS: BlogPostMeta[] = ${JSON.stringify(posts, null, 2)} as BlogPostMeta[]

export const BLOG_POST_MAP: Record<string, BlogPostMeta> = Object.fromEntries(
  BLOG_POSTS.map((post) => [post.slug, post]),
)
`

  await writeFile(join(OUTPUT_DIR, 'manifest.ts'), manifestContent, 'utf-8')
  console.log(`Generated blog manifest with ${posts.length} posts`)
}

main().catch((err) => {
  console.error(err)
  process.exit(1)
})
