/**
 * Generates blog post metadata manifest from markdoc sources.
 * Invoked by generate:blog-manifest (scripts/generate-blog-manifest.ts).
 */
import { readdir, readFile, writeFile, mkdir } from 'node:fs/promises'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import {
  getFrontmatterAuthor,
  getFrontmatterDate,
  getFrontmatterString,
  isRemovedBlogPost,
  parseBlogFrontmatter,
} from '../../src/lib/blog/frontmatter.ts'
import type { BlogPostMeta } from '../../src/lib/blog/types.ts'

const __dirname = dirname(fileURLToPath(import.meta.url))
const VIBES_ROOT = join(__dirname, '../..')
const BLOG_DIR = join(VIBES_ROOT, 'src', 'content', 'blog', 'posts')
const OUTPUT_DIR = join(VIBES_ROOT, 'src', 'lib', 'blog', 'generated')

function parseBoolean(value: unknown): boolean | undefined {
  if (typeof value === 'boolean') return value
  if (value === 'true') return true
  if (value === 'false') return false
  return undefined
}

function slugFromFilename(filename: string): string {
  return filename.replace(/\.markdoc$/, '')
}

function buildBlogPostMeta(
  slug: string,
  frontmatter: Record<string, unknown>,
): BlogPostMeta {
  const date =
    getFrontmatterDate(frontmatter, 'date') ||
    getFrontmatterDate(frontmatter, 'lastUpdated')
  const lastUpdated =
    getFrontmatterDate(frontmatter, 'lastUpdated') || date
  const cover = getFrontmatterString(frontmatter, 'cover')
  const timeToReadRaw = frontmatter.timeToRead
  const timeToRead =
    typeof timeToReadRaw === 'number'
      ? timeToReadRaw
      : Number.parseInt(getFrontmatterString(frontmatter, 'timeToRead') ?? '0', 10) || 0

  return {
    slug,
    href: `/blog/post/${slug}`,
    title: getFrontmatterString(frontmatter, 'title') ?? slug,
    description: getFrontmatterString(frontmatter, 'description') ?? '',
    date,
    lastUpdated,
    timeToRead,
    author: getFrontmatterAuthor(frontmatter),
    category: getFrontmatterString(frontmatter, 'category') ?? '',
    featured: parseBoolean(frontmatter.featured),
    unlisted: parseBoolean(frontmatter.unlisted),
    draft: parseBoolean(frontmatter.draft),
    metaTitle: getFrontmatterString(frontmatter, 'metaTitle'),
    cover,
    hasCover: Boolean(cover),
  }
}

async function listMarkdocSlugs(dir: string): Promise<Map<string, string>> {
  const bySlug = new Map<string, string>()
  try {
    const entries = await readdir(dir)
    for (const entry of entries) {
      if (!entry.endsWith('.markdoc')) continue
      const slug = slugFromFilename(entry)
      bySlug.set(slug, join(dir, entry))
    }
  } catch {
    // Directory may not exist in sparse checkouts.
  }
  return bySlug
}

function buildRemovedSlugsModule(removedSlugs: string[]): string {
  const entries = removedSlugs.map((slug) => `  ${JSON.stringify(slug)},`).join('\n')
  return `// Auto-generated by generate:blog-manifest - do not edit manually.
// Posts marked \`removed: true\`. Their URLs redirect to the home page.
export const REMOVED_BLOG_POST_SLUGS: ReadonlySet<string> = new Set([
${entries}
])
`
}

/**
 * Lazy body loaders as a glob with one negative pattern per removed post, so
 * removed post bodies are never bundled (import.meta.glob needs literals).
 */
function buildPostLoadersModule(removedSlugs: string[]): string {
  const patterns = [
    '/src/content/blog/posts/*.markdoc',
    ...removedSlugs.map((slug) => `!/src/content/blog/posts/${slug}.markdoc`),
  ]
    .map((pattern) => `    ${JSON.stringify(pattern)},`)
    .join('\n')

  return `// Auto-generated by generate:blog-manifest - do not edit manually.
// Lazy post body loaders keyed by module path. Removed posts are excluded.
export const BLOG_POST_LOADERS = import.meta.glob(
  [
${patterns}
  ],
  { query: '?raw', import: 'default' },
) as Record<string, () => Promise<string>>
`
}

async function main() {
  const filesBySlug = await listMarkdocSlugs(BLOG_DIR)

  const posts: BlogPostMeta[] = []
  const removedSlugs: string[] = []
  for (const [slug, filePath] of filesBySlug) {
    const { frontmatter } = parseBlogFrontmatter(await readFile(filePath, 'utf-8'))
    if (isRemovedBlogPost(frontmatter)) {
      removedSlugs.push(slug)
      continue
    }
    posts.push(buildBlogPostMeta(slug, frontmatter))
  }
  removedSlugs.sort()

  // Newest first; slug tie-break keeps same-day order stable (and puts
  // announcing-appwrite-2 ahead of the other Init day-1 featured posts).
  posts.sort((a, b) => {
    const byDate = new Date(b.date).getTime() - new Date(a.date).getTime()
    if (byDate !== 0) return byDate
    return a.slug.localeCompare(b.slug)
  })

  await mkdir(OUTPUT_DIR, { recursive: true })

  const manifestContent = `// Auto-generated by generate:blog-manifest - do not edit manually.
import type { BlogPostMeta } from '../types'

export const BLOG_POSTS: BlogPostMeta[] = ${JSON.stringify(posts, null, 2)} as BlogPostMeta[]

export const BLOG_POST_MAP: Record<string, BlogPostMeta> = Object.fromEntries(
  BLOG_POSTS.map((post) => [post.slug, post]),
)
`

  await writeFile(join(OUTPUT_DIR, 'manifest.ts'), manifestContent, 'utf-8')
  await writeFile(
    join(OUTPUT_DIR, 'removed.ts'),
    buildRemovedSlugsModule(removedSlugs),
    'utf-8',
  )
  await writeFile(
    join(OUTPUT_DIR, 'post-loaders.ts'),
    buildPostLoadersModule(removedSlugs),
    'utf-8',
  )
  console.log(
    `Generated blog manifest with ${posts.length} posts (${removedSlugs.length} removed)`,
  )
}

main().catch((err) => {
  console.error(err)
  process.exit(1)
})
