<?php
$fileLimit = $this->getParam('fileLimit', 0);
$fileLimitHuman = $this->getParam('fileLimitHuman', 0);
$events = array_keys($this->getParam('events', []));
$timeout = $this->getParam('timeout', 900);
$usageStatsEnabled = $this->getParam('usageStatsEnabled',true);

/** @var Utopia\Locale\Locale $locale */
$locale = $this->getParam("locale");

?>
<div
    data-service="functions.get"
    data-name="project-function"
    data-event="load,functions.update,functions.createTag,functions.updateTag,functions.deleteTag"
    data-param-function-id="{{router.params.id}}"
    data-success="trigger"
    data-success-param-trigger-events="functions.get">

    <div class="cover">
        <h1 class="zone xl margin-bottom-large">
            <a data-ls-attrs="href=/console/functions?project={{router.params.project}}" class="back text-size-small link-return-animation--start"><i class="icon-left-open"></i> <?php echo $locale->getText('console.functions.function.back-button'); ?></a>
            <br />

            <span data-ls-bind="{{project-function.name}}&nbsp;">&nbsp;</span>
        </h1>
    </div>

    <div data-ui-modal class="modal width-large box close" data-button-hide="on" data-open-event="open-json">
        <button type="button" class="close pull-end" data-ui-modal-close=""><i class="icon-cancel"></i></button>    
        
        <h2><?php echo $locale->getText('shared.json-view-title'); ?></h2>

        <div class="margin-bottom">
            <input type="hidden" data-ls-bind="{{project-function}}" data-forms-code />
        </div>

        <button data-ui-modal-close="" type="button" class="reverse"><?php echo $locale->getText('shared.json-view-button-cancel'); ?></button>
    </div>

    <div class="zone xl">
        <ul class="phases clear" data-ui-phases data-selected="{{router.params.tab}}">
            <li data-state="/console/functions/function?id={{router.params.id}}&project={{router.params.project}}">
                
                <h2><?php echo $locale->getText('console.functions.function.overview-title'); ?></h2>
                
                <div class="row responsive margin-top-negative">
                    <div class="col span-8 margin-bottom">
                        <label>&nbsp;</label>

                        <div class="box margin-bottom-large">
                            <div class="text-align-center">
                                <img src="" data-ls-attrs="src=/images/runtimes/{{project-function.runtime|runtimeLogo}}" alt="<?php echo $locale->getText('console.functions.function.overview-runtime-alt'); ?>" class="avatar huge margin-top-negative-xxl" />

                                <p class="text-fade margin-bottom-small" data-ls-bind="{{project-function.runtime|runtimeName}} {{project-function.runtime|runtimeVersion}}">
                                </p>
                                <div data-ls-if="{{project-function.tag}} !== ''" class="margin-top">
                                    <button data-ls-ui-trigger="execute-now"><?php echo $locale->getText('console.functions.function.overview-execute-button'); ?></button> &nbsp; <a data-ls-attrs="href=/console/functions/function/logs?id={{router.params.id}}&project={{router.params.project}}" class="button reverse" style="vertical-align: top;"><?php echo $locale->getText('console.functions.function.overview-logs-button'); ?></a>
                                </div>
                            </div>
                        </div>

                        <div class="margin-bottom"
                            data-service="functions.listTags"
                            data-scope="sdk"
                            data-event="load,functions.createTag,functions.deleteTag,functions.updateTag"
                            data-name="project-function-tags"
                            data-param-function-id="{{router.params.id}}"
                            data-param-limit="<?php echo APP_PAGING_LIMIT; ?>"
                            data-param-offset=""
                            data-param-order-type="DESC"
                            data-success="trigger"
                            data-success-param-trigger-events="functions.listTags">

                            <h3><?php echo $locale->getText('console.functions.function.overview-tags-title'); ?> <span class="text-fade text-size-small pull-end margin-top-small" data-ls-bind="<?php echo $locale->getText('console.functions.function.overview-tags-sum'); ?>"></span></h3>

                            <div data-ls-if="0 == {{project-function-tags.tags.length}} || undefined == {{project-function-tags.tags.length}}" class="box margin-top margin-bottom">
                                <h3 class="margin-bottom-small text-bold"><?php echo $locale->getText('console.functions.function.overview-tags-no-tags-title'); ?></h3>

                                <p class="margin-bottom-no"><?php echo $locale->getText('console.functions.function.overview-tags-no-tags-description'); ?></p>
                            </div>

                            <div data-ls-if="(0 != {{project-function-tags.tags.length}}) && (undefined !== {{project-function-tags.tags.length}})">
                                <div class="box margin-bottom">
                                    <ul data-ls-loop="project-function-tags.tags" data-ls-as="tag" class="list">
                                        <li class="clear">
                                            <form data-ls-if="{{tag.$id}} !== {{project-function.tag}}" name="functions.updateTag" class="pull-end"
                                                data-analytics
                                                data-analytics-activity
                                                data-analytics-event="submit"
                                                data-analytics-category="console"
                                                data-analytics-label="Activate Function Tag"
                                                data-service="functions.updateTag"
                                                data-event="submit"
                                                data-param-function-id="{{router.params.id}}"
                                                data-success="alert,trigger"
                                                data-success-param-alert-text="<?php echo $locale->getText('console.functions.function.overview-tags-activate-submit-success'); ?>"
                                                data-success-param-trigger-events="functions.updateTag"
                                                data-failure="alert"
                                                data-failure-param-alert-text="<?php echo $locale->getText('console.functions.function.overview-tags-activate-submit-error'); ?>"
                                                data-failure-param-alert-classname="error">
                                                <input type="hidden" name="tag" data-ls-bind="{{tag.$id}}">
                                                <button><?php echo $locale->getText('console.functions.function.overview-tags-activate-submit-button'); ?></button>
                                            </form>
    
                                            <b data-ls-bind="{{tag.$id}}"></b> &nbsp;
                                            <span class="text-fade" data-ls-bind="{{tag.command}}"></span>
                                            <div class="text-size-small margin-top-small clear">
                                                <span class="pull-start" data-ls-bind="Created {{tag.dateCreated|timeSince}} &nbsp; | &nbsp; {{tag.size|humanFileSize}}{{tag.size|humanFileUnit}}"></span>

                                                <form data-ls-if="{{tag.$id}} !== {{project-function.tag}}" name="functions.deleteTag" class="pull-start"
                                                    data-analytics
                                                    data-analytics-activity
                                                    data-analytics-event="submit"
                                                    data-analytics-category="console"
                                                    data-analytics-label="Delete Function Tag"
                                                    data-service="functions.deleteTag"
                                                    data-event="submit"
                                                    data-param-function-id="{{router.params.id}}"
                                                    data-confirm="<?php echo $locale->getText('console.functions.function.overview-tags-delete-submit-confirm'); ?>"
                                                    data-success="alert,trigger"
                                                    data-success-param-alert-text="<?php echo $locale->getText('console.functions.function.overview-tags-delete-submit-success'); ?>"
                                                    data-success-param-trigger-events="functions.deleteTag"
                                                    data-failure="alert"
                                                    data-failure-param-alert-text="<?php echo $locale->getText('console.functions.function.overview-tags-delete-submit-error'); ?>"
                                                    data-failure-param-alert-classname="error">
                                                    <input type="hidden" name="tagId" data-ls-bind="{{tag.$id}}" />

                                                    &nbsp; | &nbsp;<button type="submit" class="link text-danger text-size-small"><?php echo $locale->getText('console.functions.function.overview-tags-delete-submit-button'); ?></button>
                                                </form>
                                            </div>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </div>

                        <div class="pull-start">
                            <button data-ls-ui-trigger="deploy-tag"><?php echo $locale->getText('console.functions.function.overview-tags-deploy-button-modal'); ?></button>
                        </div>

                        <div class="pull-end paging">
                            <form
                                data-service="functions.listTags"
                                data-event="submit"
                                data-param-function-id="{{router.params.id}}"
                                data-param-search="{{router.params.search}}"
                                data-param-limit="<?php echo APP_PAGING_LIMIT; ?>"
                                data-param-order-type="DESC"
                                data-scope="sdk"
                                data-name="project-function-tags"
                                data-success="state"
                                data-success-param-state-keys="search,offset">
                                <button name="offset" data-paging-back data-offset="{{router.params.offset}}" data-sum="{{project-function-tags.sum}}" class="margin-end round small" aria-label="<?php echo $locale->getText('shared.pagination-back'); ?>"><i class="icon-left-open"></i></button>
                            </form>

                            <span data-ls-bind="{{router.params.offset|pageCurrent}} / {{project-function-tags.sum|pageTotal}}"></span>

                            <form
                                data-service="functions.listTags"
                                data-event="submit"
                                data-param-function-id="{{router.params.id}}"
                                data-param-search="{{router.params.search}}"
                                data-param-limit="<?php echo APP_PAGING_LIMIT; ?>"
                                data-param-order-type="DESC"
                                data-scope="sdk"
                                data-name="project-function-tags"
                                data-success="state"
                                data-success-param-state-keys="search,offset">
                                <button name="offset" data-paging-next data-offset="{{router.params.offset}}" data-sum="{{project-function-tags.sum}}" class="margin-start round small" aria-label="<?php echo $locale->getText('shared.pagination-next'); ?>"><i class="icon-right-open"></i></button>
                            </form>
                        </div>
                    </div>
                    <div class="col span-4 sticky-top margin-bottom">
                        <label><?php echo $locale->getText('console.functions.function.overview-side-function-id'); ?></label>
                        <div class="input-copy margin-bottom">
                            <input id="uid" type="text" autocomplete="off" placeholder="" data-ls-bind="{{project-function.$id}}" disabled data-forms-copy>
                        </div>

                        <ul class="margin-bottom-large text-fade text-size-small">
                            <li class="margin-bottom-small"><i class="icon-angle-circled-right margin-start-tiny margin-end-tiny"></i> <button data-ls-ui-trigger="open-json" class="link text-size-small"><?php echo $locale->getText('shared.view-as-json'); ?></button></li>
                            <li class="margin-bottom-small"><i class="icon-angle-circled-right margin-start-tiny margin-end-tiny"></i> <?php echo $locale->getText('shared.last-updated'); ?>: <span data-ls-bind="{{project-function.dateUpdated|dateText}}"></span></li>
                            <li class="margin-bottom-small"><i class="icon-angle-circled-right margin-start-tiny margin-end-tiny"></i> <?php echo $locale->getText('shared.side-created'); ?>: <span data-ls-bind="{{project-function.dateCreated|dateText}}"></span></li>
                        </ul>

                        <form name="functions.delete" class="margin-bottom"
                            data-analytics
                            data-analytics-activity
                            data-analytics-event="submit"
                            data-analytics-category="console"
                            data-analytics-label="Delete Function"
                            data-service="functions.delete"
                            data-event="submit"
                            data-param-function-id="{{router.params.id}}"
                            data-confirm="<?php echo $locale->getText('console.functions.function.overview-side-delete-confirm'); ?>"
                            data-success="alert,trigger,redirect"
                            data-success-param-alert-text="<?php echo $locale->getText('console.functions.function.overview-side-delete-success'); ?>"
                            data-success-param-trigger-events="functions.delete"
                            data-success-param-redirect-url="/console/functions?project={{router.params.project}}"
                            data-failure="alert"
                            data-failure-param-alert-text="<?php echo $locale->getText('console.functions.function.overview-side-delete-error'); ?>"
                            data-failure-param-alert-classname="error">

                            <button type="submit" class="danger fill"><?php echo $locale->getText('console.functions.function.overview-side-delete-button'); ?></button>
                        </form>
                    </div>
                </div>
            </li>
            <?php if($usageStatsEnabled): ?>
            <li data-state="/console/functions/function/monitors?id={{router.params.id}}&project={{router.params.project}}">
                
                <form class="pull-end margin-start-small margin-top-small" data-ls-if="{{usage.range}} !== '90d'"
                    data-service="functions.getUsage"
                    data-event="submit"
                    data-name="usage"
                    data-param-function-id="{{router.params.id}}"
                    data-param-range="90d">
                    <button class="tick"><?php echo $locale->getText('shared.graph.days90'); ?></button>
                </form>

                <button class="tick pull-end margin-start-small margin-top-small" data-ls-if="{{usage.range}} === '90d'" disabled><?php echo $locale->getText('shared.graph.days90'); ?></button>

                <form class="pull-end margin-start-small margin-top-small" data-ls-if="{{usage.range}} !== '30d'"
                    data-service="functions.getUsage"
                    data-event="submit"
                    data-name="usage"
                    data-param-function-id="{{router.params.id}}">
                    <button class="tick"><?php echo $locale->getText('shared.graph.days30'); ?></button>
                </form>

                <button class="tick pull-end margin-start-small margin-top-small" data-ls-if="{{usage.range}} === '30d'" disabled><?php echo $locale->getText('shared.graph.days30'); ?></button>

                <form class="pull-end margin-start-small margin-top-small" data-ls-if="{{usage.range}} !== '24h'"
                    data-service="functions.getUsage"
                    data-event="submit"
                    data-name="usage"
                    data-param-function-id="{{router.params.id}}"
                    data-param-range="24h">
                    <button class="tick"><?php echo $locale->getText('shared.graph.hours24'); ?></button>
                </form>

                <button class="tick pull-end margin-start-small margin-top-small" data-ls-if="{{usage.range}} === '24h'" disabled><?php echo $locale->getText('shared.graph.hours24'); ?></button>

                <h2><?php echo $locale->getText('console.functions.function.monitors-title'); ?></h2>
                
                <div 
                    data-service="functions.getUsage"
                    data-event="load"
                    data-name="usage"
                    data-param-function-id="{{router.params.id}}">
                    <div class="box margin-bottom-small">
                        <div class="margin-start-negative-small margin-end-negative-small margin-top-negative-small margin-bottom-negative-small">
                            <div class="chart margin-bottom-no">
                                <input type="hidden" data-ls-bind="{{usage}}" data-forms-chart="<?php echo $locale->getText('console.functions.function.monitors-stats-executions'); ?>=usage.executions.data" data-height="140" />
                            </div>
                        </div>
                    </div>

                    <ul class="chart-notes margin-bottom-large">
                        <li><?php echo $locale->getText('console.functions.function.monitors-stats-executions'); ?> <span data-ls-bind="({{usage.executions.total}})"></span></li>
                    </ul>

                    <div class="box margin-bottom-small">
                        <div class="margin-start-negative-small margin-end-negative-small margin-top-negative-small margin-bottom-negative-small">
                            <div class="chart margin-bottom-no">
                                <input type="hidden" data-ls-bind="{{usage}}" data-forms-chart="<?php echo $locale->getText('console.functions.function.monitors-stats-cpu-time'); ?>=usage.compute.data" data-colors="orange" data-height="140" />
                            </div>
                        </div>
                    </div>

                    <ul class="chart-notes margin-bottom-large">
                        <li class="orange"><?php echo $locale->getText('console.functions.function.monitors-stats-cpu-time'); ?> <span data-ls-bind="({{usage.compute.total|seconds2hum}})"></span></li>
                    </ul>

                    <div class="box margin-bottom-small">
                        <div class="margin-start-negative-small margin-end-negative-small margin-top-negative-small margin-bottom-negative-small">
                            <div class="chart margin-bottom-no">
                                <input type="hidden" data-ls-bind="{{usage}}" data-forms-chart="<?php echo $locale->getText('console.functions.function.monitors-stats-errors'); ?>=usage.failures.data" data-colors="red" data-height="140" />
                            </div>
                        </div>
                    </div>

                    <ul class="chart-notes margin-bottom-large">
                        <li class="red"><?php echo $locale->getText('console.functions.function.monitors-stats-errors'); ?> <span data-ls-bind="({{usage.failures.total}})"></span></li>
                    </ul>
                </div>
            </li>
            <?php endif; ?>
            <li data-state="/console/functions/function/logs?id={{router.params.id}}&project={{router.params.project}}">

                <div class="text-fade text-size-small pull-end margin-top" data-ls-bind="<?php echo $locale->getText('console.functions.function.logs-executions-sum'); ?>"></div>

                <h2><?php echo $locale->getText('console.functions.function.logs-title'); ?></h2>

                <div
                    data-service="functions.listExecutions"
                    data-scope="sdk"
                    data-event="load,functions.createExecution"
                    data-name="project-function-executions"
                    data-param-function-id="{{router.params.id}}"
                    data-param-limit="<?php echo APP_PAGING_LIMIT; ?>"
                    data-param-offset=""
                    data-param-order-type="DESC"
                    data-success="trigger"
                    data-success-param-trigger-events="functions.listExecutions">

                    <div data-ls-if="0 < {{project-function-executions.executions.length}} && undefined !== {{project-function-executions.executions}}">
                        <div class="box margin-bottom">
                            <table class="vertical small">
                                <thead>
                                    <tr>
                                        <th width="30"></th>
                                        <th width="160"><?php echo $locale->getText('console.functions.function.logs-table-column-created'); ?></th>
                                        <th width="150"><?php echo $locale->getText('console.functions.function.logs-table-column-status'); ?></th>
                                        <th width="120"><?php echo $locale->getText('console.functions.function.logs-table-column-trigger'); ?></th>
                                        <th width="80"><?php echo $locale->getText('console.functions.function.logs-table-column-runtime'); ?></th>
                                        <th></th>
                                    </tr>
                                </thead>
                                <tbody data-ls-loop="project-function-executions.executions" data-ls-as="execution">
                                    <tr>
                                        <td data-title="">
                                            <i class="dot danger" data-ls-if="{{execution.status}} === 'failed'"></i>
                                            <i class="dot info" data-ls-if="{{execution.status}} === 'waiting'"></i>
                                            <i class="dot info" data-ls-if="{{execution.status}} === 'processing'"></i>
                                            <i class="dot success" data-ls-if="{{execution.status}} === 'completed'"></i>
                                        </td>
                                        <td data-title="<?php echo $locale->getText('console.functions.function.logs-table-column-created'); ?>: ">
                                            <span data-ls-bind="{{execution.dateCreated|dateTime}}"></span>
                                        </td>
                                        <td data-title="<?php echo $locale->getText('console.functions.function.logs-table-column-status'); ?>: ">
                                            <span data-ls-bind="{{execution.status}}"></span>

                                            <span class="text-fade text-size-small" data-ls-if="{{execution.exitCode}} !== 0" data-ls-bind=" <?php echo $locale->getText('console.functions.function.logs-exit-code'); ?>: {{execution.exitCode}}"></span>
                                        </td>
                                        <td data-title="<?php echo $locale->getText('console.functions.function.logs-table-column-trigger'); ?>: ">
                                            <span data-ls-bind="{{execution.trigger}}"></span>
                                        </td>
                                        <td data-title="<?php echo $locale->getText('console.functions.function.logs-table-column-runtime'); ?>: ">
                                            <span data-ls-if="{{execution.status}} === 'completed' || {{execution.status}} === 'failed'" data-ls-bind="{{execution.time|seconds2hum}}"></span>
                                            <span data-ls-if="{{execution.status}} === 'waiting' || {{execution.status}} === 'processing'">-</span>
                                        </td>
                                        <td data-title="">
                                            <div data-ls-if="{{execution.status}} === 'completed' || {{execution.status}} === 'failed'" data-title="">
                                                
                                                <button class="desktops-only pull-end link margin-start text-danger" data-ls-ui-trigger="execution-stderr-{{execution.$id}}"><?php echo $locale->getText('console.functions.function.logs-button-errors'); ?></button>
                                                <button class="desktops-only pull-end link margin-start" data-ls-ui-trigger="execution-stdout-{{execution.$id}}"><?php echo $locale->getText('console.functions.function.logs-button-output'); ?></button>

                                                <button class="phones-only-inline tablets-only-inline link margin-end-small" data-ls-ui-trigger="execution-stdout-{{execution.$id}}"><?php echo $locale->getText('console.functions.function.logs-button-output'); ?></button>
                                                <button class="phones-only-inline tablets-only-inline link text-danger" data-ls-ui-trigger="execution-stderr-{{execution.$id}}"><?php echo $locale->getText('console.functions.function.logs-button-errors'); ?></button>

                                                <div data-ui-modal class="modal width-large box close" data-button-alias="none" data-open-event="execution-stdout-{{execution.$id}}">
                                                    <button type="button" class="close pull-end" data-ui-modal-close=""><i class="icon-cancel"></i></button>

                                                    <h1>STDOUT</h1>

                                                    <div class="margin-bottom ide" data-ls-if="({{execution.stdout.length}})">
                                                        <pre data-ls-bind="{{execution.stdout}}"></pre>
                                                        <!-- <input type="hidden" data-ls-bind="{{execution.stdout}}" data-forms-code="bash" /> -->
                                                    </div>

                                                    <div class="margin-bottom" data-ls-if="(!{{execution.stdout.length}})">
                                                        <p><?php echo $locale->getText('console.functions.function.logs-no-output'); ?></p>
                                                    </div>
                                                </div>

                                                <div data-ui-modal class="modal width-large box close" data-button-alias="none" data-open-event="execution-stderr-{{execution.$id}}">
                                                    <button type="button" class="close pull-end" data-ui-modal-close=""><i class="icon-cancel"></i></button>

                                                    <h1>STDERR</h1>

                                                    <div class="margin-bottom ide" data-ls-if="({{execution.stderr.length}})">
                                                        <pre data-ls-bind="{{execution.stderr}}"></pre>
                                                        <!-- <input type="hidden" data-ls-bind="{{execution.stderr}}" data-forms-code="bash" /> -->
                                                    </div>

                                                    <div class="margin-bottom" data-ls-if="(!{{execution.stderr.length}})">
                                                        <p><?php echo $locale->getText('console.functions.function.logs-no-error'); ?></p>
                                                    </div>
                                                </div>
                                            </div>
                                        </td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>

                        <div class="text-align-center paging">
                            <form
                                data-service="functions.listExecutions"
                                data-event="submit"
                                data-param-function-id="{{router.params.id}}"
                                data-param-search="{{router.params.search}}"
                                data-param-limit="<?php echo APP_PAGING_LIMIT; ?>"
                                data-param-order-type="DESC"
                                data-scope="sdk"
                                data-name="project-function-executions"
                                data-success="state"
                                data-success-param-state-keys="search,offset">
                                <button name="offset" data-paging-back data-offset="{{router.params.offset}}" data-sum="{{project-function-executions.sum}}" class="margin-end round small" aria-label="<?php echo $locale->getText('shared.pagination-back'); ?>"><i class="icon-left-open"></i></button>
                            </form>

                            <span data-ls-bind="{{router.params.offset|pageCurrent}} / {{project-function-executions.sum|pageTotal}}"></span>

                            <form
                                data-service="functions.listExecutions"
                                data-event="submit"
                                data-param-function-id="{{router.params.id}}"
                                data-param-search="{{router.params.search}}"
                                data-param-limit="<?php echo APP_PAGING_LIMIT; ?>"
                                data-param-order-type="DESC"
                                data-scope="sdk"
                                data-name="project-function-executions"
                                data-success="state"
                                data-success-param-state-keys="search,offset">
                                <button name="offset" data-paging-next data-offset="{{router.params.offset}}" data-sum="{{project-function-executions.sum}}" class="margin-start round small" aria-label="<?php echo $locale->getText('shared.pagination-next'); ?>"><i class="icon-right-open"></i></button>
                            </form>
                        </div>
                    </div>

                    <div data-ls-if="(!{{project-function-executions.executions.length}})" class="box dashboard margin-bottom">
                        <div class="margin-bottom-small margin-top-small margin-end margin-start">
                            <h3 class="margin-bottom-small text-bold"><?php echo $locale->getText('console.functions.function.logs-no-executions-title'); ?></h3>

                            <p class="margin-bottom-no"><?php echo $locale->getText('console.functions.function.logs-no-executions-description'); ?></p>
                        </div>
                    </div>
                </div>
            </li>
            <li data-state="/console/functions/function/settings?id={{router.params.id}}&project={{router.params.project}}">
                <h2><?php echo $locale->getText('console.functions.function.settings-title'); ?></h2>

                <div class="row responsive margin-top-negative">
                    <div class="col span-8 margin-bottom">
                        <label>&nbsp;</label>

                        <form
                            data-analytics
                            data-analytics-activity
                            data-analytics-event="submit"
                            data-analytics-category="console"
                            data-analytics-label="Update Function"
                            data-service="functions.update"
                            data-scope="sdk"
                            data-event="submit"
                            data-param-function-id="{{router.params.id}}"
                            data-success="alert,trigger"
                            data-success-param-alert-text="<?php echo $locale->getText('console.functions.function.update-success'); ?>"
                            data-success-param-trigger-events="functions.update"
                            data-failure="alert"
                            data-failure-param-alert-text="<?php echo $locale->getText('console.functions.function.update-error'); ?>"
                            data-failure-param-alert-classname="error">

                            <div class="box">
                                <section class="margin-bottom-large">
                                    <label for="name"><?php echo $locale->getText('console.functions.function.update-label-name'); ?></label>
                                    <input name="name" id="function-name" type="text" autocomplete="off" data-ls-bind="{{project-function.name}}" data-forms-text-direction required placeholder="<?php echo $locale->getText('console.functions.function.update-placeholder-name'); ?>" maxlength="128" />

                                    <label for="execute"><?php echo $locale->getText('console.functions.function.update-label-execute-access'); ?> <span class="tooltip small" data-tooltip="<?php echo $locale->getText('console.functions.function.update-tooltip-execute-access'); ?>"><i class="icon-info-circled"></i></span> <span class="text-size-small">(<a data-ls-attrs="href={{env.HOME}}/docs/permissions" target="_blank" rel="noopener"><?php echo $locale->getText('shared.learn-more'); ?></a>)</span></label>
                                    <input type="hidden" id="execute" name="execute" data-forms-tags data-cast-to="json" data-ls-bind="{{project-function.$permissions.execute}}" placeholder="<?php echo $locale->getText('shared.access-placeholder'); ?>" />
                                    <div class="text-fade text-size-xs margin-top-negative-small margin-bottom"><?php echo $locale->getText('shared.permission-info'); ?></div>

                                    <label for="timeout"><?php echo $locale->getText('console.functions.function.update-label-timeout'); ?> <span class="tooltip small" data-tooltip="<?php echo $locale->getText('console.functions.function.update-tooltip-timeout'); ?>"><i class="icon-info-circled"></i></span></label>
                                    <input name="timeout" id="function-timeout" type="number" autocomplete="off" data-ls-bind="{{project-function.timeout}}" min="1" max="<?php echo $this->escape($timeout); ?>" data-cast-to="integer" />
                                    <div class="text-size-small text-fade margin-bottom margin-top-negative-small"><?php echo $locale->getText('console.functions.function.update-description-timeout-chunk1'); ?> <?php echo $this->escape(number_format($timeout)); ?> <?php echo $locale->getText('console.functions.function.update-description-timeout-chunk2'); ?> (<?php echo $this->escape((int) ($timeout / 60)); ?> <?php echo $locale->getText('console.functions.function.update-description-timeout-chunk3'); ?>)</div>
                                </section>

                                <section class="margin-bottom" data-forms-select-all data-forms-select-all-text="<?php echo $locale->getText('shared.select-all'); ?>" data-forms-unselect-all-text="<?php echo $locale->getText('shared.unselect-all'); ?>">
                                    <label for="events" class="margin-bottom"><?php echo $locale->getText('console.functions.function.update-label-events'); ?> <span class="tooltip small" data-tooltip="<?php echo $locale->getText('console.functions.function.update-tooltip-events'); ?>"><i class="icon-info-circled"></i></span></label>
                                    <div class="row responsive thin margin-top-small">
                                        <?php foreach ($events as $i => $event) : ?>
                                            <div class="col span-6 text-one-liner margin-bottom text-height-large text-size-small" title="<?php echo $event; ?>">
                                                <input type="checkbox" name="events" data-ls-bind="{{project-function.events}}" id="<?php echo $event; ?>" value="<?php echo $event; ?>" />
                                                &nbsp;
                                                <label class="inline" for="<?php echo $event; ?>"><?php echo $event; ?></label>
                                            </div>
                                            <?php if (($i + 1) % 2 === 0) : ?>
                                            </div>
                                            <div class="row responsive thin">
                                            <?php endif; ?>

                                        <?php endforeach; ?>
                                    </div>
                                </section>

                                <label for="schedule"><?php echo $locale->getText('console.functions.function.update-label-schedule'); ?> <span class="tooltip small" data-tooltip="<?php echo $locale->getText('console.functions.function.update-tooltip-schedule'); ?>"><i class="icon-info-circled"></i></span></label>
                                <input type="text" id="function-schedule" class="full-width" name="schedule" autocomplete="off" data-ls-bind="{{project-function.schedule}}" placeholder="* * * * *" />
                                <div class="text-size-small text-fade margin-bottom margin-top-negative-small"><?php echo $locale->getText('console.functions.function.update-description-schedule'); ?></div>

                                <h3 class="margin-bottom-small"><?php echo $locale->getText('console.functions.function.update-label-variables'); ?> <span class="tooltip small" data-tooltip="<?php echo $locale->getText('console.functions.function.update-tooltip-variables'); ?>"><i class="icon-info-circled"></i></span></h3>

                                <div data-ls-if="(!{{project-function.vars.length}})">
                                    <hr class="margin-bottom margin-top-no" />

                                    <fieldset name="vars" data-cast-to="object">
                                        <div data-ls-loop="project-function.vars" data-ls-as="var" id="project-vars" style="visibility: visible;">
                                            <div class="margin-bottom-small">
                                                <div data-forms-remove class="row thin">
                                                    <div class="col span-10">
                                                        <input type="hidden" data-forms-key-value data-ls-attrs="name={{$index}}" data-ls-bind="{{var}}" />
                                                    </div>
                                                    <div class="col span-2">
                                                        <button type="button" data-remove class="reverse danger round pull-end"><i class="icon-cancel"></i></button>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>

                                        <div data-forms-clone="" data-target="project-vars" data-label="<?php echo $locale->getText('console.functions.function.update-add-variable'); ?>" data-first="0">
                                            <div class="margin-bottom-small">
                                                <div data-forms-remove class="row thin margin-bottom-small">
                                                    <div class="col span-10">
                                                        <input type="hidden" name="" data-forms-key-value />
                                                    </div>
                                                    <div class="col span-2">
                                                        <button type="button" data-remove class="reverse danger round pull-end"><i class="icon-cancel"></i></button>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </fieldset>
                                    <hr class="margin-bottom margin-top-small" />
                                </div>

                                <button><?php echo $locale->getText('console.functions.function.update-submit'); ?></button>
                            </div>
                        </form>
                    </div>
                    <div class="col span-4 sticky-top">
                        <label><?php echo $locale->getText('console.functions.function.overview-side-function-id'); ?></label>
                        <div class="input-copy margin-bottom">
                            <input id="uid" type="text" autocomplete="off" placeholder="" data-ls-bind="{{project-function.$id}}" disabled data-forms-copy>
                        </div>

                        <ul class="margin-bottom-large text-fade text-size-small">
                            <li class="margin-bottom-small"><i class="icon-angle-circled-right margin-start-tiny margin-end-tiny"></i> <button data-ls-ui-trigger="open-json" class="link text-size-small"><?php echo $locale->getText('shared.view-as-json'); ?></button></li>
                            <li class="margin-bottom-small"><i class="icon-angle-circled-right margin-start-tiny margin-end-tiny"></i> <?php echo $locale->getText('shared.last-updated'); ?>: <span data-ls-bind="{{project-function.dateUpdated|dateText}}"></span></li>
                            <li class="margin-bottom-small"><i class="icon-angle-circled-right margin-start-tiny margin-end-tiny"></i> <?php echo $locale->getText('shared.side-created'); ?>: <span data-ls-bind="{{project-function.dateCreated|dateText}}"></span></li>
                        </ul>

                        <form name="functions.delete" class="margin-bottom"
                              data-analytics
                              data-analytics-activity
                              data-analytics-event="submit"
                              data-analytics-category="console"
                              data-analytics-label="Delete Function"
                              data-service="functions.delete"
                              data-event="submit"
                              data-param-function-id="{{router.params.id}}"
                              data-confirm="<?php echo $locale->getText('console.functions.function.overview-side-delete-confirm'); ?>"
                              data-success="alert,trigger,redirect"
                              data-success-param-alert-text="<?php echo $locale->getText('console.functions.function.overview-side-delete-success'); ?>"
                              data-success-param-trigger-events="functions.delete"
                              data-success-param-redirect-url="/console/functions?project={{router.params.project}}"
                              data-failure="alert"
                              data-failure-param-alert-text="<?php echo $locale->getText('console.functions.function.overview-side-delete-error'); ?>"
                              data-failure-param-alert-classname="error">

                            <button type="submit" class="danger fill"><?php echo $locale->getText('console.functions.function.overview-side-delete-button'); ?></button>
                        </form>
                    </div>
                </div>
            </li>
        </ul>
    </div>
</div>

<div data-ui-modal class="modal close box sticky-footer" data-button-hide="on" data-open-event="execute-now">
    <button type="button" class="close pull-end" data-ui-modal-close=""><i class="icon-cancel"></i></button>
    <h1 class="margin-bottom"><?php echo $locale->getText('console.functions.function.modal-execute-title'); ?></h1>
    <form data-ls-if="{{project-function.tag}} !== ''" name="functions.createExecution" class="margin-top"
        data-analytics
        data-analytics-activity
        data-analytics-event="submit"
        data-analytics-category="console"
        data-analytics-label="Create Function Execution"
        data-service="functions.createExecution"
        data-event="submit"
        data-param-function-id="{{router.params.id}}"
        data-success="alert,trigger"
        data-success-param-alert-text="<?php echo $locale->getText('console.functions.function.modal-execute-submit-success'); ?>"
        data-success-param-trigger-events="functions.createExecution"
        data-failure="alert"
        data-failure-param-alert-text="<?php echo $locale->getText('console.functions.function.modal-execute-submit-error'); ?>"
        data-failure-param-alert-classname="error">

        <label for="execution-data"><?php echo $locale->getText('console.functions.function.modal-execute-custom-data-label'); ?></label>
        <textarea id="execution-data" name="data" autocomplete="off" class="margin-bottom" placeholder="<?php echo $locale->getText('console.functions.function.modal-execute-custom-data-placeholder'); ?>"></textarea>

        <button type="submit" style="vertical-align: top;"><?php echo $locale->getText('console.functions.function.modal-execute-submit-button'); ?></button>
     </form>
</div>
<div data-ui-modal class="modal close box sticky-footer" data-button-hide="on" data-open-event="deploy-tag">
    <button type="button" class="close pull-end" data-ui-modal-close=""><i class="icon-cancel"></i></button>

    <h1 class="margin-bottom-xl"><?php echo $locale->getText('console.functions.function.modal-deploy-tag-title'); ?></h1>

    <ul class="phases padding margin-top-negative-small" data-ui-phases>
        <li>
            <h2 style="display: none">CLI</h2>

            <p><b>Unix</b></p>

            <div class="margin-bottom">
                <textarea type="hidden" data-ls-bind="appwrite functions createTag \
    --functionId={{project-function.$id}} \
    --command='mycommand' \
    --code='/myrepo/myfunction'" data-forms-code="bash" data-lang="bash" data-lang-label="Bash"></textarea>
            </div>

            <p><b>PowerShell</b></p>

            <div class="margin-bottom">
                <textarea type="hidden" data-ls-bind="appwrite functions createTag `
    --functionId={{project-function.$id}} `
    --command='mycommand' `
    --code='/myrepo/myfunction'" data-forms-code="powershell" data-lang="powershell" data-lang-label="PowerShell"></textarea>
            </div>

            <p><?php echo $locale->getText('console.functions.function.modal-deploy-tag-cli-learn-more-chunk1'); ?> <a href="https://appwrite.io/docs/server/functions#functionsCreateTag" target="_blank"><?php echo $locale->getText('console.functions.function.modal-deploy-tag-cli-learn-more-chunk2'); ?></a>, <?php echo $locale->getText('console.functions.function.modal-deploy-tag-cli-learn-more-chunk3'); ?> <a href="https://appwrite.io/docs/command-line" target="_blank"><?php echo $locale->getText('console.functions.function.modal-deploy-tag-cli-learn-more-chunk4'); ?></a>.</p>
        </li>
        <li>
            <h2 style="display: none"><?php echo $locale->getText('console.functions.function.modal-deploy-tag-manual-title'); ?></h2>
            <form class="margin-top-negative"
                data-analytics
                data-analytics-activity
                data-analytics-event="submit"
                data-analytics-category="console"
                data-analytics-label="Create Function Tag"
                data-service="functions.createTag"
                data-scope="sdk"
                data-event="submit"
                data-success="alert,trigger,reset"
                data-success-param-alert-text="<?php echo $locale->getText('console.functions.function.modal-deploy-tag-manual-submit-success'); ?>"
                data-success-param-trigger-events="functions.createTag"
                data-failure="alert"
                data-failure-param-alert-text="<?php echo $locale->getText('console.functions.function.modal-deploy-tag-manual-submit-error'); ?>"
                data-failure-param-alert-classname="error">
                
                <input type="hidden" name="functionId" data-ls-bind="{{router.params.id}}" />

                <label for="tag-command"><?php echo $locale->getText('console.functions.function.modal-deploy-tag-manual-label-command'); ?></label>
                <input type="text" id="tag-command" name="command" required autocomplete="off" class="margin-bottom" placeholder="<?php echo $locale->getText('console.functions.function.modal-deploy-tag-manual-placeholder-command'); ?>" />

                <label for="tag-code"><?php echo $locale->getText('console.functions.function.modal-deploy-tag-manual-label-gzip'); ?></label>
                <input type="file" name="code" id="tag-code" size="1" required accept="application/x-gzip,.gz">
                <div class="text-fade text-size-xs margin-top-negative-small margin-bottom-large">(<?php echo $locale->getText('console.functions.function.modal-deploy-tag-manual-description-gzip'); ?>: <?php echo $fileLimitHuman; ?>)</div>

                <footer>
                    <button type="submit"><?php echo $locale->getText('console.functions.function.modal-deploy-tag-manual-button-submit'); ?></button> &nbsp; <button data-ui-modal-close="" type="button" class="reverse"><?php echo $locale->getText('console.functions.function.modal-deploy-tag-manual-button-cancel'); ?></button>
                </footer>
            </form>
        </li>
    </ul>


    
</div>
