/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LibRouteImport } from './routes/$lib'
import { Route as LibIndexRouteImport } from './routes/$lib/index'
import { Route as LibCasesRouteImport } from './routes/$lib/cases'
import { Route as LibDocsRouteImport } from './routes/$lib/docs'
import { Route as LibFuzzRouteImport } from './routes/$lib/fuzz'
import { Route as LibInterfaceRouteImport } from './routes/$lib/interface'
import { Route as LibRustRouteImport } from './routes/$lib/rust'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LibRoute = LibRouteImport.update({
  id: '/$lib',
  path: '/$lib',
  getParentRoute: () => rootRouteImport,
} as any)
const LibIndexRoute = LibIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LibRoute,
} as any)
const LibCasesRoute = LibCasesRouteImport.update({
  id: '/cases',
  path: '/cases',
  getParentRoute: () => LibRoute,
} as any)
const LibDocsRoute = LibDocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => LibRoute,
} as any)
const LibFuzzRoute = LibFuzzRouteImport.update({
  id: '/fuzz',
  path: '/fuzz',
  getParentRoute: () => LibRoute,
} as any)
const LibInterfaceRoute = LibInterfaceRouteImport.update({
  id: '/interface',
  path: '/interface',
  getParentRoute: () => LibRoute,
} as any)
const LibRustRoute = LibRustRouteImport.update({
  id: '/rust',
  path: '/rust',
  getParentRoute: () => LibRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$lib': typeof LibRouteWithChildren
  '/$lib/cases': typeof LibCasesRoute
  '/$lib/docs': typeof LibDocsRoute
  '/$lib/fuzz': typeof LibFuzzRoute
  '/$lib/interface': typeof LibInterfaceRoute
  '/$lib/rust': typeof LibRustRoute
  '/$lib/': typeof LibIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$lib/cases': typeof LibCasesRoute
  '/$lib/docs': typeof LibDocsRoute
  '/$lib/fuzz': typeof LibFuzzRoute
  '/$lib/interface': typeof LibInterfaceRoute
  '/$lib/rust': typeof LibRustRoute
  '/$lib': typeof LibIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$lib': typeof LibRouteWithChildren
  '/$lib/cases': typeof LibCasesRoute
  '/$lib/docs': typeof LibDocsRoute
  '/$lib/fuzz': typeof LibFuzzRoute
  '/$lib/interface': typeof LibInterfaceRoute
  '/$lib/rust': typeof LibRustRoute
  '/$lib/': typeof LibIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$lib'
    | '/$lib/cases'
    | '/$lib/docs'
    | '/$lib/fuzz'
    | '/$lib/interface'
    | '/$lib/rust'
    | '/$lib/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$lib/cases'
    | '/$lib/docs'
    | '/$lib/fuzz'
    | '/$lib/interface'
    | '/$lib/rust'
    | '/$lib'
  id:
    | '__root__'
    | '/'
    | '/$lib'
    | '/$lib/cases'
    | '/$lib/docs'
    | '/$lib/fuzz'
    | '/$lib/interface'
    | '/$lib/rust'
    | '/$lib/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LibRoute: typeof LibRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lib': {
      id: '/$lib'
      path: '/$lib'
      fullPath: '/$lib'
      preLoaderRoute: typeof LibRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lib/': {
      id: '/$lib/'
      path: '/'
      fullPath: '/$lib/'
      preLoaderRoute: typeof LibIndexRouteImport
      parentRoute: typeof LibRoute
    }
    '/$lib/cases': {
      id: '/$lib/cases'
      path: '/cases'
      fullPath: '/$lib/cases'
      preLoaderRoute: typeof LibCasesRouteImport
      parentRoute: typeof LibRoute
    }
    '/$lib/docs': {
      id: '/$lib/docs'
      path: '/docs'
      fullPath: '/$lib/docs'
      preLoaderRoute: typeof LibDocsRouteImport
      parentRoute: typeof LibRoute
    }
    '/$lib/fuzz': {
      id: '/$lib/fuzz'
      path: '/fuzz'
      fullPath: '/$lib/fuzz'
      preLoaderRoute: typeof LibFuzzRouteImport
      parentRoute: typeof LibRoute
    }
    '/$lib/interface': {
      id: '/$lib/interface'
      path: '/interface'
      fullPath: '/$lib/interface'
      preLoaderRoute: typeof LibInterfaceRouteImport
      parentRoute: typeof LibRoute
    }
    '/$lib/rust': {
      id: '/$lib/rust'
      path: '/rust'
      fullPath: '/$lib/rust'
      preLoaderRoute: typeof LibRustRouteImport
      parentRoute: typeof LibRoute
    }
  }
}

interface LibRouteChildren {
  LibCasesRoute: typeof LibCasesRoute
  LibDocsRoute: typeof LibDocsRoute
  LibFuzzRoute: typeof LibFuzzRoute
  LibInterfaceRoute: typeof LibInterfaceRoute
  LibRustRoute: typeof LibRustRoute
  LibIndexRoute: typeof LibIndexRoute
}

const LibRouteChildren: LibRouteChildren = {
  LibCasesRoute: LibCasesRoute,
  LibDocsRoute: LibDocsRoute,
  LibFuzzRoute: LibFuzzRoute,
  LibInterfaceRoute: LibInterfaceRoute,
  LibRustRoute: LibRustRoute,
  LibIndexRoute: LibIndexRoute,
}

const LibRouteWithChildren = LibRoute._addFileChildren(LibRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LibRoute: LibRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
