import type { SettingsCardIndexEntry } from '@/lib/settings-search'

/** Shared keywords for SOC 2 / SOC II compliance search (settings sidebar + cards). */
export const SOC2_SETTINGS_KEYWORDS: string[] = [
  'soc',
  'soc2',
  'soc-2',
  'soc 2',
  'soc ii',
  'soc-ii',
  'soc2 type ii',
  'soc 2 type ii',
  'soc-2 type ii',
  'soc2 type 2',
  'soc 2 type 2',
  'soc-2 type 2',
  'type ii',
  'type 2',
  'type-ii',
  'type-2',
  'service organization control',
  'service organisation control',
  'trust services',
  'trust services criteria',
  'aicpa',
  'audit',
  'audit report',
  'security audit',
  'compliance report',
  'security report',
  'certified',
  'certification',
  'enterprise',
  'security',
  'security controls',
  'auditing standard',
  'vendor compliance',
  'regulated',
  'contact sales',
]

export const ORG_SETTINGS_CARD_INDEX: SettingsCardIndexEntry[] = [
  {
    sectionId: 'overview',
    title: 'Organization ID',
    keywords: ['id', 'api', 'webhook', 'sdk', 'copy'],
  },
  {
    sectionId: 'overview',
    title: 'Organization name',
    keywords: ['rename', 'display name'],
  },
  {
    sectionId: 'overview',
    title: 'Delete organization',
    keywords: ['delete', 'remove', 'destroy', 'danger'],
  },
  {
    sectionId: 'billing',
    title: 'Current plan',
    keywords: [
      'plan',
      'subscription',
      'tier',
      'upgrade',
      'downgrade',
      'change plan',
      'pro',
      'scale',
      'core',
      'free',
      'next payment',
      'charges',
      'billing cycle',
    ],
  },
  {
    sectionId: 'billing',
    title: 'Payment history',
    keywords: ['invoice', 'invoices', 'receipt', 'payment history', 'paid'],
  },
  {
    sectionId: 'billing',
    title: 'Payment methods',
    keywords: [
      'card',
      'credit card',
      'stripe',
      'backup',
      'default payment',
      'payment method',
    ],
  },
  {
    sectionId: 'billing',
    title: 'Billing address',
    keywords: ['address', 'country', 'city', 'postal', 'zip', 'street'],
  },
  {
    sectionId: 'billing',
    title: 'Tax ID',
    keywords: ['vat', 'tax', 'ein', 'gst', 'identification'],
  },
  {
    sectionId: 'billing',
    title: 'Budget cap',
    keywords: ['budget', 'spending limit', 'cap', 'overage', 'usage limit'],
  },
  {
    sectionId: 'billing',
    title: 'Billing alerts',
    keywords: ['alerts', 'threshold', 'notification', 'usage', 'email alert'],
  },
  {
    sectionId: 'billing',
    title: 'Available credits',
    keywords: ['credits', 'balance', 'coupon', 'promo', 'prepaid'],
  },
  {
    sectionId: 'billing',
    title: 'Payment failed',
    keywords: ['failed', 'retry', 'outstanding', 'read-only'],
  },
  {
    sectionId: 'billing',
    title: 'Payment method failed',
    keywords: ['expired', 'declined', 'failed card'],
  },
  {
    sectionId: 'billing',
    title: 'Plan downgrade scheduled',
    keywords: ['downgrade', 'scheduled', 'end of period'],
  },
  {
    sectionId: 'compliance',
    title: 'Data processing agreement (DPA)',
    keywords: ['dpa', 'gdpr', 'legal', 'data processing'],
  },
  {
    sectionId: 'compliance',
    title: 'Business associate agreement (BAA)',
    keywords: ['baa', 'hipaa', 'phi', 'healthcare'],
  },
  {
    sectionId: 'compliance',
    title: 'SOC 2 type II report',
    keywords: [...SOC2_SETTINGS_KEYWORDS],
  },
  {
    sectionId: 'api-keys',
    title: 'API key types',
    keywords: ['project keys', 'account keys', 'org keys', 'scopes'],
  },
  {
    sectionId: 'api-keys',
    title: 'Project keys',
    keywords: ['database', 'storage', 'functions'],
  },
  {
    sectionId: 'api-keys',
    title: 'Account keys',
    keywords: ['cli', 'sessions', 'user'],
  },
  {
    sectionId: 'api-keys',
    title: 'Org keys',
    keywords: ['billing', 'team', 'organization'],
  },
]
