/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LibRouteImport } from './routes/$lib'
import { Route as LibIndexRouteImport } from './routes/$lib/index'
import { Route as LibSplatRouteImport } from './routes/$lib/$'
import { Route as CategoriesCategoryRouteImport } from './routes/categories/$category'
import { Route as LibPhpSplatRouteImport } from './routes/$lib/php/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LibRoute = LibRouteImport.update({
  id: '/$lib',
  path: '/$lib',
  getParentRoute: () => rootRouteImport,
} as any)
const LibIndexRoute = LibIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LibRoute,
} as any)
const LibSplatRoute = LibSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => LibRoute,
} as any)
const CategoriesCategoryRoute = CategoriesCategoryRouteImport.update({
  id: '/categories/$category',
  path: '/categories/$category',
  getParentRoute: () => rootRouteImport,
} as any)
const LibPhpSplatRoute = LibPhpSplatRouteImport.update({
  id: '/php/$',
  path: '/php/$',
  getParentRoute: () => LibRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$lib': typeof LibRouteWithChildren
  '/$lib/$': typeof LibSplatRoute
  '/categories/$category': typeof CategoriesCategoryRoute
  '/$lib/': typeof LibIndexRoute
  '/$lib/php/$': typeof LibPhpSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$lib/$': typeof LibSplatRoute
  '/categories/$category': typeof CategoriesCategoryRoute
  '/$lib': typeof LibIndexRoute
  '/$lib/php/$': typeof LibPhpSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$lib': typeof LibRouteWithChildren
  '/$lib/$': typeof LibSplatRoute
  '/categories/$category': typeof CategoriesCategoryRoute
  '/$lib/': typeof LibIndexRoute
  '/$lib/php/$': typeof LibPhpSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$lib'
    | '/$lib/$'
    | '/categories/$category'
    | '/$lib/'
    | '/$lib/php/$'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$lib/$' | '/categories/$category' | '/$lib' | '/$lib/php/$'
  id:
    | '__root__'
    | '/'
    | '/$lib'
    | '/$lib/$'
    | '/categories/$category'
    | '/$lib/'
    | '/$lib/php/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LibRoute: typeof LibRouteWithChildren
  CategoriesCategoryRoute: typeof CategoriesCategoryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lib': {
      id: '/$lib'
      path: '/$lib'
      fullPath: '/$lib'
      preLoaderRoute: typeof LibRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lib/': {
      id: '/$lib/'
      path: '/'
      fullPath: '/$lib/'
      preLoaderRoute: typeof LibIndexRouteImport
      parentRoute: typeof LibRoute
    }
    '/$lib/$': {
      id: '/$lib/$'
      path: '/$'
      fullPath: '/$lib/$'
      preLoaderRoute: typeof LibSplatRouteImport
      parentRoute: typeof LibRoute
    }
    '/categories/$category': {
      id: '/categories/$category'
      path: '/categories/$category'
      fullPath: '/categories/$category'
      preLoaderRoute: typeof CategoriesCategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lib/php/$': {
      id: '/$lib/php/$'
      path: '/php/$'
      fullPath: '/$lib/php/$'
      preLoaderRoute: typeof LibPhpSplatRouteImport
      parentRoute: typeof LibRoute
    }
  }
}

interface LibRouteChildren {
  LibSplatRoute: typeof LibSplatRoute
  LibIndexRoute: typeof LibIndexRoute
  LibPhpSplatRoute: typeof LibPhpSplatRoute
}

const LibRouteChildren: LibRouteChildren = {
  LibSplatRoute: LibSplatRoute,
  LibIndexRoute: LibIndexRoute,
  LibPhpSplatRoute: LibPhpSplatRoute,
}

const LibRouteWithChildren = LibRoute._addFileChildren(LibRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LibRoute: LibRouteWithChildren,
  CategoriesCategoryRoute: CategoriesCategoryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
