//! PHP `Utopia\Query\Schema\ColumnType`.

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum ColumnType {
    String,
    Varchar,
    Text,
    MediumText,
    LongText,
    TinyInteger,
    SmallInteger,
    Integer,
    BigInteger,
    Float,
    Double,
    Decimal,
    Boolean,
    Datetime,
    Timestamp,
    Json,
    Binary,
    Enum,
    Point,
    Linestring,
    Polygon,
    Vector,
    Id,
    Uuid,
    Uuid7,
    Object,
    Relationship,
    Serial,
    BigSerial,
    SmallSerial,
    Array,
    Tuple,
}

impl ColumnType {
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::String => "string",
            Self::Varchar => "varchar",
            Self::Text => "text",
            Self::MediumText => "mediumtext",
            Self::LongText => "longtext",
            Self::TinyInteger => "tinyinteger",
            Self::SmallInteger => "smallinteger",
            Self::Integer => "integer",
            Self::BigInteger => "biginteger",
            Self::Float => "float",
            Self::Double => "double",
            Self::Decimal => "decimal",
            Self::Boolean => "boolean",
            Self::Datetime => "datetime",
            Self::Timestamp => "timestamp",
            Self::Json => "json",
            Self::Binary => "binary",
            Self::Enum => "enum",
            Self::Point => "point",
            Self::Linestring => "linestring",
            Self::Polygon => "polygon",
            Self::Vector => "vector",
            Self::Id => "id",
            Self::Uuid => "uuid",
            Self::Uuid7 => "uuid7",
            Self::Object => "object",
            Self::Relationship => "relationship",
            Self::Serial => "serial",
            Self::BigSerial => "bigserial",
            Self::SmallSerial => "smallserial",
            Self::Array => "array",
            Self::Tuple => "tuple",
        }
    }
}
