<?php

use Appwrite\Database\Database;

$collections = [
    'movies' => [
        '$collection' => Database::COLLECTION_COLLECTIONS,
        '$permissions' => ['read' => ['*']],
        'name' => 'Movies',
        'rules' => [
            [
                '$collection' => Database::COLLECTION_RULES,
                '$permissions' => ['read' => ['*']],
                'label' => 'Name',
                'key' => 'name',
                'type' => Database::VAR_TEXT,
                'default' => '',
                'required' => true,
                'array' => false,
            ],
            [
                '$collection' => Database::COLLECTION_RULES,
                '$permissions' => ['read' => ['*']],
                'label' => 'Release Year',
                'key' => 'releaseYear',
                'type' => Database::VAR_INTEGER,
                'default' => 0,
                'required' => true,
                'array' => false,
            ],
            [
                '$collection' => Database::COLLECTION_RULES,
                '$permissions' => ['read' => ['*']],
                'label' => 'Director',
                'key' => 'director',
                'type' => Database::VAR_TEXT,
                'default' => '',
                'required' => true,
                'array' => false,
            ],
            [
                '$collection' => Database::COLLECTION_RULES,
                '$permissions' => ['read' => ['*']],
                'label' => 'Generes',
                'key' => 'generes',
                'type' => Database::VAR_TEXT,
                'default' => '',
                'required' => true,
                'array' => true,
            ],
            [
                '$collection' => Database::COLLECTION_RULES,
                '$permissions' => ['read' => ['*']],
                'label' => 'Langauges',
                'key' => 'langauges',
                'type' => Database::VAR_TEXT,
                'default' => '',
                'required' => true,
                'array' => true,
            ],
        ]
    ]
];

$movies = [
    [
        'name' => '',
        'releaseYear' => '',
        'director' => '',
        'generes' => [],
        'langauges' => [],
    ],
    [
        'name' => 'Shang-Chi and the Legend of the Ten Rings',
        'releaseYear' => '2021',
        'director' => 'Destin Daniel Cretton',
        'generes' => ['Action', 'Adventure'],
        'langauges' => ['English'],
    ],
     [
        'name' => 'The Eternals',
        'releaseYear' => '2021',
        'director' => 'Chloé Zhao',
        'generes' => ['Action', 'Adventure'],
        'langauges' => ['English'],
    ],
     [
        'name' => 'The New Mutants',
        'releaseYear' => '2020',
        'director' => 'Josh Boone',
        'generes' => ['Action', 'Adventure'],
        'langauges' => ['English'],
    ],
    [
        'name' => 'Black Widow',
        'releaseYear' => '2020',
        'director' => 'Cate Shortland',
        'generes' => ['Action', 'Adventure'],
        'langauges' => ['English'],
    ],
     [
        'name' => 'Captain Marvel',
        'releaseYear' => '2019',
        'director' => 'Anna Boden, Ryan Fleck',
        'generes' => ['Action', 'Adventure'],
        'langauges' => ['English'],
    ],
      [
        'name' => 'Avengers: Endgame',
        'releaseYear' => '2019',
        'director' => 'Joe Russo, Anthony Russo',
        'generes' => ['Action', 'Adventure'],
        'langauges' => ['English'],
    ],
    [
        'name' => 'X-Men: Dark Phoenix',
        'releaseYear' => '2019',
        'director' => 'Simon Kinberg',
        'generes' => ['Action', 'Adventure'],
        'langauges' => ['English'],
    ],
      
    [
        'name' => 'Black Panther',
        'releaseYear' => '2018',
        'director' => 'Ryan Coogler',
        'generes' => ['Action', 'Adventure'],
        'langauges' => ['Xhosa', 'English', 'Korean', 'Swahili'],
    ],
    [
        'name' => 'Venom',
        'releaseYear' => '2018',
        'director' => 'Ruben Fleischer',
        'generes' => ['Action', 'Adventure'],
        'langauges' => ['English'],
    ],
    [
        'name' => 'Avengers: Infinity War',
        'releaseYear' => '2018',
        'director' => 'Joe Russo, Anthony Russo',
        'generes' => ['Action', 'Adventure'],
        'langauges' => ['English'],
    ],
      [
        'name' => 'Ant-Man and the Wasp',
        'releaseYear' => '2018',
        'director' => 'Peyton Reed',
        'generes' => ['Action', 'Adventure'],
        'langauges' => ['English'],
    ],
      [
        'name' => 'Spider-Man: Homecoming',
        'releaseYear' => '2017',
        'director' => 'Jon Watts',
        'generes' => ['Action', 'Adventure'],
        'langauges' => ['English'],
    ],
      [
        'name' => 'Spider-Man: Far From Home',
        'releaseYear' => '2019',
        'director' => 'Jon Watts',
        'generes' => ['Action', 'Adventure'],
        'langauges' => ['English'],
    ],
     [
        'name' => 'Spider-Man: Into the Spider-Verse',
        'releaseYear' => '2018',
        'director' => 'Peter Ramsey, Rodney Rothman, Bob Persichetti',
        'generes' => ['Action', 'Adventure'],
        'langauges' => ['English'],
    ],
    [
        'name' => 'Deadpool 2',
        'releaseYear' => '2018',
        'director' => 'David Leitch',
        'generes' => ['Action', 'Adventure'],
        'langauges' => ['English'],
    ],
      [
        'name' => 'Thor: Ragnarok',
        'releaseYear' => '2017',
        'director' => 'Taika Waititi',
        'generes' => ['Action', 'Adventure'],
        'langauges' => ['English'],
    ],
      [
        'name' => 'Guardians of the Galaxy Vol. 2',
        'releaseYear' => '2017',
        'director' => 'James Gunn',
        'generes' => ['Action', 'Adventure'],
        'langauges' => ['English'],
    ],
     [
        'name' => 'Logan',
        'releaseYear' => '2017',
        'director' => 'James Mangold',
        'generes' => ['Action', 'Adventure'],
        'langauges' => ['English'],
    ],
  
      [
        'name' => 'Doctor Strange',
        'releaseYear' => '2016',
        'director' => 'Scott Derrickson',
        'generes' => ['Action', 'Adventure'],
        'langauges' => ['English'],
    ],
    [
        'name' => 'Captain America: Civil War',
        'releaseYear' => '2016',
        'director' => 'Joe Russo, Anthony Russo',
        'generes' => ['Action', 'Adventure'],
        'langauges' => ['English'],
    ],
    [
        'name' => 'Doctor Strange',
        'releaseYear' => '2016',
        'director' => 'Scott Derrickson',
        'generes' => ['Action', 'Adventure'],
        'langauges' => ['English'],
    ],
    [
        'name' => 'Deadpool',
        'releaseYear' => '2016',
        'director' => 'Tim Miller',
        'generes' => ['Action', 'Adventure'],
        'langauges' => ['English'],
    ],
    [
        'name' => 'Avengers: Age of Ultron',
        'releaseYear' => '2015',
        'director' => 'Joss Whedon',
        'generes' => ['Action', 'Adventure'],
        'langauges' => ['English'],
    ],
    [
        'name' => 'Ant-Man',
        'releaseYear' => '2015',
        'director' => 'Peyton Reed',
        'generes' => ['Action', 'Adventure'],
        'langauges' => ['English'],
    ],
    [
        'name' => 'Guardians of the Galaxy',
        'releaseYear' => '2014',
        'director' => 'James Gunn',
        'generes' => ['Action', 'Adventure'],
        'langauges' => ['English'],
    ],
    [
        'name' => 'Captain America: The Winter Soldier',
        'releaseYear' => '2014',
        'director' => 'Joe Russo, Anthony Russo',
        'generes' => ['Action', 'Adventure'],
        'langauges' => ['English'],
    ],
    [
        'name' => 'Iron Man 3',
        'releaseYear' => '2013',
        'director' => 'Shane Black',
        'generes' => ['Action', 'Adventure'],
        'langauges' => ['English'],
    ],
    [
        'name' => 'Thor: The Dark World',
        'releaseYear' => '2013',
        'director' => 'Alan Taylor',
        'generes' => ['Action', 'Adventure'],
        'langauges' => ['English'],
    ],
    [
        'name' => 'The Avengers',
        'releaseYear' => '2012',
        'director' => 'Joss Whedon',
        'generes' => ['Action', 'Adventure'],
        'langauges' => ['English'],
    ],
    [
        'name' => 'Captain America: The First Avenger',
        'releaseYear' => '2011',
        'director' => 'Joe Johnston',
        'generes' => ['Action', 'Adventure'],
        'langauges' => ['English'],
    ],
    [
        'name' => 'Thor',
        'releaseYear' => '2011',
        'director' => 'Kenneth Branagh',
        'generes' => ['Action', 'Adventure'],
        'langauges' => ['English'],
    ],
    [
        'name' => 'X-Men: First Class',
        'releaseYear' => '2011',
        'director' => 'Matthew Vaughn',
        'generes' => ['Action', 'Adventure'],
        'langauges' => ['English'],
    ],
    [
        'name' => 'Iron Man 2',
        'releaseYear' => '2010',
        'director' => 'Jon Favreau',
        'generes' => ['Action', 'Adventure'],
        'langauges' => ['English'],
    ],
     [
        'name' => 'Iron Man',
        'releaseYear' => '2008',
        'director' => 'Jon Favreau',
        'generes' => ['Action', 'Adventure'],
        'langauges' => ['English'],
    ],
     [
        'name' => 'The Incredible Hulk',
        'releaseYear' => '2008',
        'director' => 'Louis Leterrier',
        'generes' => ['Action', 'Adventure'],
        'langauges' => ['English'],
    ],
     [
        'name' => 'Elektra',
        'releaseYear' => '2005',
        'director' => 'Rob Bowman',
        'generes' => ['Action', 'Adventure'],
        'langauges' => ['English'],
    ],
   
    
    
];

