<?php

namespace Utopia\Query\Schema;

use Utopia\Query\Builder\Statement;
use Utopia\Query\Exception\UnsupportedException;
use Utopia\Query\Exception\ValidationException;
use Utopia\Query\Schema\Feature\AnalyzeTable;
use Utopia\Query\Schema\Feature\ColumnComments;
use Utopia\Query\Schema\Feature\CreatePartition;
use Utopia\Query\Schema\Feature\Databases;
use Utopia\Query\Schema\Feature\DropPartition;
use Utopia\Query\Schema\Feature\ForeignKeys;
use Utopia\Query\Schema\Feature\Partitioning;
use Utopia\Query\Schema\Feature\Procedures;
use Utopia\Query\Schema\Feature\RenameIndex;
use Utopia\Query\Schema\Feature\ReplaceView;
use Utopia\Query\Schema\Feature\Sequences;
use Utopia\Query\Schema\Feature\TableComments;
use Utopia\Query\Schema\Feature\Triggers;
use Utopia\Query\Schema\Feature\Types;
use Utopia\Query\Schema\Feature\Views;

class PostgreSQL extends SQL implements
    ForeignKeys,
    Procedures,
    Triggers,
    Types,
    Sequences,
    TableComments,
    ColumnComments,
    CreatePartition,
    DropPartition,
    Views,
    ReplaceView,
    Databases,
    RenameIndex,
    AnalyzeTable,
    Partitioning
{
    use Trait\ForeignKeys;
    use Trait\Partitioning;
    use Trait\Procedures;
    use Trait\ReplaceView;
    use Trait\Triggers;
    use Trait\Views;

    protected string $wrapChar = '"';

    #[\Override]
    public function table(string $name): Table\PostgreSQL
    {
        return new Table\PostgreSQL($this, $name);
    }

    protected function compileColumnType(Column $column): string
    {
        if ($column->userTypeName !== null) {
            return $this->quote($column->userTypeName);
        }

        return match ($column->type) {
            ColumnType::String, ColumnType::Varchar, ColumnType::Relationship => 'VARCHAR(' . ($column->length ?? 255) . ')',
            ColumnType::Text, ColumnType::MediumText, ColumnType::LongText => 'TEXT',
            ColumnType::TinyInteger, ColumnType::SmallInteger => 'SMALLINT',
            ColumnType::Integer => 'INTEGER',
            ColumnType::BigInteger, ColumnType::Id => 'BIGINT',
            ColumnType::Float, ColumnType::Double => 'DOUBLE PRECISION',
            ColumnType::Decimal => 'DECIMAL(' . ($column->precision ?? 10) . ', ' . ($column->scale ?? 0) . ')',
            ColumnType::Boolean => 'BOOLEAN',
            ColumnType::Datetime => $column->precision ? 'TIMESTAMP(' . $column->precision . ')' : 'TIMESTAMP',
            ColumnType::Timestamp => $column->precision ? 'TIMESTAMP(' . $column->precision . ') WITHOUT TIME ZONE' : 'TIMESTAMP WITHOUT TIME ZONE',
            ColumnType::Json, ColumnType::Object => 'JSONB',
            ColumnType::Binary => 'BYTEA',
            ColumnType::Enum => 'TEXT',
            ColumnType::Point => 'GEOMETRY(POINT' . ($column->srid !== null ? ', ' . $column->srid : '') . ')',
            ColumnType::Linestring => 'GEOMETRY(LINESTRING' . ($column->srid !== null ? ', ' . $column->srid : '') . ')',
            ColumnType::Polygon => 'GEOMETRY(POLYGON' . ($column->srid !== null ? ', ' . $column->srid : '') . ')',
            ColumnType::Uuid => 'UUID',
            ColumnType::Uuid7 => 'VARCHAR(36)',
            ColumnType::Vector => 'VECTOR(' . ($column->dimensions ?? 0) . ')',
            ColumnType::Serial => 'SERIAL',
            ColumnType::BigSerial => 'BIGSERIAL',
            ColumnType::SmallSerial => 'SMALLSERIAL',
            ColumnType::Array, ColumnType::Tuple => throw new UnsupportedException('Array/Tuple column types are not supported in PostgreSQL.'),
        };
    }

    protected function compileAutoIncrement(): string
    {
        return 'GENERATED BY DEFAULT AS IDENTITY';
    }

    #[\Override]
    protected function quoteCollation(string $collation): string
    {
        return $this->quote($collation);
    }

    protected function compileUnsigned(): string
    {
        return '';
    }

    protected function compileColumnDefinition(Column $column): string
    {
        $parts = [
            $this->quoteLiteral($column->name),
            $this->compileColumnType($column),
        ];

        if ($column->collation !== null) {
            $parts[] = 'COLLATE ' . $this->quoteCollation($column->collation);
        }

        if ($column->isUnsigned) {
            $unsigned = $this->compileUnsigned();
            if ($unsigned !== '') {
                $parts[] = $unsigned;
            }
        }

        if ($column->generatedExpression !== null) {
            $parts[] = $this->compileGeneratedClause($column);

            if (! $column->isNullable) {
                $parts[] = 'NOT NULL';
            } else {
                $parts[] = 'NULL';
            }

            if ($column->checkExpression !== null) {
                $parts[] = 'CHECK (' . $column->checkExpression . ')';
            }

            return \implode(' ', $parts);
        }

        $isSerial = $column->type === ColumnType::Serial
            || $column->type === ColumnType::BigSerial
            || $column->type === ColumnType::SmallSerial;

        if ($column->isAutoIncrement && ! $isSerial) {
            $parts[] = $this->compileAutoIncrement();
        }

        if (! $column->isNullable) {
            $parts[] = 'NOT NULL';
        } else {
            $parts[] = 'NULL';
        }

        if ($column->defaultRaw !== null) {
            $parts[] = 'DEFAULT ' . $column->defaultRaw;
        } elseif ($column->hasDefault) {
            $parts[] = 'DEFAULT ' . $this->compileDefaultValue($column->default);
        }

        // PostgreSQL enum emulation via CHECK constraint
        if ($column->type === ColumnType::Enum && ! empty($column->enumValues)) {
            $values = \array_map(fn (string $v): string => "'" . \str_replace(['\\', "'"], ['\\\\', "''"], $v) . "'", $column->enumValues);
            $parts[] = 'CHECK (' . $this->quoteLiteral($column->name) . ' IN (' . \implode(', ', $values) . '))';
        }

        if ($column->checkExpression !== null) {
            $parts[] = 'CHECK (' . $column->checkExpression . ')';
        }

        // No inline COMMENT in PostgreSQL (use COMMENT ON COLUMN separately)

        return \implode(' ', $parts);
    }

    /**
     * PostgreSQL supports STORED generated columns only, which is why
     * {@see Column\PostgreSQL} does not expose virtual().
     */
    #[\Override]
    protected function compileGeneratedClause(Column $column): string
    {
        return 'GENERATED ALWAYS AS (' . $column->generatedExpression . ') STORED';
    }

    /**
     * @param  string[]  $columns
     * @param  array<string, int>  $lengths
     * @param  array<string, string>  $orders
     * @param  array<string, string>  $collations
     * @param  list<string>  $rawColumns
     */
    public function createIndex(
        string $table,
        string $name,
        array $columns,
        bool $unique = false,
        string $type = '',
        string $method = '',
        string $operatorClass = '',
        array $lengths = [],
        array $orders = [],
        array $collations = [],
        array $rawColumns = [],
        bool $concurrently = false,
    ): Statement {
        if ($method !== '' && ! \preg_match('/^[A-Za-z0-9_]+$/', $method)) {
            throw new ValidationException('Invalid index method: ' . $method);
        }
        if ($operatorClass !== '' && ! \preg_match('/^[A-Za-z0-9_.]+$/', $operatorClass)) {
            throw new ValidationException('Invalid operator class: ' . $operatorClass);
        }

        $keyword = $unique ? 'CREATE UNIQUE INDEX' : 'CREATE INDEX';

        if ($concurrently) {
            $keyword .= ' CONCURRENTLY';
        }

        $sql = $keyword . ' ' . $this->quote($name)
            . ' ON ' . $this->quote($table);

        if ($method !== '') {
            $sql .= ' USING ' . \strtoupper($method);
        }

        $indexType = $unique ? IndexType::Unique : ($type !== '' ? IndexType::from($type) : IndexType::Index);
        $index = new Index($name, $columns, $indexType, $lengths, $orders, $method, $operatorClass, $collations, $rawColumns);

        $sql .= ' (' . $this->compileIndexColumns($index) . ')';

        return new Statement($sql, [], executor: $this->executor);
    }

    public function dropIndex(string $table, string $name): Statement
    {
        return new Statement(
            'DROP INDEX ' . $this->quote($name),
            [],
            executor: $this->executor,
        );
    }

    public function dropForeignKey(string $table, string $name): Statement
    {
        return new Statement(
            'ALTER TABLE ' . $this->quote($table)
            . ' DROP CONSTRAINT ' . $this->quote($name),
            [],
            executor: $this->executor,
        );
    }

    /**
     * Create a PL/pgSQL function.
     *
     * $body is emitted verbatim inside a dollar-quoted ($$...$$) block and must
     * come from trusted (developer-controlled) source — never from untrusted
     * input. A literal `$$` inside the body would close the dollar-quoted
     * string early and is rejected.
     *
     * @param  list<array{0: ParameterDirection, 1: string, 2: string}>  $params
     *
     * @throws ValidationException if $body contains a `$$` sequence.
     */
    public function createProcedure(string $name, array $params, string $body): Statement
    {
        $this->assertSafeDollarQuotedBody($body);

        $paramList = $this->compileProcedureParams($params);

        $sql = 'CREATE FUNCTION ' . $this->quote($name)
            . '(' . \implode(', ', $paramList) . ')'
            . ' RETURNS VOID LANGUAGE plpgsql AS $$ BEGIN ' . $body . ' END; $$';

        return new Statement($sql, [], executor: $this->executor);
    }

    public function dropProcedure(string $name): Statement
    {
        return new Statement('DROP FUNCTION ' . $this->quote($name) . '()', [], executor: $this->executor);
    }

    /**
     * Create a trigger backed by a PL/pgSQL function.
     *
     * $body is emitted verbatim inside a dollar-quoted ($$...$$) block and must
     * come from trusted (developer-controlled) source — never from untrusted
     * input. A literal `$$` inside the body would close the dollar-quoted
     * string early and is rejected.
     *
     * @throws ValidationException if $body contains a `$$` sequence.
     */
    public function createTrigger(
        string $name,
        string $table,
        TriggerTiming $timing,
        TriggerEvent $event,
        string $body,
    ): Statement {
        $this->assertSafeDollarQuotedBody($body);

        $funcName = $name . '_func';

        $sql = 'CREATE FUNCTION ' . $this->quote($funcName)
            . '() RETURNS TRIGGER LANGUAGE plpgsql AS $$ BEGIN ' . $body . ' RETURN NEW; END; $$; '
            . 'CREATE TRIGGER ' . $this->quote($name)
            . ' ' . $timing->value . ' ' . $event->value
            . ' ON ' . $this->quote($table)
            . ' FOR EACH ROW EXECUTE FUNCTION ' . $this->quote($funcName) . '()';

        return new Statement($sql, [], executor: $this->executor);
    }

    /**
     * Drop a trigger and its backing PL/pgSQL function. PostgreSQL requires
     * the table name (`DROP TRIGGER name ON table`); the function created by
     * {@see createTrigger()} is dropped at the same time so callers don't need
     * a separate {@see dropFunction()} call.
     *
     * @throws ValidationException if $table is null.
     */
    #[\Override]
    public function dropTrigger(string $name, ?string $table = null): Statement
    {
        if ($table === null) {
            throw new ValidationException('PostgreSQL dropTrigger() requires the table name.');
        }

        $funcName = $name . '_func';

        $sql = 'DROP TRIGGER ' . $this->quote($name) . ' ON ' . $this->quote($table)
            . '; DROP FUNCTION ' . $this->quote($funcName) . '()';

        return new Statement($sql, [], executor: $this->executor);
    }

    /**
     * Reject bodies that would break out of the surrounding `$$ ... $$`
     * dollar-quoted string.
     *
     * @throws ValidationException if $body contains `$$`.
     */
    private function assertSafeDollarQuotedBody(string $body): void
    {
        if (\str_contains($body, '$$')) {
            throw new ValidationException('Procedure/trigger body must not contain the dollar-quote terminator "$$"');
        }
    }

    #[\Override]
    public function compileAlter(Table $table): Statement
    {
        $alterations = [];

        foreach ($table->columns as $column) {
            $keyword = $column->isModify ? 'ALTER COLUMN' : 'ADD COLUMN';
            if ($column->isModify) {
                $def = $keyword . ' ' . $this->quoteLiteral($column->name)
                    . ' TYPE ' . $this->compileColumnType($column);
            } else {
                $def = $keyword . ' ' . $this->compileColumnDefinition($column);
            }
            $alterations[] = $def;
        }

        foreach ($table->renameColumns as $rename) {
            $alterations[] = 'RENAME COLUMN ' . $this->quoteLiteral($rename->from)
                . ' TO ' . $this->quoteLiteral($rename->to);
        }

        foreach ($table->dropColumns as $col) {
            $alterations[] = 'DROP COLUMN ' . $this->quoteLiteral($col);
        }

        foreach ($table->foreignKeys as $fk) {
            $def = 'ADD FOREIGN KEY (' . $this->quoteLiteral($fk->column) . ')'
                . ' REFERENCES ' . $this->quote($fk->refTable)
                . ' (' . $this->quoteLiteral($fk->refColumn) . ')';
            if ($fk->onDelete !== null) {
                $def .= ' ON DELETE ' . $fk->onDelete->toSql();
            }
            if ($fk->onUpdate !== null) {
                $def .= ' ON UPDATE ' . $fk->onUpdate->toSql();
            }
            $alterations[] = $def;
        }

        foreach ($table->dropForeignKeys as $name) {
            $alterations[] = 'DROP CONSTRAINT ' . $this->quote($name);
        }

        $statements = [];

        if (! empty($alterations)) {
            $statements[] = 'ALTER TABLE ' . $this->quote($table->name)
                . ' ' . \implode(', ', $alterations);
        }

        // PostgreSQL indexes are standalone statements, not ALTER TABLE clauses
        foreach ($table->indexes as $index) {
            $keyword = $index->type === IndexType::Unique ? 'CREATE UNIQUE INDEX' : 'CREATE INDEX';

            $indexSql = $keyword . ' ' . $this->quote($index->name)
                . ' ON ' . $this->quote($table->name);

            if ($index->method !== '') {
                $indexSql .= ' USING ' . \strtoupper($index->method);
            }

            $indexSql .= ' (' . $this->compileIndexColumns($index) . ')';
            $statements[] = $indexSql;
        }

        foreach ($table->dropIndexes as $name) {
            $statements[] = 'DROP INDEX ' . $this->quote($name);
        }

        return new Statement(\implode('; ', $statements), [], executor: $this->executor);
    }

    #[\Override]
    public function compileRename(string $from, string $to): Statement
    {
        return new Statement(
            'ALTER TABLE ' . $this->quote($from) . ' RENAME TO ' . $this->quote($to),
            [],
            executor: $this->executor,
        );
    }

    public function createExtension(string $name): Statement
    {
        return new Statement('CREATE EXTENSION IF NOT EXISTS ' . $this->quote($name), [], executor: $this->executor);
    }

    public function dropExtension(string $name): Statement
    {
        return new Statement('DROP EXTENSION IF EXISTS ' . $this->quote($name), [], executor: $this->executor);
    }

    /**
     * Create a collation.
     *
     * @param  array<string, string>  $options  Key-value pairs (e.g. ['provider' => 'icu', 'locale' => 'und-u-ks-level1'])
     */
    public function createCollation(string $name, array $options, bool $deterministic = true): Statement
    {
        $optParts = [];
        foreach ($options as $key => $value) {
            if (! \preg_match('/^[A-Za-z_][A-Za-z0-9_]*$/', $key)) {
                throw new ValidationException('Invalid collation option key: ' . $key);
            }
            $optParts[] = $key . " = '" . \str_replace(['\\', "'"], ['\\\\', "''"], $value) . "'";
        }
        $optParts[] = 'deterministic = ' . ($deterministic ? 'true' : 'false');

        $sql = 'CREATE COLLATION IF NOT EXISTS ' . $this->quote($name)
            . ' (' . \implode(', ', $optParts) . ')';

        return new Statement($sql, [], executor: $this->executor);
    }

    public function renameIndex(string $table, string $from, string $to): Statement
    {
        return new Statement(
            'ALTER INDEX ' . $this->quote($from) . ' RENAME TO ' . $this->quote($to),
            [],
            executor: $this->executor,
        );
    }

    /**
     * PostgreSQL uses schemas instead of databases for namespace isolation.
     */
    public function createDatabase(string $name): Statement
    {
        return new Statement('CREATE SCHEMA ' . $this->quote($name), [], executor: $this->executor);
    }

    public function dropDatabase(string $name): Statement
    {
        return new Statement('DROP SCHEMA IF EXISTS ' . $this->quote($name) . ' CASCADE', [], executor: $this->executor);
    }

    public function analyzeTable(string $table): Statement
    {
        return new Statement('ANALYZE ' . $this->quote($table), [], executor: $this->executor);
    }

    /**
     * Alter a column's type with an optional USING expression for type casting.
     *
     * @throws ValidationException if $type or $using contains disallowed characters.
     */
    public function alterColumnType(string $table, string $column, string $type, string $using = ''): Statement
    {
        if (! \preg_match('/^[A-Za-z_][A-Za-z0-9_]*(\s+[A-Za-z_][A-Za-z0-9_]*)*(\s*\(\s*[A-Za-z0-9_,\s]+\s*\))?$/', $type)) {
            throw new ValidationException('Invalid column type: ' . $type);
        }

        if ($using !== '') {
            $this->assertSafeExpression($using, 'USING expression');
        }

        $sql = 'ALTER TABLE ' . $this->quote($table)
            . ' ALTER COLUMN ' . $this->quoteLiteral($column)
            . ' TYPE ' . $type;

        if ($using !== '') {
            $sql .= ' USING ' . $using;
        }

        return new Statement($sql, [], executor: $this->executor);
    }

    /**
     * Alter a column's nullability.
     *
     * Postgres carries NOT NULL through an ALTER COLUMN ... TYPE, so a column
     * that changes between required and optional has to be altered separately.
     */
    public function alterColumnNullable(string $table, string $column, bool $nullable): Statement
    {
        $sql = 'ALTER TABLE ' . $this->quote($table)
            . ' ALTER COLUMN ' . $this->quoteLiteral($column)
            . ($nullable ? ' DROP NOT NULL' : ' SET NOT NULL');

        return new Statement($sql, [], executor: $this->executor);
    }

    /**
     * Reject expressions that could chain additional statements or comments.
     *
     * Partition expressions and USING casts may legitimately contain parens,
     * function calls, and casts, so an allowlist is too restrictive. We reject
     * statement terminators and comment markers instead.
     *
     * @throws ValidationException if $expression is too long or contains a disallowed sequence.
     */
    private function assertSafeExpression(string $expression, string $label): void
    {
        if (\strlen($expression) > 1024) {
            throw new ValidationException($label . ' exceeds 1024 character limit');
        }

        if (\str_contains($expression, ';')
            || \str_contains($expression, '--')
            || \str_contains($expression, '/*')
        ) {
            throw new ValidationException('Invalid ' . $label . ': ' . $expression);
        }
    }

    public function dropIndexConcurrently(string $name): Statement
    {
        return new Statement('DROP INDEX CONCURRENTLY ' . $this->quote($name), [], executor: $this->executor);
    }

    public function createType(string $name, array $values): Statement
    {
        $escaped = array_map(fn (string $v): string => "'" . str_replace(['\\', "'"], ['\\\\', "''"], $v) . "'", $values);

        return new Statement(
            'CREATE TYPE ' . $this->quote($name) . ' AS ENUM (' . implode(', ', $escaped) . ')',
            [],
            executor: $this->executor,
        );
    }

    public function dropType(string $name): Statement
    {
        return new Statement('DROP TYPE ' . $this->quote($name), [], executor: $this->executor);
    }

    public function createSequence(string $name, int $start = 1, int $incrementBy = 1): Statement
    {
        return new Statement(
            'CREATE SEQUENCE ' . $this->quote($name) . ' START ' . $start . ' INCREMENT BY ' . $incrementBy,
            [],
            executor: $this->executor,
        );
    }

    public function dropSequence(string $name): Statement
    {
        return new Statement('DROP SEQUENCE ' . $this->quote($name), [], executor: $this->executor);
    }

    public function nextVal(string $name): Statement
    {
        return new Statement(
            "SELECT nextval('" . str_replace(['\\', "'"], ['\\\\', "''"], $name) . "')",
            [],
            executor: $this->executor,
        );
    }

    public function commentOnTable(string $table, string $comment): Statement
    {
        return new Statement(
            'COMMENT ON TABLE ' . $this->quote($table) . " IS '" . str_replace(['\\', "'"], ['\\\\', "''"], $comment) . "'",
            [],
            executor: $this->executor,
        );
    }

    public function commentOnColumn(string $table, string $column, string $comment): Statement
    {
        return new Statement(
            'COMMENT ON COLUMN ' . $this->quote($table) . '.' . $this->quoteLiteral($column) . " IS '" . str_replace(['\\', "'"], ['\\\\', "''"], $comment) . "'",
            [],
            executor: $this->executor,
        );
    }

    /**
     * @throws ValidationException if $expression is too long or contains disallowed sequences.
     */
    public function createPartition(string $parent, string $name, string $expression): Statement
    {
        $this->assertSafeExpression($expression, 'partition expression');

        return new Statement(
            'CREATE TABLE ' . $this->quote($name) . ' PARTITION OF ' . $this->quote($parent) . ' FOR VALUES ' . $expression,
            [],
            executor: $this->executor,
        );
    }

    public function dropPartition(string $table, string $name): Statement
    {
        return new Statement(
            'DROP TABLE ' . $this->quote($name),
            [],
            executor: $this->executor,
        );
    }

    /**
     * PostgreSQL accepts `PARTITION BY {RANGE|LIST|HASH} (expr)` but not the
     * `PARTITIONS N` count modifier — that is MySQL-only. Override the shared
     * trait to omit the count.
     */
    #[\Override]
    public function compileCreatePartitioning(Table $table): string
    {
        if ($table->partitionType === null) {
            return '';
        }

        return 'PARTITION BY ' . $table->partitionType->value . '(' . $table->partitionExpression . ')';
    }
}
