//! The `compat` command. See `tests/compat/README.md`.

pub mod cases;
pub mod compare;
pub mod config;
pub mod coverage;
pub mod crates;
pub mod docs;
pub mod engine;
pub mod examples;
pub mod generate;
pub mod interface;
pub mod process;
pub mod report;
pub mod snapshot;
pub mod spec;
pub mod sync;

use std::path::Path;

use coverage::Coverage;

/// `tests/compat/STATUS.md`: one row per library.
pub fn render_status(rows: &[(String, Option<Coverage>)]) -> String {
    let mut out = String::from(
        "# Utopia conversion status\n\n\
         Generated by `bin/compat status --write` from each library's `tests/compat/<lib>/spec.json`, \
         its cases and both drivers. \"Complete\" means every rule of [crates/CONVERSION.md](../../crates/CONVERSION.md) §2 holds \
         and `bin/compat check` enforces it. Differential runs and fuzzing are not part of this table: CI runs them.\n\n\
         | Library | API coverage | Uncovered | Ops (spec) | Missing in PHP / Rust | Cases | Steps without expect | PHP tests ported | Complete |\n\
         |---|---:|---:|---:|---|---:|---:|---:|---|\n",
    );
    for (lib, cov) in rows {
        match cov {
            None => out.push_str(&format!("| {lib} | — | — | — | — | — | — | — | not started |\n")),
            Some(c) => out.push_str(&format!(
                "| {lib} | {:.1}% | {} | {} | {} / {} | {} | {} | {}/{} | {} |\n",
                c.percent(),
                c.uncovered.len(),
                c.ops,
                c.missing_php.len(),
                c.missing_rust.len(),
                c.cases,
                c.steps_without_expect,
                c.tests - c.tests_unported.len(),
                c.tests,
                if c.complete && c.ok() {
                    "yes"
                } else if c.complete {
                    "**regressed**"
                } else {
                    "in progress"
                }
            )),
        }
    }
    out
}

/// Creates `tests/compat/<lib>/` with a spec, a PHP adapter and a case directory.
pub fn scaffold(root: &Path, lib: &str) -> Result<Vec<String>, String> {
    let dir = spec::lib_dir(root, lib);
    if dir.join("spec.json").exists() {
        return Err(format!("{} already exists", dir.join("spec.json").display()));
    }
    let (src, tests) = if root.join("packages").join(lib).is_dir() {
        (format!("packages/{lib}/src"), format!("packages/{lib}/tests"))
    } else {
        (format!("vendor/utopia-php/{lib}/src"), format!("vendor/utopia-php/{lib}/tests"))
    };
    let class = studly(lib);
    std::fs::create_dir_all(dir.join("cases")).map_err(|e| e.to_string())?;
    let spec = serde_json::json!({
        "lib": lib,
        "description": "",
        "complete": false,
        "php": { "src": [src], "tests": [tests] },
        "rust": { "crate": format!("crates/utopia/{lib}") },
        "services": [],
        "state": [],
        "ops": {},
        "generators": {},
        "waivers": {},
        "tests_waived": {},
        "quirks": []
    });
    let write = |path: &Path, text: String| std::fs::write(path, text).map_err(|e| format!("{}: {e}", path.display()));
    write(&dir.join("spec.json"), serde_json::to_string_pretty(&spec).map_err(|e| e.to_string())? + "\n")?;
    write(
        &dir.join("Adapter.php"),
        format!(
            "<?php\n\nnamespace Tests\\Compat\\{class};\n\nuse Tests\\Compat\\Adapter as Base;\nuse Tests\\Compat\\Session;\n\n\
             /**\n * Maps tests/compat/{lib}/spec.json operations onto the PHP library. Glue only: no logic.\n */\n\
             final class Adapter implements Base\n{{\n    public function operations(): array\n    {{\n        return [\n        ];\n    }}\n}}\n"
        ),
    )?;
    Ok(vec![
        format!("tests/compat/{lib}/spec.json"),
        format!("tests/compat/{lib}/Adapter.php"),
        format!("tests/compat/{lib}/cases/"),
        format!("crates/tools/compat/src/libs/{}.rs (add the operations there)", lib.replace('-', "_")),
    ])
}

/// `user-agent` -> `UserAgent`.
pub fn studly(lib: &str) -> String {
    lib.split(['-', '_'])
        .map(|p| {
            let mut c = p.chars();
            c.next().map(|f| f.to_uppercase().collect::<String>() + c.as_str()).unwrap_or_default()
        })
        .collect()
}
