/**
 * Regenerates src/lib/public-icons/manifest.ts from public/icons/*.svg
 *
 * Run: bun run generate:public-icon-manifest
 */

import { mkdirSync, readdirSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'

const ROOT = join(import.meta.dir, '..')
const ICONS_DIR = join(ROOT, 'public/icons')
const OUTPUT = join(ROOT, 'src/lib/public-icons/manifest.ts')

const filenames = readdirSync(ICONS_DIR)
  .filter((name) => name.endsWith('.svg'))
  .sort((a, b) => a.localeCompare(b))

const contents = `/**
 * Auto-generated by generate:public-icon-manifest
 * Do not edit manually. Run \`bun run generate:public-icon-manifest\`.
 */

/** All SVG filenames in /public/icons (sorted). */
export const PUBLIC_ICON_FILENAMES = [
${filenames.map((name) => `  '${name}',`).join('\n')}
] as const

export type PublicIconFilename = (typeof PUBLIC_ICON_FILENAMES)[number]

/** Icons excluded from user-facing pickers (placeholders, duplicates). */
export const PUBLIC_ICON_PICKER_EXCLUDED: ReadonlySet<string> = new Set([
  'empty.svg',
])

export function getPublicIconPickerFilenames(): string[] {
  return PUBLIC_ICON_FILENAMES.filter(
    (filename) => !PUBLIC_ICON_PICKER_EXCLUDED.has(filename),
  )
}
`

mkdirSync(dirname(OUTPUT), { recursive: true })
writeFileSync(OUTPUT, contents, 'utf8')
console.log(`Wrote ${filenames.length} icons to ${OUTPUT}`)
