/**
 * Discovers numbered API reference versions from @appwrite.io/specs at build time.
 * Run: bun run scripts/generate-reference-versions.ts
 */
import { mkdir, readdir, writeFile } from 'node:fs/promises'
import { createRequire } from 'node:module'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const VIBES_ROOT = join(__dirname, '..')
const OUTPUT_DIR = join(VIBES_ROOT, 'src', 'lib', 'docs', 'references', 'generated')
const OUTPUT_FILE = join(OUTPUT_DIR, 'versions.ts')

function parseVersionParts(version: string): number[] {
  return version.split('.').map((part) => {
    if (part === 'x') return 0
    const parsed = Number.parseInt(part, 10)
    return Number.isFinite(parsed) ? parsed : 0
  })
}

function compareReferenceVersionsDesc(a: string, b: string): number {
  const aParts = parseVersionParts(a)
  const bParts = parseVersionParts(b)
  const length = Math.max(aParts.length, bParts.length)

  for (let index = 0; index < length; index += 1) {
    const diff = (bParts[index] ?? 0) - (aParts[index] ?? 0)
    if (diff !== 0) return diff
  }

  return b.localeCompare(a)
}

async function discoverNumberedReferenceVersions(): Promise<string[]> {
  const require = createRequire(import.meta.url)
  const specsRoot = dirname(require.resolve('@appwrite.io/specs/package.json'))
  const specsDir = join(specsRoot, 'specs')
  const entries = await readdir(specsDir, { withFileTypes: true })

  return entries
    .filter((entry) => entry.isDirectory() && entry.name !== 'latest')
    .map((entry) => entry.name)
    .sort(compareReferenceVersionsDesc)
}

async function run() {
  const versions = await discoverNumberedReferenceVersions()
  const content = `// Auto-generated by scripts/generate-reference-versions.ts — do not edit manually.

export const NUMBERED_REFERENCE_VERSIONS = ${JSON.stringify(versions, null, 2)} as const
`

  await mkdir(OUTPUT_DIR, { recursive: true })
  await writeFile(OUTPUT_FILE, content)
  console.log(`Wrote ${versions.length} reference versions to ${OUTPUT_FILE}`)
}

await run()
