/**
 * Generates API reference artifacts from @appwrite.io/specs.
 *
 * - Default: writes src/lib/docs/references/generated/versions.ts (run before build)
 * - --copy: copies specs/examples into dist/specs/ (run after build)
 *
 * Run: bun run generate:specs [--copy]
 */
import { cp, mkdir, readdir, writeFile } from 'node:fs/promises'
import { createRequire } from 'node:module'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const ROOT = join(__dirname, '..')
const VERSIONS_OUTPUT_DIR = join(ROOT, 'src', 'lib', 'docs', 'references', 'generated')
const VERSIONS_OUTPUT_FILE = join(VERSIONS_OUTPUT_DIR, 'versions.ts')
const DIST_SPECS_ROOT = join(ROOT, 'dist', 'specs')

function parseVersionParts(version: string): number[] {
  return version.split('.').map((part) => {
    if (part === 'x') return 0
    const parsed = Number.parseInt(part, 10)
    return Number.isFinite(parsed) ? parsed : 0
  })
}

function compareReferenceVersionsDesc(a: string, b: string): number {
  const aParts = parseVersionParts(a)
  const bParts = parseVersionParts(b)
  const length = Math.max(aParts.length, bParts.length)

  for (let index = 0; index < length; index += 1) {
    const diff = (bParts[index] ?? 0) - (aParts[index] ?? 0)
    if (diff !== 0) return diff
  }

  return b.localeCompare(a)
}

function getSpecsPackageRoot(): string {
  const require = createRequire(import.meta.url)
  return dirname(require.resolve('@appwrite.io/specs/package.json'))
}

async function discoverNumberedReferenceVersions(specsPackageRoot: string): Promise<string[]> {
  const specsDir = join(specsPackageRoot, 'specs')
  const entries = await readdir(specsDir, { withFileTypes: true })

  return entries
    .filter((entry) => entry.isDirectory() && entry.name !== 'latest')
    .map((entry) => entry.name)
    .sort(compareReferenceVersionsDesc)
}

async function generateReferenceVersions(): Promise<void> {
  const specsPackageRoot = getSpecsPackageRoot()
  const versions = await discoverNumberedReferenceVersions(specsPackageRoot)
  const content = `// Auto-generated by generate:specs — do not edit manually.

export const NUMBERED_REFERENCE_VERSIONS = ${JSON.stringify(versions, null, 2)} as const
`

  await mkdir(VERSIONS_OUTPUT_DIR, { recursive: true })
  await writeFile(VERSIONS_OUTPUT_FILE, content)
  console.log(`Wrote ${versions.length} reference versions to ${VERSIONS_OUTPUT_FILE}`)
}

async function copySpecsToDist(): Promise<void> {
  const specsPackageRoot = getSpecsPackageRoot()

  await mkdir(DIST_SPECS_ROOT, { recursive: true })
  await cp(join(specsPackageRoot, 'specs'), join(DIST_SPECS_ROOT, 'specs'), {
    recursive: true,
  })
  await cp(join(specsPackageRoot, 'examples'), join(DIST_SPECS_ROOT, 'examples'), {
    recursive: true,
  })
  console.log(`Copied @appwrite.io/specs to ${DIST_SPECS_ROOT}`)
}

async function run() {
  const copyOnly = process.argv.includes('--copy')

  if (!copyOnly) {
    await generateReferenceVersions()
  }

  if (copyOnly) {
    await copySpecsToDist()
  }
}

await run()
