/**
 * Project-scope tab entries - sub-tabs inside service sections.
 *
 * These are intentionally search-only: they don't appear in the default
 * landing list, but typing "templates", "domains", "smtp" etc. surfaces
 * the right destination instantly.
 *
 * Label convention: `Section · Subsection` (e.g. "Auth · Templates").
 *
 * To add a new tab, drop another object below - registration is automatic.
 */

import {
  Bell,
  Code,
  Globe,
  KeyRound,
  Layers,
  Mail,
  Megaphone,
  Send,
  Settings,
  Shield,
  ShieldCheck,
  Server,
  Sliders,
  Users,
  Zap,
} from 'lucide-react'
import {
  canShowAuthSecuritySettings,
  canShowProjectOAuth2Server,
  canShowProjectSettings,
} from '@/lib/console-access-checks'
import { registerCommands } from '../registry'
import type { CommandEntry } from '../types'

const PROJECT_TABS: CommandEntry[] = [
  // ── Auth ────────────────────────────────────────────────────────────────
  {
    id: 'project.tab.auth.users',
    scopes: ['project'],
    kind: 'tab',
    group: 'Auth',
    label: 'Auth · Users',
    description: 'Browse and manage your project users',
    icon: Users,
    keywords: ['users', 'accounts', 'people'],
    to: (ctx) => `/projects/${ctx.projectId}/auth`,
  },
  {
    id: 'project.tab.auth.teams',
    scopes: ['project'],
    kind: 'tab',
    group: 'Auth',
    label: 'Auth · Teams',
    description: 'Group users into teams with roles',
    icon: Users,
    keywords: ['teams', 'groups', 'roles'],
    to: (ctx) => `/projects/${ctx.projectId}/auth/teams`,
  },
  {
    id: 'project.tab.auth.policies',
    scopes: ['project'],
    kind: 'tab',
    group: 'Auth',
    label: 'Auth · Policies',
    description: 'User, session, email, membership, and password policies',
    icon: Shield,
    keywords: [
      'policies',
      'users',
      'sessions',
      'emails',
      'memberships',
      'password',
      'privacy',
      'limits',
      'disposable',
      'gmail',
    ],
    available: (ctx) => canShowAuthSecuritySettings(ctx.access, ctx.features),
    to: (ctx) => `/projects/${ctx.projectId}/auth/policies/sessions`,
  },
  {
    id: 'project.tab.auth.policies.sessions',
    scopes: ['project'],
    kind: 'tab',
    group: 'Auth',
    label: 'Auth · Policies · Sessions',
    description: 'Session length, limits, alerts, and invalidation',
    icon: Shield,
    keywords: ['sessions', 'length', 'limit', 'invalidation', 'alerts', 'email'],
    available: (ctx) => canShowAuthSecuritySettings(ctx.access, ctx.features),
    to: (ctx) => `/projects/${ctx.projectId}/auth/policies/sessions`,
  },
  {
    id: 'project.tab.auth.policies.users',
    scopes: ['project'],
    kind: 'tab',
    group: 'Auth',
    label: 'Auth · Policies · Users',
    description: 'Maximum number of users allowed in the project',
    icon: Users,
    keywords: ['users', 'limit', 'maximum', 'count'],
    available: (ctx) => canShowAuthSecuritySettings(ctx.access, ctx.features),
    to: (ctx) => `/projects/${ctx.projectId}/auth/policies/users`,
  },
  {
    id: 'project.tab.auth.policies.emails',
    scopes: ['project'],
    kind: 'tab',
    group: 'Auth',
    label: 'Auth · Policies · Emails',
    description:
      'Block free, aliased, disposable, and corporate emails at signup',
    icon: Mail,
    keywords: [
      'email',
      'free',
      'gmail',
      'disposable',
      'mailinator',
      'alias',
      'corporate',
      'business',
      'signup',
    ],
    available: (ctx) => canShowAuthSecuritySettings(ctx.access, ctx.features),
    to: (ctx) => `/projects/${ctx.projectId}/auth/policies/emails`,
  },
  {
    id: 'project.tab.auth.policies.memberships',
    scopes: ['project'],
    kind: 'tab',
    group: 'Auth',
    label: 'Auth · Policies · Memberships',
    description: 'Hide member name, email, or MFA status from other team members',
    icon: Users,
    keywords: ['membership', 'memberships', 'privacy', 'team'],
    available: (ctx) => canShowAuthSecuritySettings(ctx.access, ctx.features),
    to: (ctx) => `/projects/${ctx.projectId}/auth/policies/memberships`,
  },
  {
    id: 'project.tab.auth.policies.passwords',
    scopes: ['project'],
    kind: 'tab',
    group: 'Auth',
    label: 'Auth · Policies · Passwords',
    description: 'Password history, dictionary, and personal data checks',
    icon: Shield,
    keywords: ['password', 'history', 'dictionary', 'personal data'],
    available: (ctx) => canShowAuthSecuritySettings(ctx.access, ctx.features),
    to: (ctx) => `/projects/${ctx.projectId}/auth/policies/passwords`,
  },
  {
    id: 'project.tab.auth.social-providers',
    scopes: ['project'],
    kind: 'tab',
    group: 'Auth',
    label: 'Auth · Social providers',
    description: 'Configure OAuth2 providers for social login',
    icon: ShieldCheck,
    keywords: ['oauth', 'oauth2', 'social', 'providers', 'google', 'github'],
    available: (ctx) => canShowAuthSecuritySettings(ctx.access, ctx.features),
    to: (ctx) => `/projects/${ctx.projectId}/auth/social-providers`,
  },
  {
    id: 'project.tab.auth.oauth2-server.server',
    scopes: ['project'],
    kind: 'tab',
    group: 'Auth',
    label: 'Auth · OAuth2 server · Server',
    description: 'Configure OAuth2 authorization server for third-party apps',
    icon: Server,
    keywords: [
      'oauth',
      'oauth2',
      'oidc',
      'openid',
      'authorization server',
      'discovery',
      'tokens',
      'settings',
    ],
    available: (ctx) =>
      canShowProjectOAuth2Server(ctx.access, ctx.features),
    to: (ctx) => `/projects/${ctx.projectId}/auth/oauth2-server`,
  },
  {
    id: 'project.tab.auth.oauth2-server.apps',
    scopes: ['project'],
    kind: 'tab',
    group: 'Auth',
    label: 'Auth · OAuth2 server · Apps',
    description: 'Manage OAuth2 client apps for this project',
    icon: KeyRound,
    keywords: ['oauth', 'oauth2', 'clients', 'apps', 'redirect'],
    available: (ctx) =>
      canShowProjectOAuth2Server(ctx.access, ctx.features),
    to: (ctx) => `/projects/${ctx.projectId}/auth/oauth2-server/apps`,
  },
  {
    id: 'project.tab.auth.templates',
    scopes: ['project'],
    kind: 'tab',
    group: 'Auth',
    label: 'Auth · Templates',
    description: 'Customize verification, recovery and magic URL emails',
    icon: Mail,
    keywords: ['templates', 'emails', 'verification', 'recovery', 'magic url'],
    available: (ctx) => canShowAuthSecuritySettings(ctx.access, ctx.features),
    to: (ctx) => `/projects/${ctx.projectId}/auth/templates`,
  },
  {
    id: 'project.tab.auth.settings',
    scopes: ['project'],
    kind: 'tab',
    group: 'Auth',
    label: 'Auth · Settings',
    description: 'Configure auth methods and mock phone numbers',
    icon: Settings,
    keywords: ['methods', 'settings', 'mock', 'phone'],
    available: (ctx) => canShowAuthSecuritySettings(ctx.access, ctx.features),
    to: (ctx) => `/projects/${ctx.projectId}/auth/settings`,
  },

  // ── Messaging ───────────────────────────────────────────────────────────
  {
    id: 'project.tab.messaging.messages',
    scopes: ['project'],
    kind: 'tab',
    group: 'Messaging',
    label: 'Messaging · Messages',
    description: 'Sent and scheduled messages',
    icon: Send,
    keywords: ['messages', 'history', 'push', 'sms', 'email'],
    to: (ctx) => `/projects/${ctx.projectId}/messaging`,
  },
  {
    id: 'project.tab.messaging.topics',
    scopes: ['project'],
    kind: 'tab',
    group: 'Messaging',
    label: 'Messaging · Topics',
    description: 'Subscriber topics for fan-out messaging',
    icon: Megaphone,
    keywords: ['topics', 'subscribers', 'channels', 'pubsub'],
    to: (ctx) => `/projects/${ctx.projectId}/messaging/topics`,
  },
  {
    id: 'project.tab.messaging.providers',
    scopes: ['project'],
    kind: 'tab',
    group: 'Messaging',
    label: 'Messaging · Providers',
    description: 'Email, SMS and push providers',
    icon: Bell,
    keywords: ['providers', 'twilio', 'sendgrid', 'fcm', 'apns', 'mailgun'],
    to: (ctx) => `/projects/${ctx.projectId}/messaging/providers`,
  },

  // ── Settings ────────────────────────────────────────────────────────────
  {
    id: 'project.tab.settings.overview',
    scopes: ['project'],
    kind: 'tab',
    group: 'Settings',
    label: 'Settings · Overview',
    description: 'Project ID, name, region, API endpoint',
    icon: Sliders,
    keywords: ['overview', 'general', 'project id', 'endpoint', 'region'],
    available: (ctx) => canShowProjectSettings(ctx.access, ctx.features),
    to: (ctx) => `/projects/${ctx.projectId}/settings`,
  },
  {
    id: 'project.tab.settings.domains',
    scopes: ['project'],
    kind: 'tab',
    group: 'Settings',
    label: 'Settings · Custom domains',
    description: 'Custom domains for your project endpoint',
    icon: Globe,
    keywords: ['domains', 'custom', 'dns', 'cname', 'hosting'],
    available: (ctx) => canShowProjectSettings(ctx.access, ctx.features),
    to: (ctx) => `/projects/${ctx.projectId}/settings/domains`,
  },
  {
    id: 'project.tab.settings.variables',
    scopes: ['project'],
    kind: 'tab',
    group: 'Settings',
    label: 'Settings · Variables',
    description: 'Project-level environment variables',
    icon: Code,
    keywords: ['variables', 'env', 'environment', 'secrets'],
    available: (ctx) => canShowProjectSettings(ctx.access, ctx.features),
    to: (ctx) => `/projects/${ctx.projectId}/settings/variables`,
  },
  {
    id: 'project.tab.settings.webhooks',
    scopes: ['project'],
    kind: 'tab',
    group: 'Settings',
    label: 'Settings · Webhooks',
    description: 'HTTP callbacks for project events',
    icon: Zap,
    keywords: ['webhooks', 'events', 'http', 'callbacks'],
    available: (ctx) => canShowProjectSettings(ctx.access, ctx.features),
    to: (ctx) => `/projects/${ctx.projectId}/settings/webhooks`,
  },
  {
    id: 'project.tab.settings.migrations',
    scopes: ['project'],
    kind: 'tab',
    group: 'Settings',
    label: 'Settings · Migrations',
    description: 'Import data from other backends',
    icon: Layers,
    keywords: ['migrations', 'import', 'transfer', 'firebase', 'supabase'],
    available: (ctx) => canShowProjectSettings(ctx.access, ctx.features),
    to: (ctx) => `/projects/${ctx.projectId}/settings/migrations`,
  },
  {
    id: 'project.tab.settings.smtp',
    scopes: ['project'],
    kind: 'tab',
    group: 'Settings',
    label: 'Settings · SMTP',
    description: 'Custom SMTP server for outgoing emails',
    icon: Mail,
    keywords: ['smtp', 'email', 'mail', 'server'],
    available: (ctx) => canShowProjectSettings(ctx.access, ctx.features),
    to: (ctx) => `/projects/${ctx.projectId}/settings/smtp`,
  },

  // ── Security ────────────────────────────────────────────────────────────
  {
    id: 'project.tab.firewall',
    scopes: ['project'],
    kind: 'tab',
    group: 'Security',
    label: 'Security · Firewall rules',
    description: 'IP allow/block lists and request rules',
    icon: Shield,
    keywords: ['firewall', 'rules', 'ip', 'allowlist', 'deny', 'rate limit'],
    available: (ctx) => Boolean(ctx.features.firewall),
    to: (ctx) => `/projects/${ctx.projectId}/firewall`,
  },
  {
    id: 'project.create.firewall-rule',
    scopes: ['project'],
    kind: 'create',
    group: 'Security',
    label: 'Create firewall rule',
    description: 'Add a Firewall rule for this project',
    icon: Shield,
    keywords: ['firewall', 'create', 'rule', 'deny', 'rate limit'],
    available: (ctx) => Boolean(ctx.features.firewall),
    to: (ctx) => `/projects/${ctx.projectId}/firewall/create`,
  },
]

registerCommands(PROJECT_TABS)
