/**
 * Project-scope navigation entries (top-level sections in the left sidebar).
 *
 * To add a new top-level project section, drop another object into the array
 * below. RBAC and feature flags are evaluated lazily through `available()`.
 */

import {
  Activity,
  BarChart2,
  BarChart3,
  Database,
  Folder,
  FolderOpen,
  Globe,
  Key,
  LayoutDashboard,
  ListTree,
  MessageSquare,
  Plug,
  Radio,
  Settings,
  Users,
  Zap,
} from 'lucide-react'
import {
  canShowConnectSection,
  canShowProjectSettings,
  canSeeUsageNav,
} from '@/lib/console-access-checks'
import { registerCommands } from '../registry'
import type { CommandEntry } from '../types'

const PROJECT_NAV: CommandEntry[] = [
  {
    id: 'project.nav.projects',
    scopes: ['project'],
    kind: 'navigation',
    label: 'Projects',
    description: 'All projects in this organization',
    icon: FolderOpen,
    shortcut: 'G P',
    keywords: ['home', 'projects', 'list', 'organization'],
    available: (ctx) => Boolean(ctx.orgId),
    to: (ctx) => `/organizations/${ctx.orgId}`,
  },
  {
    id: 'project.nav.overview',
    scopes: ['project'],
    kind: 'navigation',
    label: 'Dashboard',
    description: 'Project dashboard and key metrics',
    icon: LayoutDashboard,
    shortcut: 'G O',
    keywords: ['home', 'dashboard', 'main', 'project'],
    to: (ctx) => `/projects/${ctx.projectId}`,
  },
  {
    id: 'project.nav.apps',
    scopes: ['project'],
    kind: 'navigation',
    label: 'Apps',
    description: 'Connect platforms (web, iOS, Android, Flutter, server)',
    icon: Plug,
    shortcut: 'G I',
    keywords: ['connect', 'platforms', 'sdk', 'integrations', 'clients'],
    available: (ctx) => canShowConnectSection(ctx.access, ctx.features),
    to: (ctx) => `/projects/${ctx.projectId}/apps`,
  },
  {
    id: 'project.nav.api-keys',
    scopes: ['project'],
    kind: 'navigation',
    label: 'API keys',
    description: 'Server API keys and tokens',
    icon: Key,
    shortcut: 'G K',
    keywords: ['keys', 'tokens', 'secrets', 'server', 'auth'],
    available: (ctx) => canShowConnectSection(ctx.access, ctx.features),
    to: (ctx) => `/projects/${ctx.projectId}/api-keys`,
  },
  {
    id: 'project.nav.explorer',
    scopes: ['project'],
    kind: 'navigation',
    label: 'Explorer',
    description: 'Browse and test Appwrite REST API endpoints',
    icon: ListTree,
    shortcut: 'G X',
    keywords: [
      'api',
      'explorer',
      'rest',
      'openapi',
      'reference',
      'endpoints',
      'methods',
    ],
    available: (ctx) => canShowConnectSection(ctx.access, ctx.features),
    to: (ctx) => `/projects/${ctx.projectId}/explorer`,
  },
  {
    id: 'project.nav.auth',
    scopes: ['project'],
    kind: 'navigation',
    label: 'Auth',
    description: 'Users, teams, sessions and authentication providers',
    icon: Users,
    shortcut: 'G A',
    keywords: ['users', 'authentication', 'login', 'signup', 'oauth', 'auth'],
    to: (ctx) => `/projects/${ctx.projectId}/auth`,
  },
  {
    id: 'project.nav.databases',
    scopes: ['project'],
    kind: 'navigation',
    label: 'Databases',
    description: 'Manage databases, tables and collections',
    icon: Database,
    shortcut: 'G D',
    keywords: ['db', 'collections', 'documents', 'tables', 'rows'],
    to: (ctx) => `/projects/${ctx.projectId}/databases`,
  },
  {
    id: 'project.nav.storage',
    scopes: ['project'],
    kind: 'navigation',
    label: 'Storage',
    description: 'Buckets and files',
    icon: Folder,
    shortcut: 'G S',
    keywords: ['files', 'buckets', 'uploads', 'images', 'assets', 'storage'],
    to: (ctx) => `/projects/${ctx.projectId}/storage/-`,
  },
  {
    id: 'project.nav.functions',
    scopes: ['project'],
    kind: 'navigation',
    label: 'Functions',
    description: 'Serverless functions and executions',
    icon: Zap,
    shortcut: 'G F',
    keywords: ['serverless', 'lambda', 'code', 'fn', 'cron'],
    to: (ctx) => `/projects/${ctx.projectId}/functions`,
  },
  {
    id: 'project.nav.messaging',
    scopes: ['project'],
    kind: 'navigation',
    label: 'Messaging',
    description: 'Push notifications, email and SMS messages',
    icon: MessageSquare,
    shortcut: 'G M',
    keywords: ['notifications', 'push', 'sms', 'email', 'topics', 'providers'],
    to: (ctx) => `/projects/${ctx.projectId}/messaging`,
  },
  {
    id: 'project.nav.sites',
    scopes: ['project'],
    kind: 'navigation',
    label: 'Sites',
    description: 'Deployed websites and hosting',
    icon: Globe,
    shortcut: 'G W',
    keywords: ['hosting', 'deploy', 'web', 'website', 'frontend', 'static'],
    to: (ctx) => `/projects/${ctx.projectId}/sites`,
  },
  {
    id: 'project.nav.activity',
    scopes: ['project'],
    kind: 'navigation',
    label: 'Activity',
    description: 'Audit log of project events',
    icon: Activity,
    shortcut: 'G L',
    keywords: ['logs', 'events', 'history', 'audit'],
    available: (ctx) => Boolean(ctx.features.activity),
    to: (ctx) => `/projects/${ctx.projectId}/activity`,
  },
  {
    id: 'project.nav.realtime',
    scopes: ['project'],
    kind: 'navigation',
    label: 'Realtime',
    description: 'Realtime channels and live messages',
    icon: Radio,
    keywords: ['realtime', 'channels', 'websocket', 'pubsub', 'live'],
    to: (ctx) => `/projects/${ctx.projectId}/realtime`,
  },
  {
    id: 'project.nav.usage',
    scopes: ['project'],
    kind: 'navigation',
    label: 'Usage',
    description: 'Usage statistics and quotas',
    icon: BarChart3,
    shortcut: 'G U',
    keywords: ['stats', 'metrics', 'usage', 'quota', 'limits'],
    available: (ctx) =>
      Boolean(ctx.features.usageStats) &&
      canSeeUsageNav(ctx.access, ctx.features),
    to: (ctx) => `/projects/${ctx.projectId}/usage`,
  },
  {
    id: 'project.nav.analytics',
    scopes: ['project'],
    kind: 'navigation',
    label: 'Analytics',
    description: 'Website analytics and traffic insights',
    icon: BarChart2,
    keywords: ['analytics', 'insights', 'tracking', 'website', 'visitors'],
    to: (ctx) => `/projects/${ctx.projectId}/analytics`,
  },
  {
    id: 'project.nav.settings',
    scopes: ['project'],
    kind: 'navigation',
    label: 'Settings',
    description: 'Project settings, custom domains, variables, webhooks',
    icon: Settings,
    shortcut: 'G E',
    keywords: ['config', 'preferences', 'options', 'settings', 'env'],
    available: (ctx) => canShowProjectSettings(ctx.access, ctx.features),
    to: (ctx) => `/projects/${ctx.projectId}/settings`,
  },
  {
    id: 'project.nav.settings-comma',
    scopes: ['project'],
    kind: 'navigation',
    label: 'Settings',
    description: 'Project settings (comma shortcut)',
    icon: Settings,
    shortcut: 'G ,',
    keywords: ['config', 'preferences', 'options', 'settings', 'env', 'comma'],
    available: (ctx) => canShowProjectSettings(ctx.access, ctx.features),
    to: (ctx) => `/projects/${ctx.projectId}/settings`,
  },
]

registerCommands(PROJECT_NAV)
