/**
 * Japanese translations for previously placeholder marketing.ts keys.
 * Keys are the exact English source strings (English is the source of truth).
 */
export const jaMarketingTranslations: Record<string, string> = {
  // Latin per glossary: sub-brand / feature proper nouns, plan names, and technical terms stay in Latin script.
  'AI-native': 'AI-native',
  'Appwrite for Enterprise': 'Appwrite for Enterprise',
  'Cloud GA': 'Cloud GA',
  CTO: 'CTO',
  'Console 2.0': 'Console 2.0',
  'Discord Command Bot': 'Discord Command Bot',
  'Email OTP': 'Email OTP',
  Enterprise: 'Enterprise',
  Free: 'Free',
  Functions: 'Functions',
  'Git push': 'Git push',
  Gold: 'Gold',
  'Golden Kitty Award': 'Golden Kitty Award',
  'Issue #': 'Issue #',
  Issues: 'Issues',
  'Magic URL': 'Magic URL',
  'N/A': 'N/A',
  'Open Issues': 'Open Issues',
  'Phone OTP': 'Phone OTP',
  'Phone SMS': 'Phone SMS',
  Platinum: 'Platinum',
  Realtime: 'Realtime',
  Scale: 'Scale',
  'Series A': 'Series A',
  Serverless: 'Serverless',
  Silver: 'Silver',
  'Single Sign-On (SSO)': 'Single Sign-On (SSO)',
  'Team Appwrite': 'Team Appwrite',
  CPU: 'CPU',
  Skills: 'Skills',
  'Appwrite Pink': 'Appwrite Pink',
  'Business Associate Agreement': 'Business Associate Agreement',
  // Testimonial fragments - genuine translations. Keys use the literal `\\u2019` escape
  // sequence (two backslashes) to match the exact raw text in ja/marketing.ts.
  'It\\u2019s especially nice that Appwrite have to deal with the scaling now and not me.':
    'スケーリングを自分ではなくAppwriteに任せられるのが、特にありがたいです。',
  'The barrier to entry is zero with Appwrite. And I think that\\u2019s really special.':
    'Appwriteなら参入障壁はゼロです。それは本当に特別なことだと思います。',
  'The integrated user authentication and the ease of creating data structures have undoubtedly saved us several weeks\\u2019 worth of time.':
    '統合されたユーザー認証とデータ構造を簡単に作成できる点により、間違いなく数週間分の時間を節約できました。',
  'infinite value that I\\u2019m still discovering today.': '今でも発見し続けている、無限の価値。',
  'A complete development platform, backed by the open source community, built to keep teams efficient by cutting context switching and integration overhead. From auth, databases, storage, and functions to MCP servers, Skills, and agent integrations, everything lives in one place so Appwrite moves with you from ideation to scale.': 'オープンソースコミュニティに支えられた、完全な開発プラットフォーム。コンテキストスイッチと統合のオーバーヘッドを削減し、チームの効率を維持するために構築されています。認証、データベース、ストレージ、FunctionsからMCPサーバー、Skills、エージェント統合まで、すべてが1つの場所にあるので、Appwriteは構想からスケールまであなたと共に歩みます。', // pragma: allowlist secret
  'A major impact that Appwrite made was the amount of time and stress saved.': 'Appwriteがもたらした大きな影響は、節約できた時間とストレスの量でした。', // pragma: allowlist secret
  'A premium, cloud-equal edition with advanced management tools. The same platform and tooling Appwrite uses to run Cloud at 500K projects scale, deployed in your environment.': '高度な管理ツールを備えた、Cloudと同等のプレミアムエディション。Appwriteが50万プロジェクト規模でCloudを運用するために使用しているのと同じプラットフォームとツールを、あなたの環境にデプロイできます。', // pragma: allowlist secret
  'A special thanks to Appwrite for providing robust features and seamless functionality.': '堅牢な機能とシームレスな動作を提供してくれたAppwriteに特別な感謝を。', // pragma: allowlist secret
  "Any student enrolled in the GitHub Student Developer Pack can apply for free and receive Appwrite's Education plan for six months.": 'GitHub Student Developer Packに登録している学生は誰でも無料で申請でき、AppwriteのEducationプランを6か月間利用できます。', // pragma: allowlist secret
  'Appwrite 2.0 introduced a refreshed platform experience and stronger foundations, powered by Hyperloop B, a new engine for the platform, and Console IV, a next-generation console rebuilt with TanStack.': 'Appwrite 2.0では、プラットフォームの新しいエンジンであるHyperloop Bと、TanStackで再構築された次世代コンソールConsole IVにより、刷新されたプラットフォーム体験とより強固な基盤が導入されました。', // pragma: allowlist secret
  'Appwrite Arena launched as an open benchmark for evaluating how effectively AI models understand and work with Appwrite APIs and workflows.': 'Appwrite Arenaは、AIモデルがAppwriteのAPIとワークフローをどれだけ効果的に理解し活用できるかを評価するオープンベンチマークとしてローンチしました。', // pragma: allowlist secret
  'Appwrite Cloud entered public beta, making the platform available without self-hosting and opening the door to managed infrastructure for teams of every size.': 'Appwrite Cloudがパブリックベータに入り、セルフホスティングなしでプラットフォームを利用できるようになり、あらゆる規模のチームにマネージドインフラストラクチャへの道を開きました。', // pragma: allowlist secret
  'Appwrite Cloud reached general availability with production-grade reliability, expanded infrastructure, and the performance teams need to run applications at scale.': 'Appwrite Cloudは、本番環境レベルの信頼性、拡張されたインフラストラクチャ、そしてチームがアプリケーションをスケールで運用するために必要なパフォーマンスを備え、一般提供を開始しました。', // pragma: allowlist secret
  'Appwrite Cloud will automatically verify your GitHub Student Developer Pack membership and apply the Education plan to your account. You can then start using Appwrite right away.': 'Appwrite Cloudが自動的にGitHub Student Developer Packの会員資格を確認し、アカウントにEducationプランを適用します。その後すぐにAppwriteを使い始められます。', // pragma: allowlist secret
  'Appwrite completed a $27M Series A led by Tiger Global, with participation from existing investors, to accelerate product development and global growth.': 'Appwriteは、既存投資家の参加を得てTiger Globalが主導する2,700万ドルのSeries Aを完了し、プロダクト開発とグローバル展開を加速させました。', // pragma: allowlist secret
  'Appwrite Firewall with WAF capabilities to filter malicious traffic and protect applications at the edge.': '悪意のあるトラフィックをフィルタリングし、エッジでアプリケーションを保護するWAF機能を備えたAppwrite Firewall。', // pragma: allowlist secret
  'Appwrite includes a migration tool to help you move from other platforms. Our team can also assist if you need additional help during your transition.': 'Appwriteには、他のプラットフォームからの移行を支援する移行ツールが含まれています。移行中に追加のサポートが必要な場合は、チームがお手伝いします。', // pragma: allowlist secret
  'Appwrite introduced native PostgreSQL and MySQL database solutions to the platform, giving teams dedicated relational engines for SQL workflows, portable schemas, and production workloads alongside Appwrite\'s managed data layer.': 'AppwriteはプラットフォームにネイティブのPostgreSQLとMySQLのデータベースソリューションを導入し、AppwriteのマネージドデータレイヤーとともにSQLワークフロー、ポータブルなスキーマ、本番ワークロード向けの専用リレーショナルエンジンをチームに提供しました。', // pragma: allowlist secret
  'Appwrite is built for and by developers, with a strong focus on your experience. Never worry about scaling or security again.': 'Appwriteは開発者のため、開発者によって構築されており、開発体験を強く重視しています。スケーリングやセキュリティについてもう心配する必要はありません。', // pragma: allowlist secret
  'Appwrite is built for developers, agents, and AI-assisted workflows, and our team works the same way. We integrate AI into how we plan, build, ship, and support, pairing human judgment with tooling that helps us move faster without adding unnecessary overhead.': 'Appwriteは開発者、エージェント、AI支援ワークフローのために構築されており、私たちのチームも同じように働いています。計画、構築、リリース、サポートのあらゆる場面でAIを活用し、人間の判断とツールを組み合わせることで、余計なオーバーヘッドを増やさずスピードを上げています。', // pragma: allowlist secret
  'Appwrite is built to handle large traffic spikes and grow with your application. During a major launch, we can also provide increased support and on-call help.': 'Appwriteは大きなトラフィックの急増に対応し、アプリケーションの成長に合わせて拡張できるように構築されています。大規模なローンチ時には、サポートの強化やオンコール対応も提供できます。', // pragma: allowlist secret
  'Appwrite launched publicly as an open-source backend platform. Designed from the outset to abstract cloud complexity through familiar APIs and protocols, the project gained rapid traction in its first month, including strong visibility across developer communities.': 'Appwriteはオープンソースのバックエンドプラットフォームとして正式に公開されました。当初からおなじみのAPIとプロトコルを通じてクラウドの複雑さを抽象化するよう設計されており、公開から最初の1か月で開発者コミュニティ全体での高い注目を含め、急速に支持を広げました。', // pragma: allowlist secret
  'Appwrite offers an all-in-one hosting platform for you to build and deploy your product from a single place.': 'Appwriteは、1つの場所からプロダクトを構築・デプロイできるオールインワンのホスティングプラットフォームを提供します。', // pragma: allowlist secret
  'Appwrite Presences introduced a Realtime API for short-lived user statuses, with built-in channels, automatic expiry, and permission-aware subscriptions.': 'Appwrite Presencesは、組み込みのチャネル、自動有効期限、権限を考慮したサブスクリプションを備えた、短命なユーザーステータス向けのRealtime APIを導入しました。', // pragma: allowlist secret
  'Appwrite raised $10M in seed funding led by Bessemer Venture Partners and Flybridge, with participation from Ibex Investors, Seedcamp, and the Abraham Fund. The round supported company formation, brought foundational engineering talent from the open-source contributor community, and expanded the investor and board network.': 'Appwriteは、Bessemer Venture PartnersとFlybridgeが主導し、Ibex Investors、Seedcamp、Abraham Fundが参加する1,000万ドルのシード資金調達を完了しました。このラウンドは会社設立を後押しし、オープンソースコントリビューターコミュニティから基盤となるエンジニアリング人材を迎え、投資家と取締役会のネットワークを拡大しました。', // pragma: allowlist secret
  'Appwrite reduces the time and resources spent building a backend infrastructure from scratch.': 'Appwriteは、バックエンドインフラをゼロから構築するのにかかる時間とリソースを削減します。', // pragma: allowlist secret
  'Appwrite shipped a redesigned Console with a new in-house design system and a developer experience built specifically for managing production backends at scale.': 'Appwriteは、新しい社内デザインシステムと、本番バックエンドをスケールで管理するために特化した開発者体験を備えた、再設計されたコンソールをリリースしました。', // pragma: allowlist secret
  'Appwrite Sites launched as an open-source application hosting product, letting teams develop, deploy, and scale web apps from the same platform as their backend services.': 'Appwrite Sitesは、オープンソースのアプリケーションホスティング製品としてローンチし、チームがバックエンドサービスと同じプラットフォームからウェブアプリを開発・デプロイ・スケールできるようにしました。', // pragma: allowlist secret
  'Appwrite surpassed 50,000 GitHub stars, reflecting sustained adoption and the strength of its global open-source community.': 'Appwriteは50,000GitHubスターを突破し、継続的な採用とグローバルなオープンソースコミュニティの強さを示しました。', // pragma: allowlist secret
  'Appwrite unveiled a refreshed brand identity, including a new logo, redesigned website, and improved documentation, reflecting the company\'s evolution from a backend service into an all-in-one open-source development platform.': 'Appwriteは、新しいロゴ、リニューアルされたウェブサイト、改善されたドキュメントを含む刷新されたブランドアイデンティティを発表し、バックエンドサービスからオールインワンのオープンソース開発プラットフォームへの進化を反映しました。', // pragma: allowlist secret
  'Appwrite won Product Hunt\'s Golden Kitty Award for Best Developer Tool, recognizing the platform\'s impact among makers and the broader developer community.': 'AppwriteはProduct HuntのGolden Kitty Awardで最優秀開発者ツールを受賞し、メーカーやより広い開発者コミュニティへのプラットフォームの影響が評価されました。', // pragma: allowlist secret
  'As your business grows, so do the opportunities with Appwrite. Our Partner Program is designed to evolve with you, offering flexible tiers that adapt to your unique needs and goals.': 'ビジネスの成長とともに、Appwriteとの機会も広がります。パートナープログラムはお客様とともに進化するよう設計されており、独自のニーズや目標に合わせた柔軟なティアを提供します。', // pragma: allowlist secret
  'Auth, databases, storage, functions, messaging, hosting, and network security in one stack your teams already know how to operate.': '認証、データベース、ストレージ、Functions、メッセージング、ホスティング、ネットワークセキュリティを、チームがすでに運用方法を知っている1つのスタックに。',
  'Build, deploy, secure, and observe your app from one platform, all under one subscription.': 'アプリの構築、デプロイ、保護、監視を1つのプラットフォームで、1つのサブスクリプションのもとに。',
  'Built into every Appwrite project: backend APIs, serverless functions, and hosted websites, with requests and assets served through our CDN and DDoS protection at the network edge. Choose global regions and edges to optimize latency, compliance, and data residency.': 'すべてのAppwriteプロジェクトに組み込まれている、バックエンドAPI、Serverless Functions、ホスティングされたウェブサイト。リクエストとアセットは、ネットワークエッジでのCDNとDDoS保護を通じて配信されます。レイテンシ、コンプライアンス、データレジデンシーを最適化するために、グローバルなリージョンとエッジを選択できます。', // pragma: allowlist secret
  'Choose serverless or dedicated compute for each database. Pay for usage when traffic is variable, or pick a fixed monthly tier when you need reserved resources and predictable costs.': 'データベースごとにServerlessまたは専用コンピュートを選択できます。トラフィックが変動する場合は使用量に応じて支払い、予約リソースと予測可能なコストが必要な場合は固定月額ティアを選択できます。',
  'Companies older than 5 years, unless bootstrapped with up to $5M in annual recurring revenue.': '設立5年を超える企業(ただし、年間経常収益$500万以下のブートストラップ企業を除く)。',
  'Complete the application form on this page with your full name, email, company name, and website.': 'このページの申請フォームに、氏名、メール、会社名、ウェブサイトを入力してください。',
  'Compliance artifacts, agreements, and enterprise governance built for security reviews and procurement. Enterprise plans include access to SOC 2 reporting, data processing agreements, and advanced identity controls.': 'セキュリティレビューと調達のために構築された、コンプライアンス資料、契約書、エンタープライズガバナンス。Enterpriseプランには、SOC 2レポート、データ処理契約、高度なアイデンティティ管理へのアクセスが含まれます。',
  'Connect a repository for automatic builds on push, branch previews, and production deploys.': 'リポジトリを接続して、push時の自動ビルド、ブランチプレビュー、本番デプロイを実現。',
  'Connect Slack, Discord, WhatsApp, and other chat surfaces for team and user notifications.': 'Slack、Discord、WhatsAppなどのチャットツールを接続して、チームやユーザーへの通知を送信。',
  'Create your Appwrite account through the Education program sign up page. Once verified, the Education plan will be applied to your account.': 'EducationプログラムのサインアップページからAppwriteアカウントを作成してください。確認が完了すると、アカウントにEducationプランが適用されます。', // pragma: allowlist secret
  'Custom bandwidth, storage, compute, and project limits tailored to your traffic, workloads, and organizational structure.': 'トラフィック、ワークロード、組織構造に合わせてカスタマイズされた、帯域幅、ストレージ、コンピュート、プロジェクトの制限。',
  'Dedicated success management, priority response times, and direct access to Appwrite engineers when you need them.': '専任のカスタマーサクセス管理、優先対応、必要なときにAppwriteエンジニアへの直接アクセス。', // pragma: allowlist secret
  'Grow your skills with Pro resources on Appwrite Cloud, join a community of open-source contributors, and build with the framework of your choice.': 'Appwrite CloudのProプラン同等のリソースでスキルを伸ばし、オープンソースコントリビューターのコミュニティに参加して、好きなフレームワークで構築しましょう。', // pragma: allowlist secret
  'DevKind reduced development time by 60% and lowered server costs by 40%': 'DevKindは開発時間を60%削減し、サーバーコストを40%削減',
  'Earn free access through GitHub Education to build your next project on Appwrite Cloud. Sign up for the GitHub Student Developer Pack to get six months of Appwrite Cloud with Pro resources.': 'GitHub Educationを通じて無料アクセスを取得し、Appwrite Cloudで次のプロジェクトを構築しましょう。GitHub Student Developer Packにサインアップすると、Proプランと同等のリソースでAppwrite Cloudを6か月間利用できます。', // pragma: allowlist secret
  'Eliminate friction and abstract complexity for every creator. We build Appwrite for agents and developers, giving them the tools and experience they need to create and innovate without limits and with minimum concerns.': 'あらゆるクリエイターのために、摩擦をなくし複雑さを抽象化する。私たちは、エージェントと開発者が限界なく、最小限の懸念で創造とイノベーションを行うために必要なツールと体験を提供するために、Appwriteを構築しています。', // pragma: allowlist secret
  'Enhanced network-level DDoS mitigation for high-traffic production workloads and mission-critical availability.': '高トラフィックの本番ワークロードとミッションクリティカルな可用性のための、強化されたネットワークレベルのDDoS対策。',
  'Enterprise customers receive a dedicated success manager, 24/7 support on Slack, and priority response times. We also help with onboarding, architecture reviews, and ongoing optimization.': 'Enterpriseのお客様には、専任のカスタマーサクセスマネージャー、Slackでの24時間365日サポート、優先対応が提供されます。オンボーディング、アーキテクチャレビュー、継続的な最適化もサポートします。',
  'Enterprise is designed for organizations with production workloads that need custom resource limits, premium support, compliance options, or deployment flexibility beyond the Pro plan.': 'Enterpriseは、カスタムリソース制限、プレミアムサポート、コンプライアンスオプション、またはProプランを超えるデプロイの柔軟性を必要とする、本番ワークロードを持つ組織向けに設計されています。',
  'Enterprise plans can include SOC-2 and HIPAA support, along with SSO, activity logs, and custom backup policies for security and governance workflows.': 'Enterpriseプランには、セキュリティとガバナンスのワークフロー向けに、SOC-2とHIPAA対応、SSO、アクティビティログ、カスタムバックアップポリシーを含めることができます。',
  'Everyday thousands of companies are built on top of Appwrite. Benefit from our network as an Appwrite Partner.': '毎日何千もの企業がAppwriteの上に構築されています。Appwriteパートナーとして、私たちのネットワークを活用しましょう。', // pragma: allowlist secret
  'Fill out the contact form on this page. Our sales team will review your use case and schedule a conversation to scope resources, support, and deployment options.': 'このページのお問い合わせフォームにご記入ください。営業チームがユースケースを確認し、リソース、サポート、デプロイオプションを検討するための打ち合わせを設定します。',
  'Find your next career at Appwrite and join a remote team building the platform developers and agents rely on.': 'Appwriteで次のキャリアを見つけ、開発者やエージェントが信頼するプラットフォームを構築するリモートチームに参加しましょう。', // pragma: allowlist secret
  'Following the Series A, Appwrite established a $50,000 fund to support independent open-source projects, reinforcing the company\'s commitment to the broader ecosystem.': 'Series Aに続き、Appwriteは独立したオープンソースプロジェクトを支援するために5万ドルの基金を設立し、より広いエコシステムへのコミットメントを強化しました。', // pragma: allowlist secret
  'For agencies, consultancies, freelancers, and integrators who want to provide a scalable backend solution for their clients. Partner with Appwrite to provide a highly custom solution with the newest technology.': 'クライアントにスケーラブルなバックエンドソリューションを提供したい代理店、コンサルティング会社、フリーランサー、インテグレーター向け。Appwriteと提携して、最新技術を用いた高度にカスタムなソリューションを提供しましょう。', // pragma: allowlist secret
  'For innovative software companies striving to create solutions that integrate seamlessly with our platform. Partner with Appwrite to create a better developer experience.': '私たちのプラットフォームとシームレスに統合するソリューションの構築を目指す、革新的なソフトウェア企業向け。Appwriteと提携して、より優れた開発者体験を作りましょう。', // pragma: allowlist secret
  'From MVP to enterprise, our app scales automatically, letting you focus on your business goals.': 'MVPからエンタープライズまで、アプリは自動的にスケールするので、ビジネス目標に集中できます。',
  'Fully managed infrastructure with a plan customized to your needs: increased limits, predictable fixed pricing, uptime SLAs, and global CDN.': 'ニーズに合わせてカスタマイズされたプランによる、フルマネージドインフラストラクチャ。制限の引き上げ、予測可能な固定料金、稼働時間SLA、グローバルCDN。',
  'Get six months of free access to build with Appwrite’s Education plan.': 'AppwriteのEducationプランで、6か月間無料で構築できます。', // pragma: allowlist secret
  'Global CDN included. Transformed images cached in your project region before they reach the edge.': 'グローバルCDNを標準搭載。変換された画像は、エッジに届く前にプロジェクトのリージョンでキャッシュされます。',
  'Go to the Appwrite Console and select the organization you wish to add credits to. In your organization overview, you can switch to the billing tab. Here, you need to go to the bottom of the page, where you will find the ability to add credits, as well as see the status of your credits. Credits are only relevant to Pro organizations since Free organizations are 100% free.': 'Appwriteコンソールにアクセスし、クレジットを追加したい組織を選択します。組織の概要画面で請求タブに切り替えられます。ページの下部に進むと、クレジットを追加する機能とクレジットの状況を確認できます。Freeの組織は完全に無料のため、クレジットはProの組織にのみ関係します。', // pragma: allowlist secret
  'Go to the Appwrite Console and select the organization you wish to view. Here, you will find a usage tab with an overview of all your project\'s usage stats.': 'Appwriteコンソールにアクセスし、確認したい組織を選択します。ここには、すべてのプロジェクトの利用統計の概要を確認できる利用状況タブがあります。', // pragma: allowlist secret
  'Go to the Appwrite Console and use the drop-down menu in the top right corner to navigate to your organization overview by clicking on your organization. This will bring you to your overview, where you can select the billing tab. Here you will find your overview, payment history and methods, billing address, set a budget cap, and add your credits.': 'Appwriteコンソールにアクセスし、右上のドロップダウンメニューから組織をクリックして、組織の概要画面に移動します。概要画面から請求タブを選択できます。ここでは、概要、支払い履歴と方法、請求先住所の確認、予算上限の設定、クレジットの追加ができます。', // pragma: allowlist secret
  'Hybrid apps are supported too. Frameworks like Next.js, Nuxt, and SvelteKit can mix static pages with server-rendered routes in the same site.': 'ハイブリッドアプリにも対応しています。Next.js、Nuxt、SvelteKitなどのフレームワークでは、同じサイト内で静的ページとサーバーレンダリングされたルートを混在させることができます。',
  'If accepted, we activate your program benefits and share next steps to build on Appwrite Cloud.': '採用された場合、プログラム特典を有効化し、Appwrite Cloudでの構築に向けた次のステップをお知らせします。', // pragma: allowlist secret
  'If you want to upgrade to a paid plan, you can do so in your Appwrite dashboard, select your organization, and change your plan in the Billing section.': '有料プランにアップグレードしたい場合は、Appwriteダッシュボードで組織を選択し、請求セクションでプランを変更できます。', // pragma: allowlist secret
  "If you're a student with the GitHub Student Developer Pack, you can use the Appwrite Education plan free for six months to build your next project.": 'GitHub Student Developer Packをお持ちの学生であれば、Appwrite Educationプランを6か月間無料で利用して、次のプロジェクトを構築できます。', // pragma: allowlist secret
  'If you\'re already enrolled in the GitHub Student Developer Pack, click the \'Sign up\' button on this page and fill in your details. If you\'re not enrolled with GitHub Education yet, first apply for the GitHub Student Developer Pack, then come back and sign up to Appwrite Cloud here.': 'すでにGitHub Student Developer Packに登録済みの場合は、このページの「サインアップ」ボタンをクリックして詳細を入力してください。まだGitHub Educationに登録していない場合は、先にGitHub Student Developer Packに申請し、その後このページに戻ってAppwrite Cloudにサインアップしてください。', // pragma: allowlist secret
  'If your needs grow beyond the program, contact us to discuss Enterprise options and a tailored plan for your organization.': 'ニーズがプログラムの範囲を超えて拡大した場合は、お問い合わせいただき、組織に合わせたEnterpriseオプションとプランについてご相談ください。',
  'Inspire and get inspired. Join Appwrite\'s community of maintainers and contributors and help us make Appwrite better for developers worldwide.': 'インスピレーションを与え、受け取る。Appwriteのメンテナーとコントリビューターのコミュニティに参加し、世界中の開発者にとってより良いAppwriteを作る手助けをしてください。', // pragma: allowlist secret
  'Join a growing community of developers and students who use Appwrite to build their products. Gain access to a wealth of knowledge, support, and shared experiences needed to grow and advance your tech career.': 'Appwriteでプロダクトを構築する、成長を続ける開発者と学生のコミュニティに参加しましょう。テックキャリアを成長させ前進させるために必要な、豊富な知識、サポート、共有された経験にアクセスできます。', // pragma: allowlist secret
  'Join the Appwrite Education program in collaboration with the GitHub Student Developer Pack. Verified students get six months of Appwrite Cloud with Pro resources for free.': 'GitHub Student Developer Packと連携したAppwrite Educationプログラムに参加しましょう。認証された学生は、Proプランと同等のリソースでAppwrite Cloudを6か月間無料で利用できます。', // pragma: allowlist secret
  'Join the Appwrite Partners program and grow your business. Deliver powerful solutions to clients, increase revenue, and expand your reach.': 'Appwrite Partnersプログラムに参加してビジネスを成長させましょう。クライアントに強力なソリューションを提供し、収益を増やし、リーチを拡大します。', // pragma: allowlist secret
  'Just like a Swiss Army Knife, you can choose and use the tools that you need with Appwrite.': 'スイスアーミーナイフのように、Appwriteでは必要なツールを選んで使うことができます。', // pragma: allowlist secret
  'K-Collect reduced infrastructure costs by 700%': 'K-Collectはインフラコストを700%削減',
  'LangX handled millions of requests using Appwrite': 'LangXはAppwriteを使って数百万件のリクエストを処理', // pragma: allowlist secret
  'Majik Kids built a Fair Pay audio platform for children on Appwrite Cloud': 'Majik KidsはAppwrite Cloudで子供向けのFair Payオーディオプラットフォームを構築', // pragma: allowlist secret
  'Messaging expanded the platform with email, push, and SMS capabilities, giving teams native tools for user communication and notifications.': 'Messagingは、メール、プッシュ通知、SMSの機能でプラットフォームを拡張し、チームにユーザーとのコミュニケーションと通知のためのネイティブツールを提供しました。',
  'mySHOEFITTER sized 12,000+ feet accurately for major EU retailers': 'mySHOEFITTERは大手EU小売業者向けに12,000以上の足のサイズを正確に測定',
  'Our team reviews your application against the program criteria and follows up by email with onboarding steps if you are accepted.': 'チームがプログラムの基準に照らして申請を審査し、採用された場合はオンボーディングの手順をメールでお知らせします。',
  'Package manager stores are cached between builds. Deployment retention removes old inactive deployments to save storage. Path filters help Turborepo monorepos skip unnecessary deploys.': 'パッケージマネージャーのストアはビルド間でキャッシュされます。デプロイ保持機能は、古い非アクティブなデプロイを削除してストレージを節約します。パスフィルターは、Turborepoモノレポで不要なデプロイをスキップするのに役立ちます。',
  'Pricing is based on your usage profile, support requirements, and deployment model. Cloud Enterprise plans offer customized limits with predictable fixed pricing. Our team works with you to build a plan that matches your scale and procurement process.': '料金は、利用プロファイル、サポート要件、デプロイモデルに基づいて決まります。Cloud Enterpriseプランでは、予測可能な固定料金でカスタマイズされた制限を提供します。チームがお客様のスケールと調達プロセスに合ったプランを一緒に構築します。',
  'Program members receive Appwrite Cloud Pro for 12 months, cloud credits, unlimited team members, premium email support, training workshops, a private Slack channel with our team, a dedicated program manager, and founder swag.': 'プログラムメンバーには、12か月間のAppwrite Cloud Pro、クラウドクレジット、無制限のチームメンバー、プレミアムメールサポート、トレーニングワークショップ、チームとのプライベートSlackチャネル、専任のプログラムマネージャー、創業者向けグッズが提供されます。', // pragma: allowlist secret
  'Radar shipped a polished iOS hub for every kind of media recommendation': 'Radarは、あらゆる種類のメディアレコメンデーションのための洗練されたiOSハブをリリース',
  'Reduce vendor sprawl and integration overhead. Appwrite unifies the backend services enterprise teams need to build, deploy, and protect modern applications without juggling multiple contracts or stitching vendors together.': 'ベンダーの乱立と統合のオーバーヘッドを削減。Appwriteは、複数の契約を管理したりベンダーをつなぎ合わせたりすることなく、エンタープライズチームがモダンなアプリケーションを構築、デプロイ、保護するために必要なバックエンドサービスを統合します。', // pragma: allowlist secret
  'Replace a patchwork of backend vendors with one platform. Enterprise teams reduce integration overhead, accelerate delivery, and scale with custom resources, dedicated support, and flexible deployment.': '寄せ集めのバックエンドベンダーを1つのプラットフォームに置き換える。エンタープライズチームは、カスタムリソース、専任サポート、柔軟なデプロイにより、統合のオーバーヘッドを削減し、リリースを加速し、スケールできます。',
  'Replace fragmented backend, hosting, storage, and delivery tooling with a single platform built for the full application lifecycle. Reduce integration surface area, simplify procurement, and give your team one system to operate and scale.': '断片化したバックエンド、ホスティング、ストレージ、配信ツールを、アプリケーションのライフサイクル全体のために構築された1つのプラットフォームに置き換える。統合範囲を縮小し、調達を簡素化し、チームに運用とスケールのための1つのシステムを提供します。',
  'Resources for presenting the Appwrite brand to maintain consistency while using our logos, colors, and other brand elements across various platforms and materials.': 'ロゴ、カラー、その他のブランド要素をさまざまなプラットフォームや資料で使用する際に一貫性を保つための、Appwriteブランドの提示に関するリソース。', // pragma: allowlist secret
  'Rollbacks switch which deployment is served. No code is deleted, modified, or rebuilt, so recovery is near-instant with zero downtime.': 'ロールバックは、どのデプロイを配信するかを切り替えます。コードの削除、変更、再ビルドは発生しないため、ダウンタイムなくほぼ瞬時に復旧できます。',
  'Run Enterprise on fully managed Appwrite Cloud or as a premium self-hosted edition in your environment.': 'Enterpriseは、フルマネージドのAppwrite Cloud上で実行するか、環境内のプレミアムセルフホスト版として実行できます。', // pragma: allowlist secret
  'Search 160+ TLDs with live pricing and private WHOIS. Manage DNS, connect Sites, Functions, or custom API domains, and provision TLS without leaving Appwrite.': 'リアルタイム料金とプライベートWHOISで160以上のTLDを検索。Appwriteを離れることなく、DNSの管理、Sites、Functions、カスタムAPIドメインの接続、TLSのプロビジョニングができます。', // pragma: allowlist secret
  'Send OTP codes, delivery updates, and alerts outside your app through Twilio, Vonage, MSG91, Telesign, Textmagic, and other SMS vendors.': 'Twilio、Vonage、MSG91、Telesign、Textmagicなどの各種SMSベンダーを通じて、OTPコード、配送状況の更新、アラートをアプリの外に送信。',
  'Send receipts, digests, and transactional mail through SendGrid, Mailgun, SMTP, and other email providers.': 'SendGrid、Mailgun、SMTPなどの各種メールプロバイダーを通じて、領収書、ダイジェスト、トランザクションメールを送信。',
  'Ship production features without stitching together multiple vendors or maintaining custom backend infrastructure.': '複数のベンダーをつなぎ合わせたり、カスタムのバックエンドインフラを維持したりすることなく、本番機能をリリース。',
  'Should you require further assistance or have specific needs beyond what\'s presented on this page, please don\'t hesitate to': 'このページに記載されている内容を超えて追加のサポートや特別なニーズがある場合は、お気軽に',
  'Socialaize runs hundreds of thousands of function executions per day on Cloud': 'SocialaizeはCloudで1日に数十万件のFunction実行を処理',
  'Software development transforms our everyday lives, shaped by the creativity and innovation of developers and the AI agents they work with. At Appwrite, we enable them to build products the world loves by removing technical barriers with our backend platform.': 'ソフトウェア開発は、開発者と彼らが共に働くAIエージェントの創造性とイノベーションによって形作られ、私たちの日常生活を変えています。Appwriteでは、バックエンドプラットフォームによって技術的な障壁を取り除くことで、彼らが世界に愛されるプロダクトを構築できるようにしています。', // pragma: allowlist secret
  'Spacing is determined by the Appwrite mark. Unless otherwise noted by partner brands, each logo is optically equal as a collection of shapes.': '余白はAppwriteのマークによって決まります。パートナーブランドから特に指定がない限り、各ロゴは図形の集合として視覚的に等しくなるようにします。', // pragma: allowlist secret
  'Create a project and add authentication in minutes with our quick start guides.': 'クイックスタートガイドで、数分でプロジェクトを作成し認証を追加できます。',
  'Create a database, define your schema, and query your first rows in minutes.': '数分でデータベースを作成し、スキーマを定義して、最初の行をクエリできます。',
  'Create a bucket, upload your first file, and generate a preview URL in minutes.': '数分でバケットを作成し、最初のファイルをアップロードして、プレビューURLを生成できます。',
  'Deploy your first function from a template or your own codebase in minutes.': '数分で、テンプレートまたは自分のコードベースから最初のFunctionをデプロイできます。',
  'Configure a provider, create a topic, and send your first message from the console or SDK.': 'プロバイダーを設定し、トピックを作成して、コンソールまたはSDKから最初のメッセージを送信できます。',
  'Connect a repository and deploy your first frontend alongside your Appwrite backend.': 'リポジトリを接続して、Appwriteバックエンドと並行して最初のフロントエンドをデプロイできます。', // pragma: allowlist secret
  'Give users a secure sign-in experience without building auth infrastructure. Appwrite Auth supports the methods your users expect, team collaboration signals, and the controls your team needs.': '認証インフラを構築せずに、ユーザーに安全なサインイン体験を提供。Appwrite Authは、ユーザーが期待する認証方法、チームコラボレーションのシグナル、チームに必要な管理機能をサポートします。', // pragma: allowlist secret
  'Model, query, and scale structured data with Appwrite TablesDB or connect native PostgreSQL and MySQL when you need full SQL control.': 'Appwrite TablesDBで構造化データをモデル化、クエリ、スケールするか、完全なSQL制御が必要な場合はネイティブのPostgreSQLとMySQLを接続できます。', // pragma: allowlist secret
  'Upload, organize, and serve images, videos, documents, and other assets through Appwrite CDN. Resize, crop, and convert formats on the fly, compress and encrypt at the bucket level, and share with granular permissions.': 'Appwrite CDNを通じて、画像、動画、ドキュメント、その他のアセットをアップロード、整理、配信。リサイズ、クロップ、フォーマット変換をその場で行い、バケットレベルで圧縮・暗号化し、きめ細かい権限で共有できます。', // pragma: allowlist secret
  'Run API endpoints, webhooks, cron jobs, and event handlers in secure isolated runtimes that scale with demand.': 'APIエンドポイント、webhook、Cronジョブ、イベントハンドラーを、需要に応じてスケールする安全な分離ランタイムで実行。',
  'Reach users on email, SMS, and push from a unified API. Manage providers, audiences, and delivery without stitching vendors together.': '統一されたAPIから、メール、SMS、プッシュ通知でユーザーにリーチ。ベンダーをつなぎ合わせることなく、プロバイダー、オーディエンス、配信を管理できます。',
  'Ship static, SSR, and client-rendered frontends with automatic builds, branch previews, and Appwrite services connected behind the scenes.': '自動ビルド、ブランチプレビュー、裏側で接続されたAppwriteサービスにより、静的、SSR、クライアントレンダリングのフロントエンドをリリース。', // pragma: allowlist secret
  'Storage files and transformed previews inherit Appwrite CDN delivery and regional caching automatically. No separate CDN setup required.': 'ストレージファイルと変換されたプレビューは、Appwrite CDNの配信とリージョンキャッシュを自動的に継承します。個別のCDN設定は不要です。', // pragma: allowlist secret
  'Students with access to the Education plan can create 2 projects with equal usage limits as the Appwrite Pro plan (minus email support) at no cost. We also have a special channel for Education program members in the Appwrite Discord server for support, which will feature exclusive events, hackathons, etc.': 'Educationプランにアクセスできる学生は、Appwrite Proプランと同等の利用制限(メールサポートを除く)で、無料で2つのプロジェクトを作成できます。また、Appwrite Discordサーバーには、Educationプログラムメンバー向けの専用チャネルがあり、サポートに加え、限定イベントやハッカソンなどが開催されます。', // pragma: allowlist secret
  'Targets are created when users verify email or phone in Auth, or when your app registers push device tokens.': 'ターゲットは、ユーザーが認証でメールまたは電話番号を検証したとき、あるいはアプリがプッシュデバイストークンを登録したときに作成されます。',
  'Teams and developers who ship integrations, tools, or services on Appwrite can join our partner program for verified catalog placement, co-marketing, training, and engineering support.': 'Appwrite上で連携、ツール、サービスをリリースするチームや開発者は、パートナープログラムに参加することで、認証済みカタログへの掲載、共同マーケティング、トレーニング、エンジニアリングサポートを受けられます。', // pragma: allowlist secret
  'Thanks to Appwrite and advances in technology, we were able to get an MVP out in 2/3 months with 1 developer.': 'Appwriteと技術の進歩のおかげで、1人の開発者で2〜3か月でMVPをリリースすることができました。', // pragma: allowlist secret
  'The Appwrite logo stands as a prominent symbol of our brand\'s identity. Refrain from altering our logo and preferably use our logo on a neutral background.': 'Appwriteのロゴは、私たちのブランドアイデンティティを象徴する重要なシンボルです。ロゴの変更は控え、できるだけニュートラルな背景の上で使用してください。', // pragma: allowlist secret
  'The Appwrite Pro plan includes generous limits designed for production applications. Review our pricing page for a full overview of included resources and add-ons.': 'Appwrite Proプランには、本番アプリケーション向けに設計された寛大な制限が含まれています。含まれるリソースとアドオンの詳細については、料金ページをご覧ください。', // pragma: allowlist secret
  'The Appwrite Startups Program gives you an all-in-one platform to build and host your product, plus cloud credits, training, priority support, and founder swag.': 'Appwrite Startupsプログラムでは、プロダクトの構築とホスティングのためのオールインワンプラットフォームに加え、クラウドクレジット、トレーニング、優先サポート、創業者向けグッズを提供します。', // pragma: allowlist secret
  'The Appwrite Startups Program launched to support early-stage teams with credits, guidance, and infrastructure as they build on the platform.': 'Appwrite Startupsプログラムは、プラットフォーム上で構築するアーリーステージのチームを、クレジット、ガイダンス、インフラで支援するためにローンチしました。', // pragma: allowlist secret
  'The first stable release marked a major milestone after years of community-driven development, spanning thousands of commits and contributions from developers worldwide.': '最初の安定版リリースは、何年にもわたるコミュニティ主導の開発を経た大きなマイルストーンとなり、世界中の開発者による数千ものコミットと貢献にわたるものでした。',
  'The Startups program is for companies with traction through funding or revenue. If you have neither, Appwrite Cloud Pro is the right place to start building.': 'Startupsプログラムは、資金調達または収益による実績のある企業向けです。どちらもない場合は、Appwrite Cloud Proが構築を始めるのに適した場所です。', // pragma: allowlist secret
  'The Startups program is for product teams at an early stage of growth. Apply if your company meets the criteria below.': 'Startupsプログラムは、成長の初期段階にあるプロダクトチーム向けです。会社が以下の基準を満たしている場合は申請してください。',
  'The Startups program is reserved for early-stage product companies with funding or revenue. These profiles are usually not accepted.': 'Startupsプログラムは、資金調達または収益のあるアーリーステージのプロダクト企業向けに限定されています。以下のプロフィールは通常受け付けられません。',
  'The Startups program requires evidence of traction through funding or revenue. If your company has neither, start with Appwrite Cloud Pro instead of applying here.': 'Startupsプログラムには、資金調達または収益による実績の証明が必要です。会社にどちらもない場合は、こちらに申請する代わりにAppwrite Cloud Proから始めてください。', // pragma: allowlist secret
  'The switch to using Appwrite brought': 'Appwriteへの切り替えがもたらしたのは', // pragma: allowlist secret
  "The Education plan is available only to students verified through the GitHub Student Developer Pack. It lasts six months, then you can choose the plan that fits what you're building next.": 'Educationプランは、GitHub Student Developer Packで学生として認証された方のみ利用できます。期間は6か月で、その後は次に作るものに合ったプランを選べます。',
  'This program is open to all Appwrite users who are verified members of the GitHub Student Developer Pack.': 'このプログラムは、GitHub Student Developer Packの認証済みメンバーであるすべてのAppwriteユーザーに開かれています。', // pragma: allowlist secret
  'UNDO went from idea to paying customers tracking 9,000+ circular assets': 'UNDOはアイデアから、9,000以上の循環資産を追跡する有料顧客獲得まで成長',
  'Use these product visuals to enhance your articles, presentations, and content related to Appwrite.': 'これらのプロダクトビジュアルを使って、Appwriteに関する記事、プレゼンテーション、コンテンツを充実させましょう。', // pragma: allowlist secret
  'Visit our showcase website built with Appwrite to find inspiration for your projects or to showcase what you have built.': 'Appwriteで構築されたショーケースサイトを訪れて、プロジェクトのインスピレーションを見つけたり、作ったものを紹介したりしましょう。', // pragma: allowlist secret
  'We are a remote-first, AI-native team built to stay lean. We recruit exceptional talent worldwide, communicate with clarity, and combine human judgment with AI to ship ambitious work at speed.': '私たちはリーンであり続けるために構築された、リモートファーストでAI-nativeなチームです。世界中から優れた人材を採用し、明確なコミュニケーションを行い、人間の判断とAIを組み合わせることで、野心的な仕事をスピーディーにリリースしています。',
  'We hire the best people wherever they are. Being remote-first keeps us thoughtful about communication across time zones and cultures. We stay humble, treat each other with respect, and work to help everyone on the team do their best work.': '私たちは、どこにいても最高の人材を採用します。リモートファーストであることは、タイムゾーンや文化を超えたコミュニケーションについて配慮を持ち続けることにつながります。謙虚さを保ち、互いを尊重し合い、チームの全員が最高の仕事ができるよう努めています。',
  'We keep overhead lean and our investments close to the product. Most of our team is dedicated to creating products developers genuinely enjoy using.': 'オーバーヘッドを抑え、投資をプロダクトに集中させています。チームの大部分は、開発者が本当に使いたいと思うプロダクトを作ることに専念しています。',
  'We strive to stay a smaller team that punches above its weight. That means clear priorities, async-first communication, and workflows designed for effectiveness. We minimize bureaucracy, keep decision-making close to the work, and use AI where it saves time so people can focus on high-impact work.': '私たちは、規模以上の力を発揮する小さなチームであり続けることを目指しています。それは、明確な優先順位、非同期を第一とするコミュニケーション、効果を重視して設計されたワークフローを意味します。官僚的な手続きを最小限に抑え、意思決定を現場の近くで行い、時間を節約できる場面ではAIを活用することで、インパクトの大きい仕事に集中できるようにしています。',
  'We welcome product-focused startups that are 5 years old or younger and have raised funding (pre-seed through Series A) or bootstrapped revenue up to $5M in annual recurring revenue. Companies with no funding and no revenue are not eligible. The program is not open to agencies, consultancies, or resellers.': '設立5年以内で、資金調達(プレシードからSeries Aまで)を行っているか、年間経常収益$500万までのブートストラップ収益があるプロダクト重視のスタートアップを歓迎します。資金調達も収益もない企業は対象外です。このプログラムは代理店、コンサルティング会社、リセラーには開かれていません。',
  'We will have a dedicated partner catalog, an official partner badge, and other visibility opportunities.': '専用のパートナーカタログ、公式パートナーバッジ、その他の露出機会をご用意します。',
  'While prioritizing recognizability, the logotype is the recommended choice. Using the Appwrite logomark is suitable for situations where space constraints make it challenging to showcase the complete logotype.': '認識しやすさを優先する場合、ロゴタイプの使用が推奨されます。Appwriteロゴマークの使用は、スペースの制約により完全なロゴタイプを表示することが難しい状況に適しています。', // pragma: allowlist secret
  'With its comprehensive suite of services, Appwrite emerged as an ideal choice for my needs.': '包括的なサービス群により、Appwriteは私のニーズに理想的な選択肢となりました。', // pragma: allowlist secret
  'Write \'Appwrite,\' with a lowercase \'w\' and no space between the two words. Please refrain from using variations like \'AppWrite\' or \'App Write\'.': '「Appwrite」は小文字の「w」で、2つの単語の間にスペースを入れずに表記してください。「AppWrite」や「App Write」のような表記は避けてください。', // pragma: allowlist secret
  'Yes. Accepted startups can host websites and web apps with Appwrite Sites as part of the program.': 'はい。採用されたスタートアップは、プログラムの一環としてAppwrite Sitesでウェブサイトやウェブアプリをホスティングできます。', // pragma: allowlist secret
  'Yes. The Enterprise self-hosted edition is a premium, cloud-equal release with advanced management tools. It is the same platform Appwrite uses to run Cloud at 500K projects scale, deployed in your environment with dedicated support, SLAs, and compliance features.': 'はい。Enterpriseセルフホスト版は、高度な管理ツールを備えた、Cloudと同等のプレミアムリリースです。Appwriteが50万プロジェクト規模でCloudを運用しているのと同じプラットフォームを、専任サポート、SLA、コンプライアンス機能とともにあなたの環境にデプロイできます。', // pragma: allowlist secret
  'You are building a software product or platform. The program is not open to agencies, consultancies, or resellers.': 'ソフトウェアプロダクトまたはプラットフォームを構築していること。このプログラムは代理店、コンサルティング会社、リセラーには開かれていません。',
  'You don\'t need to have a team of engineers to develop, host, and scale applications. Appwrite gives you everything you need, including built-in security, AI, and open source.': 'アプリケーションの開発、ホスティング、スケールにエンジニアチームは必要ありません。Appwriteは、組み込みのセキュリティ、AI、オープンソースを含め、必要なものすべてを提供します。', // pragma: allowlist secret
  'You have access to the Appwrite community for technical questions. Program members also receive a private Slack channel with our support team and a dedicated program manager for non-technical questions.': '技術的な質問については、Appwriteコミュニティにアクセスできます。プログラムメンバーはさらに、技術以外の質問向けに、サポートチームとのプライベートSlackチャネルと専任のプログラムマネージャーを利用できます。', // pragma: allowlist secret
  'You will get early access to new features and products and the ability to influence our roadmap.': '新機能やプロダクトへの早期アクセスと、ロードマップに影響を与える機会が得られます。',
  'The Education plan lasts six months from the day you join, and each account can join once. The Console reminds you five weeks before your term ends.': 'Educationプランの期間は参加した日から6か月で、各アカウントが参加できるのは1回のみです。期間終了の5週間前にコンソールでお知らせします。', // pragma: allowlist secret
  'What happens when my Education plan ends?': 'Educationプランが終了したらどうなりますか?', // pragma: allowlist secret
  "Before your term ends, choose the plan that fits what you're building next: Free for learning and side projects, Pro for apps that need more resources, or Start for students in India and Nepal. Your projects, data, and settings stay exactly as they are. If you don't choose a plan by the end date, your organization will be disabled until you select one. Projects are only deleted later, according to our standard retention process.": '期間が終わる前に、次に作るものに合ったプランを選んでください。学習やサイドプロジェクトにはFree、より多くのリソースが必要なアプリにはPro、インドとネパールの学生にはStartがあります。プロジェクト、データ、設定はそのまま引き継がれます。終了日までにプランを選ばない場合、プランを選ぶまで組織は無効になります。プロジェクトがすぐに削除されることはなく、通常のデータ保持ポリシーに従って後日削除されます。', // pragma: allowlist secret
  'Your company is 5 years old or younger and has raised funding (pre-seed through Series A) or bootstrapped revenue up to $5M in annual recurring revenue.': '会社の設立が5年以内で、資金調達(プレシードからSeries Aまで)を行っているか、年間経常収益$500万までのブートストラップ収益があること。',
  'Are you a founder looking to build with Appwrite? Learn more about our Startups program on our Startups': 'Appwriteで構築を目指す創業者の方ですか?Startupsプログラムについて詳しくは、こちらのStartups', // pragma: allowlist secret
  'From global enterprises to fast-growing product companies, teams rely on Appwrite to ship secure applications.': 'グローバル企業から急成長中のプロダクト企業まで、チームは安全なアプリケーションをリリースするためにAppwriteを信頼しています。', // pragma: allowlist secret
  'Give your developers a complete backend platform so they can focus on product innovation instead of infrastructure glue code.': '開発者に完全なバックエンドプラットフォームを提供し、インフラのグルーコードではなくプロダクトのイノベーションに集中できるようにしましょう。',
  'Ready to explore a custom plan? Share your requirements and one of our experts will follow up with a tailored proposal.': 'カスタムプランをご検討中ですか?ご要件をお聞かせいただければ、専門家が個別のご提案でご連絡します。',
  'The OSS program is exclusively for active open-source maintainers using Appwrite Cloud. You can find more information on how to join the program in our': 'OSSプログラムは、Appwrite Cloudを利用しているアクティブなオープンソースメンテナー限定です。プログラムへの参加方法の詳細は、こちらの', // pragma: allowlist secret
  'The Reserve Bank of India (RBI) mandates additional security measures for recurring payments on Indian cards. Appwrite is obligated to ask for verification before billing your card. Appwrite asks for verification for up to $150 in case you use add-ons, but will not charge more than the actual amount used or your budget cap. If you need higher limits,': 'インド準備銀行(RBI)は、インドのカードでの継続支払いに対して追加のセキュリティ対策を義務付けています。Appwriteはカードへの請求前に確認を求める必要があります。Appwriteはアドオンを利用する場合に備えて最大$150の確認を求めますが、実際に使用した金額または予算上限を超えて請求することはありません。より高い上限が必要な場合は、', // pragma: allowlist secret
  'Yes, you can sign a BAA with Appwrite. Learn more about our security and compliance in our': 'はい、AppwriteとBAAを締結できます。セキュリティとコンプライアンスの詳細は、こちらの', // pragma: allowlist secret
  'Your project will continue to run, and additional charges will apply. You can find the costs for additional resources in the pricing plans comparison below. We will also send you email reminders when you hit 75% and 100% of your resource limits. To avoid unexpected payments, you can set up a': 'プロジェクトはそのまま稼働を続け、追加料金が発生します。追加リソースの料金は、以下の料金プラン比較でご確認いただけます。リソース制限の75%と100%に達した際にはメールでお知らせします。予期しない支払いを避けるために、',
  'Your project will freeze, and Appwrite Console will continue running in read-only mode. You need to upgrade to Pro, remove resources that exceed their limit, or wait for the next billing cycle, which resets usage limits.': 'プロジェクトは停止し、Appwriteコンソールは読み取り専用モードで稼働を続けます。Proにアップグレードするか、制限を超えたリソースを削除するか、利用制限がリセットされる次の請求サイクルまでお待ちいただく必要があります。', // pragma: allowlist secret
}
