/**
 * URLs for the two halves of the CLI artifact.
 *
 * They come from the `appwrite-cli-wasm` dependency rather than a hand-placed
 * file, so the version is pinned by the lockfile and the build emits both as
 * fingerprinted assets. `wasm_exec.js` is Go's runtime glue: it is generated by
 * the toolchain, only works with a module that toolchain produced, and the
 * package publishes the two together for exactly that reason -- taking one from
 * anywhere else invites a pair that does not match.
 *
 * Kept apart from constants.ts because `?url` is a Vite feature, and the unit
 * tests import the runtime under Bun, which has no idea what it means.
 */

import wasmUrl from 'appwrite-cli-wasm/appwrite.wasm?url'
import wasmExecUrl from 'appwrite-cli-wasm/wasm_exec.js?url'

/** Overridable so a local `go build` can be pointed at without a reinstall. */
export const CLI_WASM_URL: string =
  import.meta.env.VITE_APPWRITE_CLI_WASM_URL ?? wasmUrl

export const CLI_WASM_EXEC_URL: string =
  import.meta.env.VITE_APPWRITE_CLI_WASM_EXEC_URL ?? wasmExecUrl
