//! Encodings: URL encoding, `http_build_query`, base64, hex, HTML entities,
//! backslash escaping and quoted-printable.
//!
//! Ported from PHP 8.5.10 (`ext/standard/url.c`, `http.c`, `base64.c`,
//! `string.c`, `html.c`, `quot_print.c`). Byte strings in, byte strings out;
//! encoders whose output is always ASCII return `String`.
//!
//! | PHP | Rust |
//! |---|---|
//! | `urlencode`, `rawurlencode`, `urldecode`, `rawurldecode` | [`urlencode`], [`rawurlencode`], [`urldecode`], [`rawurldecode`] |
//! | `http_build_query` | [`http_build_query`] with [`QueryEncoding`] |
//! | `parse_str` | [`parse_str`] |
//! | `base64_encode`, `base64_decode` | [`base64_encode`], [`base64_decode`] |
//! | `bin2hex`, `hex2bin` | [`bin2hex`], [`hex2bin`] |
//! | `htmlspecialchars`, `htmlentities` | [`htmlspecialchars`], [`htmlentities`] with [`HtmlFlags`] |
//! | `htmlspecialchars_decode`, `html_entity_decode` | [`htmlspecialchars_decode`], [`html_entity_decode`] |
//! | `addslashes`, `stripslashes` | [`addslashes`], [`stripslashes`] |
//! | `quoted_printable_encode`, `quoted_printable_decode` | [`quoted_printable_encode`], [`quoted_printable_decode`] |
//!
//! The HTML functions support PHP's default charset, UTF-8. Their entity
//! tables (`encoding/html_tables.rs`) are generated by
//! `data/html_entities.py` from php-src's `ext/standard/html_tables.h` and
//! PHP's own `get_html_translation_table()` (`data/html_entities.php`).
//!
//! Every function here is checked against the real PHP function by
//! `bin/compat fuzz php-std` (operations `encoding.*`).

mod html_tables;
mod query;

pub use query::parse_str;

use std::borrow::Cow;

use serde_json::Value;

use crate::number;
use crate::string::hex_value;

const HEX_UPPER: &[u8; 16] = b"0123456789ABCDEF";
const HEX_LOWER: &[u8; 16] = b"0123456789abcdef";

// ---------------------------------------------------------------------------
// URL encoding
// ---------------------------------------------------------------------------

fn url_encode_into(out: &mut Vec<u8>, s: &[u8], raw: bool) {
    for &c in s {
        if !raw && c == b' ' {
            out.push(b'+');
        } else if c.is_ascii_alphanumeric() || c == b'-' || c == b'.' || c == b'_' || (raw && c == b'~') {
            out.push(c);
        } else {
            out.extend_from_slice(&[b'%', HEX_UPPER[(c >> 4) as usize], HEX_UPPER[(c & 15) as usize]]);
        }
    }
}

/// PHP `urlencode`: `application/x-www-form-urlencoded` (RFC 1738):
/// alphanumerics and `-_.` are kept, a space is `+`, every other byte
/// (including `~`) is `%XX`.
pub fn urlencode(s: &[u8]) -> String {
    let mut out = Vec::with_capacity(s.len() * 3);
    url_encode_into(&mut out, s, false);
    String::from_utf8(out).unwrap_or_default()
}

/// PHP `rawurlencode` (RFC 3986): alphanumerics and `-_.~` are kept, every
/// other byte is `%XX`.
pub fn rawurlencode(s: &[u8]) -> String {
    let mut out = Vec::with_capacity(s.len() * 3);
    url_encode_into(&mut out, s, true);
    String::from_utf8(out).unwrap_or_default()
}

fn url_decode(s: &[u8], plus: bool) -> Vec<u8> {
    let mut out = Vec::with_capacity(s.len());
    let mut i = 0;
    while i < s.len() {
        let c = s[i];
        if plus && c == b'+' {
            out.push(b' ');
        } else if c == b'%' && i + 2 < s.len() && s[i + 1].is_ascii_hexdigit() && s[i + 2].is_ascii_hexdigit() {
            out.push(hex_value(s[i + 1]) * 16 + hex_value(s[i + 2]));
            i += 2;
        } else {
            out.push(c);
        }
        i += 1;
    }
    out
}

/// PHP `urldecode`: `+` is a space and `%XX` a byte; a `%` not followed by
/// two hex digits is kept.
pub fn urldecode(s: &[u8]) -> Vec<u8> {
    url_decode(s, true)
}

/// PHP `rawurldecode`: `%XX` is a byte (`+` stays `+`).
pub fn rawurldecode(s: &[u8]) -> Vec<u8> {
    url_decode(s, false)
}

// ---------------------------------------------------------------------------
// http_build_query
// ---------------------------------------------------------------------------

/// `http_build_query()`'s `$encoding_type`.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub enum QueryEncoding {
    /// `PHP_QUERY_RFC1738` (1, the default): spaces as `+` ([`urlencode`]).
    #[default]
    Rfc1738,
    /// `PHP_QUERY_RFC3986` (2): spaces as `%20` ([`rawurlencode`]).
    Rfc3986,
}

impl QueryEncoding {
    /// PHP's value: 2 is RFC 3986, and every other integer RFC 1738 (PHP
    /// does not validate it).
    pub fn from_php(value: i64) -> Self {
        if value == 2 { QueryEncoding::Rfc3986 } else { QueryEncoding::Rfc1738 }
    }
}

/// Whether a PHP array key string is an integer key (`ZEND_HANDLE_NUMERIC_STR`):
/// `-?[1-9][0-9]*` or `0`, within `i64`.
pub fn is_integer_key(key: &str) -> bool {
    let digits = key.strip_prefix('-').unwrap_or(key);
    if digits.is_empty() || !digits.bytes().all(|b| b.is_ascii_digit()) {
        return false;
    }
    if digits.starts_with('0') && key.len() > 1 {
        return false;
    }
    key.parse::<i64>().is_ok()
}

struct QueryBuilder<'a> {
    out: Vec<u8>,
    separator: &'a [u8],
    raw: bool,
}

impl QueryBuilder<'_> {
    fn scalar(&mut self, key: &str, value: &Value, prefix: Option<&[u8]>, numeric_prefix: Option<&[u8]>) {
        if !self.out.is_empty() {
            self.out.extend_from_slice(self.separator);
        }
        if let Some(p) = prefix {
            self.out.extend_from_slice(p);
        }
        if is_integer_key(key) {
            if let Some(np) = numeric_prefix {
                self.out.extend_from_slice(np);
            }
            self.out.extend_from_slice(key.as_bytes());
        } else {
            url_encode_into(&mut self.out, key.as_bytes(), self.raw);
        }
        if prefix.is_some() {
            self.out.extend_from_slice(b"%5D");
        }
        self.out.push(b'=');
        match value {
            Value::String(s) => url_encode_into(&mut self.out, s.as_bytes(), self.raw),
            Value::Number(n) => match crate::value::json_number(n) {
                crate::value::Number::Int(i) => self.out.extend_from_slice(i.to_string().as_bytes()),
                crate::value::Number::Float(f) => {
                    url_encode_into(&mut self.out, number::to_string(f).as_bytes(), self.raw)
                }
            },
            Value::Bool(b) => self.out.push(if *b { b'1' } else { b'0' }),
            _ => {}
        }
    }

    fn hash(&mut self, data: &Value, prefix: Option<&[u8]>, numeric_prefix: Option<&[u8]>) {
        let entries: Vec<(Cow<'_, str>, &Value)> = match data {
            Value::Array(a) => a.iter().enumerate().map(|(i, v)| (Cow::Owned(i.to_string()), v)).collect(),
            Value::Object(o) => o.iter().map(|(k, v)| (Cow::Borrowed(k.as_str()), v)).collect(),
            _ => return,
        };
        for (key, value) in entries {
            match value {
                Value::Array(_) | Value::Object(_) => {
                    let mut next = Vec::new();
                    if is_integer_key(&key) {
                        match (prefix, numeric_prefix) {
                            (Some(p), Some(np)) => {
                                next.extend_from_slice(p);
                                next.extend_from_slice(np);
                                next.extend_from_slice(key.as_bytes());
                                next.extend_from_slice(b"%5D%5B");
                            }
                            (Some(p), None) => {
                                next.extend_from_slice(p);
                                next.extend_from_slice(key.as_bytes());
                                next.extend_from_slice(b"%5D%5B");
                            }
                            (None, Some(np)) => {
                                next.extend_from_slice(np);
                                next.extend_from_slice(key.as_bytes());
                                next.extend_from_slice(b"%5B");
                            }
                            (None, None) => {
                                next.extend_from_slice(key.as_bytes());
                                next.extend_from_slice(b"%5B");
                            }
                        }
                    } else {
                        let mut encoded = Vec::new();
                        url_encode_into(&mut encoded, key.as_bytes(), self.raw);
                        match prefix {
                            Some(p) => {
                                next.extend_from_slice(p);
                                next.extend_from_slice(&encoded);
                                next.extend_from_slice(b"%5D%5B");
                            }
                            None => {
                                next.extend_from_slice(&encoded);
                                next.extend_from_slice(b"%5B");
                            }
                        }
                    }
                    self.hash(value, Some(&next), None);
                }
                Value::Null => {}
                _ => self.scalar(&key, value, prefix, numeric_prefix),
            }
        }
    }
}

/// PHP `http_build_query($data, $numeric_prefix, $arg_separator, $encoding_type)`
/// for data decoded from JSON (objects are PHP arrays; keys that are
/// canonical integers are integer keys, which get `numeric_prefix` at the
/// top level). Nested arrays become `a%5Bb%5D=...`; `null` values are
/// skipped, booleans are `1`/`0`, floats use `precision` 14.
/// `arg_separator` `None` is PHP's `arg_separator.output` default, `&`.
pub fn http_build_query(
    data: &Value,
    numeric_prefix: &[u8],
    arg_separator: Option<&[u8]>,
    encoding: QueryEncoding,
) -> Vec<u8> {
    let mut b = QueryBuilder {
        out: Vec::new(),
        separator: arg_separator.unwrap_or(b"&"),
        raw: encoding == QueryEncoding::Rfc3986,
    };
    b.hash(data, None, Some(numeric_prefix));
    b.out
}

// ---------------------------------------------------------------------------
// base64 and hex
// ---------------------------------------------------------------------------

const BASE64: &[u8; 64] = b"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";

/// PHP `base64_encode`: standard alphabet with `=` padding.
pub fn base64_encode(s: &[u8]) -> String {
    let mut out = String::with_capacity(s.len().div_ceil(3) * 4);
    for chunk in s.chunks(3) {
        let b = [chunk[0], *chunk.get(1).unwrap_or(&0), *chunk.get(2).unwrap_or(&0)];
        out.push(BASE64[(b[0] >> 2) as usize] as char);
        out.push(BASE64[(((b[0] & 0x03) << 4) | (b[1] >> 4)) as usize] as char);
        out.push(if chunk.len() > 1 { BASE64[(((b[1] & 0x0f) << 2) | (b[2] >> 6)) as usize] as char } else { '=' });
        out.push(if chunk.len() > 2 { BASE64[(b[2] & 0x3f) as usize] as char } else { '=' });
    }
    out
}

/// `base64_reverse_table`: a value, -1 for skipped white space, -2 otherwise.
fn base64_value(c: u8) -> i32 {
    match c {
        b'A'..=b'Z' => (c - b'A') as i32,
        b'a'..=b'z' => (c - b'a') as i32 + 26,
        b'0'..=b'9' => (c - b'0') as i32 + 52,
        b'+' => 62,
        b'/' => 63,
        b'\t' | b'\n' | b'\r' | b' ' => -1,
        _ => -2,
    }
}

/// PHP `base64_decode($string, $strict)`. Non-strict skips every byte that
/// is not in the alphabet (and decodes data after `=` padding); strict skips
/// only `\t \n \r` and spaces and fails (`None`, PHP's `false`) on anything
/// else, on data after padding, on a lone final character or on bad padding.
pub fn base64_decode(s: &[u8], strict: bool) -> Option<Vec<u8>> {
    let mut out: Vec<u8> = Vec::with_capacity(s.len() / 4 * 3 + 3);
    let put = |out: &mut Vec<u8>, j: usize, v: u8, or: bool| {
        if j == out.len() {
            out.push(0);
        }
        if or { out[j] |= v } else { out[j] = v }
    };
    let (mut i, mut padding, mut j) = (0usize, 0usize, 0usize);
    for &c in s {
        if c == b'=' {
            padding += 1;
            continue;
        }
        let ch = base64_value(c);
        if !strict {
            if ch < 0 {
                continue;
            }
        } else {
            if ch == -1 {
                continue;
            }
            if ch == -2 || padding > 0 {
                return None;
            }
        }
        let ch = ch as u8;
        match i % 4 {
            0 => put(&mut out, j, ch << 2, false),
            1 => {
                put(&mut out, j, ch >> 4, true);
                j += 1;
                put(&mut out, j, (ch & 0x0f) << 4, false);
            }
            2 => {
                put(&mut out, j, ch >> 2, true);
                j += 1;
                put(&mut out, j, (ch & 0x03) << 6, false);
            }
            _ => {
                put(&mut out, j, ch, true);
                j += 1;
            }
        }
        i += 1;
    }
    if strict && i % 4 == 1 {
        return None;
    }
    if strict && padding > 0 && (padding > 2 || (i + padding) % 4 != 0) {
        return None;
    }
    out.truncate(j);
    Some(out)
}

/// PHP `bin2hex`: lowercase hexadecimal.
pub fn bin2hex(s: &[u8]) -> String {
    let mut out = String::with_capacity(s.len() * 2);
    for &b in s {
        out.push(HEX_LOWER[(b >> 4) as usize] as char);
        out.push(HEX_LOWER[(b & 15) as usize] as char);
    }
    out
}

/// PHP `hex2bin`: `None` (PHP's `false`, with a warning) for an odd length
/// or a non-hexadecimal character.
pub fn hex2bin(s: &[u8]) -> Option<Vec<u8>> {
    if !s.len().is_multiple_of(2) || !s.iter().all(u8::is_ascii_hexdigit) {
        return None;
    }
    Some(s.chunks(2).map(|p| hex_value(p[0]) * 16 + hex_value(p[1])).collect())
}

// ---------------------------------------------------------------------------
// Slashes and quoted-printable
// ---------------------------------------------------------------------------

/// PHP `addslashes`: backslash before `'`, `"` and `\`, and NUL as `\0`.
pub fn addslashes(s: &[u8]) -> Cow<'_, [u8]> {
    if !s.iter().any(|&c| matches!(c, 0 | b'\'' | b'"' | b'\\')) {
        return Cow::Borrowed(s);
    }
    let mut out = Vec::with_capacity(s.len() + 8);
    for &c in s {
        match c {
            0 => out.extend_from_slice(b"\\0"),
            b'\'' | b'"' | b'\\' => out.extend_from_slice(&[b'\\', c]),
            _ => out.push(c),
        }
    }
    Cow::Owned(out)
}

/// PHP `stripslashes`: drops each backslash and keeps the byte after it
/// (`\0` is NUL); a trailing backslash is dropped.
pub fn stripslashes(s: &[u8]) -> Vec<u8> {
    let mut out = Vec::with_capacity(s.len());
    let mut i = 0;
    while i < s.len() {
        if s[i] == b'\\' {
            i += 1;
            if i < s.len() {
                out.push(if s[i] == b'0' { 0 } else { s[i] });
                i += 1;
            }
        } else {
            out.push(s[i]);
            i += 1;
        }
    }
    out
}

/// PHP `quoted_printable_encode` (RFC 2045, lines of at most 76 bytes with
/// PHP's look-ahead for multi-byte UTF-8 lead bytes).
pub fn quoted_printable_encode(s: &[u8]) -> Vec<u8> {
    const MAXL: u64 = 75;
    let mut out = Vec::with_capacity(s.len() * 3);
    let mut lp: u64 = 0;
    let mut i = 0;
    let at = |k: usize| s.get(k).copied().unwrap_or(0);
    while i < s.len() {
        let c = s[i];
        i += 1;
        let remaining = s.len() - i;
        if c == b'\r' && at(i) == b'\n' && remaining > 0 {
            out.extend_from_slice(b"\r\n");
            i += 1;
            lp = 0;
        } else if c < 32 || c == 0x7f || c & 0x80 != 0 || c == b'=' || (c == b' ' && at(i) == b'\r') {
            lp += 3;
            if (lp > MAXL && c <= 0x7f)
                || (c > 0x7f && c <= 0xdf && lp + 3 > MAXL)
                || (c > 0xdf && c <= 0xef && lp + 6 > MAXL)
                || (c > 0xef && c <= 0xf4 && lp + 9 > MAXL)
            {
                out.extend_from_slice(b"=\r\n");
                lp = 3;
            }
            out.extend_from_slice(&[b'=', HEX_UPPER[(c >> 4) as usize], HEX_UPPER[(c & 15) as usize]]);
        } else {
            lp += 1;
            if lp > MAXL {
                out.extend_from_slice(b"=\r\n");
                lp = 1;
            }
            out.push(c);
        }
    }
    out
}

/// PHP `quoted_printable_decode`: `=XX` is a byte, `=` before (spaces and)
/// a line break or the end is a soft break. Stops at a NUL byte, as PHP does.
pub fn quoted_printable_decode(s: &[u8]) -> Vec<u8> {
    let at = |k: usize| s.get(k).copied().unwrap_or(0);
    let mut out = Vec::with_capacity(s.len());
    let mut i = 0;
    while at(i) != 0 {
        if at(i) == b'=' {
            if at(i + 1) != 0 && at(i + 2) != 0 && at(i + 1).is_ascii_hexdigit() && at(i + 2).is_ascii_hexdigit() {
                out.push(hex_value(at(i + 1)) * 16 + hex_value(at(i + 2)));
                i += 3;
            } else {
                let mut k = 1;
                while at(i + k) != 0 && (at(i + k) == b' ' || at(i + k) == b'\t') {
                    k += 1;
                }
                if at(i + k) == 0 {
                    i += k;
                } else if at(i + k) == b'\r' && at(i + k + 1) == b'\n' {
                    i += k + 2;
                } else if at(i + k) == b'\r' || at(i + k) == b'\n' {
                    i += k + 1;
                } else {
                    out.push(at(i));
                    i += 1;
                }
            }
        } else {
            out.push(at(i));
            i += 1;
        }
    }
    out
}

// ---------------------------------------------------------------------------
// HTML entities
// ---------------------------------------------------------------------------

/// The document type of the `ENT_HTML401`/`ENT_XML1`/`ENT_XHTML`/`ENT_HTML5` flags.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub enum Doctype {
    /// `ENT_HTML401` (0), the default.
    #[default]
    Html401,
    /// `ENT_XML1` (16).
    Xml1,
    /// `ENT_XHTML` (32).
    Xhtml,
    /// `ENT_HTML5` (48).
    Html5,
}

/// The `$flags` of the HTML functions, decoded from PHP's bit mask.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct HtmlFlags {
    /// `ENT_HTML_QUOTE_SINGLE` (1): convert `'`.
    pub single_quotes: bool,
    /// `ENT_HTML_QUOTE_DOUBLE` (2, `ENT_COMPAT`): convert `"`.
    pub double_quotes: bool,
    /// `ENT_IGNORE` (4): drop invalid UTF-8 (wins over `substitute`).
    pub ignore: bool,
    /// `ENT_SUBSTITUTE` (8): replace invalid UTF-8 with U+FFFD. Without it
    /// (and without `ignore`) invalid UTF-8 makes the result empty.
    pub substitute: bool,
    /// `ENT_DISALLOWED` (128): replace code points the doctype disallows.
    pub disallowed: bool,
    pub doctype: Doctype,
}

impl HtmlFlags {
    /// PHP's default, `ENT_QUOTES | ENT_SUBSTITUTE | ENT_HTML401`.
    pub const DEFAULT: Self = Self::from_php(3 | 8);

    /// The flags of PHP's integer `$flags` (other bits are ignored, as in PHP).
    pub const fn from_php(flags: i64) -> Self {
        HtmlFlags {
            single_quotes: flags & 1 != 0,
            double_quotes: flags & 2 != 0,
            ignore: flags & 4 != 0,
            substitute: flags & 8 != 0,
            disallowed: flags & 128 != 0,
            doctype: match flags & 48 {
                0 => Doctype::Html401,
                16 => Doctype::Xml1,
                32 => Doctype::Xhtml,
                _ => Doctype::Html5,
            },
        }
    }
}

impl Default for HtmlFlags {
    fn default() -> Self {
        Self::DEFAULT
    }
}

/// `get_next_char` for UTF-8: a code point, or how many bytes an invalid
/// sequence spans (PHP's "strategy 2" of UTR #36).
fn next_utf8(s: &[u8], pos: usize) -> Result<(u32, usize), usize> {
    let avail = s.len() - pos;
    let c = s[pos];
    let lead = |b: u8| b < 0x80 || (0xC2..=0xF4).contains(&b);
    let trail = |b: u8| (0x80..=0xBF).contains(&b);
    if c < 0x80 {
        return Ok((c as u32, 1));
    }
    if c < 0xC2 {
        return Err(1);
    }
    if c < 0xE0 {
        if avail < 2 {
            return Err(1);
        }
        if !trail(s[pos + 1]) {
            return Err(if lead(s[pos + 1]) { 1 } else { 2 });
        }
        return Ok((((c as u32 & 0x1F) << 6) | (s[pos + 1] as u32 & 0x3F), 2));
    }
    if c < 0xF0 {
        if avail < 3 || !trail(s[pos + 1]) || !trail(s[pos + 2]) {
            return Err(if avail < 2 || lead(s[pos + 1]) {
                1
            } else if avail < 3 || lead(s[pos + 2]) {
                2
            } else {
                3
            });
        }
        let cp = ((c as u32 & 0x0F) << 12) | ((s[pos + 1] as u32 & 0x3F) << 6) | (s[pos + 2] as u32 & 0x3F);
        if cp < 0x800 || (0xD800..=0xDFFF).contains(&cp) {
            return Err(3);
        }
        return Ok((cp, 3));
    }
    if c < 0xF5 {
        if avail < 4 || !trail(s[pos + 1]) || !trail(s[pos + 2]) || !trail(s[pos + 3]) {
            return Err(if avail < 2 || lead(s[pos + 1]) {
                1
            } else if avail < 3 || lead(s[pos + 2]) {
                2
            } else if avail < 4 || lead(s[pos + 3]) {
                3
            } else {
                4
            });
        }
        let cp = ((c as u32 & 0x07) << 18)
            | ((s[pos + 1] as u32 & 0x3F) << 12)
            | ((s[pos + 2] as u32 & 0x3F) << 6)
            | (s[pos + 3] as u32 & 0x3F);
        if !(0x10000..=0x10FFFF).contains(&cp) {
            return Err(4);
        }
        return Ok((cp, 4));
    }
    Err(1)
}

/// `unicode_cp_is_allowed`.
fn cp_allowed(cp: u32, doctype: Doctype) -> bool {
    match doctype {
        Doctype::Html401 => {
            (0x20..=0x7E).contains(&cp)
                || cp == 0x0A
                || cp == 0x09
                || cp == 0x0D
                || (0xA0..=0xD7FF).contains(&cp)
                || (0xE000..=0x10FFFF).contains(&cp)
        }
        Doctype::Html5 => {
            (0x20..=0x7E).contains(&cp)
                || ((0x09..=0x0D).contains(&cp) && cp != 0x0B)
                || (0xA0..=0xD7FF).contains(&cp)
                || ((0xE000..=0x10FFFF).contains(&cp) && (cp & 0xFFFF) < 0xFFFE && !(0xFDD0..=0xFDEF).contains(&cp))
        }
        Doctype::Xhtml | Doctype::Xml1 => {
            (0x20..=0xD7FF).contains(&cp)
                || cp == 0x0A
                || cp == 0x09
                || cp == 0x0D
                || ((0xE000..=0x10FFFF).contains(&cp) && cp != 0xFFFE && cp != 0xFFFF)
        }
    }
}

/// `numeric_entity_is_allowed`.
fn numeric_allowed(cp: u32, doctype: Doctype) -> bool {
    match doctype {
        Doctype::Html401 => cp <= 0x10FFFF,
        Doctype::Html5 => {
            (0x20..=0x7E).contains(&cp)
                || ((0x09..=0x0C).contains(&cp) && cp != 0x0B)
                || ((0xA0..=0x10FFFF).contains(&cp) && (cp & 0xFFFF) < 0xFFFE && !(0xFDD0..=0xFDEF).contains(&cp))
        }
        Doctype::Xhtml | Doctype::Xml1 => cp_allowed(cp, doctype),
    }
}

/// `process_numeric_entity` from `pos` (just after `&#`): the code point and
/// the position of the closing `;`. Digits are read like C `strtol` (which
/// also accepts a `0x` prefix in hexadecimal entities).
fn numeric_entity(s: &[u8], pos: usize) -> Option<(u32, usize)> {
    let at = |k: usize| s.get(k).copied().unwrap_or(0);
    let mut p = pos;
    let hex = at(p) == b'x' || at(p) == b'X';
    if hex {
        p += 1;
    }
    if (hex && !at(p).is_ascii_hexdigit()) || (!hex && !at(p).is_ascii_digit()) {
        return None;
    }
    let base: u64 = if hex { 16 } else { 10 };
    if hex && at(p) == b'0' && at(p + 1) | 32 == b'x' {
        if at(p + 2).is_ascii_hexdigit() {
            p += 2;
        } else {
            // strtol stops after the "0"
            return if at(p + 1) == b';' { Some((0, p + 1)) } else { None };
        }
    }
    let mut value: u64 = 0;
    while at(p).is_ascii_hexdigit() && (hex || at(p).is_ascii_digit()) {
        value = value.saturating_mul(base).saturating_add(hex_value(at(p)) as u64);
        p += 1;
    }
    if at(p) != b';' || value > 0x10FFFF {
        return None;
    }
    Some((value as u32, p))
}

/// `process_named_entity_html` from `pos` (just after `&`): the name's end
/// (the `;`), for `[A-Za-z0-9]+;`.
fn named_entity(s: &[u8], pos: usize) -> Option<usize> {
    let mut p = pos;
    while p < s.len() && s[p].is_ascii_alphanumeric() {
        p += 1;
    }
    if p == pos || s.get(p) != Some(&b';') {
        return None;
    }
    Some(p)
}

fn decode_table(doctype: Doctype) -> &'static [(&'static str, u32, u32)] {
    match doctype {
        Doctype::Html5 => html_tables::HTML5_DECODE,
        _ => html_tables::HTML401_DECODE,
    }
}

/// A named entity for decoding (`resolve_named_entity_html`): `all` selects
/// the doctype's full table, else (and for XML 1.0) the basic entities.
fn resolve_named(name: &[u8], all: bool, doctype: Doctype) -> Option<(u32, u32)> {
    let basic = |apos: bool| -> Option<(u32, u32)> {
        Some(match name {
            b"quot" => (0x22, 0),
            b"amp" => (0x26, 0),
            b"lt" => (0x3C, 0),
            b"gt" => (0x3E, 0),
            b"apos" if apos => (0x27, 0),
            b"#039" if !apos => (0x27, 0),
            _ => return None,
        })
    };
    if !all {
        return basic(doctype != Doctype::Html401);
    }
    match doctype {
        Doctype::Xml1 => basic(true),
        _ => {
            let table = decode_table(doctype);
            table.binary_search_by(|(n, _, _)| n.as_bytes().cmp(name)).ok().map(|i| (table[i].1, table[i].2))
        }
    }
}

/// The basic entity of a character (`stage3_table_be_*`): XHTML, XML 1.0
/// and HTML5 use `apos`, HTML 4.01 `#039`.
fn basic_entity(c: u32, doctype: Doctype) -> Option<&'static str> {
    match c {
        0x22 => Some("quot"),
        0x26 => Some("amp"),
        0x27 => Some(if doctype == Doctype::Html401 { "#039" } else { "apos" }),
        0x3C => Some("lt"),
        0x3E => Some("gt"),
        _ => None,
    }
}

fn escape(s: &[u8], flags: HtmlFlags, double_encode: bool, all: bool) -> Vec<u8> {
    let doctype = flags.doctype;
    let all = all && doctype != Doctype::Xml1;
    let mut out = Vec::with_capacity(s.len() + s.len() / 4 + 16);
    let mut cursor = 0;
    while cursor < s.len() {
        let before = cursor;
        let (c, len) = match next_utf8(s, cursor) {
            Ok(v) => v,
            Err(advance) => {
                cursor += advance;
                if flags.ignore {
                    continue;
                } else if flags.substitute {
                    out.extend_from_slice("\u{FFFD}".as_bytes());
                    continue;
                }
                return Vec::new();
            }
        };
        cursor += len;
        if c != u32::from(b'&') {
            if (c == 0x27 && !flags.single_quotes) || (c == 0x22 && !flags.double_quotes) {
                out.extend_from_slice(&s[before..cursor]);
                continue;
            }
            let entity: Option<&str> = if all {
                if doctype == Doctype::Html5 {
                    let pair = html_tables::HTML5_ENCODE_PAIRS.iter().any(|&(a, _, _)| a == c);
                    let mut found = None;
                    if pair
                        && cursor < s.len()
                        && let Ok((next, next_len)) = next_utf8(s, cursor)
                        && let Some(&(_, _, name)) =
                            html_tables::HTML5_ENCODE_PAIRS.iter().find(|&&(a, b, _)| a == c && b == next)
                    {
                        found = Some(name);
                        cursor += next_len;
                    }
                    found.or_else(|| lookup_encode(html_tables::HTML5_ENCODE, c))
                } else {
                    lookup_encode(html_tables::HTML401_ENCODE, c)
                }
            } else {
                basic_entity(c, doctype)
            };
            match entity {
                Some(name) => {
                    out.push(b'&');
                    out.extend_from_slice(name.as_bytes());
                    out.push(b';');
                }
                None => {
                    if flags.disallowed && !cp_allowed(c, doctype) {
                        out.extend_from_slice("\u{FFFD}".as_bytes());
                    } else {
                        out.extend_from_slice(&s[before..cursor]);
                    }
                }
            }
            continue;
        }
        // '&'
        if !double_encode {
            let valid_end = if s.get(cursor) == Some(&b'#') {
                numeric_entity(s, cursor + 1)
                    .filter(|&(cp, _)| !flags.disallowed || numeric_allowed(cp, doctype))
                    .map(|(_, e)| e)
            } else {
                named_entity(s, cursor).filter(|&end| {
                    let name = &s[cursor..end];
                    resolve_named(name, true, doctype).is_some() || (doctype == Doctype::Xhtml && name == b"apos")
                })
            };
            if let Some(end) = valid_end {
                out.push(b'&');
                out.extend_from_slice(&s[cursor..end]);
                out.push(b';');
                cursor = end + 1;
                continue;
            }
        }
        out.extend_from_slice(b"&amp;");
    }
    out
}

fn lookup_encode(table: &[(u32, &'static str)], c: u32) -> Option<&'static str> {
    table.binary_search_by_key(&c, |&(k, _)| k).ok().map(|i| table[i].1)
}

/// PHP `htmlspecialchars($string, $flags, 'UTF-8', $double_encode)`:
/// escapes `& < >` and the quotes `flags` selects (`'` as `&#039;` in HTML
/// 4.01, `&apos;` otherwise). With `double_encode` false, existing valid
/// entities are kept. Invalid UTF-8 follows `ENT_IGNORE`/`ENT_SUBSTITUTE`,
/// else the result is empty.
pub fn htmlspecialchars(s: &[u8], flags: HtmlFlags, double_encode: bool) -> Vec<u8> {
    escape(s, flags, double_encode, false)
}

/// PHP `htmlentities($string, $flags, 'UTF-8', $double_encode)`: like
/// [`htmlspecialchars`] but every character with a named entity in the
/// doctype's table is converted (HTML 4.01 and XHTML: 253 entities, HTML5:
/// 1511 including two-character ones such as `fj`; XML 1.0: the basic ones).
pub fn htmlentities(s: &[u8], flags: HtmlFlags, double_encode: bool) -> Vec<u8> {
    escape(s, flags, double_encode, true)
}

fn write_utf8(out: &mut Vec<u8>, cp: u32) {
    if let Some(c) = char::from_u32(cp) {
        let mut buf = [0u8; 4];
        out.extend_from_slice(c.encode_utf8(&mut buf).as_bytes());
    }
}

const LONGEST_ENTITY_LENGTH: usize = 31;

fn unescape(s: &[u8], flags: HtmlFlags, all: bool) -> Cow<'_, [u8]> {
    if !s.contains(&b'&') {
        return Cow::Borrowed(s);
    }
    let doctype = flags.doctype;
    let mut out = Vec::with_capacity(s.len());
    let mut cur = 0;
    while cur < s.len() {
        let Some(amp) = s[cur..].iter().position(|&c| c == b'&') else {
            out.extend_from_slice(&s[cur..]);
            break;
        };
        out.extend_from_slice(&s[cur..cur + amp]);
        cur += amp;
        if s.len() - cur < 4 {
            out.extend_from_slice(&s[cur..]);
            break;
        }
        // (code, code2, position of ';'), or None for an invalid entity.
        let parsed: Option<(u32, u32, usize)> = if s[cur + 1] == b'#' {
            numeric_entity(s, cur + 2).and_then(|(code, end)| {
                let basic_ok = code <= 63 && basic_entity(code, Doctype::Xhtml).is_some();
                if (!all && !basic_ok) || !cp_allowed(code, doctype) || (doctype == Doctype::Html5 && code == 0x0D) {
                    None
                } else {
                    Some((code, 0, end))
                }
            })
        } else {
            let name_start = cur + 1;
            let window = (LONGEST_ENTITY_LENGTH + 1).min(s.len() - name_start);
            s[name_start..name_start + window].iter().position(|&c| c == b';').and_then(|n| {
                if n == 0 {
                    return None;
                }
                let name = &s[name_start..name_start + n];
                match resolve_named(name, all, doctype) {
                    Some((a, b)) => Some((a, b, name_start + n)),
                    None if doctype == Doctype::Xhtml && name == b"apos" => Some((0x27, 0, name_start + n)),
                    None => None,
                }
            })
        };
        let Some((code, code2, end)) = parsed else {
            out.push(b'&');
            cur += 1;
            continue;
        };
        let quote_off = (code == 0x27 && !flags.single_quotes) || (code == 0x22 && !flags.double_quotes);
        if quote_off || (!all && (code > 0xFF || code2 != 0)) {
            // Invalid once parsed: copy up to the ';', which is then copied as text.
            out.extend_from_slice(&s[cur..end]);
            cur = end;
            continue;
        }
        write_utf8(&mut out, code);
        if code2 != 0 {
            write_utf8(&mut out, code2);
        }
        cur = end + 1;
    }
    Cow::Owned(out)
}

/// PHP `htmlspecialchars_decode($string, $flags)`: decodes `&amp; &lt; &gt;`
/// and the quotes `flags` selects (`&quot;`, `&#039;`/`&apos;` by doctype),
/// named or numeric.
pub fn htmlspecialchars_decode(s: &[u8], flags: HtmlFlags) -> Cow<'_, [u8]> {
    unescape(s, flags, false)
}

/// PHP `html_entity_decode($string, $flags, 'UTF-8')`: decodes every named
/// entity of the doctype's table and numeric entities of code points the
/// doctype allows, to UTF-8.
pub fn html_entity_decode(s: &[u8], flags: HtmlFlags) -> Cow<'_, [u8]> {
    unescape(s, flags, true)
}

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::json;

    #[test]
    fn url_like_php() {
        assert_eq!(urlencode(b"a b~c&"), "a+b%7Ec%26");
        assert_eq!(rawurlencode(b"a b~c&"), "a%20b~c%26");
        assert_eq!(urldecode(b"a+b%2"), b"a b%2");
    }

    #[test]
    fn query_like_php() {
        let data = json!({"a": 1, "b": [1, {"c": "x y"}], "0": true, "n": null});
        assert_eq!(
            http_build_query(&data, b"p", None, QueryEncoding::Rfc1738),
            b"a=1&b%5B0%5D=1&b%5B1%5D%5Bc%5D=x+y&p0=1"
        );
    }

    #[test]
    fn base64_like_php() {
        assert_eq!(base64_encode(b"ab"), "YWI=");
        assert_eq!(base64_decode(b"YW I=", true).unwrap(), b"ab");
        assert_eq!(base64_decode(b"YWI=x", true), None);
        assert_eq!(base64_decode(b"Y!WI", false).unwrap(), b"ab");
    }

    #[test]
    fn html_like_php() {
        let f = HtmlFlags::DEFAULT;
        assert_eq!(
            htmlspecialchars(b"<a href='x'>&amp;</a>", f, true),
            b"&lt;a href=&#039;x&#039;&gt;&amp;amp;&lt;/a&gt;"
        );
        assert_eq!(htmlspecialchars(b"&amp; &bogus;", f, false), b"&amp; &amp;bogus;");
        assert_eq!(htmlentities("café".as_bytes(), f, true), b"caf&eacute;");
        assert_eq!(html_entity_decode(b"&eacute;&#x41;&apos;", f).as_ref(), "éA&apos;".as_bytes());
        assert_eq!(htmlspecialchars(b"a\xFFb", HtmlFlags::from_php(3), true), b"");
    }
}
