//! Multibyte (mbstring) functions on UTF-8.
//!
//! Ported from PHP 8.5.10's `ext/mbstring` for the UTF-8 encoding (PHP's
//! default internal encoding), including its handling of invalid UTF-8:
//! the decoder turns each invalid sequence into one error marker (one
//! "character" for `mb_strlen`), and functions that re-encode text write
//! `?` (`mbstring.substitute_character`'s default) for it. Some functions
//! work on bytes and never re-encode (`mb_str_split`, `mb_strpos`,
//! `mb_strcut`); each function's docs say which.
//!
//! Case mapping uses PHP's own Unicode tables ([`unicode`], generated from
//! `unicode_data.h`), full or simple, with PHP's rules for the final sigma
//! and title case.
//!
//! | PHP | Rust |
//! |---|---|
//! | `mb_strlen` | [`mb_strlen`], [`mb_strlen_in`] with [`Encoding`] (`'8bit'`) |
//! | `mb_substr`, `mb_strcut`, `mb_str_split` | [`mb_substr`], [`mb_strcut`], [`mb_str_split`] |
//! | `mb_strtolower`, `mb_strtoupper`, `mb_convert_case` | [`mb_strtolower`], [`mb_strtoupper`], [`mb_convert_case`] with [`Case`] |
//! | `mb_ucfirst`, `mb_lcfirst` | [`mb_ucfirst`], [`mb_lcfirst`] |
//! | `mb_strpos`, `mb_strrpos`, `mb_stripos`, `mb_strripos` | [`mb_strpos`], [`mb_strrpos`], [`mb_stripos`], [`mb_strripos`] |
//! | `mb_strstr`, `mb_strrchr`, `mb_stristr`, `mb_strrichr` | [`mb_strstr`], [`mb_strrchr`], [`mb_stristr`], [`mb_strrichr`] |
//! | `mb_substr_count` | [`mb_substr_count`] |
//! | `mb_str_pad` | [`mb_str_pad`] with [`Pad`] |
//! | `mb_trim`, `mb_ltrim`, `mb_rtrim` | [`mb_trim`], [`mb_ltrim`], [`mb_rtrim`] |
//! | `mb_check_encoding`, `mb_scrub`, `mb_convert_encoding($s, 'UTF-8')` | [`mb_check_encoding`], [`mb_scrub`] |
//! | `mb_ord`, `mb_chr` | [`mb_ord`], [`mb_chr`] |
//!
//! Every function here is checked against the real PHP function by
//! `bin/compat fuzz php-std` (operations `mb.*`).
//!
//! # Unicode data
//!
//! `mb/unicode.rs` is generated by `data/unicode.py` from php-src's
//! `ext/mbstring/unicode_data.h` at tag `php-8.5.10`: the four case tables
//! (`_uccase_{upper,lower,title,fold}_table`, sorted by code point),
//! `_uccase_extra_table`, and the `UC_CASED` and `UC_CASE_IGNORABLE` ranges
//! of `_ucprop_ranges`. Every mode of `mb_convert_case` was compared with PHP
//! for every code point. Regenerate it when PHP updates its Unicode version,
//! and re-run `bin/compat fuzz php-std --op mb.convert_case`.

mod unicode;

use std::borrow::Cow;

use crate::string::{Error, Pad};

/// mbstring's error marker for an invalid byte sequence (`MBFL_BAD_INPUT`).
const BAD: u32 = u32::MAX;

/// `mblen_table_utf8`: the length a lead byte announces (1 for anything else).
fn utf8_len(b: u8) -> usize {
    match b {
        0xC2..=0xDF => 2,
        0xE0..=0xEF => 3,
        0xF0..=0xF4 => 4,
        _ => 1,
    }
}

fn is_continuation(b: u8) -> bool {
    (0x80..=0xBF).contains(&b)
}

/// `mb_utf8_to_wchar` for one code point: decodes at `*pos` and advances;
/// an invalid sequence yields [`BAD`] and consumes what PHP consumes.
fn decode_one(s: &[u8], pos: &mut usize) -> u32 {
    let e = s.len();
    let mut p = *pos;
    let c = s[p];
    p += 1;
    let w = if c < 0x80 {
        c as u32
    } else if c < 0xC2 {
        BAD
    } else if c <= 0xDF {
        if p < e {
            let c2 = s[p];
            p += 1;
            if c2 & 0xC0 != 0x80 {
                p -= 1;
                BAD
            } else {
                ((c as u32 & 0x1F) << 6) | (c2 as u32 & 0x3F)
            }
        } else {
            BAD
        }
    } else if c <= 0xEF {
        if e - p >= 2 {
            let (c2, c3) = (s[p], s[p + 1]);
            p += 2;
            if c2 & 0xC0 != 0x80 || (c == 0xE0 && c2 < 0xA0) || (c == 0xED && c2 >= 0xA0) {
                p -= 2;
                BAD
            } else if c3 & 0xC0 != 0x80 {
                p -= 1;
                BAD
            } else {
                ((c as u32 & 0xF) << 12) | ((c2 as u32 & 0x3F) << 6) | (c3 as u32 & 0x3F)
            }
        } else {
            if p < e && (c != 0xE0 || s[p] >= 0xA0) && (c != 0xED || s[p] < 0xA0) && s[p] & 0xC0 == 0x80 {
                p += 1;
                if p < e && s[p] & 0xC0 == 0x80 {
                    p += 1;
                }
            }
            BAD
        }
    } else if c <= 0xF4 {
        if e - p >= 3 {
            let (c2, c3, c4) = (s[p], s[p + 1], s[p + 2]);
            p += 3;
            if c2 & 0xC0 != 0x80 || (c == 0xF0 && c2 < 0x90) || (c == 0xF4 && c2 >= 0x90) {
                p -= 3;
                BAD
            } else if c3 & 0xC0 != 0x80 {
                p -= 2;
                BAD
            } else if c4 & 0xC0 != 0x80 {
                p -= 1;
                BAD
            } else {
                ((c as u32 & 0x7) << 18) | ((c2 as u32 & 0x3F) << 12) | ((c3 as u32 & 0x3F) << 6) | (c4 as u32 & 0x3F)
            }
        } else {
            if p < e {
                let c2 = s[p];
                if (c == 0xF0 && c2 >= 0x90) || (c == 0xF4 && c2 < 0x90) || (0xF1..=0xF3).contains(&c) {
                    while p < e && s[p] & 0xC0 == 0x80 {
                        p += 1;
                    }
                }
            }
            BAD
        }
    } else {
        BAD
    };
    *pos = p;
    w
}

/// The code points (and error markers) of `s`, as mbstring decodes UTF-8.
fn decode(s: &[u8]) -> impl Iterator<Item = u32> + '_ {
    let mut pos = 0;
    std::iter::from_fn(move || if pos < s.len() { Some(decode_one(s, &mut pos)) } else { None })
}

/// `mb_wchar_to_utf8`: appends `w`, or `bad` for an error marker or a value
/// beyond U+10FFFF. (PHP 8.5.10 encodes surrogates as they are.)
fn encode(out: &mut Vec<u8>, w: u32, bad: &[u8]) {
    if w < 0x80 {
        out.push(w as u8);
    } else if w < 0x800 {
        out.extend_from_slice(&[0xC0 | (w >> 6) as u8, 0x80 | (w & 0x3F) as u8]);
    } else if w < 0x10000 {
        out.extend_from_slice(&[0xE0 | (w >> 12) as u8, 0x80 | ((w >> 6) & 0x3F) as u8, 0x80 | (w & 0x3F) as u8]);
    } else if w < 0x110000 {
        out.extend_from_slice(&[
            0xF0 | (w >> 18) as u8,
            0x80 | ((w >> 12) & 0x3F) as u8,
            0x80 | ((w >> 6) & 0x3F) as u8,
            0x80 | (w & 0x3F) as u8,
        ]);
    } else {
        out.extend_from_slice(bad);
    }
}

/// What PHP writes for an invalid sequence when it re-encodes text.
const SUBSTITUTE: &[u8] = b"?";
/// The marker mbstring uses internally when searching (`ILLEGAL_MODE_BADUTF8`).
const SEARCH_MARKER: &[u8] = b"\xFF";

/// An encoding `mb_strlen` accepts.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub enum Encoding {
    /// `UTF-8` (PHP's default internal encoding).
    #[default]
    Utf8,
    /// `8bit` (alias `binary`): one character per byte.
    EightBit,
}

impl Encoding {
    /// The encoding for one of PHP's names (case-insensitive): `UTF-8`,
    /// `UTF8`, `8bit`, `binary`. `None` for anything else (PHP's
    /// `ValueError` for an unknown encoding, or an encoding not ported).
    pub fn from_name(name: &str) -> Option<Self> {
        match name.to_ascii_lowercase().as_str() {
            "utf-8" | "utf8" => Some(Encoding::Utf8),
            "8bit" | "binary" => Some(Encoding::EightBit),
            _ => None,
        }
    }
}

/// PHP `mb_strlen($string)`: the number of characters; each invalid
/// sequence counts as one.
pub fn mb_strlen(s: &[u8]) -> usize {
    let mut pos = 0;
    let mut n = 0;
    while pos < s.len() {
        decode_one(s, &mut pos);
        n += 1;
    }
    n
}

/// PHP `mb_strlen($string, $encoding)` for the encodings in [`Encoding`].
pub fn mb_strlen_in(s: &[u8], encoding: Encoding) -> usize {
    match encoding {
        Encoding::Utf8 => mb_strlen(s),
        Encoding::EightBit => s.len(),
    }
}

/// PHP `mb_check_encoding($value, 'UTF-8')` on a string: strict UTF-8
/// (no overlong forms, surrogates or code points above U+10FFFF).
pub fn mb_check_encoding(s: &[u8]) -> bool {
    std::str::from_utf8(s).is_ok()
}

/// PHP `mb_scrub($string)` and `mb_convert_encoding($string, 'UTF-8')`
/// from UTF-8: each invalid sequence becomes `?`. Borrows valid input.
pub fn mb_scrub(s: &[u8]) -> Cow<'_, [u8]> {
    if mb_check_encoding(s) {
        return Cow::Borrowed(s);
    }
    let mut out = Vec::with_capacity(s.len());
    for w in decode(s) {
        encode(&mut out, w, SUBSTITUTE);
    }
    Cow::Owned(out)
}

/// `mb_get_substr`: `len` characters from character `from`, re-encoded
/// (invalid sequences become `?`).
fn get_substr(s: &[u8], from: usize, len: usize) -> Vec<u8> {
    if len == 0 || from >= s.len() {
        return Vec::new();
    }
    let mut out = Vec::new();
    for w in decode(s).skip(from).take(len) {
        encode(&mut out, w, SUBSTITUTE);
    }
    out
}

/// PHP `mb_substr($string, $start, $length)`: characters from `start`
/// (negative: from the end) for `length` characters (negative: stop that
/// many before the end; `None`: to the end). Re-encodes: invalid sequences
/// in the result become `?`. `PHP_INT_MIN` for either argument is PHP's
/// `ValueError`.
pub fn mb_substr(s: &[u8], start: i64, length: Option<i64>) -> Result<Vec<u8>, Error> {
    let range_error = |n: u32, name: &str| {
        Error::argument("mb_substr", n, name, &format!("must be between {} and {}", i64::MIN + 1, i64::MAX))
    };
    if start == i64::MIN {
        return Err(range_error(2, "start"));
    }
    if length == Some(i64::MIN) {
        return Err(range_error(3, "length"));
    }
    let mblen = if start < 0 || length.is_some_and(|l| l < 0) { mb_strlen(s) } else { 0 };
    let from = if start >= 0 {
        start as usize
    } else if start.unsigned_abs() < mblen as u64 {
        mblen - start.unsigned_abs() as usize
    } else {
        0
    };
    let len = match length {
        None => usize::MAX,
        Some(l) if l >= 0 => l as usize,
        Some(l) if from < mblen && l.unsigned_abs() < (mblen - from) as u64 => mblen - from - l.unsigned_abs() as usize,
        Some(_) => 0,
    };
    Ok(get_substr(s, from, len))
}

/// PHP `mb_strcut($string, $start, $length)`: a byte range widened or
/// narrowed so it does not split a UTF-8 sequence (works on bytes, never
/// re-encodes).
pub fn mb_strcut(s: &[u8], start: i64, length: Option<i64>) -> &[u8] {
    let n = s.len() as i64;
    let mut from = start;
    let mut len = length.unwrap_or(n);
    if from < 0 {
        from = from.saturating_add(n).max(0);
    }
    if len < 0 {
        len = (n - from).saturating_add(len).max(0);
    }
    if from > n || len == 0 {
        return &[];
    }
    let at = |i: usize| s.get(i).copied().unwrap_or(0);
    let mut begin = from as usize;
    while begin > 0 && is_continuation(at(begin)) {
        begin -= 1;
    }
    let end = begin.saturating_add(len as usize);
    if end >= s.len() {
        return &s[begin..];
    }
    let mut end = end;
    while end > begin && is_continuation(s[end]) {
        end -= 1;
    }
    &s[begin..end]
}

/// PHP `mb_str_split($string, $length)`: chunks of `length` characters,
/// cut by the byte lengths UTF-8 lead bytes announce (works on bytes, never
/// re-encodes; a truncated sequence at the end is kept as it is).
pub fn mb_str_split(s: &[u8], length: i64) -> Result<Vec<&[u8]>, Error> {
    if length <= 0 {
        return Err(Error::argument("mb_str_split", 2, "length", "must be greater than 0"));
    }
    if length > (u32::MAX / 4) as i64 {
        return Err(Error::argument("mb_str_split", 2, "length", "is too large"));
    }
    let mut out = Vec::new();
    let mut p = 0;
    while p < s.len() {
        let chunk = p;
        let mut count = 0;
        while count < length && p < s.len() {
            p += utf8_len(s[p]);
            count += 1;
        }
        p = p.min(s.len());
        out.push(&s[chunk..p]);
    }
    Ok(out)
}

/// PHP `mb_ord($string)`: the first code point, `None` (PHP's `false`)
/// when the string starts with an invalid sequence. An empty string is
/// PHP's `ValueError`.
pub fn mb_ord(s: &[u8]) -> Result<Option<u32>, Error> {
    if s.is_empty() {
        return Err(Error::argument("mb_ord", 1, "string", "must not be empty"));
    }
    let w = decode_one(s, &mut 0);
    Ok(if w == BAD { None } else { Some(w) })
}

/// PHP `mb_chr($codepoint)`: the UTF-8 encoding of a scalar value; `None`
/// (PHP's `false`) for surrogates and values outside 0..=0x10FFFF.
pub fn mb_chr(codepoint: i64) -> Option<Vec<u8>> {
    if !(0..=0x10FFFF).contains(&codepoint) || (0xD800..0xE000).contains(&codepoint) {
        return None;
    }
    let mut out = Vec::with_capacity(4);
    encode(&mut out, codepoint as u32, SUBSTITUTE);
    Some(out)
}

// ---------------------------------------------------------------------------
// Case mapping
// ---------------------------------------------------------------------------

/// `mb_convert_case()`'s `$mode` (`MB_CASE_*`).
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Case {
    /// `MB_CASE_UPPER` (0): full upper case (`ß` → `SS`).
    Upper,
    /// `MB_CASE_LOWER` (1): full lower case with the final sigma rule.
    Lower,
    /// `MB_CASE_TITLE` (2): title case per word, full mappings.
    Title,
    /// `MB_CASE_FOLD` (3): full case folding.
    Fold,
    /// `MB_CASE_UPPER_SIMPLE` (4).
    UpperSimple,
    /// `MB_CASE_LOWER_SIMPLE` (5).
    LowerSimple,
    /// `MB_CASE_TITLE_SIMPLE` (6).
    TitleSimple,
    /// `MB_CASE_FOLD_SIMPLE` (7).
    FoldSimple,
}

impl Case {
    /// The mode for PHP's `MB_CASE_*` value; `None` for anything else (PHP's
    /// `ValueError`).
    pub fn from_php(mode: i64) -> Option<Self> {
        Some(match mode {
            0 => Case::Upper,
            1 => Case::Lower,
            2 => Case::Title,
            3 => Case::Fold,
            4 => Case::UpperSimple,
            5 => Case::LowerSimple,
            6 => Case::TitleSimple,
            7 => Case::FoldSimple,
            _ => return None,
        })
    }
}

fn lookup(table: &[(u32, u32)], code: u32) -> Option<u32> {
    table.binary_search_by_key(&code, |&(k, _)| k).ok().map(|i| table[i].1)
}

fn in_ranges(ranges: &[(u32, u32)], code: u32) -> bool {
    match ranges.binary_search_by(|&(lo, _)| lo.cmp(&code)) {
        Ok(_) => true,
        Err(0) => false,
        Err(i) => code <= ranges[i - 1].1,
    }
}

fn is_cased(w: u32) -> bool {
    in_ranges(unicode::CASED, w)
}

fn is_case_ignorable(w: u32) -> bool {
    in_ranges(unicode::CASE_IGNORABLE, w)
}

fn toupper_raw(code: u32) -> u32 {
    if code < 0xB5 {
        if (0x61..=0x7A).contains(&code) { code - 0x20 } else { code }
    } else {
        lookup(unicode::UPPER, code).unwrap_or(code)
    }
}

fn tolower_raw(code: u32) -> u32 {
    if code < 0xC0 {
        if (0x41..=0x5A).contains(&code) { code + 0x20 } else { code }
    } else {
        lookup(unicode::LOWER, code).unwrap_or(code)
    }
}

fn totitle_raw(code: u32) -> u32 {
    lookup(unicode::TITLE, code).unwrap_or_else(|| toupper_raw(code))
}

fn tofold_raw(code: u32) -> u32 {
    if code < 0x80 {
        if (0x41..=0x5A).contains(&code) { code + 0x20 } else { code }
    } else {
        lookup(unicode::FOLD, code).unwrap_or(code)
    }
}

/// The simple mapping of a raw table value.
fn simple(raw: u32) -> u32 {
    if raw > 0xFFFFFF { unicode::EXTRA[(raw & 0xFFFFFF) as usize] } else { raw }
}

/// Writes a full mapping (`emit_special_casing_sequence`) or a code point.
fn emit(raw: u32, out: &mut [u32; 192], p: &mut usize) {
    if raw > 0xFFFFFF {
        let len = (raw >> 24) as usize;
        let at = (raw & 0xFFFFFF) as usize;
        for &w in &unicode::EXTRA[at + 1..=at + len] {
            out[*p] = w;
            *p += 1;
        }
    } else {
        out[*p] = raw;
        *p += 1;
    }
}

/// Whether the rest of the input, after the current chunk, continues with a
/// cased letter (skipping case-ignorable characters).
fn scan_ahead_for_cased(s: &[u8], mut pos: usize) -> bool {
    while pos < s.len() {
        let w = decode_one(s, &mut pos);
        if is_cased(w) {
            return true;
        }
        if !is_case_ignorable(w) {
            return false;
        }
    }
    false
}

/// `scan_back_for_cased_letter`: looks through what is left of the previous
/// chunk's converted output (`converted[begin..end]`, backwards).
fn scan_back_for_cased(converted: &[u32; 192], begin: usize, end: Option<usize>) -> bool {
    let Some(mut e) = end else { return false };
    while e > begin {
        e -= 1;
        let w = converted[e];
        if is_cased(w) {
            return true;
        }
        if !is_case_ignorable(w) {
            return false;
        }
    }
    false
}

/// Whether the capital sigma at `i` of the chunk ends a word (PHP's final
/// sigma rule, with its chunk-limited look-behind).
fn is_final_sigma(
    wbuf: &[u32],
    i: usize,
    s: &[u8],
    pos: usize,
    converted: &[u32; 192],
    p: usize,
    converted_end: Option<usize>,
) -> bool {
    let mut j = i as isize - 1;
    while j >= 0 && is_case_ignorable(wbuf[j as usize]) {
        j -= 1;
    }
    let before = if j >= 0 { is_cased(wbuf[j as usize]) } else { scan_back_for_cased(converted, p, converted_end) };
    if !before {
        return false;
    }
    let mut j = i + 1;
    while j < wbuf.len() && is_case_ignorable(wbuf[j]) {
        j += 1;
    }
    if j >= wbuf.len() { !scan_ahead_for_cased(s, pos) } else { !is_cased(wbuf[j]) }
}

/// `php_unicode_convert_case` for UTF-8 in and out, in chunks of 64 code
/// points like PHP (the final-sigma look-behind depends on them).
fn convert_case(s: &[u8], case: Case, bad: &[u8]) -> Vec<u8> {
    let mut out = Vec::with_capacity(s.len() + 1);
    let mut converted = [0u32; 192];
    let mut converted_end: Option<usize> = None;
    let mut title_mode = false;
    let mut pos = 0;
    let mut wbuf = [0u32; 64];
    while pos < s.len() {
        let mut n = 0;
        while pos < s.len() && n < 64 {
            wbuf[n] = decode_one(s, &mut pos);
            n += 1;
        }
        let w_in = &wbuf[..n];
        let mut p = 0;
        for (i, &w) in w_in.iter().enumerate() {
            if w > 0xFFFFFF {
                converted[p] = w;
                p += 1;
                continue;
            }
            match case {
                Case::UpperSimple => {
                    converted[p] = simple(toupper_raw(w));
                    p += 1;
                }
                Case::LowerSimple => {
                    converted[p] = simple(tolower_raw(w));
                    p += 1;
                }
                Case::FoldSimple => {
                    converted[p] = simple(tofold_raw(w));
                    p += 1;
                }
                Case::TitleSimple => {
                    converted[p] = if title_mode { simple(tolower_raw(w)) } else { simple(totitle_raw(w)) };
                    p += 1;
                    if !is_case_ignorable(w) {
                        title_mode = is_cased(w);
                    }
                }
                Case::Upper => emit(toupper_raw(w), &mut converted, &mut p),
                Case::Fold => emit(tofold_raw(w), &mut converted, &mut p),
                Case::Lower => {
                    if w == 0x3A3 && is_final_sigma(w_in, i, s, pos, &converted, p, converted_end) {
                        converted[p] = 0x3C2;
                        p += 1;
                    } else {
                        emit(tolower_raw(w), &mut converted, &mut p);
                    }
                }
                Case::Title => {
                    if title_mode {
                        if w == 0x3A3 && is_final_sigma(w_in, i, s, pos, &converted, p, converted_end) {
                            converted[p] = 0x3C2;
                            p += 1;
                        } else {
                            emit(tolower_raw(w), &mut converted, &mut p);
                        }
                    } else {
                        emit(totitle_raw(w), &mut converted, &mut p);
                    }
                    if !is_case_ignorable(w) {
                        title_mode = is_cased(w);
                    }
                }
            }
        }
        converted_end = Some(p);
        for &w in &converted[..p] {
            encode(&mut out, w, bad);
        }
    }
    out
}

/// PHP `mb_convert_case($string, $mode)`. Invalid sequences become `?`.
pub fn mb_convert_case(s: &[u8], case: Case) -> Vec<u8> {
    convert_case(s, case, SUBSTITUTE)
}

/// PHP `mb_strtoupper($string)`: full upper case (`MB_CASE_UPPER`).
pub fn mb_strtoupper(s: &[u8]) -> Vec<u8> {
    convert_case(s, Case::Upper, SUBSTITUTE)
}

/// PHP `mb_strtolower($string)`: full lower case with the final sigma rule
/// (`MB_CASE_LOWER`).
pub fn mb_strtolower(s: &[u8]) -> Vec<u8> {
    convert_case(s, Case::Lower, SUBSTITUTE)
}

/// `php_mb_ulcfirst`: converts the first character with `case`; returns the
/// input unchanged when that does not change it, else the converted first
/// character and the re-encoded rest.
fn ulcfirst(s: &[u8], case: Case) -> Cow<'_, [u8]> {
    let first = get_substr(s, 0, 1);
    let head = convert_case(&first, case, SUBSTITUTE);
    if head == first {
        return Cow::Borrowed(s);
    }
    let mut out = head;
    out.extend_from_slice(&get_substr(s, 1, usize::MAX));
    Cow::Owned(out)
}

/// PHP `mb_ucfirst($string)`: title-cases the first character (full mapping).
pub fn mb_ucfirst(s: &[u8]) -> Cow<'_, [u8]> {
    ulcfirst(s, Case::Title)
}

/// PHP `mb_lcfirst($string)`: lower-cases the first character.
pub fn mb_lcfirst(s: &[u8]) -> Cow<'_, [u8]> {
    ulcfirst(s, Case::Lower)
}

// ---------------------------------------------------------------------------
// Searching
// ---------------------------------------------------------------------------

/// `offset_to_pointer_utf8`: the byte position `offset` characters from the
/// start (or from the end, when negative), counting characters by lead bytes.
///
/// Deviation: PHP 8.5.10 can step past the end of a string that ends in a
/// truncated sequence and then reads out of bounds; this stops at the end
/// (as later PHP releases do).
fn offset_to_pointer(s: &[u8], offset: i64) -> Option<usize> {
    if offset < 0 {
        let mut pos = s.len();
        let mut offset = offset;
        while offset < 0 {
            if pos == 0 {
                return None;
            }
            pos -= 1;
            if !is_continuation(s[pos]) {
                offset += 1;
            }
        }
        Some(pos)
    } else {
        let mut pos = 0;
        let mut offset = offset;
        while offset > 0 {
            if pos >= s.len() {
                return None;
            }
            pos += utf8_len(s[pos]);
            offset -= 1;
        }
        Some(pos.min(s.len()))
    }
}

/// `pointer_to_offset_utf8`: characters (non-continuation bytes) before `pos`.
fn pointer_to_offset(s: &[u8], pos: usize) -> usize {
    s[..pos].iter().filter(|&&b| !is_continuation(b)).count()
}

/// `mb_find_strpos` on UTF-8 bytes.
fn find_strpos(function: &str, h: &[u8], n: &[u8], offset: i64, reverse: bool) -> Result<Option<usize>, Error> {
    let op = offset_to_pointer(h, offset)
        .ok_or_else(|| Error::argument(function, 3, "offset", "must be contained in argument #1 ($haystack)"))?;
    if h.len() < n.len() {
        return Ok(None);
    }
    let found = if !reverse {
        crate::string::find(&h[op..], n).map(|i| i + op)
    } else if offset >= 0 {
        crate::string::rfind(&h[op..], n).map(|i| i + op)
    } else {
        let needle_chars = pointer_to_offset(n, n.len());
        let end = offset_to_pointer(&h[op..], needle_chars as i64).map_or(h.len(), |e| op + e);
        crate::string::rfind(&h[..end], n)
    };
    Ok(found.map(|p| pointer_to_offset(h, p)))
}

/// PHP `mb_strpos($haystack, $needle, $offset)`: character position of the
/// first occurrence at or after `offset`. Matches bytes; positions count
/// lead bytes. `None` is PHP's `false`.
pub fn mb_strpos(haystack: &[u8], needle: &[u8], offset: i64) -> Result<Option<usize>, Error> {
    find_strpos("mb_strpos", haystack, needle, offset, false)
}

/// PHP `mb_strrpos($haystack, $needle, $offset)`: character position of the
/// last occurrence (a negative `offset` limits where the match may start).
pub fn mb_strrpos(haystack: &[u8], needle: &[u8], offset: i64) -> Result<Option<usize>, Error> {
    find_strpos("mb_strrpos", haystack, needle, offset, true)
}

/// Simple case folding for searching (invalid sequences become a byte that
/// cannot occur in UTF-8, as PHP's `BADUTF8` mode).
fn fold_for_search(s: &[u8]) -> Vec<u8> {
    convert_case(s, Case::FoldSimple, SEARCH_MARKER)
}

/// PHP `mb_stripos`: [`mb_strpos`] on simple-case-folded text.
pub fn mb_stripos(haystack: &[u8], needle: &[u8], offset: i64) -> Result<Option<usize>, Error> {
    find_strpos("mb_stripos", &fold_for_search(haystack), &fold_for_search(needle), offset, false)
}

/// PHP `mb_strripos`: [`mb_strrpos`] on simple-case-folded text.
pub fn mb_strripos(haystack: &[u8], needle: &[u8], offset: i64) -> Result<Option<usize>, Error> {
    find_strpos("mb_strripos", &fold_for_search(haystack), &fold_for_search(needle), offset, true)
}

fn strstr_variant(haystack: &[u8], found: Option<usize>, before_needle: bool) -> Option<Vec<u8>> {
    let n = found?;
    Some(if before_needle { get_substr(haystack, 0, n) } else { get_substr(haystack, n, usize::MAX) })
}

/// PHP `mb_strstr($haystack, $needle, $before_needle)`: the part from the
/// first occurrence (or before it), re-encoded. `None` is PHP's `false`.
pub fn mb_strstr(haystack: &[u8], needle: &[u8], before_needle: bool) -> Option<Vec<u8>> {
    let found = find_strpos("mb_strstr", haystack, needle, 0, false).ok().flatten();
    strstr_variant(haystack, found, before_needle)
}

/// PHP `mb_strrchr`: like [`mb_strstr`] from the last occurrence of `needle`.
pub fn mb_strrchr(haystack: &[u8], needle: &[u8], before_needle: bool) -> Option<Vec<u8>> {
    let found = find_strpos("mb_strrchr", haystack, needle, 0, true).ok().flatten();
    strstr_variant(haystack, found, before_needle)
}

/// PHP `mb_stristr`: [`mb_strstr`] matching simple-case-folded text.
pub fn mb_stristr(haystack: &[u8], needle: &[u8], before_needle: bool) -> Option<Vec<u8>> {
    let found =
        find_strpos("mb_stristr", &fold_for_search(haystack), &fold_for_search(needle), 0, false).ok().flatten();
    strstr_variant(haystack, found, before_needle)
}

/// PHP `mb_strrichr`: [`mb_strrchr`] matching simple-case-folded text.
pub fn mb_strrichr(haystack: &[u8], needle: &[u8], before_needle: bool) -> Option<Vec<u8>> {
    let found =
        find_strpos("mb_strrichr", &fold_for_search(haystack), &fold_for_search(needle), 0, true).ok().flatten();
    strstr_variant(haystack, found, before_needle)
}

/// Re-encodes with invalid sequences as the search marker byte.
fn for_search(s: &[u8]) -> Cow<'_, [u8]> {
    if mb_check_encoding(s) {
        return Cow::Borrowed(s);
    }
    let mut out = Vec::with_capacity(s.len());
    for w in decode(s) {
        encode(&mut out, w, SEARCH_MARKER);
    }
    Cow::Owned(out)
}

/// PHP `mb_substr_count($haystack, $needle)`: non-overlapping occurrences;
/// invalid sequences only match invalid sequences.
pub fn mb_substr_count(haystack: &[u8], needle: &[u8]) -> Result<usize, Error> {
    if needle.is_empty() {
        return Err(Error::argument("mb_substr_count", 2, "needle", "must not be empty"));
    }
    let (h, n) = (for_search(haystack), for_search(needle));
    let mut count = 0;
    let mut p = 0;
    while let Some(i) = crate::string::find(&h[p..], &n) {
        count += 1;
        p += i + n.len();
    }
    Ok(count)
}

// ---------------------------------------------------------------------------
// Padding and trimming
// ---------------------------------------------------------------------------

/// PHP `mb_str_pad($string, $length, $pad_string, $pad_type)`: pads to
/// `length` characters. Whole copies of `pad` are copied as bytes, the
/// partial copy is re-encoded.
pub fn mb_str_pad<'a>(s: &'a [u8], length: i64, pad: &[u8], pad_type: Pad) -> Result<Cow<'a, [u8]>, Error> {
    let input_len = mb_strlen(s);
    if length < 0 || (length as u64) <= input_len as u64 {
        return Ok(Cow::Borrowed(s));
    }
    let empty = || Error::argument("mb_str_pad", 3, "pad_string", "must not be empty");
    if pad.is_empty() {
        return Err(empty());
    }
    let pad_len = mb_strlen(pad);
    if pad_len == 0 {
        return Err(empty());
    }
    let (left, right) = pad_type.split(length as usize - input_len);
    let mut out = Vec::new();
    for _ in 0..left / pad_len {
        out.extend_from_slice(pad);
    }
    out.extend_from_slice(&get_substr(pad, 0, left % pad_len));
    out.extend_from_slice(s);
    for _ in 0..right / pad_len {
        out.extend_from_slice(pad);
    }
    out.extend_from_slice(&get_substr(pad, 0, right % pad_len));
    Ok(Cow::Owned(out))
}

/// `mb_trim`'s default characters: Unicode white space and NUL.
pub const MB_TRIM_CHARACTERS: &[u32] = &[
    0x20, 0x0C, 0x0A, 0x0D, 0x09, 0x0B, 0x00, 0xA0, 0x1680, 0x2000, 0x2001, 0x2002, 0x2003, 0x2004, 0x2005, 0x2006,
    0x2007, 0x2008, 0x2009, 0x200A, 0x2028, 0x2029, 0x202F, 0x205F, 0x3000, 0x85, 0x180E,
];

fn trim_mode<'a>(s: &'a [u8], characters: Option<&[u8]>, left_mode: bool, right_mode: bool) -> Cow<'a, [u8]> {
    let set: Vec<u32> = match characters {
        None => MB_TRIM_CHARACTERS.to_vec(),
        Some([]) => return Cow::Borrowed(s),
        Some(c) => decode(c).collect(),
    };
    let (mut left, mut right, mut total) = (0usize, 0usize, 0usize);
    let mut ltrim = left_mode;
    for w in decode(s) {
        total += 1;
        if set.contains(&w) {
            if ltrim {
                left += 1;
            }
            if right_mode {
                right += 1;
            }
        } else {
            ltrim = false;
            if right_mode {
                right = 0;
            }
        }
    }
    if left == 0 && right == 0 {
        return Cow::Borrowed(s);
    }
    Cow::Owned(get_substr(s, left, total.saturating_sub(left + right)))
}

/// PHP `mb_trim($string, $characters)`: strips the characters of
/// `characters` (each code point; `None` for PHP's default, Unicode white
/// space) from both ends. When something is stripped, the rest is
/// re-encoded (invalid sequences become `?`); an invalid sequence in
/// `characters` strips invalid sequences.
pub fn mb_trim<'a>(s: &'a [u8], characters: Option<&[u8]>) -> Cow<'a, [u8]> {
    trim_mode(s, characters, true, true)
}

/// PHP `mb_ltrim`: [`mb_trim`] at the start only.
pub fn mb_ltrim<'a>(s: &'a [u8], characters: Option<&[u8]>) -> Cow<'a, [u8]> {
    trim_mode(s, characters, true, false)
}

/// PHP `mb_rtrim`: [`mb_trim`] at the end only.
pub fn mb_rtrim<'a>(s: &'a [u8], characters: Option<&[u8]>) -> Cow<'a, [u8]> {
    trim_mode(s, characters, false, true)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn counts_invalid_sequences() {
        assert_eq!(mb_strlen("héllo".as_bytes()), 5);
        assert_eq!(mb_strlen(b"\xE2\x82"), 1);
        assert_eq!(mb_strlen(b"\xF0\x9F\x98\x80\x80"), 2);
    }

    #[test]
    fn cases_like_php() {
        assert_eq!(mb_strtolower(b"A\xFFB\xE2\x82"), b"a?b?");
        assert_eq!(mb_strtolower("ΣΑΣ.Σ".as_bytes()), "σασ.ς".as_bytes());
        assert_eq!(mb_strtoupper("ßﬃŉ".as_bytes()), "SSFFIʼN".as_bytes());
        assert_eq!(mb_convert_case("ǅ ǆ ǄA".as_bytes(), Case::Title), "ǅ ǅ ǅa".as_bytes());
    }

    #[test]
    fn substr_and_split() {
        assert_eq!(mb_substr(b"a\xFFbc", 1, Some(2)).unwrap(), b"?b");
        assert_eq!(mb_str_split(b"\xE2\x82a\xF0", 1).unwrap(), vec![&b"\xE2\x82a"[..], b"\xF0"]);
        assert_eq!(mb_trim("\u{3000} a\u{FF} ".as_bytes(), None).as_ref(), "a\u{FF}".as_bytes());
    }
}
