/** Prism.js language components (no types published for these paths) */
declare module 'prismjs/components/prism-dart' {}
declare module 'prismjs/components/prism-swift' {}
declare module 'prismjs/components/prism-kotlin' {}
declare module 'prismjs/components/prism-php' {}
declare module 'prismjs/components/prism-python' {}
declare module 'prismjs/components/prism-ruby' {}
declare module 'prismjs/components/prism-go' {}
declare module 'prismjs/components/prism-csharp' {}
declare module 'prismjs/components/prism-markup' {}
declare module 'prismjs/components/prism-markup-templating' {}
declare module 'prismjs/components/prism-hcl' {}
declare module 'prismjs/components/prism-rust' {}
declare module 'prismjs/components/prism-graphql' {}
declare module 'prismjs/components/prism-http' {}
declare module 'prismjs/components/prism-groovy' {}
declare module 'prismjs/components/prism-docker' {}
declare module 'prismjs/components/prism-css' {}
declare module 'prismjs/components/prism-yaml' {}
declare module 'prismjs/components/prism-toml' {}
declare module 'prismjs/components/prism-c' {}
declare module 'prismjs/components/prism-cpp' {}
declare module 'prismjs/components/prism-markdown' {}
declare module 'prismjs/components/prism-diff' {}
