[package]
name = "utopia-system"
description = "Environment variables and machine facts: OS, architecture, CPU, memory, disk, IO and network."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
indexmap.workspace = true
php-std.workspace = true
rustix.workspace = true
thiserror.workspace = true
tokio = { workspace = true, features = ["time"] }

[package.metadata.utopia]
php-sync = "b8ab7b89e775bfeeb49837aa3f26581043abd2db"
