name: AI Moderator

on:
  issues:
    types: [opened, edited]
  issue_comment:
    types: [created, edited]
  pull_request:
    types: [opened, edited]
  pull_request_review:
    types: [submitted, edited]
  pull_request_review_comment:
    types: [created, edited]
  discussion:
    types: [created, edited]
  discussion_comment:
    types: [created, edited]

permissions:
  models: read
  issues: write
  pull-requests: write
  discussions: write

jobs:
  moderate:
    runs-on: ubuntu-latest
    steps:
      - name: AI Moderator
        uses: github/ai-moderator@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
