name: Auto Label Issue

on:
  issues:
    types: [opened]

permissions:
  issues: write
  contents: read

jobs:
  labeler:
    runs-on: ubuntu-latest
    steps:
      - name: Issue Labeler
        uses: github/issue-labeler@v3.4
        with:
          configuration-path: .github/labeler.yml
          enable-versioned-regex: false
          include-title: 1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
