name: Unit Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Unit Tests
    runs-on: runs-on=${{ github.run_id }}/runner=4cpu-linux-x64/family=c7i/spot=price-capacity-optimized/retry=when-interrupted/extras=otel
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install Dependencies
        run: bun install --frozen-lockfile

      - name: Unit Tests
        run: bun run test
        env:
          VITE_APPWRITE_ENDPOINT: http://appwrite.test/v1
          PUBLIC_APPWRITE_ENDPOINT: http://appwrite.test/v1

      - name: Build
        run: bun run build
