<?php

namespace Utopia\Query\Tests\Schema;

use PHPUnit\Framework\TestCase;
use Utopia\Query\Builder\PostgreSQL as PgBuilder;
use Utopia\Query\Exception\ValidationException;
use Utopia\Query\Query;
use Utopia\Query\Schema\Column\PostgreSQL as PostgreSQLColumn;
use Utopia\Query\Schema\ColumnType;
use Utopia\Query\Schema\Feature\ColumnComments;
use Utopia\Query\Schema\Feature\CreatePartition;
use Utopia\Query\Schema\Feature\DropPartition;
use Utopia\Query\Schema\Feature\ForeignKeys;
use Utopia\Query\Schema\Feature\Procedures;
use Utopia\Query\Schema\Feature\Sequences;
use Utopia\Query\Schema\Feature\TableComments;
use Utopia\Query\Schema\Feature\Triggers;
use Utopia\Query\Schema\Feature\Types;
use Utopia\Query\Schema\ForeignKeyAction;
use Utopia\Query\Schema\Index;
use Utopia\Query\Schema\IndexType;
use Utopia\Query\Schema\ParameterDirection;
use Utopia\Query\Schema\PostgreSQL as Schema;
use Utopia\Query\Schema\TriggerEvent;
use Utopia\Query\Schema\TriggerTiming;
use Utopia\Query\Tests\AssertsBindingCount;

class PostgreSQLTest extends TestCase
{
    use AssertsBindingCount;

    public function testImplementsForeignKeys(): void
    {
        $this->assertInstanceOf(ForeignKeys::class, new Schema());
    }

    public function testImplementsProcedures(): void
    {
        $this->assertInstanceOf(Procedures::class, new Schema());
    }

    public function testImplementsTriggers(): void
    {
        $this->assertInstanceOf(Triggers::class, new Schema());
    }

    public function testCreateTableBasic(): void
    {
        $schema = new Schema();
        $result = $schema->table('users')
            ->id()
            ->string('name', 255)
            ->string('email', 255)->unique()
            ->create();
        $this->assertBindingCount($result);

        $this->assertSame('CREATE TABLE "users" ("id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, "name" VARCHAR(255) NOT NULL, "email" VARCHAR(255) NOT NULL, PRIMARY KEY ("id"), UNIQUE ("email"))', $result->query);
    }

    public function testCreateTableColumnTypes(): void
    {
        $schema = new Schema();
        $result = $schema->table('test_types')
            ->integer('int_col')
            ->bigInteger('big_col')
            ->float('float_col')
            ->boolean('bool_col')
            ->text('text_col')
            ->datetime('dt_col', 3)
            ->timestamp('ts_col', 6)
            ->json('json_col')
            ->binary('bin_col')
            ->enum('status', ['active', 'inactive'])
            ->create();
        $this->assertBindingCount($result);

        $this->assertSame('CREATE TABLE "test_types" ("int_col" INTEGER NOT NULL, "big_col" BIGINT NOT NULL, "float_col" DOUBLE PRECISION NOT NULL, "bool_col" BOOLEAN NOT NULL, "text_col" TEXT NOT NULL, "dt_col" TIMESTAMP(3) NOT NULL, "ts_col" TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL, "json_col" JSONB NOT NULL, "bin_col" BYTEA NOT NULL, "status" TEXT NOT NULL CHECK ("status" IN (\'active\', \'inactive\')))', $result->query);
    }

    public function testCreateTableSpatialTypes(): void
    {
        $schema = new Schema();
        $result = $schema->table('locations')
            ->id()
            ->point('coords', 4326)
            ->linestring('path')
            ->polygon('area')
            ->create();
        $this->assertBindingCount($result);

        $this->assertSame('CREATE TABLE "locations" ("id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, "coords" GEOMETRY(POINT, 4326) NOT NULL, "path" GEOMETRY(LINESTRING, 4326) NOT NULL, "area" GEOMETRY(POLYGON, 4326) NOT NULL, PRIMARY KEY ("id"))', $result->query);
    }

    public function testCreateTableVectorType(): void
    {
        $schema = new Schema();
        $result = $schema->table('embeddings')
            ->id()
            ->vector('embedding', 128)
            ->create();
        $this->assertBindingCount($result);

        $this->assertSame('CREATE TABLE "embeddings" ("id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, "embedding" VECTOR(128) NOT NULL, PRIMARY KEY ("id"))', $result->query);
    }

    public function testCreateTableUnsignedIgnored(): void
    {
        $schema = new Schema();
        $result = $schema->table('t')
            ->integer('age')->unsigned()
            ->create();
        $this->assertBindingCount($result);

        $this->assertStringNotContainsString('UNSIGNED', $result->query);
        $this->assertSame('CREATE TABLE "t" ("age" INTEGER NOT NULL)', $result->query);
    }

    public function testColumnCollationIsEmittedAndQuoted(): void
    {
        $result = new Schema()->table('t')
            ->string('name')->collation('C')
            ->create();

        $this->assertSame('CREATE TABLE "t" ("name" VARCHAR(255) COLLATE "C" NOT NULL)', $result->query);
    }

    public function testColumnDoesNotExposeInlineComment(): void
    {
        // PostgreSQL cannot inline a comment in CREATE TABLE; it needs a
        // separate COMMENT ON statement, which commentOnColumn() emits.
        $column = new Schema()->table('t')->string('name');

        $this->assertNotContains('comment', \get_class_methods($column));
        $this->assertStringContainsString(
            'COMMENT ON COLUMN',
            new Schema()->commentOnColumn('t', 'name', 'User display name')->query
        );
    }

    public function testAutoIncrementUsesIdentity(): void
    {
        $schema = new Schema();
        $result = $schema->table('t')
            ->id()
            ->create();
        $this->assertBindingCount($result);

        $this->assertSame('CREATE TABLE "t" ("id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, PRIMARY KEY ("id"))', $result->query);
        $this->assertStringNotContainsString('AUTO_INCREMENT', $result->query);
    }

    public function testDropIndexNoOnTable(): void
    {
        $schema = new Schema();
        $result = $schema->dropIndex('users', 'idx_email');

        $this->assertSame('DROP INDEX "idx_email"', $result->query);
    }

    public function testCreateIndexWithGin(): void
    {
        $schema = new Schema();
        $result = $schema->createIndex('documents', 'idx_content_gin', ['content'], method: 'gin', operatorClass: 'gin_trgm_ops');

        $this->assertSame(
            'CREATE INDEX "idx_content_gin" ON "documents" USING GIN ("content" gin_trgm_ops)',
            $result->query
        );
    }

    public function testCreateIndexWithHnsw(): void
    {
        $schema = new Schema();
        $result = $schema->createIndex('embeddings', 'idx_embedding_hnsw', ['embedding'], method: 'hnsw', operatorClass: 'vector_cosine_ops');

        $this->assertSame(
            'CREATE INDEX "idx_embedding_hnsw" ON "embeddings" USING HNSW ("embedding" vector_cosine_ops)',
            $result->query
        );
    }

    public function testCreateIndexWithGist(): void
    {
        $schema = new Schema();
        $result = $schema->createIndex('locations', 'idx_coords_gist', ['coords'], method: 'gist');

        $this->assertSame(
            'CREATE INDEX "idx_coords_gist" ON "locations" USING GIST ("coords")',
            $result->query
        );
    }

    public function testCreateProcedureUsesFunction(): void
    {
        $schema = new Schema();
        $result = $schema->createProcedure(
            'update_stats',
            params: [[ParameterDirection::In, 'user_id', 'INT'], [ParameterDirection::Out, 'total', 'INT']],
            body: 'SELECT COUNT(*) INTO total FROM orders WHERE orders.user_id = user_id;'
        );

        $this->assertSame('CREATE FUNCTION "update_stats"(IN "user_id" INT, OUT "total" INT) RETURNS VOID LANGUAGE plpgsql AS $$ BEGIN SELECT COUNT(*) INTO total FROM orders WHERE orders.user_id = user_id; END; $$', $result->query);
        $this->assertStringNotContainsString('CREATE PROCEDURE', $result->query);
    }

    public function testDropProcedureUsesFunction(): void
    {
        $schema = new Schema();
        $result = $schema->dropProcedure('update_stats');

        $this->assertSame('DROP FUNCTION "update_stats"()', $result->query);
    }

    public function testCreateTriggerUsesExecuteFunction(): void
    {
        $schema = new Schema();
        $result = $schema->createTrigger(
            'trg_updated_at',
            'users',
            timing: TriggerTiming::Before,
            event: TriggerEvent::Update,
            body: 'NEW.updated_at = NOW();'
        );

        $this->assertSame('CREATE FUNCTION "trg_updated_at_func"() RETURNS TRIGGER LANGUAGE plpgsql AS $$ BEGIN NEW.updated_at = NOW(); RETURN NEW; END; $$; CREATE TRIGGER "trg_updated_at" BEFORE UPDATE ON "users" FOR EACH ROW EXECUTE FUNCTION "trg_updated_at_func"()', $result->query);
        $this->assertStringNotContainsString('BEGIN SET', $result->query);
    }

    public function testDropForeignKeyUsesConstraint(): void
    {
        $schema = new Schema();
        $result = $schema->dropForeignKey('orders', 'fk_user');

        $this->assertSame(
            'ALTER TABLE "orders" DROP CONSTRAINT "fk_user"',
            $result->query
        );
    }

    public function testAlterModifyUsesAlterColumn(): void
    {
        $schema = new Schema();
        $result = $schema->table('users')
            ->modifyColumn('name', ColumnType::String, 500)
            ->alter();
        $this->assertBindingCount($result);

        $this->assertSame('ALTER TABLE "users" ALTER COLUMN "name" TYPE VARCHAR(500)', $result->query);
    }

    public function testAlterAddIndexUsesCreateIndex(): void
    {
        $schema = new Schema();
        $result = $schema->table('users')
            ->addIndex('idx_email', ['email'])
            ->alter();
        $this->assertBindingCount($result);

        $this->assertStringNotContainsString('ADD INDEX', $result->query);
        $this->assertSame('CREATE INDEX "idx_email" ON "users" ("email")', $result->query);
    }

    public function testAlterDropIndexIsStandalone(): void
    {
        $schema = new Schema();
        $result = $schema->table('users')
            ->dropIndex('idx_email')
            ->alter();
        $this->assertBindingCount($result);

        $this->assertSame('DROP INDEX "idx_email"', $result->query);
    }

    public function testAlterColumnAndIndexSeparateStatements(): void
    {
        $schema = new Schema();
        $result = $schema->table('users')
            ->addColumn('score', ColumnType::Integer)
            ->addIndex('idx_score', ['score'])
            ->alter();
        $this->assertBindingCount($result);

        $this->assertSame('ALTER TABLE "users" ADD COLUMN "score" INTEGER NOT NULL; CREATE INDEX "idx_score" ON "users" ("score")', $result->query);
    }

    public function testAlterDropForeignKeyUsesConstraint(): void
    {
        $schema = new Schema();
        $result = $schema->table('orders')
            ->dropForeignKey('fk_old')
            ->alter();
        $this->assertBindingCount($result);

        $this->assertSame('ALTER TABLE "orders" DROP CONSTRAINT "fk_old"', $result->query);
    }

    public function testCreateExtension(): void
    {
        $schema = new Schema();
        $result = $schema->createExtension('vector');

        $this->assertSame('CREATE EXTENSION IF NOT EXISTS "vector"', $result->query);
    }

    public function testDropExtension(): void
    {
        $schema = new Schema();
        $result = $schema->dropExtension('vector');

        $this->assertSame('DROP EXTENSION IF EXISTS "vector"', $result->query);
    }

    public function testCreateView(): void
    {
        $schema = new Schema();
        $builder = new PgBuilder()->from('users')->filter([Query::equal('active', [true])]);
        $result = $schema->createView('active_users', $builder);

        $this->assertSame(
            'CREATE VIEW "active_users" AS SELECT * FROM "users" WHERE "active" IN (?)',
            $result->query
        );
    }

    public function testDropView(): void
    {
        $schema = new Schema();
        $result = $schema->dropView('active_users');

        $this->assertSame('DROP VIEW "active_users"', $result->query);
    }

    public function testDropTable(): void
    {
        $schema = new Schema();
        $result = $schema->table('users')->drop();
        $this->assertBindingCount($result);

        $this->assertSame('DROP TABLE "users"', $result->query);
    }

    public function testTruncateTable(): void
    {
        $schema = new Schema();
        $result = $schema->table('users')->truncate();
        $this->assertBindingCount($result);

        $this->assertSame('TRUNCATE TABLE "users"', $result->query);
    }

    public function testRenameTableUsesAlterTable(): void
    {
        $schema = new Schema();
        $result = $schema->table('users')->rename('members');
        $this->assertBindingCount($result);

        $this->assertSame('ALTER TABLE "users" RENAME TO "members"', $result->query);
    }

    public function testDropIfExists(): void
    {
        $schema = new Schema();
        $result = $schema->table('users')->dropIfExists();

        $this->assertSame('DROP TABLE IF EXISTS "users"', $result->query);
    }

    public function testCreateOrReplaceView(): void
    {
        $schema = new Schema();
        $builder = new PgBuilder()->from('users');
        $result = $schema->createOrReplaceView('all_users', $builder);

        $this->assertStringStartsWith('CREATE OR REPLACE VIEW', $result->query);
    }

    public function testCreateTableWithMultiplePrimaryKeys(): void
    {
        $schema = new Schema();
        $result = $schema->table('order_items')
            ->integer('order_id')->primary()
            ->integer('product_id')->primary()
            ->create();
        $this->assertBindingCount($result);

        $this->assertSame('CREATE TABLE "order_items" ("order_id" INTEGER NOT NULL, "product_id" INTEGER NOT NULL, PRIMARY KEY ("order_id", "product_id"))', $result->query);
    }

    public function testCreateTableWithCompositePrimaryKey(): void
    {
        $schema = new Schema();
        $result = $schema->table('order_items')
            ->integer('order_id')
            ->integer('product_id')
            ->integer('quantity')
            ->primary(['order_id', 'product_id'])
            ->create();
        $this->assertBindingCount($result);

        $this->assertSame('CREATE TABLE "order_items" ("order_id" INTEGER NOT NULL, "product_id" INTEGER NOT NULL, "quantity" INTEGER NOT NULL, PRIMARY KEY ("order_id", "product_id"))', $result->query);
    }

    public function testCreateTableRejectsMixedColumnAndTablePrimary(): void
    {
        $schema = new Schema();

        $this->expectException(ValidationException::class);
        $this->expectExceptionMessage('Cannot combine column-level primary() with Table::primary() composite key.');

        $schema->table('order_items')
            ->integer('order_id')->primary()
            ->integer('product_id')
            ->primary(['order_id', 'product_id'])
            ->create();
    }

    public function testCreateTableWithDefaultNull(): void
    {
        $schema = new Schema();
        $result = $schema->table('t')
            ->string('name')->nullable()->default(null)
            ->create();
        $this->assertBindingCount($result);

        $this->assertSame('CREATE TABLE "t" ("name" VARCHAR(255) NULL DEFAULT NULL)', $result->query);
    }

    public function testAlterAddMultipleColumns(): void
    {
        $schema = new Schema();
        $result = $schema->table('users')
            ->addColumn('first_name', ColumnType::String, 100)
            ->addColumn('last_name', ColumnType::String, 100)
            ->dropColumn('name')
            ->alter();
        $this->assertBindingCount($result);

        $this->assertSame('ALTER TABLE "users" ADD COLUMN "first_name" VARCHAR(100) NOT NULL, ADD COLUMN "last_name" VARCHAR(100) NOT NULL, DROP COLUMN "name"', $result->query);
    }

    public function testAlterAddForeignKey(): void
    {
        $schema = new Schema();
        $result = $schema->table('orders')
            ->addForeignKey('user_id')->references('id')->on('users')->onDelete(ForeignKeyAction::Cascade)
            ->alter();
        $this->assertBindingCount($result);

        $this->assertSame('ALTER TABLE "orders" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE', $result->query);
    }

    public function testCreateIndexDefault(): void
    {
        $schema = new Schema();
        $result = $schema->createIndex('users', 'idx_email', ['email']);

        $this->assertSame('CREATE INDEX "idx_email" ON "users" ("email")', $result->query);
    }

    public function testCreateUniqueIndex(): void
    {
        $schema = new Schema();
        $result = $schema->createIndex('users', 'idx_email', ['email'], unique: true);

        $this->assertSame('CREATE UNIQUE INDEX "idx_email" ON "users" ("email")', $result->query);
    }

    public function testCreateIndexMultiColumn(): void
    {
        $schema = new Schema();
        $result = $schema->createIndex('users', 'idx_name', ['first_name', 'last_name']);

        $this->assertSame('CREATE INDEX "idx_name" ON "users" ("first_name", "last_name")', $result->query);
    }

    public function testAlterRenameColumn(): void
    {
        $schema = new Schema();
        $result = $schema->table('users')
            ->renameColumn('bio', 'biography')
            ->alter();
        $this->assertBindingCount($result);

        $this->assertSame('ALTER TABLE "users" RENAME COLUMN "bio" TO "biography"', $result->query);
    }

    public function testCreateTableWithTimestamps(): void
    {
        $schema = new Schema();
        $result = $schema->table('posts')
            ->id()
            ->timestamps()
            ->create();
        $this->assertBindingCount($result);

        $this->assertSame('CREATE TABLE "posts" ("id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, "created_at" TIMESTAMP(3) NOT NULL, "updated_at" TIMESTAMP(3) NOT NULL, PRIMARY KEY ("id"))', $result->query);
    }

    public function testCreateTableWithForeignKey(): void
    {
        $schema = new Schema();
        $result = $schema->table('posts')
            ->id()
            ->foreignKey('user_id')
                ->references('id')->on('users')
                ->onDelete(ForeignKeyAction::Cascade)
            ->create();
        $this->assertBindingCount($result);

        $this->assertSame('CREATE TABLE "posts" ("id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, PRIMARY KEY ("id"), FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE)', $result->query);
    }

    public function testAddForeignKeyStandalone(): void
    {
        $schema = new Schema();
        $result = $schema->addForeignKey('orders', 'fk_user', 'user_id', 'users', 'id', ForeignKeyAction::Cascade, ForeignKeyAction::SetNull);

        $this->assertSame(
            'ALTER TABLE "orders" ADD CONSTRAINT "fk_user" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE ON UPDATE SET NULL',
            $result->query
        );
    }

    public function testDropTriggerFunction(): void
    {
        $schema = new Schema();

        $result = $schema->dropTrigger('trg_old', 'users');

        $this->assertSame(
            'DROP TRIGGER "trg_old" ON "users"; DROP FUNCTION "trg_old_func"()',
            $result->query,
        );
    }

    public function testDropTriggerWithoutTableThrows(): void
    {
        $schema = new Schema();

        $this->expectException(ValidationException::class);
        $this->expectExceptionMessage('PostgreSQL dropTrigger() requires the table name.');

        $schema->dropTrigger('trg_old');
    }

    public function testAlterWithUniqueIndex(): void
    {
        $schema = new Schema();
        $result = $schema->table('users')
            ->addIndex('idx_email', ['email'])
            ->addIndex('idx_name', ['name'])
            ->alter();
        $this->assertBindingCount($result);

        $this->assertSame('CREATE INDEX "idx_email" ON "users" ("email"); CREATE INDEX "idx_name" ON "users" ("name")', $result->query);
    }

    public function testExactCreateTableWithTypes(): void
    {
        $schema = new Schema();
        $result = $schema->table('accounts')
            ->id()
            ->string('username', 50)
            ->boolean('verified')
            ->json('metadata')
            ->create();

        $this->assertSame(
            'CREATE TABLE "accounts" ("id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, "username" VARCHAR(50) NOT NULL, "verified" BOOLEAN NOT NULL, "metadata" JSONB NOT NULL, PRIMARY KEY ("id"))',
            $result->query
        );
        $this->assertSame([], $result->bindings);
        $this->assertBindingCount($result);
    }

    public function testExactAlterTableAddColumn(): void
    {
        $schema = new Schema();
        $result = $schema->table('accounts')
            ->addColumn('bio', ColumnType::Text)->nullable()
            ->alter();

        $this->assertSame(
            'ALTER TABLE "accounts" ADD COLUMN "bio" TEXT NULL',
            $result->query
        );
        $this->assertSame([], $result->bindings);
        $this->assertBindingCount($result);
    }

    public function testExactDropTable(): void
    {
        $schema = new Schema();
        $result = $schema->table('sessions')->drop();

        $this->assertSame('DROP TABLE "sessions"', $result->query);
        $this->assertSame([], $result->bindings);
        $this->assertBindingCount($result);
    }

    public function testImplementsTypes(): void
    {
        $this->assertInstanceOf(Types::class, new Schema());
    }

    public function testImplementsSequences(): void
    {
        $this->assertInstanceOf(Sequences::class, new Schema());
    }

    public function testImplementsTableComments(): void
    {
        $this->assertInstanceOf(TableComments::class, new Schema());
    }

    public function testImplementsColumnComments(): void
    {
        $this->assertInstanceOf(ColumnComments::class, new Schema());
    }

    public function testImplementsCreatePartition(): void
    {
        $this->assertInstanceOf(CreatePartition::class, new Schema());
    }

    public function testImplementsDropPartition(): void
    {
        $this->assertInstanceOf(DropPartition::class, new Schema());
    }

    public function testCreateCollation(): void
    {
        $schema = new Schema();
        $result = $schema->createCollation('ci_collation', ['provider' => 'icu', 'locale' => 'und-u-ks-level1']);

        $this->assertSame(
            "CREATE COLLATION IF NOT EXISTS \"ci_collation\" (provider = 'icu', locale = 'und-u-ks-level1', deterministic = true)",
            $result->query
        );
        $this->assertSame([], $result->bindings);
    }

    public function testCreateCollationNonDeterministic(): void
    {
        $schema = new Schema();
        $result = $schema->createCollation('nd_collation', ['provider' => 'icu'], false);

        $this->assertSame('CREATE COLLATION IF NOT EXISTS "nd_collation" (provider = \'icu\', deterministic = false)', $result->query);
    }

    public function testCreateCollationRejectsInvalidOptionKey(): void
    {
        $this->expectException(ValidationException::class);
        $this->expectExceptionMessage('Invalid collation option key');

        $schema = new Schema();
        $schema->createCollation('bad', ['provider = pg_catalog, invalid_key' => 'icu']);
    }

    public function testCreateCollationRejectsKeyWithSpace(): void
    {
        $this->expectException(ValidationException::class);

        $schema = new Schema();
        $schema->createCollation('bad', ['pro vider' => 'icu']);
    }

    public function testRenameIndex(): void
    {
        $schema = new Schema();
        $result = $schema->renameIndex('users', 'idx_old', 'idx_new');

        $this->assertSame('ALTER INDEX "idx_old" RENAME TO "idx_new"', $result->query);
        $this->assertSame([], $result->bindings);
    }

    public function testCreateDatabase(): void
    {
        $schema = new Schema();
        $result = $schema->createDatabase('my_schema');

        $this->assertSame('CREATE SCHEMA "my_schema"', $result->query);
        $this->assertSame([], $result->bindings);
    }

    public function testDropDatabase(): void
    {
        $schema = new Schema();
        $result = $schema->dropDatabase('my_schema');

        $this->assertSame('DROP SCHEMA IF EXISTS "my_schema" CASCADE', $result->query);
        $this->assertSame([], $result->bindings);
    }

    public function testAnalyzeTable(): void
    {
        $schema = new Schema();
        $result = $schema->analyzeTable('users');

        $this->assertSame('ANALYZE "users"', $result->query);
        $this->assertSame([], $result->bindings);
    }

    public function testAlterColumnType(): void
    {
        $schema = new Schema();
        $result = $schema->alterColumnType('users', 'age', 'BIGINT');

        $this->assertSame('ALTER TABLE "users" ALTER COLUMN "age" TYPE BIGINT', $result->query);
        $this->assertSame([], $result->bindings);
    }

    public function testAlterColumnTypeWithUsing(): void
    {
        $schema = new Schema();
        $result = $schema->alterColumnType('users', 'age', 'INTEGER', '"age"::integer');

        $this->assertSame('ALTER TABLE "users" ALTER COLUMN "age" TYPE INTEGER USING "age"::integer', $result->query);
        $this->assertSame([], $result->bindings);
    }

    public function testAlterColumnNullableDrops(): void
    {
        $schema = new Schema();
        $result = $schema->alterColumnNullable('users', 'location', true);

        $this->assertSame('ALTER TABLE "users" ALTER COLUMN "location" DROP NOT NULL', $result->query);
        $this->assertSame([], $result->bindings);
    }

    public function testAlterColumnNullableSets(): void
    {
        $schema = new Schema();
        $result = $schema->alterColumnNullable('users', 'location', false);

        $this->assertSame('ALTER TABLE "users" ALTER COLUMN "location" SET NOT NULL', $result->query);
        $this->assertSame([], $result->bindings);
    }

    public function testAlterColumnTypeRejectsInjectionInType(): void
    {
        $this->expectException(ValidationException::class);
        $this->expectExceptionMessage('Invalid column type');

        $schema = new Schema();
        $schema->alterColumnType('users', 'age', 'INTEGER; DROP TABLE users');
    }

    public function testAlterColumnTypeRejectsSemicolonInUsing(): void
    {
        $this->expectException(ValidationException::class);
        $this->expectExceptionMessage('Invalid USING expression');

        $schema = new Schema();
        $schema->alterColumnType('users', 'age', 'INTEGER', 'age::integer; DROP TABLE users');
    }

    public function testAlterColumnTypeRejectsLineCommentInUsing(): void
    {
        $this->expectException(ValidationException::class);

        $schema = new Schema();
        $schema->alterColumnType('users', 'age', 'INTEGER', 'age::integer -- trailing');
    }

    public function testAlterColumnTypeRejectsBlockCommentInUsing(): void
    {
        $this->expectException(ValidationException::class);

        $schema = new Schema();
        $schema->alterColumnType('users', 'age', 'INTEGER', 'age::integer /* comment */');
    }

    public function testAlterColumnTypeRejectsOversizedUsing(): void
    {
        $this->expectException(ValidationException::class);
        $this->expectExceptionMessage('1024 character limit');

        $schema = new Schema();
        $schema->alterColumnType('users', 'age', 'INTEGER', \str_repeat('a', 1025));
    }

    public function testAlterColumnTypeAllowsCastExpressionInUsing(): void
    {
        $schema = new Schema();
        $result = $schema->alterColumnType('users', 'age', 'INTEGER', 'CAST("age" AS INTEGER)');

        $this->assertSame('ALTER TABLE "users" ALTER COLUMN "age" TYPE INTEGER USING CAST("age" AS INTEGER)', $result->query);
    }

    public function testCreatePartitionRejectsSemicolon(): void
    {
        $this->expectException(ValidationException::class);
        $this->expectExceptionMessage('Invalid partition expression');

        $schema = new Schema();
        $schema->createPartition('orders', 'orders_bad', "IN ('2024'); DROP TABLE orders");
    }

    public function testCreatePartitionRejectsLineComment(): void
    {
        $this->expectException(ValidationException::class);

        $schema = new Schema();
        $schema->createPartition('orders', 'orders_bad', "IN ('2024') -- bad");
    }

    public function testCreatePartitionRejectsOversizedExpression(): void
    {
        $this->expectException(ValidationException::class);

        $schema = new Schema();
        $schema->createPartition('orders', 'orders_bad', \str_repeat('a', 1025));
    }

    public function testDropIndexConcurrently(): void
    {
        $schema = new Schema();
        $result = $schema->dropIndexConcurrently('idx_email');

        $this->assertSame('DROP INDEX CONCURRENTLY "idx_email"', $result->query);
        $this->assertSame([], $result->bindings);
    }

    public function testCreateType(): void
    {
        $schema = new Schema();
        $result = $schema->createType('mood', ['happy', 'sad', 'neutral']);

        $this->assertSame("CREATE TYPE \"mood\" AS ENUM ('happy', 'sad', 'neutral')", $result->query);
        $this->assertSame([], $result->bindings);
    }

    public function testDropType(): void
    {
        $schema = new Schema();
        $result = $schema->dropType('mood');

        $this->assertSame('DROP TYPE "mood"', $result->query);
        $this->assertSame([], $result->bindings);
    }

    public function testCreateSequence(): void
    {
        $schema = new Schema();
        $result = $schema->createSequence('order_seq', 100, 5);

        $this->assertSame('CREATE SEQUENCE "order_seq" START 100 INCREMENT BY 5', $result->query);
        $this->assertSame([], $result->bindings);
    }

    public function testCreateSequenceDefaults(): void
    {
        $schema = new Schema();
        $result = $schema->createSequence('seq');

        $this->assertSame('CREATE SEQUENCE "seq" START 1 INCREMENT BY 1', $result->query);
    }

    public function testDropSequence(): void
    {
        $schema = new Schema();
        $result = $schema->dropSequence('order_seq');

        $this->assertSame('DROP SEQUENCE "order_seq"', $result->query);
        $this->assertSame([], $result->bindings);
    }

    public function testNextVal(): void
    {
        $schema = new Schema();
        $result = $schema->nextVal('order_seq');

        $this->assertSame("SELECT nextval('order_seq')", $result->query);
        $this->assertSame([], $result->bindings);
    }

    public function testCommentOnTable(): void
    {
        $schema = new Schema();
        $result = $schema->commentOnTable('users', 'Main users table');

        $this->assertSame("COMMENT ON TABLE \"users\" IS 'Main users table'", $result->query);
        $this->assertSame([], $result->bindings);
    }

    public function testCommentOnColumn(): void
    {
        $schema = new Schema();
        $result = $schema->commentOnColumn('users', 'email', 'Primary email address');

        $this->assertSame("COMMENT ON COLUMN \"users\".\"email\" IS 'Primary email address'", $result->query);
        $this->assertSame([], $result->bindings);
    }

    public function testCreatePartition(): void
    {
        $schema = new Schema();
        $result = $schema->createPartition('orders', 'orders_2024', "IN ('2024')");

        $this->assertSame("CREATE TABLE \"orders_2024\" PARTITION OF \"orders\" FOR VALUES IN ('2024')", $result->query);
        $this->assertSame([], $result->bindings);
    }

    public function testDropPartition(): void
    {
        $schema = new Schema();
        $result = $schema->dropPartition('orders', 'orders_2024');

        $this->assertSame('DROP TABLE "orders_2024"', $result->query);
        $this->assertSame([], $result->bindings);
    }

    public function testCreateIndexConcurrently(): void
    {
        $schema = new Schema();
        $result = $schema->createIndex('users', 'idx_email', ['email'], concurrently: true);

        $this->assertSame('CREATE INDEX CONCURRENTLY "idx_email" ON "users" ("email")', $result->query);
        $this->assertSame([], $result->bindings);
    }

    public function testCreateUniqueIndexConcurrently(): void
    {
        $schema = new Schema();
        $result = $schema->createIndex('users', 'idx_email', ['email'], unique: true, concurrently: true);

        $this->assertSame('CREATE UNIQUE INDEX CONCURRENTLY "idx_email" ON "users" ("email")', $result->query);
    }

    public function testCreateIndexInvalidMethodThrows(): void
    {
        $this->expectException(ValidationException::class);

        $schema = new Schema();
        $schema->createIndex('t', 'idx', ['col'], method: 'DROP TABLE;--');
    }

    public function testCreateIndexInvalidOperatorClassThrows(): void
    {
        $this->expectException(ValidationException::class);

        $schema = new Schema();
        $schema->createIndex('t', 'idx', ['col'], operatorClass: 'foo;bar');
    }

    public function testAlterAddColumnAndRenameAndDropCombined(): void
    {
        $schema = new Schema();
        $result = $schema->table('users')
            ->addColumn('phone', ColumnType::String, 20)
            ->renameColumn('bio', 'biography')
            ->dropColumn('old_field')
            ->alter();
        $this->assertBindingCount($result);

        $this->assertSame('ALTER TABLE "users" ADD COLUMN "phone" VARCHAR(20) NOT NULL, RENAME COLUMN "bio" TO "biography", DROP COLUMN "old_field"', $result->query);
    }

    public function testAlterAddForeignKeyWithOnUpdate(): void
    {
        $schema = new Schema();
        $result = $schema->table('orders')
            ->addForeignKey('user_id')
                ->references('id')
                ->on('users')
                ->onDelete(ForeignKeyAction::Cascade)
                ->onUpdate(ForeignKeyAction::SetNull)
            ->alter();
        $this->assertBindingCount($result);

        $this->assertSame('ALTER TABLE "orders" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE ON UPDATE SET NULL', $result->query);
    }

    public function testAlterAddIndexWithMethod(): void
    {
        $schema = new Schema();
        $result = $schema->table('docs')
            ->addIndex('idx_content', ['content'], IndexType::Index, method: 'gin')
            ->alter();
        $this->assertBindingCount($result);

        $this->assertSame('CREATE INDEX "idx_content" ON "docs" USING GIN ("content")', $result->query);
    }

    public function testColumnDefinitionUnsignedIgnored(): void
    {
        $schema = new Schema();
        $result = $schema->table('t')
            ->integer('val')->unsigned()
            ->create();
        $this->assertBindingCount($result);

        $this->assertStringNotContainsString('UNSIGNED', $result->query);
    }

    public function testCreateIfNotExists(): void
    {
        $schema = new Schema();
        $result = $schema->table('users')
            ->id()
            ->string('name')
            ->createIfNotExists();
        $this->assertBindingCount($result);

        $this->assertSame('CREATE TABLE IF NOT EXISTS "users" ("id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, "name" VARCHAR(255) NOT NULL, PRIMARY KEY ("id"))', $result->query);
    }

    public function testCreateTableWithRawColumnDefs(): void
    {
        $schema = new Schema();
        $result = $schema->table('t')
            ->id()
            ->rawColumn('"custom_col" TEXT NOT NULL DEFAULT \'\'')
            ->create();
        $this->assertBindingCount($result);

        $this->assertSame('CREATE TABLE "t" ("id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, "custom_col" TEXT NOT NULL DEFAULT \'\', PRIMARY KEY ("id"))', $result->query);
    }

    public function testCreateTableWithRawIndexDefs(): void
    {
        $schema = new Schema();
        $result = $schema->table('t')
            ->id()
            ->string('name')
            ->rawIndex('INDEX "idx_custom" ("name")')
            ->create();
        $this->assertBindingCount($result);

        $this->assertSame('CREATE TABLE "t" ("id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, "name" VARCHAR(255) NOT NULL, PRIMARY KEY ("id"), INDEX "idx_custom" ("name"))', $result->query);
    }

    public function testCreateTableWithPartitionByRange(): void
    {
        $schema = new Schema();
        $result = $schema->table('events')
            ->id()
            ->datetime('created_at')
            ->partitionByRange('created_at')
            ->create();
        $this->assertBindingCount($result);

        $this->assertSame('CREATE TABLE "events" ("id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, "created_at" TIMESTAMP NOT NULL, PRIMARY KEY ("id")) PARTITION BY RANGE(created_at)', $result->query);
    }

    public function testCreateTableWithPartitionByList(): void
    {
        $schema = new Schema();
        $result = $schema->table('events')
            ->id()
            ->string('region')
            ->partitionByList('region')
            ->create();
        $this->assertBindingCount($result);

        $this->assertSame('CREATE TABLE "events" ("id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, "region" VARCHAR(255) NOT NULL, PRIMARY KEY ("id")) PARTITION BY LIST(region)', $result->query);
    }

    public function testCreateTableWithPartitionByHash(): void
    {
        $schema = new Schema();
        $result = $schema->table('events')
            ->id()
            ->partitionByHash('id')
            ->create();
        $this->assertBindingCount($result);

        $this->assertSame('CREATE TABLE "events" ("id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, PRIMARY KEY ("id")) PARTITION BY HASH(id)', $result->query);
    }

    public function testCreateTableWithPartitionByHashIgnoresCount(): void
    {
        // PostgreSQL does not support `PARTITIONS N` (MySQL-only). The count
        // argument must be silently dropped from the generated DDL.
        $schema = new Schema();
        $result = $schema->table('events')
            ->id()
            ->partitionByHash('id', 4)
            ->create();
        $this->assertBindingCount($result);

        $this->assertSame(
            'CREATE TABLE "events" ("id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, PRIMARY KEY ("id")) PARTITION BY HASH(id)',
            $result->query,
        );
        $this->assertStringNotContainsString('PARTITIONS', $result->query);
    }

    public function testAlterWithForeignKeyOnDeleteAndUpdate(): void
    {
        $schema = new Schema();
        $result = $schema->table('orders')
            ->addForeignKey('user_id')
                ->references('id')->on('users')
                ->onDelete(ForeignKeyAction::Cascade)
                ->onUpdate(ForeignKeyAction::SetNull)
            ->alter();
        $this->assertBindingCount($result);

        $this->assertSame('ALTER TABLE "orders" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE ON UPDATE SET NULL', $result->query);
    }

    public function testCreateIndexWithMethod(): void
    {
        $schema = new Schema();
        $result = $schema->createIndex('users', 'idx_name', ['name'], method: 'btree');
        $this->assertBindingCount($result);

        $this->assertSame('CREATE INDEX "idx_name" ON "users" USING BTREE ("name")', $result->query);
    }

    public function testCompileIndexColumnsWithCollation(): void
    {
        $schema = new Schema();
        $result = $schema->createIndex(
            'users',
            'idx_name',
            ['name'],
            collations: ['name' => 'en_US']
        );
        $this->assertBindingCount($result);

        $this->assertSame('CREATE INDEX "idx_name" ON "users" ("name" COLLATE en_US)', $result->query);
    }

    public function testCompileIndexColumnsWithLength(): void
    {
        $schema = new Schema();
        $result = $schema->createIndex(
            'users',
            'idx_name',
            ['name'],
            lengths: ['name' => 10]
        );
        $this->assertBindingCount($result);

        $this->assertSame('CREATE INDEX "idx_name" ON "users" ("name"(10))', $result->query);
    }

    public function testCompileIndexColumnsWithOrder(): void
    {
        $schema = new Schema();
        $result = $schema->createIndex(
            'users',
            'idx_name',
            ['name'],
            orders: ['name' => 'desc']
        );
        $this->assertBindingCount($result);

        $this->assertSame('CREATE INDEX "idx_name" ON "users" ("name" DESC)', $result->query);
    }

    public function testCompileIndexColumnsWithRawColumns(): void
    {
        $schema = new Schema();
        $result = $schema->createIndex(
            'docs',
            'idx_mixed',
            ['id'],
            rawColumns: ['(data->>\'name\')']
        );
        $this->assertBindingCount($result);

        $this->assertSame('CREATE INDEX "idx_mixed" ON "docs" ("id", (data->>\'name\'))', $result->query);
    }

    public function testCreateIndexRejectsInjectionInCollation(): void
    {
        $this->expectException(ValidationException::class);
        $this->expectExceptionMessage('Invalid collation');

        $schema = new Schema();
        $schema->createIndex(
            'users',
            'idx_name',
            ['name'],
            collations: ['name' => 'en_US; DROP TABLE users'],
        );
    }

    public function testCreateIndexRejectsInjectionInOrder(): void
    {
        $this->expectException(ValidationException::class);
        $this->expectExceptionMessage('Invalid index order');

        $schema = new Schema();
        $schema->createIndex(
            'users',
            'idx_name',
            ['name'],
            orders: ['name' => 'ASC; DROP TABLE users'],
        );
    }

    public function testCreateIndexRejectsNonAscDescOrder(): void
    {
        $this->expectException(ValidationException::class);

        $schema = new Schema();
        $schema->createIndex(
            'users',
            'idx_name',
            ['name'],
            orders: ['name' => 'random'],
        );
    }

    public function testCreateIndexAcceptsPlainCollation(): void
    {
        $schema = new Schema();
        $result = $schema->createIndex(
            'users',
            'idx_name',
            ['name'],
            collations: ['name' => 'en_US'],
        );

        $this->assertSame('CREATE INDEX "idx_name" ON "users" ("name" COLLATE en_US)', $result->query);
    }

    public function testCreateIndexRejectsQuotedCollation(): void
    {
        $this->expectException(ValidationException::class);
        $this->expectExceptionMessage('Invalid collation');

        new Index(
            name: 'idx_name',
            columns: ['name'],
            collations: ['name' => '"en_US"'],
        );
    }

    public function testCreateTriggerRejectsDollarQuoteTerminatorInBody(): void
    {
        $this->expectException(ValidationException::class);
        $this->expectExceptionMessage('dollar-quote terminator');

        $schema = new Schema();
        $schema->createTrigger(
            'my_trigger',
            'users',
            TriggerTiming::Before,
            TriggerEvent::Insert,
            "$$; DROP TABLE users; --",
        );
    }

    public function testCreateProcedureRejectsDollarQuoteTerminatorInBody(): void
    {
        $this->expectException(ValidationException::class);
        $this->expectExceptionMessage('dollar-quote terminator');

        $schema = new Schema();
        $schema->createProcedure(
            'my_proc',
            [[ParameterDirection::In, 'x', 'INT']],
            "$$; DROP TABLE users; --",
        );
    }

    public function testTableAddIndexWithStringType(): void
    {
        $schema = new Schema();
        $result = $schema->table('users')
            ->addIndex('idx_name', ['name'], IndexType::Unique)
            ->alter();
        $this->assertBindingCount($result);

        $this->assertSame('CREATE UNIQUE INDEX "idx_name" ON "users" ("name")', $result->query);
    }

    public function testCreateTableWithSerialColumnEmitsSerial(): void
    {
        $schema = new Schema();
        $result = $schema->table('t')
            ->serial('id')->primary()
            ->create();
        $this->assertBindingCount($result);

        $this->assertSame('CREATE TABLE "t" ("id" SERIAL NOT NULL, PRIMARY KEY ("id"))', $result->query);
        $this->assertStringNotContainsString('GENERATED BY DEFAULT AS IDENTITY', $result->query);
        $this->assertSame('CREATE TABLE "t" ("id" SERIAL NOT NULL, PRIMARY KEY ("id"))', $result->query);
    }

    public function testCreateTableWithBigSerialColumnEmitsBigSerial(): void
    {
        $schema = new Schema();
        $result = $schema->table('t')
            ->bigSerial('id')->primary()
            ->create();
        $this->assertBindingCount($result);

        $this->assertSame('CREATE TABLE "t" ("id" BIGSERIAL NOT NULL, PRIMARY KEY ("id"))', $result->query);
        $this->assertStringNotContainsString('GENERATED BY DEFAULT AS IDENTITY', $result->query);
    }

    public function testCreateTableWithSmallSerialColumnEmitsSmallSerial(): void
    {
        $schema = new Schema();
        $result = $schema->table('t')
            ->smallSerial('id')->primary()
            ->create();
        $this->assertBindingCount($result);

        $this->assertSame('CREATE TABLE "t" ("id" SMALLSERIAL NOT NULL, PRIMARY KEY ("id"))', $result->query);
    }

    public function testReferenceUserDefinedType(): void
    {
        $schema = new Schema();
        $result = $schema->table('surveys')
            ->integer('id')->primary()
            ->string('mood')->userType('mood_type')
            ->create();
        $this->assertBindingCount($result);

        $this->assertSame('CREATE TABLE "surveys" ("id" INTEGER NOT NULL, "mood" "mood_type" NOT NULL, PRIMARY KEY ("id"))', $result->query);
    }

    public function testUserTypeRejectsInvalidIdentifier(): void
    {
        $this->expectException(ValidationException::class);
        $this->expectExceptionMessage('Invalid user-defined type name');

        $bp = new Schema()->table('t');
        $col = new PostgreSQLColumn($bp, 'mood', ColumnType::String);
        $col->userType('bad; DROP TABLE users');
    }

    public function testTinyIntegerColumnMapsToSmallInt(): void
    {
        $schema = new Schema();
        $result = $schema->table('t')
            ->tinyInteger('depth')
            ->create();

        $this->assertSame(
            'CREATE TABLE "t" ("depth" SMALLINT NOT NULL)',
            $result->query,
        );
    }

    public function testSmallIntegerColumn(): void
    {
        $schema = new Schema();
        $result = $schema->table('t')
            ->smallInteger('year')
            ->create();

        $this->assertSame(
            'CREATE TABLE "t" ("year" SMALLINT NOT NULL)',
            $result->query,
        );
    }

    public function testDecimalColumn(): void
    {
        $schema = new Schema();
        $result = $schema->table('orders')
            ->decimal('amount', precision: 18, scale: 3)
            ->decimal('rate', precision: 5, scale: 4)->nullable()
            ->create();

        $this->assertSame(
            'CREATE TABLE "orders" ("amount" DECIMAL(18, 3) NOT NULL, "rate" DECIMAL(5, 4) NULL)',
            $result->query,
        );
    }

    public function testUuidColumn(): void
    {
        $schema = new Schema();
        $result = $schema->table('t')
            ->uuid('id')->primary()
            ->create();

        $this->assertSame(
            'CREATE TABLE "t" ("id" UUID NOT NULL, PRIMARY KEY ("id"))',
            $result->query,
        );
    }

    public function testUuidColumnWithDefaultRaw(): void
    {
        $schema = new Schema();
        $result = $schema->table('t')
            ->uuid('id')->defaultRaw('gen_random_uuid()')->primary()
            ->create();

        $this->assertSame(
            'CREATE TABLE "t" ("id" UUID NOT NULL DEFAULT gen_random_uuid(), PRIMARY KEY ("id"))',
            $result->query,
        );
    }
}
