<?php

use Utopia\Locale\Locale;

$protocol   = $this->getParam('protocol', '');
$domain     = $this->getParam('domain', '');
$api        = $this->getParam('api', '');
$project    = $this->getParam('project', '');
$version    = $this->getParam('version', 'v0.0.0');
$isDev      = $this->getParam('isDev', false);
$litespeed  = $this->getParam('litespeed', true);
$analytics  = $this->getParam('analytics', 'UA-26264668-9');
$env        = $this->getParam('env', '');
$canonical  = $this->getParam('canonical', '');

?>
<!DOCTYPE html><!--
<?= Locale::getText('settings.inspire') ?>

--><html lang="<?= Locale::getText('settings.locale') ?>" class="<?= $this->getParam('class', 'none') ?>  <?= $env ?>">
<head>
    <link rel="manifest" href="/manifest.json">
    <title><?= $this->getParam('title', '') ?></title>
    <meta name="description" content="<?= $this->getParam('description', '') ?>" />
    <link rel="stylesheet" media="all" type="text/css" href="/dist/styles/default-<?= Locale::getText('settings.direction') ?>.css?v=<?= $version ?>" />
    <link rel="icon" type="image/png" href="<?= $this->escape($this->getParam('icon', '')) ?>?v=1" />
    <link href="https://fonts.googleapis.com/css?family=Poppins:100,300,400,500,600" rel="stylesheet">
    <link rel="apple-touch-icon" href="/images/apple.png">
    <link rel="preconnect" href="<?= $api ?>" />
    <?php if (!empty($canonical)): ?>
        <link rel="canonical" href="<?= $canonical ?>" />
    <?php endif ?>
    <?php foreach ($this->getParam('prefetch', []) as $prefetch): ?>
        <link rel="prefetch" href="<?= $this->escape($prefetch) ?>" />
    <?php endforeach ?>
    <base href="/">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=5" />
    <meta name="theme-color" content="#24f4d4">
    <meta property="og:type" content="website" />
    <meta property="og:title" content="<?= $this->getParam('title', '') ?>" />
    <meta property="og:description" content="<?= $this->getParam('description', '') ?>" />
    <meta property="og:image"  content="<?= $protocol ?>://<?= $domain ?>/images/logo.png?v=1" />
    <script>

        (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
            (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
            m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
        })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

        ga('create', '<?= $analytics ?>', 'auto', {});

        var APP_ENV = {
            NAME: '<?= APP_NAME ?>',
            VERSION: '<?= $version ?>',
            PROTOCOL: '<?= $protocol ?>',
            DOMAIN: '<?= $domain ?>',
            HOME: '<?= $this->escape($this->getParam('home')) ?>',
            API: '<?= $api ?>/v1',
            PROJECT: '<?= $project ?>',
            LOCALE: '<?= $this->escape(Locale::getText('settings.locale')) ?>',
            PREFIX: '<?= $this->escape($this->getParam('prefix')) ?>',
            ROLES: <?= json_encode($this->getParam('roles', [])) ?>,
            PAGING_LIMIT: <?= APP_PAGING_LIMIT ?>
        };

        <?php if ($litespeed): ?>
        document.addEventListener("DOMContentLoaded", function() {
            var head      = document.getElementsByTagName('head')[0];
            var script    = document.createElement('script');

            script.type   = 'text/javascript';
            script.async  = true;
            script.src    = '/dist/scripts/app-all.js?v=<?= $version ?>';
            script.onload = function() {
                window.ls.run(window);
            };

            head.appendChild(script);
        });
        <?php endif ?>
    </script>
    <?= $this->exec($this->getParam('head', [])) ?>
</head>

<body>
    <?= $this->exec($this->getParam('header', [])) ?>

    <main data-ls-router data-first-from-server="true" data-acl data-analytics-pageview>
        <?= $this->exec($this->getParam('body', [])) ?>
   </main>

    <div class="loader"></div>

    <div data-cookie-policy="We are using cookies to make this website easier to use."></div>

    <section data-ls-ui-alerts="" class="alerts">
        <ul data-ls-loop="alerts.list" data-ls-as="alert">
            <li>
                <div data-ls-attrs="class={{alert.class}} message">
                    <i class="icon-cancel" data-ls-ui-alerts-delete data-message="{{alert.id}}"></i>
                    <span data-ls-bind="{{alert.text}}"></span>

                    <span data-ls-if="undefined !== {{alert.link}}" style="display: none;">
                        <a data-ls-attrs="href={{alert.link}}" data-ls-ui-alerts-delete data-message="{{alert.id}}">Learn More</a>
                    </span>
                </div>
            </li>
        </ul>
    </section>

    <?= $this->exec($this->getParam('footer', [])) ?>

    <!-- Version <?= VERSION ?> -->
</body>
</html>