<?php

$events = $this->getParam('events', []);
$patterns = [];

foreach ($events as $name => $event) {
    foreach ($event as $key => $value) {
        if (!\str_starts_with($key, '$')) {
            if (!($value['$resource'] ?? false)) {
                $patterns[] = "{$name}.{$key}";
            } else {
                foreach ($value as $key2 => $value2) {
                    if (!\str_starts_with($key2, '$')) {
                        if (!($value2['$resource'] ?? false)) {
                            $patterns[] = "{$key}.{$key2}";
                        }
                    }
                }
            }
        }
    }
}

?>

<div class="cover margin-bottom-large">
    <h1 class="zone xl margin-bottom-large">
        <a data-ls-attrs="href=/console/home?project={{router.params.project}}" class="back text-size-small link-return-animation--start"><i class="icon-left-open"></i> Home</a>
        <br />

        <span>Webhooks</span>
    </h1>
</div>

<div class="zone xl"
    data-service="projects.listWebhooks"
    data-scope="console"
    data-event="load,projects.createWebhook,projects.updateWebhook,projects.deleteWebhook"
    data-name="console-webhooks"
    data-param-project-id="{{router.params.project}}"
    data-success="trigger"
    data-success-param-trigger-events="projects.listWebhooks">

    <div data-ls-if="0 == {{console-webhooks.total}} || undefined == {{console-webhooks.total}}" class="box margin-top margin-bottom">
        <h3 class="margin-bottom-small text-bold">No Webhooks Found</h3>

        <p class="margin-bottom-no">You haven't created any webhooks for your project yet.</p>
    </div>

    <div class="box margin-bottom" data-ls-if="0 != {{console-webhooks.total}}">
        <ul data-ls-loop="console-webhooks.webhooks" data-ls-as="webhook" class="list">
            <li class="clear">
                <a data-ls-attrs="href=/console/webhooks/webhook?project={{router.params.project}}&id={{webhook.$id}}" class="button reverse pull-end margin-end">Manage</a>

                <span data-ls-bind="{{webhook.name}}"></span> &nbsp; (<span data-ls-bind="{{webhook.events.length}}"></span> events)
                <span data-ls-if="false === {{webhook.security}}">
                    &nbsp; <small class="text-danger">(SSL/TLS Disabled)</small>
                </span>
                <div class="margin-top-tiny">
                    <a data-ls-attrs="href={{webhook.url}}" data-ls-bind="{{webhook.url}}" target="_blank" class="text-one-liner"></a>
                </div>
            </li>
        </ul>
    </div>

    <div class="clear">
        <div data-ui-modal class="modal close box sticky-footer" data-button-text="Add Webhook">
            <button type="button" class="close pull-end" data-ui-modal-close=""><i class="icon-cancel"></i></button>

            <h1>Add Webhook</h1>

            <form
                data-analytics
                data-analytics-activity
                data-analytics-event="submit"
                data-analytics-category="console"
                data-analytics-label="Create Project Webhook"
                data-service="projects.createWebhook"
                data-scope="console"
                data-event="submit"
                data-success="alert,trigger,reset"
                data-success-param-alert-text="Created webhook successfully"
                data-success-param-trigger-events="projects.createWebhook"
                data-failure="alert"
                data-failure-param-alert-text="Failed to create webhook"
                data-failure-param-alert-classname="error">

                <input type="hidden" name="projectId" data-ls-bind="{{router.params.project}}" />

                <label for="name">Name</label>
                <input type="text" class="full-width" id="name" name="name" required autocomplete="off" maxlength="128" />

                <label for="url">POST URL</label>
                <input type="url" class="full-width" id="url" name="url" required autocomplete="off" placeholder="https://example.com/callback" />

                <section x-data="events" class="margin-bottom-small">
                    <label>Events</label>
                    <template x-for="(event, index) in events">
                        <div class="row events responsive thin margin-bottom-tiny">
                            <div class="col span-12 margin-bottom-small">
                                <span class="text" x-text="event"></span>
                                <span class="action" @click="removeEvent(index)">
                                    <i class="icon-trash"></i>
                                </span>
                            </div>
                            <input name="events" data-cast-to="array" type="hidden" :value="event"></input>
                        </div>
                    </template>
                    <label>Add event</label>
                    <select x-model="selected" @change="setEvent()">
                        <option value="" selected>---</option>
                        <?php foreach ($patterns as $event): ?>
                            <option value="<?php echo $event; ?>"><?php echo $event; ?></option>
                        <?php endforeach;?>
                    </select>
                    <div x-show="hasResource">
                        <label x-text="'Select ' + resourceName + ' (optional)'"></label>
                        <input type="text" :placeholder="resourceName" x-model="resource">
                        <div class="text-fade text-size-xs margin-top-negative-small margin-bottom">Leave empty for wildcard access</div>
                    </div>
                    <div x-show="hasSubResource">
                        <label x-text="'Select ' + subResourceName + ' (optional)'"></label>
                        <input type="text" :placeholder="subResourceName" x-model="subResource">
                        <div class="text-fade text-size-xs margin-top-negative-small margin-bottom">Leave empty for wildcard access</div>
                    </div>
                    <div x-show="hasAttribute">
                        <label for="subResource">Add Attribute (optional)</label>
                        <select x-model="attribute">
                            <option value="*">Select attribute</option>
                            <template x-for="attr in attributes">
                                <option :value="attr" x-text="attr"></option>
                            </template>
                        </select>
                    </div>
                    <button x-show="selected" type="button" @click="addEvent()">Add Event</button>
                </section>

                <div class="margin-bottom toggle" data-ls-ui-open data-button-aria="Advanced Options">
                    <i class="icon-plus pull-end margin-top-tiny"></i>
                    <i class="icon-minus pull-end margin-top-tiny"></i>

                    <h2 class="margin-bottom">
                        Advanced Options
                        <small class="text-size-small">(optional)</small>
                    </h2>

                    <label data-ls-attrs="for=security-{{task.$id}}" class="margin-bottom-small">
                        <div class="margin-bottom-small text-bold">SSL / TLS (Certificate verification)</div>

                        <input name="security" type="radio" required data-ls-attrs="id=secure-yes" checked="checked" value="1" /> &nbsp; <span>Enabled</span> &nbsp;
                        <input name="security" type="radio" required data-ls-attrs="id=secure-no" value="0" /> &nbsp; <span>Disabled</span> &nbsp;
                    </label>

                    <p class="margin-bottom text-size-small text-fade"><span class="text-red">Warning</span>: Untrusted or self-signed certificates may not be secure.
                        <a href="https://en.wikipedia.org/wiki/Self-signed_certificate" target="_blank" rel="noopener">Learn more<i class="icon-link-ext"></i></a>
                    </p>

                    <label>HTTP Authentication <span class="tooltip" data-tooltip="Use to secure your endpoint from untrusted sources"><i class="icon-question"></i></span> &nbsp;<small>(optional)</small></label>

                    <div class="row responsive thin">
                        <div class="col span-6 margin-bottom">
                            <label for="httpUser">User</label>
                            <input type="text" class="full-width margin-bottom-no" id="httpUser" name="httpUser" autocomplete="off" />
                        </div>
                        <div class="col span-6 margin-bottom">
                            <label for="httpPass">Password</label>
                            <input type="password" data-forms-show-secret class="full-width margin-bottom-no" id="httpPass" name="httpPass" autocomplete="off" />
                        </div>
                    </div>
                </div>

                <footer>
                    <button type="submit">Create</button> &nbsp; <button data-ui-modal-close="" type="button" class="reverse">Cancel</button>
                </footer>
            </form>
        </div>
    </div>
</div>
